/**
 * Curated depth expansions for the topic word lists. These fill each topic
 * list up to 150+ entries with genuinely useful everyday German, beyond
 * what the Goethe A1 Wortliste covers.
 */

import type { WordListEntry } from "./index";

const E = (de: string, en: string, part?: string, plural?: string): WordListEntry => ({
  de,
  en,
  part,
  plural,
});

export const TOPIC_EXTRAS: Record<string, WordListEntry[]> = {
  people: [
    E("der Onkel", "the uncle", "noun m.", "die Onkel"),
    E("die Tante", "the aunt", "noun f.", "die Tanten"),
    E("der Cousin", "the cousin (m.)", "noun m.", "die Cousins"),
    E("die Cousine", "the cousin (f.)", "noun f.", "die Cousinen"),
    E("der Enkel", "the grandson", "noun m.", "die Enkel"),
    E("die Enkelin", "the granddaughter", "noun f.", "die Enkelinnen"),
    E("der Großvater", "the grandfather", "noun m.", "die Großväter"),
    E("die Großmutter", "the grandmother", "noun f.", "die Großmütter"),
    E("die Großeltern", "the grandparents", "noun f. pl."),
    E("das Baby", "the baby", "noun n.", "die Babys"),
    E("der Ehemann", "the husband", "noun m.", "die Ehemänner"),
    E("die Ehefrau", "the wife", "noun f.", "die Ehefrauen"),
    E("der Partner", "the partner (m.)", "noun m.", "die Partner"),
    E("die Partnerin", "the partner (f.)", "noun f.", "die Partnerinnen"),
    E("die Verwandten", "the relatives", "noun pl."),
    E("der Stiefvater", "the stepfather", "noun m.", "die Stiefväter"),
    E("die Stiefmutter", "the stepmother", "noun f.", "die Stiefmütter"),
    E("der Zwilling", "the twin", "noun m.", "die Zwillinge"),
    E("der Mensch", "the human being", "noun m.", "die Menschen"),
    E("der Erwachsene", "the adult", "noun m.", "die Erwachsenen"),
    E("der Jugendliche", "the teenager", "noun m.", "die Jugendlichen"),
    E("der Bekannte", "the acquaintance", "noun m.", "die Bekannten"),
    E("der Gast", "the guest", "noun m.", "die Gäste"),
    E("der Besuch", "the visit", "noun m."),
    E("der Lebensgefährte", "the life partner (m.)", "noun m.", "die Lebensgefährten"),
    E("ledig", "single", "adjective"),
    E("verheiratet", "married", "adjective"),
    E("geschieden", "divorced", "adjective"),
    E("verlobt", "engaged", "adjective"),
    E("die Hochzeit", "the wedding", "noun f.", "die Hochzeiten"),
    E("die Ehe", "the marriage", "noun f.", "die Ehen"),
    E("die Scheidung", "the divorce", "noun f.", "die Scheidungen"),
    E("die Beziehung", "the relationship", "noun f.", "die Beziehungen"),
    E("der Freundeskreis", "the circle of friends", "noun m."),
    E("der Kumpel", "the buddy", "noun m.", "die Kumpel"),
    E("die Mitbewohnerin", "the flatmate (f.)", "noun f.", "die Mitbewohnerinnen"),
    E("der Nachwuchs", "the offspring", "noun m."),
    E("das Familienmitglied", "the family member", "noun n.", "die Familienmitglieder"),
    E("der Familienname", "the surname", "noun m.", "die Familiennamen"),
    E("der Vorname", "the first name", "noun m.", "die Vornamen"),
    E("der Spitzname", "the nickname", "noun m.", "die Spitznamen"),
    E("der Personalausweis", "the ID card", "noun m.", "die Personalausweise"),
    E("der Reisepass", "the passport", "noun m.", "die Reisepässe"),
    E("die Heimat", "the homeland", "noun f."),
    E("der Wohnort", "the place of residence", "noun m.", "die Wohnorte"),
    E("die Herkunft", "the origin", "noun f."),
    E("die Nationalität", "the nationality", "noun f.", "die Nationalitäten"),
    E("der Staatsangehörige", "the national", "noun m."),
    E("das Familienleben", "the family life", "noun n."),
    E("die Jugend", "the youth", "noun f."),
    E("die Kindheit", "the childhood", "noun f."),
    E("der Lebenslauf", "the CV", "noun m.", "die Lebensläufe"),
    E("der Geburtstag", "the birthday", "noun m.", "die Geburtstage"),
    E("die Geburt", "the birth", "noun f.", "die Geburten"),
    E("das Geburtsdatum", "the date of birth", "noun n.", "die Geburtsdaten"),
    E("der Geburtsort", "the birthplace", "noun m."),
    E("der Charakter", "the character", "noun m."),
    E("die Persönlichkeit", "the personality", "noun f."),
    E("das Temperament", "the temperament", "noun n."),
    E("die Stimmung", "the mood", "noun f."),
    E("das Gefühl", "the feeling", "noun n.", "die Gefühle"),
    E("die Laune", "the mood", "noun f."),
    E("glücklich", "happy", "adjective"),
    E("traurig", "sad", "adjective"),
    E("fröhlich", "cheerful", "adjective"),
    E("nervös", "nervous", "adjective"),
    E("ruhig", "calm", "adjective"),
    E("aufgeregt", "excited", "adjective"),
    E("freundlich", "friendly", "adjective"),
    E("nett", "nice", "adjective"),
    E("hilfsbereit", "helpful", "adjective"),
    E("ehrlich", "honest", "adjective"),
    E("höflich", "polite", "adjective"),
    E("sympathisch", "likeable", "adjective"),
    E("schüchtern", "shy", "adjective"),
    E("streng", "strict", "adjective"),
    E("geduldig", "patient", "adjective"),
    E("der Gruß", "the greeting", "noun m.", "die Grüße"),
    E("die Begrüßung", "the welcome", "noun f."),
    E("der Abschied", "the farewell", "noun m."),
    E("sich verabschieden", "to say goodbye", "verb"),
    E("sich vorstellen", "to introduce oneself", "verb"),
    E("kennenlernen", "to get to know", "verb"),
    E("die Begegnung", "the encounter", "noun f.", "die Begegnungen"),
  ],
  home: [
    E("das Apartment", "the apartment", "noun n.", "die Apartments"),
    E("die Badewanne", "the bathtub", "noun f.", "die Badewannen"),
    E("die Dusche", "the shower", "noun f.", "die Duschen"),
    E("das Waschbecken", "the sink", "noun n.", "die Waschbecken"),
    E("die Toilette", "the toilet", "noun f.", "die Toiletten"),
    E("die Decke", "the ceiling; the blanket", "noun f.", "die Decken"),
    E("das Kissen", "the pillow", "noun n.", "die Kissen"),
    E("die Bettdecke", "the duvet", "noun f.", "die Bettdecken"),
    E("das Kopfkissen", "the pillow", "noun n.", "die Kopfkissen"),
    E("das Handtuch", "the towel", "noun n.", "die Handtücher"),
    E("der Vorhang", "the curtain", "noun m.", "die Vorhänge"),
    E("der Teppich", "the carpet", "noun m.", "die Teppiche"),
    E("der Läufer", "the rug", "noun m.", "die Läufer"),
    E("das Regal", "the shelf", "noun n.", "die Regale"),
    E("das Bücherregal", "the bookshelf", "noun n.", "die Bücherregale"),
    E("der Schreibtisch", "the desk", "noun m.", "die Schreibtische"),
    E("das Sofa", "the sofa", "noun n.", "die Sofas"),
    E("der Sessel", "the armchair", "noun m.", "die Sessel"),
    E("die Kommode", "the chest of drawers", "noun f.", "die Kommoden"),
    E("der Kleiderschrank", "the wardrobe", "noun m.", "die Kleiderschränke"),
    E("der Flur", "the hallway", "noun m.", "die Flure"),
    E("der Keller", "the cellar", "noun m.", "die Keller"),
    E("der Dachboden", "the attic", "noun m.", "die Dachböden"),
    E("das Dach", "the roof", "noun n.", "die Dächer"),
    E("die Treppe", "the staircase", "noun f.", "die Treppen"),
    E("der Aufzug", "the lift", "noun m.", "die Aufzüge"),
    E("die Heizung", "the heating", "noun f."),
    E("der Mülleimer", "the bin", "noun m.", "die Mülleimer"),
    E("der Besen", "the broom", "noun m.", "die Besen"),
    E("der Staubsauger", "the vacuum cleaner", "noun m.", "die Staubsauger"),
    E("der Wischmopp", "the mop", "noun m.", "die Wischmopps"),
    E("das Putzmittel", "the cleaning product", "noun n."),
    E("das Geschirr", "the dishes", "noun n."),
    E("der Teller", "the plate", "noun m.", "die Teller"),
    E("die Schüssel", "the bowl", "noun f.", "die Schüsseln"),
    E("die Tasse", "the cup", "noun f.", "die Tassen"),
    E("das Glas", "the glass", "noun n.", "die Gläser"),
    E("die Flasche", "the bottle", "noun f.", "die Flaschen"),
    E("die Pfanne", "the pan", "noun f.", "die Pfannen"),
    E("der Topf", "the pot", "noun m.", "die Töpfe"),
    E("das Besteck", "the cutlery", "noun n."),
    E("die Gabel", "the fork", "noun f.", "die Gabeln"),
    E("das Messer", "the knife", "noun n.", "die Messer"),
    E("der Löffel", "the spoon", "noun m.", "die Löffel"),
    E("der Mietvertrag", "the rental contract", "noun m.", "die Mietverträge"),
    E("die Miete", "the rent", "noun f."),
    E("der Vermieter", "the landlord", "noun m.", "die Vermieter"),
    E("der Mieter", "the tenant", "noun m.", "die Mieter"),
    E("die Nebenkosten", "the ancillary costs", "noun pl."),
    E("die Kaution", "the deposit", "noun f."),
    E("die Einrichtung", "the furnishings", "noun f."),
    E("die Möbel", "the furniture", "noun pl."),
    E("einrichten", "to furnish", "verb"),
    E("umziehen", "to move house", "verb"),
    E("der Umzug", "the move", "noun m.", "die Umzüge"),
    E("die Umzugskartons", "the moving boxes", "noun pl."),
    E("aufräumen", "to tidy up", "verb"),
    E("putzen", "to clean", "verb"),
    E("abstauben", "to dust", "verb"),
    E("wischen", "to wipe", "verb"),
    E("gießen", "to water (plants)", "verb"),
    E("die Pflanze", "the plant", "noun f.", "die Pflanzen"),
    E("die Blumenampel", "the hanging basket", "noun f."),
    E("der Briefkasten", "the mailbox", "noun m.", "die Briefkästen"),
    E("die Klingel", "the doorbell", "noun f.", "die Klingeln"),
    E("das Schloss", "the lock", "noun n.", "die Schlösser"),
    E("der Strom", "the electricity", "noun m."),
    E("das Wasser", "the water supply", "noun n."),
    E("die Mülltonne", "the dustbin", "noun f.", "die Mülltonnen"),
    E("der Müll", "the rubbish", "noun m."),
    E("der Hausmüll", "the household waste", "noun m."),
    E("die Terrasse", "the terrace", "noun f.", "die Terrassen"),
    E("der Innenhof", "the courtyard", "noun m.", "die Innenhöfe"),
    E("die Garage", "the garage", "noun f.", "die Garagen"),
    E("das Carport", "the carport", "noun n."),
    E("gemütlich", "cosy", "adjective"),
    E("hell", "bright", "adjective"),
    E("geräumig", "spacious", "adjective"),
    E("bequem", "comfortable", "adjective"),
    E("modern", "modern", "adjective"),
    E("altmodisch", "old-fashioned", "adjective"),
    E("leer", "empty", "adjective"),
    E("aufgeräumt", "tidy", "adjective"),
    E("unordentlich", "messy", "adjective"),
  ],
  animals: [
    E("das Haustier", "the pet", "noun n.", "die Haustiere"),
    E("der Welpe", "the puppy", "noun m.", "die Welpen"),
    E("das Kätzchen", "the kitten", "noun n.", "die Kätzchen"),
    E("der Hamster", "the hamster", "noun m.", "die Hamster"),
    E("das Meerschweinchen", "the guinea pig", "noun n.", "die Meerschweinchen"),
    E("der Papagei", "the parrot", "noun m.", "die Papageien"),
    E("die Schildkröte", "the turtle", "noun f.", "die Schildkröten"),
    E("das Kaninchen", "the rabbit", "noun n.", "die Kaninchen"),
    E("der Hase", "the hare", "noun m.", "die Hasen"),
    E("der Frosch", "the frog", "noun m.", "die Frösche"),
    E("die Schlange", "the snake", "noun f.", "die Schlangen"),
    E("die Spinne", "the spider", "noun f.", "die Spinnen"),
    E("die Ameise", "the ant", "noun f.", "die Ameisen"),
    E("die Biene", "the bee", "noun f.", "die Bienen"),
    E("die Wespe", "the wasp", "noun f.", "die Wespen"),
    E("der Schmetterling", "the butterfly", "noun m.", "die Schmetterlinge"),
    E("der Käfer", "the beetle", "noun m.", "die Käfer"),
    E("die Mücke", "the mosquito", "noun f.", "die Mücken"),
    E("die Fliege", "the fly", "noun f.", "die Fliegen"),
    E("der Fuchs", "the fox", "noun m.", "die Füchse"),
    E("der Wolf", "the wolf", "noun m.", "die Wölfe"),
    E("der Hirsch", "the deer", "noun m.", "die Hirsche"),
    E("das Reh", "the roe deer", "noun n.", "die Rehe"),
    E("das Eichhörnchen", "the squirrel", "noun n.", "die Eichhörnchen"),
    E("der Igel", "the hedgehog", "noun m.", "die Igel"),
    E("der Dachs", "the badger", "noun m.", "die Dachse"),
    E("der Biber", "the beaver", "noun m.", "die Biber"),
    E("der Pinguin", "the penguin", "noun m.", "die Pinguine"),
    E("der Schwan", "the swan", "noun m.", "die Schwäne"),
    E("die Gans", "the goose", "noun f.", "die Gänse"),
    E("die Taube", "the pigeon", "noun f.", "die Tauben"),
    E("die Möwe", "the seagull", "noun f.", "die Möwen"),
    E("die Eule", "the owl", "noun f.", "die Eulen"),
    E("der Adler", "the eagle", "noun m.", "die Adler"),
    E("der Falke", "the falcon", "noun m.", "die Falken"),
    E("der Storch", "the stork", "noun m.", "die Störche"),
    E("die Krähe", "the crow", "noun f.", "die Krähen"),
    E("der Spatz", "the sparrow", "noun m.", "die Spatzen"),
    E("der Wurm", "the worm", "noun m.", "die Würmer"),
    E("die Schnecke", "the snail", "noun f.", "die Schnecken"),
    E("die Krake", "the octopus", "noun f."),
    E("der Wal", "the whale", "noun m.", "die Wale"),
    E("der Delfin", "the dolphin", "noun m.", "die Delfine"),
    E("der Hai", "the shark", "noun m.", "die Haie"),
    E("der Krebs", "the crab", "noun m.", "die Krebse"),
    E("die Qualle", "the jellyfish", "noun f.", "die Quallen"),
    E("der Tiger", "the tiger", "noun m.", "die Tiger"),
    E("der Löwe", "the lion", "noun m.", "die Löwen"),
    E("der Affe", "the monkey", "noun m.", "die Affen"),
    E("die Giraffe", "the giraffe", "noun f.", "die Giraffen"),
    E("das Zebra", "the zebra", "noun n.", "die Zebras"),
    E("das Känguru", "the kangaroo", "noun n.", "die Kängurus"),
    E("der Bär", "the bear", "noun m.", "die Bären"),
    E("der Elefant", "the elephant", "noun m.", "die Elefanten"),
    E("das Nashorn", "the rhino", "noun n.", "die Nashörner"),
    E("das Nilpferd", "the hippo", "noun n.", "die Nilpferde"),
    E("das Kamel", "the camel", "noun n.", "die Kamele"),
    E("der Zoo", "the zoo", "noun m.", "die Zoos"),
    E("der Tierpark", "the animal park", "noun m."),
    E("die Tierärztin", "the vet (f.)", "noun f."),
    E("der Tierarzt", "the vet (m.)", "noun m."),
    E("das Tier", "the animal", "noun n.", "die Tiere"),
    E("das Fell", "the fur", "noun n."),
    E("die Pfote", "the paw", "noun f.", "die Pfoten"),
    E("der Schwanz", "the tail", "noun m.", "die Schwänze"),
    E("die Feder", "the feather", "noun f.", "die Federn"),
    E("der Schnabel", "the beak", "noun m.", "die Schnäbel"),
    E("die Flügel", "the wings", "noun pl."),
    E("bellen", "to bark", "verb"),
    E("miauen", "to meow", "verb"),
    E("brüllen", "to roar", "verb"),
    E("zwitschern", "to chirp", "verb"),
    E("kriechen", "to crawl", "verb"),
    E("fliegen", "to fly", "verb"),
    E("schwimmen", "to swim", "verb"),
    E("fressen", "to eat (animals)", "verb"),
    E("füttern", "to feed", "verb"),
    E("streicheln", "to stroke", "verb"),
    E("leise", "quiet", "adjective"),
    E("wild", "wild", "adjective"),
    E("zahm", "tame", "adjective"),
    E("gefährlich", "dangerous", "adjective"),
    E("niedlich", "cute", "adjective"),
  ],
  nature: [
    E("die Landschaft", "the landscape", "noun f.", "die Landschaften"),
    E("der Hügel", "the hill", "noun m.", "die Hügel"),
    E("das Tal", "the valley", "noun n.", "die Täler"),
    E("die Insel", "the island", "noun f.", "die Inseln"),
    E("der Strand", "the beach", "noun m.", "die Strände"),
    E("die Küste", "the coast", "noun f.", "die Küsten"),
    E("das Ufer", "the shore", "noun n.", "die Ufer"),
    E("der Felsen", "the rock", "noun m.", "die Felsen"),
    E("der Stein", "the stone", "noun m.", "die Steine"),
    E("der Sand", "the sand", "noun m."),
    E("die Erde", "the earth; the soil", "noun f."),
    E("der Boden", "the ground", "noun m."),
    E("der Himmel", "the sky", "noun m."),
    E("die Wolke", "the cloud", "noun f.", "die Wolken"),
    E("der Nebel", "the fog", "noun m."),
    E("der Regenbogen", "the rainbow", "noun m.", "die Regenbogen"),
    E("der Blitz", "the lightning", "noun m."),
    E("der Donner", "the thunder", "noun m."),
    E("das Gewitter", "the thunderstorm", "noun n.", "die Gewitter"),
    E("der Sturm", "the storm", "noun m.", "die Stürme"),
    E("der Orkan", "the hurricane", "noun m.", "die Orkane"),
    E("der Wirbelsturm", "the tornado", "noun m."),
    E("der Hagel", "the hail", "noun m."),
    E("der Frost", "the frost", "noun m."),
    E("das Eis", "the ice", "noun n."),
    E("die Hitze", "the heat", "noun f."),
    E("die Kälte", "the cold", "noun f."),
    E("die Wärme", "the warmth", "noun f."),
    E("das Klima", "the climate", "noun n."),
    E("die Temperatur", "the temperature", "noun f.", "die Temperaturen"),
    E("das Grad", "the degree", "noun n.", "die Grade"),
    E("die Luft", "the air", "noun f."),
    E("der Sauerstoff", "the oxygen", "noun m."),
    E("der Wald", "the forest", "noun m.", "die Wälder"),
    E("das Holz", "the wood", "noun n."),
    E("die Wiese", "the meadow", "noun f.", "die Wiesen"),
    E("das Feld", "the field", "noun n.", "die Felder"),
    E("der Acker", "the farmland", "noun m."),
    E("der Bauernhof", "the farm", "noun m.", "die Bauernhöfe"),
    E("der Garten", "the garden", "noun m.", "die Gärten"),
    E("der Park", "the park", "noun m.", "die Parks"),
    E("der Nationalpark", "the national park", "noun m."),
    E("der Weg", "the path", "noun m.", "die Wege"),
    E("der Pfad", "the trail", "noun m.", "die Pfade"),
    E("die Quelle", "the spring", "noun f.", "die Quellen"),
    E("der Bach", "the stream", "noun m.", "die Bäche"),
    E("der Fluss", "the river", "noun m.", "die Flüsse"),
    E("der Wasserfall", "the waterfall", "noun m.", "die Wasserfälle"),
    E("der See", "the lake", "noun m.", "die Seen"),
    E("der Teich", "the pond", "noun m.", "die Teiche"),
    E("der Vulkan", "the volcano", "noun m.", "die Vulkane"),
    E("die Höhle", "the cave", "noun f.", "die Höhlen"),
    E("die Wüste", "the desert", "noun f.", "die Wüsten"),
    E("die Steppe", "the steppe", "noun f."),
    E("die Polarregion", "the polar region", "noun f."),
    E("der Gletscher", "the glacier", "noun m.", "die Gletscher"),
    E("der Berggipfel", "the mountain peak", "noun m."),
    E("die Aussicht", "the view", "noun f.", "die Aussichten"),
    E("der Sonnenaufgang", "the sunrise", "noun m.", "die Sonnenaufgänge"),
    E("der Sonnenuntergang", "the sunset", "noun m.", "die Sonnenuntergänge"),
    E("das Mondlicht", "the moonlight", "noun n."),
    E("der Sternenhimmel", "the starry sky", "noun m."),
    E("die Natur", "the nature", "noun f."),
    E("die Umwelt", "the environment", "noun f."),
    E("der Umweltschutz", "the environmental protection", "noun m."),
    E("der Klimawandel", "the climate change", "noun m."),
    E("die Nachhaltigkeit", "the sustainability", "noun f."),
    E("der Müll", "the waste", "noun m."),
    E("die Recycling", "the recycling", "noun f."),
    E("recyceln", "to recycle", "verb"),
    E("sparen", "to save", "verb"),
    E("wachsen", "to grow", "verb"),
    E("blühen", "to bloom", "verb"),
    E("regnen", "to rain", "verb"),
    E("schneien", "to snow", "verb"),
    E("wehen", "to blow (wind)", "verb"),
    E("scheinen", "to shine", "verb"),
    E("trocken", "dry", "adjective"),
    E("feucht", "damp", "adjective"),
    E("heiß", "hot", "adjective"),
    E("kalt", "cold", "adjective"),
    E("mild", "mild", "adjective"),
    E("sonnig", "sunny", "adjective"),
    E("bewölkt", "cloudy", "adjective"),
    E("regnerisch", "rainy", "adjective"),
    E("stürmisch", "stormy", "adjective"),
    E("neblig", "foggy", "adjective"),
    E("grün", "green", "adjective"),
    E("fruchtbar", "fertile", "adjective"),
  ],
  "food-drink": [
    E("die Butter", "the butter", "noun f."),
    E("der Honig", "the honey", "noun m."),
    E("die Marmelade", "the jam", "noun f.", "die Marmeladen"),
    E("die Wurst", "the sausage", "noun f.", "die Würste"),
    E("der Schinken", "the ham", "noun m."),
    E("der Speck", "the bacon", "noun m."),
    E("das Rindfleisch", "the beef", "noun n."),
    E("das Schweinefleisch", "the pork", "noun n."),
    E("das Hähnchen", "the chicken", "noun n.", "die Hähnchen"),
    E("das Öl", "the oil", "noun n."),
    E("der Essig", "the vinegar", "noun m."),
    E("der Pfeffer", "the pepper", "noun m."),
    E("die Zwiebel", "the onion", "noun f.", "die Zwiebeln"),
    E("der Knoblauch", "the garlic", "noun m."),
    E("die Gurke", "the cucumber", "noun f.", "die Gurken"),
    E("der Salat", "the lettuce", "noun m.", "die Salate"),
    E("die Karotte", "the carrot", "noun f.", "die Karotten"),
    E("die Möhre", "the carrot", "noun f.", "die Möhren"),
    E("die Erbse", "the pea", "noun f.", "die Erbsen"),
    E("die Bohne", "the bean", "noun f.", "die Bohnen"),
    E("der Mais", "the corn", "noun m."),
    E("die Paprika", "the bell pepper", "noun f.", "die Paprikas"),
    E("die Zucchini", "the zucchini", "noun f.", "die Zucchini"),
    E("die Aubergine", "the eggplant", "noun f.", "die Auberginen"),
    E("der Pilz", "the mushroom", "noun m.", "die Pilze"),
    E("die Erdbeere", "the strawberry", "noun f.", "die Erdbeeren"),
    E("die Himbeere", "the raspberry", "noun f.", "die Himbeeren"),
    E("die Heidelbeere", "the blueberry", "noun f.", "die Heidelbeeren"),
    E("die Kirsche", "the cherry", "noun f.", "die Kirschen"),
    E("die Pflaume", "the plum", "noun f.", "die Pflaumen"),
    E("die Birne", "the pear", "noun f.", "die Birnen"),
    E("der Pfirsich", "the peach", "noun m.", "die Pfirsiche"),
    E("die Melone", "the melon", "noun f.", "die Melonen"),
    E("die Ananas", "the pineapple", "noun f.", "die Ananas"),
    E("die Zitrone", "the lemon", "noun f.", "die Zitronen"),
    E("die Limette", "the lime", "noun f.", "die Limetten"),
    E("die Nuss", "the nut", "noun f.", "die Nüsse"),
    E("die Mandel", "the almond", "noun f.", "die Mandeln"),
    E("das Mehl", "the flour", "noun n."),
    E("die Hefe", "the yeast", "noun f."),
    E("der Quark", "the quark", "noun m."),
    E("der Joghurt", "the yogurt", "noun m."),
    E("die Sahne", "the cream", "noun f."),
    E("die Schokolade", "the chocolate", "noun f."),
    E("der Bonbon", "the candy", "noun m.", "die Bonbons"),
    E("die Süßigkeit", "the sweet", "noun f.", "die Süßigkeiten"),
    E("die Torte", "the gateau", "noun f.", "die Torten"),
    E("der Keks", "the cookie", "noun m.", "die Kekse"),
    E("der Apfelkuchen", "the apple cake", "noun m."),
    E("das Gebäck", "the pastries", "noun n."),
    E("das Müsli", "the muesli", "noun n."),
    E("die Suppe", "the soup", "noun f.", "die Suppen"),
    E("der Eintopf", "the stew", "noun m."),
    E("die Bratwurst", "the grilled sausage", "noun f."),
    E("das Schnitzel", "the schnitzel", "noun n."),
    E("die Pommes", "the fries", "noun pl."),
    E("die Pizza", "the pizza", "noun f.", "die Pizzen"),
    E("das Brot", "the bread", "noun n."),
    E("das Vollkornbrot", "the whole-grain bread", "noun n."),
    E("das Weißbrot", "the white bread", "noun n."),
    E("die Brezel", "the pretzel", "noun f.", "die Brezeln"),
    E("der Toast", "the toast", "noun m."),
    E("der Apfelsaft", "the apple juice", "noun m."),
    E("der Orangensaft", "the orange juice", "noun m."),
    E("die Limonade", "the lemonade", "noun f."),
    E("der Sekt", "the sparkling wine", "noun m."),
    E("der Wein", "the wine", "noun m."),
    E("das Mineralwasser", "the mineral water", "noun n."),
    E("der Snack", "the snack", "noun m."),
    E("das Mittagessen", "the lunch", "noun n."),
    E("die Mahlzeit", "the meal", "noun f.", "die Mahlzeiten"),
    E("das Rezept", "the recipe", "noun n.", "die Rezepte"),
    E("die Zutat", "the ingredient", "noun f.", "die Zutaten"),
    E("der Geschmack", "the taste", "noun m."),
    E("lecker", "delicious", "adjective"),
    E("süß", "sweet", "adjective"),
    E("salzig", "salty", "adjective"),
    E("sauer", "sour", "adjective"),
    E("bitter", "bitter", "adjective"),
    E("scharf", "spicy", "adjective"),
    E("frisch", "fresh", "adjective"),
    E("gekocht", "boiled", "adjective"),
    E("gebraten", "fried", "adjective"),
    E("roh", "raw", "adjective"),
    E("fettig", "fatty", "adjective"),
    E("mager", "lean", "adjective"),
    E("vegetarisch", "vegetarian", "adjective"),
    E("vegan", "vegan", "adjective"),
    E("einfrieren", "to freeze", "verb"),
    E("schneiden", "to cut", "verb"),
    E("mischen", "to mix", "verb"),
    E("kneten", "to knead", "verb"),
    E("backen", "to bake", "verb"),
    E("braten", "to fry", "verb"),
    E("dünsten", "to steam", "verb"),
    E("würzen", "to season", "verb"),
    E("probieren", "to taste, to try", "verb"),
    E("satt", "full (after eating)", "adjective"),
  ],
  restaurant: [
    E("die Vorspeise", "the starter", "noun f.", "die Vorspeisen"),
    E("die Hauptspeise", "the main course", "noun f."),
    E("das Hauptgericht", "the main dish", "noun n."),
    E("der Nachtisch", "the dessert", "noun m."),
    E("das Dessert", "the dessert", "noun n."),
    E("die Nachspeise", "the dessert", "noun f."),
    E("die Beilage", "the side dish", "noun f.", "die Beilagen"),
    E("das Trinkgeld", "the tip", "noun n."),
    E("die Reservierung", "the reservation", "noun f.", "die Reservierungen"),
    E("die Bestellung", "the order", "noun f.", "die Bestellungen"),
    E("der Tisch", "the table", "noun m.", "die Tische"),
    E("der Fensterplatz", "the window seat", "noun m."),
    E("die Speisekarte", "the menu", "noun f.", "die Speisekarten"),
    E("die Getränkekarte", "the drinks menu", "noun f."),
    E("die Karte", "the menu; the card", "noun f.", "die Karten"),
    E("die Rechnung", "the bill", "noun f.", "die Rechnungen"),
    E("das Menü", "the set menu", "noun n.", "die Menüs"),
    E("das Büfett", "the buffet", "noun n."),
    E("das Frühstücksbüfett", "the breakfast buffet", "noun n."),
    E("der Kellner", "the waiter", "noun m.", "die Kellner"),
    E("die Kellnerin", "the waitress", "noun f.", "die Kellnerinnen"),
    E("der Ober", "the head waiter", "noun m."),
    E("der Koch", "the cook", "noun m.", "die Köche"),
    E("die Köchin", "the cook (f.)", "noun f."),
    E("der Gast", "the guest", "noun m.", "die Gäste"),
    E("der Stammgast", "the regular", "noun m."),
    E("die Küche", "the kitchen", "noun f."),
    E("das Restaurant", "the restaurant", "noun n.", "die Restaurants"),
    E("das Café", "the café", "noun n.", "die Cafés"),
    E("die Bäckerei", "the bakery", "noun f.", "die Bäckereien"),
    E("die Konditorei", "the cake shop", "noun f."),
    E("das Steakhouse", "the steakhouse", "noun n."),
    E("die Imbissbude", "the snack stand", "noun f."),
    E("der Imbiss", "the snack bar", "noun m."),
    E("die Kneipe", "the pub", "noun f."),
    E("die Bar", "the bar", "noun f.", "die Bars"),
    E("das Glas", "the glass", "noun n.", "die Gläser"),
    E("das Weinglas", "the wine glass", "noun n."),
    E("die Tasse", "the cup", "noun f.", "die Tassen"),
    E("die Kaffeetasse", "the coffee cup", "noun f."),
    E("die Tasse Tee", "the cup of tea", "noun f."),
    E("die Kanne", "the pot", "noun f.", "die Kannen"),
    E("die Teekanne", "the teapot", "noun f."),
    E("die Kaffeekanne", "the coffee pot", "noun f."),
    E("die Flasche", "the bottle", "noun f.", "die Flaschen"),
    E("die Serviette", "the napkin", "noun f.", "die Servietten"),
    E("das Besteck", "the cutlery", "noun n."),
    E("die Gabel", "the fork", "noun f.", "die Gabeln"),
    E("das Messer", "the knife", "noun n.", "die Messer"),
    E("der Löffel", "the spoon", "noun m.", "die Löffel"),
    E("der Teelöffel", "the teaspoon", "noun m."),
    E("der Teller", "the plate", "noun m.", "die Teller"),
    E("die Schüssel", "the bowl", "noun f.", "die Schüsseln"),
    E("die Suppenschüssel", "the soup bowl", "noun f."),
    E("die Untertasse", "the saucer", "noun f."),
    E("bestellen", "to order", "verb"),
    E("reservieren", "to reserve", "verb"),
    E("bezahlen", "to pay", "verb"),
    E("zahlen", "to pay", "verb"),
    E("ausgeben", "to treat someone", "verb"),
    E("einladen", "to invite", "verb"),
    E("empfehlen", "to recommend", "verb"),
    E("servieren", "to serve", "verb"),
    E("decken", "to set (the table)", "verb"),
    E("abräumen", "to clear (the table)", "verb"),
    E("kosten", "to cost", "verb"),
    E("schmecken", "to taste", "verb"),
    E("auswählen", "to choose", "verb"),
    E("Prost!", "Cheers!", "interjection"),
    E("Guten Appetit!", "Enjoy your meal!", "interjection"),
    E("Zum Wohl!", "To your health!", "interjection"),
    E("satt", "full", "adjective"),
    E("hungrig", "hungry", "adjective"),
    E("durstig", "thirsty", "adjective"),
    E("voll", "full", "adjective"),
    E("besetzt", "occupied", "adjective"),
    E("frei", "free", "adjective"),
    E("warm", "warm", "adjective"),
    E("kalt", "cold", "adjective"),
    E("frisch", "fresh", "adjective"),
    E("hausgemacht", "homemade", "adjective"),
    E("die Öffnungszeiten", "the opening hours", "noun pl."),
    E("geschlossen", "closed", "adjective"),
    E("geöffnet", "open", "adjective"),
  ],
  "travel-transport": [
    E("das Reisebüro", "the travel agency", "noun n."),
    E("der Reisepass", "the passport", "noun m.", "die Reisepässe"),
    E("das Visum", "the visa", "noun n.", "die Visa"),
    E("das Gepäck", "the luggage", "noun n."),
    E("der Koffer", "the suitcase", "noun m.", "die Koffer"),
    E("der Rucksack", "the backpack", "noun m.", "die Rucksäcke"),
    E("die Reisetasche", "the travel bag", "noun f."),
    E("der Handgepäck", "the hand luggage", "noun m."),
    E("die Fahrkarte", "the ticket", "noun f.", "die Fahrkarten"),
    E("das Ticket", "the ticket", "noun n."),
    E("die Fahrkartenkontrolle", "the ticket control", "noun f."),
    E("der Fahrschein", "the ticket", "noun m."),
    E("die Rückfahrkarte", "the return ticket", "noun f."),
    E("die Fahrkarte erster Klasse", "the first-class ticket", "noun f."),
    E("der Bahnsteig", "the platform", "noun m.", "die Bahnsteige"),
    E("das Gleis", "the track", "noun n.", "die Gleise"),
    E("der Fahrplan", "the timetable", "noun m."),
    E("die Abfahrt", "the departure", "noun f."),
    E("die Ankunft", "the arrival", "noun f."),
    E("die Verspätung", "the delay", "noun f."),
    E("der Anschluss", "the connection", "noun m."),
    E("der Schaffner", "the conductor", "noun m."),
    E("der Lokführer", "the train driver", "noun m."),
    E("das Abteil", "the compartment", "noun n."),
    E("die Schlafwagen", "the sleeper car", "noun m."),
    E("die Bahn", "the railway", "noun f."),
    E("die S-Bahn", "the suburban train", "noun f."),
    E("die Straßenbahn", "the tram", "noun f."),
    E("die U-Bahn", "the underground", "noun f."),
    E("der Autofahrer", "the motorist", "noun m."),
    E("die Autobahn", "the motorway", "noun f.", "die Autobahnen"),
    E("die Tankstelle", "the petrol station", "noun f."),
    E("das Benzin", "the petrol", "noun n."),
    E("der Parkplatz", "the car park", "noun m."),
    E("die Werkstatt", "the garage (repair)", "noun f."),
    E("der Führerschein", "the driving licence", "noun m."),
    E("das Navigationsgerät", "the sat-nav", "noun n."),
    E("das Mietauto", "the rental car", "noun n."),
    E("der Motor", "the engine", "noun m."),
    E("der Reifen", "the tyre", "noun m.", "die Reifen"),
    E("das Rad", "the wheel", "noun n.", "die Räder"),
    E("der Helm", "the helmet", "noun m."),
    E("das Flugticket", "the flight ticket", "noun n."),
    E("das Boarding", "the boarding", "noun n."),
    E("die Bordkarte", "the boarding pass", "noun f."),
    E("das Gate", "the gate", "noun n."),
    E("der Pilot", "the pilot", "noun m."),
    E("die Stewardess", "the flight attendant", "noun f."),
    E("der Flug", "the flight", "noun m.", "die Flüge"),
    E("der Hinflug", "the outbound flight", "noun m."),
    E("der Rückflug", "the return flight", "noun m."),
    E("die Landung", "the landing", "noun f."),
    E("der Start", "the take-off", "noun m."),
    E("die Landebahn", "the runway", "noun f."),
    E("der Zoll", "the customs", "noun m."),
    E("die Kontrolle", "the check", "noun f."),
    E("der Schalter", "the counter", "noun m.", "die Schalter"),
    E("das Hotelzimmer", "the hotel room", "noun n."),
    E("das Einzelzimmer", "the single room", "noun n."),
    E("das Doppelzimmer", "the double room", "noun n."),
    E("die Übernachtung", "the overnight stay", "noun f."),
    E("das Frühstück inklusive", "breakfast included", "phrase"),
    E("die Rezeption", "the reception", "noun f."),
    E("der Hausmeister", "the caretaker", "noun m."),
    E("die Ferienwohnung", "the holiday apartment", "noun f."),
    E("das Ferienhaus", "the holiday house", "noun n."),
    E("der Campingplatz", "the campsite", "noun m."),
    E("das Zelt", "the tent", "noun n."),
    E("der Reiseführer", "the travel guide", "noun m."),
    E("die Sehenswürdigkeit", "the sight", "noun f."),
    E("das Souvenir", "the souvenir", "noun n."),
    E("die Postkarte", "the postcard", "noun f."),
    E("der Ausflug", "the excursion", "noun m.", "die Ausflüge"),
    E("die Rundreise", "the tour", "noun f."),
    E("die Weltreise", "the world trip", "noun f."),
    E("der Urlauber", "the holidaymaker", "noun m."),
    E("der Tourist", "the tourist", "noun m."),
    E("die Reisekrankheit", "the travel sickness", "noun f."),
    E("das Reiseziel", "the destination", "noun n."),
    E("buchen", "to book", "verb"),
    E("stornieren", "to cancel", "verb"),
    E("umbuchen", "to rebook", "verb"),
    E("einchecken", "to check in", "verb"),
    E("auschecken", "to check out", "verb"),
    E("umsteigen", "to change (trains)", "verb"),
    E("anhalten", "to stop", "verb"),
    E("losfahren", "to set off", "verb"),
    E("zurückfahren", "to drive back", "verb"),
    E("übernachten", "to stay overnight", "verb"),
    E("wandern", "to hike", "verb"),
    E("sightseeing machen", "to do sightseeing", "phrase"),
    E("unterwegs", "on the way", "adverb"),
    E("pünktlich", "on time", "adjective"),
    E("verspätet", "delayed", "adjective"),
    E("ausgebucht", "fully booked", "adjective"),
    E("fremd", "foreign", "adjective"),
  ],
  shopping: [
    E("das Kaufhaus", "the department store", "noun n.", "die Kaufhäuser"),
    E("das Einkaufszentrum", "the shopping centre", "noun n."),
    E("der Laden", "the shop", "noun m.", "die Läden"),
    E("die Boutique", "the boutique", "noun f."),
    E("die Bäckerei", "the bakery", "noun f."),
    E("die Metzgerei", "the butcher's", "noun f."),
    E("der Bäcker", "the baker", "noun m."),
    E("der Metzger", "the butcher", "noun m."),
    E("der Gemüsehändler", "the greengrocer", "noun m."),
    E("der Wochenmarkt", "the weekly market", "noun m."),
    E("der Flohmarkt", "the flea market", "noun m."),
    E("der Ausverkauf", "the sale", "noun m."),
    E("das Sonderangebot", "the special offer", "noun n."),
    E("das Schnäppchen", "the bargain", "noun n."),
    E("der Rabatt", "the discount", "noun m."),
    E("die Ermäßigung", "the reduction", "noun f."),
    E("die Quittung", "the receipt", "noun f.", "die Quittungen"),
    E("der Kassenzettel", "the till receipt", "noun m."),
    E("das Kleingeld", "the change", "noun n."),
    E("der Geldschein", "the banknote", "noun m."),
    E("die Münze", "the coin", "noun f.", "die Münzen"),
    E("die Kreditkarte", "the credit card", "noun f."),
    E("die EC-Karte", "the debit card", "noun f."),
    E("die Geldkarte", "the cash card", "noun f."),
    E("die Tüte", "the bag", "noun f.", "die Tüten"),
    E("die Plastiktüte", "the plastic bag", "noun f."),
    E("die Papiertüte", "the paper bag", "noun f."),
    E("der Einkaufswagen", "the trolley", "noun m."),
    E("der Einkaufskorb", "the shopping basket", "noun m."),
    E("das Pfand", "the deposit", "noun n."),
    E("die Flaschenpfand", "the bottle deposit", "noun f."),
    E("das Regal", "the shelf", "noun n.", "die Regale"),
    E("die Kasse", "the checkout", "noun f.", "die Kassen"),
    E("die Schlange", "the queue", "noun f.", "die Schlangen"),
    E("der Verkauf", "the sale", "noun m."),
    E("die Werbung", "the advertising", "noun f."),
    E("das Schaufenster", "the shop window", "noun n."),
    E("das Etikett", "the label", "noun n."),
    E("das Preisschild", "the price tag", "noun n."),
    E("die Größe", "the size", "noun f."),
    E("die Nummer", "the number", "noun f."),
    E("die Ware", "the goods", "noun f."),
    E("das Produkt", "the product", "noun n."),
    E("die Marke", "the brand", "noun f.", "die Marken"),
    E("das Geschäft", "the business", "noun n."),
    E("der Umsatz", "the turnover", "noun m."),
    E("die Reklamation", "the complaint", "noun f."),
    E("der Umtausch", "the exchange", "noun m."),
    E("die Rückgabe", "the return", "noun f."),
    E("die Garantie", "the guarantee", "noun f."),
    E("einkaufen gehen", "to go shopping", "phrase"),
    E("kaufen", "to buy", "verb"),
    E("verkaufen", "to sell", "verb"),
    E("bezahlen", "to pay", "verb"),
    E("zahlen", "to pay", "verb"),
    E("bar zahlen", "to pay cash", "phrase"),
    E("mit Karte zahlen", "to pay by card", "phrase"),
    E("kosten", "to cost", "verb"),
    E("bieten", "to offer", "verb"),
    E("anbieten", "to offer", "verb"),
    E("verhandeln", "to negotiate", "verb"),
    E("reklamieren", "to complain", "verb"),
    E("umtauschen", "to exchange", "verb"),
    E("zurückgeben", "to give back", "verb"),
    E("zurückbringen", "to bring back", "verb"),
    E("verglichen", "compared", "adjective"),
    E("teuer", "expensive", "adjective"),
    E("billig", "cheap", "adjective"),
    E("günstig", "reasonably priced", "adjective"),
    E("preiswert", "good value", "adjective"),
    E("kostenlos", "free", "adjective"),
    E("gratis", "free", "adjective"),
    E("neu", "new", "adjective"),
    E("gebraucht", "used", "adjective"),
    E("ausverkauft", "sold out", "adjective"),
    E("verfügbar", "available", "adjective"),
    E("im Angebot", "on offer", "phrase"),
    E("die Öffnungszeit", "the opening time", "noun f."),
    E("geschlossen", "closed", "adjective"),
    E("geöffnet", "open", "adjective"),
  ],
  "work-education": [
    E("das Vorstellungsgespräch", "the job interview", "noun n."),
    E("die Bewerbung", "the application", "noun f.", "die Bewerbungen"),
    E("der Lebenslauf", "the CV", "noun m."),
    E("das Zeugnis", "the certificate", "noun n.", "die Zeugnisse"),
    E("die Ausbildung", "the training", "noun f."),
    E("der Ausbildungsplatz", "the apprenticeship place", "noun m."),
    E("der Lehrling", "the apprentice", "noun m."),
    E("die Stelle", "the position", "noun f.", "die Stellen"),
    E("der Arbeitsplatz", "the workplace", "noun m."),
    E("der Arbeitsvertrag", "the employment contract", "noun m."),
    E("das Gehalt", "the salary", "noun n."),
    E("der Lohn", "the wage", "noun m."),
    E("die Gehaltserhöhung", "the pay rise", "noun f."),
    E("die Überstunden", "the overtime", "noun pl."),
    E("der Urlaub", "the holiday", "noun m."),
    E("der Urlaubstag", "the holiday day", "noun m."),
    E("der Feiertag", "the public holiday", "noun m."),
    E("die Arbeitszeit", "the working hours", "noun f."),
    E("die Pause", "the break", "noun f.", "die Pausen"),
    E("die Mittagspause", "the lunch break", "noun f."),
    E("der Arbeitskollege", "the work colleague", "noun m."),
    E("die Sekretärin", "the secretary (f.)", "noun f."),
    E("der Manager", "the manager", "noun m."),
    E("der Abteilungsleiter", "the department head", "noun m."),
    E("der Geschäftsführer", "the managing director", "noun m."),
    E("der Kunde", "the customer", "noun m.", "die Kunden"),
    E("die Kundin", "the customer (f.)", "noun f."),
    E("der Lieferant", "the supplier", "noun m."),
    E("die Besprechung", "the meeting", "noun f.", "die Besprechungen"),
    E("die Konferenz", "the conference", "noun f."),
    E("das Projekt", "the project", "noun n."),
    E("der Bericht", "the report", "noun m.", "die Berichte"),
    E("die Präsentation", "the presentation", "noun f."),
    E("der Vortrag", "the talk", "noun m."),
    E("die Aufgabe", "the task", "noun f.", "die Aufgaben"),
    E("die Arbeit", "the work", "noun f."),
    E("die Schicht", "the shift", "noun f.", "die Schichten"),
    E("die Nachtschicht", "the night shift", "noun f."),
    E("die Firma", "the company", "noun f.", "die Firmen"),
    E("das Unternehmen", "the enterprise", "noun n."),
    E("die Abteilung", "the department", "noun f."),
    E("das Büro", "the office", "noun n."),
    E("das Großraumbüro", "the open-plan office", "noun n."),
    E("der Drucker", "the printer", "noun m."),
    E("der Papierkorb", "the wastepaper basket", "noun m."),
    E("der Ordner", "the folder", "noun m."),
    E("die Akte", "the file", "noun f."),
    E("das Dokument", "the document", "noun n."),
    E("die Unterschrift", "the signature", "noun f."),
    E("der Stift", "the pen", "noun m.", "die Stifte"),
    E("der Bleistift", "the pencil", "noun m."),
    E("der Kugelschreiber", "the ballpoint pen", "noun m."),
    E("der Füller", "the fountain pen", "noun m."),
    E("das Heft", "the notebook", "noun n.", "die Hefte"),
    E("der Block", "the pad", "noun m."),
    E("das Papier", "the paper", "noun n."),
    E("das Klassenzimmer", "the classroom", "noun n."),
    E("die Tafel", "the blackboard", "noun f."),
    E("die Kreide", "the chalk", "noun f."),
    E("der Stundenplan", "the timetable", "noun m."),
    E("die Pause", "the break", "noun f."),
    E("die Noten", "the grades", "noun pl."),
    E("die Note", "the grade", "noun f."),
    E("die Prüfung", "the exam", "noun f.", "die Prüfungen"),
    E("die Klausur", "the written exam", "noun f."),
    E("das Abitur", "the A-levels", "noun n."),
    E("die Universität", "the university", "noun f."),
    E("die Hochschule", "the college", "noun f."),
    E("der Professor", "the professor", "noun m."),
    E("die Vorlesung", "the lecture", "noun f."),
    E("das Seminar", "the seminar", "noun n."),
    E("das Studium", "the studies", "noun n."),
    E("der Studiengang", "the degree course", "noun m."),
    E("das Fach", "the subject", "noun n.", "die Fächer"),
    E("der Unterricht", "the lesson", "noun m."),
    E("die Schulbank", "the school desk", "noun f."),
    E("der Schulhof", "the schoolyard", "noun m."),
    E("die Schultasche", "the school bag", "noun f."),
    E("der Ranzen", "the satchel", "noun m."),
    E("arbeiten", "to work", "verb"),
    E("verdienen", "to earn", "verb"),
    E("studieren", "to study", "verb"),
    E("lernen", "to learn", "verb"),
    E("üben", "to practise", "verb"),
    E("wiederholen", "to revise", "verb"),
    E("erklären", "to explain", "verb"),
    E("prüfen", "to test", "verb"),
    E("bestehen", "to pass", "verb"),
    E("durchfallen", "to fail", "verb"),
    E("fleißig", "hard-working", "adjective"),
    E("begabt", "gifted", "adjective"),
    E("erfahren", "experienced", "adjective"),
    E("qualifiziert", "qualified", "adjective"),
    E("beschäftigt", "busy", "adjective"),
    E("arbeitslos", "unemployed", "adjective"),
    E("selbstständig", "self-employed", "adjective"),
  ],
  "health-body": [
    E("das Gesicht", "the face", "noun n.", "die Gesichter"),
    E("die Stirn", "the forehead", "noun f."),
    E("die Wange", "the cheek", "noun f.", "die Wangen"),
    E("das Kinn", "the chin", "noun n."),
    E("der Hals", "the neck", "noun m.", "die Hälse"),
    E("die Schulter", "the shoulder", "noun f.", "die Schultern"),
    E("der Ellbogen", "the elbow", "noun m."),
    E("das Handgelenk", "the wrist", "noun n."),
    E("der Finger", "the finger", "noun m.", "die Finger"),
    E("der Daumen", "the thumb", "noun m."),
    E("der Zeh", "the toe", "noun m.", "die Zehen"),
    E("das Knie", "the knee", "noun n."),
    E("das Schienbein", "the shin", "noun n."),
    E("der Magen", "the stomach", "noun m."),
    E("der Bauch", "the belly", "noun m."),
    E("die Lunge", "the lung", "noun f."),
    E("die Leber", "the liver", "noun f."),
    E("die Niere", "the kidney", "noun f."),
    E("das Gehirn", "the brain", "noun n."),
    E("der Knochen", "the bone", "noun m."),
    E("der Muskel", "the muscle", "noun m."),
    E("die Haut", "the skin", "noun f."),
    E("das Blut", "the blood", "noun n."),
    E("das Haar", "the hair", "noun n."),
    E("der Zahn", "the tooth", "noun m.", "die Zähne"),
    E("der Zahnarzt", "the dentist", "noun m."),
    E("die Zahnpasta", "the toothpaste", "noun f."),
    E("die Zahnbürste", "the toothbrush", "noun f."),
    E("die Zunge", "the tongue", "noun f."),
    E("der Husten", "the cough", "noun m."),
    E("die Erkältung", "the cold", "noun f."),
    E("die Grippe", "the flu", "noun f."),
    E("das Fieber", "the fever", "noun n."),
    E("der Schnupfen", "the runny nose", "noun m."),
    E("die Allergie", "the allergy", "noun f."),
    E("der Ausschlag", "the rash", "noun m."),
    E("die Verletzung", "the injury", "noun f."),
    E("der Bruch", "the fracture", "noun m."),
    E("die Wunde", "the wound", "noun f."),
    E("das Pflaster", "the plaster", "noun n."),
    E("der Verband", "the bandage", "noun m."),
    E("die Tablette", "the tablet", "noun f.", "die Tabletten"),
    E("die Tropfen", "the drops", "noun pl."),
    E("die Salbe", "the ointment", "noun f."),
    E("das Rezept", "the prescription", "noun n."),
    E("die Impfung", "the vaccination", "noun f."),
    E("die Krankenkasse", "the health insurance", "noun f."),
    E("die Versicherung", "the insurance", "noun f."),
    E("die Krankschreibung", "the sick note", "noun f."),
    E("der Krankenstand", "the sick leave", "noun m."),
    E("die Sprechstunde", "the surgery hours", "noun f."),
    E("die Praxis", "the practice", "noun f."),
    E("der Termin", "the appointment", "noun m."),
    E("die Untersuchung", "the examination", "noun f."),
    E("die Behandlung", "the treatment", "noun f."),
    E("die Operation", "the operation", "noun f."),
    E("der Patient", "the patient", "noun m."),
    E("die Patientin", "the patient (f.)", "noun f."),
    E("die Krankenschwester", "the nurse", "noun f."),
    E("der Krankenpfleger", "the nurse (m.)", "noun m."),
    E("der Rettungswagen", "the ambulance", "noun m."),
    E("der Notruf", "the emergency call", "noun m."),
    E("der Notarzt", "the emergency doctor", "noun m."),
    E("die Krankheit", "the illness", "noun f."),
    E("der Schmerz", "the pain", "noun m.", "die Schmerzen"),
    E("die Kopfschmerzen", "the headache", "noun pl."),
    E("die Bauchschmerzen", "the stomach ache", "noun pl."),
    E("die Rückenschmerzen", "the back pain", "noun pl."),
    E("das Wohlbefinden", "the well-being", "noun n."),
    E("die Fitness", "the fitness", "noun f."),
    E("das Training", "the training", "noun n."),
    E("die Bewegung", "the exercise", "noun f."),
    E("die Diät", "the diet", "noun f."),
    E("schlafen", "to sleep", "verb"),
    E("ruhen", "to rest", "verb"),
    E("sich ausruhen", "to rest up", "verb"),
    E("sich erholen", "to recover", "verb"),
    E("heilen", "to heal", "verb"),
    E("verletzen", "to injure", "verb"),
    E("sich verletzen", "to hurt oneself", "verb"),
    E("untersuchen", "to examine", "verb"),
    E("behandeln", "to treat", "verb"),
    E("operieren", "to operate", "verb"),
    E("verschreiben", "to prescribe", "verb"),
    E("impfen", "to vaccinate", "verb"),
    E("krank", "ill", "adjective"),
    E("gesund", "healthy", "adjective"),
    E("verletzt", "injured", "adjective"),
    E("schwach", "weak", "adjective"),
    E("stark", "strong", "adjective"),
    E("fit", "fit", "adjective"),
    E("wohltuend", "soothing", "adjective"),
    E("erholt", "rested", "adjective"),
  ],
  clothes: [
    E("die Bluse", "the blouse", "noun f.", "die Blusen"),
    E("der Rock", "the skirt", "noun m.", "die Röcke"),
    E("die Krawatte", "the tie", "noun f.", "die Krawatten"),
    E("der Schal", "the scarf", "noun m.", "die Schals"),
    E("die Handschuhe", "the gloves", "noun pl."),
    E("der Stiefel", "the boot", "noun m.", "die Stiefel"),
    E("die Sandalen", "the sandals", "noun pl."),
    E("die Turnschuhe", "the trainers", "noun pl."),
    E("die Hausschuhe", "the slippers", "noun pl."),
    E("der Schlafanzug", "the pyjamas", "noun m."),
    E("der Badeanzug", "the swimsuit", "noun m."),
    E("die Badehose", "the swimming trunks", "noun f."),
    E("der Regenmantel", "the raincoat", "noun m."),
    E("die Regenjacke", "the rain jacket", "noun f."),
    E("der Anorak", "the anorak", "noun m."),
    E("die Windjacke", "the windbreaker", "noun f."),
    E("die Weste", "the waistcoat", "noun f."),
    E("der Pulli", "the jumper", "noun m."),
    E("der Rollkragenpullover", "the polo-neck jumper", "noun m."),
    E("das T-Shirt", "the T-shirt", "noun n."),
    E("das Sweatshirt", "the sweatshirt", "noun n."),
    E("die Unterhose", "the underpants", "noun f."),
    E("das Unterhemd", "the vest", "noun n."),
    E("der BH", "the bra", "noun m."),
    E("die Strumpfhose", "the tights", "noun f."),
    E("der Gürtel", "the belt", "noun m."),
    E("die Tasche", "the handbag", "noun f."),
    E("die Umhängetasche", "the shoulder bag", "noun f."),
    E("der Rucksack", "the backpack", "noun m."),
    E("der Koffer", "the suitcase", "noun m."),
    E("der Regenschirm", "the umbrella", "noun m."),
    E("die Uhr", "the watch", "noun f."),
    E("die Armbanduhr", "the wristwatch", "noun f."),
    E("die Kette", "the necklace", "noun f."),
    E("der Ring", "the ring", "noun m."),
    E("die Ohrringe", "the earrings", "noun pl."),
    E("das Armband", "the bracelet", "noun n."),
    E("die Brosche", "the brooch", "noun f."),
    E("der Knopf", "the button", "noun m.", "die Knöpfe"),
    E("der Reißverschluss", "the zipper", "noun m."),
    E("die Naht", "the seam", "noun f."),
    E("der Ärmel", "the sleeve", "noun m."),
    E("der Kragen", "the collar", "noun m."),
    E("die Kapuze", "the hood", "noun f."),
    E("die Tasche am Hemd", "the pocket", "noun f."),
    E("das Futter", "the lining", "noun n."),
    E("der Stoff", "the fabric", "noun m."),
    E("die Baumwolle", "the cotton", "noun f."),
    E("die Wolle", "the wool", "noun f."),
    E("das Leder", "the leather", "noun n."),
    E("die Seide", "the silk", "noun f."),
    E("der Anzug", "the suit", "noun m."),
    E("die Uniform", "the uniform", "noun f."),
    E("das Kostüm", "the costume", "noun n."),
    E("die Tracht", "the traditional dress", "noun f."),
    E("die Kleidergröße", "the clothing size", "noun f."),
    E("die Konfektionsgröße", "the ready-made size", "noun f."),
    E("die Anprobe", "the fitting", "noun f."),
    E("die Umkleidekabine", "the fitting room", "noun f."),
    E("der Spiegel", "the mirror", "noun m."),
    E("die Wäsche", "the laundry", "noun f."),
    E("die Waschmaschine", "the washing machine", "noun f."),
    E("der Trockner", "the dryer", "noun m."),
    E("das Bügeleisen", "the iron", "noun n."),
    E("das Bügelbrett", "the ironing board", "noun n."),
    E("die Kleiderbügel", "the coat hangers", "noun pl."),
    E("anprobieren", "to try on", "verb"),
    E("anziehen", "to put on", "verb"),
    E("ausziehen", "to take off", "verb"),
    E("tragen", "to wear", "verb"),
    E("anhaben", "to be wearing", "verb"),
    E("passen", "to fit", "verb"),
    E("stehen", "to suit (clothes)", "verb"),
    E("waschen", "to wash", "verb"),
    E("bügeln", "to iron", "verb"),
    E("falten", "to fold", "verb"),
    E("aufhängen", "to hang up", "verb"),
    E("nähen", "to sew", "verb"),
    E("stricken", "to knit", "verb"),
    E("eng", "tight", "adjective"),
    E("weit", "loose", "adjective"),
    E("kurz", "short", "adjective"),
    E("lang", "long", "adjective"),
    E("gestreift", "striped", "adjective"),
    E("gepunktet", "dotted", "adjective"),
    E("kariert", "checked", "adjective"),
    E("einfarbig", "plain", "adjective"),
    E("modisch", "fashionable", "adjective"),
    E("eleganter Stil", "elegant style", "phrase"),
    E("lässig", "casual", "adjective"),
  ],
  city: [
    E("die Straßenkreuzung", "the crossroads", "noun f."),
    E("die Fußgängerzone", "the pedestrian zone", "noun f."),
    E("der Gehweg", "the pavement", "noun m."),
    E("der Bürgersteig", "the sidewalk", "noun m."),
    E("die Laterne", "the street lamp", "noun f."),
    E("der Brunnen", "the fountain", "noun m."),
    E("die Statue", "the statue", "noun f."),
    E("das Denkmal", "the monument", "noun n."),
    E("der Turm", "the tower", "noun m."),
    E("der Glockenturm", "the bell tower", "noun m."),
    E("die Stadtmauer", "the city wall", "noun f."),
    E("das Stadttor", "the city gate", "noun n."),
    E("der Vorort", "the suburb", "noun m."),
    E("das Stadtzentrum", "the city centre", "noun n."),
    E("die Altstadt", "the old town", "noun f."),
    E("die Innenstadt", "the city centre", "noun f."),
    E("der Stadtplan", "the city map", "noun m."),
    E("die Umgebung", "the surroundings", "noun f."),
    E("der Stadtbezirk", "the district", "noun m."),
    E("die Nachbarschaft", "the neighbourhood", "noun f."),
    E("das Einwohnermeldeamt", "the registration office", "noun n."),
    E("das Rathaus", "the town hall", "noun n."),
    E("die Stadtverwaltung", "the city administration", "noun f."),
    E("der Bürgermeister", "the mayor", "noun m."),
    E("die Polizeiwache", "the police station", "noun f."),
    E("die Feuerwehr", "the fire brigade", "noun f."),
    E("die Feuerwache", "the fire station", "noun f."),
    E("das Krankenhaus", "the hospital", "noun n."),
    E("die Krankenstation", "the ward", "noun f."),
    E("das Amtsgericht", "the district court", "noun n."),
    E("das Gefängnis", "the prison", "noun n."),
    E("die Bibliothek", "the library", "noun f."),
    E("die Stadtbibliothek", "the city library", "noun f."),
    E("die Galerie", "the gallery", "noun f."),
    E("die Kunstgalerie", "the art gallery", "noun f."),
    E("die Oper", "the opera house", "noun f."),
    E("das Konzerthaus", "the concert hall", "noun n."),
    E("das Stadion", "the stadium", "noun n."),
    E("die Sporthalle", "the sports hall", "noun f."),
    E("der Spielplatz", "the playground", "noun m."),
    E("der Friedhof", "the cemetery", "noun m."),
    E("der Bahnhofsvorplatz", "the station square", "noun m."),
    E("der Taxistand", "the taxi rank", "noun m."),
    E("die Bushaltestelle", "the bus stop", "noun f."),
    E("die Endstation", "the terminus", "noun f."),
    E("die Haltestelle", "the stop", "noun f."),
    E("der Fahrkartenautomat", "the ticket machine", "noun m."),
    E("die Straßenbahnlinie", "the tram line", "noun f."),
    E("die U-Bahnstation", "the underground station", "noun f."),
    E("der Tunnel", "the tunnel", "noun m."),
    E("die Fußgängerbrücke", "the footbridge", "noun f."),
    E("die Autobrücke", "the road bridge", "noun f."),
    E("der Kreisverkehr", "the roundabout", "noun m."),
    E("die Einbahnstraße", "the one-way street", "noun f."),
    E("die Sackgasse", "the dead end", "noun f."),
    E("das Verkehrsschild", "the road sign", "noun n."),
    E("die Geschwindigkeitsbegrenzung", "the speed limit", "noun f."),
    E("die Parkuhr", "the parking meter", "noun f."),
    E("der Parkschein", "the parking ticket", "noun m."),
    E("die Straßenreinigung", "the street cleaning", "noun f."),
    E("der Mülleimer", "the litter bin", "noun m."),
    E("die Telefonzelle", "the phone booth", "noun f."),
    E("der Briefkasten", "the postbox", "noun m."),
    E("das Fundbüro", "the lost property office", "noun n."),
    E("die Touristeninformation", "the tourist office", "noun f."),
    E("die Einwohner", "the inhabitants", "noun pl."),
    E("die Bevölkerung", "the population", "noun f."),
    E("der Stadtführer", "the city guide", "noun m."),
    E("die Sehenswürdigkeit", "the attraction", "noun f."),
    E("das Wahrzeichen", "the landmark", "noun n."),
    E("der Anwohner", "the local resident", "noun m."),
    E("die Stadtbahn", "the city rail", "noun f."),
    E("der Pendler", "the commuter", "noun m."),
    E("abfahren", "to depart", "verb"),
    E("anfahren", "to arrive (vehicle)", "verb"),
    E("einbiegen", "to turn into", "verb"),
    E("abbiegen", "to turn", "verb"),
    E("überqueren", "to cross", "verb"),
    E("gehen", "to walk", "verb"),
    E("fahren", "to ride", "verb"),
    E("parken", "to park", "verb"),
    E("halten", "to stop", "verb"),
    E("aussteigen", "to get off", "verb"),
    E("einsteigen", "to get on", "verb"),
    E("sich verlaufen", "to get lost", "verb"),
    E("fragen", "to ask", "verb"),
    E("zentral", "central", "adjective"),
    E("belebt", "busy", "adjective"),
    E("ruhig", "quiet", "adjective"),
    E("sicher", "safe", "adjective"),
    E("sauber", "clean", "adjective"),
    E("verschmutzt", "polluted", "adjective"),
    E("behindertengerecht", "accessible", "adjective"),
    E("berühmt", "famous", "adjective"),
  ],
  culture: [
    E("der Künstler", "the artist", "noun m."),
    E("die Künstlerin", "the artist (f.)", "noun f."),
    E("die Kunst", "the art", "noun f."),
    E("das Gemälde", "the painting", "noun n."),
    E("die Zeichnung", "the drawing", "noun f."),
    E("die Skulptur", "the sculpture", "noun f."),
    E("die Ausstellung", "the exhibition", "noun f."),
    E("das Museum", "the museum", "noun n."),
    E("das Kunstmuseum", "the art museum", "noun n."),
    E("die Galerie", "the gallery", "noun f."),
    E("der Schauspieler", "the actor", "noun m."),
    E("die Schauspielerin", "the actress", "noun f."),
    E("der Regisseur", "the director", "noun m."),
    E("der Film", "the film", "noun m."),
    E("der Spielfilm", "the feature film", "noun m."),
    E("der Kurzfilm", "the short film", "noun m."),
    E("die Filmrolle", "the film role", "noun f."),
    E("die Szene", "the scene", "noun f."),
    E("der Drehbuchautor", "the screenwriter", "noun m."),
    E("die Kamera", "the camera", "noun f."),
    E("das Publikum", "the audience", "noun n."),
    E("die Premiere", "the premiere", "noun f."),
    E("das Kino", "the cinema", "noun n."),
    E("die Filmvorführung", "the film screening", "noun f."),
    E("der Filmabend", "the movie night", "noun m."),
    E("das Fernsehprogramm", "the TV schedule", "noun n."),
    E("die Sendung", "the show", "noun f."),
    E("die Serie", "the series", "noun f."),
    E("die Nachrichten", "the news", "noun pl."),
    E("die Sportschau", "the sports show", "noun f."),
    E("der Sender", "the channel", "noun m."),
    E("die Fernbedienung", "the remote control", "noun f."),
    E("der Fernseher", "the television set", "noun m."),
    E("die Glotze", "the telly", "noun f."),
    E("der Radiosender", "the radio station", "noun m."),
    E("die Musikrichtung", "the music genre", "noun f."),
    E("der Popmusik", "the pop music", "noun f."),
    E("der Rockmusik", "the rock music", "noun f."),
    E("die Klassik", "the classical music", "noun f."),
    E("der Jazz", "the jazz", "noun m."),
    E("die Volksmusik", "the folk music", "noun f."),
    E("der Chor", "the choir", "noun m."),
    E("das Orchester", "the orchestra", "noun n."),
    E("die Band", "the band", "noun f."),
    E("der Sänger", "the singer", "noun m."),
    E("die Sängerin", "the singer (f.)", "noun f."),
    E("das Lied", "the song", "noun n.", "die Lieder"),
    E("der Text", "the lyrics", "noun m."),
    E("die Melodie", "the melody", "noun f."),
    E("der Rhythmus", "the rhythm", "noun m."),
    E("die Gitarre", "the guitar", "noun f."),
    E("das Klavier", "the piano", "noun n."),
    E("die Geige", "the violin", "noun f."),
    E("die Trommel", "the drum", "noun f."),
    E("die Flöte", "the flute", "noun f."),
    E("das Saxophon", "the saxophone", "noun n."),
    E("die Bühne", "the stage", "noun f."),
    E("der Vorhang", "the curtain", "noun m."),
    E("das Theaterstück", "the play", "noun n."),
    E("die Aufführung", "the performance", "noun f."),
    E("die Oper", "the opera", "noun f."),
    E("das Ballett", "the ballet", "noun n."),
    E("der Zirkus", "the circus", "noun m."),
    E("der Artist", "the acrobat", "noun m."),
    E("der Clown", "the clown", "noun m."),
    E("das Feuerwerk", "the fireworks", "noun n."),
    E("die Parade", "the parade", "noun f."),
    E("der Umzug", "the procession", "noun m."),
    E("der Karneval", "the carnival", "noun m."),
    E("das Oktoberfest", "the Oktoberfest", "noun n."),
    E("das Volksfest", "the funfair", "noun n."),
    E("die Kirmes", "the fair", "noun f."),
    E("das Hobby", "the hobby", "noun n.", "die Hobbys"),
    E("die Freizeitbeschäftigung", "the leisure activity", "noun f."),
    E("das Schach", "the chess", "noun n."),
    E("das Kartenspiel", "the card game", "noun n."),
    E("das Brettspiel", "the board game", "noun n."),
    E("das Puzzle", "the puzzle", "noun n."),
    E("das Videospiel", "the video game", "noun n."),
    E("der Fußball", "the football", "noun m."),
    E("der Handball", "the handball", "noun m."),
    E("das Tennis", "the tennis", "noun n."),
    E("das Schwimmen", "the swimming", "noun n."),
    E("das Wandern", "the hiking", "noun n."),
    E("das Radfahren", "the cycling", "noun n."),
    E("das Angeln", "the fishing", "noun n."),
    E("das Kochen", "the cooking", "noun n."),
    E("das Backen", "the baking", "noun n."),
    E("das Fotografieren", "the photography", "noun n."),
    E("das Zeichnen", "the drawing", "noun n."),
    E("das Lesen", "the reading", "noun n."),
    E("die Fantasie", "the imagination", "noun f."),
    E("die Kreativität", "the creativity", "noun f."),
    E("das Talent", "the talent", "noun n."),
    E("der Geschmack", "the taste", "noun m."),
    E("der Stil", "the style", "noun m."),
    E("die Mode", "the fashion", "noun f."),
    E("der Trend", "the trend", "noun m."),
    E("die Kultur", "the culture", "noun f."),
    E("das Kulturerbe", "the cultural heritage", "noun n."),
    E("die Tradition", "the tradition", "noun f."),
    E("der Brauch", "the custom", "noun m."),
    E("das Fest", "the festival", "noun n."),
    E("die Feier", "the celebration", "noun f."),
    E("das Jubiläum", "the anniversary", "noun n."),
    E("interessant", "interesting", "adjective"),
    E("unterhaltsam", "entertaining", "adjective"),
    E("spannend", "exciting", "adjective"),
    E("langweilig", "boring", "adjective"),
    E("lustig", "funny", "adjective"),
    E("traurig", "sad", "adjective"),
    E("kulturell", "cultural", "adjective"),
    E("modern", "modern", "adjective"),
    E("traditionell", "traditional", "adjective"),
    E("berühmt", "famous", "adjective"),
    E("kreativ", "creative", "adjective"),
    E("sich amüsieren", "to enjoy oneself", "verb"),
    E("feiern", "to celebrate", "verb"),
    E("genießen", "to enjoy", "verb"),
    E("verbringen", "to spend (time)", "verb"),
    E("sich entspannen", "to relax", "verb"),
  ],
};