import type { Lesson } from "../../../schema";

export const wortschatzWortgruppen: Lesson = {
  id: "wortschatz-wortgruppen",
  title: "Wortschatz: Wortgruppen",
  summary: "The official Goethe word groups: numbers, days, months, seasons, colors, time, measures.",
  status: "ready",
  sections: [
    { heading: "Die Wortgruppen", blocks: [
      { type: 'paragraph', text: "The Goethe exam groups its basic vocabulary into fixed lists, and the exam expects you to know them cold: numbers, weekdays, months, seasons, colors, time units, day parts, directions, and measures. These are the words of every timetable, price tag, and date line." },
      { type: 'paragraph', text: "The number pattern deserves attention: from 20 up, German says the unit first, then und, then the ten: einundzwanzig is one-and-twenty. Days and months always come with der: der Montag, der Mai. Colors are bare adjectives: rot, blau, grün." }
    ] }
  ],
  vocab: [
    { id: "w001", de: "eins", en: "one", part: "noun m.", audio: true },
    { id: "w002", de: "zwei", en: "two", part: "noun m.", audio: true },
    { id: "w003", de: "drei", en: "three", part: "noun m.", audio: true },
    { id: "w004", de: "vier", en: "four", part: "noun m.", audio: true },
    { id: "w005", de: "fünf", en: "five", part: "noun m.", audio: true },
    { id: "w006", de: "sechs", en: "six", part: "noun m.", audio: true },
    { id: "w007", de: "sieben", en: "seven", part: "noun m.", audio: true },
    { id: "w008", de: "acht", en: "eight", part: "noun m.", audio: true },
    { id: "w009", de: "neun", en: "nine", part: "noun m.", audio: true },
    { id: "w010", de: "zehn", en: "ten", part: "noun m.", audio: true },
    { id: "w011", de: "elf", en: "eleven", part: "noun m.", audio: true },
    { id: "w012", de: "zwölf", en: "twelve", part: "noun m.", audio: true },
    { id: "w013", de: "dreizehn", en: "thirteen", part: "noun m.", audio: true },
    { id: "w014", de: "vierzehn", en: "fourteen", part: "noun m.", audio: true },
    { id: "w015", de: "fünfzehn", en: "fifteen", part: "noun m.", audio: true },
    { id: "w016", de: "sechzehn", en: "sixteen", part: "noun m.", audio: true },
    { id: "w017", de: "siebzehn", en: "seventeen", part: "noun m.", audio: true },
    { id: "w018", de: "achtzehn", en: "eighteen", part: "noun m.", audio: true },
    { id: "w019", de: "neunzehn", en: "nineteen", part: "noun m.", audio: true },
    { id: "w020", de: "zwanzig", en: "twenty", part: "noun m.", audio: true },
    { id: "w021", de: "dreißig", en: "thirty", part: "noun m.", audio: true },
    { id: "w022", de: "vierzig", en: "forty", part: "noun m.", audio: true },
    { id: "w023", de: "fünfzig", en: "fifty", part: "noun m.", audio: true },
    { id: "w024", de: "sechzig", en: "sixty", part: "noun m.", audio: true },
    { id: "w025", de: "siebzig", en: "seventy", part: "noun m.", audio: true },
    { id: "w026", de: "achtzig", en: "eighty", part: "noun m.", audio: true },
    { id: "w027", de: "neunzig", en: "ninety", part: "noun m.", audio: true },
    { id: "w028", de: "hundert", en: "hundred", part: "noun m.", audio: true },
    { id: "w029", de: "tausend", en: "thousand", part: "noun m.", audio: true },
    { id: "w030", de: "eine Million", en: "a million", part: "noun n.", audio: true },
    { id: "w031", de: "der Montag", en: "Monday", part: "noun m.", audio: true },
    { id: "w032", de: "der Dienstag", en: "Tuesday", part: "noun m.", audio: true },
    { id: "w033", de: "der Mittwoch", en: "Wednesday", part: "noun m.", audio: true },
    { id: "w034", de: "der Donnerstag", en: "Thursday", part: "noun m.", audio: true },
    { id: "w035", de: "der Freitag", en: "Friday", part: "noun m.", audio: true },
    { id: "w036", de: "der Samstag", en: "Saturday", part: "noun m.", audio: true },
    { id: "w037", de: "der Sonntag", en: "Sunday", part: "noun m.", audio: true },
    { id: "w038", de: "das Wochenende", en: "the weekend", part: "noun n.", audio: true },
    { id: "w039", de: "der Januar", en: "January", part: "noun m.", audio: true },
    { id: "w040", de: "der Februar", en: "February", part: "noun m.", audio: true },
    { id: "w041", de: "der März", en: "March", part: "noun m.", audio: true },
    { id: "w042", de: "der April", en: "April", part: "noun m.", audio: true },
    { id: "w043", de: "der Mai", en: "May", part: "noun m.", audio: true },
    { id: "w044", de: "der Juni", en: "June", part: "noun m.", audio: true },
    { id: "w045", de: "der Juli", en: "July", part: "noun m.", audio: true },
    { id: "w046", de: "der August", en: "August", part: "noun m.", audio: true },
    { id: "w047", de: "der September", en: "September", part: "noun m.", audio: true },
    { id: "w048", de: "der Oktober", en: "October", part: "noun m.", audio: true },
    { id: "w049", de: "der November", en: "November", part: "noun m.", audio: true },
    { id: "w050", de: "der Dezember", en: "December", part: "noun m.", audio: true },
    { id: "w051", de: "der Frühling", en: "the spring", part: "noun m.", audio: true },
    { id: "w052", de: "der Sommer", en: "the summer", part: "noun m.", audio: true },
    { id: "w053", de: "der Herbst", en: "the autumn", part: "noun m.", audio: true },
    { id: "w054", de: "der Winter", en: "the winter", part: "noun m.", audio: true },
    { id: "w055", de: "schwarz", en: "black", part: "adjective", audio: true },
    { id: "w056", de: "grau", en: "grey", part: "adjective", audio: true },
    { id: "w057", de: "blau", en: "blue", part: "adjective", audio: true },
    { id: "w058", de: "grün", en: "green", part: "adjective", audio: true },
    { id: "w059", de: "weiß", en: "white", part: "adjective", audio: true },
    { id: "w060", de: "rot", en: "red", part: "adjective", audio: true },
    { id: "w061", de: "gelb", en: "yellow", part: "adjective", audio: true },
    { id: "w062", de: "braun", en: "brown", part: "adjective", audio: true },
    { id: "w063", de: "die Sekunde", en: "the second", part: "noun f.", audio: true },
    { id: "w064", de: "die Minute", en: "the minute", part: "noun f.", audio: true },
    { id: "w065", de: "die Stunde", en: "the hour", part: "noun f.", audio: true },
    { id: "w066", de: "der Tag", en: "the day", part: "noun m.", audio: true },
    { id: "w067", de: "die Woche", en: "the week", part: "noun f.", audio: true },
    { id: "w068", de: "das Jahr", en: "the year", part: "noun n.", audio: true },
    { id: "w069", de: "der Morgen", en: "the morning", part: "noun m.", audio: true },
    { id: "w070", de: "der Vormittag", en: "the late morning", part: "noun m.", audio: true },
    { id: "w071", de: "der Mittag", en: "the midday", part: "noun m.", audio: true },
    { id: "w072", de: "der Nachmittag", en: "the afternoon", part: "noun m.", audio: true },
    { id: "w073", de: "der Abend", en: "the evening", part: "noun m.", audio: true },
    { id: "w074", de: "die Nacht", en: "the night", part: "noun f.", audio: true },
    { id: "w075", de: "der Norden", en: "the north", part: "noun m.", audio: true },
    { id: "w076", de: "der Süden", en: "the south", part: "noun m.", audio: true },
    { id: "w077", de: "der Westen", en: "the west", part: "noun m.", audio: true },
    { id: "w078", de: "der Osten", en: "the east", part: "noun m.", audio: true },
    { id: "w079", de: "der Meter", en: "the metre", part: "noun m.", audio: true },
    { id: "w080", de: "der Zentimeter", en: "the centimetre", part: "noun m.", audio: true },
    { id: "w081", de: "der Kilometer", en: "the kilometre", part: "noun m.", audio: true },
    { id: "w082", de: "der Quadratmeter", en: "the square metre", part: "noun m.", audio: true },
    { id: "w083", de: "der Liter", en: "the litre", part: "noun m.", audio: true },
    { id: "w084", de: "das Gramm", en: "the gram", part: "noun n.", audio: true },
    { id: "w085", de: "das Kilo", en: "the kilo", part: "noun n.", audio: true },
    { id: "w086", de: "das Pfund", en: "the pound (500 g)", part: "noun n.", audio: true },
  ],
  exercises: [
{"id": "ex-wg-1", "type": "multiple-choice", "title": "Übung 1", "instruction": "Choose the correct number.", "prompt": "What is 25 in German?", "options": ["fünfundzwanzig", "fünfzehn", "fünfzig"], "correctIndex": 0, "explain": "25 is fünfundzwanzig: unit first."},
{"id": "ex-wg-2", "type": "multiple-choice", "title": "Übung 2", "instruction": "Choose the correct day.", "prompt": "Which day is between Friday and Sunday?", "options": ["der Samstag", "der Donnerstag", "der Montag"], "correctIndex": 0, "explain": "Samstag sits between Friday and Sunday."},
{"id": "ex-wg-3", "type": "multiple-choice", "title": "Übung 3", "instruction": "Choose the correct month.", "prompt": "The seventh month is ...", "options": ["der Juli", "der Juni", "der August"], "correctIndex": 0, "explain": "Juli is the seventh month."},
{"id": "ex-wg-4", "type": "fill-blank", "title": "Übung 4", "instruction": "Type the missing word.", "sentence": "Der Termin ist ___ Montag. (on)", "translation": "The appointment is ___ Monday. (on)", "blanks": [{"answers": ["am"], "hint": "an + dem"}]},
{"id": "ex-wg-5", "type": "multiple-choice", "title": "Übung 5", "instruction": "Choose the correct color.", "prompt": "Die Sonne ist ___.", "options": ["gelb", "blau", "grün"], "correctIndex": 0, "explain": "The sun is yellow: gelb."},
{"id": "ex-wg-6", "type": "flashcard", "title": "Übung 6: Wortgruppen", "instruction": "Say the German word out loud before revealing.", "items": [{"front": "zwanzig", "back": "20", "frontAudio": true}, {"front": "der Freitag", "back": "Friday", "frontAudio": true}, {"front": "der Juli", "back": "July", "frontAudio": true}, {"front": "der Winter", "back": "winter", "frontAudio": true}, {"front": "rot", "back": "red", "frontAudio": true}, {"front": "das Wochenende", "back": "the weekend", "frontAudio": true}]}
  ],
};
