import type { Lesson } from "../../../schema";

export const wortschatzSZ: Lesson = {
  id: "wortschatz-s-z",
  title: "Wortschatz S-Z",
  summary: "The official Goethe A1 word list, letters S to Z.",
  status: "ready",
  sections: [
    { heading: "Wörter von S bis Z", blocks: [
      { type: 'paragraph', text: "This lesson covers the official Goethe A1 word list from S to Z, the largest chunk: the home and city (der Schrank, die Stadt, die Straße, die Treppe), travel and transport (das Taxi, umsteigen, der Zug), food (der Salat, die Suppe, die Tomate, der Teller), money and shopping (verkaufen, zahlen, die Zeitung), and time itself (die Zeit, die Stunde, der Tag, die Woche)." },
      { type: 'paragraph', text: "By now you have met the whole official A1 vocabulary. Notice how the same building blocks return everywhere: um + steigen, um + tauschen, zu + rück, vor + stellen. Every compound is a story: die Straßenbahn is the tram, the Bahn that rides on the Straße." }
    ] }
  ],
  vocab: [
    { id: "w001", de: "der Saft", en: "the juice", part: "noun m.", audio: true },
    { id: "w002", de: "sagen", en: "to say", part: "verb", audio: true },
    { id: "w003", de: "der Salat", en: "the salad, the lettuce", part: "noun m.", audio: true },
    { id: "w004", de: "das Salz", en: "the salt", part: "noun n.", audio: true },
    { id: "w005", de: "sammeln", en: "to collect", part: "verb", audio: true },
    { id: "w006", de: "der Samstag", en: "Saturday", part: "noun m.", audio: true },
    { id: "w007", de: "der Sand", en: "the sand", part: "noun m.", audio: true },
    { id: "w008", de: "satt", en: "full (after eating)", part: "adjective", audio: true },
    { id: "w009", de: "der Schaden", en: "the damage", part: "noun m.", audio: true },
    { id: "w010", de: "schaffen", en: "to manage, to create", part: "verb", audio: true },
    { id: "w011", de: "der Schal", en: "the scarf", part: "noun m.", audio: true },
    { id: "w012", de: "schauen", en: "to look", part: "verb", audio: true },
    { id: "w013", de: "scheinen", en: "to shine, to seem", part: "verb", audio: true },
    { id: "w014", de: "schenken", en: "to give (a gift)", part: "verb", audio: true },
    { id: "w015", de: "schicken", en: "to send", part: "verb", audio: true },
    { id: "w016", de: "das Schild", en: "the sign", part: "noun n.", audio: true },
    { id: "w017", de: "schlafen", en: "to sleep", part: "verb", audio: true },
    { id: "w018", de: "der Schlaf", en: "the sleep", part: "noun m.", audio: true },
    { id: "w019", de: "der Schlag", en: "the blow, the stroke", part: "noun m.", audio: true },
    { id: "w020", de: "schlagen", en: "to hit", part: "verb", audio: true },
    { id: "w021", de: "der Schlüssel", en: "the key", part: "noun m.", audio: true },
    { id: "w022", de: "schmecken", en: "to taste", part: "verb", audio: true },
    { id: "w023", de: "der Schmerz", en: "the pain", part: "noun m.", audio: true },
    { id: "w024", de: "schmücken", en: "to decorate", part: "verb", audio: true },
    { id: "w025", de: "schneiden", en: "to cut", part: "verb", audio: true },
    { id: "w026", de: "der Schnee", en: "the snow", part: "noun m.", audio: true },
    { id: "w027", de: "schneien", en: "to snow", part: "verb", audio: true },
    { id: "w028", de: "schnell", en: "fast, quick", part: "adjective", audio: true },
    { id: "w029", de: "schön", en: "beautiful, nice", part: "adjective", audio: true },
    { id: "w030", de: "der Schrank", en: "the cupboard, the wardrobe", part: "noun m.", audio: true },
    { id: "w031", de: "schreiben", en: "to write", part: "verb", audio: true },
    { id: "w032", de: "die Schule", en: "the school", part: "noun f.", audio: true },
    { id: "w033", de: "der Schüler", en: "the pupil (male)", part: "noun m.", audio: true },
    { id: "w034", de: "die Schülerin", en: "the pupil (female)", part: "noun f.", audio: true },
    { id: "w035", de: "der Schutz", en: "the protection", part: "noun m.", audio: true },
    { id: "w036", de: "schwarz", en: "black", part: "adjective", audio: true },
    { id: "w037", de: "das Schwein", en: "the pig", part: "noun n.", audio: true },
    { id: "w038", de: "schwer", en: "heavy, difficult", part: "adjective", audio: true },
    { id: "w039", de: "die Schwester", en: "the sister", part: "noun f.", audio: true },
    { id: "w040", de: "schwimmen", en: "to swim", part: "verb", audio: true },
    { id: "w041", de: "das Schwimmbad", en: "the swimming pool", part: "noun n.", audio: true },
    { id: "w042", de: "die See", en: "the sea", part: "noun f.", audio: true },
    { id: "w043", de: "sehen", en: "to see", part: "verb", audio: true },
    { id: "w044", de: "sehr", en: "very", part: "adverb", audio: true },
    { id: "w045", de: "sein", en: "to be; his", part: "verb", audio: true },
    { id: "w046", de: "seit", en: "since, for", part: "particle / preposition", audio: true },
    { id: "w047", de: "die Seite", en: "the page, the side", part: "noun f.", audio: true },
    { id: "w048", de: "der Sektor", en: "the sector", part: "noun m.", audio: true },
    { id: "w049", de: "selbst", en: "self, even", part: "adverb", audio: true },
    { id: "w050", de: "selten", en: "rare, seldom", part: "adjective", audio: true },
    { id: "w051", de: "die Sendung", en: "the broadcast, the shipment", part: "noun f.", audio: true },
    { id: "w052", de: "die Serviette", en: "the napkin", part: "noun f.", audio: true },
    { id: "w053", de: "setzen", en: "to sit (someone) down", part: "verb", audio: true },
    { id: "w054", de: "sich", en: "oneself, himself, herself", part: "noun m.", audio: true },
    { id: "w055", de: "sicher", en: "safe, certain", part: "adjective", audio: true },
    { id: "w056", de: "die Sicherheit", en: "the safety, the security", part: "noun f.", audio: true },
    { id: "w057", de: "sie", en: "she, they", part: "noun f.", audio: true },
    { id: "w058", de: "Sie", en: "you (formal)", part: "noun m.", audio: true },
    { id: "w059", de: "sofort", en: "immediately", part: "adverb", audio: true },
    { id: "w060", de: "sogar", en: "even", part: "adverb", audio: true },
    { id: "w061", de: "der Sohn", en: "the son", part: "noun m.", audio: true },
    { id: "w062", de: "solch", en: "such", part: "noun m.", audio: true },
    { id: "w063", de: "sollen", en: "should, to be supposed to", part: "verb", audio: true },
    { id: "w064", de: "der Sommer", en: "the summer", part: "noun m.", audio: true },
    { id: "w065", de: "sondern", en: "but rather", part: "particle / preposition", audio: true },
    { id: "w066", de: "die Sonne", en: "the sun", part: "noun f.", audio: true },
    { id: "w067", de: "der Sonntag", en: "Sunday", part: "noun m.", audio: true },
    { id: "w068", de: "sonst", en: "otherwise, else", part: "adverb", audio: true },
    { id: "w069", de: "die Sorte", en: "the sort, the kind", part: "noun f.", audio: true },
    { id: "w070", de: "spät", en: "late", part: "adjective", audio: true },
    { id: "w071", de: "spazieren", en: "to stroll, to walk", part: "verb", audio: true },
    { id: "w072", de: "der Spaß", en: "the fun", part: "noun m.", audio: true },
    { id: "w073", de: "speisen", en: "to dine", part: "verb", audio: true },
    { id: "w074", de: "die Speisekarte", en: "the menu", part: "noun f.", audio: true },
    { id: "w075", de: "spielen", en: "to play", part: "verb", audio: true },
    { id: "w076", de: "der Sport", en: "the sport", part: "noun m.", audio: true },
    { id: "w077", de: "die Sprache", en: "the language", part: "noun f.", audio: true },
    { id: "w078", de: "sprechen", en: "to speak", part: "verb", audio: true },
    { id: "w079", de: "das Sprechzimmer", en: "the consultation room", part: "noun n.", audio: true },
    { id: "w080", de: "die Stadt", en: "the city, the town", part: "noun f.", audio: true },
    { id: "w081", de: "der Stadtplan", en: "the city map", part: "noun m.", audio: true },
    { id: "w082", de: "der Stand", en: "the stand, the stall", part: "noun m.", audio: true },
    { id: "w083", de: "stark", en: "strong", part: "adjective", audio: true },
    { id: "w084", de: "statt", en: "instead of", part: "particle / preposition", audio: true },
    { id: "w085", de: "der Staubsauger", en: "the vacuum cleaner", part: "noun m.", audio: true },
    { id: "w086", de: "stecken", en: "to put, to stick", part: "verb", audio: true },
    { id: "w087", de: "stehen", en: "to stand", part: "verb", audio: true },
    { id: "w088", de: "steigen", en: "to climb, to rise", part: "verb", audio: true },
    { id: "w089", de: "die Stelle", en: "the place, the position", part: "noun f.", audio: true },
    { id: "w090", de: "stellen", en: "to put (upright)", part: "verb", audio: true },
    { id: "w091", de: "der Stempel", en: "the stamp, the seal", part: "noun m.", audio: true },
    { id: "w092", de: "die Stereoanlage", en: "the stereo system", part: "noun f.", audio: true },
    { id: "w093", de: "das Stern", en: "the star", part: "noun m.", audio: true },
    { id: "w094", de: "der Stift", en: "the pen", part: "noun m.", audio: true },
    { id: "w095", de: "still", en: "quiet, still", part: "adjective", audio: true },
    { id: "w096", de: "die Stimme", en: "the voice", part: "noun f.", audio: true },
    { id: "w097", de: "stimmen", en: "to be right, to vote", part: "verb", audio: true },
    { id: "w098", de: "die Stimmung", en: "the mood, the atmosphere", part: "noun f.", audio: true },
    { id: "w099", de: "der Stock", en: "the floor, the storey", part: "noun m.", audio: true },
    { id: "w100", de: "der Stopp", en: "the stop", part: "noun m.", audio: true },
    { id: "w101", de: "stören", en: "to disturb", part: "verb", audio: true },
    { id: "w102", de: "die Straße", en: "the street", part: "noun f.", audio: true },
    { id: "w103", de: "die Straßenbahn", en: "the tram", part: "noun f.", audio: true },
    { id: "w104", de: "streichen", en: "to paint, to strike", part: "verb", audio: true },
    { id: "w105", de: "streiten", en: "to argue", part: "verb", audio: true },
    { id: "w106", de: "der Strom", en: "the electricity, the current", part: "noun m.", audio: true },
    { id: "w107", de: "das Stück", en: "the piece", part: "noun n.", audio: true },
    { id: "w108", de: "die Stufe", en: "the step", part: "noun f.", audio: true },
    { id: "w109", de: "der Stuhl", en: "the chair", part: "noun m.", audio: true },
    { id: "w110", de: "die Stunde", en: "the hour, the lesson", part: "noun f.", audio: true },
    { id: "w111", de: "suchen", en: "to look for", part: "verb", audio: true },
    { id: "w112", de: "der Süden", en: "the south", part: "noun m.", audio: true },
    { id: "w113", de: "die Suppe", en: "the soup", part: "noun f.", audio: true },
    { id: "w114", de: "das System", en: "the system", part: "noun n.", audio: true },
    { id: "w115", de: "der Tag", en: "the day", part: "noun m.", audio: true },
    { id: "w116", de: "die Tante", en: "the aunt", part: "noun f.", audio: true },
    { id: "w117", de: "tanzen", en: "to dance", part: "verb", audio: true },
    { id: "w118", de: "die Tasche", en: "the bag, the pocket", part: "noun f.", audio: true },
    { id: "w119", de: "die Tasse", en: "the cup", part: "noun f.", audio: true },
    { id: "w120", de: "die Tastatur", en: "the keyboard", part: "noun f.", audio: true },
    { id: "w121", de: "der Tausch", en: "the exchange, the swap", part: "noun m.", audio: true },
    { id: "w122", de: "tauschen", en: "to exchange, to swap", part: "verb", audio: true },
    { id: "w123", de: "das Taxi", en: "the taxi", part: "noun n.", audio: true },
    { id: "w124", de: "der Tee", en: "the tea", part: "noun m.", audio: true },
    { id: "w125", de: "der Teil", en: "the part", part: "noun m.", audio: true },
    { id: "w126", de: "teilen", en: "to share, to divide", part: "verb", audio: true },
    { id: "w127", de: "das Telefon", en: "the telephone", part: "noun n.", audio: true },
    { id: "w128", de: "telefonieren", en: "to phone", part: "verb", audio: true },
    { id: "w129", de: "der Teller", en: "the plate", part: "noun m.", audio: true },
    { id: "w130", de: "der Termin", en: "the appointment", part: "noun m.", audio: true },
    { id: "w131", de: "teuer", en: "expensive", part: "adjective", audio: true },
    { id: "w132", de: "das Theater", en: "the theatre", part: "noun n.", audio: true },
    { id: "w133", de: "das Tier", en: "the animal", part: "noun n.", audio: true },
    { id: "w134", de: "der Tisch", en: "the table", part: "noun m.", audio: true },
    { id: "w135", de: "das Toilettenpapier", en: "the toilet paper", part: "noun n.", audio: true },
    { id: "w136", de: "die Toilette", en: "the toilet", part: "noun f.", audio: true },
    { id: "w137", de: "die Tomate", en: "the tomato", part: "noun f.", audio: true },
    { id: "w138", de: "der Topf", en: "the pot", part: "noun m.", audio: true },
    { id: "w139", de: "tragen", en: "to carry, to wear", part: "verb", audio: true },
    { id: "w140", de: "der Traum", en: "the dream", part: "noun m.", audio: true },
    { id: "w141", de: "träumen", en: "to dream", part: "verb", audio: true },
    { id: "w142", de: "treffen", en: "to meet", part: "verb", audio: true },
    { id: "w143", de: "treiben", en: "to do (sport), to drive", part: "verb", audio: true },
    { id: "w144", de: "die Treppe", en: "the stairs", part: "noun f.", audio: true },
    { id: "w145", de: "trinken", en: "to drink", part: "verb", audio: true },
    { id: "w146", de: "das Trinkgeld", en: "the tip", part: "noun n.", audio: true },
    { id: "w147", de: "trocknen", en: "to dry", part: "verb", audio: true },
    { id: "w148", de: "das T-Shirt", en: "the T-shirt", part: "noun n.", audio: true },
    { id: "w149", de: "die Tür", en: "the door", part: "noun f.", audio: true },
    { id: "w150", de: "tun", en: "to do", part: "verb", audio: true },
    { id: "w151", de: "typisch", en: "typical", part: "adjective", audio: true },
    { id: "w152", de: "über", en: "over, above, about", part: "particle / preposition", audio: true },
    { id: "w153", de: "überall", en: "everywhere", part: "adverb", audio: true },
    { id: "w154", de: "übernachten", en: "to stay overnight", part: "verb", audio: true },
    { id: "w155", de: "überraschen", en: "to surprise", part: "verb", audio: true },
    { id: "w156", de: "übersetzen", en: "to translate", part: "verb", audio: true },
    { id: "w157", de: "die Uhr", en: "the clock, the watch", part: "noun f.", audio: true },
    { id: "w158", de: "um", en: "around, at (time)", part: "particle / preposition", audio: true },
    { id: "w159", de: "umsteigen", en: "to change (trains)", part: "verb", audio: true },
    { id: "w160", de: "umtauschen", en: "to exchange, to swap", part: "verb", audio: true },
    { id: "w161", de: "die Umwelt", en: "the environment", part: "noun f.", audio: true },
    { id: "w162", de: "unbekannt", en: "unknown", part: "adjective", audio: true },
    { id: "w163", de: "und", en: "and", part: "particle / preposition", audio: true },
    { id: "w164", de: "ungeduldig", en: "impatient", part: "adjective", audio: true },
    { id: "w165", de: "unglaublich", en: "unbelievable", part: "adjective", audio: true },
    { id: "w166", de: "unten", en: "below, downstairs", part: "adverb", audio: true },
    { id: "w167", de: "unter", en: "under, below", part: "particle / preposition", audio: true },
    { id: "w168", de: "unterhalten", en: "to entertain, to chat", part: "verb", audio: true },
    { id: "w169", de: "unternehmen", en: "to undertake", part: "verb", audio: true },
    { id: "w170", de: "die Unterschrift", en: "the signature", part: "noun f.", audio: true },
    { id: "w171", de: "unterstreichen", en: "to underline", part: "verb", audio: true },
    { id: "w172", de: "der Unterricht", en: "the lesson, the teaching", part: "noun m.", audio: true },
    { id: "w173", de: "das Urlaub", en: "the vacation", part: "noun m.", audio: true },
    { id: "w174", de: "der Urlaub", en: "the vacation", part: "noun m.", audio: true },
    { id: "w175", de: "die Ursache", en: "the cause, the reason", part: "noun f.", audio: true },
    { id: "w176", de: "der Vater", en: "the father", part: "noun m.", audio: true },
    { id: "w177", de: "verkaufen", en: "to sell", part: "verb", audio: true },
    { id: "w178", de: "der Verkäufer", en: "the salesperson", part: "noun m.", audio: true },
    { id: "w179", de: "verlieren", en: "to lose", part: "verb", audio: true },
    { id: "w180", de: "vermissen", en: "to miss (someone)", part: "verb", audio: true },
    { id: "w181", de: "die Vermieter", en: "the landlord", part: "noun m.", audio: true },
    { id: "w182", de: "der Vermieter", en: "the landlord", part: "noun m.", audio: true },
    { id: "w183", de: "verreisen", en: "to go away (on a trip)", part: "verb", audio: true },
    { id: "w184", de: "verschieden", en: "different, various", part: "adjective", audio: true },
    { id: "w185", de: "verstehen", en: "to understand", part: "verb", audio: true },
    { id: "w186", de: "der Versuch", en: "the attempt", part: "noun m.", audio: true },
    { id: "w187", de: "viel", en: "much, a lot", part: "adverb", audio: true },
    { id: "w188", de: "vielleicht", en: "maybe, perhaps", part: "adverb", audio: true },
    { id: "w189", de: "vier", en: "four", part: "noun m.", audio: true },
    { id: "w190", de: "das Viertel", en: "the quarter", part: "noun n.", audio: true },
    { id: "w191", de: "das Visum", en: "the visa", part: "noun n.", audio: true },
    { id: "w192", de: "das Vogel", en: "the bird", part: "noun m.", audio: true },
    { id: "w193", de: "der Vogel", en: "the bird", part: "noun m.", audio: true },
    { id: "w194", de: "völlig", en: "completely", part: "adverb", audio: true },
    { id: "w195", de: "von", en: "from, of", part: "particle / preposition", audio: true },
    { id: "w196", de: "vor", en: "before, in front of", part: "particle / preposition", audio: true },
    { id: "w197", de: "vorbereiten", en: "to prepare", part: "verb", audio: true },
    { id: "w198", de: "vorher", en: "beforehand", part: "adverb", audio: true },
    { id: "w199", de: "der Vormittag", en: "the morning (before noon)", part: "noun m.", audio: true },
    { id: "w200", de: "der Vorname", en: "the first name", part: "noun m.", audio: true },
    { id: "w201", de: "vorstellen", en: "to introduce, to imagine", part: "verb", audio: true },
    { id: "w202", de: "der Vortrag", en: "the lecture, the presentation", part: "noun m.", audio: true },
    { id: "w203", de: "wachsen", en: "to grow", part: "verb", audio: true },
    { id: "w204", de: "die Wand", en: "the wall", part: "noun f.", audio: true },
    { id: "w205", de: "wann", en: "when", part: "adverb", audio: true },
    { id: "w206", de: "warm", en: "warm", part: "adjective", audio: true },
    { id: "w207", de: "warten", en: "to wait", part: "verb", audio: true },
    { id: "w208", de: "warum", en: "why", part: "adverb", audio: true },
    { id: "w209", de: "was", en: "what", part: "adverb", audio: true },
    { id: "w210", de: "waschen", en: "to wash", part: "verb", audio: true },
    { id: "w211", de: "das Wasser", en: "the water", part: "noun n.", audio: true },
    { id: "w212", de: "wechseln", en: "to change", part: "verb", audio: true },
    { id: "w213", de: "weg", en: "away, gone", part: "adverb", audio: true },
    { id: "w214", de: "der Weg", en: "the way, the path", part: "noun m.", audio: true },
    { id: "w215", de: "weggehen", en: "to go away", part: "verb", audio: true },
    { id: "w216", de: "weh tun", en: "to hurt", part: "verb", audio: true },
    { id: "w217", de: "weil", en: "because (verb at the end)", part: "particle / preposition", audio: true },
    { id: "w218", de: "der Wein", en: "the wine", part: "noun m.", audio: true },
    { id: "w219", de: "weiß", en: "white", part: "adjective", audio: true },
    { id: "w220", de: "weit", en: "far, wide", part: "adjective", audio: true },
    { id: "w221", de: "weiter", en: "further, on", part: "adverb", audio: true },
    { id: "w222", de: "welcher", en: "which", part: "noun m.", audio: true },
    { id: "w223", de: "die Welle", en: "the wave", part: "noun f.", audio: true },
    { id: "w224", de: "die Welt", en: "the world", part: "noun f.", audio: true },
    { id: "w225", de: "wenig", en: "little, few", part: "adverb", audio: true },
    { id: "w226", de: "wenn", en: "when, if", part: "particle / preposition", audio: true },
    { id: "w227", de: "wer", en: "who", part: "adverb", audio: true },
    { id: "w228", de: "werden", en: "to become, will", part: "verb", audio: true },
    { id: "w229", de: "werfen", en: "to throw", part: "verb", audio: true },
    { id: "w230", de: "das Werkzeug", en: "the tool", part: "noun n.", audio: true },
    { id: "w231", de: "der Westen", en: "the west", part: "noun m.", audio: true },
    { id: "w232", de: "das Wetter", en: "the weather", part: "noun n.", audio: true },
    { id: "w233", de: "wichtig", en: "important", part: "adjective", audio: true },
    { id: "w234", de: "wie", en: "how, like", part: "adverb", audio: true },
    { id: "w235", de: "wieder", en: "again", part: "adverb", audio: true },
    { id: "w236", de: "wiedersehen", en: "to see again", part: "verb", audio: true },
    { id: "w237", de: "die Wiese", en: "the meadow", part: "noun f.", audio: true },
    { id: "w238", de: "das Wild", en: "the game (animals)", part: "noun n.", audio: true },
    { id: "w239", de: "willkommen", en: "welcome", part: "adjective", audio: true },
    { id: "w240", de: "der Wind", en: "the wind", part: "noun m.", audio: true },
    { id: "w241", de: "das Winter", en: "the winter", part: "noun n.", audio: true },
    { id: "w242", de: "der Winter", en: "the winter", part: "noun m.", audio: true },
    { id: "w243", de: "wir", en: "we", part: "noun m.", audio: true },
    { id: "w244", de: "wirklich", en: "really, real", part: "adverb", audio: true },
    { id: "w245", de: "die Wirtschaft", en: "the economy", part: "noun f.", audio: true },
    { id: "w246", de: "wissen", en: "to know (a fact)", part: "verb", audio: true },
    { id: "w247", de: "wo", en: "where", part: "adverb", audio: true },
    { id: "w248", de: "die Woche", en: "the week", part: "noun f.", audio: true },
    { id: "w249", de: "das Wochenende", en: "the weekend", part: "noun n.", audio: true },
    { id: "w250", de: "woher", en: "where from", part: "adverb", audio: true },
    { id: "w251", de: "wohin", en: "where to", part: "adverb", audio: true },
    { id: "w252", de: "wohnen", en: "to live, to reside", part: "verb", audio: true },
    { id: "w253", de: "die Wohnung", en: "the apartment", part: "noun f.", audio: true },
    { id: "w254", de: "wollen", en: "to want", part: "verb", audio: true },
    { id: "w255", de: "das Wort", en: "the word", part: "noun n.", audio: true },
    { id: "w256", de: "die Wunde", en: "the wound", part: "noun f.", audio: true },
    { id: "w257", de: "die Wurst", en: "the sausage", part: "noun f.", audio: true },
    { id: "w258", de: "die Zahl", en: "the number", part: "noun f.", audio: true },
    { id: "w259", de: "zahlen", en: "to pay", part: "verb", audio: true },
    { id: "w260", de: "zählen", en: "to count", part: "verb", audio: true },
    { id: "w261", de: "zahm", en: "tame", part: "adjective", audio: true },
    { id: "w262", de: "der Zahn", en: "the tooth", part: "noun m.", audio: true },
    { id: "w263", de: "zeigen", en: "to show", part: "verb", audio: true },
    { id: "w264", de: "die Zeit", en: "the time", part: "noun f.", audio: true },
    { id: "w265", de: "die Zeitung", en: "the newspaper", part: "noun f.", audio: true },
    { id: "w266", de: "das Zentrum", en: "the centre", part: "noun n.", audio: true },
    { id: "w267", de: "zerreißen", en: "to tear apart", part: "verb", audio: true },
    { id: "w268", de: "das Zeugnis", en: "the certificate, the report card", part: "noun n.", audio: true },
    { id: "w269", de: "ziehen", en: "to pull, to move", part: "verb", audio: true },
    { id: "w270", de: "das Ziel", en: "the goal, the destination", part: "noun n.", audio: true },
    { id: "w271", de: "das Zimmer", en: "the room", part: "noun n.", audio: true },
    { id: "w272", de: "der Zoll", en: "the customs", part: "noun m.", audio: true },
    { id: "w273", de: "zu", en: "to, too (with adjective)", part: "particle / preposition", audio: true },
    { id: "w274", de: "zubereiten", en: "to prepare (food)", part: "verb", audio: true },
    { id: "w275", de: "der Zucker", en: "the sugar", part: "noun m.", audio: true },
    { id: "w276", de: "zufrieden", en: "satisfied, content", part: "adjective", audio: true },
    { id: "w277", de: "der Zug", en: "the train", part: "noun m.", audio: true },
    { id: "w278", de: "die Zukunft", en: "the future", part: "noun f.", audio: true },
    { id: "w279", de: "zumachen", en: "to close", part: "verb", audio: true },
    { id: "w280", de: "zurück", en: "back", part: "adverb", audio: true },
    { id: "w281", de: "zurückgeben", en: "to give back", part: "verb", audio: true },
    { id: "w282", de: "zusammen", en: "together", part: "adverb", audio: true },
    { id: "w283", de: "zuschauen", en: "to watch", part: "verb", audio: true },
    { id: "w284", de: "der Zustand", en: "the condition, the state", part: "noun m.", audio: true },
    { id: "w285", de: "zuverlässig", en: "reliable", part: "adjective", audio: true },
    { id: "w286", de: "zwanzig", en: "twenty", part: "noun m.", audio: true },
    { id: "w287", de: "zwei", en: "two", part: "noun m.", audio: true },
    { id: "w288", de: "der Zweck", en: "the purpose", part: "noun m.", audio: true },
    { id: "w289", de: "zweimal", en: "twice", part: "adverb", audio: true },
    { id: "w290", de: "zwischen", en: "between", part: "particle / preposition", audio: true },
  ],
  exercises: [
{"id": "ex-sz-1", "type": "multiple-choice", "title": "Übung 1", "instruction": "Choose the correct translation.", "prompt": "Was heißt 'die Unterschrift'?", "options": ["the signature", "the underline", "the understanding"], "correctIndex": 0, "explain": "die Unterschrift is the signature."},
{"id": "ex-sz-2", "type": "multiple-choice", "title": "Übung 2", "instruction": "Choose the correct translation.", "prompt": "Was heißt 'zufrieden'?", "options": ["satisfied", "angry", "tired"], "correctIndex": 0, "explain": "zufrieden means satisfied."},
{"id": "ex-sz-3", "type": "multiple-choice", "title": "Übung 3", "instruction": "Choose the word that fits.", "prompt": "Ich muss in Hamburg ___.", "options": ["umsteigen", "umtauschen", "unterstreichen"], "correctIndex": 0, "explain": "Changing trains is umsteigen."},
{"id": "ex-sz-4", "type": "fill-blank", "title": "Übung 4", "instruction": "Type the missing verb.", "sentence": "Ich ___ dich heute an. (rufen)", "blanks": [{"answers": ["rufe"], "hint": "anrufen, ich"}]},
{"id": "ex-sz-5", "type": "multiple-choice", "title": "Übung 5", "instruction": "Choose the word that fits.", "prompt": "Das ___ ist im dritten Stock.", "options": ["Zimmer", "Zucker", "Zug"], "correctIndex": 0, "explain": "das Zimmer is the room."},
{"id": "ex-sz-6", "type": "word-order", "title": "Übung 6", "instruction": "Build the sentence: I understand the question.", "chunks": ["Ich", "verstehe", "die", "Frage."], "explain": "verstehen takes the accusative."}
  ],
};
