import type { Lesson } from "../../../schema";

export const wortschatzEI: Lesson = {
  id: "wortschatz-e-i",
  title: "Wortschatz E-I",
  summary: "The official Goethe A1 word list, letters E to I.",
  status: "ready",
  sections: [
    { heading: "Wörter von E bis I", blocks: [
      { type: 'paragraph', text: "This lesson covers the official Goethe A1 word list from E to I: the words of family and friendship (die Eltern, der Freund, feiern), food (das Ei, das Essen, das Frühstück), money and travel (der Euro, die Fahrkarte, der Flughafen), and the question of feelings (das Gefühl, glücklich, das Glück)." },
      { type: 'paragraph', text: "Notice how many words are families again: essen, das Essen; fahren, der Fahrer, die Fahrkarte; frei, die Freiheit; froh, sich freuen. The Goethe list deliberately includes these families so that one stem teaches you several words." }
    ] }
  ],
  vocab: [
    { id: "w001", de: "egal", en: "all the same", part: "adjective", audio: true },
    { id: "w002", de: "das Ei", en: "the egg", part: "noun n.", audio: true },
    { id: "w003", de: "eigentlich", en: "actually", part: "adverb", audio: true },
    { id: "w004", de: "ein", en: "a, one (masculine/neuter article)", part: "article", audio: true },
    { id: "w005", de: "eine", en: "a, one (feminine article)", part: "article", audio: true },
    { id: "w006", de: "der Eingang", en: "the entrance", part: "noun m.", audio: true },
    { id: "w007", de: "einkaufen", en: "to shop", part: "verb", audio: true },
    { id: "w008", de: "einladen", en: "to invite", part: "verb", audio: true },
    { id: "w009", de: "die Einladung", en: "the invitation", part: "noun f.", audio: true },
    { id: "w010", de: "einmal", en: "once, one time", part: "adverb", audio: true },
    { id: "w011", de: "einsteigen", en: "to get in (transport)", part: "verb", audio: true },
    { id: "w012", de: "der Eintritt", en: "the admission, entrance fee", part: "noun m.", audio: true },
    { id: "w013", de: "einzeln", en: "single, separate", part: "adjective", audio: true },
    { id: "w014", de: "der Ehemann", en: "the husband", part: "noun m.", audio: true },
    { id: "w015", de: "die Ehefrau", en: "the wife", part: "noun f.", audio: true },
    { id: "w016", de: "die Eltern", en: "the parents", part: "noun f.", audio: true },
    { id: "w017", de: "die E-Mail", en: "the email", part: "noun f.", audio: true },
    { id: "w018", de: "empfangen", en: "to receive", part: "verb", audio: true },
    { id: "w019", de: "das Ende", en: "the end", part: "noun n.", audio: true },
    { id: "w020", de: "endlich", en: "finally", part: "adverb", audio: true },
    { id: "w021", de: "eng", en: "narrow, tight", part: "adjective", audio: true },
    { id: "w022", de: "entdecken", en: "to discover", part: "verb", audio: true },
    { id: "w023", de: "entschuldigen", en: "to excuse", part: "verb", audio: true },
    { id: "w024", de: "entschuldigung", en: "excuse me", part: "interjection", audio: true },
    { id: "w025", de: "er", en: "he, it (for masculine nouns)", part: "pronoun", audio: true },
    { id: "w026", de: "erklären", en: "to explain", part: "verb", audio: true },
    { id: "w027", de: "erlauben", en: "to allow", part: "verb", audio: true },
    { id: "w028", de: "das Essen", en: "the food, the meal", part: "noun n.", audio: true },
    { id: "w029", de: "essen", en: "to eat", part: "verb", audio: true },
    { id: "w030", de: "der Essig", en: "the vinegar", part: "noun m.", audio: true },
    { id: "w031", de: "etwas", en: "something", part: "adverb", audio: true },
    { id: "w032", de: "die Etage", en: "the floor, the storey", part: "noun f.", audio: true },
    { id: "w033", de: "euer", en: "your (plural informal)", part: "pronoun", audio: true },
    { id: "w034", de: "der Euro", en: "the euro", part: "noun m.", audio: true },
    { id: "w035", de: "Europa", en: "Europe", part: "noun n.", audio: true },
    { id: "w036", de: "europäisch", en: "European", part: "adjective", audio: true },
    { id: "w037", de: "extra", en: "extra, separately", part: "adverb", audio: true },
    { id: "w038", de: "fahren", en: "to drive, travel", part: "verb", audio: true },
    { id: "w039", de: "der Fahrer", en: "the driver", part: "noun m.", audio: true },
    { id: "w040", de: "die Fahrkarte", en: "the ticket", part: "noun f.", audio: true },
    { id: "w041", de: "das Fahrrad", en: "the bicycle", part: "noun n.", audio: true },
    { id: "w042", de: "der Fall", en: "the case", part: "noun m.", audio: true },
    { id: "w043", de: "falsch", en: "wrong", part: "adjective", audio: true },
    { id: "w044", de: "die Familie", en: "the family", part: "noun f.", audio: true },
    { id: "w045", de: "die Farbe", en: "the color", part: "noun f.", audio: true },
    { id: "w046", de: "farbig", en: "colored", part: "adjective", audio: true },
    { id: "w047", de: "fast", en: "almost", part: "adverb", audio: true },
    { id: "w048", de: "fegen", en: "to sweep", part: "verb", audio: true },
    { id: "w049", de: "fehlen", en: "to be missing, to lack", part: "verb", audio: true },
    { id: "w050", de: "der Fehler", en: "the mistake", part: "noun m.", audio: true },
    { id: "w051", de: "die Feier", en: "the party, the celebration", part: "noun f.", audio: true },
    { id: "w052", de: "feiern", en: "to celebrate", part: "verb", audio: true },
    { id: "w053", de: "das Fenster", en: "the window", part: "noun n.", audio: true },
    { id: "w054", de: "fernsehen", en: "to watch TV", part: "verb", audio: true },
    { id: "w055", de: "der Fernseher", en: "the television", part: "noun m.", audio: true },
    { id: "w056", de: "fertig", en: "finished, ready", part: "adjective", audio: true },
    { id: "w057", de: "fest", en: "firm, fixed", part: "adjective", audio: true },
    { id: "w058", de: "das Fest", en: "the festival", part: "noun n.", audio: true },
    { id: "w059", de: "das Feuer", en: "the fire", part: "noun n.", audio: true },
    { id: "w060", de: "das Fieber", en: "the fever", part: "noun n.", audio: true },
    { id: "w061", de: "der Film", en: "the film", part: "noun m.", audio: true },
    { id: "w062", de: "finden", en: "to find", part: "verb", audio: true },
    { id: "w063", de: "der Finger", en: "the finger", part: "noun m.", audio: true },
    { id: "w064", de: "die Firma", en: "the company", part: "noun f.", audio: true },
    { id: "w065", de: "das Fleisch", en: "the meat", part: "noun n.", audio: true },
    { id: "w066", de: "fliegen", en: "to fly", part: "verb", audio: true },
    { id: "w067", de: "der Flughafen", en: "the airport", part: "noun m.", audio: true },
    { id: "w068", de: "das Flugzeug", en: "the airplane", part: "noun n.", audio: true },
    { id: "w069", de: "der Flur", en: "the hallway", part: "noun m.", audio: true },
    { id: "w070", de: "der Fluss", en: "the river", part: "noun m.", audio: true },
    { id: "w071", de: "die Flüssigkeit", en: "the liquid", part: "noun f.", audio: true },
    { id: "w072", de: "folgen", en: "to follow", part: "verb", audio: true },
    { id: "w073", de: "die Frage", en: "the question", part: "noun f.", audio: true },
    { id: "w074", de: "fragen", en: "to ask", part: "verb", audio: true },
    { id: "w075", de: "Frankreich", en: "France", part: "noun n.", audio: true },
    { id: "w076", de: "die Frau", en: "the woman, Mrs", part: "noun f.", audio: true },
    { id: "w077", de: "frei", en: "free", part: "adjective", audio: true },
    { id: "w078", de: "die Freiheit", en: "the freedom", part: "noun f.", audio: true },
    { id: "w079", de: "freuen", en: "to be glad", part: "verb", audio: true },
    { id: "w080", de: "der Freund", en: "the friend (male)", part: "noun m.", audio: true },
    { id: "w081", de: "die Freundin", en: "the friend (female)", part: "noun f.", audio: true },
    { id: "w082", de: "freundlich", en: "friendly", part: "adjective", audio: true },
    { id: "w083", de: "der Frieden", en: "the peace", part: "noun m.", audio: true },
    { id: "w084", de: "frisch", en: "fresh", part: "adjective", audio: true },
    { id: "w085", de: "früh", en: "early", part: "adjective", audio: true },
    { id: "w086", de: "früher", en: "earlier, in the past", part: "adverb", audio: true },
    { id: "w087", de: "der Frühling", en: "the spring", part: "noun m.", audio: true },
    { id: "w088", de: "das Frühstück", en: "the breakfast", part: "noun n.", audio: true },
    { id: "w089", de: "frühstücken", en: "to have breakfast", part: "verb", audio: true },
    { id: "w090", de: "der Füller", en: "the fountain pen", part: "noun m.", audio: true },
    { id: "w091", de: "fünf", en: "five", part: "numeral", audio: true },
    { id: "w092", de: "fünfzehn", en: "fifteen", part: "numeral", audio: true },
    { id: "w093", de: "fünfzig", en: "fifty", part: "numeral", audio: true },
    { id: "w094", de: "funktionieren", en: "to work, function", part: "verb", audio: true },
    { id: "w095", de: "für", en: "for", part: "particle / preposition", audio: true },
    { id: "w096", de: "der Fuß", en: "the foot", part: "noun m.", audio: true },
    { id: "w097", de: "der Fußball", en: "the football", part: "noun m.", audio: true },
    { id: "w098", de: "der Gast", en: "the guest", part: "noun m.", audio: true },
    { id: "w099", de: "das Gebäude", en: "the building", part: "noun n.", audio: true },
    { id: "w100", de: "geben", en: "to give", part: "verb", audio: true },
    { id: "w101", de: "das Gebiet", en: "the area, the region", part: "noun n.", audio: true },
    { id: "w102", de: "gebrauchen", en: "to use", part: "verb", audio: true },
    { id: "w103", de: "die Gebühr", en: "the fee", part: "noun f.", audio: true },
    { id: "w104", de: "die Geburt", en: "the birth", part: "noun f.", audio: true },
    { id: "w105", de: "das Geburtsdatum", en: "the date of birth", part: "noun n.", audio: true },
    { id: "w106", de: "der Geburtstag", en: "the birthday", part: "noun m.", audio: true },
    { id: "w107", de: "das Gedächtnis", en: "the memory", part: "noun n.", audio: true },
    { id: "w108", de: "das Gefühl", en: "the feeling", part: "noun n.", audio: true },
    { id: "w109", de: "gegen", en: "against", part: "particle / preposition", audio: true },
    { id: "w110", de: "gegenüber", en: "opposite", part: "particle / preposition", audio: true },
    { id: "w111", de: "gehen", en: "to go, to walk", part: "verb", audio: true },
    { id: "w112", de: "gehören", en: "to belong to", part: "verb", audio: true },
    { id: "w113", de: "das Gehalt", en: "the salary", part: "noun n.", audio: true },
    { id: "w114", de: "gelb", en: "yellow", part: "adjective", audio: true },
    { id: "w115", de: "das Geld", en: "the money", part: "noun n.", audio: true },
    { id: "w116", de: "gemeinsam", en: "together, joint", part: "adjective", audio: true },
    { id: "w117", de: "das Gemüse", en: "the vegetables", part: "noun n.", audio: true },
    { id: "w118", de: "genau", en: "exact, exactly", part: "adjective", audio: true },
    { id: "w119", de: "genug", en: "enough", part: "adverb", audio: true },
    { id: "w120", de: "das Gepäck", en: "the luggage", part: "noun n.", audio: true },
    { id: "w121", de: "gerade", en: "straight, just now", part: "adverb", audio: true },
    { id: "w122", de: "geradeaus", en: "straight ahead", part: "adverb", audio: true },
    { id: "w123", de: "gern", en: "gladly, likes to", part: "adverb", audio: true },
    { id: "w124", de: "das Gerücht", en: "the rumor", part: "noun n.", audio: true },
    { id: "w125", de: "das Geschenk", en: "the present, the gift", part: "noun n.", audio: true },
    { id: "w126", de: "die Geschichte", en: "the story, the history", part: "noun f.", audio: true },
    { id: "w127", de: "die Geschwister", en: "the siblings", part: "noun f.", audio: true },
    { id: "w128", de: "das Gesicht", en: "the face", part: "noun n.", audio: true },
    { id: "w129", de: "das Gespräch", en: "the conversation", part: "noun n.", audio: true },
    { id: "w130", de: "gestern", en: "yesterday", part: "adverb", audio: true },
    { id: "w131", de: "gesund", en: "healthy", part: "adjective", audio: true },
    { id: "w132", de: "das Getränk", en: "the drink", part: "noun n.", audio: true },
    { id: "w133", de: "gewinnen", en: "to win", part: "verb", audio: true },
    { id: "w134", de: "das Glas", en: "the glass", part: "noun n.", audio: true },
    { id: "w135", de: "glauben", en: "to believe", part: "verb", audio: true },
    { id: "w136", de: "gleich", en: "same, immediately", part: "adverb", audio: true },
    { id: "w137", de: "das Glück", en: "the luck", part: "noun n.", audio: true },
    { id: "w138", de: "glücklich", en: "happy", part: "adjective", audio: true },
    { id: "w139", de: "das Gold", en: "the gold", part: "noun n.", audio: true },
    { id: "w140", de: "der Gratis", en: "free of charge", part: "noun m.", audio: true },
    { id: "w141", de: "grau", en: "grey", part: "adjective", audio: true },
    { id: "w142", de: "greifen", en: "to grab, reach", part: "verb", audio: true },
    { id: "w143", de: "groß", en: "big, tall", part: "adjective", audio: true },
    { id: "w144", de: "die Größe", en: "the size", part: "noun f.", audio: true },
    { id: "w145", de: "grün", en: "green", part: "adjective", audio: true },
    { id: "w146", de: "der Gruß", en: "the greeting", part: "noun m.", audio: true },
    { id: "w147", de: "gültig", en: "valid", part: "adjective", audio: true },
    { id: "w148", de: "günstig", en: "cheap, favorable", part: "adjective", audio: true },
    { id: "w149", de: "gut", en: "good", part: "adjective", audio: true },
    { id: "w150", de: "das Haar", en: "the hair", part: "noun n.", audio: true },
    { id: "w151", de: "haben", en: "to have", part: "verb", audio: true },
    { id: "w152", de: "der Hafen", en: "the harbor", part: "noun m.", audio: true },
    { id: "w153", de: "halb", en: "half", part: "adjective", audio: true },
    { id: "w154", de: "die Hälfte", en: "the half", part: "noun f.", audio: true },
    { id: "w155", de: "die Halle", en: "the hall", part: "noun f.", audio: true },
    { id: "w156", de: "hallo", en: "hello", part: "interjection", audio: true },
    { id: "w157", de: "der Hals", en: "the neck, the throat", part: "noun m.", audio: true },
    { id: "w158", de: "halten", en: "to hold, to stop", part: "verb", audio: true },
    { id: "w159", de: "die Haltestelle", en: "the stop", part: "noun f.", audio: true },
    { id: "w160", de: "die Hand", en: "the hand", part: "noun f.", audio: true },
    { id: "w161", de: "das Handy", en: "the mobile phone", part: "noun n.", audio: true },
    { id: "w162", de: "hängen", en: "to hang", part: "verb", audio: true },
    { id: "w163", de: "häufig", en: "frequent", part: "adjective", audio: true },
    { id: "w164", de: "das Haus", en: "the house", part: "noun n.", audio: true },
    { id: "w165", de: "die Hausfrau", en: "the housewife", part: "noun f.", audio: true },
    { id: "w166", de: "der Haushalt", en: "the household", part: "noun m.", audio: true },
    { id: "w167", de: "das Heft", en: "the notebook", part: "noun n.", audio: true },
    { id: "w168", de: "heiraten", en: "to marry", part: "verb", audio: true },
    { id: "w169", de: "heißen", en: "to be called", part: "verb", audio: true },
    { id: "w170", de: "heiß", en: "hot", part: "adjective", audio: true },
    { id: "w171", de: "helfen", en: "to help", part: "verb", audio: true },
    { id: "w172", de: "hell", en: "bright, light", part: "adjective", audio: true },
    { id: "w173", de: "das Hemd", en: "the shirt", part: "noun n.", audio: true },
    { id: "w174", de: "heraus", en: "out (direction)", part: "adverb", audio: true },
    { id: "w175", de: "der Herbst", en: "the autumn", part: "noun m.", audio: true },
    { id: "w176", de: "der Herd", en: "the stove", part: "noun m.", audio: true },
    { id: "w177", de: "der Herr", en: "the gentleman, Mr", part: "noun m.", audio: true },
    { id: "w178", de: "herzlich", en: "hearty, cordial", part: "adjective", audio: true },
    { id: "w179", de: "heute", en: "today", part: "adverb", audio: true },
    { id: "w180", de: "hier", en: "here", part: "adverb", audio: true },
    { id: "w181", de: "die Hilfe", en: "the help", part: "noun f.", audio: true },
    { id: "w182", de: "der Himmel", en: "the sky", part: "noun m.", audio: true },
    { id: "w183", de: "hin", en: "to, towards", part: "adverb", audio: true },
    { id: "w184", de: "hinten", en: "at the back", part: "adverb", audio: true },
    { id: "w185", de: "hinter", en: "behind", part: "particle / preposition", audio: true },
    { id: "w186", de: "das Hochhaus", en: "the high-rise building", part: "noun n.", audio: true },
    { id: "w187", de: "hoch", en: "high, tall", part: "adjective", audio: true },
    { id: "w188", de: "holen", en: "to fetch, get", part: "verb", audio: true },
    { id: "w189", de: "das Holz", en: "the wood", part: "noun n.", audio: true },
    { id: "w190", de: "hören", en: "to hear, listen", part: "verb", audio: true },
    { id: "w191", de: "die Hose", en: "the pants, the trousers", part: "noun f.", audio: true },
    { id: "w192", de: "das Hotel", en: "the hotel", part: "noun n.", audio: true },
    { id: "w193", de: "hübsch", en: "pretty", part: "adjective", audio: true },
    { id: "w194", de: "der Hund", en: "the dog", part: "noun m.", audio: true },
    { id: "w195", de: "der Hunger", en: "the hunger", part: "noun m.", audio: true },
    { id: "w196", de: "husten", en: "to cough", part: "verb", audio: true },
    { id: "w197", de: "der Husten", en: "the cough", part: "noun m.", audio: true },
    { id: "w198", de: "die Idee", en: "the idea", part: "noun f.", audio: true },
    { id: "w199", de: "ihr", en: "her, their, you (plural)", part: "pronoun", audio: true },
    { id: "w200", de: "Ihr", en: "your (formal)", part: "noun m.", audio: true },
    { id: "w201", de: "immer", en: "always", part: "adverb", audio: true },
    { id: "w202", de: "in", en: "in, into", part: "particle / preposition", audio: true },
    { id: "w203", de: "die Information", en: "the information", part: "noun f.", audio: true },
    { id: "w204", de: "das Informationsbüro", en: "the information office", part: "noun n.", audio: true },
    { id: "w205", de: "der Ingenieur", en: "the engineer", part: "noun m.", audio: true },
    { id: "w206", de: "der Inhalt", en: "the content", part: "noun m.", audio: true },
    { id: "w207", de: "innen", en: "inside", part: "adverb", audio: true },
    { id: "w208", de: "interessant", en: "interesting", part: "adjective", audio: true },
    { id: "w209", de: "das Interesse", en: "the interest", part: "noun n.", audio: true },
    { id: "w210", de: "sich interessieren", en: "to be interested in", part: "verb", audio: true },
    { id: "w211", de: "das Internet", en: "the internet", part: "noun n.", audio: true },
    { id: "w212", de: "italienisch", en: "Italian", part: "adjective", audio: true },
    { id: "w213", de: "Italien", en: "Italy", part: "noun n.", audio: true },
  ],
  exercises: [
{"id": "ex-ei-1", "type": "multiple-choice", "title": "Übung 1", "instruction": "Choose the word that fits.", "prompt": "Ich habe einen Termin beim ___.", "options": ["Arzt", "Essig", "Herd"], "correctIndex": 0, "explain": "der Arzt is the doctor."},
{"id": "ex-ei-2", "type": "multiple-choice", "title": "Übung 2", "instruction": "Choose the correct translation.", "prompt": "Was heißt 'die Eltern'?", "options": ["the parents", "the elderly", "the children"], "correctIndex": 0, "explain": "die Eltern are the parents."},
{"id": "ex-ei-3", "type": "multiple-choice", "title": "Übung 3", "instruction": "Choose the correct translation.", "prompt": "Was heißt 'das Frühstück'?", "options": ["the breakfast", "the lunch", "the dinner"], "correctIndex": 0, "explain": "das Frühstück is breakfast."},
{"id": "ex-ei-4", "type": "fill-blank", "title": "Übung 4", "instruction": "Type the missing verb.", "sentence": "Wir ___ um zwölf Uhr ab. (fahren)", "translation": "We ___ at twelve o'clock. (depart)", "blanks": [{"answers": ["fahren"], "hint": "abfahren, wir"}]},
{"id": "ex-ei-5", "type": "multiple-choice", "title": "Übung 5", "instruction": "Choose the word that fits.", "prompt": "Ich brauche eine ___ nach Berlin.", "options": ["Fahrkarte", "Gebühr", "Hose"], "correctIndex": 0, "explain": "die Fahrkarte is the ticket."},
{"id": "ex-ei-6", "type": "word-order", "title": "Übung 6", "instruction": "Build the sentence: I am flying to Berlin.", "chunks": ["Ich", "fliege", "nach", "Berlin."], "translation": "I am flying to Berlin.", "explain": "The destination follows the verb."}
  ],
};
