import type { Lesson } from "../../../schema";

export const wortschatzAD: Lesson = {
  id: "wortschatz-a-d",
  title: "Wortschatz A-D",
  summary: "The official Goethe A1 word list, letters A to D.",
  status: "ready",
  sections: [
    { heading: "Wörter von A bis D", blocks: [
      { type: 'paragraph', text: "This lesson covers the official Goethe A1 word list from A to D: everyday verbs, the words of the first days in Germany (Anmeldung, Ausweis, Arbeitsplatz), and the basic building blocks (aber, auch, also, bald, bitte)." },
      { type: 'paragraph', text: "Notice the patterns as you go: nouns come with their article (der Arm, das Auge, die Adresse), verbs with their meaning, and several words are families: arbeiten, die Arbeit, arbeitslos, der Arbeitsplatz. Learn the family together and four words cost as much as one." }
    ] }
  ],
  vocab: [
    { id: "w001", de: "ab", en: "from, as of", part: "particle / preposition", audio: true },
    { id: "w002", de: "aber", en: "but", part: "particle / preposition", audio: true },
    { id: "w003", de: "abfahren", en: "to depart", part: "verb", audio: true },
    { id: "w004", de: "die Abfahrt", en: "the departure", part: "noun f.", audio: true },
    { id: "w005", de: "abgeben", en: "to hand in, drop off", part: "verb", audio: true },
    { id: "w006", de: "abholen", en: "to pick up", part: "verb", audio: true },
    { id: "w007", de: "der Absender", en: "the sender", part: "noun m.", audio: true },
    { id: "w008", de: "Achtung", en: "attention, caution", part: "interjection", audio: true },
    { id: "w009", de: "die Adresse", en: "the address", part: "noun f.", audio: true },
    { id: "w010", de: "allein", en: "alone", part: "adverb", audio: true },
    { id: "w011", de: "also", en: "so, therefore", part: "adverb", audio: true },
    { id: "w012", de: "alt", en: "old", part: "adjective", audio: true },
    { id: "w013", de: "das Alter", en: "the age", part: "noun n.", audio: true },
    { id: "w014", de: "an", en: "at, on", part: "particle / preposition", audio: true },
    { id: "w015", de: "anbieten", en: "to offer", part: "verb", audio: true },
    { id: "w016", de: "das Angebot", en: "the offer, the special", part: "noun n.", audio: true },
    { id: "w017", de: "anfangen", en: "to begin", part: "verb", audio: true },
    { id: "w018", de: "der Anfang", en: "the beginning", part: "noun m.", audio: true },
    { id: "w019", de: "anklicken", en: "to click on", part: "verb", audio: true },
    { id: "w020", de: "ankommen", en: "to arrive", part: "verb", audio: true },
    { id: "w021", de: "die Ankunft", en: "the arrival", part: "noun f.", audio: true },
    { id: "w022", de: "ankreuzen", en: "to tick, mark", part: "verb", audio: true },
    { id: "w023", de: "anmachen", en: "to turn on", part: "verb", audio: true },
    { id: "w024", de: "die Anmeldung", en: "the registration", part: "noun f.", audio: true },
    { id: "w025", de: "die Anrede", en: "the form of address", part: "noun f.", audio: true },
    { id: "w026", de: "anrufen", en: "to call", part: "verb", audio: true },
    { id: "w027", de: "der Anruf", en: "the call", part: "noun m.", audio: true },
    { id: "w028", de: "die Ansage", en: "the announcement", part: "noun f.", audio: true },
    { id: "w029", de: "der Anschluss", en: "the connection", part: "noun m.", audio: true },
    { id: "w030", de: "antworten", en: "to answer", part: "verb", audio: true },
    { id: "w031", de: "die Antwort", en: "the answer", part: "noun f.", audio: true },
    { id: "w032", de: "die Anzeige", en: "the advertisement, the notice", part: "noun f.", audio: true },
    { id: "w033", de: "das Apartment", en: "the apartment", part: "noun n.", audio: true },
    { id: "w034", de: "der Apfel", en: "the apple", part: "noun m.", audio: true },
    { id: "w035", de: "der Appetit", en: "the appetite", part: "noun m.", audio: true },
    { id: "w036", de: "arbeiten", en: "to work", part: "verb", audio: true },
    { id: "w037", de: "die Arbeit", en: "the work, the job", part: "noun f.", audio: true },
    { id: "w038", de: "arbeitslos", en: "unemployed", part: "adjective", audio: true },
    { id: "w039", de: "der Arbeitsplatz", en: "the workplace", part: "noun m.", audio: true },
    { id: "w040", de: "der Arm", en: "the arm", part: "noun m.", audio: true },
    { id: "w041", de: "der Arzt", en: "the doctor", part: "noun m.", audio: true },
    { id: "w042", de: "auch", en: "also, too", part: "adverb", audio: true },
    { id: "w043", de: "auf", en: "on, onto", part: "particle / preposition", audio: true },
    { id: "w044", de: "der Aufenthalt", en: "the stay", part: "noun m.", audio: true },
    { id: "w045", de: "auf sein", en: "to be open", part: "particle / preposition", audio: true },
    { id: "w046", de: "aufstehen", en: "to get up", part: "verb", audio: true },
    { id: "w047", de: "das Auge", en: "the eye", part: "noun n.", audio: true },
    { id: "w048", de: "der Ausgang", en: "the exit", part: "noun m.", audio: true },
    { id: "w049", de: "ausgehen", en: "to go out", part: "verb", audio: true },
    { id: "w050", de: "ausfüllen", en: "to fill in", part: "verb", audio: true },
    { id: "w051", de: "aussehen", en: "to look (appearance)", part: "verb", audio: true },
    { id: "w052", de: "außer", en: "except", part: "particle / preposition", audio: true },
    { id: "w053", de: "aussteigen", en: "to get out (of transport)", part: "verb", audio: true },
    { id: "w054", de: "der Ausweis", en: "the ID card", part: "noun m.", audio: true },
    { id: "w055", de: "das Auto", en: "the car", part: "noun n.", audio: true },
    { id: "w056", de: "der Automat", en: "the machine", part: "noun m.", audio: true },
    { id: "w057", de: "automatisch", en: "automatic", part: "adjective", audio: true },
    { id: "w058", de: "die Bäckerei", en: "the bakery", part: "noun f.", audio: true },
    { id: "w059", de: "das Bad", en: "the bathroom", part: "noun n.", audio: true },
    { id: "w060", de: "die Badewanne", en: "the bathtub", part: "noun f.", audio: true },
    { id: "w061", de: "backen", en: "to bake", part: "verb", audio: true },
    { id: "w062", de: "der Bahnhof", en: "the train station", part: "noun m.", audio: true },
    { id: "w063", de: "bald", en: "soon", part: "adverb", audio: true },
    { id: "w064", de: "der Balkon", en: "the balcony", part: "noun m.", audio: true },
    { id: "w065", de: "die Banane", en: "the banana", part: "noun f.", audio: true },
    { id: "w066", de: "die Bank", en: "the bank; the bench", part: "noun f.", audio: true },
    { id: "w067", de: "bar", en: "cash", part: "adverb", audio: true },
    { id: "w068", de: "das Bargeld", en: "the cash", part: "noun n.", audio: true },
    { id: "w069", de: "der Bau", en: "the building site", part: "noun m.", audio: true },
    { id: "w070", de: "bauen", en: "to build", part: "verb", audio: true },
    { id: "w071", de: "der Baum", en: "the tree", part: "noun m.", audio: true },
    { id: "w072", de: "das Bäumchen", en: "the little tree", part: "noun n.", audio: true },
    { id: "w073", de: "das Becken", en: "the basin, the pool", part: "noun n.", audio: true },
    { id: "w074", de: "beginnen", en: "to begin", part: "verb", audio: true },
    { id: "w075", de: "behalten", en: "to keep", part: "verb", audio: true },
    { id: "w076", de: "bei", en: "at, with, near", part: "particle / preposition", audio: true },
    { id: "w077", de: "das Beispiel", en: "the example", part: "noun n.", audio: true },
    { id: "w078", de: "bekommen", en: "to get, receive", part: "verb", audio: true },
    { id: "w079", de: "benötigen", en: "to need", part: "verb", audio: true },
    { id: "w080", de: "der Bericht", en: "the report", part: "noun m.", audio: true },
    { id: "w081", de: "der Beruf", en: "the profession", part: "noun m.", audio: true },
    { id: "w082", de: "beruflich", en: "professional, work-related", part: "adjective", audio: true },
    { id: "w083", de: "besichtigen", en: "to visit, view", part: "verb", audio: true },
    { id: "w084", de: "besonders", en: "especially", part: "adverb", audio: true },
    { id: "w085", de: "besser", en: "better", part: "adjective", audio: true },
    { id: "w086", de: "bestellen", en: "to order", part: "verb", audio: true },
    { id: "w087", de: "der Besuch", en: "the visit", part: "noun m.", audio: true },
    { id: "w088", de: "besuchen", en: "to visit", part: "verb", audio: true },
    { id: "w089", de: "der Besucher", en: "the visitor", part: "noun m.", audio: true },
    { id: "w090", de: "betreten", en: "to enter", part: "verb", audio: true },
    { id: "w091", de: "die Beule", en: "the bump, the dent", part: "noun f.", audio: true },
    { id: "w092", de: "bewölkt", en: "cloudy", part: "adjective", audio: true },
    { id: "w093", de: "bezahlen", en: "to pay", part: "verb", audio: true },
    { id: "w094", de: "das Bier", en: "the beer", part: "noun n.", audio: true },
    { id: "w095", de: "bieten", en: "to offer", part: "verb", audio: true },
    { id: "w096", de: "das Bild", en: "the picture", part: "noun n.", audio: true },
    { id: "w097", de: "billig", en: "cheap", part: "adjective", audio: true },
    { id: "w098", de: "bis", en: "until, to", part: "particle / preposition", audio: true },
    { id: "w099", de: "ein bisschen", en: "a little bit", part: "particle / preposition", audio: true },
    { id: "w100", de: "bitte", en: "please, you're welcome", part: "interjection", audio: true },
    { id: "w101", de: "blau", en: "blue", part: "adjective", audio: true },
    { id: "w102", de: "bleiben", en: "to stay", part: "verb", audio: true },
    { id: "w103", de: "der Blick", en: "the view, the look", part: "noun m.", audio: true },
    { id: "w104", de: "das Blut", en: "the blood", part: "noun n.", audio: true },
    { id: "w105", de: "der Boden", en: "the floor, the ground", part: "noun m.", audio: true },
    { id: "w106", de: "das Brot", en: "the bread", part: "noun n.", audio: true },
    { id: "w107", de: "das Brötchen", en: "the roll", part: "noun n.", audio: true },
    { id: "w108", de: "der Bruder", en: "the brother", part: "noun m.", audio: true },
    { id: "w109", de: "das Buch", en: "the book", part: "noun n.", audio: true },
    { id: "w110", de: "buchstabieren", en: "to spell", part: "verb", audio: true },
    { id: "w111", de: "die Bucht", en: "the bay", part: "noun f.", audio: true },
    { id: "w112", de: "das Bügeleisen", en: "the iron", part: "noun n.", audio: true },
    { id: "w113", de: "das Büro", en: "the office", part: "noun n.", audio: true },
    { id: "w114", de: "der Bus", en: "the bus", part: "noun m.", audio: true },
    { id: "w115", de: "die Butter", en: "the butter", part: "noun f.", audio: true },
    { id: "w116", de: "das Café", en: "the café", part: "noun n.", audio: true },
    { id: "w117", de: "die CD", en: "the CD", part: "noun f.", audio: true },
    { id: "w118", de: "der Cent", en: "the cent", part: "noun m.", audio: true },
    { id: "w119", de: "die Cola", en: "the cola", part: "noun f.", audio: true },
    { id: "w120", de: "der Computer", en: "the computer", part: "noun m.", audio: true },
    { id: "w121", de: "der Cousin", en: "the cousin (male)", part: "noun m.", audio: true },
    { id: "w122", de: "die Cousine", en: "the cousin (female)", part: "noun f.", audio: true },
    { id: "w123", de: "das Dach", en: "the roof", part: "noun n.", audio: true },
    { id: "w124", de: "dafür", en: "for that", part: "adverb", audio: true },
    { id: "w125", de: "die Dame", en: "the lady", part: "noun f.", audio: true },
    { id: "w126", de: "danach", en: "after that", part: "adverb", audio: true },
    { id: "w127", de: "danke", en: "thanks", part: "interjection", audio: true },
    { id: "w128", de: "danken", en: "to thank", part: "verb", audio: true },
    { id: "w129", de: "dann", en: "then", part: "adverb", audio: true },
    { id: "w130", de: "das Datum", en: "the date", part: "noun n.", audio: true },
    { id: "w131", de: "dauern", en: "to last", part: "verb", audio: true },
    { id: "w132", de: "dazu", en: "in addition, for that", part: "adverb", audio: true },
    { id: "w133", de: "die Decke", en: "the ceiling; the blanket", part: "noun f.", audio: true },
    { id: "w134", de: "denken", en: "to think", part: "verb", audio: true },
    { id: "w135", de: "denn", en: "because, then", part: "particle / preposition", audio: true },
    { id: "w136", de: "der", en: "the (masculine article)", part: "article", audio: true },
    { id: "w137", de: "deshalb", en: "therefore", part: "adverb", audio: true },
    { id: "w138", de: "das", en: "the (neuter article)", part: "article", audio: true },
    { id: "w139", de: "deutsch", en: "German", part: "adjective", audio: true },
    { id: "w140", de: "der Deutsche", en: "the German (person)", part: "noun m.", audio: true },
    { id: "w141", de: "Deutschland", en: "Germany", part: "noun n.", audio: true },
    { id: "w142", de: "dick", en: "thick, fat", part: "adjective", audio: true },
    { id: "w143", de: "die", en: "the (feminine article)", part: "article", audio: true },
    { id: "w144", de: "der Dienst", en: "the service", part: "noun m.", audio: true },
    { id: "w145", de: "Dienstag", en: "Tuesday", part: "noun m.", audio: true },
    { id: "w146", de: "der Dienstag", en: "Tuesday", part: "noun m.", audio: true },
    { id: "w147", de: "dieser", en: "this (demonstrative)", part: "pronoun", audio: true },
    { id: "w148", de: "das Ding", en: "the thing", part: "noun n.", audio: true },
    { id: "w149", de: "direkt", en: "direct, straight", part: "adjective", audio: true },
    { id: "w150", de: "doch", en: "yes (contradicting), after all", part: "interjection", audio: true },
    { id: "w151", de: "der Doktor", en: "the doctor (title)", part: "noun m.", audio: true },
    { id: "w152", de: "das Dokument", en: "the document", part: "noun n.", audio: true },
    { id: "w153", de: "Donnerstag", en: "Thursday", part: "noun m.", audio: true },
    { id: "w154", de: "der Donnerstag", en: "Thursday", part: "noun m.", audio: true },
    { id: "w155", de: "doppelt", en: "double", part: "adjective", audio: true },
    { id: "w156", de: "dort", en: "there", part: "adverb", audio: true },
    { id: "w157", de: "der Drucker", en: "the printer", part: "noun m.", audio: true },
    { id: "w158", de: "du", en: "you (informal)", part: "pronoun", audio: true },
    { id: "w159", de: "dunkel", en: "dark", part: "adjective", audio: true },
    { id: "w160", de: "dünn", en: "thin", part: "adjective", audio: true },
    { id: "w161", de: "durch", en: "through", part: "particle / preposition", audio: true },
    { id: "w162", de: "dürfen", en: "to be allowed to", part: "verb", audio: true },
    { id: "w163", de: "der Durst", en: "the thirst", part: "noun m.", audio: true },
    { id: "w164", de: "die Dusche", en: "the shower", part: "noun f.", audio: true },
    { id: "w165", de: "duschen", en: "to shower", part: "verb", audio: true },
  ],
  exercises: [
{"id": "ex-ad-1", "type": "multiple-choice", "title": "Übung 1", "instruction": "Choose the word that fits the sentence.", "prompt": "Ich muss mich beim Bürgeramt ___.", "options": ["anmelden", "ankommen", "aussteigen"], "correctIndex": 0, "explain": "Registering is sich anmelden."},
{"id": "ex-ad-2", "type": "multiple-choice", "title": "Übung 2", "instruction": "Choose the correct translation.", "prompt": "Was heißt 'die Anmeldung'?", "options": ["the registration", "the arrival", "the address"], "correctIndex": 0, "explain": "die Anmeldung is the registration."},
{"id": "ex-ad-3", "type": "multiple-choice", "title": "Übung 3", "instruction": "Choose the correct translation.", "prompt": "Was heißt 'arbeitslos'?", "options": ["unemployed", "the workplace", "to work"], "correctIndex": 0, "explain": "arbeitslos means unemployed."},
{"id": "ex-ad-4", "type": "fill-blank", "title": "Übung 4", "instruction": "Type the missing verb.", "sentence": "Wir ___ um zwölf Uhr ab. (fahren)", "translation": "We ___ at twelve o'clock. (depart)", "blanks": [{"answers": ["fahren"], "hint": "abfahren, wir"}]},
{"id": "ex-ad-5", "type": "multiple-choice", "title": "Übung 5", "instruction": "Choose the word that fits.", "prompt": "Ich habe einen Termin beim ___.", "options": ["Arzt", "Apfel", "Buch"], "correctIndex": 0, "explain": "The doctor is der Arzt."},
{"id": "ex-ad-6", "type": "word-order", "title": "Übung 6", "instruction": "Build the sentence: I am arriving in Hamburg.", "chunks": ["Ich", "komme", "in", "Hamburg", "an."], "translation": "I am arriving in Hamburg.", "explain": "ankommen splits: komme ... an."}
  ],
};
