import type { Lesson } from "../../../schema";

export const wortschatzJM: Lesson = {
  id: "wortschatz-j-m",
  title: "Wortschatz J-M",
  summary: "The official Goethe A1 word list, letters J to M.",
  status: "ready",
  sections: [
    { heading: "Wörter von J bis M", blocks: [
      { type: 'paragraph', text: "This lesson covers the official Goethe A1 word list from J to M: family and people (der Junge, das Kind, die Leute, der Mann), food and kitchen (der Käse, die Kartoffel, kochen, die Küche), shopping and money (kaufen, das Konto, die Kreditkarte), and health (krank, das Krankenhaus, die Krankheit)." },
      { type: 'paragraph', text: "Two patterns worth naming: verbs with mit- (mitbringen, mitkommen, mitnehmen) all mean doing something together with someone, and words ending in -heit, -keit, -ung, -tion are almost always feminine: die Krankheit, die Möglichkeit, die Wohnung, die Information." }
    ] }
  ],
  vocab: [
    { id: "w001", de: "ja", en: "yes", part: "interjection", audio: true },
    { id: "w002", de: "die Jacke", en: "the jacket", part: "noun f.", audio: true },
    { id: "w003", de: "das Jahr", en: "the year", part: "noun n.", audio: true },
    { id: "w004", de: "der Januar", en: "January", part: "noun m.", audio: true },
    { id: "w005", de: "Japan", en: "Japan", part: "noun n.", audio: true },
    { id: "w006", de: "japanisch", en: "Japanese", part: "adjective", audio: true },
    { id: "w007", de: "jeder", en: "every, each", part: "pronoun", audio: true },
    { id: "w008", de: "jemand", en: "someone", part: "pronoun", audio: true },
    { id: "w009", de: "jetzt", en: "now", part: "adverb", audio: true },
    { id: "w010", de: "der Job", en: "the job", part: "noun m.", audio: true },
    { id: "w011", de: "der Joghurt", en: "the yogurt", part: "noun m.", audio: true },
    { id: "w012", de: "jubeln", en: "to cheer", part: "verb", audio: true },
    { id: "w013", de: "jung", en: "young", part: "adjective", audio: true },
    { id: "w014", de: "der Junge", en: "the boy", part: "noun m.", audio: true },
    { id: "w015", de: "die Kaffeemaschine", en: "the coffee machine", part: "noun f.", audio: true },
    { id: "w016", de: "der Kaffee", en: "the coffee", part: "noun m.", audio: true },
    { id: "w017", de: "kalt", en: "cold", part: "adjective", audio: true },
    { id: "w018", de: "die Kamera", en: "the camera", part: "noun f.", audio: true },
    { id: "w019", de: "der Kamm", en: "the comb", part: "noun m.", audio: true },
    { id: "w020", de: "das Kaninchen", en: "the rabbit", part: "noun n.", audio: true },
    { id: "w021", de: "der Karton", en: "the cardboard box", part: "noun m.", audio: true },
    { id: "w022", de: "der Käse", en: "the cheese", part: "noun m.", audio: true },
    { id: "w023", de: "die Karte", en: "the card, the map, the ticket", part: "noun f.", audio: true },
    { id: "w024", de: "der Kartoffelsalat", en: "the potato salad", part: "noun m.", audio: true },
    { id: "w025", de: "die Kartoffel", en: "the potato", part: "noun f.", audio: true },
    { id: "w026", de: "kaufen", en: "to buy", part: "verb", audio: true },
    { id: "w027", de: "der Kaufmann", en: "the merchant", part: "noun m.", audio: true },
    { id: "w028", de: "kaum", en: "hardly", part: "adverb", audio: true },
    { id: "w029", de: "kein", en: "no, not a (negative article)", part: "article", audio: true },
    { id: "w030", de: "keine", en: "no (feminine/plural, negative article)", part: "article", audio: true },
    { id: "w031", de: "kennen", en: "to know (someone)", part: "verb", audio: true },
    { id: "w032", de: "das Kind", en: "the child", part: "noun n.", audio: true },
    { id: "w033", de: "der Kindergarten", en: "the kindergarten", part: "noun m.", audio: true },
    { id: "w034", de: "das Kino", en: "the cinema", part: "noun n.", audio: true },
    { id: "w035", de: "die Kirche", en: "the church", part: "noun f.", audio: true },
    { id: "w036", de: "klar", en: "clear", part: "adjective", audio: true },
    { id: "w037", de: "die Klasse", en: "the class", part: "noun f.", audio: true },
    { id: "w038", de: "das Kleid", en: "the dress", part: "noun n.", audio: true },
    { id: "w039", de: "die Kleidung", en: "the clothing", part: "noun f.", audio: true },
    { id: "w040", de: "klein", en: "small", part: "adjective", audio: true },
    { id: "w041", de: "klettern", en: "to climb", part: "verb", audio: true },
    { id: "w042", de: "klingeln", en: "to ring", part: "verb", audio: true },
    { id: "w043", de: "der Koffer", en: "the suitcase", part: "noun m.", audio: true },
    { id: "w044", de: "der Kohl", en: "the cabbage", part: "noun m.", audio: true },
    { id: "w045", de: "kochen", en: "to cook", part: "verb", audio: true },
    { id: "w046", de: "kommen", en: "to come", part: "verb", audio: true },
    { id: "w047", de: "kompliziert", en: "complicated", part: "adjective", audio: true },
    { id: "w048", de: "können", en: "can, to be able to", part: "verb", audio: true },
    { id: "w049", de: "das Konto", en: "the bank account", part: "noun n.", audio: true },
    { id: "w050", de: "der Kontrolleur", en: "the ticket inspector", part: "noun m.", audio: true },
    { id: "w051", de: "der Kopf", en: "the head", part: "noun m.", audio: true },
    { id: "w052", de: "der Körper", en: "the body", part: "noun m.", audio: true },
    { id: "w053", de: "korrigieren", en: "to correct", part: "verb", audio: true },
    { id: "w054", de: "kosten", en: "to cost", part: "verb", audio: true },
    { id: "w055", de: "krank", en: "sick", part: "adjective", audio: true },
    { id: "w056", de: "das Krankenhaus", en: "the hospital", part: "noun n.", audio: true },
    { id: "w057", de: "die Krankheit", en: "the illness", part: "noun f.", audio: true },
    { id: "w058", de: "der Kredit", en: "the credit", part: "noun m.", audio: true },
    { id: "w059", de: "die Kreditkarte", en: "the credit card", part: "noun f.", audio: true },
    { id: "w060", de: "der Kreis", en: "the circle", part: "noun m.", audio: true },
    { id: "w061", de: "die Kreuzung", en: "the crossing, the junction", part: "noun f.", audio: true },
    { id: "w062", de: "der Krieg", en: "the war", part: "noun m.", audio: true },
    { id: "w063", de: "die Küche", en: "the kitchen", part: "noun f.", audio: true },
    { id: "w064", de: "der Kuchen", en: "the cake", part: "noun m.", audio: true },
    { id: "w065", de: "die Kugel", en: "the ball, the sphere", part: "noun f.", audio: true },
    { id: "w066", de: "kühl", en: "cool", part: "adjective", audio: true },
    { id: "w067", de: "der Kühlschrank", en: "the fridge", part: "noun m.", audio: true },
    { id: "w068", de: "kündigen", en: "to cancel, to quit", part: "verb", audio: true },
    { id: "w069", de: "der Kunde", en: "the customer", part: "noun m.", audio: true },
    { id: "w070", de: "die Kundin", en: "the customer (female)", part: "noun f.", audio: true },
    { id: "w071", de: "kurz", en: "short", part: "adjective", audio: true },
    { id: "w072", de: "die Lampe", en: "the lamp", part: "noun f.", audio: true },
    { id: "w073", de: "das Land", en: "the country", part: "noun n.", audio: true },
    { id: "w074", de: "lang", en: "long", part: "adjective", audio: true },
    { id: "w075", de: "langsam", en: "slow", part: "adjective", audio: true },
    { id: "w076", de: "langweilig", en: "boring", part: "adjective", audio: true },
    { id: "w077", de: "lassen", en: "to let, leave", part: "verb", audio: true },
    { id: "w078", de: "laufen", en: "to run, to walk", part: "verb", audio: true },
    { id: "w079", de: "laut", en: "loud", part: "adjective", audio: true },
    { id: "w080", de: "leben", en: "to live", part: "verb", audio: true },
    { id: "w081", de: "das Leben", en: "the life", part: "noun n.", audio: true },
    { id: "w082", de: "die Lebensmittel", en: "the groceries, food", part: "noun f.", audio: true },
    { id: "w083", de: "legen", en: "to put (flat)", part: "verb", audio: true },
    { id: "w084", de: "der Lehrer", en: "the teacher (male)", part: "noun m.", audio: true },
    { id: "w085", de: "die Lehrerin", en: "the teacher (female)", part: "noun f.", audio: true },
    { id: "w086", de: "leicht", en: "easy, light", part: "adjective", audio: true },
    { id: "w087", de: "leid tun", en: "to be sorry", part: "verb", audio: true },
    { id: "w088", de: "leider", en: "unfortunately", part: "adverb", audio: true },
    { id: "w089", de: "lernen", en: "to learn", part: "verb", audio: true },
    { id: "w090", de: "lesen", en: "to read", part: "verb", audio: true },
    { id: "w091", de: "letzt", en: "last", part: "adjective", audio: true },
    { id: "w092", de: "die Leute", en: "the people", part: "noun f.", audio: true },
    { id: "w093", de: "das Licht", en: "the light", part: "noun n.", audio: true },
    { id: "w094", de: "liegen", en: "to lie (flat)", part: "verb", audio: true },
    { id: "w095", de: "die Liebe", en: "the love", part: "noun f.", audio: true },
    { id: "w096", de: "lieben", en: "to love", part: "verb", audio: true },
    { id: "w097", de: "lieber", en: "rather, prefer", part: "adverb", audio: true },
    { id: "w098", de: "das Lied", en: "the song", part: "noun n.", audio: true },
    { id: "w099", de: "links", en: "left", part: "adverb", audio: true },
    { id: "w100", de: "die Liste", en: "the list", part: "noun f.", audio: true },
    { id: "w101", de: "der Löffel", en: "the spoon", part: "noun m.", audio: true },
    { id: "w102", de: "das Lokal", en: "the restaurant, the pub", part: "noun n.", audio: true },
    { id: "w103", de: "los", en: "off, going", part: "adverb", audio: true },
    { id: "w104", de: "das Los", en: "the lottery ticket", part: "noun n.", audio: true },
    { id: "w105", de: "die Luft", en: "the air", part: "noun f.", audio: true },
    { id: "w106", de: "die Lust", en: "the desire, the wish", part: "noun f.", audio: true },
    { id: "w107", de: "machen", en: "to make, to do", part: "verb", audio: true },
    { id: "w108", de: "das Mädchen", en: "the girl", part: "noun n.", audio: true },
    { id: "w109", de: "die Mahlzeit", en: "the meal", part: "noun f.", audio: true },
    { id: "w110", de: "mal", en: "once, times; (particle) just", part: "adverb", audio: true },
    { id: "w111", de: "man", en: "one, people in general", part: "pronoun", audio: true },
    { id: "w112", de: "manchmal", en: "sometimes", part: "adverb", audio: true },
    { id: "w113", de: "der Mann", en: "the man, the husband", part: "noun m.", audio: true },
    { id: "w114", de: "der Mantel", en: "the coat", part: "noun m.", audio: true },
    { id: "w115", de: "die Marmelade", en: "the jam", part: "noun f.", audio: true },
    { id: "w116", de: "die Maschine", en: "the machine", part: "noun f.", audio: true },
    { id: "w117", de: "das Maß", en: "the measure, the size", part: "noun n.", audio: true },
    { id: "w118", de: "die Mauer", en: "the wall", part: "noun f.", audio: true },
    { id: "w119", de: "die Maus", en: "the mouse", part: "noun f.", audio: true },
    { id: "w120", de: "das Medikament", en: "the medicine", part: "noun n.", audio: true },
    { id: "w121", de: "das Meer", en: "the sea", part: "noun n.", audio: true },
    { id: "w122", de: "mehr", en: "more", part: "adverb", audio: true },
    { id: "w123", de: "mein", en: "my", part: "pronoun", audio: true },
    { id: "w124", de: "meinen", en: "to think, to mean", part: "verb", audio: true },
    { id: "w125", de: "meistens", en: "mostly", part: "adverb", audio: true },
    { id: "w126", de: "der Mensch", en: "the human being", part: "noun m.", audio: true },
    { id: "w127", de: "das Messer", en: "the knife", part: "noun n.", audio: true },
    { id: "w128", de: "das Metall", en: "the metal", part: "noun n.", audio: true },
    { id: "w129", de: "mieten", en: "to rent", part: "verb", audio: true },
    { id: "w130", de: "die Miete", en: "the rent", part: "noun f.", audio: true },
    { id: "w131", de: "die Milch", en: "the milk", part: "noun f.", audio: true },
    { id: "w132", de: "die Minute", en: "the minute", part: "noun f.", audio: true },
    { id: "w133", de: "mit", en: "with", part: "particle / preposition", audio: true },
    { id: "w134", de: "mitbringen", en: "to bring along", part: "verb", audio: true },
    { id: "w135", de: "mitkommen", en: "to come along", part: "verb", audio: true },
    { id: "w136", de: "das Mitglied", en: "the member", part: "noun n.", audio: true },
    { id: "w137", de: "mitnehmen", en: "to take along", part: "verb", audio: true },
    { id: "w138", de: "die Mittagszeit", en: "the lunchtime", part: "noun f.", audio: true },
    { id: "w139", de: "das Mittagessen", en: "the lunch", part: "noun n.", audio: true },
    { id: "w140", de: "der Mittag", en: "the midday", part: "noun m.", audio: true },
    { id: "w141", de: "das Möbel", en: "the piece of furniture", part: "noun n.", audio: true },
    { id: "w142", de: "möchten", en: "would like to", part: "verb", audio: true },
    { id: "w143", de: "möglich", en: "possible", part: "adjective", audio: true },
    { id: "w144", de: "die Möglichkeit", en: "the possibility", part: "noun f.", audio: true },
    { id: "w145", de: "der Monat", en: "the month", part: "noun m.", audio: true },
    { id: "w146", de: "das Monatsticket", en: "the monthly ticket", part: "noun n.", audio: true },
    { id: "w147", de: "morgen", en: "tomorrow", part: "adverb", audio: true },
    { id: "w148", de: "der Morgen", en: "the morning", part: "noun m.", audio: true },
    { id: "w149", de: "müde", en: "tired", part: "adjective", audio: true },
    { id: "w150", de: "der Mund", en: "the mouth", part: "noun m.", audio: true },
    { id: "w151", de: "das Museum", en: "the museum", part: "noun n.", audio: true },
    { id: "w152", de: "die Musik", en: "the music", part: "noun f.", audio: true },
    { id: "w153", de: "müssen", en: "must, to have to", part: "verb", audio: true },
    { id: "w154", de: "die Mutter", en: "the mother", part: "noun f.", audio: true },
    { id: "w155", de: "die Mütze", en: "the cap", part: "noun f.", audio: true },
  ],
  exercises: [
{"id": "ex-jm-1", "type": "multiple-choice", "title": "Übung 1", "instruction": "Choose the correct translation.", "prompt": "Was heißt 'das Krankenhaus'?", "options": ["the hospital", "the pharmacy", "the doctor"], "correctIndex": 0, "explain": "das Krankenhaus is the hospital."},
{"id": "ex-jm-2", "type": "multiple-choice", "title": "Übung 2", "instruction": "Choose the correct translation.", "prompt": "Was heißt 'die Möglichkeit'?", "options": ["the possibility", "the memory", "the machine"], "correctIndex": 0, "explain": "die Möglichkeit is the possibility."},
{"id": "ex-jm-3", "type": "multiple-choice", "title": "Übung 3", "instruction": "Choose the word that fits.", "prompt": "Ich möchte ein Auto ___.", "options": ["mieten", "liegen", "klettern"], "correctIndex": 0, "explain": "Renting is mieten."},
{"id": "ex-jm-4", "type": "fill-blank", "title": "Übung 4", "instruction": "Type the missing verb.", "sentence": "Ich ___ gern Musik. (hören)", "translation": "I ___ music. (listen to)", "blanks": [{"answers": ["höre"], "hint": "hören, ich"}]},
{"id": "ex-jm-5", "type": "multiple-choice", "title": "Übung 5", "instruction": "Choose the word that fits.", "prompt": "Das ___ steht in der Küche.", "options": ["Kühlschrank", "Koffer", "Kopf"], "correctIndex": 0, "explain": "der Kühlschrank is the fridge."},
{"id": "ex-jm-6", "type": "word-order", "title": "Übung 6", "instruction": "Build the sentence: I would like to drink a coffee.", "chunks": ["Ich", "möchte", "einen", "Kaffee", "trinken."], "translation": "I would like to drink a coffee.", "explain": "The modal is second; the infinitive closes."}
  ],
};
