import type { Lesson } from "../../../schema";

export const wortschatzNR: Lesson = {
  id: "wortschatz-n-r",
  title: "Wortschatz N-R",
  summary: "The official Goethe A1 word list, letters N to R.",
  status: "ready",
  sections: [
    { heading: "Wörter von N bis R", blocks: [
      { type: 'paragraph', text: "This lesson covers the official Goethe A1 word list from N to R: directions and places (nach, der Norden, rechts, der Park, der Platz), travel (das Paket, der Pass, reisen, die Reise), shopping and money (der Preis, die Rechnung, die Quittung), and everyday necessities (öffnen, die Öffnungszeiten, die Pause)." },
      { type: 'paragraph', text: "Notice the small words that hold German together: noch, nur, nie, nichts, niemand, oft, ohne. They look tiny but they decide the meaning of whole sentences. Learn them in pairs: nie (never) and immer (always), nichts (nothing) and etwas (something)." }
    ] }
  ],
  vocab: [
    { id: "w001", de: "nach", en: "to, after", part: "particle / preposition", audio: true },
    { id: "w002", de: "der Nachbar", en: "the neighbor (male)", part: "noun m.", audio: true },
    { id: "w003", de: "die Nachbarin", en: "the neighbor (female)", part: "noun f.", audio: true },
    { id: "w004", de: "nachher", en: "afterwards", part: "adverb", audio: true },
    { id: "w005", de: "der Nachmittag", en: "the afternoon", part: "noun m.", audio: true },
    { id: "w006", de: "die Nachricht", en: "the message, the news", part: "noun f.", audio: true },
    { id: "w007", de: "der Nachname", en: "the last name", part: "noun m.", audio: true },
    { id: "w008", de: "die Nacht", en: "the night", part: "noun f.", audio: true },
    { id: "w009", de: "der Nagel", en: "the nail", part: "noun m.", audio: true },
    { id: "w010", de: "nah", en: "near, close", part: "adjective", audio: true },
    { id: "w011", de: "der Name", en: "the name", part: "noun m.", audio: true },
    { id: "w012", de: "die Nase", en: "the nose", part: "noun f.", audio: true },
    { id: "w013", de: "nehmen", en: "to take", part: "verb", audio: true },
    { id: "w014", de: "nein", en: "no", part: "interjection", audio: true },
    { id: "w015", de: "nennen", en: "to name, to call", part: "verb", audio: true },
    { id: "w016", de: "nervös", en: "nervous", part: "adjective", audio: true },
    { id: "w017", de: "das Netz", en: "the net, the network", part: "noun n.", audio: true },
    { id: "w018", de: "neu", en: "new", part: "adjective", audio: true },
    { id: "w019", de: "neugierig", en: "curious", part: "adjective", audio: true },
    { id: "w020", de: "nicht", en: "not", part: "adverb", audio: true },
    { id: "w021", de: "nichts", en: "nothing", part: "adverb", audio: true },
    { id: "w022", de: "nie", en: "never", part: "adverb", audio: true },
    { id: "w023", de: "niedrig", en: "low", part: "adjective", audio: true },
    { id: "w024", de: "niemand", en: "nobody", part: "noun m.", audio: true },
    { id: "w025", de: "noch", en: "still, yet", part: "adverb", audio: true },
    { id: "w026", de: "der Norden", en: "the north", part: "noun m.", audio: true },
    { id: "w027", de: "normal", en: "normal", part: "adjective", audio: true },
    { id: "w028", de: "die Not", en: "the emergency, the distress", part: "noun f.", audio: true },
    { id: "w029", de: "notwendig", en: "necessary", part: "adjective", audio: true },
    { id: "w030", de: "die Nummer", en: "the number", part: "noun f.", audio: true },
    { id: "w031", de: "nur", en: "only", part: "adverb", audio: true },
    { id: "w032", de: "ob", en: "whether", part: "particle / preposition", audio: true },
    { id: "w033", de: "oben", en: "above, upstairs", part: "adverb", audio: true },
    { id: "w034", de: "das Obst", en: "the fruit", part: "noun n.", audio: true },
    { id: "w035", de: "oder", en: "or", part: "particle / preposition", audio: true },
    { id: "w036", de: "der Ofen", en: "the oven, the stove", part: "noun m.", audio: true },
    { id: "w037", de: "offen", en: "open", part: "adjective", audio: true },
    { id: "w038", de: "öffnen", en: "to open", part: "verb", audio: true },
    { id: "w039", de: "die Öffnungszeiten", en: "the opening hours", part: "noun f.", audio: true },
    { id: "w040", de: "oft", en: "often", part: "adverb", audio: true },
    { id: "w041", de: "ohne", en: "without", part: "particle / preposition", audio: true },
    { id: "w042", de: "das Ohr", en: "the ear", part: "noun n.", audio: true },
    { id: "w043", de: "der Onkel", en: "the uncle", part: "noun m.", audio: true },
    { id: "w044", de: "das Oper", en: "the opera", part: "noun n.", audio: true },
    { id: "w045", de: "die Orange", en: "the orange (fruit)", part: "noun f.", audio: true },
    { id: "w046", de: "die Ordnung", en: "the order, the tidiness", part: "noun f.", audio: true },
    { id: "w047", de: "das Paket", en: "the parcel", part: "noun n.", audio: true },
    { id: "w048", de: "der Papierkorb", en: "the wastepaper basket", part: "noun m.", audio: true },
    { id: "w049", de: "das Papier", en: "the paper", part: "noun n.", audio: true },
    { id: "w050", de: "der Park", en: "the park", part: "noun m.", audio: true },
    { id: "w051", de: "parken", en: "to park", part: "verb", audio: true },
    { id: "w052", de: "der Parkplatz", en: "the parking space", part: "noun m.", audio: true },
    { id: "w053", de: "der Pass", en: "the passport", part: "noun m.", audio: true },
    { id: "w054", de: "passen", en: "to fit", part: "verb", audio: true },
    { id: "w055", de: "passieren", en: "to happen", part: "verb", audio: true },
    { id: "w056", de: "die Pause", en: "the break", part: "noun f.", audio: true },
    { id: "w057", de: "die Person", en: "the person", part: "noun f.", audio: true },
    { id: "w058", de: "der Pfeffer", en: "the pepper", part: "noun m.", audio: true },
    { id: "w059", de: "das Pflaster", en: "the plaster, the band-aid", part: "noun n.", audio: true },
    { id: "w060", de: "die Pflanze", en: "the plant", part: "noun f.", audio: true },
    { id: "w061", de: "die Pille", en: "the pill", part: "noun f.", audio: true },
    { id: "w062", de: "die Pizza", en: "the pizza", part: "noun f.", audio: true },
    { id: "w063", de: "der Plan", en: "the plan, the map", part: "noun m.", audio: true },
    { id: "w064", de: "der Platz", en: "the place, the square, the seat", part: "noun m.", audio: true },
    { id: "w065", de: "die Polizei", en: "the police", part: "noun f.", audio: true },
    { id: "w066", de: "der Polizist", en: "the police officer", part: "noun m.", audio: true },
    { id: "w067", de: "die Politik", en: "the politics", part: "noun f.", audio: true },
    { id: "w068", de: "die Portion", en: "the portion", part: "noun f.", audio: true },
    { id: "w069", de: "die Post", en: "the post office, the mail", part: "noun f.", audio: true },
    { id: "w070", de: "der Preis", en: "the price", part: "noun m.", audio: true },
    { id: "w071", de: "die Prüfung", en: "the exam", part: "noun f.", audio: true },
    { id: "w072", de: "das Publikum", en: "the audience", part: "noun n.", audio: true },
    { id: "w073", de: "der Punkt", en: "the point, the dot", part: "noun m.", audio: true },
    { id: "w074", de: "das Quadrat", en: "the square (shape)", part: "noun n.", audio: true },
    { id: "w075", de: "die Qualität", en: "the quality", part: "noun f.", audio: true },
    { id: "w076", de: "die Quittung", en: "the receipt", part: "noun f.", audio: true },
    { id: "w077", de: "das Radio", en: "the radio", part: "noun n.", audio: true },
    { id: "w078", de: "der Rand", en: "the edge", part: "noun m.", audio: true },
    { id: "w079", de: "die Rechnung", en: "the bill, the invoice", part: "noun f.", audio: true },
    { id: "w080", de: "recht haben", en: "to be right", part: "verb", audio: true },
    { id: "w081", de: "rechts", en: "right (direction)", part: "adverb", audio: true },
    { id: "w082", de: "das Regal", en: "the shelf", part: "noun n.", audio: true },
    { id: "w083", de: "der Regen", en: "the rain", part: "noun m.", audio: true },
    { id: "w084", de: "regnen", en: "to rain", part: "verb", audio: true },
    { id: "w085", de: "reich", en: "rich", part: "adjective", audio: true },
    { id: "w086", de: "das Reich", en: "the empire, the realm", part: "noun n.", audio: true },
    { id: "w087", de: "reisen", en: "to travel", part: "verb", audio: true },
    { id: "w088", de: "die Reise", en: "the journey, the trip", part: "noun f.", audio: true },
    { id: "w089", de: "der Reis", en: "the rice", part: "noun m.", audio: true },
    { id: "w090", de: "die Reklamation", en: "the complaint", part: "noun f.", audio: true },
    { id: "w091", de: "rennen", en: "to run", part: "verb", audio: true },
    { id: "w092", de: "das Restaurant", en: "the restaurant", part: "noun n.", audio: true },
    { id: "w093", de: "das Rezept", en: "the recipe, the prescription", part: "noun n.", audio: true },
    { id: "w094", de: "richtig", en: "correct, right", part: "adjective", audio: true },
    { id: "w095", de: "die Richtung", en: "the direction", part: "noun f.", audio: true },
    { id: "w096", de: "riechen", en: "to smell", part: "verb", audio: true },
    { id: "w097", de: "der Rücken", en: "the back", part: "noun m.", audio: true },
    { id: "w098", de: "rufen", en: "to call", part: "verb", audio: true },
    { id: "w099", de: "ruhig", en: "quiet, calm", part: "adjective", audio: true },
    { id: "w100", de: "rund", en: "round", part: "adjective", audio: true },
  ],
  exercises: [
{"id": "ex-nr-1", "type": "multiple-choice", "title": "Übung 1", "instruction": "Choose the correct translation.", "prompt": "Was heißt 'die Rechnung'?", "options": ["the bill", "the receipt", "the price"], "correctIndex": 0, "explain": "die Rechnung is the bill."},
{"id": "ex-nr-2", "type": "multiple-choice", "title": "Übung 2", "instruction": "Choose the correct translation.", "prompt": "Was heißt 'rechts'?", "options": ["right (direction)", "left", "straight"], "correctIndex": 0, "explain": "rechts means right."},
{"id": "ex-nr-3", "type": "multiple-choice", "title": "Übung 3", "instruction": "Choose the word that fits.", "prompt": "Ich brauche eine ___ für das Paket.", "options": ["Quittung", "Rechnung", "Pizza"], "correctIndex": 0, "explain": "die Quittung is the receipt."},
{"id": "ex-nr-4", "type": "fill-blank", "title": "Übung 4", "instruction": "Type the missing verb.", "sentence": "Wir ___ nach Berlin. (reisen)", "blanks": [{"answers": ["reisen"], "hint": "reisen, wir"}]},
{"id": "ex-nr-5", "type": "multiple-choice", "title": "Übung 5", "instruction": "Choose the word that fits.", "prompt": "Der Zug hat zehn Minuten ___.", "options": ["Verspätung", "Quittung", "Richtung"], "correctIndex": 0, "explain": "die Verspätung is the delay."},
{"id": "ex-nr-6", "type": "word-order", "title": "Übung 6", "instruction": "Build the sentence: The parcel is on the table.", "chunks": ["Das", "Paket", "liegt", "auf", "dem", "Tisch."], "explain": "Static location takes the dative."}
  ],
};
