import type { Lesson, Unit } from "../../schema";

export const berufe: Lesson = {
  id: "berufe",
  title: "Berufe",
  summary:
    "The complete professions system for A1: the jobs, the gender pairs, asking about work, and the job verbs.",
  status: "ready",
  sections: [
    {
      heading: "Die Berufe",
      blocks: [
        {
          type: "paragraph",
          text: "The professions (die Berufe) come in gender pairs: der Lehrer and die Lehrerin, der Arzt and die Ärztin, der Verkäufer and die Verkäuferin. The question about work: Was bist du von Beruf? (What do you do for a living?) and the answer: Ich bin Lehrer. (I am a teacher.).",
        },
        {
          type: "table",
          caption: "The professions",
          head: ["Male", "Female", "English"],
          rows: [
            ["der Lehrer", "die Lehrerin", "the teacher"],
            ["der Arzt", "die Ärztin", "the doctor"],
            ["der Verkäufer", "die Verkäuferin", "the shop assistant"],
            ["der Ingenieur", "die Ingenieurin", "the engineer"],
            ["der Koch", "die Köchin", "the cook"],
            ["der Fahrer", "die Fahrerin", "the driver"],
            ["der Polizist", "die Polizistin", "the police officer"],
            ["der Student", "die Studentin", "the student"],
          ],
        },
        {
          type: "example",
          de: "Was bist du von Beruf? Ich bin Lehrer. Und was machst du? Ich unterrichte Deutsch.",
          en: "The profession dialogue.",
        },
        {
          type: "tip",
          text: "The profession phrase: Was bist du von Beruf? and Ich bin + profession, without an article: Ich bin Lehrer.",
        },
      ],
    },
    {
      heading: "Die weiblichen Formen",
      blocks: [
        {
          type: "paragraph",
          text: "The feminine profession forms add -in: der Lehrer → die Lehrerin, der Arzt → die Ärztin. The plural of the feminine adds -nen: die Lehrerinnen, die Ärztinnen. The female form always follows the male one in the dictionary, and many professions have both.",
        },
        {
          type: "table",
          caption: "The feminine forms",
          head: ["Male", "Female", "Female plural"],
          rows: [
            ["der Lehrer", "die Lehrerin", "die Lehrerinnen"],
            ["der Arzt", "die Ärztin", "die Ärztinnen"],
            ["der Verkäufer", "die Verkäuferin", "die Verkäuferinnen"],
            ["der Koch", "die Köchin", "die Köchinnen"],
            ["der Student", "die Studentin", "die Studentinnen"],
          ],
        },
        {
          type: "example",
          de: "Meine Schwester ist Ärztin. Meine Mutter ist Lehrerin. Die Köchinnen arbeiten im Restaurant.",
          en: "The feminine professions.",
        },
        {
          type: "tip",
          text: "The feminine pattern: stem + in (Lehrerin), plural + nen (Lehrerinnen). The umlaut: der Koch → die Köchin.",
        },
      ],
    },
    {
      heading: "Die Arbeitsverben",
      blocks: [
        {
          type: "paragraph",
          text: "The work verbs: arbeiten (to work), unterrichten (to teach), verkaufen (to sell), kochen (to cook), fahren (to drive), behandeln (to treat, of doctors). The question: Wo arbeitest du? (Where do you work?) and the answer: Ich arbeite in einer Schule. (I work in a school.).",
        },
        {
          type: "table",
          caption: "The work verbs",
          head: ["Verb", "English", "Example"],
          rows: [
            ["arbeiten", "to work", "Ich arbeite in einer Schule."],
            ["unterrichten", "to teach", "Er unterrichtet Deutsch."],
            ["verkaufen", "to sell", "Sie verkauft Kleidung."],
            ["kochen", "to cook", "Er kocht im Restaurant."],
            ["fahren", "to drive", "Ich fahre Bus."],
            ["behandeln", "to treat", "Die Ärztin behandelt Patienten."],
          ],
        },
        {
          type: "example",
          de: "Ich arbeite in einer Schule und unterrichte Deutsch. Meine Frau arbeitet im Krankenhaus.",
          en: "The work sentences.",
        },
        {
          type: "tip",
          text: "The work location: Ich arbeite in + dative. in einer Schule, in einem Büro, im Krankenhaus.",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: the article after sein, the feminine forms, and mixing the work verbs.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["article after sein", "Ich bin ein Lehrer.", "Ich bin Lehrer.", "professions after sein take no article"],
            ["feminine form", "die Lehrer für eine Frau", "die Lehrerin", "the feminine adds -in"],
            ["work verb mix", "Ich arbeite Bus.", "Ich fahre Bus.", "driving takes fahren"],
            ["wrong location", "Ich arbeite in Schule.", "Ich arbeite in einer Schule.", "the location takes the article"],
            ["gender mix", "die Koch für einen Mann", "der Koch", "the masculine is der Koch"],
          ],
        },
        {
          type: "tip",
          text: "The profession topic is a script: Was bist du von Beruf? Ich bin + profession, the feminine -in form, and the work verb.",
        },
      ],
    },
  ],
  vocab: [
    { id: "der-beruf", de: "der Beruf", en: "the profession", part: "noun m.", plural: "die Berufe", audio: true },
    { id: "der-lehrer", de: "der Lehrer", en: "the teacher (male)", part: "noun m.", plural: "die Lehrer", audio: true },
    { id: "die-lehrerin", de: "die Lehrerin", en: "the teacher (female)", part: "noun f.", plural: "die Lehrerinnen", audio: true },
    { id: "der-arzt", de: "der Arzt", en: "the doctor (male)", part: "noun m.", plural: "die Ärzte", audio: true },
    { id: "die-aerztin", de: "die Ärztin", en: "the doctor (female)", part: "noun f.", plural: "die Ärztinnen", audio: true },
    { id: "der-verkaeufer", de: "der Verkäufer", en: "the shop assistant (male)", part: "noun m.", plural: "die Verkäufer", audio: true },
    { id: "die-verkaeuferin", de: "die Verkäuferin", en: "the shop assistant (female)", part: "noun f.", plural: "die Verkäuferinnen", audio: true },
    { id: "der-ingenieur", de: "der Ingenieur", en: "the engineer", part: "noun m.", plural: "die Ingenieure", audio: true },
    { id: "der-koch", de: "der Koch", en: "the cook (male)", part: "noun m.", plural: "die Köche", audio: true },
    { id: "die-koechin", de: "die Köchin", en: "the cook (female)", part: "noun f.", plural: "die Köchinnen", audio: true },
    { id: "der-fahrer", de: "der Fahrer", en: "the driver", part: "noun m.", plural: "die Fahrer", audio: true },
    { id: "der-polizist", de: "der Polizist", en: "the police officer", part: "noun m.", plural: "die Polizisten", audio: true },
    { id: "die-polizistin", de: "die Polizistin", en: "the police officer (female)", part: "noun f.", plural: "die Polizistinnen", audio: true },
    { id: "der-student", de: "der Student", en: "the student", part: "noun m.", plural: "die Studenten", audio: true },
    { id: "die-studentin", de: "die Studentin", en: "the student (female)", part: "noun f.", plural: "die Studentinnen", audio: true },
    { id: "der-kellner", de: "der Kellner", en: "the waiter", part: "noun m.", plural: "die Kellner", audio: true },
    { id: "die-kellnerin", de: "die Kellnerin", en: "the waitress", part: "noun f.", plural: "die Kellnerinnen", audio: true },
    { id: "arbeiten", de: "arbeiten", en: "to work", part: "verb", audio: true },
    { id: "unterrichten", de: "unterrichten", en: "to teach", part: "verb", audio: true },
    { id: "verkaufen", de: "verkaufen", en: "to sell", part: "verb", audio: true },
    { id: "kochen", de: "kochen", en: "to cook", part: "verb", audio: true },
    { id: "die-arbeit", de: "die Arbeit", en: "the work", part: "noun f.", plural: "die Arbeiten", audio: true },
    { id: "das-buero", de: "das Büro", en: "the office", part: "noun n.", plural: "die Büros", audio: true },
    { id: "die-schule", de: "die Schule", en: "the school", part: "noun f.", plural: "die Schulen", audio: true },
    { id: "was-bist-du-von-beruf", de: "Was bist du von Beruf?", en: "What do you do for a living?", part: "phrase", phrase: true, audio: true },
    { id: "ich-bin-lehrer", de: "Ich bin Lehrer.", en: "I am a teacher.", part: "phrase", phrase: true, audio: true },
    { id: "wo-arbeitest-du", de: "Wo arbeitest du?", en: "Where do you work?", part: "phrase", phrase: true, audio: true },
    { id: "ich-arbeite-in-einer-schule", de: "Ich arbeite in einer Schule.", en: "I work in a school.", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-berufe",
      type: "matching",
      title: "Übung 1: Die Berufe",
      instruction: "Match each profession to its meaning.",
      pairs: [
        ["der Lehrer", "the teacher"],
        ["der Arzt", "the doctor"],
        ["der Verkäufer", "the shop assistant"],
        ["der Ingenieur", "the engineer"],
        ["der Koch", "the cook"],
        ["der Polizist", "the police officer"],
      ],
    },
    {
      id: "ex-weiblich",
      type: "matching",
      title: "Übung 2: Die weiblichen Formen",
      instruction: "Match each male form to its female form.",
      pairs: [
        ["der Lehrer", "die Lehrerin"],
        ["der Arzt", "die Ärztin"],
        ["der Koch", "die Köchin"],
        ["der Student", "die Studentin"],
        ["der Kellner", "die Kellnerin"],
      ],
    },
    {
      id: "ex-frage",
      type: "multiple-choice",
      title: "Übung 3: Die Berufsfrage",
      instruction: "Choose the profession question.",
      prompt: "You ask what someone does for a living.",
      options: ["Was bist du von Beruf?", "Was machst du Beruf?", "Wo bist du von Beruf?"],
      correctIndex: 0,
      explain: "The profession question: Was bist du von Beruf?",
    },
    {
      id: "ex-antwort",
      type: "multiple-choice",
      title: "Übung 4: Die Berufsantwort",
      instruction: "Choose the profession answer.",
      prompt: "I am a teacher.",
      options: ["Ich bin Lehrer.", "Ich bin ein Lehrer.", "Ich bin der Lehrer."],
      correctIndex: 0,
      explain: "Professions after sein take no article.",
    },
    {
      id: "ex-weiblich-2",
      type: "multiple-choice",
      title: "Übung 5: Die weibliche Form",
      instruction: "Choose the female form.",
      prompt: "der Arzt → ...",
      options: ["die Ärztin", "die Arztin", "die Ärztin?"],
      correctIndex: 0,
      explain: "The feminine adds -in with the umlaut.",
    },
    {
      id: "ex-arbeit",
      type: "multiple-choice",
      title: "Übung 6: Die Arbeit",
      instruction: "Choose the work sentence.",
      prompt: "I work in a school.",
      options: ["Ich arbeite in einer Schule.", "Ich arbeite in ein Schule.", "Ich arbeite in der Schule? Nein, in einer Schule."],
      correctIndex: 0,
      explain: "The work location: in einer Schule.",
    },
    {
      id: "ex-verb",
      type: "multiple-choice",
      title: "Übung 7: Das Arbeitsverb",
      instruction: "Choose the correct verb.",
      prompt: "Er ___ Deutsch.",
      options: ["unterrichtet", "arbeitet", "verkauft"],
      correctIndex: 0,
      explain: "Teaching takes unterrichten.",
    },
    {
      id: "ex-wo",
      type: "multiple-choice",
      title: "Übung 8: Wo arbeitest du?",
      instruction: "Choose the work question.",
      prompt: "You ask where someone works.",
      options: ["Wo arbeitest du?", "Was arbeitest du?", "Wie arbeitest du?"],
      correctIndex: 0,
      explain: "The work location question: Wo?",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 9: Hören",
      instruction: "Play the audio and pick the profession you heard.",
      prompt: "der Arzt",
      options: ["der Arzt", "der Koch", "der Lehrer"],
      correctIndex: 0,
      explain: "The profession heard: doctor.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 10: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Ich bin Lehrer.",
      options: ["Ich bin Lehrer.", "Ich bin Koch.", "Ich bin Student."],
      correctIndex: 0,
      explain: "The profession sentence heard.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 11: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Ich bin Lehrer.", "Ich bin ein Lehrer.", "Ich bin der Lehrer."],
      correctIndex: 0,
      explain: "Professions take no article after sein.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 12: Der Satz",
      instruction: "Build the sentence: I am a teacher.",
      chunks: ["Ich", "bin", "Lehrer."],
      explain: "The profession without an article.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 13: Der Satz",
      instruction: "Build the sentence: I work in a school.",
      chunks: ["Ich", "arbeite", "in", "einer", "Schule."],
      explain: "The work location.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 14: Berufskarten",
      instruction: "Say the German with the article out loud.",
      items: [
        { front: "der Lehrer", back: "the teacher (male)", frontAudio: true },
        { front: "die Lehrerin", back: "the teacher (female)", frontAudio: true },
        { front: "der Arzt", back: "the doctor (male)", frontAudio: true },
        { front: "die Ärztin", back: "the doctor (female)", frontAudio: true },
        { front: "der Koch", back: "the cook (male)", frontAudio: true },
        { front: "die Köchin", back: "the cook (female)", frontAudio: true },
        { front: "der Student", back: "the student", frontAudio: true },
        { front: "die Studentin", back: "the student (female)", frontAudio: true },
        { front: "Was bist du von Beruf?", back: "What do you do for a living?", frontAudio: true },
        { front: "Ich bin Lehrer.", back: "I am a teacher.", frontAudio: true },
        { front: "arbeiten", back: "to work", frontAudio: true },
        { front: "Wo arbeitest du?", back: "Where do you work?", frontAudio: true },
      ],
    },
  ],
};

export const praepositionenMitDativ: Lesson = {
  id: "praepositionen-mit-dativ",
  title: "Präpositionen mit Dativ",
  summary:
    "The dative prepositions: mit, nach, bei, seit, von, zu, aus, außer, gegenüber and the complete declension table for A1.",
  status: "ready",
  sections: [
    {
      heading: "Die Dativpräpositionen",
      blocks: [
        {
          type: "paragraph",
          text: "Nine prepositions always take the dative: aus (out of, from), bei (at), mit (with), nach (after, to), seit (since), von (from, of), zu (to), außer (except), gegenüber (opposite). After them, der becomes dem, die becomes der, das becomes dem, and the plural becomes den + n.",
        },
        {
          type: "table",
          caption: "The dative prepositions",
          head: ["Preposition", "English", "Example"],
          rows: [
            ["mit", "with", "mit dem Auto"],
            ["nach", "to, after", "nach der Arbeit"],
            ["bei", "at", "bei der Oma"],
            ["seit", "since", "seit dem Montag"],
            ["von", "from, of", "von dem Bahnhof"],
            ["zu", "to", "zu dem Bahnhof"],
            ["aus", "out of", "aus der Küche"],
            ["außer", "except", "außer dem Lehrer"],
            ["gegenüber", "opposite", "gegenüber der Kirche"],
          ],
        },
        {
          type: "example",
          de: "Ich fahre mit dem Auto zur Arbeit. Seit dem Montag wohne ich bei meiner Oma.",
          en: "The dative prepositions in use.",
        },
        {
          type: "tip",
          text: "The dative table: der → dem, die → der, das → dem, plural → den ... n. The contraction pair: zu + dem = zum, bei + dem = beim.",
        },
      ],
    },
    {
      heading: "Die Dativendungen",
      blocks: [
        {
          type: "paragraph",
          text: "After a dative preposition, the article and the adjective change: masculine dem neuen Auto, feminine der neuen Lampe, neuter dem neuen Haus, plural den neuen Autos. The adjective after the dative article always takes -en. The noun in the plural dative adds -n.",
        },
        {
          type: "table",
          caption: "The dative declension",
          head: ["Gender", "Article", "Example"],
          rows: [
            ["masculine", "dem", "mit dem neuen Auto"],
            ["feminine", "der", "mit der neuen Lampe"],
            ["neuter", "dem", "mit dem neuen Haus"],
            ["plural", "den", "mit den neuen Autos"],
          ],
        },
        {
          type: "example",
          de: "Ich fahre mit dem neuen Auto. Sie spricht mit der neuen Kollegin. Wir sitzen bei den alten Freunden.",
          en: "The dative endings in use.",
        },
        {
          type: "tip",
          text: "The dative rule: the article carries der/dem, the adjective always takes -en, and the plural noun adds -n.",
        },
      ],
    },
    {
      heading: "mit und von",
      blocks: [
        {
          type: "paragraph",
          text: "mit (with) covers company and means: mit dem Auto (by car), mit einem Freund (with a friend). von (from, of) covers origin and possession: von dem Bahnhof (from the station), die Mutter von Anna (Anna's mother). Both are always dative.",
        },
        {
          type: "table",
          caption: "mit and von",
          head: ["Preposition", "Use", "Example"],
          rows: [
            ["mit", "company", "mit meinem Bruder"],
            ["mit", "means of transport", "mit dem Zug"],
            ["von", "origin", "vom Bahnhof"],
            ["von", "possession", "das Auto von meinem Vater"],
          ],
        },
        {
          type: "example",
          de: "Ich fahre mit dem Zug und treffe dort einen Freund von der Arbeit.",
          en: "mit and von together.",
        },
        {
          type: "tip",
          text: "The pair test: mit answers With whom? (mit einem Freund), von answers From where? (vom Bahnhof).",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: using the accusative after dative prepositions, forgetting the contraction, and mixing mit and von.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["accusative after mit", "mit den Auto", "mit dem Auto", "mit always takes the dative"],
            ["missing contraction", "zu dem Bahnhof", "zum Bahnhof", "zu + dem merges"],
            ["mit/von mix", "das Auto mit meinem Vater", "das Auto von meinem Vater", "possession takes von"],
            ["wrong plural dative", "mit den Autos? Nein, mit den Autos.", "mit den Autos", "the plural adds -n"],
            ["gegenüber loss", "gegenüber die Kirche", "gegenüber der Kirche", "gegenüber takes the dative"],
          ],
        },
        {
          type: "tip",
          text: "The dative prepositions are a fixed set: aus, bei, mit, nach, seit, von, zu, außer, gegenüber. Learn the set, then the article forms dem/der/den.",
        },
      ],
    },
  ],
  vocab: [
    { id: "mit-dem-auto", de: "mit dem Auto", en: "by car", part: "phrase", phrase: true, audio: true },
    { id: "mit-dem-zug", de: "mit dem Zug", en: "by train", part: "phrase", phrase: true, audio: true },
    { id: "mit-einem-freund", de: "mit einem Freund", en: "with a friend", part: "phrase", phrase: true, audio: true },
    { id: "mit-meiner-schwester", de: "mit meiner Schwester", en: "with my sister", part: "phrase", phrase: true, audio: true },
    { id: "nach-der-arbeit", de: "nach der Arbeit", en: "after work", part: "phrase", phrase: true, audio: true },
    { id: "bei-meiner-oma", de: "bei meiner Oma", en: "at my grandma's", part: "phrase", phrase: true, audio: true },
    { id: "beim-arzt", de: "beim Arzt", en: "at the doctor", part: "phrase", phrase: true, audio: true },
    { id: "seit-dem-montag", de: "seit dem Montag", en: "since Monday", part: "phrase", phrase: true, audio: true },
    { id: "vom-bahnhof", de: "vom Bahnhof", en: "from the station", part: "phrase", phrase: true, audio: true },
    { id: "von-meinem-vater", de: "von meinem Vater", en: "from my father", part: "phrase", phrase: true, audio: true },
    { id: "zum-bahnhof", de: "zum Bahnhof", en: "to the station", part: "phrase", phrase: true, audio: true },
    { id: "zur-schule", de: "zur Schule", en: "to school", part: "phrase", phrase: true, audio: true },
    { id: "aus-der-kueche", de: "aus der Küche", en: "out of the kitchen", part: "phrase", phrase: true, audio: true },
    { id: "aus-berlin", de: "aus Berlin", en: "from Berlin", part: "phrase", phrase: true, audio: true },
    { id: "gegenueber-der-kirche", de: "gegenüber der Kirche", en: "opposite the church", part: "phrase", phrase: true, audio: true },
    { id: "mit-den-freunden", de: "mit den Freunden", en: "with the friends", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-praepositionen",
      type: "matching",
      title: "Übung 1: Die Dativpräpositionen",
      instruction: "Match each preposition to its meaning.",
      pairs: [
        ["mit", "with"],
        ["nach", "to, after"],
        ["bei", "at"],
        ["seit", "since"],
        ["von", "from, of"],
        ["zu", "to"],
        ["aus", "out of"],
      ],
    },
    {
      id: "ex-dativ",
      type: "multiple-choice",
      title: "Übung 2: Der Dativ",
      instruction: "Choose the correct article.",
      prompt: "Ich fahre mit ___ Auto.",
      options: ["dem", "den", "das"],
      correctIndex: 0,
      explain: "mit takes the dative: dem.",
    },
    {
      id: "ex-dativ-2",
      type: "multiple-choice",
      title: "Übung 3: Der Dativ",
      instruction: "Choose the correct article.",
      prompt: "Sie spricht mit ___ Schwester.",
      options: ["der", "die", "dem"],
      correctIndex: 0,
      explain: "Feminine dative: der.",
    },
    {
      id: "ex-zum",
      type: "multiple-choice",
      title: "Übung 4: zum",
      instruction: "Choose the correct contraction.",
      prompt: "Ich gehe ___ Bahnhof.",
      options: ["zum", "zu den", "zur"],
      correctIndex: 0,
      explain: "Masculine direction: zum.",
    },
    {
      id: "ex-zur",
      type: "multiple-choice",
      title: "Übung 5: zur",
      instruction: "Choose the correct contraction.",
      prompt: "Ich gehe ___ Schule.",
      options: ["zur", "zum", "zu dem"],
      correctIndex: 0,
      explain: "Feminine direction: zur.",
    },
    {
      id: "ex-mit-von",
      type: "multiple-choice",
      title: "Übung 6: mit oder von",
      instruction: "Choose the correct preposition.",
      prompt: "I go with my brother.",
      options: ["Ich gehe mit meinem Bruder.", "Ich gehe von meinem Bruder.", "Ich gehe zu meinem Bruder."],
      correctIndex: 0,
      explain: "Company takes mit.",
    },
    {
      id: "ex-von",
      type: "multiple-choice",
      title: "Übung 7: von",
      instruction: "Choose the possession phrase.",
      prompt: "My father's car.",
      options: ["das Auto von meinem Vater", "das Auto mit meinem Vater", "das Auto bei meinem Vater"],
      correctIndex: 0,
      explain: "Possession takes von.",
    },
    {
      id: "ex-plural",
      type: "multiple-choice",
      title: "Übung 8: Der Plural",
      instruction: "Choose the plural dative.",
      prompt: "with the friends",
      options: ["mit den Freunden", "mit die Freunde", "mit dem Freunden"],
      correctIndex: 0,
      explain: "The plural dative: den + n.",
    },
    {
      id: "ex-gegenueber",
      type: "multiple-choice",
      title: "Übung 9: gegenüber",
      instruction: "Choose the correct sentence.",
      prompt: "The bank is opposite the church.",
      options: ["Die Bank ist gegenüber der Kirche.", "Die Bank ist gegenüber die Kirche.", "Die Bank ist gegenüber dem Kirche."],
      correctIndex: 0,
      explain: "gegenüber takes the dative.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 10: Hören",
      instruction: "Play the audio and pick the phrase you heard.",
      prompt: "mit dem Auto",
      options: ["mit dem Auto", "mit dem Zug", "mit dem Bus"],
      correctIndex: 0,
      explain: "The phrase heard: by car.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 11: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Ich fahre mit dem Zug.",
      options: ["Ich fahre mit dem Zug.", "Ich fahre mit dem Auto.", "Ich fahre mit dem Bus."],
      correctIndex: 0,
      explain: "The transport sentence heard.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 12: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Ich fahre mit dem Auto.", "Ich fahre mit das Auto.", "Ich fahre mit den Auto."],
      correctIndex: 0,
      explain: "mit takes the dative: dem.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 13: Der Satz",
      instruction: "Build the sentence: I go to the station.",
      chunks: ["Ich", "gehe", "zum", "Bahnhof."],
      explain: "The direction contraction.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 14: Der Satz",
      instruction: "Build the sentence: I go with my brother.",
      chunks: ["Ich", "gehe", "mit", "meinem", "Bruder."],
      explain: "Company with mit.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 15: Dativkarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "mit dem Auto", back: "by car", frontAudio: true },
        { front: "mit meinem Bruder", back: "with my brother", frontAudio: true },
        { front: "bei meiner Oma", back: "at my grandma's", frontAudio: true },
        { front: "beim Arzt", back: "at the doctor", frontAudio: true },
        { front: "seit dem Montag", back: "since Monday", frontAudio: true },
        { front: "vom Bahnhof", back: "from the station", frontAudio: true },
        { front: "zum Bahnhof", back: "to the station", frontAudio: true },
        { front: "zur Schule", back: "to school", frontAudio: true },
        { front: "aus Berlin", back: "from Berlin", frontAudio: true },
        { front: "gegenüber der Kirche", back: "opposite the church", frontAudio: true },
        { front: "mit den Freunden", back: "with the friends", frontAudio: true },
        { front: "nach der Arbeit", back: "after work", frontAudio: true },
      ],
    },
  ],
};

export const pronomenImDativ: Lesson = {
  id: "pronomen-im-dativ",
  title: "Pronomen im Dativ",
  summary:
    "The dative pronouns: mir, dir, ihm, ihr, uns, euch, ihnen, Ihnen and the verbs that take the dative for A1.",
  status: "ready",
  sections: [
    {
      heading: "Die Dativpronomen",
      blocks: [
        {
          type: "paragraph",
          text: "The dative pronouns replace the dative objects: ich → mir, du → dir, er → ihm, sie → ihr, es → ihm, wir → uns, ihr → euch, sie/Sie → ihnen/Ihnen. The phrase: Das gefällt mir. (I like that.) and Das schmeckt mir gut. (It tastes good to me.).",
        },
        {
          type: "table",
          caption: "The dative pronouns",
          head: ["Nominative", "Dative", "Example"],
          rows: [
            ["ich", "mir", "Das gefällt mir."],
            ["du", "dir", "Das gefällt dir."],
            ["er", "ihm", "Das gefällt ihm."],
            ["sie", "ihr", "Das gefällt ihr."],
            ["wir", "uns", "Das gefällt uns."],
            ["ihr", "euch", "Das gefällt euch."],
            ["sie", "ihnen", "Das gefällt ihnen."],
            ["Sie", "Ihnen", "Das gefällt Ihnen."],
          ],
        },
        {
          type: "example",
          de: "Das Buch gefällt mir. Das Kleid gefällt ihr. Die Musik gefällt uns.",
          en: "The dative pronouns in use.",
        },
        {
          type: "tip",
          text: "The dative pronouns: mir, dir, ihm, ihr, uns, euch, ihnen. Learn the set as one line: mir dir ihm ihr uns euch ihnen.",
        },
      ],
    },
    {
      heading: "Die Dativverben",
      blocks: [
        {
          type: "paragraph",
          text: "Some verbs always take the dative: gefallen (to please), schmecken (to taste), helfen (to help), danken (to thank), gehören (to belong), passen (to fit), antworten (to answer). With these, the object is in the dative: Das gefällt mir, Ich helfe dir.",
        },
        {
          type: "table",
          caption: "The dative verbs",
          head: ["Verb", "English", "Example"],
          rows: [
            ["gefallen", "to please", "Das gefällt mir."],
            ["schmecken", "to taste", "Das schmeckt mir gut."],
            ["helfen", "to help", "Ich helfe dir."],
            ["danken", "to thank", "Ich danke Ihnen."],
            ["gehören", "to belong", "Das gehört mir."],
            ["passen", "to fit", "Die Hose passt mir."],
            ["antworten", "to answer", "Ich antworte dir."],
          ],
        },
        {
          type: "example",
          de: "Kann ich dir helfen? Ja, danke. Das Kleid gehört mir, und die Schuhe passen mir gut.",
          en: "The dative verbs in a dialogue.",
        },
        {
          type: "tip",
          text: "The dative verbs are a set to learn: gefallen, schmecken, helfen, danken, gehören, passen, antworten. The object after them is always mir/dir/ihm...",
        },
      ],
    },
    {
      heading: "gefallen und schmecken",
      blocks: [
        {
          type: "paragraph",
          text: "gefallen (to please) and schmecken (to taste) are the two most tested dative verbs. gefallen answers about likes: Das gefällt mir (I like that), die Sache gefällt mir (the thing pleases me). schmecken answers about taste: Das schmeckt mir gut (I like the taste). The person who likes or tastes is in the dative.",
        },
        {
          type: "table",
          caption: "gefallen and schmecken",
          head: ["Verb", "English", "Example"],
          rows: [
            ["gefallen", "to please", "Das Bild gefällt mir."],
            ["schmecken", "to taste", "Die Suppe schmeckt mir."],
            ["gefallen", "with a question", "Wie gefällt dir das?"],
            ["schmecken", "with an adverb", "Das schmeckt mir sehr gut."],
          ],
        },
        {
          type: "example",
          de: "Wie gefällt dir das neue Auto? Es gefällt mir gut. Und die Suppe schmeckt mir sehr gut.",
          en: "The two dative verbs together.",
        },
        {
          type: "tip",
          text: "The pair: Das gefällt mir (I like it) and Das schmeckt mir (I like the taste). Both take the dative person.",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: using mich instead of mir, confusing the dative verbs with accusative verbs, and forgetting the dative pronoun.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["mich instead of mir", "Das gefällt mich.", "Das gefällt mir.", "gefallen takes the dative"],
            ["dative verb with accusative", "Ich helfe dich.", "Ich helfe dir.", "helfen takes the dative"],
            ["dative loss", "Das gehört ich.", "Das gehört mir.", "gehören takes the dative"],
            ["schmecken case", "Das schmeckt mich gut.", "Das schmeckt mir gut.", "schmecken takes the dative"],
            ["antworten case", "Ich antworte dich.", "Ich antworte dir.", "antworten takes the dative"],
          ],
        },
        {
          type: "tip",
          text: "The dative pronoun set: mir, dir, ihm, ihr, uns, euch, ihnen. The dative verb set: gefallen, schmecken, helfen, danken, gehören, passen, antworten.",
        },
      ],
    },
  ],
  vocab: [
    { id: "mir", de: "mir", en: "to me", part: "pronoun", audio: true },
    { id: "dir", de: "dir", en: "to you", part: "pronoun", audio: true },
    { id: "ihm", de: "ihm", en: "to him", part: "pronoun", audio: true },
    { id: "ihr", de: "ihr", en: "to her", part: "pronoun", audio: true },
    { id: "uns", de: "uns", en: "to us", part: "pronoun", audio: true },
    { id: "euch", de: "euch", en: "to you (plural)", part: "pronoun", audio: true },
    { id: "ihnen", de: "ihnen", en: "to them", part: "pronoun", audio: true },
    { id: "ihnen-formal", de: "Ihnen", en: "to you (formal)", part: "pronoun", audio: true },
    { id: "gefallen", de: "gefallen", en: "to please", part: "verb", audio: true },
    { id: "schmecken", de: "schmecken", en: "to taste", part: "verb", audio: true },
    { id: "helfen", de: "helfen", en: "to help", part: "verb", audio: true },
    { id: "danken", de: "danken", en: "to thank", part: "verb", audio: true },
    { id: "gehoeren", de: "gehören", en: "to belong", part: "verb", audio: true },
    { id: "passen", de: "passen", en: "to fit", part: "verb", audio: true },
    { id: "antworten", de: "antworten", en: "to answer", part: "verb", audio: true },
    { id: "das-gefaellt-mir", de: "Das gefällt mir.", en: "I like that.", part: "phrase", phrase: true, audio: true },
    { id: "das-schmeckt-mir-gut", de: "Das schmeckt mir gut.", en: "It tastes good to me.", part: "phrase", phrase: true, audio: true },
    { id: "ich-helfe-dir", de: "Ich helfe dir.", en: "I help you.", part: "phrase", phrase: true, audio: true },
    { id: "wie-gefaellt-dir-das", de: "Wie gefällt dir das?", en: "How do you like that?", part: "phrase", phrase: true, audio: true },
    { id: "ich-danke-ihnen", de: "Ich danke Ihnen.", en: "Thank you (formal).", part: "phrase", phrase: true, audio: true },
    { id: "das-gehoert-mir", de: "Das gehört mir.", en: "That belongs to me.", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-pronomen",
      type: "matching",
      title: "Übung 1: Die Dativpronomen",
      instruction: "Match each pronoun to its dative form.",
      pairs: [
        ["ich", "mir"],
        ["du", "dir"],
        ["er", "ihm"],
        ["sie", "ihr"],
        ["wir", "uns"],
        ["ihr", "euch"],
      ],
    },
    {
      id: "ex-gefallen",
      type: "multiple-choice",
      title: "Übung 2: gefallen",
      instruction: "Choose the correct sentence.",
      prompt: "I like that.",
      options: ["Das gefällt mir.", "Das gefällt mich.", "Das gefällt ich."],
      correctIndex: 0,
      explain: "gefallen takes the dative: mir.",
    },
    {
      id: "ex-schmecken",
      type: "multiple-choice",
      title: "Übung 3: schmecken",
      instruction: "Choose the correct sentence.",
      prompt: "It tastes good to me.",
      options: ["Das schmeckt mir gut.", "Das schmeckt mich gut.", "Das schmeckt ich gut."],
      correctIndex: 0,
      explain: "schmecken takes the dative: mir.",
    },
    {
      id: "ex-helfen",
      type: "multiple-choice",
      title: "Übung 4: helfen",
      instruction: "Choose the correct sentence.",
      prompt: "I help you.",
      options: ["Ich helfe dir.", "Ich helfe dich.", "Ich helfe du."],
      correctIndex: 0,
      explain: "helfen takes the dative: dir.",
    },
    {
      id: "ex-gehoeren",
      type: "multiple-choice",
      title: "Übung 5: gehören",
      instruction: "Choose the correct sentence.",
      prompt: "That belongs to me.",
      options: ["Das gehört mir.", "Das gehört mich.", "Das gehört ich."],
      correctIndex: 0,
      explain: "gehören takes the dative: mir.",
    },
    {
      id: "ex-ihm",
      type: "multiple-choice",
      title: "Übung 6: ihm",
      instruction: "Choose the correct pronoun.",
      prompt: "Das gefällt ___ (er).",
      options: ["ihm", "ihr", "mir"],
      correctIndex: 0,
      explain: "er → ihm in the dative.",
    },
    {
      id: "ex-ihr-2",
      type: "multiple-choice",
      title: "Übung 7: ihr",
      instruction: "Choose the correct pronoun.",
      prompt: "Das gefällt ___ (sie, singular).",
      options: ["ihr", "ihm", "dir"],
      correctIndex: 0,
      explain: "sie → ihr in the dative.",
    },
    {
      id: "ex-dank",
      type: "multiple-choice",
      title: "Übung 8: danken",
      instruction: "Choose the correct sentence.",
      prompt: "Thank you (formal).",
      options: ["Ich danke Ihnen.", "Ich danke Sie.", "Ich danke dir?"],
      correctIndex: 0,
      explain: "danken takes the dative: Ihnen.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 9: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Das gefällt mir.",
      options: ["Das gefällt mir.", "Das gefällt dir.", "Das gefällt ihr."],
      correctIndex: 0,
      explain: "The dative sentence heard.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 10: Hören",
      instruction: "Play the audio and pick the phrase you heard.",
      prompt: "Ich helfe dir.",
      options: ["Ich helfe dir.", "Ich helfe ihr.", "Ich helfe Ihnen."],
      correctIndex: 0,
      explain: "The help sentence heard.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 11: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Das gefällt mir.", "Das gefällt mich.", "Das gefällt ich."],
      correctIndex: 0,
      explain: "gefallen takes the dative.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 12: Der Satz",
      instruction: "Build the sentence: I like that.",
      chunks: ["Das", "gefällt", "mir."],
      explain: "The dative object.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 13: Der Satz",
      instruction: "Build the sentence: I help you.",
      chunks: ["Ich", "helfe", "dir."],
      explain: "helfen + dative.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 14: Pronomenkarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "mir", back: "to me", frontAudio: true },
        { front: "dir", back: "to you", frontAudio: true },
        { front: "ihm", back: "to him", frontAudio: true },
        { front: "ihr", back: "to her", frontAudio: true },
        { front: "uns", back: "to us", frontAudio: true },
        { front: "euch", back: "to you (plural)", frontAudio: true },
        { front: "Das gefällt mir.", back: "I like that.", frontAudio: true },
        { front: "Das schmeckt mir gut.", back: "It tastes good to me.", frontAudio: true },
        { front: "Ich helfe dir.", back: "I help you.", frontAudio: true },
        { front: "Ich danke Ihnen.", back: "Thank you (formal).", frontAudio: true },
        { front: "Das gehört mir.", back: "That belongs to me.", frontAudio: true },
        { front: "Wie gefällt dir das?", back: "How do you like that?", frontAudio: true },
      ],
    },
  ],
};

export const wortstellung: Lesson = {
  id: "wortstellung",
  title: "Wortstellung",
  summary:
    "The German word order: the verb in second position, the time-manner-place rule, and the position of the object for A1.",
  status: "ready",
  sections: [
    {
      heading: "Die Verbposition",
      blocks: [
        {
          type: "paragraph",
          text: "The most important rule of German: the finite verb stands in the second position of the main clause. The first position can be the subject (Ich lerne Deutsch.) or any other element (Heute lerne ich Deutsch.). After the verb, the subject follows if it was not first.",
        },
        {
          type: "table",
          caption: "The verb position",
          head: ["First position", "Verb", "Rest"],
          rows: [
            ["Ich", "lerne", "Deutsch."],
            ["Heute", "lerne", "ich Deutsch."],
            ["In Berlin", "wohne", "ich seit zwei Jahren."],
            ["Morgen", "fahre", "wir nach Hamburg."],
          ],
        },
        {
          type: "example",
          de: "Ich lerne Deutsch. Heute lerne ich Deutsch. In Berlin lerne ich Deutsch.",
          en: "The verb stays in second position.",
        },
        {
          type: "tip",
          text: "The verb is always second. Move anything to the front and the verb stays in position two, the subject follows the verb.",
        },
      ],
    },
    {
      heading: "Zeit, Art, Ort",
      blocks: [
        {
          type: "paragraph",
          text: "The adverb order in the middle field is time, manner, place (temporal, kausal, modal, lokal): Ich fahre heute mit dem Zug nach Berlin. (time: heute, manner: mit dem Zug, place: nach Berlin). The order: when, how, where.",
        },
        {
          type: "table",
          caption: "Time, manner, place",
          head: ["Time", "Manner", "Place", "Example"],
          rows: [
            ["heute", "mit dem Zug", "nach Berlin", "Ich fahre heute mit dem Zug nach Berlin."],
            ["morgen", "mit dem Auto", "zur Arbeit", "Ich fahre morgen mit dem Auto zur Arbeit."],
            ["am Samstag", "mit dem Bus", "in die Stadt", "Wir fahren am Samstag mit dem Bus in die Stadt."],
          ],
        },
        {
          type: "example",
          de: "Ich gehe heute mit meinem Freund ins Kino.",
          en: "Time, manner, place in one sentence.",
        },
        {
          type: "tip",
          text: "The word order test: when (heute), how (mit dem Zug), where (nach Berlin). The order is always time, manner, place.",
        },
      ],
    },
    {
      heading: "Die Position des Objekts",
      blocks: [
        {
          type: "paragraph",
          text: "The object order: when both objects are present, the dative comes before the accusative: Ich gebe dem Mann das Buch. (I give the man the book.). If the accusative is a pronoun, it comes first: Ich gebe es dem Mann.",
        },
        {
          type: "table",
          caption: "The object order",
          head: ["Order", "Example"],
          rows: [
            ["dative + accusative", "Ich gebe dem Mann das Buch."],
            ["pronoun first", "Ich gebe es dem Mann."],
            ["two nouns", "Sie gibt der Frau die Blume."],
            ["pronoun accusative", "Ich kaufe dir das Auto. / Ich kaufe es dir."],
          ],
        },
        {
          type: "example",
          de: "Ich gebe dem Mann das Buch. Ich gebe es dem Mann. Ich kaufe dir das Auto.",
          en: "The object order in use.",
        },
        {
          type: "tip",
          text: "The object order: dative before accusative (Ich gebe dem Mann das Buch), but the pronoun first (Ich gebe es ihm).",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: the verb not in second position, the wrong adverb order, and the dative/accusative swap.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["verb in first position", "Heute ich lerne Deutsch.", "Heute lerne ich Deutsch.", "the verb stays in second position"],
            ["verb in third position", "Ich heute lerne Deutsch.", "Heute lerne ich Deutsch.", "the verb is position two"],
            ["adverb order", "Ich fahre nach Berlin heute mit dem Zug.", "Ich fahre heute mit dem Zug nach Berlin.", "time, manner, place"],
            ["object swap", "Ich gebe das Buch dem Mann.", "Ich gebe dem Mann das Buch.", "dative before accusative"],
            ["subject after verb", "Heute lerne Deutsch ich.", "Heute lerne ich Deutsch.", "the subject follows the verb"],
          ],
        },
        {
          type: "tip",
          text: "The word order rules: verb second, subject after the verb when fronted, time-manner-place, and dative before accusative.",
        },
      ],
    },
  ],
  vocab: [
    { id: "der-satz", de: "der Satz", en: "the sentence", part: "noun m.", plural: "die Sätze", audio: true },
    { id: "die-wortstellung", de: "die Wortstellung", en: "the word order", part: "noun f.", audio: true },
    { id: "das-subjekt", de: "das Subjekt", en: "the subject", part: "noun n.", plural: "die Subjekte", audio: true },
    { id: "das-objekt", de: "das Objekt", en: "the object", part: "noun n.", plural: "die Objekte", audio: true },
    { id: "ich-lerne-deutsch", de: "Ich lerne Deutsch.", en: "I am learning German.", part: "phrase", phrase: true, audio: true },
    { id: "heute-lerne-ich-deutsch", de: "Heute lerne ich Deutsch.", en: "Today I am learning German.", part: "phrase", phrase: true, audio: true },
    { id: "ich-fahre-heute-mit-dem-zug", de: "Ich fahre heute mit dem Zug nach Berlin.", en: "I am going to Berlin by train today.", part: "phrase", phrase: true, audio: true },
    { id: "ich-gebe-dem-mann-das-buch", de: "Ich gebe dem Mann das Buch.", en: "I give the man the book.", part: "phrase", phrase: true, audio: true },
    { id: "ich-gebe-es-dem-mann", de: "Ich gebe es dem Mann.", en: "I give it to the man.", part: "phrase", phrase: true, audio: true },
    { id: "ich-kaufe-dir-das-auto", de: "Ich kaufe dir das Auto.", en: "I buy you the car.", part: "phrase", phrase: true, audio: true },
    { id: "ich-kaufe-es-dir", de: "Ich kaufe es dir.", en: "I buy it for you.", part: "phrase", phrase: true, audio: true },
    { id: "zur-arbeit", de: "zur Arbeit", en: "to work", part: "phrase", phrase: true, audio: true },
    { id: "in-die-stadt", de: "in die Stadt", en: "into the city", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-verb",
      type: "multiple-choice",
      title: "Übung 1: Die Verbposition",
      instruction: "Choose the correct sentence.",
      prompt: "The verb must be in ... position.",
      options: ["second", "first", "last"],
      correctIndex: 0,
      explain: "The finite verb is second in the main clause.",
    },
    {
      id: "ex-front",
      type: "multiple-choice",
      title: "Übung 2: Der Frontsatz",
      instruction: "Choose the correct sentence.",
      prompt: "Today I am learning German.",
      options: ["Heute lerne ich Deutsch.", "Heute ich lerne Deutsch.", "Heute lerne Deutsch ich."],
      correctIndex: 0,
      explain: "The verb stays second, the subject follows.",
    },
    {
      id: "ex-tmp",
      type: "multiple-choice",
      title: "Übung 3: Zeit, Art, Ort",
      instruction: "Choose the correct order.",
      prompt: "I am going to Berlin by train today.",
      options: ["Ich fahre heute mit dem Zug nach Berlin.", "Ich fahre nach Berlin heute mit dem Zug.", "Ich fahre mit dem Zug heute nach Berlin."],
      correctIndex: 0,
      explain: "Time, manner, place: heute, mit dem Zug, nach Berlin.",
    },
    {
      id: "ex-objekt",
      type: "multiple-choice",
      title: "Übung 4: Das Objekt",
      instruction: "Choose the correct order.",
      prompt: "I give the man the book.",
      options: ["Ich gebe dem Mann das Buch.", "Ich gebe das Buch dem Mann.", "Ich dem Mann gebe das Buch."],
      correctIndex: 0,
      explain: "Dative before accusative.",
    },
    {
      id: "ex-pronomen",
      type: "multiple-choice",
      title: "Übung 5: Das Pronomen",
      instruction: "Choose the correct order.",
      prompt: "I give it to the man.",
      options: ["Ich gebe es dem Mann.", "Ich gebe dem Mann es.", "Ich dem Mann gebe es."],
      correctIndex: 0,
      explain: "The pronoun comes first.",
    },
    {
      id: "ex-kaufen",
      type: "multiple-choice",
      title: "Übung 6: kaufen",
      instruction: "Choose the correct sentence.",
      prompt: "I buy you the car.",
      options: ["Ich kaufe dir das Auto.", "Ich kaufe das Auto dir.", "Ich das Auto kaufe dir."],
      correctIndex: 0,
      explain: "Dative before accusative.",
    },
    {
      id: "ex-heute",
      type: "multiple-choice",
      title: "Übung 7: heute",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence has the verb in second position?",
      options: ["Heute lerne ich Deutsch.", "Heute ich lerne Deutsch.", "Ich heute lerne Deutsch."],
      correctIndex: 0,
      explain: "The verb is second.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 8: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Heute lerne ich Deutsch.",
      options: ["Heute lerne ich Deutsch.", "Ich lerne heute Deutsch.", "Deutsch lerne ich heute."],
      correctIndex: 0,
      explain: "The sentence heard with fronted time.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 9: Hören",
      instruction: "Play the audio and pick the phrase you heard.",
      prompt: "Ich gebe dem Mann das Buch.",
      options: ["Ich gebe dem Mann das Buch.", "Ich gebe das Buch dem Mann.", "Ich dem Mann gebe das Buch."],
      correctIndex: 0,
      explain: "The object order heard.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 10: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Ich fahre heute mit dem Zug nach Berlin.", "Ich fahre nach Berlin heute mit dem Zug.", "Ich heute mit dem Zug nach Berlin fahre."],
      correctIndex: 0,
      explain: "Time, manner, place with the verb second.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 11: Der Satz",
      instruction: "Build the sentence: Today I am learning German.",
      chunks: ["Heute", "lerne", "ich", "Deutsch."],
      explain: "The verb stays second.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 12: Der Satz",
      instruction: "Build the sentence: I am going to Berlin by train today.",
      chunks: ["Ich", "fahre", "heute", "mit", "dem", "Zug", "nach", "Berlin."],
      explain: "Time, manner, place.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 13: Wortstellungskarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "Ich lerne Deutsch.", back: "I am learning German.", frontAudio: true },
        { front: "Heute lerne ich Deutsch.", back: "Today I am learning German.", frontAudio: true },
        { front: "Ich fahre heute mit dem Zug nach Berlin.", back: "I am going to Berlin by train today.", frontAudio: true },
        { front: "Ich gebe dem Mann das Buch.", back: "I give the man the book.", frontAudio: true },
        { front: "Ich gebe es dem Mann.", back: "I give it to the man.", frontAudio: true },
        { front: "Ich kaufe dir das Auto.", back: "I buy you the car.", frontAudio: true },
        { front: "Ich kaufe es dir.", back: "I buy it for you.", frontAudio: true },
        { front: "zur Arbeit", back: "to work", frontAudio: true },
        { front: "in die Stadt", back: "into the city", frontAudio: true },
        { front: "das Subjekt", back: "the subject", frontAudio: true },
        { front: "das Objekt", back: "the object", frontAudio: true },
        { front: "die Wortstellung", back: "the word order", frontAudio: true },
      ],
    },
  ],
};

export const imBuerro: Lesson = {
  id: "im-buero",
  title: "Im Büro",
  summary:
    "The complete office vocabulary for A1: the office equipment, the workday, the phone call, and the office dialogue.",
  status: "ready",
  sections: [
    {
      heading: "Das Büro",
      blocks: [
        {
          type: "paragraph",
          text: "The office (das Büro) is a room full of equipment: der Schreibtisch (desk, m.), der Computer (computer, m.), der Bildschirm (screen, m.), die Tastatur (keyboard, f.), die Maus (mouse, f.), der Drucker (printer, m.), das Telefon (telephone, n.), das Papier (paper, n.).",
        },
        {
          type: "table",
          caption: "The office equipment",
          head: ["German", "English", "Plural"],
          rows: [
            ["der Schreibtisch", "the desk", "die Schreibtische"],
            ["der Computer", "the computer", "die Computer"],
            ["der Bildschirm", "the screen", "die Bildschirme"],
            ["die Tastatur", "the keyboard", "die Tastaturen"],
            ["die Maus", "the mouse", "die Mäuse"],
            ["der Drucker", "the printer", "die Drucker"],
            ["das Telefon", "the telephone", "die Telefone"],
            ["das Papier", "the paper", "die Papiere"],
          ],
        },
        {
          type: "example",
          de: "Auf meinem Schreibtisch stehen ein Computer, ein Bildschirm und ein Telefon.",
          en: "The desk description.",
        },
        {
          type: "tip",
          text: "The office equipment: der Schreibtisch, der Computer, der Drucker, das Telefon. The desk position phrase: Auf dem Schreibtisch steht ...",
        },
      ],
    },
    {
      heading: "Der Arbeitstag",
      blocks: [
        {
          type: "paragraph",
          text: "The workday (der Arbeitstag) runs on the verbs: arbeiten (to work), anrufen (to call), schreiben (to write), lesen (to read), E-Mails beantworten (to answer emails), eine Pause machen (to take a break). The phrase: Ich arbeite von 9 bis 17 Uhr. (I work from 9 to 5.).",
        },
        {
          type: "table",
          caption: "The workday verbs",
          head: ["Verb", "English", "Example"],
          rows: [
            ["arbeiten", "to work", "Ich arbeite im Büro."],
            ["anrufen", "to call", "Ich rufe den Kunden an."],
            ["schreiben", "to write", "Ich schreibe eine E-Mail."],
            ["lesen", "to read", "Ich lese den Bericht."],
            ["beantworten", "to answer", "Ich beantworte E-Mails."],
            ["eine Pause machen", "to take a break", "Ich mache eine Pause."],
          ],
        },
        {
          type: "example",
          de: "Ich arbeite von 9 bis 17 Uhr. Am Vormittag beantworte ich E-Mails, am Nachmittag schreibe ich Berichte.",
          en: "The workday description.",
        },
        {
          type: "tip",
          text: "The workday phrase: Ich arbeite von X bis Y Uhr. The office verbs: arbeiten, anrufen, schreiben, lesen, beantworten.",
        },
      ],
    },
    {
      heading: "Der Telefonanruf",
      blocks: [
        {
          type: "paragraph",
          text: "The office phone call runs on a script: Hier ist Frau Schmidt. (This is Ms Schmidt.), Kann ich bitte Herrn Müller sprechen? (Can I speak to Mr Müller, please?), Einen Moment, bitte. (One moment, please.), Er ist gerade in einer Besprechung. (He is in a meeting right now.).",
        },
        {
          type: "table",
          caption: "The phone script",
          head: ["German", "English"],
          rows: [
            ["Hier ist Frau Schmidt.", "This is Ms Schmidt."],
            ["Kann ich bitte Herrn Müller sprechen?", "Can I speak to Mr Müller, please?"],
            ["Einen Moment, bitte.", "One moment, please."],
            ["Er ist gerade in einer Besprechung.", "He is in a meeting right now."],
            ["Ich rufe später wieder an.", "I will call again later."],
            ["Auf Wiederhören!", "Goodbye (on the phone)!"],
          ],
        },
        {
          type: "example",
          de: "Guten Tag, hier ist Frau Schmidt. Kann ich bitte Herrn Müller sprechen? Einen Moment, bitte. Ich verbinde.",
          en: "The office phone call.",
        },
        {
          type: "tip",
          text: "The phone phrase: Hier ist ... (This is ...), the phone goodbye is Auf Wiederhören, not Auf Wiedersehen.",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: the phone greeting, the separable anrufen, and the office equipment genders.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["phone goodbye", "Auf Wiedersehen (phone)", "Auf Wiederhören", "the phone has its own goodbye"],
            ["anrufen split", "Ich anrufe den Kunden.", "Ich rufe den Kunden an.", "anrufen is separable"],
            ["wrong gender", "die Schreibtisch", "der Schreibtisch", "Schreibtisch is masculine"],
            ["wrong phone phrase", "Hier Frau Schmidt.", "Hier ist Frau Schmidt.", "the phone intro uses ist"],
            ["anrufen/sprechen mix", "Ich spreche dich an.", "Ich rufe dich an.", "calling takes anrufen"],
          ],
        },
        {
          type: "tip",
          text: "The office topic is a script: the equipment, the workday, and the phone call with Hier ist and Auf Wiederhören.",
        },
      ],
    },
  ],
  vocab: [
    { id: "der-schreibtisch", de: "der Schreibtisch", en: "the desk", part: "noun m.", plural: "die Schreibtische", audio: true },
    { id: "der-computer", de: "der Computer", en: "the computer", part: "noun m.", plural: "die Computer", audio: true },
    { id: "der-bildschirm", de: "der Bildschirm", en: "the screen", part: "noun m.", plural: "die Bildschirme", audio: true },
    { id: "die-tastatur", de: "die Tastatur", en: "the keyboard", part: "noun f.", plural: "die Tastaturen", audio: true },
    { id: "die-maus", de: "die Maus", en: "the mouse", part: "noun f.", plural: "die Mäuse", audio: true },
    { id: "der-drucker", de: "der Drucker", en: "the printer", part: "noun m.", plural: "die Drucker", audio: true },
    { id: "das-telefon", de: "das Telefon", en: "the telephone", part: "noun n.", plural: "die Telefone", audio: true },
    { id: "das-papier", de: "das Papier", en: "the paper", part: "noun n.", plural: "die Papiere", audio: true },
    { id: "die-e-mail", de: "die E-Mail", en: "the email", part: "noun f.", plural: "die E-Mails", audio: true },
    { id: "der-bericht", de: "der Bericht", en: "the report", part: "noun m.", plural: "die Berichte", audio: true },
    { id: "der-termin", de: "der Termin", en: "the appointment", part: "noun m.", plural: "die Termine", audio: true },
    { id: "die-besprechung", de: "die Besprechung", en: "the meeting", part: "noun f.", plural: "die Besprechungen", audio: true },
    { id: "die-pause", de: "die Pause", en: "the break", part: "noun f.", plural: "die Pausen", audio: true },
    { id: "anrufen", de: "anrufen", en: "to call", part: "verb", audio: true },
    { id: "schreiben", de: "schreiben", en: "to write", part: "verb", audio: true },
    { id: "beantworten", de: "beantworten", en: "to answer", part: "verb", audio: true },
    { id: "verbinden", de: "verbinden", en: "to connect (a call)", part: "verb", audio: true },
    { id: "die-arbeit", de: "die Arbeit", en: "the work", part: "noun f.", plural: "die Arbeiten", audio: true },
    { id: "der-arbeitstag", de: "der Arbeitstag", en: "the workday", part: "noun m.", plural: "die Arbeitstage", audio: true },
    { id: "ich-arbeite-im-buero", de: "Ich arbeite im Büro.", en: "I work in the office.", part: "phrase", phrase: true, audio: true },
    { id: "ich-schreibe-eine-email", de: "Ich schreibe eine E-Mail.", en: "I am writing an email.", part: "phrase", phrase: true, audio: true },
    { id: "hier-ist-frau-schmidt", de: "Hier ist Frau Schmidt.", en: "This is Ms Schmidt.", part: "phrase", phrase: true, audio: true },
    { id: "kann-ich-bitte-herrn-mueller-sprechen", de: "Kann ich bitte Herrn Müller sprechen?", en: "Can I speak to Mr Müller, please?", part: "phrase", phrase: true, audio: true },
    { id: "einen-moment-bitte", de: "Einen Moment, bitte.", en: "One moment, please.", part: "phrase", phrase: true, audio: true },
    { id: "auf-wiederhoeren", de: "Auf Wiederhören!", en: "Goodbye (on the phone)!", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-geraete",
      type: "matching",
      title: "Übung 1: Die Bürogeräte",
      instruction: "Match each office device to its meaning.",
      pairs: [
        ["der Schreibtisch", "the desk"],
        ["der Computer", "the computer"],
        ["die Tastatur", "the keyboard"],
        ["die Maus", "the mouse"],
        ["der Drucker", "the printer"],
        ["das Telefon", "the telephone"],
      ],
    },
    {
      id: "ex-genus",
      type: "multiple-choice",
      title: "Übung 2: Das Genus",
      instruction: "Choose the correct article.",
      prompt: "___ Maus ist neu.",
      options: ["Die", "Der", "Das"],
      correctIndex: 0,
      explain: "Maus is feminine: die Maus.",
    },
    {
      id: "ex-anrufen",
      type: "multiple-choice",
      title: "Übung 3: anrufen",
      instruction: "Choose the correct sentence.",
      prompt: "I am calling the customer.",
      options: ["Ich rufe den Kunden an.", "Ich anrufe den Kunden.", "Ich rufe an den Kunden."],
      correctIndex: 0,
      explain: "anrufen is separable.",
    },
    {
      id: "ex-tag",
      type: "multiple-choice",
      title: "Übung 4: Der Arbeitstag",
      instruction: "Choose the correct sentence.",
      prompt: "I work from 9 to 5.",
      options: ["Ich arbeite von 9 bis 17 Uhr.", "Ich arbeite von 9 bis 17 Uhr?", "Ich arbeite am 9 bis 17 Uhr."],
      correctIndex: 0,
      explain: "The work hours phrase: von X bis Y Uhr.",
    },
    {
      id: "ex-telefon",
      type: "multiple-choice",
      title: "Übung 5: Der Telefonanruf",
      instruction: "Choose the phone intro.",
      prompt: "This is Ms Schmidt.",
      options: ["Hier ist Frau Schmidt.", "Hier Frau Schmidt.", "Ich bin Frau Schmidt."],
      correctIndex: 0,
      explain: "The phone intro: Hier ist ...",
    },
    {
      id: "ex-sprechen",
      type: "multiple-choice",
      title: "Übung 6: sprechen",
      instruction: "Choose the phone request.",
      prompt: "Can I speak to Mr Müller, please?",
      options: ["Kann ich bitte Herrn Müller sprechen?", "Kann ich bitte Herr Müller sprechen?", "Kann ich bitte sprechen Herrn Müller?"],
      correctIndex: 0,
      explain: "The phone request: Kann ich ... sprechen?",
    },
    {
      id: "ex-wiederhoeren",
      type: "multiple-choice",
      title: "Übung 7: Auf Wiederhören",
      instruction: "Choose the phone goodbye.",
      prompt: "The phone call ends.",
      options: ["Auf Wiederhören!", "Auf Wiedersehen!", "Tschüss auf dem Telefon!"],
      correctIndex: 0,
      explain: "The phone goodbye: Auf Wiederhören.",
    },
    {
      id: "ex-email",
      type: "multiple-choice",
      title: "Übung 8: Die E-Mail",
      instruction: "Choose the correct sentence.",
      prompt: "I am writing an email.",
      options: ["Ich schreibe eine E-Mail.", "Ich schreibe ein E-Mail.", "Ich schreibe den E-Mail."],
      correctIndex: 0,
      explain: "E-Mail is feminine: eine E-Mail.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 9: Hören",
      instruction: "Play the audio and pick the device you heard.",
      prompt: "der Drucker",
      options: ["der Drucker", "der Computer", "der Bildschirm"],
      correctIndex: 0,
      explain: "The device heard: printer.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 10: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Hier ist Frau Schmidt.",
      options: ["Hier ist Frau Schmidt.", "Hier ist Herr Müller.", "Hier ist Frau Müller."],
      correctIndex: 0,
      explain: "The phone intro heard.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 11: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Ich rufe den Kunden an.", "Ich anrufe den Kunden.", "Ich rufe an den Kunden."],
      correctIndex: 0,
      explain: "anrufen is separable.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 12: Der Satz",
      instruction: "Build the sentence: I work in the office.",
      chunks: ["Ich", "arbeite", "im", "Büro."],
      explain: "Working in the office.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 13: Der Satz",
      instruction: "Build the sentence: This is Ms Schmidt.",
      chunks: ["Hier", "ist", "Frau", "Schmidt."],
      explain: "The phone intro.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 14: Bürokarten",
      instruction: "Say the German with the article out loud.",
      items: [
        { front: "der Schreibtisch", back: "the desk", frontAudio: true },
        { front: "der Computer", back: "the computer", frontAudio: true },
        { front: "die Tastatur", back: "the keyboard", frontAudio: true },
        { front: "die Maus", back: "the mouse", frontAudio: true },
        { front: "der Drucker", back: "the printer", frontAudio: true },
        { front: "das Telefon", back: "the telephone", frontAudio: true },
        { front: "Hier ist Frau Schmidt.", back: "This is Ms Schmidt.", frontAudio: true },
        { front: "Kann ich bitte Herrn Müller sprechen?", back: "Can I speak to Mr Müller, please?", frontAudio: true },
        { front: "Einen Moment, bitte.", back: "One moment, please.", frontAudio: true },
        { front: "Auf Wiederhören!", back: "Goodbye (on the phone)!", frontAudio: true },
        { front: "anrufen", back: "to call", frontAudio: true },
        { front: "Ich schreibe eine E-Mail.", back: "I am writing an email.", frontAudio: true },
      ],
    },
  ],
};

export const derDativ: Lesson = {
  id: "der-dativ",
  title: "Der Dativ",
  summary:
    "The complete dative system for A1: the dative articles, the dative pronouns, the dative verbs, and the dative prepositions in one lesson.",
  status: "ready",
  sections: [
    {
      heading: "Der Dativ: die Endungen",
      blocks: [
        {
          type: "paragraph",
          text: "The dative (der Dativ) is the third case. Its articles: der → dem, die → der, das → dem, plural → den. The dative answers Wem? (To whom?). The phrase: Ich gebe dem Mann das Buch (I give the man the book): the man is the dative recipient.",
        },
        {
          type: "table",
          caption: "The dative articles",
          head: ["Gender", "Nominative", "Dative", "Example"],
          rows: [
            ["masculine", "der Mann", "dem Mann", "Ich helfe dem Mann."],
            ["feminine", "die Frau", "der Frau", "Ich helfe der Frau."],
            ["neuter", "das Kind", "dem Kind", "Ich helfe dem Kind."],
            ["plural", "die Kinder", "den Kindern", "Ich helfe den Kindern."],
          ],
        },
        {
          type: "example",
          de: "Ich helfe dem Mann, der Frau, dem Kind und den Kindern.",
          en: "All four dative articles.",
        },
        {
          type: "tip",
          text: "The dative table: der → dem, die → der, das → dem, plural → den + n. The question test: Wem hilfst du? Dem Mann.",
        },
      ],
    },
    {
      heading: "Die Dativpronomen",
      blocks: [
        {
          type: "paragraph",
          text: "The dative pronouns: mir, dir, ihm, ihr, uns, euch, ihnen, Ihnen. The dative object replaces the person: Ich gebe dir das Buch (I give you the book), Sie hilft ihm (She helps him).",
        },
        {
          type: "table",
          caption: "The dative pronouns",
          head: ["Nominative", "Dative", "Example"],
          rows: [
            ["ich", "mir", "Das gefällt mir."],
            ["du", "dir", "Ich helfe dir."],
            ["er", "ihm", "Sie gibt ihm das Buch."],
            ["sie", "ihr", "Wir danken ihr."],
            ["wir", "uns", "Er hilft uns."],
            ["ihr", "euch", "Ich helfe euch."],
            ["sie", "ihnen", "Das gefällt ihnen."],
          ],
        },
        {
          type: "example",
          de: "Das gefällt mir, aber das gefällt dir nicht. Wir helfen euch gerne.",
          en: "The dative pronouns in a dialogue.",
        },
        {
          type: "tip",
          text: "The dative pronoun line: mir dir ihm ihr uns euch ihnen. They answer Wem? (to whom).",
        },
      ],
    },
    {
      heading: "Die Dativverben",
      blocks: [
        {
          type: "paragraph",
          text: "The dative verbs always take the dative: gefallen, schmecken, helfen, danken, gehören, passen, antworten. With these, the object is always in the dative: Das gefällt mir, Ich helfe dir, Die Hose passt mir.",
        },
        {
          type: "table",
          caption: "The dative verbs",
          head: ["Verb", "English", "Example"],
          rows: [
            ["gefallen", "to please", "Das gefällt mir."],
            ["schmecken", "to taste", "Das schmeckt mir gut."],
            ["helfen", "to help", "Ich helfe dir."],
            ["danken", "to thank", "Ich danke Ihnen."],
            ["gehören", "to belong", "Das gehört mir."],
            ["passen", "to fit", "Die Hose passt mir."],
            ["antworten", "to answer", "Ich antworte dir."],
          ],
        },
        {
          type: "example",
          de: "Kann ich dir helfen? Ja, danke. Das Kleid gehört mir, und die Schuhe passen mir gut.",
          en: "The dative verbs together.",
        },
        {
          type: "tip",
          text: "The dative verb set: gefallen, schmecken, helfen, danken, gehören, passen, antworten. The object after them is always in the dative.",
        },
      ],
    },
    {
      heading: "Die Dativpräpositionen",
      blocks: [
        {
          type: "paragraph",
          text: "The dative prepositions always take the dative: aus, bei, mit, nach, seit, von, zu, außer, gegenüber. After them the articles change to dem, der, den: mit dem Auto, bei der Oma, nach der Arbeit.",
        },
        {
          type: "table",
          caption: "The dative prepositions",
          head: ["Preposition", "English", "Example"],
          rows: [
            ["mit", "with", "mit dem Auto"],
            ["nach", "to, after", "nach der Arbeit"],
            ["bei", "at", "bei der Oma"],
            ["seit", "since", "seit dem Montag"],
            ["von", "from, of", "vom Bahnhof"],
            ["zu", "to", "zum Bahnhof"],
            ["aus", "out of", "aus der Küche"],
            ["gegenüber", "opposite", "gegenüber der Kirche"],
          ],
        },
        {
          type: "example",
          de: "Ich fahre mit dem Auto nach der Arbeit zu meiner Oma.",
          en: "Three dative prepositions in one sentence.",
        },
        {
          type: "tip",
          text: "The dative preposition set: aus, bei, mit, nach, seit, von, zu, außer, gegenüber. The contraction pair: zu + dem = zum, bei + dem = beim.",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: using the accusative instead of the dative, the mich/mir mix, and forgetting the plural -n.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["mich/mir mix", "Das gefällt mich.", "Das gefällt mir.", "gefallen takes the dative"],
            ["accusative after mit", "mit den Auto", "mit dem Auto", "mit always takes the dative"],
            ["object order", "Ich gebe das Buch dem Mann.", "Ich gebe dem Mann das Buch.", "dative before accusative"],
            ["plural dative", "mit den Kinder", "mit den Kindern", "the plural dative adds -n"],
            ["dative loss", "Ich helfe du.", "Ich helfe dir.", "helfen takes the dative"],
          ],
        },
        {
          type: "tip",
          text: "The dative system: the articles (dem, der, den), the pronouns (mir, dir, ihm...), the verbs (gefallen, schmecken...), and the prepositions (mit, von, zu...).",
        },
      ],
    },
  ],
  vocab: [
    { id: "der-dativ", de: "der Dativ", en: "the dative case", part: "noun m.", audio: true },
    { id: "wem", de: "Wem?", en: "To whom?", part: "pronoun", audio: true },
    { id: "dem-mann", de: "dem Mann", en: "to the man", part: "phrase", phrase: true, audio: true },
    { id: "der-frau", de: "der Frau", en: "to the woman", part: "phrase", phrase: true, audio: true },
    { id: "dem-kind", de: "dem Kind", en: "to the child", part: "phrase", phrase: true, audio: true },
    { id: "den-kindern", de: "den Kindern", en: "to the children", part: "phrase", phrase: true, audio: true },
    { id: "ich-helfe-dem-mann", de: "Ich helfe dem Mann.", en: "I help the man.", part: "phrase", phrase: true, audio: true },
    { id: "ich-gebe-der-frau-das-buch", de: "Ich gebe der Frau das Buch.", en: "I give the woman the book.", part: "phrase", phrase: true, audio: true },
    { id: "ich-gebe-dem-kind-das-buch", de: "Ich gebe dem Kind das Buch.", en: "I give the child the book.", part: "phrase", phrase: true, audio: true },
    { id: "das-gefaellt-mir", de: "Das gefällt mir.", en: "I like that.", part: "phrase", phrase: true, audio: true },
    { id: "ich-helfe-dir", de: "Ich helfe dir.", en: "I help you.", part: "phrase", phrase: true, audio: true },
    { id: "ich-danke-ihnen", de: "Ich danke Ihnen.", en: "Thank you (formal).", part: "phrase", phrase: true, audio: true },
    { id: "mit-dem-auto", de: "mit dem Auto", en: "by car", part: "phrase", phrase: true, audio: true },
    { id: "bei-der-oma", de: "bei der Oma", en: "at grandma's", part: "phrase", phrase: true, audio: true },
    { id: "nach-der-arbeit", de: "nach der Arbeit", en: "after work", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-artikel",
      type: "matching",
      title: "Übung 1: Die Dativartikel",
      instruction: "Match each article to its dative form.",
      pairs: [
        ["der Mann", "dem Mann"],
        ["die Frau", "der Frau"],
        ["das Kind", "dem Kind"],
        ["die Kinder", "den Kindern"],
      ],
    },
    {
      id: "ex-wem",
      type: "multiple-choice",
      title: "Übung 2: Die Dativfrage",
      instruction: "Choose the dative question.",
      prompt: "The dative answers which question?",
      options: ["Wem?", "Wen?", "Wer?"],
      correctIndex: 0,
      explain: "The dative answers Wem? (to whom).",
    },
    {
      id: "ex-artikel-2",
      type: "multiple-choice",
      title: "Übung 3: Der Artikel",
      instruction: "Choose the correct dative.",
      prompt: "Ich helfe ___ Mann.",
      options: ["dem", "den", "der"],
      correctIndex: 0,
      explain: "Masculine dative: dem.",
    },
    {
      id: "ex-pronomen",
      type: "multiple-choice",
      title: "Übung 4: Das Pronomen",
      instruction: "Choose the correct pronoun.",
      prompt: "Das gefällt ___ (mir).",
      options: ["mir", "mich", "ich"],
      correctIndex: 0,
      explain: "gefallen takes the dative: mir.",
    },
    {
      id: "ex-verb",
      type: "multiple-choice",
      title: "Übung 5: Das Dativverb",
      instruction: "Choose the correct sentence.",
      prompt: "I help you.",
      options: ["Ich helfe dir.", "Ich helfe dich.", "Ich helfe du."],
      correctIndex: 0,
      explain: "helfen takes the dative.",
    },
    {
      id: "ex-praep",
      type: "multiple-choice",
      title: "Übung 6: Die Dativpräposition",
      instruction: "Choose the correct phrase.",
      prompt: "I am going by car.",
      options: ["mit dem Auto", "mit das Auto", "mit den Auto"],
      correctIndex: 0,
      explain: "mit takes the dative.",
    },
    {
      id: "ex-order",
      type: "multiple-choice",
      title: "Übung 7: Die Objektordnung",
      instruction: "Choose the correct order.",
      prompt: "I give the woman the book.",
      options: ["Ich gebe der Frau das Buch.", "Ich gebe das Buch der Frau.", "Ich der Frau gebe das Buch."],
      correctIndex: 0,
      explain: "Dative before accusative.",
    },
    {
      id: "ex-plural",
      type: "multiple-choice",
      title: "Übung 8: Der Plural",
      instruction: "Choose the plural dative.",
      prompt: "Ich helfe ___ (die Kinder).",
      options: ["den Kindern", "den Kinder", "dem Kindern"],
      correctIndex: 0,
      explain: "The plural dative adds -n.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 9: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Ich helfe dem Mann.",
      options: ["Ich helfe dem Mann.", "Ich helfe der Frau.", "Ich helfe dem Kind."],
      correctIndex: 0,
      explain: "The dative sentence heard.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 10: Hören",
      instruction: "Play the audio and pick the phrase you heard.",
      prompt: "mit dem Auto",
      options: ["mit dem Auto", "mit dem Zug", "mit dem Bus"],
      correctIndex: 0,
      explain: "The dative phrase heard.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 11: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Das gefällt mir.", "Das gefällt mich.", "Das gefällt ich."],
      correctIndex: 0,
      explain: "gefallen takes the dative.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 12: Der Satz",
      instruction: "Build the sentence: I give the woman the book.",
      chunks: ["Ich", "gebe", "der", "Frau", "das", "Buch."],
      explain: "Dative before accusative.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 13: Der Satz",
      instruction: "Build the sentence: I help the children.",
      chunks: ["Ich", "helfe", "den", "Kindern."],
      explain: "The plural dative adds -n.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 14: Dativkarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "Ich helfe dem Mann.", back: "I help the man.", frontAudio: true },
        { front: "Ich helfe der Frau.", back: "I help the woman.", frontAudio: true },
        { front: "Ich helfe dem Kind.", back: "I help the child.", frontAudio: true },
        { front: "Ich helfe den Kindern.", back: "I help the children.", frontAudio: true },
        { front: "Das gefällt mir.", back: "I like that.", frontAudio: true },
        { front: "Ich helfe dir.", back: "I help you.", frontAudio: true },
        { front: "Ich danke Ihnen.", back: "Thank you (formal).", frontAudio: true },
        { front: "mit dem Auto", back: "by car", frontAudio: true },
        { front: "bei der Oma", back: "at grandma's", frontAudio: true },
        { front: "nach der Arbeit", back: "after work", frontAudio: true },
        { front: "Wem?", back: "To whom?", frontAudio: true },
        { front: "der Dativ", back: "the dative case", frontAudio: true },
      ],
    },
  ],
};

export const konjunktionen: Lesson = {
  id: "konjunktionen",
  title: "Konjunktionen",
  summary:
    "The conjunctions for A1: und, oder, aber, denn, and the verb-final dass, weil, obwohl. The two clause types and their word order.",
  status: "ready",
  sections: [
    {
      heading: "und, oder, aber, denn",
      blocks: [
        {
          type: "paragraph",
          text: "Four conjunctions connect two main clauses without changing the word order: und (and), oder (or), aber (but), denn (because). After them the verb stays in position two: Ich lerne Deutsch, denn ich möchte in Deutschland arbeiten.",
        },
        {
          type: "table",
          caption: "The main-clause conjunctions",
          head: ["Conjunction", "English", "Example"],
          rows: [
            ["und", "and", "Ich lerne Deutsch und ich übe jeden Tag."],
            ["oder", "or", "Trinkst du Kaffee oder Tee?"],
            ["aber", "but", "Ich mag Kaffee, aber ich trinke ihn selten."],
            ["denn", "because", "Ich lerne Deutsch, denn ich brauche es."],
          ],
        },
        {
          type: "example",
          de: "Ich lerne Deutsch, denn ich möchte in Deutschland arbeiten. Ich mag Kaffee, aber ich trinke Tee.",
          en: "denn and aber in use.",
        },
        {
          type: "tip",
          text: "denn keeps the normal word order: Verb-Subject. The pair test: Ich lerne Deutsch, denn ich brauche es (verb in position two after denn).",
        },
      ],
    },
    {
      heading: "dass, weil, obwohl: das Verb am Ende",
      blocks: [
        {
          type: "paragraph",
          text: "The three subordinating conjunctions send the verb to the end: dass (that), weil (because), obwohl (although). The pattern: main clause + conjunction + subject + ... + verb at the end: Ich weiß, dass du recht hast (I know that you are right).",
        },
        {
          type: "table",
          caption: "The subordinating conjunctions",
          head: ["Conjunction", "English", "Verb position"],
          rows: [
            ["dass", "that", "Ich weiß, dass du recht hast."],
            ["weil", "because", "Ich bleibe zu Hause, weil es regnet."],
            ["obwohl", "although", "Ich gehe raus, obwohl es regnet."],
          ],
        },
        {
          type: "example",
          de: "Ich bleibe zu Hause, weil es regnet. Ich gehe raus, obwohl es kalt ist.",
          en: "weil and obwohl in use.",
        },
        {
          type: "tip",
          text: "The verb-final rule: after dass, weil, obwohl the verb goes to the end. weil es regnet, obwohl es kalt ist.",
        },
      ],
    },
    {
      heading: "und: die Satzverbindung",
      blocks: [
        {
          type: "paragraph",
          text: "und (and) is the most common conjunction. It connects subjects (Peter und Anna), objects (Kaffee und Tee), and whole clauses (Ich lerne Deutsch und ich übe jeden Tag). The comma rules: before und there is no comma in German.",
        },
        {
          type: "table",
          caption: "und connections",
          head: ["What it connects", "Example"],
          rows: [
            ["subjects", "Peter und Anna kommen."],
            ["objects", "Ich trinke Kaffee und Tee."],
            ["clauses", "Ich lerne Deutsch und ich übe."],
            ["adjectives", "ein großes und schönes Haus"],
          ],
        },
        {
          type: "example",
          de: "Peter und Anna lernen Deutsch. Sie trinken Kaffee und Tee. Sie lernen und üben jeden Tag.",
          en: "und in all its roles.",
        },
        {
          type: "tip",
          text: "und needs no comma. It connects anything of the same kind: nouns, clauses, adjectives.",
        },
      ],
    },
    {
      heading: "weil und denn",
      blocks: [
        {
          type: "paragraph",
          text: "weil and denn both mean because, but they differ: weil sends the verb to the end (Ich bleibe zu Hause, weil es regnet), denn keeps it in position two (Ich bleibe zu Hause, denn es regnet). The choice is about word order, not meaning.",
        },
        {
          type: "table",
          caption: "weil against denn",
          head: ["Conjunction", "Verb position", "Example"],
          rows: [
            ["weil", "at the end", "Ich bleibe zu Hause, weil es regnet."],
            ["denn", "position two", "Ich bleibe zu Hause, denn es regnet."],
          ],
        },
        {
          type: "example",
          de: "Ich lerne Deutsch, weil ich in Deutschland arbeiten möchte. Ich lerne Deutsch, denn ich möchte in Deutschland arbeiten.",
          en: "The same idea, two word orders.",
        },
        {
          type: "tip",
          text: "weil and denn are synonyms for because, but weil ends the clause and denn keeps the normal order. The exam tests the difference.",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: wrong verb position after weil/dass, confusing weil and denn, and the comma rules.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["verb not final after weil", "Ich bleibe zu Hause, weil es regnet.", "Ich bleibe zu Hause, weil es regnet.", "weil ends the clause"],
            ["denn verb order", "Ich bleibe zu Hause, denn es regnet.", "Ich bleibe zu Hause, denn es regnet.", "denn keeps position two"],
            ["weil/denn mix", "Ich bleibe zu Hause, weil es regnet (with denn order)", "correct forms", "each has its own order"],
            ["comma loss", "Ich lerne Deutsch und ich übe.", "Ich lerne Deutsch und ich übe.", "no comma before und"],
            ["verb before weil", "weil es regnet.", "weil es regnet.", "the verb ends the weil clause"],
          ],
        },
        {
          type: "tip",
          text: "The conjunction system: und/oder/aber/denn keep the normal order, dass/weil/obwohl send the verb to the end.",
        },
      ],
    },
  ],
  vocab: [
    { id: "und", de: "und", en: "and", part: "conjunction", audio: true },
    { id: "oder", de: "oder", en: "or", part: "conjunction", audio: true },
    { id: "aber", de: "aber", en: "but", part: "conjunction", audio: true },
    { id: "denn", de: "denn", en: "because", part: "conjunction", audio: true },
    { id: "dass", de: "dass", en: "that", part: "conjunction", audio: true },
    { id: "weil", de: "weil", en: "because", part: "conjunction", audio: true },
    { id: "obwohl", de: "obwohl", en: "although", part: "conjunction", audio: true },
    { id: "ich-lerne-deutsch", de: "Ich lerne Deutsch.", en: "I am learning German.", part: "phrase", phrase: true, audio: true },
    { id: "denn-ich-brauche-es", de: "denn ich brauche es", en: "because I need it", part: "phrase", phrase: true, audio: true },
    { id: "weil-es-regnet", de: "weil es regnet", en: "because it is raining", part: "phrase", phrase: true, audio: true },
    { id: "dass-du-recht-hast", de: "dass du recht hast", en: "that you are right", part: "phrase", phrase: true, audio: true },
    { id: "obwohl-es-kalt-ist", de: "obwohl es kalt ist", en: "although it is cold", part: "phrase", phrase: true, audio: true },
    { id: "ich-mag-kaffee-aber", de: "Ich mag Kaffee, aber ich trinke Tee.", en: "I like coffee, but I drink tea.", part: "phrase", phrase: true, audio: true },
    { id: "kaffee-oder-tee", de: "Kaffee oder Tee?", en: "Coffee or tea?", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-basics",
      type: "matching",
      title: "Übung 1: Die Konjunktionen",
      instruction: "Match each conjunction to its meaning.",
      pairs: [
        ["und", "and"],
        ["oder", "or"],
        ["aber", "but"],
        ["denn", "because"],
        ["dass", "that"],
        ["weil", "because"],
      ],
    },
    {
      id: "ex-denn",
      type: "multiple-choice",
      title: "Übung 2: denn",
      instruction: "Choose the correct sentence.",
      prompt: "I am learning German because I need it.",
      options: ["Ich lerne Deutsch, denn ich brauche es.", "Ich lerne Deutsch, denn ich es brauche.", "Ich lerne Deutsch, denn ich brauche."],
      correctIndex: 0,
      explain: "denn keeps the normal word order.",
    },
    {
      id: "ex-weil",
      type: "multiple-choice",
      title: "Übung 3: weil",
      instruction: "Choose the correct sentence.",
      prompt: "I stay home because it is raining.",
      options: ["Ich bleibe zu Hause, weil es regnet.", "Ich bleibe zu Hause, weil regnet es.", "Ich bleibe zu Hause, weil es regnet heute."],
      correctIndex: 0,
      explain: "weil sends the verb to the end.",
    },
    {
      id: "ex-dass",
      type: "multiple-choice",
      title: "Übung 4: dass",
      instruction: "Choose the correct sentence.",
      prompt: "I know that you are right.",
      options: ["Ich weiß, dass du recht hast.", "Ich weiß, dass du hast recht.", "Ich weiß, dass du recht haben."],
      correctIndex: 0,
      explain: "dass sends the verb to the end.",
    },
    {
      id: "ex-obwohl",
      type: "multiple-choice",
      title: "Übung 5: obwohl",
      instruction: "Choose the correct sentence.",
      prompt: "I go out although it is cold.",
      options: ["Ich gehe raus, obwohl es kalt ist.", "Ich gehe raus, obwohl es ist kalt.", "Ich gehe raus, obwohl kalt ist es."],
      correctIndex: 0,
      explain: "obwohl sends the verb to the end.",
    },
    {
      id: "ex-und",
      type: "multiple-choice",
      title: "Übung 6: und",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Peter und Anna kommen.", "Peter kommt und Anna.", "Peter und Anna kommst."],
      correctIndex: 0,
      explain: "und connects subjects.",
    },
    {
      id: "ex-aber",
      type: "multiple-choice",
      title: "Übung 7: aber",
      instruction: "Choose the correct sentence.",
      prompt: "I like coffee, but I drink tea.",
      options: ["Ich mag Kaffee, aber ich trinke Tee.", "Ich mag Kaffee, aber ich trinke Kaffee.", "Ich mag Kaffee aber ich trinke Tee."],
      correctIndex: 0,
      explain: "aber keeps the normal order.",
    },
    {
      id: "ex-weil-denn",
      type: "multiple-choice",
      title: "Übung 8: weil oder denn",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence has the verb at the end?",
      options: ["Ich bleibe zu Hause, weil es regnet.", "Ich bleibe zu Hause, denn es regnet.", "Ich bleibe zu Hause, aber es regnet."],
      correctIndex: 0,
      explain: "weil ends the clause.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 9: Hören",
      instruction: "Play the audio and pick the conjunction you heard.",
      prompt: "weil",
      options: ["weil", "denn", "aber"],
      correctIndex: 0,
      explain: "The conjunction heard: weil.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 10: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Ich bleibe zu Hause, weil es regnet.",
      options: ["Ich bleibe zu Hause, weil es regnet.", "Ich bleibe zu Hause, denn es regnet.", "Ich gehe raus, weil es regnet."],
      correctIndex: 0,
      explain: "The weil sentence heard.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 11: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Ich weiß, dass du recht hast.", "Ich weiß, dass du hast recht.", "Ich weiß, dass du recht hast?"],
      correctIndex: 0,
      explain: "dass ends the clause.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 12: Der Satz",
      instruction: "Build the sentence: I stay home because it is raining.",
      chunks: ["Ich", "bleibe", "zu", "Hause,", "weil", "es", "regnet."],
      explain: "weil ends the clause.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 13: Der Satz",
      instruction: "Build the sentence: I like coffee, but I drink tea.",
      chunks: ["Ich", "mag", "Kaffee,", "aber", "ich", "trinke", "Tee."],
      explain: "aber keeps the normal order.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 14: Konjunktionskarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "und", back: "and", frontAudio: true },
        { front: "oder", back: "or", frontAudio: true },
        { front: "aber", back: "but", frontAudio: true },
        { front: "denn", back: "because", frontAudio: true },
        { front: "dass", back: "that", frontAudio: true },
        { front: "weil", back: "because", frontAudio: true },
        { front: "obwohl", back: "although", frontAudio: true },
        { front: "weil es regnet", back: "because it is raining", frontAudio: true },
        { front: "dass du recht hast", back: "that you are right", frontAudio: true },
        { front: "obwohl es kalt ist", back: "although it is cold", frontAudio: true },
        { front: "Kaffee oder Tee?", back: "Coffee or tea?", frontAudio: true },
        { front: "Ich lerne Deutsch.", back: "I am learning German.", frontAudio: true },
      ],
    },
  ],
};

export const arbeitUndBeruf: Unit = {
  id: "arbeit-und-beruf",
  title: "Arbeit und Beruf",
  theme: "Work and professions",
  lessons: [
    berufe,
    praepositionenMitDativ,
    pronomenImDativ,
    derDativ,
    wortstellung,
    konjunktionen,
    imBuerro,
  ],
};