import type { Lesson, Unit } from "../../schema";

export const kleidung: Lesson = {
  id: "kleidung",
  title: "Kleidung",
  summary:
    "The complete clothing system for A1: the garments, the genders, the verbs of wearing, and the shopping phrases for clothes.",
  status: "ready",
  sections: [
    {
      heading: "Die Kleidungsstücke",
      blocks: [
        {
          type: "paragraph",
          text: "Clothing words follow the three-gender system. The everyday set: das T-Shirt (n.), das Hemd (n.), die Hose (f.), das Kleid (n.), der Rock (m.), die Jacke (f.), der Mantel (m.), der Pullover (m.), die Schuhe (pl.), die Socken (pl.). The plural forms end in -e, -en or stay bare.",
        },
        {
          type: "table",
          caption: "Clothing",
          head: ["German", "English", "Plural"],
          rows: [
            ["das T-Shirt", "the T-shirt", "die T-Shirts"],
            ["das Hemd", "the shirt", "die Hemden"],
            ["die Hose", "the trousers", "die Hosen"],
            ["das Kleid", "the dress", "die Kleider"],
            ["der Rock", "the skirt", "die Röcke"],
            ["die Jacke", "the jacket", "die Jacken"],
            ["der Mantel", "the coat", "die Mäntel"],
            ["der Pullover", "the jumper", "die Pullover"],
            ["die Schuhe", "the shoes", "only plural"],
            ["die Socken", "the socks", "only plural"],
            ["die Mütze", "the cap", "die Mützen"],
            ["der Hut", "the hat", "die Hüte"],
          ],
        },
        {
          type: "example",
          de: "Heute trage ich eine Jeans, ein T-Shirt und eine Jacke. Im Winter trage ich einen Mantel und eine Mütze.",
          en: "Today I'm wearing jeans, a T-shirt and a jacket. In winter I wear a coat and a hat.",
        },
        {
          type: "tip",
          text: "die Schuhe and die Socken only exist in the plural. The classic phrase: ein Paar Schuhe (a pair of shoes).",
        },
      ],
    },
    {
      heading: "Die Verben des Tragens",
      blocks: [
        {
          type: "paragraph",
          text: "Wearing runs on two verbs: tragen (to wear, carry) and anhaben (to have on, wear). The question: Was trägst du heute? (What are you wearing today?). Anziehen is the dressing verb: Ich ziehe die Jacke an (I put on the jacket).",
        },
        {
          type: "table",
          caption: "The wearing verbs",
          head: ["Verb", "English", "Example"],
          rows: [
            ["tragen", "to wear", "Ich trage eine Hose."],
            ["anhaben", "to have on", "Sie hat ein Kleid an."],
            ["anziehen", "to put on", "Ich ziehe die Jacke an."],
            ["ausziehen", "to take off", "Ich ziehe die Schuhe aus."],
            ["kaufen", "to buy", "Ich kaufe einen Pullover."],
            ["anprobieren", "to try on", "Ich probiere die Hose an."],
          ],
        },
        {
          type: "example",
          de: "Ich ziehe den Mantel an, weil es kalt ist. Kann ich die Hose anprobieren? Ja, die Kabine ist dort.",
          en: "I put the coat on because it is cold. Can I try on the trousers? Yes, the fitting room is over there.",
        },
        {
          type: "tip",
          text: "The separable pair: anziehen (put on) and ausziehen (take off). The shop phrase: Ich möchte die Jacke anprobieren.",
        },
      ],
    },
    {
      heading: "Die Kleidung kaufen",
      blocks: [
        {
          type: "paragraph",
          text: "Buying clothes runs on the shopping script: the seller asks Kann ich Ihnen helfen? (Can I help you?), you answer Ich suche ... (I am looking for ...) with the accusative, and the sizing questions: Welche Größe haben Sie? (What size do you have?), Welche Farbe möchten Sie? (What colour would you like?).",
        },
        {
          type: "table",
          caption: "The clothes shopping script",
          head: ["German", "English"],
          rows: [
            ["Kann ich Ihnen helfen?", "Can I help you?"],
            ["Ich suche eine Jacke.", "I am looking for a jacket."],
            ["Welche Größe haben Sie?", "What size do you have?"],
            ["Ich habe Größe M.", "I am size M."],
            ["Welche Farbe möchten Sie?", "What colour would you like?"],
            ["Kann ich das anprobieren?", "Can I try it on?"],
            ["Das passt mir gut.", "It fits me well."],
            ["Das nehme ich.", "I will take it."],
          ],
        },
        {
          type: "example",
          de: "Kann ich Ihnen helfen? Ja, ich suche ein blaues T-Shirt. Welche Größe haben Sie? Größe M. Hier bitte. Das passt mir gut, das nehme ich.",
          en: "Can I help you? Yes, I'm looking for a blue T-shirt. What size are you? Size M. Here you go. That fits me well, I'll take it.",
        },
        {
          type: "tip",
          text: "The pair: Ich suche (present tense looking) and Das passt mir gut (it fits). The passive fit is tested by the exam question: passt or steht?",
        },
      ],
    },
    {
      heading: "Größen und Farben",
      blocks: [
        {
          type: "paragraph",
          text: "The sizes: S (small), M (medium), L (large), XL. The colour combinations: ein rotes T-Shirt, eine blaue Hose, ein weißes Hemd. The adjective endings apply before the garment: ein neues Kleid, eine schwarze Jacke.",
        },
        {
          type: "table",
          caption: "Sizes and colours",
          head: ["Size", "Meaning", "Example"],
          rows: [
            ["S", "small", "ein T-Shirt in S"],
            ["M", "medium", "Größe M"],
            ["L", "large", "ein Hemd in L"],
            ["XL", "extra large", "Größe XL"],
            ["eine Farbe", "a colour", "in Blau, in Rot"],
          ],
        },
        {
          type: "tip",
          text: "The exam clothing pair: Größe (size) and Farbe (colour). Practise the dialogue: Welche Größe? Welche Farbe? Das passt.",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: wrong gender, mixing the wearing verbs, and forgetting the separable verb in anziehen.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["wrong gender", "der Kleid", "das Kleid", "Kleid is neuter"],
            ["anziehen split", "Ich anziehe die Jacke.", "Ich ziehe die Jacke an.", "anziehen is separable"],
            ["trage/habe mix", "Ich habe eine Jacke.", "Ich trage eine Jacke.", "wearing uses tragen"],
            ["anprobieren missing", "Kann ich die Hose sehen?", "Kann ich die Hose anprobieren?", "trying on uses anprobieren"],
            ["plural alone", "die Schuh", "die Schuhe", "shoes take the plural"],
          ],
        },
        {
          type: "tip",
          text: "The clothing topic is a script: Ich suche + garment + accusative, Welche Größe/Farbe, anprobieren, Das passt, Das nehme ich.",
        },
      ],
    },
  ],
  vocab: [
    { id: "das-tshirt", de: "das T-Shirt", en: "the T-shirt", part: "noun n.", plural: "die T-Shirts", audio: true },
    { id: "das-hemd", de: "das Hemd", en: "the shirt", part: "noun n.", plural: "die Hemden", audio: true },
    { id: "die-hose", de: "die Hose", en: "the trousers", part: "noun f.", plural: "die Hosen", audio: true },
    { id: "das-kleid", de: "das Kleid", en: "the dress", part: "noun n.", plural: "die Kleider", audio: true },
    { id: "der-rock", de: "der Rock", en: "the skirt", part: "noun m.", plural: "die Röcke", audio: true },
    { id: "die-jacke", de: "die Jacke", en: "the jacket", part: "noun f.", plural: "die Jacken", audio: true },
    { id: "der-mantel", de: "der Mantel", en: "the coat", part: "noun m.", plural: "die Mäntel", audio: true },
    { id: "der-pullover", de: "der Pullover", en: "the jumper", part: "noun m.", plural: "die Pullover", audio: true },
    { id: "die-schuhe", de: "die Schuhe", en: "the shoes", part: "noun pl.", audio: true },
    { id: "die-socken", de: "die Socken", en: "the socks", part: "noun pl.", audio: true },
    { id: "die-muetze", de: "die Mütze", en: "the cap", part: "noun f.", plural: "die Mützen", audio: true },
    { id: "der-hut", de: "der Hut", en: "the hat", part: "noun m.", plural: "die Hüte", audio: true },
    { id: "die-jeans", de: "die Jeans", en: "the jeans", part: "noun f.", plural: "die Jeans", audio: true },
    { id: "tragen", de: "tragen", en: "to wear", part: "verb", audio: true },
    { id: "anhaben", de: "anhaben", en: "to have on", part: "verb", audio: true },
    { id: "anziehen", de: "anziehen", en: "to put on", part: "verb", audio: true },
    { id: "ausziehen", de: "ausziehen", en: "to take off", part: "verb", audio: true },
    { id: "anprobieren", de: "anprobieren", en: "to try on", part: "verb", audio: true },
    { id: "die-groesse", de: "die Größe", en: "the size", part: "noun f.", plural: "die Größen", audio: true },
    { id: "die-kabine", de: "die Kabine", en: "the fitting room", part: "noun f.", plural: "die Kabinen", audio: true },
    { id: "ich-suche-eine-jacke", de: "Ich suche eine Jacke.", en: "I am looking for a jacket.", part: "phrase", phrase: true, audio: true },
    { id: "welche-groesse-haben-sie", de: "Welche Größe haben Sie?", en: "What size do you have?", part: "phrase", phrase: true, audio: true },
    { id: "ich-habe-groesse-m", de: "Ich habe Größe M.", en: "I am size M.", part: "phrase", phrase: true, audio: true },
    { id: "das-passt-mir-gut", de: "Das passt mir gut.", en: "It fits me well.", part: "phrase", phrase: true, audio: true },
    { id: "das-nehme-ich", de: "Das nehme ich.", en: "I will take it.", part: "phrase", phrase: true, audio: true },
    { id: "kann-ich-das-anprobieren", de: "Kann ich das anprobieren?", en: "Can I try it on?", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-kleidung",
      type: "matching",
      title: "Übung 1: Die Kleidung",
      instruction: "Match each garment to its meaning.",
      pairs: [
        ["das Hemd", "the shirt"],
        ["die Hose", "the trousers"],
        ["das Kleid", "the dress"],
        ["die Jacke", "the jacket"],
        ["der Mantel", "the coat"],
        ["die Schuhe", "the shoes"],
      ],
    },
    {
      id: "ex-genus",
      type: "multiple-choice",
      title: "Übung 2: Das Genus",
      instruction: "Choose the correct article.",
      prompt: "___ Kleid ist schön.",
      options: ["Das", "Die", "Der"],
      correctIndex: 0,
      explain: "Kleid is neuter: das Kleid.",
    },
    {
      id: "ex-genus-2",
      type: "multiple-choice",
      title: "Übung 3: Das Genus",
      instruction: "Choose the correct article.",
      prompt: "___ Hose ist blau.",
      options: ["Die", "Das", "Der"],
      correctIndex: 0,
      explain: "Hose is feminine: die Hose.",
    },
    {
      id: "ex-tragen",
      type: "multiple-choice",
      title: "Übung 4: tragen",
      instruction: "Choose the correct verb.",
      prompt: "Ich ___ heute eine Jacke.",
      options: ["trage", "bin", "habe"],
      correctIndex: 0,
      explain: "Wearing uses tragen.",
    },
    {
      id: "ex-anziehen",
      type: "multiple-choice",
      title: "Übung 5: anziehen",
      instruction: "Choose the correct sentence.",
      prompt: "I am putting on the jacket.",
      options: ["Ich ziehe die Jacke an.", "Ich anziehe die Jacke.", "Ich ziehe an die Jacke."],
      correctIndex: 0,
      explain: "anziehen is separable: ziehe ... an.",
    },
    {
      id: "ex-groesse",
      type: "multiple-choice",
      title: "Übung 6: Die Größe",
      instruction: "Choose the size question.",
      prompt: "You ask the seller for your size.",
      options: ["Welche Größe haben Sie?", "Welche Farbe haben Sie?", "Wie groß ist die Jacke?"],
      correctIndex: 0,
      explain: "Size question: Welche Größe?",
    },
    {
      id: "ex-kaufen",
      type: "multiple-choice",
      title: "Übung 7: Im Geschäft",
      instruction: "Choose the shopping phrase.",
      prompt: "You are looking for a jacket.",
      options: ["Ich suche eine Jacke.", "Ich sehe eine Jacke.", "Ich finde eine Jacke."],
      correctIndex: 0,
      explain: "Looking uses suchen.",
    },
    {
      id: "ex-anprobieren",
      type: "multiple-choice",
      title: "Übung 8: anprobieren",
      instruction: "Choose the correct sentence.",
      prompt: "Can I try on the trousers?",
      options: ["Kann ich die Hose anprobieren?", "Kann ich die Hose ansehen?", "Kann ich die Hose kaufen?"],
      correctIndex: 0,
      explain: "Trying on uses anprobieren.",
    },
    {
      id: "ex-passt",
      type: "multiple-choice",
      title: "Übung 9: Das passt",
      instruction: "Choose the correct phrase.",
      prompt: "It fits me well.",
      options: ["Das passt mir gut.", "Das passt mich gut.", "Das passt ich gut."],
      correctIndex: 0,
      explain: "passen takes the dative: mir.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 10: Hören",
      instruction: "Play the audio and pick the garment you heard.",
      prompt: "die Jacke",
      options: ["die Jacke", "die Hose", "das Kleid"],
      correctIndex: 0,
      explain: "The garment heard: jacket.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 11: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Ich suche einen Mantel.",
      options: ["Ich suche einen Mantel.", "Ich suche eine Mütze.", "Ich trage einen Mantel."],
      correctIndex: 0,
      explain: "The shopping sentence heard.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 12: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Ich trage eine Hose.", "Ich bin eine Hose.", "Ich habe eine Hose anhaben."],
      correctIndex: 0,
      explain: "Wearing uses tragen.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 13: Der Satz",
      instruction: "Build the sentence: I am looking for a blue shirt.",
      chunks: ["Ich", "suche", "ein", "blaues", "Hemd."], translation: "I am looking for a blue shirt.",
      explain: "suchen + accusative with adjective ending.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 14: Der Satz",
      instruction: "Build the sentence: I will take the jacket.",
      chunks: ["Ich", "nehme", "die", "Jacke."], translation: "I'll take the jacket.",
      explain: "The purchase sentence.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 15: Kleidungskarten",
      instruction: "Say the German with the article out loud.",
      items: [
        { front: "das T-Shirt", back: "the T-shirt", frontAudio: true },
        { front: "das Hemd", back: "the shirt", frontAudio: true },
        { front: "die Hose", back: "the trousers", frontAudio: true },
        { front: "das Kleid", back: "the dress", frontAudio: true },
        { front: "die Jacke", back: "the jacket", frontAudio: true },
        { front: "der Mantel", back: "the coat", frontAudio: true },
        { front: "die Schuhe", back: "the shoes", frontAudio: true },
        { front: "tragen", back: "to wear", frontAudio: true },
        { front: "anziehen", back: "to put on", frontAudio: true },
        { front: "anprobieren", back: "to try on", frontAudio: true },
        { front: "Das passt mir gut.", back: "It fits me well.", frontAudio: true },
        { front: "Ich suche eine Jacke.", back: "I am looking for a jacket.", frontAudio: true },
      ],
    },
  ],
};

export const einkaufsdialoge: Lesson = {
  id: "einkaufsdialoge",
  title: "Einkaufsdialoge",
  summary:
    "The complete shopping dialogues for A1: the supermarket, the clothes shop, asking for help, comparing prices, and the payment script.",
  status: "ready",
  sections: [
    {
      heading: "Der Supermarkt",
      blocks: [
        {
          type: "paragraph",
          text: "The supermarket dialogue runs on the script: ask where something is, pay at the checkout, and answer the checkout questions. The key phrase: Entschuldigung, wo finde ich ...? (Excuse me, where do I find ...?). The checkout phrases: Zahlen Sie bar oder mit Karte? and Haben Sie einen Kundenbonus?",
        },
        {
          type: "table",
          caption: "The supermarket script",
          head: ["German", "English"],
          rows: [
            ["Entschuldigung, wo finde ich die Milch?", "Excuse me, where do I find the milk?"],
            ["Im Kühlregal, hinten links.", "In the fridge, back left."],
            ["Wie viel kostet das?", "How much does that cost?"],
            ["Das macht zusammen 12 Euro.", "That is 12 euros altogether."],
            ["Zahlen Sie bar oder mit Karte?", "Cash or card?"],
            ["Mit Karte, bitte.", "By card, please."],
            ["Hier ist Ihr Bon.", "Here is your receipt."],
            ["Auf Wiedersehen!", "Goodbye!"],
          ],
        },
        {
          type: "example",
          de: "Entschuldigung, wo finde ich die Milch? Im Kühlregal hinten links. Danke! Gern geschehen!",
          en: "Excuse me, where can I find the milk? In the fridge section at the back left. Thanks! You're welcome!",
        },
        {
          type: "tip",
          text: "The customer question: Entschuldigung, wo finde ich ...? The answer: Im Regal, hinten/vorne, links/rechts. The two direction words: links (left) and rechts (right).",
        },
      ],
    },
    {
      heading: "Der Kleidungskauf",
      blocks: [
        {
          type: "paragraph",
          text: "The clothes dialogue combines looking, sizing, trying on, and buying. The seller asks Kann ich Ihnen helfen? (Can I help you?), you answer with Ich suche ... (I am looking for ...). The buying: Das passt mir gut, das nehme ich.",
        },
        {
          type: "table",
          caption: "The clothes dialogue",
          head: ["German", "English"],
          rows: [
            ["Kann ich Ihnen helfen?", "Can I help you?"],
            ["Ja, ich suche eine Bluse in Größe M.", "Yes, I am looking for a blouse in size M."],
            ["Welche Farbe möchten Sie?", "What colour would you like?"],
            ["Ich möchte eine weiße Bluse.", "I would like a white blouse."],
            ["Kann ich sie anprobieren?", "Can I try it on?"],
            ["Die Kabine ist dort.", "The fitting room is over there."],
            ["Sie passt gut, ich nehme sie.", "It fits well, I will take it."],
          ],
        },
        {
          type: "example",
          de: "Kann ich Ihnen helfen? Ja, ich suche eine Bluse in Größe M. Hier ist eine weiße. Kann ich sie anprobieren? Ja, die Kabine ist dort. Sie passt gut, ich nehme sie.",
          en: "Can I help you? Yes, I'm looking for a blouse in size M. Here is a white one. Can I try it on? Yes, the fitting room is over there. It fits well, I'll take it.",
        },
        {
          type: "tip",
          text: "The size question: Welche Größe haben Sie? The try-on: anprobieren. The decision: Das passt mir gut, ich nehme es.",
        },
      ],
    },
    {
      heading: "Preise vergleichen",
      blocks: [
        {
          type: "paragraph",
          text: "Comparing prices uses the comparative: günstig (cheap) against teuer (expensive), and the comparison words billiger als (cheaper than) and so teuer wie (as expensive as). The question: Ist das günstiger als das andere? (Is that cheaper than the other one?).",
        },
        {
          type: "table",
          caption: "Price comparisons",
          head: ["German", "English"],
          rows: [
            ["billiger als", "cheaper than"],
            ["teurer als", "more expensive than"],
            ["so günstig wie", "as cheap as"],
            ["das Sonderangebot", "the special offer"],
            ["der Rabatt", "the discount"],
            ["umsonst / gratis", "free of charge"],
          ],
        },
        {
          type: "example",
          de: "Dieses Hemd kostet 20 Euro, das andere 30 Euro. Das erste ist billiger als das zweite.",
          en: "This shirt costs 20 euros, the other one 30 euros. The first one is cheaper than the second one.",
        },
        {
          type: "tip",
          text: "The comparison pair: billiger als (cheaper than) and so teuer wie (as expensive as). The offer: Das ist im Sonderangebot.",
        },
      ],
    },
    {
      heading: "Der Umtausch",
      blocks: [
        {
          type: "paragraph",
          text: "Exchanging a purchase uses the verbs: umtauschen (to exchange), zurückgeben (to return), die Quittung (the receipt), der Kassenbon (the till receipt). The phrases: Ich möchte das umtauschen. (I would like to exchange this.) Haben Sie die Quittung? (Do you have the receipt?).",
        },
        {
          type: "table",
          caption: "The exchange script",
          head: ["German", "English"],
          rows: [
            ["Ich möchte das umtauschen.", "I would like to exchange this."],
            ["Das ist zu klein / zu groß.", "It is too small / too big."],
            ["Haben Sie die Quittung?", "Do you have the receipt?"],
            ["Hier ist der Kassenbon.", "Here is the till receipt."],
            ["Sie können ein anderes nehmen.", "You can take another one."],
          ],
        },
        {
          type: "example",
          de: "Guten Tag, ich möchte dieses T-Shirt umtauschen. Es ist zu klein. Haben Sie die Quittung? Ja, hier ist der Kassenbon. Sie können ein anderes nehmen.",
          en: "Good day, I would like to exchange this T-shirt. It is too small. Do you have the receipt? Yes, here is the receipt. You can take another one.",
        },
        {
          type: "tip",
          text: "The exchange reason: Es ist zu klein (too small) or zu groß (too big). The receipt: die Quittung, der Kassenbon.",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: wrong preposition for location, mixing the payment methods, and confusing the comparison words.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["location phrase", "Ich finde die Milch in Kühlregal.", "Im Kühlregal.", "in + dem = im"],
            ["payment mix", "Ich bezahle Karte.", "Ich bezahle mit Karte.", "payment takes mit"],
            ["comparison mix", "billig als", "billiger als", "the comparative takes -er"],
            ["too small", "Das ist zu klein.", "Das ist zu klein.", "keep zu before the adjective"],
            ["receipt loss", "Ich habe kein Bon.", "Ich habe keinen Kassenbon.", "Kassenbon is masculine"],
          ],
        },
        {
          type: "tip",
          text: "The shopping dialogue is a fixed script: ask (wo finde ich), decide (das nehme ich), pay (bar oder Karte), and exchange (umtauschen). Practise the full script aloud.",
        },
      ],
    },
  ],
  vocab: [
    { id: "das-regal", de: "das Regal", en: "the shelf", part: "noun n.", plural: "die Regale", audio: true },
    { id: "das-kuehlregal", de: "das Kühlregal", en: "the fridge (in the shop)", part: "noun n.", plural: "die Kühlregale", audio: true },
    { id: "die-kasse", de: "die Kasse", en: "the checkout", part: "noun f.", plural: "die Kassen", audio: true },
    { id: "der-bon", de: "der Bon", en: "the receipt", part: "noun m.", plural: "die Bons", audio: true },
    { id: "der-kassenbon", de: "der Kassenbon", en: "the till receipt", part: "noun m.", plural: "die Kassenbons", audio: true },
    { id: "die-quittung", de: "die Quittung", en: "the receipt", part: "noun f.", plural: "die Quittungen", audio: true },
    { id: "links", de: "links", en: "left", part: "adverb", audio: true },
    { id: "rechts", de: "rechts", en: "right", part: "adverb", audio: true },
    { id: "hinten", de: "hinten", en: "at the back", part: "adverb", audio: true },
    { id: "vorne", de: "vorne", en: "at the front", part: "adverb", audio: true },
    { id: "umtauschen", de: "umtauschen", en: "to exchange", part: "verb", audio: true },
    { id: "zurueckgeben", de: "zurückgeben", en: "to return", part: "verb", audio: true },
    { id: "das-sonderangebot", de: "das Sonderangebot", en: "the special offer", part: "noun n.", plural: "die Sonderangebote", audio: true },
    { id: "der-rabatt", de: "der Rabatt", en: "the discount", part: "noun m.", plural: "die Rabatte", audio: true },
    { id: "guenstig", de: "günstig", en: "cheap", part: "adjective", audio: true },
    { id: "billiger-als", de: "billiger als", en: "cheaper than", part: "phrase", phrase: true, audio: true },
    { id: "teurer-als", de: "teurer als", en: "more expensive than", part: "phrase", phrase: true, audio: true },
    { id: "wo-finde-ich", de: "Entschuldigung, wo finde ich die Milch?", en: "Excuse me, where do I find the milk?", part: "phrase", phrase: true, audio: true },
    { id: "zahlen-sie-bar-oder-mit-karte", de: "Zahlen Sie bar oder mit Karte?", en: "Cash or card?", part: "phrase", phrase: true, audio: true },
    { id: "das-nehme-ich", de: "Das nehme ich.", en: "I will take it.", part: "phrase", phrase: true, audio: true },
    { id: "das-ist-zu-klein", de: "Das ist zu klein.", en: "It is too small.", part: "phrase", phrase: true, audio: true },
    { id: "ich-moechte-das-umtauschen", de: "Ich möchte das umtauschen.", en: "I would like to exchange this.", part: "phrase", phrase: true, audio: true },
    { id: "hier-ist-ihr-bon", de: "Hier ist Ihr Bon.", en: "Here is your receipt.", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-supermarkt",
      type: "multiple-choice",
      title: "Übung 1: Im Supermarkt",
      instruction: "Choose the question for finding milk.",
      prompt: "You ask where the milk is.",
      options: ["Entschuldigung, wo finde ich die Milch?", "Entschuldigung, wo ist die Milch kaufen?", "Entschuldigung, was kostet die Milch?"],
      correctIndex: 0,
      explain: "The finding question: wo finde ich ...?",
    },
    {
      id: "ex-kasse",
      type: "multiple-choice",
      title: "Übung 2: An der Kasse",
      instruction: "Choose the checkout question.",
      prompt: "The cashier asks how you pay.",
      options: ["Zahlen Sie bar oder mit Karte?", "Was kostet das?", "Möchten Sie einen Bon?"],
      correctIndex: 0,
      explain: "Payment question: bar oder mit Karte.",
    },
    {
      id: "ex-zahlen",
      type: "multiple-choice",
      title: "Übung 3: Bezahlen",
      instruction: "Choose the correct answer.",
      prompt: "You pay by card.",
      options: ["Mit Karte, bitte.", "Bar, bitte.", "Karte, bitte."],
      correctIndex: 0,
      explain: "Payment takes mit.",
    },
    {
      id: "ex-kleidung",
      type: "multiple-choice",
      title: "Übung 4: Der Kleidungskauf",
      instruction: "Choose the buying sentence.",
      prompt: "The blouse fits, you take it.",
      options: ["Sie passt gut, ich nehme sie.", "Sie ist gut, ich kaufe sie.", "Sie passt, ich nehme es."],
      correctIndex: 0,
      explain: "The fit decision: passt gut, ich nehme sie.",
    },
    {
      id: "ex-groesse",
      type: "multiple-choice",
      title: "Übung 5: Die Größe",
      instruction: "Choose the size answer.",
      prompt: "The seller asks your size.",
      options: ["Ich habe Größe M.", "Ich bin Größe M.", "Ich trage Größe M."],
      correctIndex: 0,
      explain: "The size phrase: Ich habe Größe M.",
    },
    {
      id: "ex-anprobieren",
      type: "multiple-choice",
      title: "Übung 6: anprobieren",
      instruction: "Choose the try-on question.",
      prompt: "You ask to try on the blouse.",
      options: ["Kann ich sie anprobieren?", "Kann ich sie ansehen?", "Kann ich sie anziehen?"],
      correctIndex: 0,
      explain: "Trying on: anprobieren.",
    },
    {
      id: "ex-vergleichen",
      type: "multiple-choice",
      title: "Übung 7: Preise vergleichen",
      instruction: "Choose the correct comparison.",
      prompt: "The first shirt is cheaper than the second.",
      options: ["Das erste ist billiger als das zweite.", "Das erste ist billiger als das zweite. Nein, so günstig wie.", "Das erste ist so billig wie das zweite."],
      correctIndex: 0,
      explain: "Comparisons take -er als.",
    },
    {
      id: "ex-umtauschen",
      type: "multiple-choice",
      title: "Übung 8: Der Umtausch",
      instruction: "Choose the exchange sentence.",
      prompt: "You want to exchange the T-shirt.",
      options: ["Ich möchte dieses T-Shirt umtauschen.", "Ich möchte dieses T-Shirt zurückgehen.", "Ich möchte dieses T-Shirt neu kaufen."],
      correctIndex: 0,
      explain: "The exchange verb: umtauschen.",
    },
    {
      id: "ex-quittung",
      type: "multiple-choice",
      title: "Übung 9: Die Quittung",
      instruction: "Choose the receipt phrase.",
      prompt: "The seller asks for the receipt.",
      options: ["Haben Sie die Quittung?", "Haben Sie das Geld?", "Haben Sie den Bon nicht?"],
      correctIndex: 0,
      explain: "The receipt question: die Quittung.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 10: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Zahlen Sie bar oder mit Karte?",
      options: ["Zahlen Sie bar oder mit Karte?", "Zahlen Sie mit Karte oder mit Bargeld?", "Möchten Sie bar bezahlen?"],
      correctIndex: 0,
      explain: "The payment question heard.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 11: Hören",
      instruction: "Play the audio and pick the phrase you heard.",
      prompt: "Im Kühlregal, hinten links.",
      options: ["Im Kühlregal, hinten links.", "Im Kühlregal, vorne rechts.", "Im Regal, hinten rechts."],
      correctIndex: 0,
      explain: "The location heard: back left.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 12: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Das ist zu klein.", "Das ist zu der klein.", "Das ist zu kleines."],
      correctIndex: 0,
      explain: "zu comes before the bare adjective.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 13: Der Satz",
      instruction: "Build the sentence: Where do I find the milk?",
      chunks: ["Wo", "finde", "ich", "die", "Milch?"], translation: "Where can I find the milk?",
      explain: "The finding question.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 14: Der Satz",
      instruction: "Build the sentence: I would like to exchange this.",
      chunks: ["Ich", "möchte", "das", "umtauschen."], translation: "I would like to exchange that.",
      explain: "The exchange sentence.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 15: Einkaufskarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "Entschuldigung, wo finde ich die Milch?", back: "Excuse me, where do I find the milk?", frontAudio: true },
        { front: "Im Kühlregal, hinten links.", back: "In the fridge, back left.", frontAudio: true },
        { front: "Zahlen Sie bar oder mit Karte?", back: "Cash or card?", frontAudio: true },
        { front: "Mit Karte, bitte.", back: "By card, please.", frontAudio: true },
        { front: "Ich suche eine Bluse in Größe M.", back: "I am looking for a blouse in size M.", frontAudio: true },
        { front: "Das passt mir gut, ich nehme es.", back: "It fits well, I will take it.", frontAudio: true },
        { front: "billiger als", back: "cheaper than", frontAudio: true },
        { front: "Ich möchte das umtauschen.", back: "I would like to exchange this.", frontAudio: true },
        { front: "Das ist zu klein.", back: "It is too small.", frontAudio: true },
        { front: "die Quittung", back: "the receipt", frontAudio: true },
        { front: "der Kassenbon", back: "the till receipt", frontAudio: true },
        { front: "Hier ist Ihr Bon.", back: "Here is your receipt.", frontAudio: true },
      ],
    },
  ],
};

export const kontraktionen: Lesson = {
  id: "kontraktionen",
  title: "Kontraktionen",
  summary:
    "The contracted preposition-article combinations: im, am, ins, aufs, zum, zur, vom and beim, with the rules for when they are mandatory.",
  status: "ready",
  sections: [
    {
      heading: "Die Grundkontraktionen",
      blocks: [
        {
          type: "paragraph",
          text: "German merges some prepositions with the following article into one word. The two most common: in + dem = im and in + das = ins. The full A1 set: am (an dem), im (in dem), ins (in das), aufs (auf das), zum (zu dem), zur (zu der), vom (von dem), beim (bei dem).",
        },
        {
          type: "table",
          caption: "The contractions",
          head: ["Preposition + article", "Contraction", "Example"],
          rows: [
            ["an + dem", "am", "am Montag"],
            ["in + dem", "im", "im Sommer"],
            ["in + das", "ins", "ins Kino"],
            ["auf + das", "aufs", "aufs Land"],
            ["zu + dem", "zum", "zum Bahnhof"],
            ["zu + der", "zur", "zur Schule"],
            ["von + dem", "vom", "vom Bahnhof"],
            ["bei + dem", "beim", "beim Arzt"],
          ],
        },
        {
          type: "example",
          de: "Ich bin am Montag im Büro und gehe abends ins Kino. Danach fahre ich zum Bahnhof.",
          en: "I am in the office on Monday and go to the cinema in the evening. Afterwards I drive to the station.",
        },
        {
          type: "tip",
          text: "The two words merge when they feel natural together. am for days, im for months and seasons, zum for directions, beim for people.",
        },
      ],
    },
    {
      heading: "am, im und die Zeit",
      blocks: [
        {
          type: "paragraph",
          text: "The time contractions: am + day or date (am Montag, am 5. Mai), im + month or season (im Januar, im Sommer), and the pair in der Nacht but am Abend, am Morgen, am Nachmittag. The preposition carries the time expression.",
        },
        {
          type: "table",
          caption: "Time contractions",
          head: ["Expression", "Contraction", "Example"],
          rows: [
            ["day", "am", "am Montag"],
            ["date", "am", "am 5. Mai"],
            ["month", "im", "im Januar"],
            ["season", "im", "im Sommer"],
            ["morning", "am", "am Morgen"],
            ["evening", "am", "am Abend"],
          ],
        },
        {
          type: "example",
          de: "Am Montag gehe ich ins Büro. Im Sommer fahren wir aufs Land. Am Abend lese ich ein Buch.",
          en: "On Monday I go to the office. In summer we drive to the countryside. In the evening I read a book.",
        },
        {
          type: "tip",
          text: "The time rule: days take am, months and seasons take im. The one oddity: die Nacht takes in der Nacht.",
        },
      ],
    },
    {
      heading: "zum, zur und die Richtung",
      blocks: [
        {
          type: "paragraph",
          text: "The direction contractions: zu + dem = zum for masculine and neuter targets, zu + der = zur for feminine targets. The pattern: zum Bahnhof (m.), zum Supermarkt (m.), zur Schule (f.), zur Arbeit (f.). The question: Wohin gehst du? Ich gehe zum Bahnhof.",
        },
        {
          type: "table",
          caption: "Direction contractions",
          head: ["Target", "Gender", "Form"],
          rows: [
            ["der Bahnhof", "masculine", "zum Bahnhof"],
            ["der Supermarkt", "masculine", "zum Supermarkt"],
            ["das Kino", "neuter", "zum Kino"],
            ["die Schule", "feminine", "zur Schule"],
            ["die Arbeit", "feminine", "zur Arbeit"],
          ],
        },
        {
          type: "example",
          de: "Ich gehe zum Bahnhof. Dann fahre ich zur Arbeit. Nach der Arbeit gehe ich noch zum Supermarkt.",
          en: "I go to the station. Then I drive to work. After work I also go to the supermarket.",
        },
        {
          type: "tip",
          text: "The direction test: masculine and neuter take zum, feminine takes zur. The pair: zum Arzt (m.) and zur Ärztin (f.).",
        },
      ],
    },
    {
      heading: "vom, beim und die Lage",
      blocks: [
        {
          type: "paragraph",
          text: "The position contractions: von + dem = vom for origin (vom Bahnhof, from the station), bei + dem = beim for being with or at someone (beim Arzt, at the doctor, beim Essen, at eating). The pair: Ich komme vom Bahnhof and Ich bin beim Arzt.",
        },
        {
          type: "table",
          caption: "Position contractions",
          head: ["Expression", "Meaning", "Example"],
          rows: [
            ["vom Bahnhof", "from the station", "Ich komme vom Bahnhof."],
            ["vom Markt", "from the market", "Wir kommen vom Markt."],
            ["beim Arzt", "at the doctor", "Ich bin beim Arzt."],
            ["beim Essen", "at eating", "Beim Essen sprechen wir."],
            ["beim Friseur", "at the hairdresser", "Sie ist beim Friseur."],
          ],
        },
        {
          type: "example",
          de: "Ich komme gerade vom Bahnhof und bin jetzt beim Arzt. Nachher gehe ich zum Friseur.",
          en: "I've just come from the station and am now at the doctor's. Afterwards I'm going to the hairdresser.",
        },
        {
          type: "tip",
          text: "vom answers Woher? (from where), beim answers Wo? (with whom/at what). The pair test: Woher kommst du? Vom Bahnhof.",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: not contracting where German requires it, and contracting where it is not allowed.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["day contraction", "an dem Montag", "am Montag", "days take am"],
            ["direction contraction", "zu dem Bahnhof", "zum Bahnhof", "masculine direction takes zum"],
            ["feminine contraction", "zu dem Schule", "zur Schule", "feminine takes zur"],
            ["month contraction", "in Januar", "im Januar", "months take im"],
            ["double contraction", "am dem Morgen", "am Morgen", "the article is already inside"],
          ],
        },
        {
          type: "tip",
          text: "The contraction table is the whole system: am for days, im for months, zum/zur for directions, vom for origin, beim for people. Learn the table and the pair test.",
        },
      ],
    },
  ],
  vocab: [
    { id: "am-montag", de: "am Montag", en: "on Monday", part: "phrase", phrase: true, audio: true },
    { id: "am-abend", de: "am Abend", en: "in the evening", part: "phrase", phrase: true, audio: true },
    { id: "am-morgen", de: "am Morgen", en: "in the morning", part: "phrase", phrase: true, audio: true },
    { id: "im-sommer", de: "im Sommer", en: "in summer", part: "phrase", phrase: true, audio: true },
    { id: "im-winter", de: "im Winter", en: "in winter", part: "phrase", phrase: true, audio: true },
    { id: "im-januar", de: "im Januar", en: "in January", part: "phrase", phrase: true, audio: true },
    { id: "ins-kino", de: "ins Kino", en: "to the cinema", part: "phrase", phrase: true, audio: true },
    { id: "aufs-land", de: "aufs Land", en: "to the countryside", part: "phrase", phrase: true, audio: true },
    { id: "zum-bahnhof", de: "zum Bahnhof", en: "to the station", part: "phrase", phrase: true, audio: true },
    { id: "zum-supermarkt", de: "zum Supermarkt", en: "to the supermarket", part: "phrase", phrase: true, audio: true },
    { id: "zur-schule", de: "zur Schule", en: "to school", part: "phrase", phrase: true, audio: true },
    { id: "zur-arbeit", de: "zur Arbeit", en: "to work", part: "phrase", phrase: true, audio: true },
    { id: "vom-bahnhof", de: "vom Bahnhof", en: "from the station", part: "phrase", phrase: true, audio: true },
    { id: "beim-arzt", de: "beim Arzt", en: "at the doctor", part: "phrase", phrase: true, audio: true },
    { id: "beim-essen", de: "beim Essen", en: "at eating", part: "phrase", phrase: true, audio: true },
    { id: "beim-friseur", de: "beim Friseur", en: "at the hairdresser", part: "phrase", phrase: true, audio: true },
    { id: "in-der-nacht", de: "in der Nacht", en: "at night", part: "phrase", phrase: true, audio: true },
    { id: "ich-komme-vom-bahnhof", de: "Ich komme vom Bahnhof.", en: "I am coming from the station.", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-paar",
      type: "matching",
      title: "Übung 1: Die Kontraktionen",
      instruction: "Match each contraction to its full form.",
      pairs: [
        ["im", "in + dem"],
        ["ins", "in + das"],
        ["am", "an + dem"],
        ["zum", "zu + dem"],
        ["zur", "zu + der"],
        ["vom", "von + dem"],
      ],
    },
    {
      id: "ex-tag",
      type: "multiple-choice",
      title: "Übung 2: Der Tag",
      instruction: "Choose the correct contraction.",
      prompt: "I work on Monday.",
      options: ["Am Montag arbeite ich.", "Im Montag arbeite ich.", "An Montag arbeite ich."],
      correctIndex: 0,
      explain: "Days take am.",
    },
    {
      id: "ex-monat",
      type: "multiple-choice",
      title: "Übung 3: Der Monat",
      instruction: "Choose the correct contraction.",
      prompt: "It is cold in January.",
      options: ["Im Januar ist es kalt.", "Am Januar ist es kalt.", "In Januar ist es kalt."],
      correctIndex: 0,
      explain: "Months take im.",
    },
    {
      id: "ex-richtung",
      type: "multiple-choice",
      title: "Übung 4: Die Richtung",
      instruction: "Choose the correct contraction.",
      prompt: "I am going to the station.",
      options: ["zum Bahnhof", "zur Bahnhof", "zu dem Bahnhof"],
      correctIndex: 0,
      explain: "Masculine direction takes zum.",
    },
    {
      id: "ex-richtung-2",
      type: "multiple-choice",
      title: "Übung 5: Die Richtung",
      instruction: "Choose the correct contraction.",
      prompt: "She is going to school.",
      options: ["zur Schule", "zum Schule", "zu Schule"],
      correctIndex: 0,
      explain: "Feminine direction takes zur.",
    },
    {
      id: "ex-woher",
      type: "multiple-choice",
      title: "Übung 6: Woher?",
      instruction: "Choose the correct answer.",
      prompt: "Woher kommst du?",
      options: ["Vom Bahnhof.", "Zum Bahnhof.", "Ins Bahnhof."],
      correctIndex: 0,
      explain: "Origin takes vom.",
    },
    {
      id: "ex-bei",
      type: "multiple-choice",
      title: "Übung 7: beim",
      instruction: "Choose the correct phrase.",
      prompt: "I am at the doctor.",
      options: ["Ich bin beim Arzt.", "Ich bin zum Arzt.", "Ich bin am Arzt."],
      correctIndex: 0,
      explain: "Being at someone takes beim.",
    },
    {
      id: "ex-kino",
      type: "multiple-choice",
      title: "Übung 8: ins",
      instruction: "Choose the correct phrase.",
      prompt: "We are going to the cinema.",
      options: ["Wir gehen ins Kino.", "Wir gehen im Kino.", "Wir gehen in dem Kino."],
      correctIndex: 0,
      explain: "Direction into the cinema: ins.",
    },
    {
      id: "ex-nacht",
      type: "multiple-choice",
      title: "Übung 9: Die Nacht",
      instruction: "Choose the correct phrase.",
      prompt: "At night.",
      options: ["in der Nacht", "am Nacht", "im Nacht"],
      correctIndex: 0,
      explain: "The night exception: in der Nacht.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 10: Hören",
      instruction: "Play the audio and pick the phrase you heard.",
      prompt: "am Montag",
      options: ["am Montag", "im Montag", "zum Montag"],
      correctIndex: 0,
      explain: "The contraction heard: on Monday.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 11: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Ich gehe zum Bahnhof.",
      options: ["Ich gehe zum Bahnhof.", "Ich gehe zur Schule.", "Ich komme vom Bahnhof."],
      correctIndex: 0,
      explain: "The direction sentence heard.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 12: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Ich bin am Montag im Büro.", "Ich bin an Montag im Büro.", "Ich bin am Montag in Büro."],
      correctIndex: 0,
      explain: "Days take am, offices take im.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 13: Der Satz",
      instruction: "Build the sentence: I am going to the supermarket.",
      chunks: ["Ich", "gehe", "zum", "Supermarkt."], translation: "I am going to the supermarket.",
      explain: "Masculine direction takes zum.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 14: Der Satz",
      instruction: "Build the sentence: We are coming from the market.",
      chunks: ["Wir", "kommen", "vom", "Markt."], translation: "We are coming from the market.",
      explain: "Origin takes vom.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 15: Kontraktionskarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "am Montag", back: "on Monday", frontAudio: true },
        { front: "im Sommer", back: "in summer", frontAudio: true },
        { front: "ins Kino", back: "to the cinema", frontAudio: true },
        { front: "zum Bahnhof", back: "to the station", frontAudio: true },
        { front: "zur Schule", back: "to school", frontAudio: true },
        { front: "zur Arbeit", back: "to work", frontAudio: true },
        { front: "vom Bahnhof", back: "from the station", frontAudio: true },
        { front: "beim Arzt", back: "at the doctor", frontAudio: true },
        { front: "aufs Land", back: "to the countryside", frontAudio: true },
        { front: "in der Nacht", back: "at night", frontAudio: true },
        { front: "Ich gehe zum Bahnhof.", back: "I am going to the station.", frontAudio: true },
        { front: "Ich komme vom Bahnhof.", back: "I am coming from the station.", frontAudio: true },
      ],
    },
  ],
};

export const umtauschUndReklamation: Lesson = {
  id: "umtausch-und-reklamation",
  title: "Umtausch und Reklamation",
  summary:
    "Exchanging and complaining: the return dialogue, the reasons, the receipt, and the full complaint script at the shop.",
  status: "ready",
  sections: [
    {
      heading: "Der Umtausch",
      blocks: [
        {
          type: "paragraph",
          text: "Umtausch (exchange) is the shop scenario where you bring something back. The verbs: umtauschen (to exchange), zurückgeben (to return), reklamieren (to complain). The script: name the problem, show the receipt, get the exchange. The key phrase: Ich möchte das umtauschen.",
        },
        {
          type: "table",
          caption: "The exchange script",
          head: ["German", "English"],
          rows: [
            ["Ich möchte das umtauschen.", "I would like to exchange this."],
            ["Es ist zu klein.", "It is too small."],
            ["Es passt nicht.", "It does not fit."],
            ["Haben Sie die Quittung?", "Do you have the receipt?"],
            ["Ja, hier ist der Kassenbon.", "Yes, here is the till receipt."],
            ["Sie können ein anderes nehmen.", "You can take another one."],
            ["Danke, ich nehme das.", "Thank you, I will take this one."],
          ],
        },
        {
          type: "example",
          de: "Guten Tag, ich möchte dieses T-Shirt umtauschen. Es ist zu klein. Haben Sie die Quittung? Ja, hier. Sie können ein anderes nehmen. Danke, ich nehme das.",
          en: "Good day, I would like to exchange this T-shirt. It is too small. Do you have the receipt? Yes, here. You can take another one. Thanks, I'll take that one.",
        },
        {
          type: "tip",
          text: "The exchange reasons: zu klein, zu groß, es passt nicht, die Farbe gefällt mir nicht. The two receipt words: die Quittung, der Kassenbon.",
        },
      ],
    },
    {
      heading: "Die Reklamation",
      blocks: [
        {
          type: "paragraph",
          text: "Reklamation (complaint) covers defective goods. The verbs: reklamieren (to complain), kaputt (broken), funktioniert nicht (does not work), die Reklamation (the complaint). The script: say what is broken, show the receipt, ask for a replacement or your money back.",
        },
        {
          type: "table",
          caption: "The complaint script",
          head: ["German", "English"],
          rows: [
            ["Ich möchte reklamieren.", "I would like to complain."],
            ["Die Jacke ist kaputt.", "The jacket is broken."],
            ["Der Reißverschluss funktioniert nicht.", "The zip does not work."],
            ["Ich möchte mein Geld zurück.", "I would like my money back."],
            ["Ich möchte einen Ersatz.", "I would like a replacement."],
            ["Wir entschuldigen uns.", "We apologise."],
          ],
        },
        {
          type: "example",
          de: "Ich möchte reklamieren. Die Jacke ist kaputt, der Reißverschluss funktioniert nicht. Haben Sie den Kassenbon? Ja, hier bitte. Wir entschuldigen uns, hier ist Ihr Geld zurück.",
          en: "I would like to make a complaint. The jacket is broken, the zip doesn't work. Do you have the receipt? Yes, here you go. We apologise, here is your money back.",
        },
        {
          type: "tip",
          text: "The two outcomes of a complaint: Geld zurück (money back) or einen Ersatz (a replacement). The apology: Wir entschuldigen uns.",
        },
      ],
    },
    {
      heading: "Der Reißverschluss und die Details",
      blocks: [
        {
          type: "paragraph",
          text: "The complaint details name the failing part: der Reißverschluss (zip), der Knopf (button), die Naht (seam), der Ärmel (sleeve), das Loch (hole). The pattern: Das + part + ist kaputt or funktioniert nicht.",
        },
        {
          type: "table",
          caption: "The failing parts",
          head: ["German", "English", "Plural"],
          rows: [
            ["der Reißverschluss", "the zip", "die Reißverschlüsse"],
            ["der Knopf", "the button", "die Knöpfe"],
            ["die Naht", "the seam", "die Nähte"],
            ["der Ärmel", "the sleeve", "die Ärmel"],
            ["das Loch", "the hole", "die Löcher"],
            ["die Sohle", "the sole", "die Sohlen"],
          ],
        },
        {
          type: "example",
          de: "An der Hose fehlt ein Knopf. An der Jacke ist der Reißverschluss kaputt. An dem Schuh ist die Sohle kaputt.",
          en: "The trousers are missing a button. The zip on the jacket is broken. The sole of the shoe is broken.",
        },
        {
          type: "tip",
          text: "The complaint detail: An dem Schuh ist die Sohle kaputt. The preposition an + dative names where the problem is.",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: confusing umtauschen and zurückgeben, using the wrong receipt word, and forgetting the separable verb.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["umtauschen/zurückgeben mix", "Ich möchte das zurückschenken.", "Ich möchte das umtauschen.", "the exchange verb is umtauschen"],
            ["wrong receipt", "Haben Sie das Geld?", "Haben Sie die Quittung?", "the shop needs the receipt"],
            ["separable verb", "Ich umtausche das.", "Ich möchte das umtauschen.", "möchte + infinitive is the form"],
            ["kaputt grammar", "Das ist kaputt gegangen.", "Das ist kaputt.", "the simple form covers it"],
            ["wrong part", "An der Jacke ist der Ärmel kaputt.", "correct", "name the exact part"],
          ],
        },
        {
          type: "tip",
          text: "The complaint is a fixed script: reklamieren, the broken part, the receipt, the solution (Geld zurück or Ersatz).",
        },
      ],
    },
  ],
  vocab: [
    { id: "umtauschen", de: "umtauschen", en: "to exchange", part: "verb", audio: true },
    { id: "zurueckgeben", de: "zurückgeben", en: "to return", part: "verb", audio: true },
    { id: "reklamieren", de: "reklamieren", en: "to complain", part: "verb", audio: true },
    { id: "die-reklamation", de: "die Reklamation", en: "the complaint", part: "noun f.", plural: "die Reklamationen", audio: true },
    { id: "die-quittung", de: "die Quittung", en: "the receipt", part: "noun f.", plural: "die Quittungen", audio: true },
    { id: "der-kassenbon", de: "der Kassenbon", en: "the till receipt", part: "noun m.", plural: "die Kassenbons", audio: true },
    { id: "der-ersatz", de: "der Ersatz", en: "the replacement", part: "noun m.", audio: true },
    { id: "kaputt", de: "kaputt", en: "broken", part: "adjective", audio: true },
    { id: "der-reissverschluss", de: "der Reißverschluss", en: "the zip", part: "noun m.", plural: "die Reißverschlüsse", audio: true },
    { id: "der-knopf", de: "der Knopf", en: "the button", part: "noun m.", plural: "die Knöpfe", audio: true },
    { id: "die-naht", de: "die Naht", en: "the seam", part: "noun f.", plural: "die Nähte", audio: true },
    { id: "der-aermel", de: "der Ärmel", en: "the sleeve", part: "noun m.", plural: "die Ärmel", audio: true },
    { id: "das-loch", de: "das Loch", en: "the hole", part: "noun n.", plural: "die Löcher", audio: true },
    { id: "ich-moechte-das-umtauschen", de: "Ich möchte das umtauschen.", en: "I would like to exchange this.", part: "phrase", phrase: true, audio: true },
    { id: "es-ist-zu-klein", de: "Es ist zu klein.", en: "It is too small.", part: "phrase", phrase: true, audio: true },
    { id: "haben-sie-die-quittung", de: "Haben Sie die Quittung?", en: "Do you have the receipt?", part: "phrase", phrase: true, audio: true },
    { id: "ich-moechte-reklamieren", de: "Ich möchte reklamieren.", en: "I would like to complain.", part: "phrase", phrase: true, audio: true },
    { id: "die-jacke-ist-kaputt", de: "Die Jacke ist kaputt.", en: "The jacket is broken.", part: "phrase", phrase: true, audio: true },
    { id: "ich-moechte-mein-geld-zurueck", de: "Ich möchte mein Geld zurück.", en: "I would like my money back.", part: "phrase", phrase: true, audio: true },
    { id: "wir-entschuldigen-uns", de: "Wir entschuldigen uns.", en: "We apologise.", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-umtausch",
      type: "multiple-choice",
      title: "Übung 1: Der Umtausch",
      instruction: "Choose the exchange sentence.",
      prompt: "You want to exchange the shirt.",
      options: ["Ich möchte das Hemd umtauschen.", "Ich möchte das Hemd zurückgehen.", "Ich möchte das Hemd neu kaufen."],
      correctIndex: 0,
      explain: "The exchange verb: umtauschen.",
    },
    {
      id: "ex-grund",
      type: "multiple-choice",
      title: "Übung 2: Der Grund",
      instruction: "Choose the exchange reason.",
      prompt: "The shirt is too small.",
      options: ["Es ist zu klein.", "Es ist zu groß.", "Es ist sehr gut."],
      correctIndex: 0,
      explain: "The small reason: zu klein.",
    },
    {
      id: "ex-quittung",
      type: "multiple-choice",
      title: "Übung 3: Die Quittung",
      instruction: "Choose the receipt question.",
      prompt: "The seller asks for the receipt.",
      options: ["Haben Sie die Quittung?", "Haben Sie das Geld?", "Haben Sie die Rechnung?"],
      correctIndex: 0,
      explain: "The receipt: die Quittung.",
    },
    {
      id: "ex-reklamation",
      type: "multiple-choice",
      title: "Übung 4: Die Reklamation",
      instruction: "Choose the complaint sentence.",
      prompt: "You want to complain.",
      options: ["Ich möchte reklamieren.", "Ich möchte umtauschen.", "Ich möchte zahlen."],
      correctIndex: 0,
      explain: "The complaint verb: reklamieren.",
    },
    {
      id: "ex-kaputt",
      type: "multiple-choice",
      title: "Übung 5: Die Jacke",
      instruction: "Choose the correct sentence.",
      prompt: "The jacket is broken.",
      options: ["Die Jacke ist kaputt.", "Die Jacke hat kaputt.", "Die Jacke ist kaputt gegangen."],
      correctIndex: 0,
      explain: "The simple broken sentence.",
    },
    {
      id: "ex-teil",
      type: "multiple-choice",
      title: "Übung 6: Der Teil",
      instruction: "Choose the correct part.",
      prompt: "The zip does not work.",
      options: ["Der Reißverschluss funktioniert nicht.", "Der Knopf funktioniert nicht.", "Die Naht funktioniert nicht."],
      correctIndex: 0,
      explain: "The zip: der Reißverschluss.",
    },
    {
      id: "ex-geld",
      type: "multiple-choice",
      title: "Übung 7: Das Geld zurück",
      instruction: "Choose the money-back phrase.",
      prompt: "You want your money back.",
      options: ["Ich möchte mein Geld zurück.", "Ich möchte mein Geld kaufen.", "Ich möchte das Geld neu."],
      correctIndex: 0,
      explain: "The refund phrase: Geld zurück.",
    },
    {
      id: "ex-ersatz",
      type: "multiple-choice",
      title: "Übung 8: Der Ersatz",
      instruction: "Choose the replacement phrase.",
      prompt: "You want a replacement.",
      options: ["Ich möchte einen Ersatz.", "Ich möchte ein Ersatz.", "Ich möchte eine Ersatz."],
      correctIndex: 0,
      explain: "Ersatz is masculine: einen Ersatz.",
    },
    {
      id: "ex-entschuldigung",
      type: "multiple-choice",
      title: "Übung 9: Die Entschuldigung",
      instruction: "Choose the apology.",
      prompt: "The shop apologises.",
      options: ["Wir entschuldigen uns.", "Wir sagen sorry.", "Wir sind entschuldigt."],
      correctIndex: 0,
      explain: "The apology: Wir entschuldigen uns.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 10: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Ich möchte das umtauschen.",
      options: ["Ich möchte das umtauschen.", "Ich möchte das zurückgeben.", "Ich möchte reklamieren."],
      correctIndex: 0,
      explain: "The exchange sentence heard.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 11: Hören",
      instruction: "Play the audio and pick the phrase you heard.",
      prompt: "Haben Sie die Quittung?",
      options: ["Haben Sie die Quittung?", "Haben Sie den Kassenbon?", "Wo ist die Quittung?"],
      correctIndex: 0,
      explain: "The receipt question heard.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 12: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Ich möchte das umtauschen.", "Ich möchte das umgetauschen.", "Ich umtauschen das."],
      correctIndex: 0,
      explain: "möchte + infinitive.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 13: Der Satz",
      instruction: "Build the sentence: The jacket is broken.",
      chunks: ["Die", "Jacke", "ist", "kaputt."], translation: "The jacket is broken.",
      explain: "The broken sentence.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 14: Der Satz",
      instruction: "Build the sentence: I would like my money back.",
      chunks: ["Ich", "möchte", "mein", "Geld", "zurück."], translation: "I would like my money back.",
      explain: "The refund sentence.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 15: Reklamationskarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "Ich möchte das umtauschen.", back: "I would like to exchange this.", frontAudio: true },
        { front: "Es ist zu klein.", back: "It is too small.", frontAudio: true },
        { front: "Haben Sie die Quittung?", back: "Do you have the receipt?", frontAudio: true },
        { front: "Ich möchte reklamieren.", back: "I would like to complain.", frontAudio: true },
        { front: "Die Jacke ist kaputt.", back: "The jacket is broken.", frontAudio: true },
        { front: "Der Reißverschluss funktioniert nicht.", back: "The zip does not work.", frontAudio: true },
        { front: "Ich möchte mein Geld zurück.", back: "I would like my money back.", frontAudio: true },
        { front: "Ich möchte einen Ersatz.", back: "I would like a replacement.", frontAudio: true },
        { front: "Wir entschuldigen uns.", back: "We apologise.", frontAudio: true },
        { front: "die Quittung", back: "the receipt", frontAudio: true },
        { front: "der Kassenbon", back: "the till receipt", frontAudio: true },
        { front: "der Reißverschluss", back: "the zip", frontAudio: true },
      ],
    },
  ],
};

export const einkaufen: Unit = {
  id: "einkaufen",
  title: "Einkaufen",
  theme: "Shopping",
  lessons: [
    kleidung,
    einkaufsdialoge,
    kontraktionen,
    umtauschUndReklamation,
  ],
};