import type { Lesson, Unit } from "../../schema";

const kleidung: Lesson = {
  id: "kleidung",
  title: "Kleidung",
  summary: "Clothes, sizes, and colors.",
  status: "ready",
  sections: [
    {
      heading: "Die Kleidung",
      blocks: [
        {
          type: "table",
          caption: "Clothes",
          head: ["German", "English"],
          rows: [
            ["die Hose", "the pants"],
            ["das Hemd", "the shirt"],
            ["das T-Shirt", "the T-shirt"],
            ["die Jacke", "the jacket"],
            ["der Mantel", "the coat"],
            ["der Pullover", "the sweater"],
            ["der Rock", "the skirt"],
            ["das Kleid", "the dress"],
            ["die Schuhe", "the shoes"],
            ["die Socken", "the socks"],
            ["die Mütze", "the cap"],
            ["der Schal", "the scarf"],
            ["die Handschuhe", "the gloves"],
            ["die Größe", "the size"],
          ],
        },
        {
          type: "tip",
          text: "Clothes are plural in pairs: die Schuhe, die Socken, die Handschuhe. Ein Paar Schuhe is a pair of shoes.",
        },
      ],
    },
    {
      heading: "Im Geschäft",
      blocks: [
        {
          type: "example",
          de: "Ich suche eine Hose in Größe 38.",
          en: "I am looking for pants in size 38.",
        },
        {
          type: "example",
          de: "Welche Farbe möchten Sie? Blau, bitte.",
          en: "Which color would you like? Blue, please.",
        },
        {
          type: "example",
          de: "Die Jacke ist zu groß. Haben Sie sie in klein?",
          en: "The jacket is too big. Do you have it in small?",
        },
        {
          type: "tip",
          text: "suchen + accusative: Ich suche eine Hose. The article after suchen is always ein/eine because you do not know the object yet.",
        },
      ],
    },
  ],
  vocab: [
    { id: "die-hose", de: "die Hose", en: "the pants", part: "noun f.", plural: "die Hosen", audio: true },
    { id: "das-hemd", de: "das Hemd", en: "the shirt", part: "noun n.", plural: "die Hemden", audio: true },
    { id: "das-tshirt", de: "das T-Shirt", en: "the T-shirt", part: "noun n.", plural: "die T-Shirts", audio: true },
    { id: "die-jacke", de: "die Jacke", en: "the jacket", part: "noun f.", plural: "die Jacken", audio: true },
    { id: "der-mantel", de: "der Mantel", en: "the coat", part: "noun m.", plural: "die Mäntel", audio: true },
    { id: "der-pullover", de: "der Pullover", en: "the sweater", part: "noun m.", plural: "die Pullover", audio: true },
    { id: "das-kleid", de: "das Kleid", en: "the dress", part: "noun n.", plural: "die Kleider", audio: true },
    { id: "die-schuhe", de: "die Schuhe", en: "the shoes", part: "noun pl.", plural: "-", audio: true },
    { id: "die-socken", de: "die Socken", en: "the socks", part: "noun pl.", plural: "-", audio: true },
    { id: "die-muetze", de: "die Mütze", en: "the cap", part: "noun f.", plural: "die Mützen", audio: true },
    { id: "der-schal", de: "der Schal", en: "the scarf", part: "noun m.", plural: "die Schals", audio: true },
    { id: "die-groesse", de: "die Größe", en: "the size", part: "noun f.", plural: "die Größen", audio: true },
    { id: "anprobieren", de: "anprobieren", en: "to try on", part: "verb", audio: true },
    { id: "zu-gross", de: "zu groß", en: "too big", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "mc-kleidung",
      type: "multiple-choice",
      title: "Die Kleidung",
      instruction: "Choose the right piece of clothing.",
      prompt: "Was trägst du im Winter um den Hals?",
      options: ["der Schal", "die Mütze", "der Mantel"],
      correctIndex: 0,
      explain: "Around the neck goes der Schal.",
    },
    {
      id: "listening-kleidung",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the word you heard.",
      prompt: "die Jacke",
      options: ["die Jacke", "die Hose", "die Mütze"],
      correctIndex: 0,
    },
    {
      id: "fill-kleidung",
      type: "fill-blank",
      title: "Im Geschäft",
      instruction: "Complete the sentences.",
      sentence: "Ich suche eine ___ in Größe 38. (pants) Die Jacke ist zu ___.",
      blanks: [
        { answers: ["Hose"], hint: "pants" },
        { answers: ["groß"], hint: "too big" },
      ],
    },
    {
      id: "matching-kleidung",
      type: "matching",
      title: "Kleidung",
      instruction: "Match each German word to its meaning.",
      pairs: [
        ["die Hose", "the pants"],
        ["das Kleid", "the dress"],
        ["der Mantel", "the coat"],
        ["die Schuhe", "the shoes"],
        ["die Mütze", "the cap"],
      ],
    },
    {
      id: "word-order-kleidung",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: I am looking for a jacket.",
      chunks: ["Ich", "suche", "eine", "Jacke."],
      explain: "suchen takes the accusative: eine Jacke.",
    },
    {
      id: "flashcard-kleidung",
      type: "flashcard",
      title: "Kleidungskarten",
      instruction: "Say the German out loud before revealing.",
      items: [
        { front: "die Hose", back: "the pants", frontAudio: true },
        { front: "die Jacke", back: "the jacket", frontAudio: true },
        { front: "der Mantel", back: "the coat", frontAudio: true },
        { front: "das Kleid", back: "the dress", frontAudio: true },
        { front: "die Schuhe", back: "the shoes", frontAudio: true },
        { front: "die Größe", back: "the size", frontAudio: true },
      ],
    },
  ],
};

const einkaufsdialoge: Lesson = {
  id: "einkaufsdialoge",
  title: "Einkaufsdialoge",
  summary: "Buying things: Wie viel kostet das?",
  status: "ready",
  sections: [
    {
      heading: "Im Geschäft",
      blocks: [
        {
          type: "table",
          caption: "Shopping phrases",
          head: ["German", "English"],
          rows: [
            ["Wie viel kostet das?", "How much does that cost?"],
            ["Was kostet das?", "What does that cost?"],
            ["Ich suche eine Hose.", "I am looking for pants."],
            ["Haben Sie das in Größe 38?", "Do you have this in size 38?"],
            ["Kann ich das anprobieren?", "Can I try this on?"],
            ["Die Umkleidekabine, bitte.", "The fitting room, please."],
            ["Das ist zu teuer.", "That is too expensive."],
            ["Ich nehme es.", "I will take it."],
          ],
        },
        {
          type: "tip",
          text: "nehmen is the shopping verb: Ich nehme es. means I will take it, the moment of decision.",
        },
      ],
    },
    {
      heading: "Der Dialog",
      blocks: [
        {
          type: "example",
          de: "Verkäuferin: Kann ich Ihnen helfen? Kunde: Ja, ich suche eine Jacke. Verkäuferin: Welche Größe? Kunde: Größe 40. Kann ich sie anprobieren?",
          en: "Salesperson: Can I help you? Customer: Yes, I am looking for a jacket. Salesperson: Which size? Customer: Size 40. Can I try it on?",
        },
        {
          type: "example",
          de: "Kunde: Wie viel kostet die Jacke? Verkäuferin: 45 Euro. Kunde: Gut, ich nehme sie.",
          en: "Customer: How much is the jacket? Salesperson: 45 euros. Customer: Fine, I will take it.",
        },
      ],
    },
  ],
  vocab: [
    { id: "der-kunde", de: "der Kunde", en: "the customer", part: "noun m.", plural: "die Kunden", audio: true },
    { id: "die-kundin", de: "die Kundin", en: "the customer (female)", part: "noun f.", plural: "die Kundinnen", audio: true },
    { id: "die-umkleidekabine", de: "die Umkleidekabine", en: "the fitting room", part: "noun f.", plural: "die Umkleidekabinen", audio: true },
    { id: "anprobieren", de: "anprobieren", en: "to try on", part: "verb", audio: true },
    { id: "ich-nehme-es", de: "Ich nehme es.", en: "I will take it.", part: "phrase", phrase: true, audio: true },
    { id: "wie-viel-kostet", de: "Wie viel kostet das?", en: "How much does that cost?", part: "phrase", phrase: true, audio: true },
    { id: "zu-teuer", de: "zu teuer", en: "too expensive", part: "phrase", phrase: true, audio: true },
    { id: "haben-sie-das", de: "Haben Sie das in Größe 38?", en: "Do you have this in size 38?", part: "phrase", phrase: true, audio: true },
    { id: "kann-ich", de: "Kann ich das anprobieren?", en: "Can I try this on?", part: "phrase", phrase: true, audio: true },
    { id: "der-verkaufer", de: "der Verkäufer", en: "the salesperson", part: "noun m.", plural: "die Verkäufer", audio: true },
  ],
  exercises: [
    {
      id: "mc-einkauf",
      type: "multiple-choice",
      title: "Der Dialog",
      instruction: "Choose the customer's line.",
      prompt: "The jacket costs 45 euros and you want it.",
      options: ["Gut, ich nehme sie.", "Das ist zu teuer, ich gehe.", "Ich nehme die Hose."],
      correctIndex: 0,
      explain: "I will take it: Ich nehme sie.",
    },
    {
      id: "listening-einkauf",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Kann ich das anprobieren?",
      options: ["Kann ich das anprobieren?", "Kann ich das bezahlen?", "Kann ich es umtauschen?"],
      correctIndex: 0,
    },
    {
      id: "fill-einkauf",
      type: "fill-blank",
      title: "Im Geschäft",
      instruction: "Complete the shopping sentences.",
      sentence: "Wie viel ___ das? (costs) Das ist zu ___.",
      blanks: [
        { answers: ["kostet"], hint: "kosten, er/es form" },
        { answers: ["teuer"], hint: "too expensive" },
      ],
    },
    {
      id: "matching-einkauf",
      type: "matching",
      title: "Sätze",
      instruction: "Match each German phrase to its meaning.",
      pairs: [
        ["Ich nehme es.", "I will take it."],
        ["Kann ich das anprobieren?", "Can I try this on?"],
        ["Das ist zu teuer.", "That is too expensive."],
        ["Haben Sie das in Größe 38?", "Do you have this in size 38?"],
        ["Wie viel kostet das?", "How much does that cost?"],
      ],
    },
    {
      id: "word-order-einkauf",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: I am looking for a jacket.",
      chunks: ["Ich", "suche", "eine", "Jacke."],
      explain: "The object follows the verb.",
    },
    {
      id: "flashcard-einkauf",
      type: "flashcard",
      title: "Einkaufskarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "Ich suche eine Hose.", back: "I am looking for pants.", frontAudio: true },
        { front: "Kann ich das anprobieren?", back: "Can I try this on?", frontAudio: true },
        { front: "Das ist zu teuer.", back: "That is too expensive.", frontAudio: true },
        { front: "Ich nehme es.", back: "I will take it.", frontAudio: true },
        { front: "Wie viel kostet das?", back: "How much does that cost?", frontAudio: true },
        { front: "Die Umkleidekabine, bitte.", back: "The fitting room, please.", frontAudio: true },
      ],
    },
  ],
};

const kontraktionen: Lesson = {
  id: "kontraktionen",
  title: "am, im, zum, zur",
  summary: "Article contractions: am, im, ins, zum, zur, beim, vom.",
  status: "ready",
  sections: [
    {
      heading: "Die Kontraktionen",
      blocks: [
        {
          type: "paragraph",
          text: "Preposition and article melt together in everyday German. Contractions are not optional: am and im are the normal way to speak.",
        },
        {
          type: "table",
          caption: "Common contractions",
          head: ["Full form", "Contracted", "Meaning"],
          rows: [
            ["an dem", "am", "on the (day), at the"],
            ["in dem", "im", "in the"],
            ["zu dem", "zum", "to the"],
            ["zu der", "zur", "to the (f.)"],
            ["bei dem", "beim", "at the"],
            ["von dem", "vom", "from the"],
            ["in das", "ins", "into the"],
            ["auf das", "aufs", "onto the"],
            ["an das", "ans", "to the"],
            ["durch das", "durchs", "through the"],
          ],
        },
        {
          type: "tip",
          text: "The dative pairs (am, im, zum, zur, beim, vom) are the everyday ones. The accusative pairs (ins, aufs, ans) appear with movement.",
        },
      ],
    },
    {
      heading: "Im Alltag",
      blocks: [
        {
          type: "example",
          de: "Ich gehe ins Kino. Am Montag gehe ich zur Schule.",
          en: "I am going to the cinema. On Monday I go to school.",
        },
        {
          type: "example",
          de: "Wir sind beim Arzt. Der Zug kommt vom Bahnhof.",
          en: "We are at the doctor's. The train comes from the station.",
        },
        {
          type: "example",
          de: "Leg das Buch aufs Regal!",
          en: "Put the book on the shelf!",
        },
      ],
    },
  ],
  vocab: [
    { id: "am", de: "am", en: "an + dem", part: "contraction", audio: true },
    { id: "im", de: "im", en: "in + dem", part: "contraction", audio: true },
    { id: "zum", de: "zum", en: "zu + dem", part: "contraction", audio: true },
    { id: "zur", de: "zur", en: "zu + der", part: "contraction", audio: true },
    { id: "beim", de: "beim", en: "bei + dem", part: "contraction", audio: true },
    { id: "vom", de: "vom", en: "von + dem", part: "contraction", audio: true },
    { id: "ins", de: "ins", en: "in + das", part: "contraction", audio: true },
    { id: "aufs", de: "aufs", en: "auf + das", part: "contraction", audio: true },
    { id: "ans", de: "ans", en: "an + das", part: "contraction", audio: true },
    { id: "ins-kino", de: "ins Kino", en: "to the cinema", part: "phrase", phrase: true, audio: true },
    { id: "zur-schule", de: "zur Schule", en: "to school", part: "phrase", phrase: true, audio: true },
    { id: "aufs-regal", de: "aufs Regal", en: "onto the shelf", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "mc-kontraktion",
      type: "multiple-choice",
      title: "Die Kontraktion",
      instruction: "Choose the correct contraction.",
      prompt: "zu + dem = ...",
      options: ["zum", "zur", "zu dem"],
      correctIndex: 0,
      explain: "zu + dem contracts to zum.",
    },
    {
      id: "listening-kontraktion",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the phrase you heard.",
      prompt: "ins Kino",
      options: ["ins Kino", "im Kino", "zum Kino"],
      correctIndex: 0,
    },
    {
      id: "fill-kontraktion",
      type: "fill-blank",
      title: "Kontraktionen",
      instruction: "Complete with the right contraction.",
      sentence: "Ich gehe ___ Kino. (in + das) Wir sind ___ Arzt. (bei + dem)",
      blanks: [
        { answers: ["ins"], hint: "in + das" },
        { answers: ["beim"], hint: "bei + dem" },
      ],
    },
    {
      id: "matching-kontraktion",
      type: "matching",
      title: "Zerlegen",
      instruction: "Match each contraction to its full form.",
      pairs: [
        ["am", "an dem"],
        ["im", "in dem"],
        ["zum", "zu dem"],
        ["zur", "zu der"],
        ["vom", "von dem"],
      ],
    },
    {
      id: "word-order-kontraktion",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: I am going to the cinema.",
      chunks: ["Ich", "gehe", "ins", "Kino."],
      explain: "The destination follows the verb.",
    },
    {
      id: "flashcard-kontraktion",
      type: "flashcard",
      title: "Kontraktionskarten",
      instruction: "Say the German out loud before revealing.",
      items: [
        { front: "am Montag", back: "on Monday", frontAudio: true },
        { front: "im Sommer", back: "in summer", frontAudio: true },
        { front: "ins Kino", back: "to the cinema", frontAudio: true },
        { front: "zum Bahnhof", back: "to the station", frontAudio: true },
        { front: "zur Schule", back: "to school", frontAudio: true },
        { front: "beim Arzt", back: "at the doctor's", frontAudio: true },
      ],
    },
  ],
};

const umtauschUndReklamation: Lesson = {
  id: "umtausch-und-reklamation",
  title: "Umtausch und Reklamation",
  summary: "Exchanging goods and complaining politely.",
  status: "ready",
  sections: [
    {
      heading: "Zurückgeben und umtauschen",
      blocks: [
        {
          type: "table",
          caption: "Returns and complaints",
          head: ["German", "English"],
          rows: [
            ["Ich möchte das zurückgeben.", "I would like to return this."],
            ["Kann ich das umtauschen?", "Can I exchange this?"],
            ["Es passt nicht.", "It does not fit."],
            ["Es ist kaputt.", "It is broken."],
            ["Ich möchte mein Geld zurück.", "I would like my money back."],
            ["Haben Sie den Kassenbon?", "Do you have the receipt?"],
            ["Die Rechnung, bitte.", "The receipt, please."],
          ],
        },
        {
          type: "tip",
          text: "The key pair: umtauschen (exchange) and zurückgeben (give back). Both are separable and take the accusative.",
        },
      ],
    },
    {
      heading: "Der Dialog",
      blocks: [
        {
          type: "example",
          de: "Kunde: Guten Tag, ich möchte diese Hose umtauschen. Sie passt nicht. Verkäuferin: Haben Sie den Kassenbon? Kunde: Ja, hier bitte.",
          en: "Customer: Hello, I would like to exchange these pants. They do not fit. Salesperson: Do you have the receipt? Customer: Yes, here you go.",
        },
        {
          type: "example",
          de: "Kunde: Die Jacke ist kaputt. Ich möchte mein Geld zurück. Verkäuferin: Das tut mir leid. Moment bitte.",
          en: "Customer: The jacket is broken. I would like my money back. Salesperson: I am sorry. One moment please.",
        },
      ],
    },
  ],
  vocab: [
    { id: "umtauschen", de: "umtauschen", en: "to exchange", part: "verb", audio: true },
    { id: "zurueckgeben", de: "zurückgeben", en: "to give back, return", part: "verb", audio: true },
    { id: "der-kassenbon", de: "der Kassenbon", en: "the receipt", part: "noun m.", plural: "die Kassenbons", audio: true },
    { id: "die-rechnung", de: "die Rechnung", en: "the invoice", part: "noun f.", plural: "die Rechnungen", audio: true },
    { id: "kaputt", de: "kaputt", en: "broken", part: "adjective", audio: true },
    { id: "es-passt-nicht", de: "Es passt nicht.", en: "It does not fit.", part: "phrase", phrase: true, audio: true },
    { id: "geld-zurueck", de: "Ich möchte mein Geld zurück.", en: "I would like my money back.", part: "phrase", phrase: true, audio: true },
    { id: "das-tut-mir-leid", de: "Das tut mir leid.", en: "I am sorry.", part: "phrase", phrase: true, audio: true },
    { id: "die-quittung", de: "die Quittung", en: "the receipt (proof of payment)", part: "noun f.", plural: "die Quittungen", audio: true },
    { id: "kaputt-gehen", de: "kaputt gehen", en: "to break", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "mc-reklamation",
      type: "multiple-choice",
      title: "Die Reklamation",
      instruction: "Choose the right sentence.",
      prompt: "The pants are too big and you want a different size.",
      options: [
        "Kann ich das umtauschen?",
        "Ich möchte mein Geld zurück.",
        "Das ist kaputt.",
      ],
      correctIndex: 0,
      explain: "Exchange for another size: umtauschen.",
    },
    {
      id: "listening-reklamation",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Es passt nicht.",
      options: ["Es passt nicht.", "Es ist kaputt.", "Es ist zu teuer."],
      correctIndex: 0,
    },
    {
      id: "fill-reklamation",
      type: "fill-blank",
      title: "Im Geschäft",
      instruction: "Complete the sentences.",
      sentence: "Haben Sie den ___? (receipt) Es ist ___.",
      blanks: [
        { answers: ["Kassenbon"], hint: "receipt" },
        { answers: ["kaputt"], hint: "broken" },
      ],
    },
    {
      id: "matching-reklamation",
      type: "matching",
      title: "Sätze",
      instruction: "Match each German phrase to its meaning.",
      pairs: [
        ["Ich möchte das zurückgeben.", "I would like to return this."],
        ["Es passt nicht.", "It does not fit."],
        ["Es ist kaputt.", "It is broken."],
        ["Haben Sie den Kassenbon?", "Do you have the receipt?"],
        ["Das tut mir leid.", "I am sorry."],
      ],
    },
    {
      id: "word-order-reklamation",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: I would like to return this jacket.",
      chunks: ["Ich", "möchte", "diese", "Jacke", "zurückgeben."],
      explain: "The separable prefix closes the sentence.",
    },
    {
      id: "flashcard-reklamation",
      type: "flashcard",
      title: "Reklamationskarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "Ich möchte das zurückgeben.", back: "I would like to return this.", frontAudio: true },
        { front: "Es passt nicht.", back: "It does not fit.", frontAudio: true },
        { front: "Es ist kaputt.", back: "It is broken.", frontAudio: true },
        { front: "Haben Sie den Kassenbon?", back: "Do you have the receipt?", frontAudio: true },
        { front: "Das tut mir leid.", back: "I am sorry.", frontAudio: true },
        { front: "umtauschen", back: "to exchange", frontAudio: true },
      ],
    },
  ],
};

export const einkaufen: Unit = {
  id: "einkaufen",
  title: "Einkaufen",
  theme: "Shopping",
  lessons: [
    kleidung,
    einkaufsdialoge,
    kontraktionen,
    umtauschUndReklamation,
  ],
};