import type { Lesson, Unit } from "../../schema";

export const lebensmittel: Lesson = {
  id: "lebensmittel",
  title: "Lebensmittel",
  summary:
    "The complete food vocabulary for A1: food, drinks, fruit and vegetables, meals, and the grammar that comes with shopping for food.",
  status: "ready",
  sections: [
    {
      heading: "Das Essen: die Grundnahrungsmittel",
      blocks: [
        {
          type: "paragraph",
          text: "Food words teach the most important German habit: learn the article with the noun. das Brot, die Butter, der Käse. Most food nouns have a gender you can feel from the ending: -e words like die Butter, die Wurst, die Milch are feminine; das Brot, das Ei, das Fleisch are neuter; der Käse, der Reis, der Schinken are masculine.",
        },
        {
          type: "table",
          caption: "Food",
          head: ["German", "English", "Plural"],
          rows: [
            ["das Brot", "the bread", "die Brote"],
            ["die Butter", "the butter", "-"],
            ["der Käse", "the cheese", "die Käsesorten"],
            ["die Wurst", "the sausage", "die Würste"],
            ["das Ei", "the egg", "die Eier"],
            ["der Schinken", "the ham", "die Schinken"],
            ["das Müsli", "the muesli", "die Müslis"],
            ["der Joghurt", "the yogurt", "die Joghurts"],
            ["der Reis", "the rice", "-"],
            ["die Nudeln", "the pasta", "only plural"],
            ["das Fleisch", "the meat", "-"],
            ["das Hähnchen", "the chicken", "die Hähnchen"],
            ["der Fisch", "the fish", "die Fische"],
          ],
        },
        {
          type: "tip",
          text: "Uncountable foods have no plural: das Brot? No: die Butter, der Käse, der Reis, das Fleisch take no plural in everyday use. You buy Butter, not 'Buttern'.",
        },
      ],
    },
    {
      heading: "Die Getränke",
      blocks: [
        {
          type: "table",
          caption: "Drinks",
          head: ["German", "English"],
          rows: [
            ["das Wasser", "the water"],
            ["das Mineralwasser", "the sparkling water"],
            ["der Kaffee", "the coffee"],
            ["der Tee", "the tea"],
            ["der Saft", "the juice"],
            ["die Milch", "the milk"],
            ["das Bier", "the beer"],
            ["der Wein", "the wine"],
            ["die Cola", "the cola"],
          ],
        },
        {
          type: "paragraph",
          text: "Water has two versions in Germany: stilles Wasser (still water) and Mineralwasser or Sprudel (sparkling water). Ordering coffee: einen Kaffee with the accusative masculine. The drink words are mostly masculine or neuter, with die Milch and die Cola as the feminine exceptions.",
        },
        {
          type: "tip",
          text: "Ordering a coffee uses the accusative: Ich möchte einen Kaffee. The masculine takes -en. Remember the pair: einen Kaffee, einen Tee, einen Saft, ein Bier, ein Wasser.",
        },
      ],
    },
    {
      heading: "Das Obst und das Gemüse",
      blocks: [
        {
          type: "table",
          caption: "Fruit and vegetables",
          head: ["German", "English", "Plural"],
          rows: [
            ["der Apfel", "the apple", "die Äpfel"],
            ["die Banane", "the banana", "die Bananen"],
            ["die Orange", "the orange", "die Orangen"],
            ["die Erdbeere", "the strawberry", "die Erdbeeren"],
            ["die Zitrone", "the lemon", "die Zitronen"],
            ["die Traube", "the grape", "die Trauben"],
            ["die Tomate", "the tomato", "die Tomaten"],
            ["die Kartoffel", "the potato", "die Kartoffeln"],
            ["die Gurke", "the cucumber", "die Gurken"],
            ["die Karotte / die Möhre", "the carrot", "die Karotten"],
            ["der Salat", "the lettuce, the salad", "die Salate"],
            ["die Zwiebel", "the onion", "die Zwiebeln"],
          ],
        },
        {
          type: "paragraph",
          text: "The plural patterns are visible in the fruit and vegetable table: most are feminine and take -n or -en (die Banane, die Bananen), the apples take an umlaut (der Apfel, die Äpfel), and the salad is masculine (der Salat).",
        },
        {
          type: "tip",
          text: "Buying food uses the partitive with no article: ein Pfund Äpfel, ein Kilo Kartoffeln, eine Flasche Wasser. The unit word carries the article, the food follows in the plural.",
        },
      ],
    },
    {
      heading: "Die Mahlzeiten",
      blocks: [
        {
          type: "paragraph",
          text: "The three meals: das Frühstück (breakfast), das Mittagessen (lunch), das Abendessen (dinner). The verb pairs: frühstücken (to have breakfast), zu Mittag essen, zu Abend essen. The question: Was gibt es zum Frühstück? (What is there for breakfast?)",
        },
        {
          type: "table",
          caption: "Meals",
          head: ["German", "English", "Verb"],
          rows: [
            ["das Frühstück", "breakfast", "frühstücken"],
            ["das Mittagessen", "lunch", "zu Mittag essen"],
            ["das Abendessen", "dinner", "zu Abend essen"],
            ["der Hunger", "the hunger", "Hunger haben"],
            ["der Durst", "the thirst", "Durst haben"],
          ],
        },
        {
          type: "example",
          de: "Zum Frühstück esse ich Brot mit Käse und trinke einen Kaffee. Zum Mittagessen gibt es Nudeln mit Tomatensoße.",
          en: "Meals in two sentences.",
        },
        {
          type: "tip",
          text: "The meal pattern: zum Frühstück/Mittagessen/Abendessen + there is (es gibt). And remember: Ich habe Hunger und Durst, not 'ich bin hungrig und durstig' in everyday speech.",
        },
      ],
    },
    {
      heading: "Einkaufen: Mengen und Verpackungen",
      blocks: [
        {
          type: "paragraph",
          text: "Shopping for food uses units and packages: ein Pfund (500 g), ein Kilo, eine Flasche (bottle), eine Tasse (cup), ein Glas (glass), ein Stück (piece), ein Becher (pot/cup), eine Packung (packet). The unit word carries the article: eine Flasche Wasser, ein Kilo Äpfel.",
        },
        {
          type: "table",
          caption: "Units and packages",
          head: ["German", "English", "Example"],
          rows: [
            ["ein Pfund", "500 grams", "ein Pfund Äpfel"],
            ["ein Kilo", "one kilo", "ein Kilo Kartoffeln"],
            ["eine Flasche", "a bottle", "eine Flasche Wasser"],
            ["ein Glas", "a glass", "ein Glas Milch"],
            ["eine Tasse", "a cup", "eine Tasse Kaffee"],
            ["ein Stück", "a piece", "ein Stück Kuchen"],
            ["eine Packung", "a packet", "eine Packung Butter"],
            ["ein Becher", "a pot (yogurt)", "ein Becher Joghurt"],
          ],
        },
        {
          type: "tip",
          text: "The pattern: unit + food. Eine Flasche Wasser, ein Kilo Äpfel. The food follows without an article and in the plural where it exists.",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: the wrong article on das Brot or die Milch, using an article where German has none, and confusing the meals.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["wrong gender", "die Brot", "das Brot", "Brot is neuter"],
            ["article with milk", "Ich trinke die Milch.", "Ich trinke Milch.", "general statements take no article"],
            ["meal mix", "Zum Abendessen esse ich Müsli. (morning)", "Zum Frühstück esse ich Müsli.", "Müsli is breakfast food"],
            ["Hunger/Durst", "Ich bin Hunger.", "Ich habe Hunger.", "Hunger takes haben"],
            ["plural on Butter", "Ich kaufe Buttern.", "Ich kaufe Butter.", "Butter has no plural"],
          ],
        },
        {
          type: "tip",
          text: "Every word in the vocabulary table below has audio. Learn each noun as a three-piece: article + noun + plural. das Brot, die Brote.",
        },
      ],
    },
  ],
  vocab: [
    { id: "das-brot", de: "das Brot", en: "the bread", part: "noun n.", plural: "die Brote", audio: true },
    { id: "die-butter", de: "die Butter", en: "the butter", part: "noun f.", audio: true },
    { id: "der-kaese", de: "der Käse", en: "the cheese", part: "noun m.", audio: true },
    { id: "die-wurst", de: "die Wurst", en: "the sausage", part: "noun f.", plural: "die Würste", audio: true },
    { id: "das-ei", de: "das Ei", en: "the egg", part: "noun n.", plural: "die Eier", audio: true },
    { id: "der-schinken", de: "der Schinken", en: "the ham", part: "noun m.", audio: true },
    { id: "das-muesli", de: "das Müsli", en: "the muesli", part: "noun n.", plural: "die Müslis", audio: true },
    { id: "der-reis", de: "der Reis", en: "the rice", part: "noun m.", audio: true },
    { id: "die-nudeln", de: "die Nudeln", en: "the pasta", part: "noun pl.", audio: true },
    { id: "das-fleisch", de: "das Fleisch", en: "the meat", part: "noun n.", audio: true },
    { id: "das-haehnchen", de: "das Hähnchen", en: "the chicken", part: "noun n.", plural: "die Hähnchen", audio: true },
    { id: "der-fisch", de: "der Fisch", en: "the fish", part: "noun m.", plural: "die Fische", audio: true },
    { id: "das-wasser", de: "das Wasser", en: "the water", part: "noun n.", audio: true },
    { id: "das-mineralwasser", de: "das Mineralwasser", en: "the sparkling water", part: "noun n.", audio: true },
    { id: "der-kaffee", de: "der Kaffee", en: "the coffee", part: "noun m.", plural: "die Kaffees", audio: true },
    { id: "der-tee", de: "der Tee", en: "the tea", part: "noun m.", plural: "die Tees", audio: true },
    { id: "der-saft", de: "der Saft", en: "the juice", part: "noun m.", plural: "die Säfte", audio: true },
    { id: "die-milch", de: "die Milch", en: "the milk", part: "noun f.", audio: true },
    { id: "das-bier", de: "das Bier", en: "the beer", part: "noun n.", plural: "die Biere", audio: true },
    { id: "der-wein", de: "der Wein", en: "the wine", part: "noun m.", plural: "die Weine", audio: true },
    { id: "die-cola", de: "die Cola", en: "the cola", part: "noun f.", audio: true },
    { id: "der-apfel", de: "der Apfel", en: "the apple", part: "noun m.", plural: "die Äpfel", audio: true },
    { id: "die-banane", de: "die Banane", en: "the banana", part: "noun f.", plural: "die Bananen", audio: true },
    { id: "die-orange", de: "die Orange", en: "the orange", part: "noun f.", plural: "die Orangen", audio: true },
    { id: "die-erdbeere", de: "die Erdbeere", en: "the strawberry", part: "noun f.", plural: "die Erdbeeren", audio: true },
    { id: "die-tomate", de: "die Tomate", en: "the tomato", part: "noun f.", plural: "die Tomaten", audio: true },
    { id: "die-kartoffel", de: "die Kartoffel", en: "the potato", part: "noun f.", plural: "die Kartoffeln", audio: true },
    { id: "die-gurke", de: "die Gurke", en: "the cucumber", part: "noun f.", plural: "die Gurken", audio: true },
    { id: "die-karotte", de: "die Karotte", en: "the carrot", part: "noun f.", plural: "die Karotten", audio: true },
    { id: "der-salat", de: "der Salat", en: "the salad, the lettuce", part: "noun m.", plural: "die Salate", audio: true },
    { id: "die-zwiebel", de: "die Zwiebel", en: "the onion", part: "noun f.", plural: "die Zwiebeln", audio: true },
    { id: "das-fruehstueck", de: "das Frühstück", en: "the breakfast", part: "noun n.", plural: "die Frühstücke", audio: true },
    { id: "das-mittagessen", de: "das Mittagessen", en: "the lunch", part: "noun n.", audio: true },
    { id: "das-abendessen", de: "das Abendessen", en: "the dinner", part: "noun n.", audio: true },
    { id: "fruehstuecken", de: "frühstücken", en: "to have breakfast", part: "verb", audio: true },
    { id: "ein-pfund", de: "ein Pfund", en: "500 grams", part: "phrase", phrase: true, audio: true },
    { id: "ein-kilo", de: "ein Kilo", en: "one kilo", part: "phrase", phrase: true, audio: true },
    { id: "eine-flasche", de: "eine Flasche Wasser", en: "a bottle of water", part: "phrase", phrase: true, audio: true },
    { id: "eine-tasse", de: "eine Tasse Kaffee", en: "a cup of coffee", part: "phrase", phrase: true, audio: true },
    { id: "ich-habe-hunger", de: "Ich habe Hunger.", en: "I am hungry.", part: "phrase", phrase: true, audio: true },
    { id: "ich-habe-durst", de: "Ich habe Durst.", en: "I am thirsty.", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-essen",
      type: "matching",
      title: "Übung 1: Das Essen",
      instruction: "Match each food word to its meaning.",
      pairs: [
        ["das Brot", "the bread"],
        ["die Butter", "the butter"],
        ["der Käse", "the cheese"],
        ["das Ei", "the egg"],
        ["das Fleisch", "the meat"],
        ["der Fisch", "the fish"],
      ],
    },
    {
      id: "ex-getraenke",
      type: "matching",
      title: "Übung 2: Die Getränke",
      instruction: "Match each drink to its meaning.",
      pairs: [
        ["das Wasser", "the water"],
        ["der Kaffee", "the coffee"],
        ["der Tee", "the tea"],
        ["der Saft", "the juice"],
        ["die Milch", "the milk"],
        ["das Bier", "the beer"],
      ],
    },
    {
      id: "ex-genus",
      type: "multiple-choice",
      title: "Übung 3: Das Genus",
      instruction: "Choose the correct article.",
      prompt: "___ Brot ist frisch.",
      options: ["Das", "Die", "Der"],
      correctIndex: 0,
      explain: "Brot is neuter: das Brot.",
    },
    {
      id: "ex-genus-2",
      type: "multiple-choice",
      title: "Übung 4: Das Genus",
      instruction: "Choose the correct article.",
      prompt: "___ Milch ist kalt.",
      options: ["Die", "Der", "Das"],
      correctIndex: 0,
      explain: "Milch is feminine: die Milch.",
    },
    {
      id: "ex-plural",
      type: "fill-blank",
      title: "Übung 5: Der Plural",
      instruction: "Type the plurals.",
      sentence: "der Apfel -> die ___, die Banane -> die ___, die Kartoffel -> die ___, das Ei -> die ___.",
      blanks: [
        { answers: ["Äpfel"], hint: "umlaut" },
        { answers: ["Bananen"], hint: "+ -en" },
        { answers: ["Kartoffeln"], hint: "+ -n" },
        { answers: ["Eier"], hint: "+ -er" },
      ],
    },
    {
      id: "ex-akkusativ",
      type: "multiple-choice",
      title: "Übung 6: Der Akkusativ",
      instruction: "Choose the correct form.",
      prompt: "Ich möchte ___ Kaffee.",
      options: ["einen", "ein", "eine"],
      correctIndex: 0,
      explain: "Kaffee is masculine: einen Kaffee.",
    },
    {
      id: "ex-mahlzeiten",
      type: "multiple-choice",
      title: "Übung 7: Die Mahlzeiten",
      instruction: "Choose the correct meal.",
      prompt: "Müsli is typical for ...",
      options: ["das Frühstück", "das Mittagessen", "das Abendessen"],
      correctIndex: 0,
      explain: "Müsli is breakfast food.",
    },
    {
      id: "ex-mengen",
      type: "multiple-choice",
      title: "Übung 8: Die Mengen",
      instruction: "Choose the correct unit.",
      prompt: "Ich kaufe eine ___ Wasser.",
      options: ["Flasche", "Pfund", "Stück"],
      correctIndex: 0,
      explain: "Water comes in a bottle: die Flasche.",
    },
    {
      id: "ex-hunger",
      type: "multiple-choice",
      title: "Übung 9: Hunger und Durst",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Ich habe Hunger.", "Ich bin Hunger.", "Ich habe hungrig."],
      correctIndex: 0,
      explain: "Hunger takes haben.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 10: Hören",
      instruction: "Play the audio and pick the word you heard.",
      prompt: "der Käse",
      options: ["der Käse", "der Reis", "die Wurst"],
      correctIndex: 0,
      explain: "The food heard: cheese.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 11: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Zum Frühstück esse ich Brot mit Käse.",
      options: ["Zum Frühstück esse ich Brot mit Käse.", "Zum Mittagessen esse ich Brot mit Käse.", "Zum Frühstück trinke ich Kaffee."],
      correctIndex: 0,
      explain: "The breakfast sentence heard.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 12: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Ich trinke Milch.", "Ich trinke die Milch.", "Ich trinke ein Milch."],
      correctIndex: 0,
      explain: "General statements take no article.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 13: Der Satz",
      instruction: "Build the sentence: I am drinking a coffee.",
      chunks: ["Ich", "trinke", "einen", "Kaffee."],
      explain: "The accusative object follows the verb.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 14: Der Satz",
      instruction: "Build the sentence: I buy a kilo of apples.",
      chunks: ["Ich", "kaufe", "ein", "Kilo", "Äpfel."],
      explain: "Unit + food: ein Kilo Äpfel.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 15: Essenskarten",
      instruction: "Say the German with the article out loud.",
      items: [
        { front: "das Brot", back: "the bread", frontAudio: true },
        { front: "die Butter", back: "the butter", frontAudio: true },
        { front: "der Käse", back: "the cheese", frontAudio: true },
        { front: "das Ei", back: "the egg", frontAudio: true },
        { front: "das Wasser", back: "the water", frontAudio: true },
        { front: "der Kaffee", back: "the coffee", frontAudio: true },
        { front: "die Milch", back: "the milk", frontAudio: true },
        { front: "der Apfel", back: "the apple", frontAudio: true },
        { front: "die Kartoffel", back: "the potato", frontAudio: true },
        { front: "das Frühstück", back: "the breakfast", frontAudio: true },
        { front: "einen Kaffee", back: "a coffee (accusative)", frontAudio: true },
        { front: "Ich habe Hunger.", back: "I am hungry.", frontAudio: true },
      ],
    },
  ],
};

export const imRestaurant: Lesson = {
  id: "im-restaurant",
  title: "Im Restaurant",
  summary:
    "The complete restaurant system for A1: ordering with möchten, the menu, the bill, paying, and the full waiter dialogue.",
  status: "ready",
  sections: [
    {
      heading: "Ankommen und bestellen",
      blocks: [
        {
          type: "paragraph",
          text: "The restaurant visit runs on a fixed script: you ask for a table, get the menu, order with möchten, eat, and ask for the bill. The golden word is möchten (would like to): it is polite in every situation and the verb of the whole restaurant visit. Ich möchte einen Kaffee, bitte.",
        },
        {
          type: "table",
          caption: "The restaurant script",
          head: ["Step", "German", "English"],
          rows: [
            ["ask for a table", "Haben Sie einen Tisch für zwei?", "Do you have a table for two?"],
            ["the menu", "Die Speisekarte, bitte.", "The menu, please."],
            ["order", "Ich möchte einen Kaffee, bitte.", "I would like a coffee, please."],
            ["take", "Ich nehme die Suppe.", "I will take the soup."],
            ["recommend", "Was empfehlen Sie?", "What do you recommend?"],
            ["the bill", "Die Rechnung, bitte.", "The bill, please."],
            ["pay", "Zahlen, bitte!", "The bill, please!"],
            ["keep the change", "Stimmt so.", "Keep the change."],
          ],
        },
        {
          type: "tip",
          text: "The two ordering verbs: möchten is the polite wish (Ich möchte einen Tee), nehmen is the decision (Ich nehme die Suppe). Both take the accusative.",
        },
      ],
    },
    {
      heading: "Bestellen mit dem Akkusativ",
      blocks: [
        {
          type: "paragraph",
          text: "Ordering uses the accusative: masculine drinks and dishes take einen, feminine take eine, neuter take ein. Ich möchte einen Kaffee, eine Suppe, ein Bier. The same pattern works for Ich nehme: Ich nehme einen Salat, die Suppe, das Hähnchen.",
        },
        {
          type: "table",
          caption: "Ordering with the accusative",
          head: ["Dish", "Gender", "Ich möchte ..."],
          rows: [
            ["der Kaffee", "masculine", "einen Kaffee"],
            ["der Salat", "masculine", "einen Salat"],
            ["die Suppe", "feminine", "eine Suppe"],
            ["die Pizza", "feminine", "eine Pizza"],
            ["das Bier", "neuter", "ein Bier"],
            ["das Hähnchen", "neuter", "ein Hähnchen"],
          ],
        },
        {
          type: "example",
          de: "Ich möchte einen Kaffee, eine Suppe und ein Bier, bitte.",
          en: "All three genders in one order.",
        },
        {
          type: "tip",
          text: "The order line is the accusative test: Ich möchte einen (m.), eine (f.), ein (n.). Practise ordering your own meal aloud before the exam.",
        },
      ],
    },
    {
      heading: "Der Dialog: Kellner und Gast",
      blocks: [
        {
          type: "paragraph",
          text: "Here is the complete waiter-guest dialogue, the exam's favourite speaking task. Learn both roles.",
        },
        {
          type: "example",
          de: "Kellner: Guten Tag! Was möchten Sie trinken? Gast: Einen Tee, bitte. Und die Speisekarte. Kellner: Hier bitte. Was möchten Sie essen? Gast: Ich nehme das Hähnchen mit Reis. Kellner: Sehr gut. Sonst noch etwas? Gast: Nein, danke. Kellner: Guten Appetit!",
          en: "The complete ordering dialogue.",
        },
        {
          type: "example",
          de: "Gast: Die Rechnung, bitte! Kellner: Das macht zwölf Euro. Gast: Stimmt so. Danke schön!",
          en: "Paying the bill.",
        },
        {
          type: "tip",
          text: "The waiter says Guten Appetit! when the food arrives; the guest answers Danke, gleichfalls! or Danke, ebenfalls!. The bill phrase: Die Rechnung, bitte!",
        },
      ],
    },
    {
      heading: "Bezahlen",
      blocks: [
        {
          type: "paragraph",
          text: "Paying has its own vocabulary: bar bezahlen (to pay cash), mit Karte zahlen (to pay by card), die Kreditkarte (credit card), das Bargeld (cash), das Wechselgeld (the change), die Trinkgeld (the tip). The waiter asks: Zahlen Sie bar oder mit Karte? The tip phrase: Stimmt so (keep the change) or Das stimmt so.",
        },
        {
          type: "table",
          caption: "Paying vocabulary",
          head: ["German", "English"],
          rows: [
            ["bar bezahlen", "to pay cash"],
            ["mit Karte zahlen", "to pay by card"],
            ["die Kreditkarte", "the credit card"],
            ["das Bargeld", "the cash"],
            ["das Wechselgeld", "the change"],
            ["das Trinkgeld", "the tip"],
            ["getrennt oder zusammen?", "separately or together?"],
            ["Stimmt so.", "Keep the change."],
          ],
        },
        {
          type: "example",
          de: "Zahlen bitte! Getrennt oder zusammen? Zusammen, bitte. Das macht zwölf Euro fünfzig. Stimmt so.",
          en: "The paying dialogue.",
        },
        {
          type: "tip",
          text: "getrennt oder zusammen is the classic waiter question: separately or together? The answer: Getrennt, bitte or Zusammen, bitte.",
        },
      ],
    },
    {
      heading: "Das Essen bewerten",
      blocks: [
        {
          type: "paragraph",
          text: "Talking about the food uses schmecken (to taste) with the dative: Das schmeckt mir gut (I like the taste). The phrases: Es schmeckt sehr gut, Es schmeckt nicht so gut, Das ist zu salzig (too salty), Das ist sehr lecker (very tasty).",
        },
        {
          type: "table",
          caption: "Talking about food",
          head: ["German", "English"],
          rows: [
            ["Das schmeckt mir gut.", "I like the taste."],
            ["Es schmeckt sehr gut.", "It tastes very good."],
            ["Das ist lecker.", "That is tasty."],
            ["Das ist zu salzig.", "That is too salty."],
            ["Das ist zu scharf.", "That is too spicy."],
            ["Es schmeckt nicht so gut.", "It does not taste so good."],
          ],
        },
        {
          type: "tip",
          text: "schmecken takes the dative: Das schmeckt MIR gut. The person who tastes is in the dative, exactly like gefallen.",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: using ich bin instead of ich möchte for ordering, forgetting the accusative article, and asking for the bill with the wrong phrase.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["bin instead of möchte", "Ich bin einen Kaffee.", "Ich möchte einen Kaffee.", "ordering uses möchten"],
            ["missing accusative", "Ich möchte ein Kaffee.", "Ich möchte einen Kaffee.", "Kaffee is masculine"],
            ["bill phrase", "Das Essen, bitte!", "Die Rechnung, bitte!", "the bill is die Rechnung"],
            ["schmecken case", "Das schmeckt mich gut.", "Das schmeckt mir gut.", "schmecken takes the dative"],
            ["take phrase", "Ich will die Suppe.", "Ich nehme die Suppe.", "the natural choice verb is nehmen"],
          ],
        },
        {
          type: "tip",
          text: "The restaurant is a script: möchten for ordering, nehmen for choosing, die Rechnung for the bill, Stimmt so for the tip. Learn the script and the whole topic is solved.",
        },
      ],
    },
  ],
  vocab: [
    { id: "das-restaurant", de: "das Restaurant", en: "the restaurant", part: "noun n.", plural: "die Restaurants", audio: true },
    { id: "die-speisekarte", de: "die Speisekarte", en: "the menu", part: "noun f.", plural: "die Speisekarten", audio: true },
    { id: "die-rechnung", de: "die Rechnung", en: "the bill", part: "noun f.", plural: "die Rechnungen", audio: true },
    { id: "der-kellner", de: "der Kellner", en: "the waiter", part: "noun m.", plural: "die Kellner", audio: true },
    { id: "die-kellnerin", de: "die Kellnerin", en: "the waitress", part: "noun f.", plural: "die Kellnerinnen", audio: true },
    { id: "bestellen", de: "bestellen", en: "to order", part: "verb", audio: true },
    { id: "zahlen", de: "zahlen", en: "to pay", part: "verb", audio: true },
    { id: "empfehlen", de: "empfehlen", en: "to recommend", part: "verb", audio: true },
    { id: "schmecken", de: "schmecken", en: "to taste", part: "verb", audio: true },
    { id: "der-tisch", de: "der Tisch", en: "the table", part: "noun m.", plural: "die Tische", audio: true },
    { id: "die-suppe", de: "die Suppe", en: "the soup", part: "noun f.", plural: "die Suppen", audio: true },
    { id: "das-broetchen", de: "das Brötchen", en: "the roll", part: "noun n.", plural: "die Brötchen", audio: true },
    { id: "die-pizza", de: "die Pizza", en: "the pizza", part: "noun f.", plural: "die Pizzen", audio: true },
    { id: "ich-moechte", de: "Ich möchte ...", en: "I would like ...", part: "phrase", phrase: true, audio: true },
    { id: "ich-nehme", de: "Ich nehme ...", en: "I will take ...", part: "phrase", phrase: true, audio: true },
    { id: "einen-kaffee", de: "einen Kaffee", en: "a coffee", part: "phrase", phrase: true, audio: true },
    { id: "was-moechten-sie", de: "Was möchten Sie?", en: "What would you like?", part: "phrase", phrase: true, audio: true },
    { id: "die-rechnung-bitte", de: "Die Rechnung, bitte!", en: "The bill, please!", part: "phrase", phrase: true, audio: true },
    { id: "stimmt-so", de: "Stimmt so.", en: "Keep the change.", part: "phrase", phrase: true, audio: true },
    { id: "guten-appetit", de: "Guten Appetit!", en: "Enjoy your meal!", part: "phrase", phrase: true, audio: true },
    { id: "bar-oder-karte", de: "Bar oder mit Karte?", en: "Cash or card?", part: "phrase", phrase: true, audio: true },
    { id: "getrennt-oder-zusammen", de: "Getrennt oder zusammen?", en: "Separately or together?", part: "phrase", phrase: true, audio: true },
    { id: "das-trinkgeld", de: "das Trinkgeld", en: "the tip", part: "noun n.", audio: true },
    { id: "das-wechselgeld", de: "das Wechselgeld", en: "the change", part: "noun n.", audio: true },
    { id: "lecker", de: "lecker", en: "tasty", part: "adjective", audio: true },
    { id: "salzig", de: "salzig", en: "salty", part: "adjective", audio: true },
    { id: "scharf", de: "scharf", en: "spicy, hot", part: "adjective", audio: true },
  ],
  exercises: [
    {
      id: "ex-begruessung",
      type: "multiple-choice",
      title: "Übung 1: Ankommen",
      instruction: "Choose the question for a table.",
      prompt: "You want a table for two.",
      options: ["Haben Sie einen Tisch für zwei?", "Haben Sie die Rechnung?", "Was kostet das?"],
      correctIndex: 0,
      explain: "The table question: einen Tisch für zwei.",
    },
    {
      id: "ex-ordern",
      type: "multiple-choice",
      title: "Übung 2: Bestellen",
      instruction: "Choose the polite order.",
      prompt: "You want a coffee.",
      options: ["Ich möchte einen Kaffee, bitte.", "Ich bin einen Kaffee.", "Kaffee, schnell!"],
      correctIndex: 0,
      explain: "möchten + accusative is the polite order.",
    },
    {
      id: "ex-akkusativ",
      type: "fill-blank",
      title: "Übung 3: Der Akkusativ",
      instruction: "Complete with the right article.",
      sentence: "Ich möchte ___ Kaffee. (a, m.) Ich möchte ___ Suppe. (a, f.) Ich möchte ___ Bier. (a, n.)",
      blanks: [
        { answers: ["einen"], hint: "masculine" },
        { answers: ["eine"], hint: "feminine" },
        { answers: ["ein"], hint: "neuter" },
      ],
    },
    {
      id: "ex-nehmen",
      type: "multiple-choice",
      title: "Übung 4: nehmen",
      instruction: "Choose the correct verb.",
      prompt: "Ich ___ die Suppe.",
      options: ["nehme", "bin", "möchte"],
      correctIndex: 0,
      explain: "The decision verb is nehmen.",
    },
    {
      id: "ex-rechnung",
      type: "multiple-choice",
      title: "Übung 5: Die Rechnung",
      instruction: "Choose the bill phrase.",
      prompt: "You want to pay.",
      options: ["Die Rechnung, bitte!", "Das Essen, bitte!", "Der Tisch, bitte!"],
      correctIndex: 0,
      explain: "The bill is die Rechnung.",
    },
    {
      id: "ex-zahlen",
      type: "multiple-choice",
      title: "Übung 6: Bezahlen",
      instruction: "Choose the correct phrase.",
      prompt: "You pay cash.",
      options: ["Ich bezahle bar.", "Ich bezahle Karte.", "Ich bin bar."],
      correctIndex: 0,
      explain: "Cash payment: bar bezahlen.",
    },
    {
      id: "ex-tipp",
      type: "multiple-choice",
      title: "Übung 7: Das Trinkgeld",
      instruction: "Choose the tip phrase.",
      prompt: "The waiter keeps the change.",
      options: ["Stimmt so.", "Das ist zu teuer.", "Zahlen, bitte!"],
      correctIndex: 0,
      explain: "Stimmt so means keep the change.",
    },
    {
      id: "ex-schmecken",
      type: "multiple-choice",
      title: "Übung 8: schmecken",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Das schmeckt mir gut.", "Das schmeckt mich gut.", "Das schmeckt ich gut."],
      correctIndex: 0,
      explain: "schmecken takes the dative: mir.",
    },
    {
      id: "ex-dialog",
      type: "matching",
      title: "Übung 9: Der Dialog",
      instruction: "Match each waiter line to its meaning.",
      pairs: [
        ["Was möchten Sie trinken?", "What would you like to drink?"],
        ["Was möchten Sie essen?", "What would you like to eat?"],
        ["Zahlen Sie bar oder mit Karte?", "Cash or card?"],
        ["Getrennt oder zusammen?", "Separately or together?"],
        ["Guten Appetit!", "Enjoy your meal!"],
      ],
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 10: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Die Rechnung, bitte!",
      options: ["Die Rechnung, bitte!", "Die Speisekarte, bitte!", "Ich möchte zahlen!"],
      correctIndex: 0,
      explain: "The bill request heard.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 11: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Ich möchte einen Kaffee trinken.",
      options: ["Ich möchte einen Kaffee trinken.", "Ich möchte einen Tee trinken.", "Ich muss einen Kaffee trinken."],
      correctIndex: 0,
      explain: "The polite order heard.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 12: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Ich möchte einen Kaffee.", "Ich möchte ein Kaffee.", "Ich möchte eine Kaffee."],
      correctIndex: 0,
      explain: "Kaffee is masculine: einen.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 13: Der Satz",
      instruction: "Build the sentence: I would like a tea, please.",
      chunks: ["Ich", "möchte", "einen", "Tee,", "bitte."],
      explain: "möchte is second; bitte closes the order.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 14: Der Satz",
      instruction: "Build the sentence: The bill is twelve euros.",
      chunks: ["Die", "Rechnung", "macht", "zwölf", "Euro."],
      explain: "The bill makes twelve euros.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 15: Restaurantkarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "Ich möchte einen Kaffee.", back: "I would like a coffee.", frontAudio: true },
        { front: "Ich nehme die Suppe.", back: "I will take the soup.", frontAudio: true },
        { front: "Die Speisekarte, bitte.", back: "The menu, please.", frontAudio: true },
        { front: "Was empfehlen Sie?", back: "What do you recommend?", frontAudio: true },
        { front: "Die Rechnung, bitte!", back: "The bill, please!", frontAudio: true },
        { front: "Stimmt so.", back: "Keep the change.", frontAudio: true },
        { front: "Guten Appetit!", back: "Enjoy your meal!", frontAudio: true },
        { front: "Getrennt oder zusammen?", back: "Separately or together?", frontAudio: true },
        { front: "Bar oder mit Karte?", back: "Cash or card?", frontAudio: true },
        { front: "Das schmeckt mir gut.", back: "I like the taste.", frontAudio: true },
        { front: "einen Kaffee", back: "a coffee", frontAudio: true },
        { front: "eine Suppe", back: "a soup", frontAudio: true },
      ],
    },
  ],
};

export const derAkkusativ: Lesson = {
  id: "der-akkusativ",
  title: "Der Akkusativ",
  summary:
    "The complete accusative for A1: why it exists, how articles and pronouns change, which verbs and prepositions demand it, and how to use it in sentences.",
  status: "ready",
  sections: [
    {
      heading: "Warum gibt es den Akkusativ?",
      blocks: [
        {
          type: "paragraph",
          text: "German has four cases, and the accusative (der Akkusativ, also der vierte Fall) is the case of the direct object: the person or thing that the action happens to. In Ich sehe den Mann, the seeing happens to the man. English shows this with word order; German shows it with the article. That is why German can move words around freely: the article, not the position, tells you who acts and who is acted on.",
        },
        {
          type: "paragraph",
          text: "The question word for the accusative is wen? or was? Wen siehst du? Den Mann. Was isst du? Das Brot. If a noun answers wen or was, it stands in the accusative. Learn to ask the question after every verb: it decides the case instantly.",
        },
        {
          type: "table",
          caption: "The four cases and their questions",
          head: ["Case", "Question", "Job", "Example"],
          rows: [
            ["Nominativ", "wer?", "subject, who acts", "Der Mann schläft."],
            ["Akkusativ", "wen? was?", "direct object, who is acted on", "Ich sehe den Mann."],
            ["Dativ", "wem?", "receiver, who benefits", "Ich gebe dem Mann ein Buch."],
            ["Genitiv", "wessen?", "possession (B1)", "das Auto des Mannes"],
          ],
        },
        {
          type: "tip",
          text: "The accusative is the easiest case: only the masculine changes. Learn the change once (der to den, ein to einen, kein to keinen) and the entire case is yours.",
        },
      ],
    },
    {
      heading: "Die Artikel im Akkusativ",
      blocks: [
        {
          type: "paragraph",
          text: "In the accusative, the masculine article changes and everything else stays the same: der becomes den, ein becomes einen, kein becomes keinen. Feminine, neuter, and plural keep their nominative forms.",
        },
        {
          type: "table",
          caption: "Articles in the accusative",
          head: ["Noun", "Nominative", "Accusative"],
          rows: [
            ["der Mann (m.)", "der Mann", "den Mann"],
            ["die Frau (f.)", "die Frau", "die Frau"],
            ["das Kind (n.)", "das Kind", "das Kind"],
            ["die Kinder (pl.)", "die Kinder", "die Kinder"],
            ["ein Mann", "ein Mann", "einen Mann"],
            ["eine Frau", "eine Frau", "eine Frau"],
            ["ein Kind", "ein Kind", "ein Kind"],
            ["kein Mann", "kein Mann", "keinen Mann"],
            ["keine Frau", "keine Frau", "keine Frau"],
            ["kein Kind", "kein Kind", "kein Kind"],
            ["keine Kinder", "keine Kinder", "keine Kinder"],
          ],
        },
        {
          type: "example",
          de: "Ich sehe den Mann. Ich kaufe einen Apfel. Ich habe keinen Bruder. Ich sehe die Frau, das Kind und die Kinder.",
          en: "The whole accusative table in five sentences.",
        },
        {
          type: "tip",
          text: "The possessive article changes exactly like ein: meinen Bruder, deinen Termin, seinen Koffer. The -en appears only on the masculine.",
        },
      ],
    },
    {
      heading: "Die Pronomen im Akkusativ",
      blocks: [
        {
          type: "paragraph",
          text: "Pronouns change in the accusative too: ich becomes mich, du becomes dich, and er becomes ihn. The pattern mirrors the articles: only the masculine third person changes visibly; sie, es, wir, ihr, and sie keep their form.",
        },
        {
          type: "table",
          caption: "Pronouns in the accusative",
          head: ["Person", "Nominative", "Accusative"],
          rows: [
            ["I", "ich", "mich"],
            ["you (informal)", "du", "dich"],
            ["he", "er", "ihn"],
            ["she", "sie", "sie"],
            ["it", "es", "es"],
            ["we", "wir", "uns"],
            ["you (plural)", "ihr", "euch"],
            ["they / you (formal)", "sie / Sie", "sie / Sie"],
          ],
        },
        {
          type: "example",
          de: "Sie kennt mich. Ich sehe ihn. Wir besuchen euch. Du kennst sie.",
          en: "Pronouns in the accusative.",
        },
        {
          type: "tip",
          text: "The pair to drill: er becomes ihn, and ihn is used exactly where er would be as subject. Der Kaffee ist gut. Ich trinke ihn. Der Mann ist nett. Ich kenne ihn.",
        },
      ],
    },
    {
      heading: "Verben mit Akkusativ",
      blocks: [
        {
          type: "paragraph",
          text: "Many everyday verbs always take the accusative. They are the verbs of getting and doing: haben, kaufen, essen, trinken, sehen, brauchen, suchen, finden, kennen, nehmen, möchten, machen, lesen, schreiben. Learn them as pairs: verb plus wen?",
        },
        {
          type: "table",
          caption: "The accusative verbs of A1",
          head: ["Verb", "Example"],
          rows: [
            ["haben", "Ich habe einen Bruder."],
            ["kaufen", "Ich kaufe den Apfel."],
            ["essen", "Sie isst das Brot."],
            ["trinken", "Wir trinken einen Kaffee."],
            ["sehen", "Ich sehe die Frau."],
            ["brauchen", "Er braucht einen Kaffee."],
            ["suchen", "Wir suchen den Schlüssel."],
            ["finden", "Ich finde das Buch."],
            ["kennen", "Sie kennt den Kellner."],
            ["nehmen", "Ich nehme die Suppe."],
            ["möchten", "Ich möchte einen Tee."],
            ["lesen", "Er liest die Zeitung."],
            ["schreiben", "Sie schreibt einen Brief."],
            ["machen", "Ich mache einen Termin."],
          ],
        },
        {
          type: "example",
          de: "Ich brauche einen Kaffee. Wir suchen den Schlüssel. Sie kennt den Kellner. Er liest die Zeitung.",
          en: "The accusative verb pattern: verb + wen? + object.",
        },
        {
          type: "tip",
          text: "The test that never fails: can you ask wen or was after the verb? Wen kaufst du? Den Apfel. Then the object is accusative. Every verb in this table passes the test.",
        },
      ],
    },
    {
      heading: "Präpositionen mit Akkusativ",
      blocks: [
        {
          type: "paragraph",
          text: "A small group of prepositions always demands the accusative: für (for), ohne (without), durch (through), um (around), gegen (against), bis (until). There is no choice here; these six are accusative, period.",
        },
        {
          type: "table",
          caption: "The accusative prepositions",
          head: ["Preposition", "Meaning", "Example"],
          rows: [
            ["für", "for", "Ein Geschenk für dich."],
            ["ohne", "without", "Ohne Zucker, bitte."],
            ["durch", "through", "Wir gehen durch den Park."],
            ["um", "around", "Wir fahren um die Stadt."],
            ["gegen", "against", "Das Mittel gegen Kopfschmerzen."],
            ["bis", "until", "Bis nächste Woche!"],
          ],
        },
        {
          type: "example",
          de: "Ein Geschenk für dich. Ohne den Schlüssel geht es nicht. Wir gehen durch den Park. Das Medikament gegen die Schmerzen.",
          en: "Prepositions in action, always with the accusative.",
        },
        {
          type: "tip",
          text: "Pair the preposition groups: für, ohne, durch, um, gegen take the accusative; mit, nach, aus, zu, von, bei take the dative. Learn them in two rows and never mix them again.",
        },
      ],
    },
    {
      heading: "Der Akkusativ nach wo? und wohin?",
      blocks: [
        {
          type: "paragraph",
          text: "The two-way prepositions (in, auf, an, unter, über, vor, hinter, neben, zwischen) switch between dative and accusative: the dative answers wo? (static location), the accusative answers wohin? (movement toward). This is the most tested rule in the A1 exam.",
        },
        {
          type: "table",
          caption: "wo? vs wohin?",
          head: ["wo? (dative)", "wohin? (accusative)"],
          rows: [
            ["Das Buch liegt auf dem Tisch.", "Ich lege das Buch auf den Tisch."],
            ["Die Lampe hängt an der Wand.", "Ich hänge die Lampe an die Wand."],
            ["Ich bin in der Küche.", "Ich gehe in die Küche."],
            ["Das Kind sitzt auf dem Stuhl.", "Ich setze das Kind auf den Stuhl."],
          ],
        },
        {
          type: "example",
          de: "Wo ist das Buch? Auf dem Tisch. Wohin legst du das Buch? Auf den Tisch.",
          en: "The question decides the case: wo asks dative, wohin asks accusative.",
        },
        {
          type: "tip",
          text: "Ask the question before the preposition: wo? or wohin? If the answer is a destination with movement, the object goes into the accusative: auf den Tisch, in die Küche, an die Wand.",
        },
      ],
    },
    {
      heading: "Der Akkusativ in festen Wendungen",
      blocks: [
        {
          type: "paragraph",
          text: "The accusative appears in fixed everyday phrases that the exam loves. The most important: es gibt (there is), einen Termin haben, einen Termin machen, eine Frage haben, einen Kaffee trinken. In es gibt, the object is ALWAYS accusative: Es gibt einen Park, Es gibt eine Apotheke, Es gibt ein Museum.",
        },
        {
          type: "table",
          caption: "Fixed accusative phrases",
          head: ["Phrase", "Example"],
          rows: [
            ["es gibt + Akkusativ", "Es gibt einen Park in der Stadt."],
            ["einen Termin haben", "Ich habe einen Termin beim Arzt."],
            ["einen Termin machen", "Ich möchte einen Termin machen."],
            ["eine Frage haben", "Ich habe eine Frage."],
            ["einen Kaffee trinken", "Ich trinke einen Kaffee."],
          ],
        },
        {
          type: "example",
          de: "Es gibt einen Park, eine Apotheke und ein Museum in dieser Straße.",
          en: "es gibt always takes the accusative, even with neuter: ein Museum.",
        },
        {
          type: "tip",
          text: "Es gibt is the German 'there is': the noun after it is always accusative. Es gibt einen Park (masculine accusative with -en) is the most common exam sentence in A1.",
        },
      ],
    },
    {
      heading: "Zwei Objekte: Akkusativ und Dativ",
      blocks: [
        {
          type: "paragraph",
          text: "Some verbs take two objects: a dative person (the receiver) and an accusative thing (what is given). The order is always: person first, thing second. Ich gebe dem Kind einen Apfel: the child (dative) receives the apple (accusative). With pronouns, the accusative pronoun comes first: Ich gebe ihm den Apfel, Ich gebe ihn dem Kind.",
        },
        {
          type: "table",
          caption: "Two objects",
          head: ["Pattern", "Example"],
          rows: [
            ["Dative person + accusative thing", "Ich gebe dem Kind einen Apfel."],
            ["Dative person + accusative thing", "Sie bringt dem Vater das Buch."],
            ["Pronoun accusative first", "Ich gebe ihn dem Kind."],
            ["Pronoun dative first", "Ich gebe ihm den Apfel."],
          ],
        },
        {
          type: "tip",
          text: "The receiver answers wem? and takes the dative; the thing answers was? and takes the accusative. Person first, thing second: dem Kind einen Apfel.",
        },
      ],
    },
    {
      heading: "Die häufigsten Akkusativ-Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: keeping der instead of den, forgetting the -en on einen, using ein instead of keinen in the negative, and mixing dative and accusative after two-way prepositions.",
        },
        {
          type: "table",
          caption: "The classic mistakes and the fix",
          head: ["Mistake", "Wrong", "Right", "Test"],
          rows: [
            ["der instead of den", "Ich sehe der Mann.", "Ich sehe den Mann.", "wen? -> den"],
            ["missing -en", "Ich habe ein Bruder.", "Ich habe einen Bruder.", "masculine accusative -> -en"],
            ["ein instead of kein", "Ich habe ein Bruder nicht.", "Ich habe keinen Bruder.", "negative noun -> kein"],
            ["wo/wohin mix", "Ich lege das Buch auf dem Tisch.", "Ich lege das Buch auf den Tisch.", "wohin? -> accusative"],
            ["forgetting ihn", "Der Kaffee ist gut. Ich trinke er.", "Ich trinke ihn.", "er -> ihn"],
          ],
        },
        {
          type: "tip",
          text: "One question before every object: wen oder was? The answer in the sentence must carry the accusative marker: den, einen, keinen, mich, dich, ihn.",
        },
      ],
    },
  ],
  vocab: [
    { id: "der-akkusativ", de: "der Akkusativ", en: "the accusative case", part: "noun m.", audio: true },
    { id: "das-direkte-objekt", de: "das direkte Objekt", en: "the direct object", part: "noun n.", plural: "die direkten Objekte", audio: true },
    { id: "kaufen", de: "kaufen", en: "to buy", part: "verb", audio: true },
    { id: "brauchen", de: "brauchen", en: "to need", part: "verb", audio: true },
    { id: "suchen", de: "suchen", en: "to look for", part: "verb", audio: true },
    { id: "finden", de: "finden", en: "to find", part: "verb", audio: true },
    { id: "nehmen", de: "nehmen", en: "to take", part: "verb", audio: true },
    { id: "kennen", de: "kennen", en: "to know (someone)", part: "verb", audio: true },
    { id: "den-mann", de: "den Mann", en: "the man (accusative)", part: "phrase", phrase: true, audio: true },
    { id: "einen-apfel", de: "einen Apfel", en: "an apple (accusative)", part: "phrase", phrase: true, audio: true },
    { id: "keinen-bruder", de: "keinen Bruder", en: "no brother (accusative)", part: "phrase", phrase: true, audio: true },
    { id: "mich", de: "mich", en: "me (accusative)", part: "pronoun", audio: true },
    { id: "ihn", de: "ihn", en: "him (accusative)", part: "pronoun", audio: true },
    { id: "fuer-dich", de: "für dich", en: "for you", part: "phrase", phrase: true, audio: true },
    { id: "ohne-zucker", de: "ohne Zucker", en: "without sugar", part: "phrase", phrase: true, audio: true },
    { id: "es-gibt", de: "es gibt", en: "there is / there are", part: "phrase", phrase: true, audio: true },
    { id: "den-schluessel", de: "den Schlüssel", en: "the key (accusative)", part: "phrase", phrase: true, audio: true },
    { id: "auf-den-tisch", de: "auf den Tisch", en: "onto the table (wohin)", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-wen-frage",
      type: "multiple-choice",
      title: "Übung 1: Die wen-Frage",
      instruction: "Choose the question for the accusative.",
      prompt: "Wen oder was? Das ist die Frage nach dem ...",
      options: ["Akkusativ", "Nominativ", "Dativ"],
      correctIndex: 0,
      explain: "wen? was? asks for the direct object: the accusative.",
    },
    {
      id: "ex-artikel-1",
      type: "multiple-choice",
      title: "Übung 2: Der Artikel",
      instruction: "Choose the accusative article.",
      prompt: "Ich sehe ___ Mann.",
      options: ["den", "der", "dem"],
      correctIndex: 0,
      explain: "sehen takes the accusative: den Mann.",
    },
    {
      id: "ex-artikel-2",
      type: "multiple-choice",
      title: "Übung 3: Der Artikel",
      instruction: "Choose the accusative article.",
      prompt: "Ich kaufe ___ Apfel.",
      options: ["einen", "ein", "eine"],
      correctIndex: 0,
      explain: "Apfel is masculine, accusative: einen Apfel.",
    },
    {
      id: "ex-artikel-3",
      type: "multiple-choice",
      title: "Übung 4: Der Artikel",
      instruction: "Choose the accusative article.",
      prompt: "Ich habe ___ Bruder.",
      options: ["keinen", "kein", "keine"],
      correctIndex: 0,
      explain: "Masculine accusative negative: keinen Bruder.",
    },
    {
      id: "ex-pronomen",
      type: "fill-blank",
      title: "Übung 5: Die Pronomen",
      instruction: "Complete with the accusative pronoun.",
      sentence: "Sie kennt ___. (me) Ich sehe ___. (him) Wir besuchen ___. (you all) Du kennst ___. (her)",
      blanks: [
        { answers: ["mich"], hint: "ich -> mich" },
        { answers: ["ihn"], hint: "er -> ihn" },
        { answers: ["euch"], hint: "ihr -> euch" },
        { answers: ["sie"], hint: "sie stays sie" },
      ],
    },
    {
      id: "ex-verben",
      type: "fill-blank",
      title: "Übung 6: Verben mit Akkusativ",
      instruction: "Complete with the right object.",
      sentence: "Ich habe ___ Termin. Wir suchen ___ Schlüssel. Sie kennt ___ Kellner.",
      blanks: [
        { answers: ["einen"], hint: "Termin, masculine" },
        { answers: ["den"], hint: "Schlüssel, masculine" },
        { answers: ["den"], hint: "Kellner, masculine" },
      ],
    },
    {
      id: "ex-praepositionen",
      type: "multiple-choice",
      title: "Übung 7: Präpositionen",
      instruction: "Choose the correct preposition.",
      prompt: "Ein Geschenk ___ dich.",
      options: ["für", "mit", "bei"],
      correctIndex: 0,
      explain: "für takes the accusative: für dich.",
    },
    {
      id: "ex-praepositionen-2",
      type: "multiple-choice",
      title: "Übung 8: Präpositionen",
      instruction: "Choose the correct preposition.",
      prompt: "Wir gehen ___ den Park.",
      options: ["durch", "mit", "zu"],
      correctIndex: 0,
      explain: "durch takes the accusative: durch den Park.",
    },
    {
      id: "ex-wo-wohin",
      type: "multiple-choice",
      title: "Übung 9: wo oder wohin?",
      instruction: "Choose the correct form.",
      prompt: "Ich lege das Buch ___ den Tisch.",
      options: ["auf", "unter", "hinter"],
      correctIndex: 0,
      explain: "The movement phrase: auf den Tisch (accusative).",
    },
    {
      id: "ex-wo-wohin-2",
      type: "multiple-choice",
      title: "Übung 10: wo oder wohin?",
      instruction: "Choose the correct case.",
      prompt: "Das Buch liegt auf ___ Tisch.",
      options: ["dem", "den", "der"],
      correctIndex: 0,
      explain: "Static location takes the dative: auf dem Tisch.",
    },
    {
      id: "ex-es-gibt",
      type: "fill-blank",
      title: "Übung 11: es gibt",
      instruction: "Complete with the accusative article.",
      sentence: "Es gibt ___ Park. (a) Es gibt ___ Apotheke. (a) Es gibt ___ Museum. (a)",
      blanks: [
        { answers: ["einen"], hint: "masculine" },
        { answers: ["eine"], hint: "feminine" },
        { answers: ["ein"], hint: "neuter" },
      ],
    },
    {
      id: "ex-zwei-objekte",
      type: "multiple-choice",
      title: "Übung 12: Zwei Objekte",
      instruction: "Choose the correct word order.",
      prompt: "Ich gebe ...",
      options: ["dem Kind einen Apfel", "einen Apfel dem Kind", "den Apfel dem Kind"],
      correctIndex: 0,
      explain: "Dative person first, accusative thing second.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 13: Hören",
      instruction: "Play the audio and pick the phrase you heard.",
      prompt: "einen Kaffee",
      options: ["einen Kaffee", "ein Kaffee", "der Kaffee"],
      correctIndex: 0,
      explain: "The accusative masculine: einen Kaffee.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 14: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Ich kenne den Kellner.",
      options: ["Ich kenne den Kellner.", "Ich kenne der Kellner.", "Ich kenne einen Kellner."],
      correctIndex: 0,
      explain: "The known waiter: den Kellner.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 15: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Ich habe einen Bruder.", "Ich habe ein Bruder.", "Ich habe einer Bruder."],
      correctIndex: 0,
      explain: "Masculine accusative: einen Bruder.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 16: Der Satz",
      instruction: "Build the sentence: I am buying a new computer.",
      chunks: ["Ich", "kaufe", "einen", "neuen", "Computer."],
      explain: "The accusative object follows the verb.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 17: Der Satz",
      instruction: "Build the sentence: There is a park in the city.",
      chunks: ["Es", "gibt", "einen", "Park", "in", "der", "Stadt."],
      explain: "es gibt always takes the accusative.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 18: Akkusativkarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "den Mann", back: "the man (accusative)", frontAudio: true },
        { front: "einen Apfel", back: "an apple (accusative)", frontAudio: true },
        { front: "keinen Bruder", back: "no brother (accusative)", frontAudio: true },
        { front: "mich", back: "me (accusative)", frontAudio: true },
        { front: "ihn", back: "him (accusative)", frontAudio: true },
        { front: "für dich", back: "for you", frontAudio: true },
        { front: "ohne Zucker", back: "without sugar", frontAudio: true },
        { front: "durch den Park", back: "through the park", frontAudio: true },
        { front: "auf den Tisch", back: "onto the table", frontAudio: true },
        { front: "es gibt einen Park", back: "there is a park", frontAudio: true },
        { front: "den Schlüssel", back: "the key (accusative)", frontAudio: true },
        { front: "einen Termin", back: "an appointment", frontAudio: true },
      ],
    },
  ],
};

export const modalverben: Lesson = {
  id: "modalverben",
  title: "Modalverben: können, möchten, wollen, müssen",
  summary:
    "The complete modal verb system for A1: all six modals, full conjugation, sentence structure, meanings, and the most common mistakes.",
  status: "ready",
  sections: [
    {
      heading: "Was sind Modalverben?",
      blocks: [
        {
          type: "paragraph",
          text: "Modal verbs change the mood of a sentence: they say whether something is possible, desired, necessary, or allowed. Instead of Ich lerne Deutsch (I learn German), the modal system says Ich kann Deutsch lernen (I CAN learn German), Ich möchte Deutsch lernen (I would LIKE to learn German), Ich muss Deutsch lernen (I MUST learn German).",
        },
        {
          type: "paragraph",
          text: "There are six modals in German: können (can), möchten (would like to), wollen (want to), müssen (must), dürfen (may), sollen (should). Every modal works the same way: it is conjugated and stands in position two, while the main verb goes to the very end of the sentence in the infinitive.",
        },
        {
          type: "table",
          caption: "The six modals and their meanings",
          head: ["Modal", "Meaning", "Question it answers"],
          rows: [
            ["können", "can, to be able to", "Is it possible?"],
            ["möchten", "would like to", "Do I want it (politely)?"],
            ["wollen", "to want to", "Do I want it?"],
            ["müssen", "must, to have to", "Is it necessary?"],
            ["dürfen", "may, to be allowed to", "Is it allowed?"],
            ["sollen", "should", "Is it expected?"],
          ],
        },
        {
          type: "tip",
          text: "möchten is the polite one: it is the form you use to order food, ask for things, and make requests. Ich möchte einen Kaffee is the golden sentence of A1.",
        },
      ],
    },
    {
      heading: "Die Konjugation aller sechs Modalverben",
      blocks: [
        {
          type: "paragraph",
          text: "All six modals are irregular in the same pattern: the singular forms lose their ending entirely for ich and er/sie/es (kann, kann, kann), du adds -st (kannst), and the plural forms are regular (können, könnt, können). The vowel changes between singular and plural for können, müssen, and dürfen.",
        },
        {
          type: "table",
          caption: "The complete modal conjugation",
          head: ["Person", "können", "möchten", "wollen", "müssen", "dürfen", "sollen"],
          rows: [
            ["ich", "kann", "möchte", "will", "muss", "darf", "soll"],
            ["du", "kannst", "möchtest", "willst", "musst", "darfst", "sollst"],
            ["er / sie / es", "kann", "möchte", "will", "muss", "darf", "soll"],
            ["wir", "können", "möchten", "wollen", "müssen", "dürfen", "sollen"],
            ["ihr", "könnt", "möchtet", "wollt", "müsst", "dürft", "sollt"],
            ["sie / Sie", "können", "möchten", "wollen", "müssen", "dürfen", "sollen"],
          ],
        },
        {
          type: "example",
          de: "Ich kann schwimmen. Du möchtest einen Kaffee. Er will nach Berlin fahren. Wir müssen arbeiten. Ihr dürft gehen. Sie sollen das Formular ausfüllen.",
          en: "All six modals, all six persons.",
        },
        {
          type: "tip",
          text: "The pattern is simple: ich and er share the bare form (kann, möchte, will, muss, darf, soll). Only du and ihr add endings. Learn the six ich-forms first; the rest follows.",
        },
      ],
    },
    {
      heading: "Der Satzbau: Modal + Infinitiv am Ende",
      blocks: [
        {
          type: "paragraph",
          text: "The modal verb is conjugated and holds position two. The main verb stands at the very end of the sentence in the infinitive. Together they form the sentence bracket: the modal opens the bracket, the infinitive closes it. Everything else lives inside.",
        },
        {
          type: "table",
          caption: "The modal bracket",
          head: ["Sentence", "Position two", "End of sentence"],
          rows: [
            ["Ich kann gut schwimmen.", "kann", "schwimmen"],
            ["Ich möchte einen Kaffee trinken.", "möchte", "trinken"],
            ["Er muss morgen früh aufstehen.", "muss", "aufstehen"],
            ["Wir wollen am Wochenende wandern.", "wollen", "wandern"],
          ],
        },
        {
          type: "example",
          de: "Ich kann gut kochen. Ich möchte heute Abend einen Film sehen. Er muss um sieben Uhr aufstehen.",
          en: "Modal in position two, infinitive at the end.",
        },
        {
          type: "tip",
          text: "Read the sentence from the end: Ich möchte einen Kaffee trinken means the action is trinken, the wish is möchte. The infinitive at the end is always the real action.",
        },
      ],
    },
    {
      heading: "Die Bedeutung im Detail",
      blocks: [
        {
          type: "paragraph",
          text: "Each modal has its own world of use. können expresses ability and possibility: Ich kann schwimmen, Er kann heute kommen. möchten is the polite want, used for orders and requests: Ich möchte einen Tee. wollen is the strong want: Ich will nach Berlin fahren. müssen expresses necessity, inner or outer: Ich muss arbeiten, Der Zug muss um zehn ankommen. dürfen expresses permission: Hier dürfen Sie nicht rauchen. sollen expresses expectation and advice: Du sollst mehr Wasser trinken.",
        },
        {
          type: "table",
          caption: "The modals in real life",
          head: ["Modal", "Situation", "Example"],
          rows: [
            ["können", "ability", "Ich kann gut schwimmen."],
            ["können", "possibility", "Er kann heute kommen."],
            ["möchten", "polite order", "Ich möchte einen Kaffee."],
            ["wollen", "strong desire", "Ich will Deutsch lernen."],
            ["müssen", "necessity", "Ich muss um sieben aufstehen."],
            ["dürfen", "permission", "Hier darf man nicht rauchen."],
            ["sollen", "advice", "Du sollst mehr Wasser trinken."],
            ["sollen", "expectation", "Sie sollen das Formular ausfüllen."],
          ],
        },
        {
          type: "example",
          de: "Ich kann Deutsch, aber ich muss mehr üben. Möchten Sie einen Kaffee? Ich will ein Auto kaufen. Hier dürfen Sie nicht rauchen. Du sollst mehr schlafen.",
          en: "All six modals in one text.",
        },
        {
          type: "tip",
          text: "The exam pairs: möchte for ordering in a restaurant, muss for obligations, kann for abilities, darf for rules (Rauchen verboten). Learn the situations, not just the words.",
        },
      ],
    },
    {
      heading: "Negation mit Modalverben",
      blocks: [
        {
          type: "paragraph",
          text: "The negative of a modal sentence uses nicht before the infinitive at the end: Ich kann nicht kommen. The meaning of the negation changes with the modal: Ich muss nicht arbeiten means I do not have to work (no obligation); Ich kann nicht kommen means I cannot come (no ability). Note: müssen negated means 'not have to', not 'must not'; forbidden is expressed with dürfen nicht: Hier darf man nicht rauchen.",
        },
        {
          type: "table",
          caption: "Negated modals",
          head: ["Sentence", "Meaning"],
          rows: [
            ["Ich kann nicht kommen.", "I cannot come."],
            ["Ich möchte keinen Kaffee.", "I would not like a coffee."],
            ["Ich will nicht gehen.", "I do not want to go."],
            ["Ich muss nicht arbeiten.", "I do not have to work."],
            ["Hier darf man nicht rauchen.", "Smoking is not allowed here."],
            ["Du sollst nicht lügen.", "You should not lie."],
          ],
        },
        {
          type: "tip",
          text: "muss nicht means 'does not have to', not 'must not'. The forbidden meaning belongs to darf nicht. This distinction is tested in A1.",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: forgetting the infinitive at the end, conjugating the main verb, mixing wollen and möchten, and using kann instead of darf for permission.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["missing infinitive", "Ich möchte einen Kaffee.", "Ich möchte einen Kaffee trinken.", "the action verb waits at the end"],
            ["conjugated main verb", "Ich kann Deutsch lerne.", "Ich kann Deutsch lernen.", "after a modal, always the infinitive"],
            ["wollen vs möchten", "Ich möchte nach Berlin fahren (strong want).", "Ich will nach Berlin fahren.", "wollen is the strong want"],
            ["kann vs darf", "Hier kann man nicht rauchen.", "Hier darf man nicht rauchen.", "permission takes dürfen"],
            ["muss nicht mix", "Ich muss nicht arbeiten. (I am forbidden to work.)", "Ich muss nicht arbeiten. (I do not have to work.)", "forbidden = darf nicht"],
          ],
        },
        {
          type: "tip",
          text: "After every modal, the next verb is ALWAYS an infinitive at the end. If you see a conjugated verb after kann or möchte, stop and correct it.",
        },
      ],
    },
  ],
  vocab: [
    { id: "das-modalverb", de: "das Modalverb", en: "the modal verb", part: "noun n.", plural: "die Modalverben", audio: true },
    { id: "koennen", de: "können", en: "can, to be able to", part: "verb", audio: true },
    { id: "moechten", de: "möchten", en: "would like to", part: "verb", audio: true },
    { id: "wollen", de: "wollen", en: "to want to", part: "verb", audio: true },
    { id: "muessen", de: "müssen", en: "must, to have to", part: "verb", audio: true },
    { id: "duerfen", de: "dürfen", en: "may, to be allowed to", part: "verb", audio: true },
    { id: "sollen", de: "sollen", en: "should", part: "verb", audio: true },
    { id: "ich-kann", de: "ich kann", en: "I can", part: "phrase", phrase: true, audio: true },
    { id: "du-kannst", de: "du kannst", en: "you can", part: "phrase", phrase: true, audio: true },
    { id: "ich-moechte", de: "ich möchte", en: "I would like", part: "phrase", phrase: true, audio: true },
    { id: "ich-muss", de: "ich muss", en: "I must", part: "phrase", phrase: true, audio: true },
    { id: "ich-will", de: "ich will", en: "I want", part: "phrase", phrase: true, audio: true },
    { id: "ich-darf", de: "ich darf", en: "I may", part: "phrase", phrase: true, audio: true },
    { id: "du-sollst", de: "du sollst", en: "you should", part: "phrase", phrase: true, audio: true },
    { id: "kochen", de: "kochen", en: "to cook", part: "verb", audio: true },
    { id: "schwimmen", de: "schwimmen", en: "to swim", part: "verb", audio: true },
    { id: "rauchen", de: "rauchen", en: "to smoke", part: "verb", audio: true },
    { id: "aufstehen", de: "aufstehen", en: "to get up", part: "verb", audio: true },
  ],
  exercises: [
    {
      id: "ex-konjugation",
      type: "fill-blank",
      title: "Übung 1: Die Konjugation",
      instruction: "Complete with the right modal form.",
      sentence: "Ich ___ gut schwimmen. (können) Du ___ einen Kaffee? (möchten) Er ___ nach Berlin fahren. (wollen) Wir ___ arbeiten. (müssen) Ihr ___ gehen. (dürfen)",
      blanks: [
        { answers: ["kann"], hint: "können, ich" },
        { answers: ["möchtest"], hint: "möchten, du" },
        { answers: ["will"], hint: "wollen, er" },
        { answers: ["müssen"], hint: "müssen, wir" },
        { answers: ["dürft"], hint: "dürfen, ihr" },
      ],
    },
    {
      id: "ex-bedeutung",
      type: "multiple-choice",
      title: "Übung 2: Die Bedeutung",
      instruction: "Choose the modal that fits the situation.",
      prompt: "You are ordering a coffee. You say: Ich ___ einen Kaffee.",
      options: ["möchte", "muss", "darf"],
      correctIndex: 0,
      explain: "Orders and requests use möchten.",
    },
    {
      id: "ex-bedeutung-2",
      type: "multiple-choice",
      title: "Übung 3: Die Bedeutung",
      instruction: "Choose the modal that fits the situation.",
      prompt: "The sign says smoking is not allowed: Hier ___ man nicht rauchen.",
      options: ["darf", "kann", "möchte"],
      correctIndex: 0,
      explain: "Rules and permission use dürfen.",
    },
    {
      id: "ex-bedeutung-3",
      type: "multiple-choice",
      title: "Übung 4: Die Bedeutung",
      instruction: "Choose the modal that fits the situation.",
      prompt: "Advice from the doctor: Du ___ mehr Wasser trinken.",
      options: ["sollst", "willst", "kannst"],
      correctIndex: 0,
      explain: "Advice uses sollen: Du sollst.",
    },
    {
      id: "ex-satzbau",
      type: "multiple-choice",
      title: "Übung 5: Der Satzbau",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Ich möchte einen Kaffee trinken.", "Ich möchte trinken einen Kaffee.", "Ich möchte einen Kaffee trinke."],
      correctIndex: 0,
      explain: "The modal holds position two; the infinitive waits at the end.",
    },
    {
      id: "ex-infinitiv",
      type: "fill-blank",
      title: "Übung 6: Der Infinitiv",
      instruction: "Complete with the infinitive at the end.",
      sentence: "Ich kann gut ___ (schwimmen). Er muss um sieben ___ (aufstehen). Wir wollen am Wochenende ___ (wandern).",
      blanks: [
        { answers: ["schwimmen"], hint: "the action" },
        { answers: ["aufstehen"], hint: "separable infinitive" },
        { answers: ["wandern"], hint: "the action" },
      ],
    },
    {
      id: "ex-negation",
      type: "multiple-choice",
      title: "Übung 7: Die Negation",
      instruction: "Choose the correct meaning.",
      prompt: "Ich muss nicht arbeiten. Means ...",
      options: ["I do not have to work.", "I am forbidden to work.", "I cannot work."],
      correctIndex: 0,
      explain: "muss nicht = no obligation. Forbidden is darf nicht.",
    },
    {
      id: "ex-negation-2",
      type: "fill-blank",
      title: "Übung 8: Die Negation",
      instruction: "Complete with nicht or keinen.",
      sentence: "Ich kann ___ kommen. (not) Ich möchte ___ Kaffee. (no, masculine) Hier darf man ___ rauchen. (not)",
      blanks: [
        { answers: ["nicht"], hint: "before the infinitive" },
        { answers: ["keinen"], hint: "noun negation" },
        { answers: ["nicht"], hint: "before the verb" },
      ],
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 9: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Ich kann gut kochen.",
      options: ["Ich kann gut kochen.", "Ich kann gut schwimmen.", "Ich möchte gut kochen."],
      correctIndex: 0,
      explain: "The modal and verb heard: kann kochen.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 10: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Du sollst mehr Wasser trinken.",
      options: ["Du sollst mehr Wasser trinken.", "Du sollst mehr Wasser kaufen.", "Du musst mehr Wasser trinken."],
      correctIndex: 0,
      explain: "The advice heard: sollst trinken.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 11: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Ich kann Deutsch lernen.", "Ich kann Deutsch lerne.", "Ich kann lerne Deutsch."],
      correctIndex: 0,
      explain: "After a modal, the main verb is always an infinitive at the end.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 12: Der Satz",
      instruction: "Build the sentence: I would like to drink a coffee.",
      chunks: ["Ich", "möchte", "einen", "Kaffee", "trinken."],
      explain: "The modal is second; the infinitive closes the bracket.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 13: Der Satz",
      instruction: "Build the sentence: He has to get up at seven.",
      chunks: ["Er", "muss", "um", "sieben", "Uhr", "aufstehen."],
      explain: "The separable infinitive stays whole at the end.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 14: Modalverbenkarten",
      instruction: "Say the German form out loud before revealing.",
      items: [
        { front: "ich kann", back: "I can", frontAudio: true },
        { front: "du kannst", back: "you can", frontAudio: true },
        { front: "ich möchte", back: "I would like", frontAudio: true },
        { front: "du möchtest", back: "you would like", frontAudio: true },
        { front: "ich will", back: "I want", frontAudio: true },
        { front: "ich muss", back: "I must", frontAudio: true },
        { front: "ich darf", back: "I may", frontAudio: true },
        { front: "du sollst", back: "you should", frontAudio: true },
        { front: "Ich möchte einen Kaffee.", back: "I would like a coffee.", frontAudio: true },
        { front: "Hier darf man nicht rauchen.", back: "No smoking here.", frontAudio: true },
        { front: "Du sollst mehr schlafen.", back: "You should sleep more.", frontAudio: true },
        { front: "Ich muss um sieben aufstehen.", back: "I have to get up at seven.", frontAudio: true },
      ],
    },
  ],
};

const pluralBildung: Lesson = {
  id: "plural-bildung",
  title: "Der Plural",
  summary: "Plural patterns: -e, -er, -n, -s, no change, and umlauts.",
  status: "ready",
  sections: [
    {
      heading: "Die Pluralmuster",
      blocks: [
        {
          type: "paragraph",
          text: "German plurals follow five main patterns. There is no single rule, so always learn a noun with its plural. The plural article is always die.",
        },
        {
          type: "table",
          caption: "The five patterns",
          head: ["Pattern", "Example", "Plural"],
          rows: [
            ["no change (sometimes with umlaut)", "der Vater", "die Väter"],
            ["+ -e (sometimes with umlaut)", "der Tisch", "die Tische"],
            ["+ -er (often with umlaut)", "das Kind", "die Kinder"],
            ["+ -n or -en", "die Frau", "die Frauen"],
            ["+ -s", "das Auto", "die Autos"],
          ],
        },
        {
          type: "tip",
          text: "Umlauts appear on a, o, u: der Apfel -> die Äpfel, der Sohn -> die Söhne, das Buch -> die Bücher.",
        },
      ],
    },
    {
      heading: "Wichtige Plurale",
      blocks: [
        {
          type: "table",
          caption: "Common nouns with plurals",
          head: ["Singular", "Plural", "English"],
          rows: [
            ["der Mann", "die Männer", "men"],
            ["die Mutter", "die Mütter", "mothers"],
            ["das Buch", "die Bücher", "books"],
            ["das Haus", "die Häuser", "houses"],
            ["der Student", "die Studenten", "students"],
            ["das Kind", "die Kinder", "children"],
            ["der Apfel", "die Äpfel", "apples"],
            ["die Banane", "die Bananen", "bananas"],
          ],
        },
      ],
    },
    {
      heading: "Kein Plural für ein",
      blocks: [
        {
          type: "paragraph",
          text: "ein has no plural. To say not any or no + plural, German uses keine.",
        },
        {
          type: "example",
          de: "Ich habe keine Äpfel.",
          en: "I have no apples.",
        },
        {
          type: "example",
          de: "Wir haben keine Kinder.",
          en: "We have no children.",
        },
      ],
    },
  ],
  vocab: [
    { id: "der-tisch", de: "der Tisch", en: "the table", part: "noun m.", plural: "die Tische", audio: true },
    { id: "die-frau", de: "die Frau", en: "the woman", part: "noun f.", plural: "die Frauen", audio: true },
    { id: "das-auto", de: "das Auto", en: "the car", part: "noun n.", plural: "die Autos", audio: true },
    { id: "der-mann", de: "der Mann", en: "the man", part: "noun m.", plural: "die Männer", audio: true },
    { id: "die-mutter", de: "die Mutter", en: "the mother", part: "noun f.", plural: "die Mütter", audio: true },
    { id: "das-buch", de: "das Buch", en: "the book", part: "noun n.", plural: "die Bücher", audio: true },
    { id: "das-haus", de: "das Haus", en: "the house", part: "noun n.", plural: "die Häuser", audio: true },
    { id: "der-student", de: "der Student", en: "the student", part: "noun m.", plural: "die Studenten", audio: true },
    { id: "das-kind", de: "das Kind", en: "the child", part: "noun n.", plural: "die Kinder", audio: true },
    { id: "der-sohn", de: "der Sohn", en: "the son", part: "noun m.", plural: "die Söhne", audio: true },
  ],
  exercises: [
    {
      id: "mc-plural",
      type: "multiple-choice",
      title: "Der Plural",
      instruction: "Choose the correct plural.",
      prompt: "Der Plural von der Apfel ist ...",
      options: ["die Äpfel", "die Apfelen", "die Apfels"],
      correctIndex: 0,
      explain: "der Apfel takes the no-change pattern with umlaut: die Äpfel.",
    },
    {
      id: "listening-plural",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the word you heard.",
      prompt: "die Bücher",
      options: ["die Bücher", "das Buch", "die Buchen"],
      correctIndex: 0,
    },
    {
      id: "fill-plural",
      type: "fill-blank",
      title: "Plural bilden",
      instruction: "Write the plural forms.",
      sentence: "der Mann -> die ___, das Auto -> die ___.",
      blanks: [
        { answers: ["Männer"], hint: "with umlaut" },
        { answers: ["Autos"], hint: "-s pattern" },
      ],
    },
    {
      id: "matching-plural",
      type: "matching",
      title: "Singular und Plural",
      instruction: "Match each noun to its plural.",
      pairs: [
        ["der Tisch", "die Tische"],
        ["die Frau", "die Frauen"],
        ["das Auto", "die Autos"],
        ["das Kind", "die Kinder"],
        ["der Sohn", "die Söhne"],
      ],
    },
    {
      id: "word-order-plural",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: The apples are good.",
      chunks: ["Die", "Äpfel", "sind", "gut."],
      explain: "The plural article die leads; the verb stays second.",
    },
    {
      id: "flashcard-plural",
      type: "flashcard",
      title: "Pluralkarten",
      instruction: "Say the plural out loud before revealing.",
      items: [
        { front: "der Tisch", back: "die Tische", frontAudio: true },
        { front: "die Frau", back: "die Frauen", frontAudio: true },
        { front: "das Auto", back: "die Autos", frontAudio: true },
        { front: "der Mann", back: "die Männer", frontAudio: true },
        { front: "das Buch", back: "die Bücher", frontAudio: true },
        { front: "das Kind", back: "die Kinder", frontAudio: true },
      ],
    },
  ],
};

const preiseUndBezahlen: Lesson = {
  id: "preise-und-bezahlen",
  title: "Preise und Bezahlen",
  summary: "Prices in euros, paying, and restaurant numbers.",
  status: "ready",
  sections: [
    {
      heading: "Preise",
      blocks: [
        {
          type: "paragraph",
          text: "Prices are read with a comma: 2,50 Euro is zwei fünfzig. The comma is the decimal separator, and it is spoken as a small pause.",
        },
        {
          type: "example",
          de: "Was kostet das? Das kostet 9,99 Euro.",
          en: "How much is that? That costs 9.99 euros.",
        },
        {
          type: "example",
          de: "Wie viel kostet das Brot? Drei Euro zwanzig.",
          en: "How much is the bread? Three euros twenty.",
        },
        {
          type: "tip",
          text: "Euro stays the same in the plural after numbers: 10 Euro, 25 Euro. cents are die Cent.",
        },
      ],
    },
    {
      heading: "Bezahlen",
      blocks: [
        {
          type: "table",
          caption: "Paying",
          head: ["German", "English"],
          rows: [
            ["bar bezahlen", "to pay cash"],
            ["mit Karte zahlen", "to pay by card"],
            ["das Bargeld", "the cash"],
            ["die Kreditkarte", "the credit card"],
            ["der Cent", "the cent"],
            ["das Geld", "the money"],
            ["teuer", "expensive"],
            ["billig", "cheap"],
          ],
        },
        {
          type: "example",
          de: "Zahlen Sie bar oder mit Karte? Mit Karte, bitte.",
          en: "Are you paying cash or by card? By card, please.",
        },
        {
          type: "example",
          de: "Das ist aber teuer! Das ist billig.",
          en: "That is expensive! That is cheap.",
        },
      ],
    },
    {
      heading: "Der Dialog",
      blocks: [
        {
          type: "example",
          de: "Gast: Was kostet das Brot? Verkäufer: Drei Euro zwanzig. Gast: Hier bitte. Verkäufer: Danke schön!",
          en: "Customer: How much is the bread? Seller: Three euros twenty. Customer: Here you go. Seller: Thank you!",
        },
        {
          type: "tip",
          text: "Hier, bitte. is the natural way to hand over money.",
        },
      ],
    },
  ],
  vocab: [
    { id: "kosten", de: "kosten", en: "to cost", part: "verb", audio: true },
    { id: "der-preis", de: "der Preis", en: "the price", part: "noun m.", plural: "die Preise", audio: true },
    { id: "bezahlen", de: "bezahlen", en: "to pay", part: "verb", audio: true },
    { id: "das-geld", de: "das Geld", en: "the money", part: "noun n.", plural: "-", audio: true },
    { id: "das-bargeld", de: "das Bargeld", en: "the cash", part: "noun n.", plural: "-", audio: true },
    { id: "die-karte", de: "die Karte", en: "the card", part: "noun f.", plural: "die Karten", audio: true },
    { id: "der-cent", de: "der Cent", en: "the cent", part: "noun m.", plural: "die Cent", audio: true },
    { id: "teuer", de: "teuer", en: "expensive", part: "adjective", audio: true },
    { id: "billig", de: "billig", en: "cheap", part: "adjective", audio: true },
    { id: "bar", de: "bar", en: "cash (adverb)", part: "adverb", audio: true },
    { id: "was-kostet", de: "Was kostet das?", en: "How much is that?", part: "phrase", phrase: true, audio: true },
    { id: "wie-viel-kostet", de: "Wie viel kostet das Brot?", en: "How much is the bread?", part: "phrase", phrase: true, audio: true },
    { id: "hier-bitte", de: "Hier, bitte.", en: "Here you go.", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "mc-preise",
      type: "multiple-choice",
      title: "Der Preis",
      instruction: "Read the price correctly.",
      prompt: "19,99 Euro",
      options: ["neunzehn neunundneunzig", "neunzehn komma neunundneunzig", "neunundneunzig Euro"],
      correctIndex: 0,
      explain: "After the comma, the cents are read as one number: neun neunundneunzig.",
    },
    {
      id: "listening-preise",
      type: "listening",
      title: "Was kostet es?",
      instruction: "Play the audio and pick the price you heard.",
      prompt: "drei Euro zwanzig",
      options: ["drei Euro zwanzig", "drei Euro zwei", "zwanzig Euro drei"],
      correctIndex: 0,
    },
    {
      id: "fill-preise",
      type: "fill-blank",
      title: "Im Geschäft",
      instruction: "Complete the questions.",
      sentence: "___ kostet das Brot? Wie ___ kostet das?",
      blanks: [
        { answers: ["Was"], hint: "what costs" },
        { answers: ["viel"], hint: "how much" },
      ],
    },
    {
      id: "matching-preise",
      type: "matching",
      title: "Preise",
      instruction: "Match each price to the correct number.",
      pairs: [
        ["zwei fünfzig", "2,50 €"],
        ["zehn Euro", "10,00 €"],
        ["neunzehn neunundneunzig", "19,99 €"],
        ["fünf Cent", "0,05 €"],
        ["drei Euro zwanzig", "3,20 €"],
      ],
    },
    {
      id: "word-order-preise",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: The bread costs three euros.",
      chunks: ["Das", "Brot", "kostet", "drei", "Euro."],
      explain: "kostet sits in second position.",
    },
    {
      id: "flashcard-preise",
      type: "flashcard",
      title: "Preiskarten",
      instruction: "Say the German price out loud before revealing.",
      items: [
        { front: "Was kostet das?", back: "How much is that?", frontAudio: true },
        { front: "Das kostet 10 Euro.", back: "That costs 10 euros.", frontAudio: true },
        { front: "bar bezahlen", back: "to pay cash", frontAudio: true },
        { front: "mit Karte zahlen", back: "to pay by card", frontAudio: true },
        { front: "teuer", back: "expensive", frontAudio: true },
        { front: "billig", back: "cheap", frontAudio: true },
      ],
    },
  ],
};

export const essenUndTrinken: Unit = {
  id: "essen-und-trinken",
  title: "Essen und Trinken",
  theme: "Food and drink",
  lessons: [
    lebensmittel,
    imRestaurant,
    derAkkusativ,
    modalverben,
    pluralBildung,
    preiseUndBezahlen,
  ],
};