import type { Lesson, Unit } from "../../schema";

const lebensmittel: Lesson = {
  id: "lebensmittel",
  title: "Lebensmittel",
  summary: "Food and drink vocabulary: what is on the table.",
  status: "ready",
  sections: [
    {
      heading: "Was isst du?",
      blocks: [
        {
          type: "paragraph",
          text: "Learn food words with their articles from the start: the article is part of the word. Brot is bread, das Brot is the word you need.",
        },
        {
          type: "table",
          caption: "Food",
          head: ["German", "English"],
          rows: [
            ["das Brot", "the bread"],
            ["die Butter", "the butter"],
            ["der Käse", "the cheese"],
            ["die Wurst", "the sausage"],
            ["das Ei", "the egg"],
            ["das Müsli", "the muesli"],
            ["der Joghurt", "the yogurt"],
            ["der Schinken", "the ham"],
            ["der Reis", "the rice"],
            ["die Nudeln", "the pasta"],
            ["das Fleisch", "the meat"],
            ["das Hähnchen", "the chicken"],
          ],
        },
      ],
    },
    {
      heading: "Getränke",
      blocks: [
        {
          type: "table",
          caption: "Drinks",
          head: ["German", "English"],
          rows: [
            ["das Wasser", "the water"],
            ["der Kaffee", "the coffee"],
            ["der Tee", "the tea"],
            ["der Saft", "the juice"],
            ["die Milch", "the milk"],
            ["das Bier", "the beer"],
            ["der Wein", "the wine"],
          ],
        },
        {
          type: "tip",
          text: "still means non-carbonated: stilles Wasser. With gas it is Mineralwasser or Sprudel.",
        },
      ],
    },
    {
      heading: "Obst und Gemüse",
      blocks: [
        {
          type: "table",
          caption: "Fruit and vegetables",
          head: ["German", "English"],
          rows: [
            ["der Apfel", "the apple"],
            ["die Banane", "the banana"],
            ["die Orange", "the orange"],
            ["die Erdbeere", "the strawberry"],
            ["die Tomate", "the tomato"],
            ["die Kartoffel", "the potato"],
            ["die Gurke", "the cucumber"],
            ["die Karotte", "the carrot"],
            ["der Salat", "the lettuce, the salad"],
            ["die Zwiebel", "the onion"],
          ],
        },
        {
          type: "example",
          de: "Ich esse gern Obst und Gemüse.",
          en: "I like eating fruit and vegetables.",
        },
        {
          type: "example",
          de: "Zum Frühstück esse ich Brot mit Käse.",
          en: "For breakfast I eat bread with cheese.",
        },
        {
          type: "tip",
          text: "The meals: das Frühstück (breakfast), das Mittagessen (lunch), das Abendessen (dinner). essen is to eat, trinken is to drink.",
        },
      ],
    },
  ],
  vocab: [
    { id: "das-brot", de: "das Brot", en: "the bread", part: "noun n.", plural: "die Brote", audio: true },
    { id: "die-butter", de: "die Butter", en: "the butter", part: "noun f.", plural: "-", audio: true },
    { id: "der-kaese", de: "der Käse", en: "the cheese", part: "noun m.", plural: "die Käsesorten", audio: true },
    { id: "die-wurst", de: "die Wurst", en: "the sausage", part: "noun f.", plural: "die Würste", audio: true },
    { id: "das-ei", de: "das Ei", en: "the egg", part: "noun n.", plural: "die Eier", audio: true },
    { id: "das-wasser", de: "das Wasser", en: "the water", part: "noun n.", plural: "-", audio: true },
    { id: "der-kaffee", de: "der Kaffee", en: "the coffee", part: "noun m.", plural: "die Kaffees", audio: true },
    { id: "der-tee", de: "der Tee", en: "the tea", part: "noun m.", plural: "die Tees", audio: true },
    { id: "der-saft", de: "der Saft", en: "the juice", part: "noun m.", plural: "die Säfte", audio: true },
    { id: "die-milch", de: "die Milch", en: "the milk", part: "noun f.", plural: "-", audio: true },
    { id: "der-apfel", de: "der Apfel", en: "the apple", part: "noun m.", plural: "die Äpfel", audio: true },
    { id: "die-banane", de: "die Banane", en: "the banana", part: "noun f.", plural: "die Bananen", audio: true },
    { id: "die-tomate", de: "die Tomate", en: "the tomato", part: "noun f.", plural: "die Tomaten", audio: true },
    { id: "die-kartoffel", de: "die Kartoffel", en: "the potato", part: "noun f.", plural: "die Kartoffeln", audio: true },
    { id: "essen", de: "essen", en: "to eat", part: "verb", audio: true },
    { id: "trinken", de: "trinken", en: "to drink", part: "verb", audio: true },
    { id: "das-fruehstueck", de: "das Frühstück", en: "the breakfast", part: "noun n.", plural: "die Frühstücke", audio: true },
  ],
  exercises: [
    {
      id: "mc-getraenk",
      type: "multiple-choice",
      title: "Was trinkst du?",
      instruction: "Pick the drink.",
      prompt: "Which of these is a drink?",
      options: ["der Saft", "der Käse", "das Brot"],
      correctIndex: 0,
      explain: "der Saft (juice) is a drink; the others are food.",
    },
    {
      id: "listening-lebensmittel",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the word you heard.",
      prompt: "der Käse",
      options: ["der Käse", "der Reis", "die Wurst"],
      correctIndex: 0,
    },
    {
      id: "fill-lebensmittel",
      type: "fill-blank",
      title: "Essen und Trinken",
      instruction: "Complete the sentences.",
      sentence: "Ich ___ gern Brot. Ich ___ gern Tee.",
      blanks: [
        { answers: ["esse"], hint: "ich-form of essen" },
        { answers: ["trinke"], hint: "ich-form of trinken" },
      ],
    },
    {
      id: "matching-lebensmittel",
      type: "matching",
      title: "Lebensmittel",
      instruction: "Match each German word to its meaning.",
      pairs: [
        ["das Brot", "the bread"],
        ["die Milch", "the milk"],
        ["der Apfel", "the apple"],
        ["die Kartoffel", "the potato"],
        ["das Hähnchen", "the chicken"],
      ],
    },
    {
      id: "word-order-lebensmittel",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: I like drinking coffee.",
      chunks: ["Ich", "trinke", "gern", "Kaffee."],
      explain: "gern sits right after the verb.",
    },
    {
      id: "flashcard-lebensmittel",
      type: "flashcard",
      title: "Essenskarten",
      instruction: "Say the German word out loud before revealing.",
      items: [
        { front: "das Brot", back: "the bread", frontAudio: true },
        { front: "der Käse", back: "the cheese", frontAudio: true },
        { front: "das Ei", back: "the egg", frontAudio: true },
        { front: "das Wasser", back: "the water", frontAudio: true },
        { front: "der Kaffee", back: "the coffee", frontAudio: true },
        { front: "der Apfel", back: "the apple", frontAudio: true },
        { front: "die Banane", back: "the banana", frontAudio: true },
        { front: "die Tomate", back: "the tomato", frontAudio: true },
      ],
    },
  ],
};

const imRestaurant: Lesson = {
  id: "im-restaurant",
  title: "Im Restaurant",
  summary: "Ordering food and drinks; Ich möchte ... and the bill.",
  status: "ready",
  sections: [
    {
      heading: "Am Tisch",
      blocks: [
        {
          type: "paragraph",
          text: "möchten is the golden word for ordering: it means would like, and it is polite in every situation.",
        },
        {
          type: "table",
          caption: "Useful phrases",
          head: ["German", "English"],
          rows: [
            ["Die Speisekarte, bitte.", "The menu, please."],
            ["Ich möchte einen Kaffee, bitte.", "I would like a coffee, please."],
            ["Ich nehme die Suppe.", "I will take the soup."],
            ["Was möchten Sie?", "What would you like?"],
            ["Für mich bitte einen Tee.", "For me a tea, please."],
            ["Ich möchte zahlen.", "I would like to pay."],
            ["Die Rechnung, bitte.", "The bill, please."],
          ],
        },
        {
          type: "tip",
          text: "einen marks the accusative for masculine food and drinks: Ich möchte einen Kaffee. Feminine and neuter stay eine and ein.",
        },
      ],
    },
    {
      heading: "Bestellen",
      blocks: [
        {
          type: "example",
          de: "Kellner: Was möchten Sie? Gast: Ich möchte einen Tee und ein Brötchen.",
          en: "Waiter: What would you like? Guest: I would like a tea and a roll.",
        },
        {
          type: "example",
          de: "Ich nehme das Hähnchen mit Reis.",
          en: "I will have the chicken with rice.",
        },
        {
          type: "example",
          de: "Was empfehlen Sie?",
          en: "What do you recommend?",
        },
      ],
    },
    {
      heading: "Bezahlen",
      blocks: [
        {
          type: "example",
          de: "Zahlen bitte! Das macht zwölf Euro.",
          en: "The bill, please! That will be twelve euros.",
        },
        {
          type: "example",
          de: "Stimmt so. Danke schön!",
          en: "Keep the change. Thank you very much!",
        },
        {
          type: "tip",
          text: "Stimmt so means keep the change. Together or separately is getrennt oder zusammen.",
        },
      ],
    },
  ],
  vocab: [
    { id: "die-speisekarte", de: "die Speisekarte", en: "the menu", part: "noun f.", plural: "die Speisekarten", audio: true },
    { id: "die-rechnung", de: "die Rechnung", en: "the bill", part: "noun f.", plural: "die Rechnungen", audio: true },
    { id: "der-kellner", de: "der Kellner", en: "the waiter", part: "noun m.", plural: "die Kellner", audio: true },
    { id: "die-kellnerin", de: "die Kellnerin", en: "the waitress", part: "noun f.", plural: "die Kellnerinnen", audio: true },
    { id: "bestellen", de: "bestellen", en: "to order", part: "verb", audio: true },
    { id: "zahlen", de: "zahlen", en: "to pay", part: "verb", audio: true },
    { id: "empfehlen", de: "empfehlen", en: "to recommend", part: "verb", audio: true },
    { id: "der-tisch", de: "der Tisch", en: "the table", part: "noun m.", plural: "die Tische", audio: true },
    { id: "die-suppe", de: "die Suppe", en: "the soup", part: "noun f.", plural: "die Suppen", audio: true },
    { id: "das-broetchen", de: "das Brötchen", en: "the roll", part: "noun n.", plural: "die Brötchen", audio: true },
    { id: "ich-moechte", de: "Ich möchte ...", en: "I would like ...", part: "phrase", phrase: true, audio: true },
    { id: "ich-nehme", de: "Ich nehme ...", en: "I will take ...", part: "phrase", phrase: true, audio: true },
    { id: "stimmt-so", de: "Stimmt so.", en: "Keep the change.", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "mc-restaurant",
      type: "multiple-choice",
      title: "Bestellen",
      instruction: "Choose the polite order.",
      prompt: "You want a coffee. What do you say?",
      options: [
        "Ich möchte einen Kaffee, bitte.",
        "Ich bin Kaffee.",
        "Kaffee! Schnell!",
      ],
      correctIndex: 0,
      explain: "Ich möchte + accusative is the polite way to order.",
    },
    {
      id: "listening-restaurant",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the phrase you heard.",
      prompt: "Die Rechnung, bitte.",
      options: [
        "Die Rechnung, bitte.",
        "Die Speisekarte, bitte.",
        "Ich möchte zahlen.",
      ],
      correctIndex: 0,
    },
    {
      id: "fill-restaurant",
      type: "fill-blank",
      title: "Im Restaurant",
      instruction: "Complete the sentences.",
      sentence: "Ich möchte ___ Kaffee, bitte. ___ Rechnung, bitte.",
      blanks: [
        { answers: ["einen"], hint: "accusative, masculine" },
        { answers: ["Die"], hint: "definite article, feminine" },
      ],
    },
    {
      id: "matching-restaurant",
      type: "matching",
      title: "Sätze",
      instruction: "Match each German phrase to its meaning.",
      pairs: [
        ["Die Speisekarte, bitte.", "The menu, please."],
        ["Ich möchte zahlen.", "I would like to pay."],
        ["Was empfehlen Sie?", "What do you recommend?"],
        ["Stimmt so.", "Keep the change."],
        ["Was möchten Sie?", "What would you like?"],
      ],
    },
    {
      id: "word-order-restaurant",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: I would like a tea, please.",
      chunks: ["Ich", "möchte", "einen", "Tee,", "bitte."],
      explain: "möchte holds position two; bitte closes the order.",
    },
    {
      id: "flashcard-restaurant",
      type: "flashcard",
      title: "Restaurantkarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "Die Speisekarte, bitte.", back: "The menu, please.", frontAudio: true },
        { front: "Ich möchte einen Kaffee.", back: "I would like a coffee.", frontAudio: true },
        { front: "Ich nehme die Suppe.", back: "I will take the soup.", frontAudio: true },
        { front: "Die Rechnung, bitte.", back: "The bill, please.", frontAudio: true },
        { front: "Ich möchte zahlen.", back: "I would like to pay.", frontAudio: true },
        { front: "Stimmt so.", back: "Keep the change.", frontAudio: true },
      ],
    },
  ],
};

export const derAkkusativ: Lesson = {
  id: "der-akkusativ",
  title: "Der Akkusativ",
  summary:
    "The complete accusative for A1: why it exists, how articles and pronouns change, which verbs and prepositions demand it, and how to use it in sentences.",
  status: "ready",
  sections: [
    {
      heading: "Warum gibt es den Akkusativ?",
      blocks: [
        {
          type: "paragraph",
          text: "German has four cases, and the accusative (der Akkusativ, also der vierte Fall) is the case of the direct object: the person or thing that the action happens to. In Ich sehe den Mann, the seeing happens to the man. English shows this with word order; German shows it with the article. That is why German can move words around freely: the article, not the position, tells you who acts and who is acted on.",
        },
        {
          type: "paragraph",
          text: "The question word for the accusative is wen? or was? Wen siehst du? Den Mann. Was isst du? Das Brot. If a noun answers wen or was, it stands in the accusative. Learn to ask the question after every verb: it decides the case instantly.",
        },
        {
          type: "table",
          caption: "The four cases and their questions",
          head: ["Case", "Question", "Job", "Example"],
          rows: [
            ["Nominativ", "wer?", "subject, who acts", "Der Mann schläft."],
            ["Akkusativ", "wen? was?", "direct object, who is acted on", "Ich sehe den Mann."],
            ["Dativ", "wem?", "receiver, who benefits", "Ich gebe dem Mann ein Buch."],
            ["Genitiv", "wessen?", "possession (B1)", "das Auto des Mannes"],
          ],
        },
        {
          type: "tip",
          text: "The accusative is the easiest case: only the masculine changes. Learn the change once (der to den, ein to einen, kein to keinen) and the entire case is yours.",
        },
      ],
    },
    {
      heading: "Die Artikel im Akkusativ",
      blocks: [
        {
          type: "paragraph",
          text: "In the accusative, the masculine article changes and everything else stays the same: der becomes den, ein becomes einen, kein becomes keinen. Feminine, neuter, and plural keep their nominative forms.",
        },
        {
          type: "table",
          caption: "Articles in the accusative",
          head: ["Noun", "Nominative", "Accusative"],
          rows: [
            ["der Mann (m.)", "der Mann", "den Mann"],
            ["die Frau (f.)", "die Frau", "die Frau"],
            ["das Kind (n.)", "das Kind", "das Kind"],
            ["die Kinder (pl.)", "die Kinder", "die Kinder"],
            ["ein Mann", "ein Mann", "einen Mann"],
            ["eine Frau", "eine Frau", "eine Frau"],
            ["ein Kind", "ein Kind", "ein Kind"],
            ["kein Mann", "kein Mann", "keinen Mann"],
            ["keine Frau", "keine Frau", "keine Frau"],
            ["kein Kind", "kein Kind", "kein Kind"],
            ["keine Kinder", "keine Kinder", "keine Kinder"],
          ],
        },
        {
          type: "example",
          de: "Ich sehe den Mann. Ich kaufe einen Apfel. Ich habe keinen Bruder. Ich sehe die Frau, das Kind und die Kinder.",
          en: "The whole accusative table in five sentences.",
        },
        {
          type: "tip",
          text: "The possessive article changes exactly like ein: meinen Bruder, deinen Termin, seinen Koffer. The -en appears only on the masculine.",
        },
      ],
    },
    {
      heading: "Die Pronomen im Akkusativ",
      blocks: [
        {
          type: "paragraph",
          text: "Pronouns change in the accusative too: ich becomes mich, du becomes dich, and er becomes ihn. The pattern mirrors the articles: only the masculine third person changes visibly; sie, es, wir, ihr, and sie keep their form.",
        },
        {
          type: "table",
          caption: "Pronouns in the accusative",
          head: ["Person", "Nominative", "Accusative"],
          rows: [
            ["I", "ich", "mich"],
            ["you (informal)", "du", "dich"],
            ["he", "er", "ihn"],
            ["she", "sie", "sie"],
            ["it", "es", "es"],
            ["we", "wir", "uns"],
            ["you (plural)", "ihr", "euch"],
            ["they / you (formal)", "sie / Sie", "sie / Sie"],
          ],
        },
        {
          type: "example",
          de: "Sie kennt mich. Ich sehe ihn. Wir besuchen euch. Du kennst sie.",
          en: "Pronouns in the accusative.",
        },
        {
          type: "tip",
          text: "The pair to drill: er becomes ihn, and ihn is used exactly where er would be as subject. Der Kaffee ist gut. Ich trinke ihn. Der Mann ist nett. Ich kenne ihn.",
        },
      ],
    },
    {
      heading: "Verben mit Akkusativ",
      blocks: [
        {
          type: "paragraph",
          text: "Many everyday verbs always take the accusative. They are the verbs of getting and doing: haben, kaufen, essen, trinken, sehen, brauchen, suchen, finden, kennen, nehmen, möchten, machen, lesen, schreiben. Learn them as pairs: verb plus wen?",
        },
        {
          type: "table",
          caption: "The accusative verbs of A1",
          head: ["Verb", "Example"],
          rows: [
            ["haben", "Ich habe einen Bruder."],
            ["kaufen", "Ich kaufe den Apfel."],
            ["essen", "Sie isst das Brot."],
            ["trinken", "Wir trinken einen Kaffee."],
            ["sehen", "Ich sehe die Frau."],
            ["brauchen", "Er braucht einen Kaffee."],
            ["suchen", "Wir suchen den Schlüssel."],
            ["finden", "Ich finde das Buch."],
            ["kennen", "Sie kennt den Kellner."],
            ["nehmen", "Ich nehme die Suppe."],
            ["möchten", "Ich möchte einen Tee."],
            ["lesen", "Er liest die Zeitung."],
            ["schreiben", "Sie schreibt einen Brief."],
            ["machen", "Ich mache einen Termin."],
          ],
        },
        {
          type: "example",
          de: "Ich brauche einen Kaffee. Wir suchen den Schlüssel. Sie kennt den Kellner. Er liest die Zeitung.",
          en: "The accusative verb pattern: verb + wen? + object.",
        },
        {
          type: "tip",
          text: "The test that never fails: can you ask wen or was after the verb? Wen kaufst du? Den Apfel. Then the object is accusative. Every verb in this table passes the test.",
        },
      ],
    },
    {
      heading: "Präpositionen mit Akkusativ",
      blocks: [
        {
          type: "paragraph",
          text: "A small group of prepositions always demands the accusative: für (for), ohne (without), durch (through), um (around), gegen (against), bis (until). There is no choice here; these six are accusative, period.",
        },
        {
          type: "table",
          caption: "The accusative prepositions",
          head: ["Preposition", "Meaning", "Example"],
          rows: [
            ["für", "for", "Ein Geschenk für dich."],
            ["ohne", "without", "Ohne Zucker, bitte."],
            ["durch", "through", "Wir gehen durch den Park."],
            ["um", "around", "Wir fahren um die Stadt."],
            ["gegen", "against", "Das Mittel gegen Kopfschmerzen."],
            ["bis", "until", "Bis nächste Woche!"],
          ],
        },
        {
          type: "example",
          de: "Ein Geschenk für dich. Ohne den Schlüssel geht es nicht. Wir gehen durch den Park. Das Medikament gegen die Schmerzen.",
          en: "Prepositions in action, always with the accusative.",
        },
        {
          type: "tip",
          text: "Pair the preposition groups: für, ohne, durch, um, gegen take the accusative; mit, nach, aus, zu, von, bei take the dative. Learn them in two rows and never mix them again.",
        },
      ],
    },
    {
      heading: "Der Akkusativ nach wo? und wohin?",
      blocks: [
        {
          type: "paragraph",
          text: "The two-way prepositions (in, auf, an, unter, über, vor, hinter, neben, zwischen) switch between dative and accusative: the dative answers wo? (static location), the accusative answers wohin? (movement toward). This is the most tested rule in the A1 exam.",
        },
        {
          type: "table",
          caption: "wo? vs wohin?",
          head: ["wo? (dative)", "wohin? (accusative)"],
          rows: [
            ["Das Buch liegt auf dem Tisch.", "Ich lege das Buch auf den Tisch."],
            ["Die Lampe hängt an der Wand.", "Ich hänge die Lampe an die Wand."],
            ["Ich bin in der Küche.", "Ich gehe in die Küche."],
            ["Das Kind sitzt auf dem Stuhl.", "Ich setze das Kind auf den Stuhl."],
          ],
        },
        {
          type: "example",
          de: "Wo ist das Buch? Auf dem Tisch. Wohin legst du das Buch? Auf den Tisch.",
          en: "The question decides the case: wo asks dative, wohin asks accusative.",
        },
        {
          type: "tip",
          text: "Ask the question before the preposition: wo? or wohin? If the answer is a destination with movement, the object goes into the accusative: auf den Tisch, in die Küche, an die Wand.",
        },
      ],
    },
    {
      heading: "Der Akkusativ in festen Wendungen",
      blocks: [
        {
          type: "paragraph",
          text: "The accusative appears in fixed everyday phrases that the exam loves. The most important: es gibt (there is), einen Termin haben, einen Termin machen, eine Frage haben, einen Kaffee trinken. In es gibt, the object is ALWAYS accusative: Es gibt einen Park, Es gibt eine Apotheke, Es gibt ein Museum.",
        },
        {
          type: "table",
          caption: "Fixed accusative phrases",
          head: ["Phrase", "Example"],
          rows: [
            ["es gibt + Akkusativ", "Es gibt einen Park in der Stadt."],
            ["einen Termin haben", "Ich habe einen Termin beim Arzt."],
            ["einen Termin machen", "Ich möchte einen Termin machen."],
            ["eine Frage haben", "Ich habe eine Frage."],
            ["einen Kaffee trinken", "Ich trinke einen Kaffee."],
          ],
        },
        {
          type: "example",
          de: "Es gibt einen Park, eine Apotheke und ein Museum in dieser Straße.",
          en: "es gibt always takes the accusative, even with neuter: ein Museum.",
        },
        {
          type: "tip",
          text: "Es gibt is the German 'there is': the noun after it is always accusative. Es gibt einen Park (masculine accusative with -en) is the most common exam sentence in A1.",
        },
      ],
    },
    {
      heading: "Zwei Objekte: Akkusativ und Dativ",
      blocks: [
        {
          type: "paragraph",
          text: "Some verbs take two objects: a dative person (the receiver) and an accusative thing (what is given). The order is always: person first, thing second. Ich gebe dem Kind einen Apfel: the child (dative) receives the apple (accusative). With pronouns, the accusative pronoun comes first: Ich gebe ihm den Apfel, Ich gebe ihn dem Kind.",
        },
        {
          type: "table",
          caption: "Two objects",
          head: ["Pattern", "Example"],
          rows: [
            ["Dative person + accusative thing", "Ich gebe dem Kind einen Apfel."],
            ["Dative person + accusative thing", "Sie bringt dem Vater das Buch."],
            ["Pronoun accusative first", "Ich gebe ihn dem Kind."],
            ["Pronoun dative first", "Ich gebe ihm den Apfel."],
          ],
        },
        {
          type: "tip",
          text: "The receiver answers wem? and takes the dative; the thing answers was? and takes the accusative. Person first, thing second: dem Kind einen Apfel.",
        },
      ],
    },
    {
      heading: "Die häufigsten Akkusativ-Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: keeping der instead of den, forgetting the -en on einen, using ein instead of keinen in the negative, and mixing dative and accusative after two-way prepositions.",
        },
        {
          type: "table",
          caption: "The classic mistakes and the fix",
          head: ["Mistake", "Wrong", "Right", "Test"],
          rows: [
            ["der instead of den", "Ich sehe der Mann.", "Ich sehe den Mann.", "wen? -> den"],
            ["missing -en", "Ich habe ein Bruder.", "Ich habe einen Bruder.", "masculine accusative -> -en"],
            ["ein instead of kein", "Ich habe ein Bruder nicht.", "Ich habe keinen Bruder.", "negative noun -> kein"],
            ["wo/wohin mix", "Ich lege das Buch auf dem Tisch.", "Ich lege das Buch auf den Tisch.", "wohin? -> accusative"],
            ["forgetting ihn", "Der Kaffee ist gut. Ich trinke er.", "Ich trinke ihn.", "er -> ihn"],
          ],
        },
        {
          type: "tip",
          text: "One question before every object: wen oder was? The answer in the sentence must carry the accusative marker: den, einen, keinen, mich, dich, ihn.",
        },
      ],
    },
  ],
  vocab: [
    { id: "der-akkusativ", de: "der Akkusativ", en: "the accusative case", part: "noun m.", audio: true },
    { id: "das-direkte-objekt", de: "das direkte Objekt", en: "the direct object", part: "noun n.", plural: "die direkten Objekte", audio: true },
    { id: "kaufen", de: "kaufen", en: "to buy", part: "verb", audio: true },
    { id: "brauchen", de: "brauchen", en: "to need", part: "verb", audio: true },
    { id: "suchen", de: "suchen", en: "to look for", part: "verb", audio: true },
    { id: "finden", de: "finden", en: "to find", part: "verb", audio: true },
    { id: "nehmen", de: "nehmen", en: "to take", part: "verb", audio: true },
    { id: "kennen", de: "kennen", en: "to know (someone)", part: "verb", audio: true },
    { id: "den-mann", de: "den Mann", en: "the man (accusative)", part: "phrase", phrase: true, audio: true },
    { id: "einen-apfel", de: "einen Apfel", en: "an apple (accusative)", part: "phrase", phrase: true, audio: true },
    { id: "keinen-bruder", de: "keinen Bruder", en: "no brother (accusative)", part: "phrase", phrase: true, audio: true },
    { id: "mich", de: "mich", en: "me (accusative)", part: "pronoun", audio: true },
    { id: "ihn", de: "ihn", en: "him (accusative)", part: "pronoun", audio: true },
    { id: "fuer-dich", de: "für dich", en: "for you", part: "phrase", phrase: true, audio: true },
    { id: "ohne-zucker", de: "ohne Zucker", en: "without sugar", part: "phrase", phrase: true, audio: true },
    { id: "es-gibt", de: "es gibt", en: "there is / there are", part: "phrase", phrase: true, audio: true },
    { id: "den-schluessel", de: "den Schlüssel", en: "the key (accusative)", part: "phrase", phrase: true, audio: true },
    { id: "auf-den-tisch", de: "auf den Tisch", en: "onto the table (wohin)", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-wen-frage",
      type: "multiple-choice",
      title: "Übung 1: Die wen-Frage",
      instruction: "Choose the question for the accusative.",
      prompt: "Wen oder was? Das ist die Frage nach dem ...",
      options: ["Akkusativ", "Nominativ", "Dativ"],
      correctIndex: 0,
      explain: "wen? was? asks for the direct object: the accusative.",
    },
    {
      id: "ex-artikel-1",
      type: "multiple-choice",
      title: "Übung 2: Der Artikel",
      instruction: "Choose the accusative article.",
      prompt: "Ich sehe ___ Mann.",
      options: ["den", "der", "dem"],
      correctIndex: 0,
      explain: "sehen takes the accusative: den Mann.",
    },
    {
      id: "ex-artikel-2",
      type: "multiple-choice",
      title: "Übung 3: Der Artikel",
      instruction: "Choose the accusative article.",
      prompt: "Ich kaufe ___ Apfel.",
      options: ["einen", "ein", "eine"],
      correctIndex: 0,
      explain: "Apfel is masculine, accusative: einen Apfel.",
    },
    {
      id: "ex-artikel-3",
      type: "multiple-choice",
      title: "Übung 4: Der Artikel",
      instruction: "Choose the accusative article.",
      prompt: "Ich habe ___ Bruder.",
      options: ["keinen", "kein", "keine"],
      correctIndex: 0,
      explain: "Masculine accusative negative: keinen Bruder.",
    },
    {
      id: "ex-pronomen",
      type: "fill-blank",
      title: "Übung 5: Die Pronomen",
      instruction: "Complete with the accusative pronoun.",
      sentence: "Sie kennt ___. (me) Ich sehe ___. (him) Wir besuchen ___. (you all) Du kennst ___. (her)",
      blanks: [
        { answers: ["mich"], hint: "ich -> mich" },
        { answers: ["ihn"], hint: "er -> ihn" },
        { answers: ["euch"], hint: "ihr -> euch" },
        { answers: ["sie"], hint: "sie stays sie" },
      ],
    },
    {
      id: "ex-verben",
      type: "fill-blank",
      title: "Übung 6: Verben mit Akkusativ",
      instruction: "Complete with the right object.",
      sentence: "Ich habe ___ Termin. Wir suchen ___ Schlüssel. Sie kennt ___ Kellner.",
      blanks: [
        { answers: ["einen"], hint: "Termin, masculine" },
        { answers: ["den"], hint: "Schlüssel, masculine" },
        { answers: ["den"], hint: "Kellner, masculine" },
      ],
    },
    {
      id: "ex-praepositionen",
      type: "multiple-choice",
      title: "Übung 7: Präpositionen",
      instruction: "Choose the correct preposition.",
      prompt: "Ein Geschenk ___ dich.",
      options: ["für", "mit", "bei"],
      correctIndex: 0,
      explain: "für takes the accusative: für dich.",
    },
    {
      id: "ex-praepositionen-2",
      type: "multiple-choice",
      title: "Übung 8: Präpositionen",
      instruction: "Choose the correct preposition.",
      prompt: "Wir gehen ___ den Park.",
      options: ["durch", "mit", "zu"],
      correctIndex: 0,
      explain: "durch takes the accusative: durch den Park.",
    },
    {
      id: "ex-wo-wohin",
      type: "multiple-choice",
      title: "Übung 9: wo oder wohin?",
      instruction: "Choose the correct form.",
      prompt: "Ich lege das Buch ___ den Tisch.",
      options: ["auf", "unter", "hinter"],
      correctIndex: 0,
      explain: "The movement phrase: auf den Tisch (accusative).",
    },
    {
      id: "ex-wo-wohin-2",
      type: "multiple-choice",
      title: "Übung 10: wo oder wohin?",
      instruction: "Choose the correct case.",
      prompt: "Das Buch liegt auf ___ Tisch.",
      options: ["dem", "den", "der"],
      correctIndex: 0,
      explain: "Static location takes the dative: auf dem Tisch.",
    },
    {
      id: "ex-es-gibt",
      type: "fill-blank",
      title: "Übung 11: es gibt",
      instruction: "Complete with the accusative article.",
      sentence: "Es gibt ___ Park. (a) Es gibt ___ Apotheke. (a) Es gibt ___ Museum. (a)",
      blanks: [
        { answers: ["einen"], hint: "masculine" },
        { answers: ["eine"], hint: "feminine" },
        { answers: ["ein"], hint: "neuter" },
      ],
    },
    {
      id: "ex-zwei-objekte",
      type: "multiple-choice",
      title: "Übung 12: Zwei Objekte",
      instruction: "Choose the correct word order.",
      prompt: "Ich gebe ...",
      options: ["dem Kind einen Apfel", "einen Apfel dem Kind", "den Apfel dem Kind"],
      correctIndex: 0,
      explain: "Dative person first, accusative thing second.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 13: Hören",
      instruction: "Play the audio and pick the phrase you heard.",
      prompt: "einen Kaffee",
      options: ["einen Kaffee", "ein Kaffee", "der Kaffee"],
      correctIndex: 0,
      explain: "The accusative masculine: einen Kaffee.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 14: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Ich kenne den Kellner.",
      options: ["Ich kenne den Kellner.", "Ich kenne der Kellner.", "Ich kenne einen Kellner."],
      correctIndex: 0,
      explain: "The known waiter: den Kellner.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 15: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Ich habe einen Bruder.", "Ich habe ein Bruder.", "Ich habe einer Bruder."],
      correctIndex: 0,
      explain: "Masculine accusative: einen Bruder.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 16: Der Satz",
      instruction: "Build the sentence: I am buying a new computer.",
      chunks: ["Ich", "kaufe", "einen", "neuen", "Computer."],
      explain: "The accusative object follows the verb.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 17: Der Satz",
      instruction: "Build the sentence: There is a park in the city.",
      chunks: ["Es", "gibt", "einen", "Park", "in", "der", "Stadt."],
      explain: "es gibt always takes the accusative.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 18: Akkusativkarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "den Mann", back: "the man (accusative)", frontAudio: true },
        { front: "einen Apfel", back: "an apple (accusative)", frontAudio: true },
        { front: "keinen Bruder", back: "no brother (accusative)", frontAudio: true },
        { front: "mich", back: "me (accusative)", frontAudio: true },
        { front: "ihn", back: "him (accusative)", frontAudio: true },
        { front: "für dich", back: "for you", frontAudio: true },
        { front: "ohne Zucker", back: "without sugar", frontAudio: true },
        { front: "durch den Park", back: "through the park", frontAudio: true },
        { front: "auf den Tisch", back: "onto the table", frontAudio: true },
        { front: "es gibt einen Park", back: "there is a park", frontAudio: true },
        { front: "den Schlüssel", back: "the key (accusative)", frontAudio: true },
        { front: "einen Termin", back: "an appointment", frontAudio: true },
      ],
    },
  ],
};

const modalverben: Lesson = {
  id: "modalverben",
  title: "Modalverben: können, möchten, wollen, müssen",
  summary: "Modal verbs in the present tense with the infinitive at the end.",
  status: "ready",
  sections: [
    {
      heading: "Die Modalverben",
      blocks: [
        {
          type: "paragraph",
          text: "Modal verbs say how something happens: whether you can, want to, would like to, or must. They always travel with a second verb, the infinitive, which waits at the end of the sentence.",
        },
        {
          type: "table",
          caption: "The four core modals",
          head: ["Modal", "Meaning"],
          rows: [
            ["können", "can, to be able to"],
            ["möchten", "would like to"],
            ["wollen", "to want to"],
            ["müssen", "must, to have to"],
            ["dürfen", "may, to be allowed to"],
            ["sollen", "should (recognition)"],
          ],
        },
        {
          type: "tip",
          text: "möchten looks like a Konjunktiv but is used as a normal present: Ich möchte einen Kaffee.",
        },
      ],
    },
    {
      heading: "Die Konjugation",
      blocks: [
        {
          type: "table",
          caption: "Present tense",
          head: ["Person", "können", "möchten", "wollen", "müssen"],
          rows: [
            ["ich", "kann", "möchte", "will", "muss"],
            ["du", "kannst", "möchtest", "willst", "musst"],
            ["er / sie / es", "kann", "möchte", "will", "muss"],
            ["wir", "können", "möchten", "wollen", "müssen"],
            ["ihr", "könnt", "möchtet", "wollt", "müsst"],
            ["sie / Sie", "können", "möchten", "wollen", "müssen"],
          ],
        },
        {
          type: "tip",
          text: "Notice the pattern: ich and er share the same form (kann, möchte, will, muss). Only du and ihr get endings.",
        },
      ],
    },
    {
      heading: "Der Satzbau",
      blocks: [
        {
          type: "paragraph",
          text: "The modal verb is conjugated and stands in position two. The main verb goes, in the infinitive, to the very end.",
        },
        {
          type: "example",
          de: "Ich kann gut kochen.",
          en: "I can cook well.",
        },
        {
          type: "example",
          de: "Wir möchten heute Abend essen gehen.",
          en: "We would like to go out to eat tonight.",
        },
        {
          type: "example",
          de: "Er muss morgen früh aufstehen.",
          en: "He has to get up early tomorrow.",
        },
        {
          type: "example",
          de: "Ich will Deutsch lernen.",
          en: "I want to learn German.",
        },
      ],
    },
  ],
  vocab: [
    { id: "koennen", de: "können", en: "can, to be able to", part: "verb", audio: true },
    { id: "moechten", de: "möchten", en: "would like to", part: "verb", audio: true },
    { id: "wollen", de: "wollen", en: "to want to", part: "verb", audio: true },
    { id: "muessen", de: "müssen", en: "must, to have to", part: "verb", audio: true },
    { id: "duerfen", de: "dürfen", en: "may, to be allowed to", part: "verb", audio: true },
    { id: "sollen", de: "sollen", en: "should", part: "verb", audio: true },
    { id: "ich-kann", de: "ich kann", en: "I can", part: "phrase", phrase: true, audio: true },
    { id: "du-kannst", de: "du kannst", en: "you can", part: "phrase", phrase: true, audio: true },
    { id: "ich-moechte", de: "ich möchte", en: "I would like", part: "phrase", phrase: true, audio: true },
    { id: "ich-muss", de: "ich muss", en: "I must", part: "phrase", phrase: true, audio: true },
    { id: "kochen", de: "kochen", en: "to cook", part: "verb", audio: true },
    { id: "aufstehen", de: "aufstehen", en: "to get up", part: "verb", audio: true },
  ],
  exercises: [
    {
      id: "mc-modalverben",
      type: "multiple-choice",
      title: "Die Form",
      instruction: "Choose the correct form.",
      prompt: "___ du schwimmen?",
      options: ["Kannst", "Kann", "Können"],
      correctIndex: 0,
      explain: "du takes kannst.",
    },
    {
      id: "listening-modalverben",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Ich möchte einen Kaffee trinken.",
      options: [
        "Ich möchte einen Kaffee trinken.",
        "Ich muss einen Kaffee trinken.",
        "Ich kann einen Kaffee trinken.",
      ],
      correctIndex: 0,
    },
    {
      id: "fill-modalverben",
      type: "fill-blank",
      title: "Die Lücke",
      instruction: "Complete with the right modal form.",
      sentence: "Ich ___ gut schwimmen. Du ___ einen Kaffee? Er ___ morgen arbeiten.",
      blanks: [
        { answers: ["kann"], hint: "ability, ich" },
        { answers: ["möchtest"], hint: "would like, du" },
        { answers: ["muss"], hint: "obligation, er" },
      ],
    },
    {
      id: "matching-modalverben",
      type: "matching",
      title: "Modal und Person",
      instruction: "Match each person to the correct form of können.",
      pairs: [
        ["ich", "kann"],
        ["du", "kannst"],
        ["wir", "können"],
        ["ihr", "könnt"],
        ["er", "kann"],
      ],
    },
    {
      id: "word-order-modalverben",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: I would like to drink a coffee.",
      chunks: ["Ich", "möchte", "einen", "Kaffee", "trinken."],
      explain: "The modal is second; the infinitive closes the sentence.",
    },
    {
      id: "flashcard-modalverben",
      type: "flashcard",
      title: "Modalverbenkarten",
      instruction: "Say the German form out loud before revealing.",
      items: [
        { front: "ich kann", back: "I can", frontAudio: true },
        { front: "du kannst", back: "you can", frontAudio: true },
        { front: "ich möchte", back: "I would like", frontAudio: true },
        { front: "du möchtest", back: "you would like", frontAudio: true },
        { front: "ich will", back: "I want", frontAudio: true },
        { front: "ich muss", back: "I must", frontAudio: true },
      ],
    },
  ],
};

const pluralBildung: Lesson = {
  id: "plural-bildung",
  title: "Der Plural",
  summary: "Plural patterns: -e, -er, -n, -s, no change, and umlauts.",
  status: "ready",
  sections: [
    {
      heading: "Die Pluralmuster",
      blocks: [
        {
          type: "paragraph",
          text: "German plurals follow five main patterns. There is no single rule, so always learn a noun with its plural. The plural article is always die.",
        },
        {
          type: "table",
          caption: "The five patterns",
          head: ["Pattern", "Example", "Plural"],
          rows: [
            ["no change (sometimes with umlaut)", "der Vater", "die Väter"],
            ["+ -e (sometimes with umlaut)", "der Tisch", "die Tische"],
            ["+ -er (often with umlaut)", "das Kind", "die Kinder"],
            ["+ -n or -en", "die Frau", "die Frauen"],
            ["+ -s", "das Auto", "die Autos"],
          ],
        },
        {
          type: "tip",
          text: "Umlauts appear on a, o, u: der Apfel -> die Äpfel, der Sohn -> die Söhne, das Buch -> die Bücher.",
        },
      ],
    },
    {
      heading: "Wichtige Plurale",
      blocks: [
        {
          type: "table",
          caption: "Common nouns with plurals",
          head: ["Singular", "Plural", "English"],
          rows: [
            ["der Mann", "die Männer", "men"],
            ["die Mutter", "die Mütter", "mothers"],
            ["das Buch", "die Bücher", "books"],
            ["das Haus", "die Häuser", "houses"],
            ["der Student", "die Studenten", "students"],
            ["das Kind", "die Kinder", "children"],
            ["der Apfel", "die Äpfel", "apples"],
            ["die Banane", "die Bananen", "bananas"],
          ],
        },
      ],
    },
    {
      heading: "Kein Plural für ein",
      blocks: [
        {
          type: "paragraph",
          text: "ein has no plural. To say not any or no + plural, German uses keine.",
        },
        {
          type: "example",
          de: "Ich habe keine Äpfel.",
          en: "I have no apples.",
        },
        {
          type: "example",
          de: "Wir haben keine Kinder.",
          en: "We have no children.",
        },
      ],
    },
  ],
  vocab: [
    { id: "der-tisch", de: "der Tisch", en: "the table", part: "noun m.", plural: "die Tische", audio: true },
    { id: "die-frau", de: "die Frau", en: "the woman", part: "noun f.", plural: "die Frauen", audio: true },
    { id: "das-auto", de: "das Auto", en: "the car", part: "noun n.", plural: "die Autos", audio: true },
    { id: "der-mann", de: "der Mann", en: "the man", part: "noun m.", plural: "die Männer", audio: true },
    { id: "die-mutter", de: "die Mutter", en: "the mother", part: "noun f.", plural: "die Mütter", audio: true },
    { id: "das-buch", de: "das Buch", en: "the book", part: "noun n.", plural: "die Bücher", audio: true },
    { id: "das-haus", de: "das Haus", en: "the house", part: "noun n.", plural: "die Häuser", audio: true },
    { id: "der-student", de: "der Student", en: "the student", part: "noun m.", plural: "die Studenten", audio: true },
    { id: "das-kind", de: "das Kind", en: "the child", part: "noun n.", plural: "die Kinder", audio: true },
    { id: "der-sohn", de: "der Sohn", en: "the son", part: "noun m.", plural: "die Söhne", audio: true },
  ],
  exercises: [
    {
      id: "mc-plural",
      type: "multiple-choice",
      title: "Der Plural",
      instruction: "Choose the correct plural.",
      prompt: "Der Plural von der Apfel ist ...",
      options: ["die Äpfel", "die Apfelen", "die Apfels"],
      correctIndex: 0,
      explain: "der Apfel takes the no-change pattern with umlaut: die Äpfel.",
    },
    {
      id: "listening-plural",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the word you heard.",
      prompt: "die Bücher",
      options: ["die Bücher", "das Buch", "die Buchen"],
      correctIndex: 0,
    },
    {
      id: "fill-plural",
      type: "fill-blank",
      title: "Plural bilden",
      instruction: "Write the plural forms.",
      sentence: "der Mann -> die ___, das Auto -> die ___.",
      blanks: [
        { answers: ["Männer"], hint: "with umlaut" },
        { answers: ["Autos"], hint: "-s pattern" },
      ],
    },
    {
      id: "matching-plural",
      type: "matching",
      title: "Singular und Plural",
      instruction: "Match each noun to its plural.",
      pairs: [
        ["der Tisch", "die Tische"],
        ["die Frau", "die Frauen"],
        ["das Auto", "die Autos"],
        ["das Kind", "die Kinder"],
        ["der Sohn", "die Söhne"],
      ],
    },
    {
      id: "word-order-plural",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: The apples are good.",
      chunks: ["Die", "Äpfel", "sind", "gut."],
      explain: "The plural article die leads; the verb stays second.",
    },
    {
      id: "flashcard-plural",
      type: "flashcard",
      title: "Pluralkarten",
      instruction: "Say the plural out loud before revealing.",
      items: [
        { front: "der Tisch", back: "die Tische", frontAudio: true },
        { front: "die Frau", back: "die Frauen", frontAudio: true },
        { front: "das Auto", back: "die Autos", frontAudio: true },
        { front: "der Mann", back: "die Männer", frontAudio: true },
        { front: "das Buch", back: "die Bücher", frontAudio: true },
        { front: "das Kind", back: "die Kinder", frontAudio: true },
      ],
    },
  ],
};

const preiseUndBezahlen: Lesson = {
  id: "preise-und-bezahlen",
  title: "Preise und Bezahlen",
  summary: "Prices in euros, paying, and restaurant numbers.",
  status: "ready",
  sections: [
    {
      heading: "Preise",
      blocks: [
        {
          type: "paragraph",
          text: "Prices are read with a comma: 2,50 Euro is zwei fünfzig. The comma is the decimal separator, and it is spoken as a small pause.",
        },
        {
          type: "example",
          de: "Was kostet das? Das kostet 9,99 Euro.",
          en: "How much is that? That costs 9.99 euros.",
        },
        {
          type: "example",
          de: "Wie viel kostet das Brot? Drei Euro zwanzig.",
          en: "How much is the bread? Three euros twenty.",
        },
        {
          type: "tip",
          text: "Euro stays the same in the plural after numbers: 10 Euro, 25 Euro. cents are die Cent.",
        },
      ],
    },
    {
      heading: "Bezahlen",
      blocks: [
        {
          type: "table",
          caption: "Paying",
          head: ["German", "English"],
          rows: [
            ["bar bezahlen", "to pay cash"],
            ["mit Karte zahlen", "to pay by card"],
            ["das Bargeld", "the cash"],
            ["die Kreditkarte", "the credit card"],
            ["der Cent", "the cent"],
            ["das Geld", "the money"],
            ["teuer", "expensive"],
            ["billig", "cheap"],
          ],
        },
        {
          type: "example",
          de: "Zahlen Sie bar oder mit Karte? Mit Karte, bitte.",
          en: "Are you paying cash or by card? By card, please.",
        },
        {
          type: "example",
          de: "Das ist aber teuer! Das ist billig.",
          en: "That is expensive! That is cheap.",
        },
      ],
    },
    {
      heading: "Der Dialog",
      blocks: [
        {
          type: "example",
          de: "Gast: Was kostet das Brot? Verkäufer: Drei Euro zwanzig. Gast: Hier bitte. Verkäufer: Danke schön!",
          en: "Customer: How much is the bread? Seller: Three euros twenty. Customer: Here you go. Seller: Thank you!",
        },
        {
          type: "tip",
          text: "Hier, bitte. is the natural way to hand over money.",
        },
      ],
    },
  ],
  vocab: [
    { id: "kosten", de: "kosten", en: "to cost", part: "verb", audio: true },
    { id: "der-preis", de: "der Preis", en: "the price", part: "noun m.", plural: "die Preise", audio: true },
    { id: "bezahlen", de: "bezahlen", en: "to pay", part: "verb", audio: true },
    { id: "das-geld", de: "das Geld", en: "the money", part: "noun n.", plural: "-", audio: true },
    { id: "das-bargeld", de: "das Bargeld", en: "the cash", part: "noun n.", plural: "-", audio: true },
    { id: "die-karte", de: "die Karte", en: "the card", part: "noun f.", plural: "die Karten", audio: true },
    { id: "der-cent", de: "der Cent", en: "the cent", part: "noun m.", plural: "die Cent", audio: true },
    { id: "teuer", de: "teuer", en: "expensive", part: "adjective", audio: true },
    { id: "billig", de: "billig", en: "cheap", part: "adjective", audio: true },
    { id: "bar", de: "bar", en: "cash (adverb)", part: "adverb", audio: true },
    { id: "was-kostet", de: "Was kostet das?", en: "How much is that?", part: "phrase", phrase: true, audio: true },
    { id: "wie-viel-kostet", de: "Wie viel kostet das Brot?", en: "How much is the bread?", part: "phrase", phrase: true, audio: true },
    { id: "hier-bitte", de: "Hier, bitte.", en: "Here you go.", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "mc-preise",
      type: "multiple-choice",
      title: "Der Preis",
      instruction: "Read the price correctly.",
      prompt: "19,99 Euro",
      options: ["neunzehn neunundneunzig", "neunzehn komma neunundneunzig", "neunundneunzig Euro"],
      correctIndex: 0,
      explain: "After the comma, the cents are read as one number: neun neunundneunzig.",
    },
    {
      id: "listening-preise",
      type: "listening",
      title: "Was kostet es?",
      instruction: "Play the audio and pick the price you heard.",
      prompt: "drei Euro zwanzig",
      options: ["drei Euro zwanzig", "drei Euro zwei", "zwanzig Euro drei"],
      correctIndex: 0,
    },
    {
      id: "fill-preise",
      type: "fill-blank",
      title: "Im Geschäft",
      instruction: "Complete the questions.",
      sentence: "___ kostet das Brot? Wie ___ kostet das?",
      blanks: [
        { answers: ["Was"], hint: "what costs" },
        { answers: ["viel"], hint: "how much" },
      ],
    },
    {
      id: "matching-preise",
      type: "matching",
      title: "Preise",
      instruction: "Match each price to the correct number.",
      pairs: [
        ["zwei fünfzig", "2,50 €"],
        ["zehn Euro", "10,00 €"],
        ["neunzehn neunundneunzig", "19,99 €"],
        ["fünf Cent", "0,05 €"],
        ["drei Euro zwanzig", "3,20 €"],
      ],
    },
    {
      id: "word-order-preise",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: The bread costs three euros.",
      chunks: ["Das", "Brot", "kostet", "drei", "Euro."],
      explain: "kostet sits in second position.",
    },
    {
      id: "flashcard-preise",
      type: "flashcard",
      title: "Preiskarten",
      instruction: "Say the German price out loud before revealing.",
      items: [
        { front: "Was kostet das?", back: "How much is that?", frontAudio: true },
        { front: "Das kostet 10 Euro.", back: "That costs 10 euros.", frontAudio: true },
        { front: "bar bezahlen", back: "to pay cash", frontAudio: true },
        { front: "mit Karte zahlen", back: "to pay by card", frontAudio: true },
        { front: "teuer", back: "expensive", frontAudio: true },
        { front: "billig", back: "cheap", frontAudio: true },
      ],
    },
  ],
};

export const essenUndTrinken: Unit = {
  id: "essen-und-trinken",
  title: "Essen und Trinken",
  theme: "Food and drink",
  lessons: [
    lebensmittel,
    imRestaurant,
    derAkkusativ,
    modalverben,
    pluralBildung,
    preiseUndBezahlen,
  ],
};