import type { Lesson, Unit } from "../../schema";

const meineFamilie: Lesson = {
  id: "meine-familie",
  title: "Meine Familie",
  summary: "Family members and simple sentences about them.",
  status: "ready",
  sections: [
    {
      heading: "Die Familie",
      blocks: [
        {
          type: "paragraph",
          text: "Family words are among the first you need. Notice the articles: der for male family members, die for female ones, das for the child.",
        },
        {
          type: "table",
          caption: "Family members",
          head: ["German", "English"],
          rows: [
            ["die Familie", "the family"],
            ["der Vater", "the father"],
            ["die Mutter", "the mother"],
            ["die Eltern", "the parents"],
            ["der Sohn", "the son"],
            ["die Tochter", "the daughter"],
            ["die Kinder", "the children"],
            ["der Bruder", "the brother"],
            ["die Schwester", "the sister"],
            ["die Geschwister", "the siblings"],
            ["der Opa / der Großvater", "the grandpa / grandfather"],
            ["die Oma / die Großmutter", "the grandma / grandmother"],
            ["der Onkel", "the uncle"],
            ["die Tante", "the aunt"],
            ["der Cousin", "the cousin (male)"],
            ["die Cousine", "the cousin (female)"],
          ],
        },
        {
          type: "tip",
          text: "die Eltern and die Kinder are plurals but mean 'the parents' and 'the children' as one group. Die Geschwister is plural only, there is no single 'Geschwister'.",
        },
      ],
    },
    {
      heading: "Über die Familie sprechen",
      blocks: [
        {
          type: "paragraph",
          text: "haben takes the accusative: masculine nouns get einen, feminine and neuter keep eine and ein.",
        },
        {
          type: "example",
          de: "Ich habe einen Bruder und eine Schwester.",
          en: "I have a brother and a sister.",
        },
        {
          type: "example",
          de: "Meine Eltern wohnen in Hamburg.",
          en: "My parents live in Hamburg.",
        },
        {
          type: "example",
          de: "Er ist mein Vater. Sie ist meine Mutter.",
          en: "He is my father. She is my mother.",
        },
        {
          type: "tip",
          text: "my in German is mein + the noun: mein Vater, meine Mutter, mein Kind. The ending follows the noun's gender, not the owner's.",
        },
      ],
    },
  ],
  vocab: [
    { id: "die-familie", de: "die Familie", en: "the family", part: "noun f.", plural: "die Familien", audio: true },
    { id: "der-vater", de: "der Vater", en: "the father", part: "noun m.", plural: "die Väter", audio: true },
    { id: "die-mutter", de: "die Mutter", en: "the mother", part: "noun f.", plural: "die Mütter", audio: true },
    { id: "die-eltern", de: "die Eltern", en: "the parents", part: "noun pl.", plural: "-", audio: true },
    { id: "der-sohn", de: "der Sohn", en: "the son", part: "noun m.", plural: "die Söhne", audio: true },
    { id: "die-tochter", de: "die Tochter", en: "the daughter", part: "noun f.", plural: "die Töchter", audio: true },
    { id: "die-kinder", de: "die Kinder", en: "the children", part: "noun pl.", plural: "-", audio: true },
    { id: "die-schwester", de: "die Schwester", en: "the sister", part: "noun f.", plural: "die Schwestern", audio: true },
    { id: "der-opa", de: "der Opa", en: "the grandpa", part: "noun m.", plural: "die Opas", audio: true },
    { id: "die-oma", de: "die Oma", en: "the grandma", part: "noun f.", plural: "die Omas", audio: true },
    { id: "der-onkel", de: "der Onkel", en: "the uncle", part: "noun m.", plural: "die Onkel", audio: true },
    { id: "die-tante", de: "die Tante", en: "the aunt", part: "noun f.", plural: "die Tanten", audio: true },
    { id: "die-cousine", de: "die Cousine", en: "the cousin (female)", part: "noun f.", plural: "die Cousinen", audio: true },
    { id: "haben", de: "haben", en: "to have", part: "verb", audio: true },
  ],
  exercises: [
    {
      id: "mc-familie",
      type: "multiple-choice",
      title: "Wer ist das?",
      instruction: "Choose the family member that fits.",
      prompt: "Die Schwester von meiner Mutter ist meine ...",
      options: ["Tante", "Cousine", "Oma"],
      correctIndex: 0,
      explain: "Your mother's sister is your aunt: die Tante.",
    },
    {
      id: "listening-familie",
      type: "listening",
      title: "Wer ist das?",
      instruction: "Play the audio and pick the word you heard.",
      prompt: "die Eltern",
      options: ["die Eltern", "die Kinder", "die Geschwister"],
      correctIndex: 0,
    },
    {
      id: "fill-familie",
      type: "fill-blank",
      title: "Meine Familie",
      instruction: "Complete the sentences about the family.",
      sentence: "Ich habe ___ Bruder und ___ Schwester.",
      blanks: [
        { answers: ["einen"], hint: "accusative, masculine" },
        { answers: ["eine"], hint: "accusative, feminine" },
      ],
    },
    {
      id: "matching-familie",
      type: "matching",
      title: "Familienmitglieder",
      instruction: "Match each German family word to its meaning.",
      pairs: [
        ["die Mutter", "the mother"],
        ["der Vater", "the father"],
        ["die Tochter", "the daughter"],
        ["der Onkel", "the uncle"],
        ["die Oma", "the grandma"],
      ],
    },
    {
      id: "word-order-familie",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: My parents live in Hamburg.",
      chunks: ["Meine", "Eltern", "wohnen", "in", "Hamburg."],
      explain: "The verb wohnen stays in second position.",
    },
    {
      id: "flashcard-familie",
      type: "flashcard",
      title: "Familienkarten",
      instruction: "Say the German word out loud before revealing.",
      items: [
        { front: "die Familie", back: "the family", frontAudio: true },
        { front: "der Vater", back: "the father", frontAudio: true },
        { front: "die Mutter", back: "the mother", frontAudio: true },
        { front: "der Bruder", back: "the brother", frontAudio: true },
        { front: "die Schwester", back: "the sister", frontAudio: true },
        { front: "die Oma", back: "the grandma", frontAudio: true },
        { front: "die Tante", back: "the aunt", frontAudio: true },
        { front: "das Kind", back: "the child", frontAudio: true },
      ],
    },
  ],
};

const possessivartikel: Lesson = {
  id: "possessivartikel",
  title: "Mein, dein, sein",
  summary: "Possessive determiners in the nominative and accusative.",
  status: "ready",
  sections: [
    {
      heading: "Wem gehört was?",
      blocks: [
        {
          type: "paragraph",
          text: "The possessive determiner tells you who owns something. It depends on the owner, not on the thing being owned.",
        },
        {
          type: "table",
          caption: "Possessives by owner",
          head: ["Owner", "Possessive"],
          rows: [
            ["ich", "mein"],
            ["du", "dein"],
            ["er / es", "sein"],
            ["sie (she)", "ihr"],
            ["wir", "unser"],
            ["ihr", "euer"],
            ["sie (they)", "ihr"],
            ["Sie (formal)", "Ihr"],
          ],
        },
        {
          type: "tip",
          text: "ihr has three jobs: her, their, and your (formal singular with a capital I: Ihr). Context decides.",
        },
      ],
    },
    {
      heading: "Die Endungen",
      blocks: [
        {
          type: "paragraph",
          text: "The possessive then takes the ending of the noun's gender: masculine gets nothing in the nominative, feminine gets -e, neuter nothing, plural -e.",
        },
        {
          type: "table",
          caption: "Nominative endings",
          head: ["Noun", "with mein"],
          rows: [
            ["der Bruder (m.)", "mein Bruder"],
            ["die Schwester (f.)", "meine Schwester"],
            ["das Kind (n.)", "mein Kind"],
            ["die Kinder (pl.)", "meine Kinder"],
          ],
        },
      ],
    },
    {
      heading: "Der Akkusativ",
      blocks: [
        {
          type: "paragraph",
          text: "In the accusative only the masculine ending changes: meinen. Everything else stays exactly as in the nominative.",
        },
        {
          type: "table",
          caption: "Accusative endings",
          head: ["Noun", "with mein"],
          rows: [
            ["der Bruder (m.)", "meinen Bruder"],
            ["die Schwester (f.)", "meine Schwester"],
            ["das Kind (n.)", "mein Kind"],
            ["die Kinder (pl.)", "meine Kinder"],
          ],
        },
        {
          type: "example",
          de: "Ich sehe meinen Bruder. Ich besuche meine Oma.",
          en: "I see my brother. I visit my grandma.",
        },
        {
          type: "tip",
          text: "Two steps: first pick the possessive by the owner (Anna -> ihr), then add the ending for the noun's gender and case (ihr Bruder, ihre Schwester).",
        },
      ],
    },
  ],
  vocab: [
    { id: "mein", de: "mein / meine", en: "my", part: "possessive", audio: true },
    { id: "dein", de: "dein / deine", en: "your (informal)", part: "possessive", audio: true },
    { id: "sein", de: "sein / seine", en: "his / its", part: "possessive", audio: true },
    { id: "ihr", de: "ihr / ihre", en: "her / their", part: "possessive", audio: true },
    { id: "unser", de: "unser / unsere", en: "our", part: "possessive", audio: true },
    { id: "euer", de: "euer / eure", en: "your (plural)", part: "possessive", audio: true },
    { id: "ihr-formal", de: "Ihr / Ihre", en: "your (formal)", part: "possessive", audio: true },
    { id: "meinen-bruder", de: "meinen Bruder", en: "my brother (accusative)", part: "phrase", phrase: true, audio: true },
    { id: "meine-schwester", de: "meine Schwester", en: "my sister", part: "phrase", phrase: true, audio: true },
    { id: "gehoeren", de: "gehören", en: "to belong to", part: "verb", audio: true },
  ],
  exercises: [
    {
      id: "mc-possessiv",
      type: "multiple-choice",
      title: "Wessen Bruder?",
      instruction: "Choose the correct possessive.",
      prompt: "Anna hat einen Bruder. ___ Bruder heißt Paul.",
      options: ["Ihr", "Sein", "Dein"],
      correctIndex: 0,
      explain: "Anna is she, so the possessive is ihr.",
    },
    {
      id: "listening-possessiv",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the phrase you heard.",
      prompt: "mein Bruder",
      options: ["mein Bruder", "meine Schwester", "mein Vater"],
      correctIndex: 0,
    },
    {
      id: "fill-possessiv",
      type: "fill-blank",
      title: "Die Endung",
      instruction: "Complete with the right possessive form.",
      sentence: "Ich habe eine Schwester. ___ Schwester heißt Mia. Er hat einen Bruder. ___ Bruder ist zehn.",
      blanks: [
        { answers: ["Meine"], hint: "mein + feminine ending" },
        { answers: ["Sein"], hint: "er -> sein" },
      ],
    },
    {
      id: "matching-possessiv",
      type: "matching",
      title: "Wem gehört was?",
      instruction: "Match each owner to their possessive.",
      pairs: [
        ["ich", "mein"],
        ["du", "dein"],
        ["er", "sein"],
        ["wir", "unser"],
        ["Sie", "Ihr"],
      ],
    },
    {
      id: "word-order-possessiv",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: My brother is called Paul.",
      chunks: ["Mein", "Bruder", "heißt", "Paul."],
      explain: "heißen stays in second position with the subject first.",
    },
    {
      id: "flashcard-possessiv",
      type: "flashcard",
      title: "Possessivkarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "mein Vater", back: "my father", frontAudio: true },
        { front: "meine Mutter", back: "my mother", frontAudio: true },
        { front: "mein Kind", back: "my child", frontAudio: true },
        { front: "meine Kinder", back: "my children", frontAudio: true },
        { front: "meinen Bruder", back: "my brother (accusative)", frontAudio: true },
        { front: "dein Buch", back: "your book", frontAudio: true },
      ],
    },
  ],
};

const personalpronomen: Lesson = {
  id: "personalpronomen",
  title: "Personalpronomen",
  summary: "Personal pronouns in the nominative and accusative.",
  status: "ready",
  sections: [
    {
      heading: "Wer? Der Nominativ",
      blocks: [
        {
          type: "table",
          caption: "Nominative pronouns",
          head: ["German", "English"],
          rows: [
            ["ich", "I"],
            ["du", "you (informal)"],
            ["er / sie / es", "he / she / it"],
            ["wir", "we"],
            ["ihr", "you (plural)"],
            ["sie", "they"],
            ["Sie", "you (formal)"],
          ],
        },
        {
          type: "paragraph",
          text: "Pronouns replace nouns, and the noun's gender decides which pronoun: der Vater becomes er, die Mutter becomes sie, das Kind becomes es.",
        },
        {
          type: "example",
          de: "Das ist mein Bruder. Er heißt Paul.",
          en: "This is my brother. He is called Paul.",
        },
        {
          type: "example",
          de: "Das ist meine Oma. Sie ist 80 Jahre alt.",
          en: "This is my grandma. She is 80 years old.",
        },
      ],
    },
    {
      heading: "Wen? Der Akkusativ",
      blocks: [
        {
          type: "table",
          caption: "Accusative pronouns",
          head: ["Nominative", "Accusative"],
          rows: [
            ["ich", "mich"],
            ["du", "dich"],
            ["er", "ihn"],
            ["sie", "sie"],
            ["es", "es"],
            ["wir", "uns"],
            ["ihr", "euch"],
            ["sie / Sie", "sie / Sie"],
          ],
        },
        {
          type: "paragraph",
          text: "Only er changes visibly in the accusative (ihn). sie, es, wir, ihr, and sie keep their form; ich and du become mich and dich.",
        },
        {
          type: "example",
          de: "Wo ist der Vater? Ich sehe ihn.",
          en: "Where is father? I see him.",
        },
        {
          type: "example",
          de: "Sie kennt mich. Wir besuchen euch.",
          en: "She knows me. We visit you (all).",
        },
        {
          type: "tip",
          text: "ihn is the accusative of er. Whenever you would say er about a noun, use ihn after the verb: Der Kaffee ist gut. Ich trinke ihn.",
        },
      ],
    },
  ],
  vocab: [
    { id: "ich", de: "ich", en: "I", part: "pronoun", audio: true },
    { id: "du", de: "du", en: "you (informal)", part: "pronoun", audio: true },
    { id: "er", de: "er", en: "he", part: "pronoun", audio: true },
    { id: "sie-she", de: "sie", en: "she", part: "pronoun", audio: true },
    { id: "es", de: "es", en: "it", part: "pronoun", audio: true },
    { id: "wir", de: "wir", en: "we", part: "pronoun", audio: true },
    { id: "mich", de: "mich", en: "me (accusative)", part: "pronoun", audio: true },
    { id: "dich", de: "dich", en: "you (accusative)", part: "pronoun", audio: true },
    { id: "ihn", de: "ihn", en: "him (accusative)", part: "pronoun", audio: true },
    { id: "uns", de: "uns", en: "us", part: "pronoun", audio: true },
    { id: "euch", de: "euch", en: "you all (accusative)", part: "pronoun", audio: true },
    { id: "kennen", de: "kennen", en: "to know (someone)", part: "verb", audio: true },
  ],
  exercises: [
    {
      id: "mc-pronomen-akk",
      type: "multiple-choice",
      title: "Wen siehst du?",
      instruction: "Choose the right accusative pronoun.",
      prompt: "Wo ist der Vater? Ich sehe ___.",
      options: ["ihn", "er", "ihm"],
      correctIndex: 0,
      explain: "After the verb, er becomes ihn.",
    },
    {
      id: "listening-pronomen",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the pronoun you heard.",
      prompt: "uns",
      options: ["uns", "euch", "ihn"],
      correctIndex: 0,
    },
    {
      id: "fill-pronomen",
      type: "fill-blank",
      title: "Das Kind",
      instruction: "Complete with the right pronoun.",
      sentence: "Das Kind schläft. Ich sehe ___. Wir haben einen Onkel. Wir besuchen ___.",
      blanks: [
        { answers: ["es"], hint: "das Kind -> es" },
        { answers: ["ihn"], hint: "der Onkel -> ihn" },
      ],
    },
    {
      id: "matching-pronomen",
      type: "matching",
      title: "Nominativ oder Akkusativ?",
      instruction: "Match each nominative pronoun to its accusative form.",
      pairs: [
        ["ich", "mich"],
        ["du", "dich"],
        ["er", "ihn"],
        ["wir", "uns"],
        ["ihr", "euch"],
      ],
    },
    {
      id: "word-order-pronomen",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: She knows me.",
      chunks: ["Sie", "kennt", "mich."],
      explain: "The verb kennt is second; the object follows.",
    },
    {
      id: "flashcard-pronomen",
      type: "flashcard",
      title: "Pronomenkarten",
      instruction: "Say the German pronoun out loud before revealing.",
      items: [
        { front: "ich", back: "I", frontAudio: true },
        { front: "du", back: "you (informal)", frontAudio: true },
        { front: "er", back: "he", frontAudio: true },
        { front: "mich", back: "me (accusative)", frontAudio: true },
        { front: "dich", back: "you (accusative)", frontAudio: true },
        { front: "ihn", back: "him (accusative)", frontAudio: true },
        { front: "uns", back: "us", frontAudio: true },
      ],
    },
  ],
};

const hobbysUndFreunde: Lesson = {
  id: "hobbys-und-freunde",
  title: "Hobbys und Freunde",
  summary: "Talking about hobbies and friends; gern and lieber.",
  status: "ready",
  sections: [
    {
      heading: "Was machst du gern?",
      blocks: [
        {
          type: "paragraph",
          text: "Hobbies are built with verbs you already conjugate. gern says you like doing something; it sits right after the verb.",
        },
        {
          type: "example",
          de: "Ich spiele gern Fußball.",
          en: "I like playing football.",
        },
        {
          type: "example",
          de: "Ich höre gern Musik. Ich lese gern Bücher.",
          en: "I like listening to music. I like reading books.",
        },
        {
          type: "table",
          caption: "Common hobbies",
          head: ["German", "English"],
          rows: [
            ["Fußball spielen", "to play football"],
            ["Tennis spielen", "to play tennis"],
            ["Musik hören", "to listen to music"],
            ["ein Buch lesen", "to read a book"],
            ["schwimmen", "to swim"],
            ["wandern", "to hike"],
            ["Fahrrad fahren", "to ride a bike"],
            ["kochen", "to cook"],
            ["fotografieren", "to take photos"],
            ["tanzen", "to dance"],
          ],
        },
      ],
    },
    {
      heading: "gern, lieber, am liebsten",
      blocks: [
        {
          type: "paragraph",
          text: "Compare preferences with the same three words you use in English: like, prefer, love the most.",
        },
        {
          type: "example",
          de: "Ich spiele gern Fußball, aber ich schwimme lieber.",
          en: "I like playing football, but I prefer swimming.",
        },
        {
          type: "example",
          de: "Am liebsten höre ich Musik.",
          en: "Most of all I like listening to music.",
        },
        {
          type: "tip",
          text: "am liebsten pushes to the front, the verb stays second: Am liebsten + verb + ...",
        },
      ],
    },
    {
      heading: "Über Freunde sprechen",
      blocks: [
        {
          type: "example",
          de: "Mein bester Freund heißt Jonas.",
          en: "My best friend is called Jonas.",
        },
        {
          type: "example",
          de: "Meine beste Freundin kommt aus Wien.",
          en: "My best friend (female) comes from Vienna.",
        },
        {
          type: "example",
          de: "Wir treffen uns am Samstag im Park.",
          en: "We are meeting on Saturday in the park.",
        },
        {
          type: "tip",
          text: "Freund is male, Freundin is female. Bester and beste are the first adjective endings you will meet; the full system comes in A2.",
        },
      ],
    },
  ],
  vocab: [
    { id: "das-hobby", de: "das Hobby", en: "the hobby", part: "noun n.", plural: "die Hobbys", audio: true },
    { id: "fussball-spielen", de: "Fußball spielen", en: "to play football", part: "phrase", phrase: true, audio: true },
    { id: "musik-hoeren", de: "Musik hören", en: "to listen to music", part: "phrase", phrase: true, audio: true },
    { id: "ein-buch-lesen", de: "ein Buch lesen", en: "to read a book", part: "phrase", phrase: true, audio: true },
    { id: "schwimmen", de: "schwimmen", en: "to swim", part: "verb", audio: true },
    { id: "wandern", de: "wandern", en: "to hike", part: "verb", audio: true },
    { id: "fahrrad-fahren", de: "Fahrrad fahren", en: "to ride a bike", part: "phrase", phrase: true, audio: true },
    { id: "kochen", de: "kochen", en: "to cook", part: "verb", audio: true },
    { id: "tanzen", de: "tanzen", en: "to dance", part: "verb", audio: true },
    { id: "gern", de: "gern", en: "gladly, likes to", part: "adverb", audio: true },
    { id: "lieber", de: "lieber", en: "rather, prefers to", part: "adverb", audio: true },
    { id: "am-liebsten", de: "am liebsten", en: "most of all", part: "adverb", audio: true },
    { id: "der-freund", de: "der Freund", en: "the friend (male)", part: "noun m.", plural: "die Freunde", audio: true },
    { id: "die-freundin", de: "die Freundin", en: "the friend (female)", part: "noun f.", plural: "die Freundinnen", audio: true },
    { id: "treffen", de: "treffen", en: "to meet", part: "verb", audio: true },
  ],
  exercises: [
    {
      id: "mc-hobbys",
      type: "multiple-choice",
      title: "Am liebsten",
      instruction: "Choose the correct verb form.",
      prompt: "Am liebsten ___ ich Musik.",
      options: ["höre", "hören", "hörst"],
      correctIndex: 0,
      explain: "ich takes höre. Am liebsten pushes the verb to second position.",
    },
    {
      id: "listening-hobbys",
      type: "listening",
      title: "Welches Hobby?",
      instruction: "Play the audio and pick the activity you heard.",
      prompt: "Fahrrad fahren",
      options: ["Fahrrad fahren", "Fußball spielen", "schwimmen"],
      correctIndex: 0,
    },
    {
      id: "fill-hobbys",
      type: "fill-blank",
      title: "Was machst du gern?",
      instruction: "Complete the sentences.",
      sentence: "Ich spiele ___ Fußball. Am liebsten ___ ich Musik.",
      blanks: [
        { answers: ["gern"], hint: "likes to" },
        { answers: ["höre"], hint: "ich-form of hören" },
      ],
    },
    {
      id: "matching-hobbys",
      type: "matching",
      title: "Hobbys",
      instruction: "Match each activity to its meaning.",
      pairs: [
        ["schwimmen", "to swim"],
        ["wandern", "to hike"],
        ["kochen", "to cook"],
        ["tanzen", "to dance"],
        ["Fahrrad fahren", "to ride a bike"],
      ],
    },
    {
      id: "word-order-hobbys",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: Most of all I like listening to music.",
      chunks: ["Am liebsten", "höre", "ich", "Musik."],
      explain: "The fronted phrase forces the verb into second position.",
    },
    {
      id: "flashcard-hobbys",
      type: "flashcard",
      title: "Hobbykarten",
      instruction: "Say the German out loud before revealing.",
      items: [
        { front: "Fußball spielen", back: "to play football", frontAudio: true },
        { front: "Musik hören", back: "to listen to music", frontAudio: true },
        { front: "schwimmen", back: "to swim", frontAudio: true },
        { front: "wandern", back: "to hike", frontAudio: true },
        { front: "kochen", back: "to cook", frontAudio: true },
        { front: "Fahrrad fahren", back: "to ride a bike", frontAudio: true },
      ],
    },
  ],
};

const wFragen: Lesson = {
  id: "w-fragen",
  title: "W-Fragen",
  summary: "All question words: wer, was, wo, wann, warum and friends.",
  status: "ready",
  sections: [
    {
      heading: "Die Fragewörter",
      blocks: [
        {
          type: "paragraph",
          text: "Every German question word starts with w. The question word takes position one, the verb position two, then the subject.",
        },
        {
          type: "table",
          caption: "Question words",
          head: ["German", "English", "Asks about"],
          rows: [
            ["wer", "who", "a person"],
            ["was", "what", "a thing"],
            ["wo", "where", "a place (location)"],
            ["woher", "where from", "origin"],
            ["wohin", "where to", "destination"],
            ["wann", "when", "time"],
            ["warum", "why", "reason"],
            ["wie", "how", "manner, condition"],
            ["wie viel", "how much", "amount (uncountable)"],
            ["wie viele", "how many", "count"],
            ["welcher / welche / welches", "which", "choosing one"],
          ],
        },
        {
          type: "example",
          de: "Wo wohnst du? Warum lernst du Deutsch?",
          en: "Where do you live? Why are you learning German?",
        },
        {
          type: "tip",
          text: "wie viel for amounts without counting (wie viel Wasser), wie viele for countable things (wie viele Kinder).",
        },
      ],
    },
    {
      heading: "Fragen stellen",
      blocks: [
        {
          type: "paragraph",
          text: "The answer usually starts where the question word pointed: who -> person, where -> place, when -> time.",
        },
        {
          type: "example",
          de: "Wer ist das? Das ist meine Schwester.",
          en: "Who is that? That is my sister.",
        },
        {
          type: "example",
          de: "Wie viele Geschwister hast du? Ich habe zwei Brüder.",
          en: "How many siblings do you have? I have two brothers.",
        },
        {
          type: "example",
          de: "Wann hast du Geburtstag? Am 5. Mai.",
          en: "When is your birthday? On May 5th.",
        },
      ],
    },
  ],
  vocab: [
    { id: "wer", de: "wer", en: "who", part: "question word", audio: true },
    { id: "was", de: "was", en: "what", part: "question word", audio: true },
    { id: "wo", de: "wo", en: "where", part: "question word", audio: true },
    { id: "woher", de: "woher", en: "where from", part: "question word", audio: true },
    { id: "wohin", de: "wohin", en: "where to", part: "question word", audio: true },
    { id: "wann", de: "wann", en: "when", part: "question word", audio: true },
    { id: "warum", de: "warum", en: "why", part: "question word", audio: true },
    { id: "wie", de: "wie", en: "how", part: "question word", audio: true },
    { id: "wie-viel", de: "wie viel", en: "how much", part: "question word", audio: true },
    { id: "wie-viele", de: "wie viele", en: "how many", part: "question word", audio: true },
    { id: "welcher", de: "welcher / welche / welches", en: "which", part: "question word", audio: true },
    { id: "der-geburtstag", de: "der Geburtstag", en: "the birthday", part: "noun m.", plural: "die Geburtstage", audio: true },
  ],
  exercises: [
    {
      id: "mc-w-fragen",
      type: "multiple-choice",
      title: "Welches Fragewort?",
      instruction: "Choose the question word that fits the answer.",
      prompt: "___ wohnst du? In Berlin.",
      options: ["Wo", "Wer", "Wann"],
      correctIndex: 0,
      explain: "The answer is a place, so the question is wo.",
    },
    {
      id: "listening-w-fragen",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the question word you heard.",
      prompt: "warum",
      options: ["warum", "wann", "wohin"],
      correctIndex: 0,
    },
    {
      id: "fill-w-fragen",
      type: "fill-blank",
      title: "Die richtige Frage",
      instruction: "Complete the questions.",
      sentence: "___ alt bist du? ___ kommst du? Aus Italien.",
      blanks: [
        { answers: ["Wie"], hint: "how old" },
        { answers: ["Woher"], hint: "origin" },
      ],
    },
    {
      id: "matching-w-fragen",
      type: "matching",
      title: "Frage und Bedeutung",
      instruction: "Match each question word to its meaning.",
      pairs: [
        ["wer", "who"],
        ["was", "what"],
        ["wann", "when"],
        ["warum", "why"],
        ["wie viele", "how many"],
      ],
    },
    {
      id: "word-order-w-fragen",
      type: "word-order",
      title: "Die Frage",
      instruction: "Build the question: How many siblings do you have?",
      chunks: ["Wie viele", "Geschwister", "hast", "du?"],
      explain: "The question word leads, the verb follows in second position.",
    },
    {
      id: "flashcard-w-fragen",
      type: "flashcard",
      title: "Fragewortkarten",
      instruction: "Say the German question word out loud before revealing.",
      items: [
        { front: "wer", back: "who", frontAudio: true },
        { front: "was", back: "what", frontAudio: true },
        { front: "wo", back: "where", frontAudio: true },
        { front: "wann", back: "when", frontAudio: true },
        { front: "warum", back: "why", frontAudio: true },
        { front: "wie viele", back: "how many", frontAudio: true },
      ],
    },
  ],
};

const verneinung: Lesson = {
  id: "verneinung",
  title: "Nicht oder kein?",
  summary: "Negation rules: when nicht, when kein.",
  status: "ready",
  sections: [
    {
      heading: "Die Grundregel",
      blocks: [
        {
          type: "paragraph",
          text: "kein negates nouns: it replaces the article. nicht negates everything else: verbs, adjectives, and whole sentences.",
        },
        {
          type: "example",
          de: "Ich habe keine Schwester.",
          en: "I have no sister.",
        },
        {
          type: "example",
          de: "Ich wohne nicht in Berlin.",
          en: "I do not live in Berlin.",
        },
        {
          type: "example",
          de: "Das ist nicht mein Buch.",
          en: "That is not my book.",
        },
        {
          type: "tip",
          text: "Test: can you replace the word with a noun? Then use kein. Is it a verb, an adjective, or a whole statement? Use nicht.",
        },
      ],
    },
    {
      heading: "Die kein-Formen",
      blocks: [
        {
          type: "table",
          caption: "kein in nominative and accusative",
          head: ["Noun", "Nominative", "Accusative"],
          rows: [
            ["der Bruder (m.)", "kein Bruder", "keinen Bruder"],
            ["die Schwester (f.)", "keine Schwester", "keine Schwester"],
            ["das Kind (n.)", "kein Kind", "kein Kind"],
            ["die Kinder (pl.)", "keine Kinder", "keine Kinder"],
          ],
        },
        {
          type: "paragraph",
          text: "kein declines exactly like ein, which means it has a plural: keine Kinder.",
        },
      ],
    },
    {
      heading: "Die Position von nicht",
      blocks: [
        {
          type: "paragraph",
          text: "nicht sits at the end of the sentence when it negates the whole statement, and directly before the word it negates.",
        },
        {
          type: "example",
          de: "Ich koche nicht. (I don't cook at all.)",
          en: "Whole sentence negated.",
        },
        {
          type: "example",
          de: "Ich koche nicht gern. (I don't like cooking.)",
          en: "nicht before gern.",
        },
      ],
    },
  ],
  vocab: [
    { id: "nicht", de: "nicht", en: "not", part: "adverb", audio: true },
    { id: "kein", de: "kein", en: "no, not a (masculine/neuter)", part: "determiner", audio: true },
    { id: "keine", de: "keine", en: "no, not a (feminine/plural)", part: "determiner", audio: true },
    { id: "keinen", de: "keinen", en: "no, not a (masculine, accusative)", part: "determiner", audio: true },
    { id: "keine-geschwister", de: "keine Geschwister", en: "no siblings", part: "phrase", phrase: true, audio: true },
    { id: "nicht-gern", de: "nicht gern", en: "don't like to", part: "phrase", phrase: true, audio: true },
    { id: "nichts", de: "nichts", en: "nothing", part: "pronoun", audio: true },
    { id: "nie", de: "nie", en: "never", part: "adverb", audio: true },
    { id: "der-hund", de: "der Hund", en: "the dog", part: "noun m.", plural: "die Hunde", audio: true },
  ],
  exercises: [
    {
      id: "mc-verneinung",
      type: "multiple-choice",
      title: "Nicht oder kein?",
      instruction: "Choose the correct negation.",
      prompt: "Ich habe ___ Bruder.",
      options: ["keinen", "nicht", "keine"],
      correctIndex: 0,
      explain: "Bruder is a masculine noun in the accusative: keinen Bruder.",
    },
    {
      id: "listening-verneinung",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the phrase you heard.",
      prompt: "keine Schwester",
      options: ["keine Schwester", "keinen Bruder", "kein Kind"],
      correctIndex: 0,
    },
    {
      id: "fill-verneinung",
      type: "fill-blank",
      title: "Die Negation",
      instruction: "Complete with nicht or the right kein form.",
      sentence: "Ich habe ___ Schwester. Ich wohne ___ in Berlin.",
      blanks: [
        { answers: ["keine"], hint: "feminine noun" },
        { answers: ["nicht"], hint: "negates the place" },
      ],
    },
    {
      id: "matching-verneinung",
      type: "matching",
      title: "Kein-Formen",
      instruction: "Match each noun to its kein form.",
      pairs: [
        ["der Bruder (nom.)", "kein Bruder"],
        ["der Bruder (akk.)", "keinen Bruder"],
        ["die Schwester", "keine Schwester"],
        ["das Kind", "kein Kind"],
        ["die Kinder", "keine Kinder"],
      ],
    },
    {
      id: "word-order-verneinung",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: I have no siblings.",
      chunks: ["Ich", "habe", "keine", "Geschwister."],
      explain: "keine replaces the article in front of the noun.",
    },
    {
      id: "flashcard-verneinung",
      type: "flashcard",
      title: "Negationskarten",
      instruction: "Say the German out loud before revealing.",
      items: [
        { front: "kein Bruder", back: "no brother", frontAudio: true },
        { front: "keinen Bruder", back: "no brother (accusative)", frontAudio: true },
        { front: "keine Schwester", back: "no sister", frontAudio: true },
        { front: "kein Kind", back: "no child", frontAudio: true },
        { front: "keine Kinder", back: "no children", frontAudio: true },
        { front: "nicht gern", back: "don't like to", frontAudio: true },
      ],
    },
  ],
};

const adjektiveGrundlagen: Lesson = {
  id: "adjektive-grundlagen",
  title: "Adjektive: groß oder klein?",
  summary: "Describing people and things with predicate adjectives.",
  status: "ready",
  sections: [
    {
      heading: "Gute Adjektive",
      blocks: [
        {
          type: "table",
          caption: "Useful adjectives",
          head: ["German", "English", "Opposite"],
          rows: [
            ["groß", "big, tall", "klein"],
            ["jung", "young", "alt"],
            ["nett", "nice", "unfreundlich"],
            ["freundlich", "friendly", "unfreundlich"],
            ["lustig", "funny", "ernst"],
            ["ruhig", "quiet", "laut"],
            ["schön", "beautiful", "hässlich"],
            ["interessant", "interesting", "langweilig"],
          ],
        },
        {
          type: "tip",
          text: "Opposites are the fastest way to double your vocabulary: learn groß with klein, jung with alt.",
        },
      ],
    },
    {
      heading: "Das Prädikativ",
      blocks: [
        {
          type: "paragraph",
          text: "After sein, the adjective stays bare: no ending. This is called the predicate position, and it is the easiest place to use adjectives.",
        },
        {
          type: "example",
          de: "Das Haus ist groß.",
          en: "The house is big.",
        },
        {
          type: "example",
          de: "Er ist nett. Wir sind jung.",
          en: "He is nice. We are young.",
        },
        {
          type: "example",
          de: "Meine Schwester ist klein und lustig.",
          en: "My sister is small and funny.",
        },
        {
          type: "tip",
          text: "A1 keeps adjectives bare after sein. In A2 you will learn the endings they take in front of nouns (ein großer Hund).",
        },
      ],
    },
    {
      heading: "Menschen beschreiben",
      blocks: [
        {
          type: "example",
          de: "Mein Bruder ist groß und laut.",
          en: "My brother is tall and loud.",
        },
        {
          type: "example",
          de: "Meine Oma ist alt, aber sehr freundlich.",
          en: "My grandma is old but very friendly.",
        },
        {
          type: "example",
          de: "Der Hund ist klein und ruhig.",
          en: "The dog is small and quiet.",
        },
        {
          type: "tip",
          text: "aber links two descriptions and never changes the word order after it: main clause stays main clause.",
        },
      ],
    },
  ],
  vocab: [
    { id: "gross", de: "groß", en: "big, tall", part: "adjective", audio: true },
    { id: "klein", de: "klein", en: "small", part: "adjective", audio: true },
    { id: "jung", de: "jung", en: "young", part: "adjective", audio: true },
    { id: "alt", de: "alt", en: "old", part: "adjective", audio: true },
    { id: "nett", de: "nett", en: "nice", part: "adjective", audio: true },
    { id: "freundlich", de: "freundlich", en: "friendly", part: "adjective", audio: true },
    { id: "lustig", de: "lustig", en: "funny", part: "adjective", audio: true },
    { id: "ruhig", de: "ruhig", en: "quiet", part: "adjective", audio: true },
    { id: "laut", de: "laut", en: "loud", part: "adjective", audio: true },
    { id: "schoen", de: "schön", en: "beautiful", part: "adjective", audio: true },
    { id: "interessant", de: "interessant", en: "interesting", part: "adjective", audio: true },
    { id: "langweilig", de: "langweilig", en: "boring", part: "adjective", audio: true },
    { id: "das-haus", de: "das Haus", en: "the house", part: "noun n.", plural: "die Häuser", audio: true },
  ],
  exercises: [
    {
      id: "mc-adjektive",
      type: "multiple-choice",
      title: "Das Gegenteil",
      instruction: "Choose the opposite adjective.",
      prompt: "Das Gegenteil von groß ist ...",
      options: ["klein", "jung", "laut"],
      correctIndex: 0,
      explain: "groß and klein are opposites.",
    },
    {
      id: "listening-adjektive",
      type: "listening",
      title: "Welches Adjektiv?",
      instruction: "Play the audio and pick the adjective you heard.",
      prompt: "freundlich",
      options: ["freundlich", "lustig", "ruhig"],
      correctIndex: 0,
    },
    {
      id: "fill-adjektive",
      type: "fill-blank",
      title: "Beschreiben",
      instruction: "Complete the descriptions.",
      sentence: "Das Gegenteil von jung ist ___. Meine Schwester ist klein und ___.",
      blanks: [
        { answers: ["alt"], hint: "opposite of young" },
        { answers: ["lustig", "nett", "freundlich", "ruhig", "schön"], hint: "any positive adjective" },
      ],
    },
    {
      id: "matching-adjektive",
      type: "matching",
      title: "Gegenteile",
      instruction: "Match each adjective to its opposite.",
      pairs: [
        ["groß", "klein"],
        ["jung", "alt"],
        ["laut", "ruhig"],
        ["lustig", "ernst"],
        ["interessant", "langweilig"],
      ],
    },
    {
      id: "word-order-adjektive",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: My sister is small and funny.",
      chunks: ["Meine", "Schwester", "ist", "klein", "und", "lustig."],
      explain: "The adjective stays bare after sein.",
    },
    {
      id: "flashcard-adjektive",
      type: "flashcard",
      title: "Adjektivkarten",
      instruction: "Say the German adjective out loud before revealing.",
      items: [
        { front: "groß", back: "big, tall", frontAudio: true },
        { front: "klein", back: "small", frontAudio: true },
        { front: "jung", back: "young", frontAudio: true },
        { front: "alt", back: "old", frontAudio: true },
        { front: "nett", back: "nice", frontAudio: true },
        { front: "lustig", back: "funny", frontAudio: true },
        { front: "ruhig", back: "quiet", frontAudio: true },
        { front: "schön", back: "beautiful", frontAudio: true },
      ],
    },
  ],
};

export const familieUndFreunde: Unit = {
  id: "familie-und-freunde",
  title: "Familie und Freunde",
  theme: "Family and friends",
  lessons: [
    meineFamilie,
    possessivartikel,
    personalpronomen,
    hobbysUndFreunde,
    wFragen,
    verneinung,
    adjektiveGrundlagen,
  ],
};