import type { Lesson, Unit } from "../../schema";

const hobbysUndSport: Lesson = {
  id: "hobbys-und-sport",
  title: "Hobbys und Sport",
  summary: "Free time activities and sports.",
  status: "ready",
  sections: [
    {
      heading: "Die Sportarten",
      blocks: [
        {
          type: "table",
          caption: "Sports",
          head: ["German", "English", "Verb"],
          rows: [
            ["Fußball", "football", "Fußball spielen"],
            ["Tennis", "tennis", "Tennis spielen"],
            ["Basketball", "basketball", "Basketball spielen"],
            ["Tischtennis", "table tennis", "Tischtennis spielen"],
            ["Schwimmen", "swimming", "schwimmen gehen"],
            ["Joggen", "jogging", "joggen gehen"],
            ["Radfahren", "cycling", "Rad fahren"],
            ["Yoga", "yoga", "Yoga machen"],
            ["Gymnastik", "gymnastics", "Gymnastik machen"],
            ["Tanzen", "dancing", "tanzen gehen"],
          ],
        },
        {
          type: "tip",
          text: "spielen for ball games, machen for yoga and gymnastics, gehen for activities with a destination: schwimmen gehen, tanzen gehen.",
        },
      ],
    },
    {
      heading: "Was machst du am Wochenende?",
      blocks: [
        {
          type: "example",
          de: "Ich spiele am Wochenende Fußball.",
          en: "I play football on the weekend.",
        },
        {
          type: "example",
          de: "Wir gehen jeden Samstag schwimmen.",
          en: "We go swimming every Saturday.",
        },
        {
          type: "example",
          de: "Sie macht dreimal pro Woche Yoga.",
          en: "She does yoga three times a week.",
        },
        {
          type: "tip",
          text: "Frequency: jeden Tag (every day), einmal pro Woche (once a week), dreimal pro Woche (three times a week).",
        },
      ],
    },
  ],
  vocab: [
    { id: "fussball", de: "Fußball spielen", en: "to play football", part: "phrase", phrase: true, audio: true },
    { id: "tennis", de: "Tennis spielen", en: "to play tennis", part: "phrase", phrase: true, audio: true },
    { id: "basketball", de: "Basketball spielen", en: "to play basketball", part: "phrase", phrase: true, audio: true },
    { id: "schwimmen-gehen", de: "schwimmen gehen", en: "to go swimming", part: "phrase", phrase: true, audio: true },
    { id: "joggen", de: "joggen", en: "to jog", part: "verb", audio: true },
    { id: "radfahren", de: "Rad fahren", en: "to cycle", part: "phrase", phrase: true, audio: true },
    { id: "yoga", de: "Yoga machen", en: "to do yoga", part: "phrase", phrase: true, audio: true },
    { id: "tanzen", de: "tanzen gehen", en: "to go dancing", part: "phrase", phrase: true, audio: true },
    { id: "der-sport", de: "der Sport", en: "the sport", part: "noun m.", plural: "die Sportarten", audio: true },
    { id: "jeden-tag", de: "jeden Tag", en: "every day", part: "phrase", phrase: true, audio: true },
    { id: "pro-woche", de: "dreimal pro Woche", en: "three times a week", part: "phrase", phrase: true, audio: true },
    { id: "am-wochenende", de: "am Wochenende", en: "on the weekend", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "mc-sport",
      type: "multiple-choice",
      title: "Der Sport",
      instruction: "Choose the right verb.",
      prompt: "Sie ___ Yoga.",
      options: ["macht", "spielt", "geht"],
      correctIndex: 0,
      explain: "Yoga takes machen: Yoga machen.",
    },
    {
      id: "listening-sport",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the activity you heard.",
      prompt: "schwimmen gehen",
      options: ["schwimmen gehen", "tanzen gehen", "joggen gehen"],
      correctIndex: 0,
    },
    {
      id: "fill-sport",
      type: "fill-blank",
      title: "Der Sport",
      instruction: "Complete the sentences.",
      sentence: "Wir ___ jeden Samstag schwimmen. Ich ___ Fußball.",
      blanks: [
        { answers: ["gehen"], hint: "schwimmen gehen" },
        { answers: ["spiele"], hint: "Fußball spielen" },
      ],
    },
    {
      id: "matching-sport",
      type: "matching",
      title: "Sportarten",
      instruction: "Match each sport to its meaning.",
      pairs: [
        ["Fußball spielen", "to play football"],
        ["schwimmen gehen", "to go swimming"],
        ["Yoga machen", "to do yoga"],
        ["Rad fahren", "to cycle"],
        ["tanzen gehen", "to go dancing"],
      ],
    },
    {
      id: "word-order-sport",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: We go swimming every Saturday.",
      chunks: ["Wir", "gehen", "jeden", "Samstag", "schwimmen."],
      explain: "The destination infinitive closes the sentence.",
    },
    {
      id: "flashcard-sport",
      type: "flashcard",
      title: "Sportkarten",
      instruction: "Say the German out loud before revealing.",
      items: [
        { front: "Fußball spielen", back: "to play football", frontAudio: true },
        { front: "Tennis spielen", back: "to play tennis", frontAudio: true },
        { front: "schwimmen gehen", back: "to go swimming", frontAudio: true },
        { front: "Rad fahren", back: "to cycle", frontAudio: true },
        { front: "Yoga machen", back: "to do yoga", frontAudio: true },
        { front: "am Wochenende", back: "on the weekend", frontAudio: true },
      ],
    },
  ],
};

const nachBerlin: Lesson = {
  id: "nach-berlin-oder-in-die-schweiz",
  title: "Nach Berlin oder in die Schweiz?",
  summary: "nach, in, and aus with countries and cities.",
  status: "ready",
  sections: [
    {
      heading: "Die Regel",
      blocks: [
        {
          type: "table",
          caption: "nach, in, aus",
          head: ["Target", "Preposition", "Example"],
          rows: [
            ["city", "nach", "nach Berlin"],
            ["country without article", "nach", "nach Deutschland"],
            ["article country", "in", "in die Schweiz, in den Iran, in die USA"],
            ["origin", "aus", "aus Berlin, aus der Schweiz"],
          ],
        },
        {
          type: "tip",
          text: "Article countries are few: die Schweiz, die Türkei, die USA, der Iran, die Niederlande, der Irak. Everything else takes nach.",
        },
      ],
    },
    {
      heading: "Im Alltag",
      blocks: [
        {
          type: "example",
          de: "Ich fahre nach Berlin. Er fliegt nach Spanien.",
          en: "I drive to Berlin. He flies to Spain.",
        },
        {
          type: "example",
          de: "Wir fahren in die Schweiz. Sie fliegt in die Türkei.",
          en: "We drive to Switzerland. She flies to Turkey.",
        },
        {
          type: "example",
          de: "Ich komme aus der Schweiz. Er kommt aus Berlin.",
          en: "I come from Switzerland. He comes from Berlin.",
        },
        {
          type: "tip",
          text: "Memory hook: no article in the name, no article with nach. Article in the name, article with in and aus.",
        },
      ],
    },
  ],
  vocab: [
    { id: "nach-berlin", de: "nach Berlin", en: "to Berlin", part: "phrase", phrase: true, audio: true },
    { id: "nach-deutschland", de: "nach Deutschland", en: "to Germany", part: "phrase", phrase: true, audio: true },
    { id: "in-die-schweiz", de: "in die Schweiz", en: "to Switzerland", part: "phrase", phrase: true, audio: true },
    { id: "in-den-iran", de: "in den Iran", en: "to Iran", part: "phrase", phrase: true, audio: true },
    { id: "in-die-usa", de: "in die USA", en: "to the USA", part: "phrase", phrase: true, audio: true },
    { id: "aus-der-schweiz", de: "aus der Schweiz", en: "from Switzerland", part: "phrase", phrase: true, audio: true },
    { id: "aus-berlin", de: "aus Berlin", en: "from Berlin", part: "phrase", phrase: true, audio: true },
    { id: "fliegen", de: "fliegen", en: "to fly", part: "verb", audio: true },
    { id: "fahren", de: "fahren", en: "to drive, travel", part: "verb", audio: true },
  ],
  exercises: [
    {
      id: "mc-nach-in",
      type: "multiple-choice",
      title: "Nach oder in?",
      instruction: "Choose the correct preposition.",
      prompt: "Ich fliege ___ die Schweiz.",
      options: ["in", "nach", "aus"],
      correctIndex: 0,
      explain: "The Schweiz has an article, so in.",
    },
    {
      id: "listening-nach-in",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the phrase you heard.",
      prompt: "nach Spanien",
      options: ["nach Spanien", "in die Schweiz", "aus Spanien"],
      correctIndex: 0,
    },
    {
      id: "fill-nach-in",
      type: "fill-blank",
      title: "Die Präposition",
      instruction: "Complete with nach, in, or aus.",
      sentence: "Ich fahre ___ Berlin. Wir fliegen ___ die Türkei.",
      blanks: [
        { answers: ["nach"], hint: "city" },
        { answers: ["in"], hint: "article country" },
      ],
    },
    {
      id: "matching-nach-in",
      type: "matching",
      title: "Ziele",
      instruction: "Match each phrase to its meaning.",
      pairs: [
        ["nach Berlin", "to Berlin"],
        ["in die Schweiz", "to Switzerland"],
        ["aus Berlin", "from Berlin"],
        ["in die USA", "to the USA"],
        ["nach Deutschland", "to Germany"],
      ],
    },
    {
      id: "word-order-nach-in",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: We drive to Switzerland.",
      chunks: ["Wir", "fahren", "in", "die", "Schweiz."],
      explain: "The destination follows the verb.",
    },
    {
      id: "flashcard-nach-in",
      type: "flashcard",
      title: "Zielkarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "nach Berlin", back: "to Berlin", frontAudio: true },
        { front: "nach Deutschland", back: "to Germany", frontAudio: true },
        { front: "in die Schweiz", back: "to Switzerland", frontAudio: true },
        { front: "in die USA", back: "to the USA", frontAudio: true },
        { front: "aus der Schweiz", back: "from Switzerland", frontAudio: true },
        { front: "aus Berlin", back: "from Berlin", frontAudio: true },
      ],
    },
  ],
};

const reisen: Lesson = {
  id: "reisen",
  title: "Reisen",
  summary: "Travel vocabulary and vowel-changing verbs: fahren, lesen, sprechen.",
  status: "ready",
  sections: [
    {
      heading: "Die Reise",
      blocks: [
        {
          type: "table",
          caption: "Travel vocabulary",
          head: ["German", "English"],
          rows: [
            ["die Reise", "the trip"],
            ["der Urlaub", "the vacation"],
            ["der Koffer", "the suitcase"],
            ["das Gepäck", "the luggage"],
            ["das Flugzeug", "the airplane"],
            ["der Flughafen", "the airport"],
            ["das Hotel", "the hotel"],
            ["der Pass", "the passport"],
            ["das Ticket", "the ticket"],
          ],
        },
        {
          type: "tip",
          text: "Urlaub is only vacation time, Reise is the journey itself. Im Urlaub fahre ich nach Italien. Die Reise dauert drei Stunden.",
        },
      ],
    },
    {
      heading: "Vokalwechselnde Verben",
      blocks: [
        {
          type: "paragraph",
          text: "Strong verbs change their vowel in the du and er/sie/es forms. The most useful six for travel:",
        },
        {
          type: "table",
          caption: "Vowel-changing verbs",
          head: ["Infinitive", "du", "er / sie / es", "English"],
          rows: [
            ["fahren", "fährst", "fährt", "to drive, travel"],
            ["schlafen", "schläfst", "schläft", "to sleep"],
            ["lesen", "liest", "liest", "to read"],
            ["sprechen", "sprichst", "spricht", "to speak"],
            ["essen", "isst", "isst", "to eat"],
            ["nehmen", "nimmst", "nimmt", "to take"],
          ],
        },
        {
          type: "example",
          de: "Er fährt nach Italien. Du sprichst sehr gut Deutsch.",
          en: "He drives to Italy. You speak German very well.",
        },
        {
          type: "tip",
          text: "The change is a > ä (fahren) or e > i(e) (sprechen, lesen, nehmen). The infinitive and the wir/ihr forms keep the original vowel.",
        },
      ],
    },
  ],
  vocab: [
    { id: "die-reise", de: "die Reise", en: "the trip", part: "noun f.", plural: "die Reisen", audio: true },
    { id: "der-urlaub", de: "der Urlaub", en: "the vacation", part: "noun m.", plural: "die Urlaube", audio: true },
    { id: "der-koffer", de: "der Koffer", en: "the suitcase", part: "noun m.", plural: "die Koffer", audio: true },
    { id: "das-gepaeck", de: "das Gepäck", en: "the luggage", part: "noun n.", audio: true },
    { id: "das-flugzeug", de: "das Flugzeug", en: "the airplane", part: "noun n.", plural: "die Flugzeuge", audio: true },
    { id: "der-flughafen", de: "der Flughafen", en: "the airport", part: "noun m.", plural: "die Flughäfen", audio: true },
    { id: "das-hotel", de: "das Hotel", en: "the hotel", part: "noun n.", plural: "die Hotels", audio: true },
    { id: "der-pass", de: "der Pass", en: "the passport", part: "noun m.", plural: "die Pässe", audio: true },
    { id: "fahren", de: "fahren", en: "to drive, travel", part: "verb", audio: true },
    { id: "du-faehrst", de: "du fährst", en: "you drive, travel", part: "phrase", phrase: true, audio: true },
    { id: "er-faehrt", de: "er fährt", en: "he drives, travels", part: "phrase", phrase: true, audio: true },
    { id: "du-sprichst", de: "du sprichst", en: "you speak", part: "phrase", phrase: true, audio: true },
    { id: "der-dauern", de: "dauern", en: "to last", part: "verb", audio: true },
  ],
  exercises: [
    {
      id: "mc-reisen",
      type: "multiple-choice",
      title: "Die Form",
      instruction: "Choose the correct verb form.",
      prompt: "Er ___ nach Italien. (fahren)",
      options: ["fährt", "fahrt", "fahren"],
      correctIndex: 0,
      explain: "er takes fährt with the vowel change.",
    },
    {
      id: "listening-reisen",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Er fährt nach Italien.",
      options: ["Er fährt nach Italien.", "Er fliegt nach Italien.", "Er fährt nach Spanien."],
      correctIndex: 0,
    },
    {
      id: "fill-reisen",
      type: "fill-blank",
      title: "Die Reise",
      instruction: "Complete the sentences.",
      sentence: "Er ___ nach Spanien. (fahren) Die Reise ___ drei Stunden.",
      blanks: [
        { answers: ["fährt"], hint: "fahren, er" },
        { answers: ["dauert"], hint: "to last" },
      ],
    },
    {
      id: "matching-reisen",
      type: "matching",
      title: "Reisevokabular",
      instruction: "Match each German word to its meaning.",
      pairs: [
        ["der Koffer", "the suitcase"],
        ["das Gepäck", "the luggage"],
        ["der Flughafen", "the airport"],
        ["der Pass", "the passport"],
        ["der Urlaub", "the vacation"],
      ],
    },
    {
      id: "word-order-reisen",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: In vacation I drive to Italy.",
      chunks: ["Im", "Urlaub", "fahre", "ich", "nach", "Italien."],
      explain: "The fronted time forces the inversion.",
    },
    {
      id: "flashcard-reisen",
      type: "flashcard",
      title: "Reisekarten",
      instruction: "Say the German out loud before revealing.",
      items: [
        { front: "der Koffer", back: "the suitcase", frontAudio: true },
        { front: "der Flughafen", back: "the airport", frontAudio: true },
        { front: "der Pass", back: "the passport", frontAudio: true },
        { front: "er fährt", back: "he drives", frontAudio: true },
        { front: "du sprichst", back: "you speak", frontAudio: true },
        { front: "im Urlaub", back: "on vacation", frontAudio: true },
      ],
    },
  ],
};

const einladungen: Lesson = {
  id: "einladungen",
  title: "Einladungen",
  summary: "Invitations: Wann? Wo? Um wie viel Uhr?",
  status: "ready",
  sections: [
    {
      heading: "Einladen",
      blocks: [
        {
          type: "table",
          caption: "Inviting and answering",
          head: ["German", "English"],
          rows: [
            ["Kommst du mit?", "Are you coming along?"],
            ["Möchtest du mitkommen?", "Would you like to come?"],
            ["Ich lade dich ein.", "I am inviting you."],
            ["Wir treffen uns am Samstag.", "We are meeting on Saturday."],
            ["Wann und wo?", "When and where?"],
            ["Um wie viel Uhr?", "At what time?"],
            ["Das freut mich!", "I am happy about that!"],
            ["Leider kann ich nicht.", "Unfortunately I cannot."],
            ["Ich habe keine Zeit.", "I have no time."],
          ],
        },
        {
          type: "tip",
          text: "einladen is separable: Ich lade dich ein. The fixed question trio: Wann? Wo? Um wie viel Uhr?",
        },
      ],
    },
    {
      heading: "Der Dialog",
      blocks: [
        {
          type: "example",
          de: "Anna: Hey, ich habe am Samstag Geburtstag. Möchtest du kommen? Jonas: Ja, gerne! Wann und wo? Anna: Um sieben Uhr bei mir zu Hause.",
          en: "Anna: Hey, it is my birthday on Saturday. Would you like to come? Jonas: Yes, gladly! When and where? Anna: At seven at my place.",
        },
        {
          type: "example",
          de: "Leider kann ich nicht kommen. Ich habe schon einen Termin.",
          en: "Unfortunately I cannot come. I already have an appointment.",
        },
      ],
    },
  ],
  vocab: [
    { id: "einladen", de: "einladen", en: "to invite", part: "verb", audio: true },
    { id: "mitkommen", de: "mitkommen", en: "to come along", part: "verb", audio: true },
    { id: "die-einladung", de: "die Einladung", en: "the invitation", part: "noun f.", plural: "die Einladungen", audio: true },
    { id: "sich-treffen", de: "sich treffen", en: "to meet (each other)", part: "verb", audio: true },
    { id: "das-freut-mich", de: "Das freut mich!", en: "I am happy about that!", part: "phrase", phrase: true, audio: true },
    { id: "leider", de: "leider", en: "unfortunately", part: "adverb", audio: true },
    { id: "keine-zeit", de: "Ich habe keine Zeit.", en: "I have no time.", part: "phrase", phrase: true, audio: true },
    { id: "gern", de: "Ja, gerne!", en: "Yes, gladly!", part: "phrase", phrase: true, audio: true },
    { id: "zu-hause", de: "bei mir zu Hause", en: "at my place", part: "phrase", phrase: true, audio: true },
    { id: "die-feier", de: "die Feier", en: "the party", part: "noun f.", plural: "die Feiern", audio: true },
  ],
  exercises: [
    {
      id: "mc-einladung",
      type: "multiple-choice",
      title: "Die Einladung",
      instruction: "Choose the correct response.",
      prompt: "Möchtest du mitkommen?",
      options: ["Ja, gerne!", "Das freut mich, aber nein.", "Ich habe keine Zeit, gerne!"],
      correctIndex: 0,
      explain: "The natural yes is Ja, gerne!",
    },
    {
      id: "listening-einladung",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Wir treffen uns am Samstag um sieben.",
      options: [
        "Wir treffen uns am Samstag um sieben.",
        "Wir treffen uns am Sonntag um sieben.",
        "Wir treffen uns am Samstag um acht.",
      ],
      correctIndex: 0,
    },
    {
      id: "fill-einladung",
      type: "fill-blank",
      title: "Einladen",
      instruction: "Complete the sentences.",
      sentence: "Ich ___ dich ein. (invite) Leider kann ich nicht ___.",
      blanks: [
        { answers: ["lade"], hint: "einladen, ich" },
        { answers: ["kommen"], hint: "cannot come" },
      ],
    },
    {
      id: "matching-einladung",
      type: "matching",
      title: "Sätze",
      instruction: "Match each German phrase to its meaning.",
      pairs: [
        ["Kommst du mit?", "Are you coming along?"],
        ["Ich lade dich ein.", "I am inviting you."],
        ["Das freut mich!", "I am happy about that!"],
        ["Leider kann ich nicht.", "Unfortunately I cannot."],
        ["Um wie viel Uhr?", "At what time?"],
      ],
    },
    {
      id: "word-order-einladung",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: We meet on Saturday at seven.",
      chunks: ["Wir", "treffen", "uns", "am", "Samstag", "um", "sieben."],
      explain: "Time comes first: day, then clock time.",
    },
    {
      id: "flashcard-einladung",
      type: "flashcard",
      title: "Einladungskarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "Möchtest du mitkommen?", back: "Would you like to come?", frontAudio: true },
        { front: "Ich lade dich ein.", back: "I am inviting you.", frontAudio: true },
        { front: "Das freut mich!", back: "I am happy about that!", frontAudio: true },
        { front: "Leider kann ich nicht.", back: "Unfortunately I cannot.", frontAudio: true },
        { front: "Ja, gerne!", back: "Yes, gladly!", frontAudio: true },
        { front: "Wann und wo?", back: "When and where?", frontAudio: true },
      ],
    },
  ],
};

const wiederholung: Lesson = {
  id: "wiederholung",
  title: "Wiederholung A1",
  summary: "Bring your A1 German together: review and consolidation.",
  status: "ready",
  sections: [
    {
      heading: "Was kannst du jetzt?",
      blocks: [
        {
          type: "paragraph",
          text: "You have finished the A1 grammar. Before the mock exams, take stock. You can introduce yourself, conjugate regular and strong verbs, ask W-questions and yes/no questions, use der/die/das and ein/eine, negate with nicht and kein, form the Perfekt with haben and sein, give imperatives, use the dative with prepositions and verbs, and connect sentences with und, oder, aber, denn, and sondern.",
        },
        {
          type: "table",
          caption: "The A1 checklist",
          head: ["Area", "You can"],
          rows: [
            ["Present tense", "conjugate regular, strong, and modal verbs"],
            ["Cases", "use nominative, accusative, and dative"],
            ["Articles", "choose der/die/das, ein/eine, kein"],
            ["Negation", "place nicht and kein correctly"],
            ["Questions", "ask with question words and verb-first"],
            ["Past", "build the Perfekt with haben and sein"],
            ["Commands", "give imperatives for du, ihr, Sie"],
            ["Sentence structure", "keep the verb in position two"],
            ["Connectors", "join sentences with und, oder, aber, denn"],
          ],
        },
        {
          type: "tip",
          text: "If any row feels shaky, open that lesson again before the mock exam. The mock exams are designed to show you exactly which row needs work.",
        },
      ],
    },
    {
      heading: "Schnelle Wiederholung",
      blocks: [
        {
          type: "paragraph",
          text: "Here are the three tables that hold A1 together. Read them aloud once, then do the exercises: the mixed practice below mixes everything on purpose.",
        },
        {
          type: "table",
          caption: "sein und haben",
          head: ["Person", "sein", "haben"],
          rows: [
            ["ich", "bin", "habe"],
            ["du", "bist", "hast"],
            ["er / sie / es", "ist", "hat"],
            ["wir", "sind", "haben"],
            ["ihr", "seid", "habt"],
            ["sie / Sie", "sind", "haben"],
          ],
        },
        {
          type: "table",
          caption: "The three cases",
          head: ["Gender", "Nominative", "Accusative", "Dative"],
          rows: [
            ["masculine", "der Mann", "den Mann", "dem Mann"],
            ["feminine", "die Frau", "die Frau", "der Frau"],
            ["neuter", "das Kind", "das Kind", "dem Kind"],
            ["plural", "die Kinder", "die Kinder", "den Kindern"],
          ],
        },
        {
          type: "tip",
          text: "One sentence to test all three cases: Ich gebe dem Kind einen Apfel. Ich (nominative), dem Kind (dative, the receiver), einen Apfel (accusative, the thing).",
        },
      ],
    },
    {
      heading: "Dein Plan",
      blocks: [
        {
          type: "paragraph",
          text: "A1 ends with two mock exams in this course: one in Goethe style and one in telc style. Do them without notes, like the real exam, then review the topics you missed.",
        },
        {
          type: "example",
          de: "Ich kann ein bisschen Deutsch. Ich kann mich vorstellen und einen Termin machen.",
          en: "I can speak a little German. I can introduce myself and make an appointment.",
        },
        {
          type: "tip",
          text: "Congratulations: with the Perfekt, the dative, and the connectors, you have everything you need to start A2, where subordinate clauses and the future arrive.",
        },
      ],
    },
  ],
  vocab: [
    { id: "die-wiederholung", de: "die Wiederholung", en: "the review", part: "noun f.", plural: "die Wiederholungen", audio: true },
    { id: "wiederholen", de: "wiederholen", en: "to repeat, review", part: "verb", audio: true },
    { id: "die-pruefung", de: "die Prüfung", en: "the exam", part: "noun f.", plural: "die Prüfungen", audio: true },
    { id: "vorstellen", de: "sich vorstellen", en: "to introduce oneself", part: "verb", audio: true },
    { id: "ein-bisschen", de: "ein bisschen", en: "a little", part: "adverb", audio: true },
    { id: "der-checklist", de: "die Checkliste", en: "the checklist", part: "noun f.", plural: "die Checklisten", audio: true },
    { id: "sicher", de: "sicher", en: "certain, safe", part: "adjective", audio: true },
    { id: "der-tipp", de: "der Tipp", en: "the tip", part: "noun m.", plural: "die Tipps", audio: true },
    { id: "fertig", de: "fertig", en: "done, finished", part: "adjective", audio: true },
    { id: "losgehen", de: "losgehen", en: "to get going, start", part: "verb", audio: true },
  ],
  exercises: [
    {
      id: "mc-wiederholung",
      type: "multiple-choice",
      title: "Alles zusammen",
      instruction: "Mixed A1 practice: choose the correct form.",
      prompt: "Ich ___ gestern nach Berlin gefahren.",
      options: ["bin", "habe", "haben"],
      correctIndex: 0,
      explain: "Movement takes sein: bin gefahren.",
    },
    {
      id: "listening-wiederholung",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Ich kann mich vorstellen und einen Termin machen.",
      options: [
        "Ich kann mich vorstellen und einen Termin machen.",
        "Ich kann mich vorstellen und ein Termin machen.",
        "Ich kann mich vorstellen und einen Termin machen?",
      ],
      correctIndex: 0,
    },
    {
      id: "fill-wiederholung",
      type: "fill-blank",
      title: "Die Lücken",
      instruction: "Complete the mixed sentences.",
      sentence: "Ich ___ aus Deutschland. (come) Wir ___ gestern nach Berlin gefahren. Das schmeckt ___.",
      blanks: [
        { answers: ["komme"], hint: "kommen, ich" },
        { answers: ["sind"], hint: "sein + movement" },
        { answers: ["mir"], hint: "dative pronoun" },
      ],
    },
    {
      id: "matching-wiederholung",
      type: "matching",
      title: "Alles gemischt",
      instruction: "Match each item to its partner.",
      pairs: [
        ["haben (ich)", "habe"],
        ["fahren (du)", "fährst"],
        ["essen (Partizip)", "gegessen"],
        ["die Frau (dativ)", "der Frau"],
        ["nicht after negation + but", "sondern"],
      ],
    },
    {
      id: "word-order-wiederholung",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: I can introduce myself and make an appointment.",
      chunks: ["Ich", "kann", "mich", "vorstellen", "und", "einen", "Termin", "machen."],
      explain: "The modal is second; both infinitives close the sentence.",
    },
    {
      id: "flashcard-wiederholung",
      type: "flashcard",
      title: "A1-Karten",
      instruction: "Say the German out loud before revealing.",
      items: [
        { front: "ich bin", back: "I am", frontAudio: true },
        { front: "du fährst", back: "you drive", frontAudio: true },
        { front: "gegessen", back: "eaten", frontAudio: true },
        { front: "dem Mann", back: "to the man (dative)", frontAudio: true },
        { front: "sondern", back: "but rather", frontAudio: true },
        { front: "sich vorstellen", back: "to introduce oneself", frontAudio: true },
      ],
    },
  ],
};

const goetheMockExam: Lesson = {
  id: "goethe-a1-mock-exam",
  title: "Goethe-Style A1 Mock Exam",
  summary: "A full A1-style practice round for everyday life in Germany.",
  status: "ready",
  sections: [
    {
      heading: "So funktioniert die Prüfung",
      blocks: [
        {
          type: "paragraph",
          text: "The real Goethe A1 exam has four parts: Hören (listening), Lesen (reading), Schreiben (writing), and Sprechen (speaking). This mock exam practises the same skills with the same kind of tasks: listening and choosing, filling forms, matching notices, and building correct sentences.",
        },
        {
          type: "table",
          caption: "The exam parts",
          head: ["Part", "What happens", "Here you practise"],
          rows: [
            ["Hören", "you hear short texts and pick answers", "listening exercises"],
            ["Lesen", "you read notices and forms", "reading and matching"],
            ["Schreiben", "you fill in forms and write short messages", "fill-blank tasks"],
            ["Sprechen", "you introduce yourself and ask questions", "word-order sentences"],
          ],
        },
        {
          type: "tip",
          text: "Exam vocabulary you will actually meet: der Termin, die Anmeldung, das Formular, das Bürgeramt, die Krankenversicherung, der Aufenthaltstitel, das Konto. Learn these as a set, they appear in every A1 paper.",
        },
      ],
    },
    {
      heading: "Teil 1: Wortschatz für den Alltag",
      blocks: [
        {
          type: "paragraph",
          text: "Goethe A1 loves the practical Germany: appointments, forms, and documents. These words are the exam's favourite topic and the words you really need after landing.",
        },
        {
          type: "table",
          caption: "Exam vocabulary",
          head: ["German", "English"],
          rows: [
            ["der Termin", "the appointment"],
            ["die Anmeldung", "the registration"],
            ["das Formular", "the form"],
            ["das Bürgeramt", "the citizen's office"],
            ["die Krankenversicherung", "the health insurance"],
            ["der Aufenthaltstitel", "the residence permit"],
            ["das Konto", "the bank account"],
            ["die Meldebescheinigung", "the registration certificate"],
          ],
        },
        {
          type: "example",
          de: "Ich habe morgen einen Termin beim Bürgeramt.",
          en: "I have an appointment at the citizen's office tomorrow.",
        },
      ],
    },
    {
      heading: "Teil 2: Grammatik in der Prüfung",
      blocks: [
        {
          type: "paragraph",
          text: "The exam checks the same grammar you already know: articles, cases, the Perfekt, modals, and word order. The exercises below mix all of it the way the exam does.",
        },
        {
          type: "example",
          de: "Ich möchte einen Termin machen. Kann ich das Formular hier bekommen?",
          en: "I would like to make an appointment. Can I get the form here?",
        },
      ],
    },
  ],
  vocab: [
    { id: "die-pruefung", de: "die Prüfung", en: "the exam", part: "noun f.", plural: "die Prüfungen", audio: true },
    { id: "der-termin", de: "der Termin", en: "the appointment", part: "noun m.", plural: "die Termine", audio: true },
    { id: "die-anmeldung", de: "die Anmeldung", en: "the registration", part: "noun f.", plural: "die Anmeldungen", audio: true },
    { id: "das-formular", de: "das Formular", en: "the form", part: "noun n.", plural: "die Formulare", audio: true },
    { id: "das-buergeramt", de: "das Bürgeramt", en: "the citizen's office", part: "noun n.", plural: "die Bürgerämter", audio: true },
    { id: "die-krankenversicherung", de: "die Krankenversicherung", en: "the health insurance", part: "noun f.", plural: "die Krankenversicherungen", audio: true },
    { id: "der-aufenthaltstitel", de: "der Aufenthaltstitel", en: "the residence permit", part: "noun m.", plural: "die Aufenthaltstitel", audio: true },
    { id: "das-konto", de: "das Konto", en: "the bank account", part: "noun n.", plural: "die Konten", audio: true },
    { id: "die-meldebescheinigung", de: "die Meldebescheinigung", en: "the registration certificate", part: "noun f.", plural: "die Meldebescheinigungen", audio: true },
    { id: "die-hoeren", de: "das Hören", en: "the listening (exam part)", part: "noun n.", audio: true },
    { id: "das-lesen", de: "das Lesen", en: "the reading (exam part)", part: "noun n.", audio: true },
    { id: "das-schreiben", de: "das Schreiben", en: "the writing (exam part)", part: "noun n.", audio: true },
  ],
  exercises: [
    {
      id: "mc-goethe-woerter",
      type: "multiple-choice",
      title: "Teil 1: Wortschatz",
      instruction: "Choose the word that fits the exam sentence.",
      prompt: "Ich habe morgen einen ___ beim Bürgeramt.",
      options: ["Termin", "Formular", "Aufenthaltstitel"],
      correctIndex: 0,
      explain: "The appointment is der Termin: einen Termin haben.",
    },
    {
      id: "listening-goethe-hoeren",
      type: "listening",
      title: "Teil: Hören",
      instruction: "Play the audio and pick what you heard.",
      prompt: "Ich möchte einen Termin machen.",
      options: [
        "Ich möchte einen Termin machen.",
        "Ich möchte ein Formular machen.",
        "Ich möchte einen Termin haben.",
      ],
      correctIndex: 0,
    },
    {
      id: "fill-goethe-formular",
      type: "fill-blank",
      title: "Teil: Schreiben",
      instruction: "Fill in the form sentences.",
      sentence: "Mein ___ ist Anna Müller. (last name) Ich habe ___ Termin. (an, masculine)",
      blanks: [
        { answers: ["Nachname"], hint: "last name" },
        { answers: ["einen"], hint: "accusative, masculine" },
      ],
    },
    {
      id: "matching-goethe-lesen",
      type: "matching",
      title: "Teil: Lesen",
      instruction: "Match each document word to its meaning.",
      pairs: [
        ["die Anmeldung", "the registration"],
        ["das Formular", "the form"],
        ["der Aufenthaltstitel", "the residence permit"],
        ["die Krankenversicherung", "the health insurance"],
        ["das Konto", "the bank account"],
      ],
    },
    {
      id: "word-order-goethe",
      type: "word-order",
      title: "Teil: Sprechen",
      instruction: "Build the sentence: I have an appointment at the citizen's office tomorrow.",
      chunks: ["Ich", "habe", "morgen", "einen", "Termin", "beim", "Bürgeramt."],
      explain: "Time (morgen) comes before the object.",
    },
    {
      id: "flashcard-goethe",
      type: "flashcard",
      title: "Prüfungswortschatz",
      instruction: "Say the German exam word out loud before revealing.",
      items: [
        { front: "der Termin", back: "the appointment", frontAudio: true },
        { front: "die Anmeldung", back: "the registration", frontAudio: true },
        { front: "das Formular", back: "the form", frontAudio: true },
        { front: "das Bürgeramt", back: "the citizen's office", frontAudio: true },
        { front: "der Aufenthaltstitel", back: "the residence permit", frontAudio: true },
        { front: "die Krankenversicherung", back: "the health insurance", frontAudio: true },
      ],
    },
  ],
};

const telcMockExam: Lesson = {
  id: "telc-a1-mock-exam",
  title: "telc-Style A1 Mock Exam",
  summary: "Housing and city life: apartment notices, transport, shops, directions.",
  status: "ready",
  sections: [
    {
      heading: "So funktioniert telc",
      blocks: [
        {
          type: "paragraph",
          text: "The telc A1 exam is organized like Goethe A1: Hören, Lesen, Schreiben, and Sprechen. Its favourite topics are housing and city life: apartment notices, transport, shops, and directions. This mock exam practises exactly those.",
        },
        {
          type: "table",
          caption: "telc topics",
          head: ["Topic", "Words you need"],
          rows: [
            ["Housing", "die Miete, der Vermieter, die Wohnung, der Stock"],
            ["Transport", "die Haltestelle, der Bahnsteig, die Fahrkarte"],
            ["Shops", "der Supermarkt, die Apotheke, öffnen, schließen"],
            ["Directions", "links, rechts, geradeaus, an der Ampel"],
          ],
        },
        {
          type: "tip",
          text: "telc notices are short and use the imperative: Bitte links abbiegen. Öffnungszeiten: Mo-Fr 9-18 Uhr. Learn to read the imperative in notices: it is the same form you already know.",
        },
      ],
    },
    {
      heading: "Die Wohnung",
      blocks: [
        {
          type: "paragraph",
          text: "Apartment notices are a telc classic. They are packed with abbreviations and numbers: 2-Zimmer-Wohnung, 58 qm, 3. Stock, 850 Euro kalt, zzgl. Nebenkosten.",
        },
        {
          type: "example",
          de: "2-Zimmer-Wohnung, 58 qm, Balkon, 850 Euro kalt.",
          en: "Two-room apartment, 58 sqm, balcony, 850 euros cold.",
        },
        {
          type: "example",
          de: "Die Wohnung ist im dritten Stock. Der Vermieter heißt Herr Weber.",
          en: "The apartment is on the third floor. The landlord is called Mr Weber.",
        },
      ],
    },
    {
      heading: "Unterwegs",
      blocks: [
        {
          type: "paragraph",
          text: "The transport section of telc checks directions and timetables: when the bus leaves, where the platform is, how to change trains.",
        },
        {
          type: "example",
          de: "Entschuldigung, wo ist der Bahnsteig? Gehen Sie geradeaus, dann links.",
          en: "Excuse me, where is the platform? Go straight ahead, then left.",
        },
        {
          type: "example",
          de: "Der Bus hat zehn Minuten Verspätung.",
          en: "The bus is ten minutes late.",
        },
        {
          type: "tip",
          text: "Notice the imperative inside directions: Gehen Sie geradeaus. The polite form with Sie is what appears in exam listening texts.",
        },
      ],
    },
  ],
  vocab: [
    { id: "der-vermieter", de: "der Vermieter", en: "the landlord", part: "noun m.", plural: "die Vermieter", audio: true },
    { id: "die-miete", de: "die Miete", en: "the rent", part: "noun f.", plural: "die Mieten", audio: true },
    { id: "die-nebenkosten", de: "die Nebenkosten", en: "the utilities", part: "noun pl.", audio: true },
    { id: "der-supermarkt", de: "der Supermarkt", en: "the supermarket", part: "noun m.", plural: "die Supermärkte", audio: true },
    { id: "oeffnen", de: "öffnen", en: "to open", part: "verb", audio: true },
    { id: "schliessen", de: "schließen", en: "to close", part: "verb", audio: true },
    { id: "die-oefnungszeiten", de: "die Öffnungszeiten", en: "the opening hours", part: "noun pl.", audio: true },
    { id: "die-haltestelle", de: "die Haltestelle", en: "the stop", part: "noun f.", plural: "die Haltestellen", audio: true },
    { id: "der-bahnsteig", de: "der Bahnsteig", en: "the platform", part: "noun m.", plural: "die Bahnsteige", audio: true },
    { id: "die-fahrkarte", de: "die Fahrkarte", en: "the ticket", part: "noun f.", plural: "die Fahrkarten", audio: true },
    { id: "die-verspaetung", de: "die Verspätung", en: "the delay", part: "noun f.", plural: "die Verspätungen", audio: true },
    { id: "abbiegen", de: "abbiegen", en: "to turn (a corner)", part: "verb", audio: true },
  ],
  exercises: [
    {
      id: "mc-telc-anzeige",
      type: "multiple-choice",
      title: "Teil: Lesen",
      instruction: "Read the notice and answer.",
      prompt: "In einer Anzeige steht: 2-Zimmer-Wohnung, 3. Stock. Wo ist die Wohnung?",
      options: ["im dritten Stock", "im Erdgeschoss", "im zweiten Stock"],
      correctIndex: 0,
      explain: "3. Stock means the third floor.",
    },
    {
      id: "listening-telc-hoeren",
      type: "listening",
      title: "Teil: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Der Bus hat zehn Minuten Verspätung.",
      options: [
        "Der Bus hat zehn Minuten Verspätung.",
        "Der Bus hat zehn Minuten Haltestelle.",
        "Der Zug hat zehn Minuten Verspätung.",
      ],
      correctIndex: 0,
    },
    {
      id: "fill-telc-schreiben",
      type: "fill-blank",
      title: "Teil: Schreiben",
      instruction: "Complete the housing sentences.",
      sentence: "Die Wohnung ist im dritten ___. (floor) Die Miete ist 850 Euro ___.",
      blanks: [
        { answers: ["Stock"], hint: "the floor" },
        { answers: ["kalt"], hint: "without utilities" },
      ],
    },
    {
      id: "matching-telc-lesen",
      type: "matching",
      title: "Teil: Lesen",
      instruction: "Match each word to its meaning.",
      pairs: [
        ["die Haltestelle", "the stop"],
        ["der Bahnsteig", "the platform"],
        ["die Fahrkarte", "the ticket"],
        ["die Öffnungszeiten", "the opening hours"],
        ["der Supermarkt", "the supermarket"],
      ],
    },
    {
      id: "word-order-telc",
      type: "word-order",
      title: "Teil: Sprechen",
      instruction: "Build the directions: Go straight ahead, then left.",
      chunks: ["Gehen", "Sie", "geradeaus,", "dann", "links."],
      explain: "The imperative leads, the direction follows.",
    },
    {
      id: "flashcard-telc",
      type: "flashcard",
      title: "telc-Wortschatz",
      instruction: "Say the German word out loud before revealing.",
      items: [
        { front: "die Haltestelle", back: "the stop", frontAudio: true },
        { front: "der Bahnsteig", back: "the platform", frontAudio: true },
        { front: "die Fahrkarte", back: "the ticket", frontAudio: true },
        { front: "die Miete", back: "the rent", frontAudio: true },
        { front: "der Vermieter", back: "the landlord", frontAudio: true },
        { front: "die Öffnungszeiten", back: "the opening hours", frontAudio: true },
      ],
    },
  ],
};

const goethePracticeExam: Lesson = {
  id: "goethe-a1-practice-exam",
  title: "Goethe A1 Practice Exam (100 Fragen)",
  summary: "A very detailed Goethe-standard practice exam: 100 questions across listening, reading, writing, vocabulary, and sentence building.",
  status: "ready",
  sections: [
    {
      heading: "So ist die Prüfung aufgebaut",
      blocks: [
        {
          type: "paragraph",
          text: "This practice exam mirrors the real Goethe A1 paper, part by part and question by question. It has 100 questions in five parts: Hören (listening), Lesen (reading), Schreiben (writing and grammar), Wortschatz (vocabulary), and Sätze bauen (sentence building, the writing-and-speaking skill). Work through it without notes, like the real exam, then review anything you missed.",
        },
        {
          type: "table",
          caption: "The five parts",
          head: ["Part", "Questions", "Format"],
          rows: [
            ["1. Hören", "25", "Play the audio, pick what you heard"],
            ["2. Lesen", "30", "Choose the correct answer"],
            ["3. Schreiben", "20", "Type the missing word"],
            ["4. Wortschatz", "15", "Match German and English"],
            ["5. Sätze bauen", "10", "Build the sentence in order"],
          ],
        },
        {
          type: "tip",
          text: "The real Goethe A1 exam is scored per part: you need about 60 percent in each part to pass. Aim for at least 60 percent in every part here too, and you are exam-ready.",
        },
      ],
    },
    {
      heading: "Teil 1: Hören (25 Fragen)",
      blocks: [
        {
          type: "paragraph",
          text: "In the listening part you hear short, slow sentences and pick the correct answer. The exam topics are always the everyday ones: greetings, numbers, personal data, daily routine, and directions. Tap the play button for each question.",
        },
        {
          type: "tip",
          text: "Listening strategy: read the options before you press play. You are not listening for every word, only for the one detail that separates the options.",
        },
      ],
    },
    {
      heading: "Teil 2: Lesen (30 Fragen)",
      blocks: [
        {
          type: "paragraph",
          text: "The reading part checks articles, verb forms, the cases, and everyday notices. The same grammar you practised all course appears here in exam form.",
        },
        {
          type: "tip",
          text: "Notice-reading is a Goethe speciality: Öffnungszeiten (opening hours), Eingang (entrance), Rauchen verboten (no smoking). Learn the ten most common notice words and you pick up easy points.",
        },
      ],
    },
    {
      heading: "Teil 3: Schreiben (20 Fragen)",
      blocks: [
        {
          type: "paragraph",
          text: "The writing part of the real exam asks you to fill in forms and write short sentences. Here you type the missing words into real exam sentences, exactly the words the exam expects.",
        },
        {
          type: "tip",
          text: "The exam loves forms: name, address, phone number, age. Practise typing them without thinking: Nachname, Adresse, Telefonnummer, Jahre alt.",
        },
      ],
    },
    {
      heading: "Teil 4: Wortschatz (15 Fragen)",
      blocks: [
        {
          type: "paragraph",
          text: "Vocabulary is tested through matching: a German word with its meaning. The exam's favourite fields are everyday objects, verbs and their participles, and the documents of life in Germany.",
        },
      ],
    },
    {
      heading: "Teil 5: Sätze bauen (10 Fragen)",
      blocks: [
        {
          type: "paragraph",
          text: "Sentence building trains the grammar the exam checks in speaking and writing: word order. Every sentence here follows a rule you know: verb second, time before place, participle or prefix at the end.",
        },
        {
          type: "tip",
          text: "Build each sentence out loud first, then tap the words. Speaking it forces your brain to use the word order, not just recognize it.",
        },
      ],
    },
  ],
  vocab: [
    { id: "die-pruefung", de: "die Prüfung", en: "the exam", part: "noun f.", plural: "die Prüfungen", audio: true },
    { id: "das-hoeren", de: "das Hören", en: "the listening (part)", part: "noun n.", audio: true },
    { id: "das-lesen", de: "das Lesen", en: "the reading (part)", part: "noun n.", audio: true },
    { id: "das-schreiben", de: "das Schreiben", en: "the writing (part)", part: "noun n.", audio: true },
    { id: "das-sprechen", de: "das Sprechen", en: "the speaking (part)", part: "noun n.", audio: true },
    { id: "der-termi", de: "der Termin", en: "the appointment", part: "noun m.", plural: "die Termine", audio: true },
    { id: "die-anmeldung", de: "die Anmeldung", en: "the registration", part: "noun f.", plural: "die Anmeldungen", audio: true },
    { id: "das-formular", de: "das Formular", en: "the form", part: "noun n.", plural: "die Formulare", audio: true },
    { id: "die-fahrkarte", de: "die Fahrkarte", en: "the ticket", part: "noun f.", plural: "die Fahrkarten", audio: true },
    { id: "die-oefnungszeiten", de: "die Öffnungszeiten", en: "the opening hours", part: "noun pl.", audio: true },
    { id: "der-eingang", de: "der Eingang", en: "the entrance", part: "noun m.", plural: "die Eingänge", audio: true },
    { id: "bestehen", de: "bestehen", en: "to pass (an exam)", part: "verb", audio: true },
  ],
  exercises: [
    {
      id: "hoeren-gruesse",
      type: "listening",
      title: "Hören 1: Grüße",
      instruction: "Play the audio and pick the greeting you heard. (Questions 1-5)",
      prompt: "Guten Morgen",
      options: ["Guten Morgen", "Guten Abend", "Gute Nacht"],
      correctIndex: 0,
      explain: "Question 1: the morning greeting is Guten Morgen.",
    },
    {
      id: "hoeren-zahlen",
      type: "listening",
      title: "Hören 2: Zahlen",
      instruction: "Play the audio and pick the number you heard. (Questions 6-10)",
      prompt: "fünfundzwanzig",
      options: ["fünfundzwanzig", "fünfunddreißig", "fünfundvierzig"],
      correctIndex: 0,
      explain: "Question 6: 25 is fünfundzwanzig.",
    },
    {
      id: "hoeren-daten",
      type: "listening",
      title: "Hören 3: Persönliche Daten",
      instruction: "Play the audio and pick the sentence you heard. (Questions 11-15)",
      prompt: "Mein Name ist Anna Müller.",
      options: [
        "Mein Name ist Anna Müller.",
        "Mein Name ist Anna Maier.",
        "Mein Name ist Anna Schmidt.",
      ],
      correctIndex: 0,
      explain: "Question 11: the name heard is Müller.",
    },
    {
      id: "hoeren-tagesablauf",
      type: "listening",
      title: "Hören 4: Tagesablauf",
      instruction: "Play the audio and pick the sentence you heard. (Questions 16-20)",
      prompt: "Ich stehe um sechs Uhr auf.",
      options: [
        "Ich stehe um sechs Uhr auf.",
        "Ich stehe um sieben Uhr auf.",
        "Ich stehe um sechs Uhr früh auf.",
      ],
      correctIndex: 0,
      explain: "Question 16: the time heard is six o'clock.",
    },
    {
      id: "hoeren-richtung",
      type: "listening",
      title: "Hören 5: Richtungen",
      instruction: "Play the audio and pick the direction you heard. (Questions 21-25)",
      prompt: "An der Ampel links.",
      options: ["An der Ampel links.", "An der Ampel rechts.", "An der Kreuzung links."],
      correctIndex: 0,
      explain: "Question 21: at the traffic light, turn left.",
    },
    {
      id: "lesen-artikel",
      type: "multiple-choice",
      title: "Lesen 1: Artikel (Fragen 26-30)",
      instruction: "Choose the correct article.",
      prompt: "Ich habe ___ Termin beim Bürgeramt.",
      options: ["einen", "ein", "eine"],
      correctIndex: 0,
      explain: "Question 26: Termin is masculine, accusative: einen.",
    },
    {
      id: "lesen-verben",
      type: "multiple-choice",
      title: "Lesen 2: Verbformen (Fragen 31-35)",
      instruction: "Choose the correct verb form.",
      prompt: "Er ___ nach Berlin.",
      options: ["fährt", "fahrt", "fahren"],
      correctIndex: 0,
      explain: "Question 31: er takes fährt with the vowel change.",
    },
    {
      id: "lesen-faelle",
      type: "multiple-choice",
      title: "Lesen 3: Fälle (Fragen 36-40)",
      instruction: "Choose the correct case form.",
      prompt: "Ich gebe ___ Kind einen Apfel.",
      options: ["dem", "den", "der"],
      correctIndex: 0,
      explain: "Question 36: the receiver is dative, neuter: dem Kind.",
    },
    {
      id: "lesen-woerter",
      type: "multiple-choice",
      title: "Lesen 4: Wortwahl (Fragen 41-45)",
      instruction: "Choose the word that fits.",
      prompt: "Ich brauche eine ___ nach Berlin.",
      options: ["Fahrkarte", "Haltestelle", "Straße"],
      correctIndex: 0,
      explain: "Question 41: the ticket is die Fahrkarte.",
    },
    {
      id: "lesen-schilder",
      type: "multiple-choice",
      title: "Lesen 5: Schilder (Fragen 46-50)",
      instruction: "Read the notice and choose the meaning.",
      prompt: "Auf einem Schild steht: Rauchen verboten. Was heißt das?",
      options: ["No smoking", "No parking", "No entry"],
      correctIndex: 0,
      explain: "Question 46: Rauchen verboten means no smoking.",
    },
    {
      id: "lesen-grammatik",
      type: "multiple-choice",
      title: "Lesen 6: Grammatik (Fragen 51-55)",
      instruction: "Choose the correct form.",
      prompt: "Ich habe gestern Pizza ___.",
      options: ["gegessen", "essen", "gegessen gegangen"],
      correctIndex: 0,
      explain: "Question 51: the participle of essen is gegessen.",
    },
    {
      id: "schreiben-daten",
      type: "fill-blank",
      title: "Schreiben 1: Formular (Fragen 56-59)",
      instruction: "Type the missing word, like filling in a form.",
      sentence: "Mein ___ ist Anna. Meine ___ ist Hauptstraße 5. Meine ___nummer ist 0172. Ich bin 25 ___ alt.",
      blanks: [
        { answers: ["Vorname"], hint: "first name" },
        { answers: ["Adresse"], hint: "address" },
        { answers: ["Telefon"], hint: "phone" },
        { answers: ["Jahre"], hint: "years old" },
      ],
    },
    {
      id: "schreiben-perfekt",
      type: "fill-blank",
      title: "Schreiben 2: Perfekt (Fragen 60-63)",
      instruction: "Type the missing helper or participle.",
      sentence: "Ich ___ Anna. (sein) Wir ___ gestern nach Berlin ___. Ich habe einen Film ___. Er ___ einen Bruder.",
      blanks: [
        { answers: ["bin"], hint: "sein, ich" },
        { answers: ["sind"], hint: "movement, wir" },
        { answers: ["gefahren"], hint: "participle of fahren" },
        { answers: ["gesehen"], hint: "participle of sehen" },
        { answers: ["hat"], hint: "haben, er" },
      ],
    },
    {
      id: "schreiben-praepositionen",
      type: "fill-blank",
      title: "Schreiben 3: Präpositionen (Fragen 64-67)",
      instruction: "Type the missing preposition.",
      sentence: "Ich fahre ___ Berlin. Wir gehen ___ Kino. Der Termin ist ___ Montag. Ich komme ___ Italien.",
      blanks: [
        { answers: ["nach"], hint: "city, no article" },
        { answers: ["ins"], hint: "in + das" },
        { answers: ["am"], hint: "an + dem, day" },
        { answers: ["aus"], hint: "origin" },
      ],
    },
    {
      id: "schreiben-modalverben",
      type: "fill-blank",
      title: "Schreiben 4: Modalverben (Fragen 68-71)",
      instruction: "Type the missing verb form.",
      sentence: "Ich ___ gut kochen. Ich muss um sieben Uhr ___. Du ___ mehr Wasser trinken. Ich ___ dich an.",
      blanks: [
        { answers: ["kann"], hint: "ability, ich" },
        { answers: ["aufstehen"], hint: "separable infinitive" },
        { answers: ["sollst"], hint: "should, du" },
        { answers: ["rufe"], hint: "anrufen, ich" },
      ],
    },
    {
      id: "schreiben-fragen",
      type: "fill-blank",
      title: "Schreiben 5: Fragen (Fragen 72-75)",
      instruction: "Type the missing question or negation word.",
      sentence: "___ kommst du? Ich habe ___ Auto. Nein, ich wohne ___ in Berlin. ___ du Deutsch?",
      blanks: [
        { answers: ["Woher"], hint: "origin" },
        { answers: ["kein"], hint: "negation before noun" },
        { answers: ["nicht"], hint: "negation of the place" },
        { answers: ["Lernst"], hint: "yes/no question, verb first" },
      ],
    },
    {
      id: "wortschatz-alltag",
      type: "matching",
      title: "Wortschatz 1: Alltag (Fragen 76-80)",
      instruction: "Match each German word to its meaning.",
      pairs: [
        ["der Tisch", "the table"],
        ["die Lampe", "the lamp"],
        ["das Bett", "the bed"],
        ["die Küche", "the kitchen"],
        ["der Bahnhof", "the station"],
      ],
    },
    {
      id: "wortschatz-partizipien",
      type: "matching",
      title: "Wortschatz 2: Partizipien (Fragen 81-85)",
      instruction: "Match each infinitive to its participle.",
      pairs: [
        ["essen", "gegessen"],
        ["trinken", "getrunken"],
        ["sehen", "gesehen"],
        ["schreiben", "geschrieben"],
        ["fahren", "gefahren"],
      ],
    },
    {
      id: "wortschatz-dokumente",
      type: "matching",
      title: "Wortschatz 3: Dokumente (Fragen 86-90)",
      instruction: "Match each word to its meaning.",
      pairs: [
        ["die Anmeldung", "the registration"],
        ["das Formular", "the form"],
        ["der Termin", "the appointment"],
        ["der Aufenthaltstitel", "the residence permit"],
        ["die Fahrkarte", "the ticket"],
      ],
    },
    {
      id: "satz-1",
      type: "word-order",
      title: "Satz 1 (Frage 91)",
      instruction: "Build the sentence: My name is Anna.",
      chunks: ["Ich", "heiße", "Anna."],
      explain: "The verb heiße stays in second position.",
    },
    {
      id: "satz-2",
      type: "word-order",
      title: "Satz 2 (Frage 92)",
      instruction: "Build the sentence: I come from Italy.",
      chunks: ["Ich", "komme", "aus", "Italien."],
      explain: "Origin takes aus: aus Italien.",
    },
    {
      id: "satz-3",
      type: "word-order",
      title: "Satz 3 (Frage 93)",
      instruction: "Build the sentence: I would like a coffee.",
      chunks: ["Ich", "möchte", "einen", "Kaffee."],
      explain: "The modal is second; the object follows.",
    },
    {
      id: "satz-4",
      type: "word-order",
      title: "Satz 4 (Frage 94)",
      instruction: "Build the sentence: The train departs at ten o'clock.",
      chunks: ["Der", "Zug", "fährt", "um", "zehn", "Uhr", "ab."],
      explain: "The separable prefix ab closes the sentence.",
    },
    {
      id: "satz-5",
      type: "word-order",
      title: "Satz 5 (Frage 95)",
      instruction: "Build the sentence: We drove to Berlin yesterday.",
      chunks: ["Wir", "sind", "gestern", "nach", "Berlin", "gefahren."],
      explain: "Movement takes sein; the participle closes.",
    },
    {
      id: "satz-6",
      type: "word-order",
      title: "Satz 6 (Frage 96)",
      instruction: "Build the sentence: Can you help me?",
      chunks: ["Kannst", "du", "mir", "helfen?"],
      explain: "The modal leads the question; helfen closes it.",
    },
    {
      id: "satz-7",
      type: "word-order",
      title: "Satz 7 (Frage 97)",
      instruction: "Build the sentence: I watched a film yesterday.",
      chunks: ["Ich", "habe", "gestern", "einen", "Film", "gesehen."],
      explain: "The participle gesehen closes the bracket.",
    },
    {
      id: "satz-8",
      type: "word-order",
      title: "Satz 8 (Frage 98)",
      instruction: "Build the sentence: The apartment is on the third floor.",
      chunks: ["Die", "Wohnung", "ist", "im", "dritten", "Stock."],
      explain: "The dative phrase im dritten Stock closes the sentence.",
    },
    {
      id: "satz-9",
      type: "word-order",
      title: "Satz 9 (Frage 99)",
      instruction: "Build the sentence: I learn German because I live in Germany.",
      chunks: ["Ich", "lerne", "Deutsch,", "denn", "ich", "lebe", "in", "Deutschland."],
      explain: "denn keeps the second verb in position two.",
    },
    {
      id: "satz-10",
      type: "word-order",
      title: "Satz 10 (Frage 100)",
      instruction: "Build the sentence: On Monday I work.",
      chunks: ["Am", "Montag", "arbeite", "ich."],
      explain: "The fronted time forces the inversion.",
    },
  ],
};

export const freizeitUndReisen: Unit = {
  id: "freizeit-und-reisen",
  title: "Freizeit und Reisen",
  theme: "Free time and travel",
  lessons: [
    hobbysUndSport,
    nachBerlin,
    reisen,
    einladungen,
    wiederholung,
    goetheMockExam,
    telcMockExam,
    goethePracticeExam,
  ],
};