import type { Lesson, Unit } from "../../schema";

const hobbysUndSport: Lesson = {
  id: "hobbys-und-sport",
  title: "Hobbys und Sport",
  summary: "Free time activities and sports.",
  status: "ready",
  sections: [
    {
      heading: "Die Sportarten",
      blocks: [
        {
          type: "table",
          caption: "Sports",
          head: ["German", "English", "Verb"],
          rows: [
            ["Fußball", "football", "Fußball spielen"],
            ["Tennis", "tennis", "Tennis spielen"],
            ["Basketball", "basketball", "Basketball spielen"],
            ["Tischtennis", "table tennis", "Tischtennis spielen"],
            ["Schwimmen", "swimming", "schwimmen gehen"],
            ["Joggen", "jogging", "joggen gehen"],
            ["Radfahren", "cycling", "Rad fahren"],
            ["Yoga", "yoga", "Yoga machen"],
            ["Gymnastik", "gymnastics", "Gymnastik machen"],
            ["Tanzen", "dancing", "tanzen gehen"],
          ],
        },
        {
          type: "tip",
          text: "spielen for ball games, machen for yoga and gymnastics, gehen for activities with a destination: schwimmen gehen, tanzen gehen.",
        },
      ],
    },
    {
      heading: "Was machst du am Wochenende?",
      blocks: [
        {
          type: "example",
          de: "Ich spiele am Wochenende Fußball.",
          en: "I play football on the weekend.",
        },
        {
          type: "example",
          de: "Wir gehen jeden Samstag schwimmen.",
          en: "We go swimming every Saturday.",
        },
        {
          type: "example",
          de: "Sie macht dreimal pro Woche Yoga.",
          en: "She does yoga three times a week.",
        },
        {
          type: "tip",
          text: "Frequency: jeden Tag (every day), einmal pro Woche (once a week), dreimal pro Woche (three times a week).",
        },
      ],
    },
  ],
  vocab: [
    { id: "fussball", de: "Fußball spielen", en: "to play football", part: "phrase", phrase: true, audio: true },
    { id: "tennis", de: "Tennis spielen", en: "to play tennis", part: "phrase", phrase: true, audio: true },
    { id: "basketball", de: "Basketball spielen", en: "to play basketball", part: "phrase", phrase: true, audio: true },
    { id: "schwimmen-gehen", de: "schwimmen gehen", en: "to go swimming", part: "phrase", phrase: true, audio: true },
    { id: "joggen", de: "joggen", en: "to jog", part: "verb", audio: true },
    { id: "radfahren", de: "Rad fahren", en: "to cycle", part: "phrase", phrase: true, audio: true },
    { id: "yoga", de: "Yoga machen", en: "to do yoga", part: "phrase", phrase: true, audio: true },
    { id: "tanzen", de: "tanzen gehen", en: "to go dancing", part: "phrase", phrase: true, audio: true },
    { id: "der-sport", de: "der Sport", en: "the sport", part: "noun m.", plural: "die Sportarten", audio: true },
    { id: "jeden-tag", de: "jeden Tag", en: "every day", part: "phrase", phrase: true, audio: true },
    { id: "pro-woche", de: "dreimal pro Woche", en: "three times a week", part: "phrase", phrase: true, audio: true },
    { id: "am-wochenende", de: "am Wochenende", en: "on the weekend", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "mc-sport",
      type: "multiple-choice",
      title: "Der Sport",
      instruction: "Choose the right verb.",
      prompt: "Sie ___ Yoga.",
      options: ["macht", "spielt", "geht"],
      correctIndex: 0,
      explain: "Yoga takes machen: Yoga machen.",
    },
    {
      id: "listening-sport",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the activity you heard.",
      prompt: "schwimmen gehen",
      options: ["schwimmen gehen", "tanzen gehen", "joggen gehen"],
      correctIndex: 0,
    },
    {
      id: "fill-sport",
      type: "fill-blank",
      title: "Der Sport",
      instruction: "Complete the sentences.",
      sentence: "Wir ___ jeden Samstag schwimmen. Ich ___ Fußball.",
      blanks: [
        { answers: ["gehen"], hint: "schwimmen gehen" },
        { answers: ["spiele"], hint: "Fußball spielen" },
      ],
    },
    {
      id: "matching-sport",
      type: "matching",
      title: "Sportarten",
      instruction: "Match each sport to its meaning.",
      pairs: [
        ["Fußball spielen", "to play football"],
        ["schwimmen gehen", "to go swimming"],
        ["Yoga machen", "to do yoga"],
        ["Rad fahren", "to cycle"],
        ["tanzen gehen", "to go dancing"],
      ],
    },
    {
      id: "word-order-sport",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: We go swimming every Saturday.",
      chunks: ["Wir", "gehen", "jeden", "Samstag", "schwimmen."],
      explain: "The destination infinitive closes the sentence.",
    },
    {
      id: "flashcard-sport",
      type: "flashcard",
      title: "Sportkarten",
      instruction: "Say the German out loud before revealing.",
      items: [
        { front: "Fußball spielen", back: "to play football", frontAudio: true },
        { front: "Tennis spielen", back: "to play tennis", frontAudio: true },
        { front: "schwimmen gehen", back: "to go swimming", frontAudio: true },
        { front: "Rad fahren", back: "to cycle", frontAudio: true },
        { front: "Yoga machen", back: "to do yoga", frontAudio: true },
        { front: "am Wochenende", back: "on the weekend", frontAudio: true },
      ],
    },
  ],
};

const nachBerlin: Lesson = {
  id: "nach-berlin-oder-in-die-schweiz",
  title: "Nach Berlin oder in die Schweiz?",
  summary: "nach, in, and aus with countries and cities.",
  status: "ready",
  sections: [
    {
      heading: "Die Regel",
      blocks: [
        {
          type: "table",
          caption: "nach, in, aus",
          head: ["Target", "Preposition", "Example"],
          rows: [
            ["city", "nach", "nach Berlin"],
            ["country without article", "nach", "nach Deutschland"],
            ["article country", "in", "in die Schweiz, in den Iran, in die USA"],
            ["origin", "aus", "aus Berlin, aus der Schweiz"],
          ],
        },
        {
          type: "tip",
          text: "Article countries are few: die Schweiz, die Türkei, die USA, der Iran, die Niederlande, der Irak. Everything else takes nach.",
        },
      ],
    },
    {
      heading: "Im Alltag",
      blocks: [
        {
          type: "example",
          de: "Ich fahre nach Berlin. Er fliegt nach Spanien.",
          en: "I drive to Berlin. He flies to Spain.",
        },
        {
          type: "example",
          de: "Wir fahren in die Schweiz. Sie fliegt in die Türkei.",
          en: "We drive to Switzerland. She flies to Turkey.",
        },
        {
          type: "example",
          de: "Ich komme aus der Schweiz. Er kommt aus Berlin.",
          en: "I come from Switzerland. He comes from Berlin.",
        },
        {
          type: "tip",
          text: "Memory hook: no article in the name, no article with nach. Article in the name, article with in and aus.",
        },
      ],
    },
  ],
  vocab: [
    { id: "nach-berlin", de: "nach Berlin", en: "to Berlin", part: "phrase", phrase: true, audio: true },
    { id: "nach-deutschland", de: "nach Deutschland", en: "to Germany", part: "phrase", phrase: true, audio: true },
    { id: "in-die-schweiz", de: "in die Schweiz", en: "to Switzerland", part: "phrase", phrase: true, audio: true },
    { id: "in-den-iran", de: "in den Iran", en: "to Iran", part: "phrase", phrase: true, audio: true },
    { id: "in-die-usa", de: "in die USA", en: "to the USA", part: "phrase", phrase: true, audio: true },
    { id: "aus-der-schweiz", de: "aus der Schweiz", en: "from Switzerland", part: "phrase", phrase: true, audio: true },
    { id: "aus-berlin", de: "aus Berlin", en: "from Berlin", part: "phrase", phrase: true, audio: true },
    { id: "fliegen", de: "fliegen", en: "to fly", part: "verb", audio: true },
    { id: "fahren", de: "fahren", en: "to drive, travel", part: "verb", audio: true },
  ],
  exercises: [
    {
      id: "mc-nach-in",
      type: "multiple-choice",
      title: "Nach oder in?",
      instruction: "Choose the correct preposition.",
      prompt: "Ich fliege ___ die Schweiz.",
      options: ["in", "nach", "aus"],
      correctIndex: 0,
      explain: "The Schweiz has an article, so in.",
    },
    {
      id: "listening-nach-in",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the phrase you heard.",
      prompt: "nach Spanien",
      options: ["nach Spanien", "in die Schweiz", "aus Spanien"],
      correctIndex: 0,
    },
    {
      id: "fill-nach-in",
      type: "fill-blank",
      title: "Die Präposition",
      instruction: "Complete with nach, in, or aus.",
      sentence: "Ich fahre ___ Berlin. Wir fliegen ___ die Türkei.",
      blanks: [
        { answers: ["nach"], hint: "city" },
        { answers: ["in"], hint: "article country" },
      ],
    },
    {
      id: "matching-nach-in",
      type: "matching",
      title: "Ziele",
      instruction: "Match each phrase to its meaning.",
      pairs: [
        ["nach Berlin", "to Berlin"],
        ["in die Schweiz", "to Switzerland"],
        ["aus Berlin", "from Berlin"],
        ["in die USA", "to the USA"],
        ["nach Deutschland", "to Germany"],
      ],
    },
    {
      id: "word-order-nach-in",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: We drive to Switzerland.",
      chunks: ["Wir", "fahren", "in", "die", "Schweiz."],
      explain: "The destination follows the verb.",
    },
    {
      id: "flashcard-nach-in",
      type: "flashcard",
      title: "Zielkarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "nach Berlin", back: "to Berlin", frontAudio: true },
        { front: "nach Deutschland", back: "to Germany", frontAudio: true },
        { front: "in die Schweiz", back: "to Switzerland", frontAudio: true },
        { front: "in die USA", back: "to the USA", frontAudio: true },
        { front: "aus der Schweiz", back: "from Switzerland", frontAudio: true },
        { front: "aus Berlin", back: "from Berlin", frontAudio: true },
      ],
    },
  ],
};

const reisen: Lesson = {
  id: "reisen",
  title: "Reisen",
  summary: "Travel vocabulary and vowel-changing verbs: fahren, lesen, sprechen.",
  status: "ready",
  sections: [
    {
      heading: "Die Reise",
      blocks: [
        {
          type: "table",
          caption: "Travel vocabulary",
          head: ["German", "English"],
          rows: [
            ["die Reise", "the trip"],
            ["der Urlaub", "the vacation"],
            ["der Koffer", "the suitcase"],
            ["das Gepäck", "the luggage"],
            ["das Flugzeug", "the airplane"],
            ["der Flughafen", "the airport"],
            ["das Hotel", "the hotel"],
            ["der Pass", "the passport"],
            ["das Ticket", "the ticket"],
          ],
        },
        {
          type: "tip",
          text: "Urlaub is only vacation time, Reise is the journey itself. Im Urlaub fahre ich nach Italien. Die Reise dauert drei Stunden.",
        },
      ],
    },
    {
      heading: "Vokalwechselnde Verben",
      blocks: [
        {
          type: "paragraph",
          text: "Strong verbs change their vowel in the du and er/sie/es forms. The most useful six for travel:",
        },
        {
          type: "table",
          caption: "Vowel-changing verbs",
          head: ["Infinitive", "du", "er / sie / es", "English"],
          rows: [
            ["fahren", "fährst", "fährt", "to drive, travel"],
            ["schlafen", "schläfst", "schläft", "to sleep"],
            ["lesen", "liest", "liest", "to read"],
            ["sprechen", "sprichst", "spricht", "to speak"],
            ["essen", "isst", "isst", "to eat"],
            ["nehmen", "nimmst", "nimmt", "to take"],
          ],
        },
        {
          type: "example",
          de: "Er fährt nach Italien. Du sprichst sehr gut Deutsch.",
          en: "He drives to Italy. You speak German very well.",
        },
        {
          type: "tip",
          text: "The change is a > ä (fahren) or e > i(e) (sprechen, lesen, nehmen). The infinitive and the wir/ihr forms keep the original vowel.",
        },
      ],
    },
  ],
  vocab: [
    { id: "die-reise", de: "die Reise", en: "the trip", part: "noun f.", plural: "die Reisen", audio: true },
    { id: "der-urlaub", de: "der Urlaub", en: "the vacation", part: "noun m.", plural: "die Urlaube", audio: true },
    { id: "der-koffer", de: "der Koffer", en: "the suitcase", part: "noun m.", plural: "die Koffer", audio: true },
    { id: "das-gepaeck", de: "das Gepäck", en: "the luggage", part: "noun n.", audio: true },
    { id: "das-flugzeug", de: "das Flugzeug", en: "the airplane", part: "noun n.", plural: "die Flugzeuge", audio: true },
    { id: "der-flughafen", de: "der Flughafen", en: "the airport", part: "noun m.", plural: "die Flughäfen", audio: true },
    { id: "das-hotel", de: "das Hotel", en: "the hotel", part: "noun n.", plural: "die Hotels", audio: true },
    { id: "der-pass", de: "der Pass", en: "the passport", part: "noun m.", plural: "die Pässe", audio: true },
    { id: "fahren", de: "fahren", en: "to drive, travel", part: "verb", audio: true },
    { id: "du-faehrst", de: "du fährst", en: "you drive, travel", part: "phrase", phrase: true, audio: true },
    { id: "er-faehrt", de: "er fährt", en: "he drives, travels", part: "phrase", phrase: true, audio: true },
    { id: "du-sprichst", de: "du sprichst", en: "you speak", part: "phrase", phrase: true, audio: true },
    { id: "der-dauern", de: "dauern", en: "to last", part: "verb", audio: true },
  ],
  exercises: [
    {
      id: "mc-reisen",
      type: "multiple-choice",
      title: "Die Form",
      instruction: "Choose the correct verb form.",
      prompt: "Er ___ nach Italien. (fahren)",
      options: ["fährt", "fahrt", "fahren"],
      correctIndex: 0,
      explain: "er takes fährt with the vowel change.",
    },
    {
      id: "listening-reisen",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Er fährt nach Italien.",
      options: ["Er fährt nach Italien.", "Er fliegt nach Italien.", "Er fährt nach Spanien."],
      correctIndex: 0,
    },
    {
      id: "fill-reisen",
      type: "fill-blank",
      title: "Die Reise",
      instruction: "Complete the sentences.",
      sentence: "Er ___ nach Spanien. (fahren) Die Reise ___ drei Stunden.",
      blanks: [
        { answers: ["fährt"], hint: "fahren, er" },
        { answers: ["dauert"], hint: "to last" },
      ],
    },
    {
      id: "matching-reisen",
      type: "matching",
      title: "Reisevokabular",
      instruction: "Match each German word to its meaning.",
      pairs: [
        ["der Koffer", "the suitcase"],
        ["das Gepäck", "the luggage"],
        ["der Flughafen", "the airport"],
        ["der Pass", "the passport"],
        ["der Urlaub", "the vacation"],
      ],
    },
    {
      id: "word-order-reisen",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: In vacation I drive to Italy.",
      chunks: ["Im", "Urlaub", "fahre", "ich", "nach", "Italien."],
      explain: "The fronted time forces the inversion.",
    },
    {
      id: "flashcard-reisen",
      type: "flashcard",
      title: "Reisekarten",
      instruction: "Say the German out loud before revealing.",
      items: [
        { front: "der Koffer", back: "the suitcase", frontAudio: true },
        { front: "der Flughafen", back: "the airport", frontAudio: true },
        { front: "der Pass", back: "the passport", frontAudio: true },
        { front: "er fährt", back: "he drives", frontAudio: true },
        { front: "du sprichst", back: "you speak", frontAudio: true },
        { front: "im Urlaub", back: "on vacation", frontAudio: true },
      ],
    },
  ],
};

const einladungen: Lesson = {
  id: "einladungen",
  title: "Einladungen",
  summary: "Invitations: Wann? Wo? Um wie viel Uhr?",
  status: "ready",
  sections: [
    {
      heading: "Einladen",
      blocks: [
        {
          type: "table",
          caption: "Inviting and answering",
          head: ["German", "English"],
          rows: [
            ["Kommst du mit?", "Are you coming along?"],
            ["Möchtest du mitkommen?", "Would you like to come?"],
            ["Ich lade dich ein.", "I am inviting you."],
            ["Wir treffen uns am Samstag.", "We are meeting on Saturday."],
            ["Wann und wo?", "When and where?"],
            ["Um wie viel Uhr?", "At what time?"],
            ["Das freut mich!", "I am happy about that!"],
            ["Leider kann ich nicht.", "Unfortunately I cannot."],
            ["Ich habe keine Zeit.", "I have no time."],
          ],
        },
        {
          type: "tip",
          text: "einladen is separable: Ich lade dich ein. The fixed question trio: Wann? Wo? Um wie viel Uhr?",
        },
      ],
    },
    {
      heading: "Der Dialog",
      blocks: [
        {
          type: "example",
          de: "Anna: Hey, ich habe am Samstag Geburtstag. Möchtest du kommen? Jonas: Ja, gerne! Wann und wo? Anna: Um sieben Uhr bei mir zu Hause.",
          en: "Anna: Hey, it is my birthday on Saturday. Would you like to come? Jonas: Yes, gladly! When and where? Anna: At seven at my place.",
        },
        {
          type: "example",
          de: "Leider kann ich nicht kommen. Ich habe schon einen Termin.",
          en: "Unfortunately I cannot come. I already have an appointment.",
        },
      ],
    },
  ],
  vocab: [
    { id: "einladen", de: "einladen", en: "to invite", part: "verb", audio: true },
    { id: "mitkommen", de: "mitkommen", en: "to come along", part: "verb", audio: true },
    { id: "die-einladung", de: "die Einladung", en: "the invitation", part: "noun f.", plural: "die Einladungen", audio: true },
    { id: "sich-treffen", de: "sich treffen", en: "to meet (each other)", part: "verb", audio: true },
    { id: "das-freut-mich", de: "Das freut mich!", en: "I am happy about that!", part: "phrase", phrase: true, audio: true },
    { id: "leider", de: "leider", en: "unfortunately", part: "adverb", audio: true },
    { id: "keine-zeit", de: "Ich habe keine Zeit.", en: "I have no time.", part: "phrase", phrase: true, audio: true },
    { id: "gern", de: "Ja, gerne!", en: "Yes, gladly!", part: "phrase", phrase: true, audio: true },
    { id: "zu-hause", de: "bei mir zu Hause", en: "at my place", part: "phrase", phrase: true, audio: true },
    { id: "die-feier", de: "die Feier", en: "the party", part: "noun f.", plural: "die Feiern", audio: true },
  ],
  exercises: [
    {
      id: "mc-einladung",
      type: "multiple-choice",
      title: "Die Einladung",
      instruction: "Choose the correct response.",
      prompt: "Möchtest du mitkommen?",
      options: ["Ja, gerne!", "Das freut mich, aber nein.", "Ich habe keine Zeit, gerne!"],
      correctIndex: 0,
      explain: "The natural yes is Ja, gerne!",
    },
    {
      id: "listening-einladung",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Wir treffen uns am Samstag um sieben.",
      options: [
        "Wir treffen uns am Samstag um sieben.",
        "Wir treffen uns am Sonntag um sieben.",
        "Wir treffen uns am Samstag um acht.",
      ],
      correctIndex: 0,
    },
    {
      id: "fill-einladung",
      type: "fill-blank",
      title: "Einladen",
      instruction: "Complete the sentences.",
      sentence: "Ich ___ dich ein. (invite) Leider kann ich nicht ___.",
      blanks: [
        { answers: ["lade"], hint: "einladen, ich" },
        { answers: ["kommen"], hint: "cannot come" },
      ],
    },
    {
      id: "matching-einladung",
      type: "matching",
      title: "Sätze",
      instruction: "Match each German phrase to its meaning.",
      pairs: [
        ["Kommst du mit?", "Are you coming along?"],
        ["Ich lade dich ein.", "I am inviting you."],
        ["Das freut mich!", "I am happy about that!"],
        ["Leider kann ich nicht.", "Unfortunately I cannot."],
        ["Um wie viel Uhr?", "At what time?"],
      ],
    },
    {
      id: "word-order-einladung",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: We meet on Saturday at seven.",
      chunks: ["Wir", "treffen", "uns", "am", "Samstag", "um", "sieben."],
      explain: "Time comes first: day, then clock time.",
    },
    {
      id: "flashcard-einladung",
      type: "flashcard",
      title: "Einladungskarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "Möchtest du mitkommen?", back: "Would you like to come?", frontAudio: true },
        { front: "Ich lade dich ein.", back: "I am inviting you.", frontAudio: true },
        { front: "Das freut mich!", back: "I am happy about that!", frontAudio: true },
        { front: "Leider kann ich nicht.", back: "Unfortunately I cannot.", frontAudio: true },
        { front: "Ja, gerne!", back: "Yes, gladly!", frontAudio: true },
        { front: "Wann und wo?", back: "When and where?", frontAudio: true },
      ],
    },
  ],
};

export const freizeitUndReisen: Unit = {
  id: "freizeit-und-reisen",
  title: "Freizeit und Reisen",
  theme: "Free time and travel",
  lessons: [
    hobbysUndSport,
    nachBerlin,
    reisen,
    einladungen,
  ],
};