import type { Lesson, Unit } from "../../schema";
import { goethePracticeExam } from "./exams/goethe-practice-exam";

export const hobbysUndSport: Lesson = {
  id: "hobbys-und-sport",
  title: "Hobbys und Sport",
  summary:
    "The complete hobbies and sport for A1: the activity verbs, the sport articles, the like and dislike patterns, and the free time dialogue.",
  status: "ready",
  sections: [
    {
      heading: "Die Hobbys",
      blocks: [
        {
          type: "paragraph",
          text: "The hobbies (die Hobbys) use two patterns: machen with feminine nouns (Ich mache Musik) and spielen with games and instruments (Ich spiele Fußball). The question: Was machst du in deiner Freizeit? (What do you do in your free time?).",
        },
        {
          type: "table",
          caption: "The hobbies",
          head: ["German", "English", "Verb"],
          rows: [
            ["Musik machen", "to make music", "machen"],
            ["Sport machen", "to do sport", "machen"],
            ["Fotos machen", "to take photos", "machen"],
            ["Fußball spielen", "to play football", "spielen"],
            ["Klavier spielen", "to play piano", "spielen"],
            ["Gitarre spielen", "to play guitar", "spielen"],
            ["lesen", "to read", "lesen"],
            ["schwimmen", "to swim", "schwimmen"],
            ["kochen", "to cook", "kochen"],
          ],
        },
        {
          type: "example",
          de: "In meiner Freizeit mache ich Sport, spiele Gitarre und lese Bücher.",
          en: "The hobby list.",
        },
        {
          type: "tip",
          text: "The hobby pair: machen for activities, spielen for games and instruments. Ich mache Sport, ich spiele Fußball.",
        },
      ],
    },
    {
      heading: "Der Sport",
      blocks: [
        {
          type: "paragraph",
          text: "The sports (der Sport): Fußball (football), Tennis (tennis), Schwimmen (swimming), Radfahren (cycling), Joggen (jogging), Volleyball (volleyball). The verb pattern: Fußball spielen, Tennis spielen, schwimmen, Rad fahren. The question: Welchen Sport machst du? (Which sport do you do?).",
        },
        {
          type: "table",
          caption: "The sports",
          head: ["Sport", "English", "Verb"],
          rows: [
            ["Fußball", "football", "Fußball spielen"],
            ["Tennis", "tennis", "Tennis spielen"],
            ["Volleyball", "volleyball", "Volleyball spielen"],
            ["Schwimmen", "swimming", "schwimmen"],
            ["Radfahren", "cycling", "Rad fahren"],
            ["Joggen", "jogging", "joggen"],
            ["Wandern", "hiking", "wandern"],
            ["Tanzen", "dancing", "tanzen"],
          ],
        },
        {
          type: "example",
          de: "Ich spiele am Wochenende Fußball und schwimme im Sommer im See.",
          en: "The sport sentences.",
        },
        {
          type: "tip",
          text: "The sport verb: spielen for ball games, the bare verb for the rest. Fußball spielen, schwimmen, Rad fahren.",
        },
      ],
    },
    {
      heading: "Mögen und nicht mögen",
      blocks: [
        {
          type: "paragraph",
          text: "Likes and dislikes run on mögen and nicht mögen: Ich mag Fußball (I like football), Ich mag keine Musik (I do not like music). The question: Magst du ...? The answer: Ja, ich mag ... or Nein, ich mag ... nicht.",
        },
        {
          type: "table",
          caption: "Likes and dislikes",
          head: ["German", "English"],
          rows: [
            ["Ich mag Fußball.", "I like football."],
            ["Ich mag keine Musik.", "I do not like music."],
            ["Magst du Sport?", "Do you like sport?"],
            ["Ja, ich mag Sport.", "Yes, I like sport."],
            ["Nein, ich mag keinen Sport.", "No, I do not like sport."],
            ["Ich spiele gern Fußball.", "I like playing football."],
            ["Ich schwimme nicht gern.", "I do not like swimming."],
          ],
        },
        {
          type: "example",
          de: "Magst du Sport? Ja, ich mag Fußball und spiele gern Tennis. Aber ich schwimme nicht gern.",
          en: "The like dialogue.",
        },
        {
          type: "tip",
          text: "The gern pattern: Ich spiele gern (I like to play), Ich schwimme nicht gern (I do not like to swim). gern makes the like.",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: machen/spielen mix, the gern position, and the keine negation.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["machen/spielen mix", "Ich mache Fußball.", "Ich spiele Fußball.", "ball games take spielen"],
            ["gern position", "Ich gern spiele Fußball.", "Ich spiele gern Fußball.", "gern follows the verb"],
            ["keine negation", "Ich mag nicht Musik.", "Ich mag keine Musik.", "nouns need kein/keine"],
            ["sport article", "der Sport? Ja, der Sport.", "der Sport", "Sport is masculine"],
            ["freizeit phrase", "in deiner Freizeit? Ja.", "in meiner Freizeit", "the freetime phrase is fixed"],
          ],
        },
        {
          type: "tip",
          text: "The hobby topic is a script: machen/spielen + activity, gern for likes, and the pair mag ... / mag ... nicht.",
        },
      ],
    },
  ],
  vocab: [
    { id: "das-hobby", de: "das Hobby", en: "the hobby", part: "noun n.", plural: "die Hobbys", audio: true },
    { id: "der-sport", de: "der Sport", en: "the sport", part: "noun m.", audio: true },
    { id: "die-freizeit", de: "die Freizeit", en: "the free time", part: "noun f.", audio: true },
    { id: "der-fussball", de: "der Fußball", en: "the football", part: "noun m.", plural: "die Fußbälle", audio: true },
    { id: "das-tennis", de: "das Tennis", en: "the tennis", part: "noun n.", audio: true },
    { id: "das-schwimmen", de: "das Schwimmen", en: "the swimming", part: "noun n.", audio: true },
    { id: "das-radfahren", de: "das Radfahren", en: "the cycling", part: "noun n.", audio: true },
    { id: "das-joggen", de: "das Joggen", en: "the jogging", part: "noun n.", audio: true },
    { id: "die-musik", de: "die Musik", en: "the music", part: "noun f.", audio: true },
    { id: "das-klavier", de: "das Klavier", en: "the piano", part: "noun n.", plural: "die Klaviere", audio: true },
    { id: "die-gitarre", de: "die Gitarre", en: "the guitar", part: "noun f.", plural: "die Gitarren", audio: true },
    { id: "spielen", de: "spielen", en: "to play", part: "verb", audio: true },
    { id: "schwimmen", de: "schwimmen", en: "to swim", part: "verb", audio: true },
    { id: "wandern", de: "wandern", en: "to hike", part: "verb", audio: true },
    { id: "tanzen", de: "tanzen", en: "to dance", part: "verb", audio: true },
    { id: "lesen", de: "lesen", en: "to read", part: "verb", audio: true },
    { id: "kochen", de: "kochen", en: "to cook", part: "verb", audio: true },
    { id: "was-machst-du-in-deiner-freizeit", de: "Was machst du in deiner Freizeit?", en: "What do you do in your free time?", part: "phrase", phrase: true, audio: true },
    { id: "ich-mache-sport", de: "Ich mache Sport.", en: "I do sport.", part: "phrase", phrase: true, audio: true },
    { id: "ich-spiele-fussball", de: "Ich spiele Fußball.", en: "I play football.", part: "phrase", phrase: true, audio: true },
    { id: "ich-mag-fussball", de: "Ich mag Fußball.", en: "I like football.", part: "phrase", phrase: true, audio: true },
    { id: "ich-spiele-gern-tennis", de: "Ich spiele gern Tennis.", en: "I like playing tennis.", part: "phrase", phrase: true, audio: true },
    { id: "magst-du-sport", de: "Magst du Sport?", en: "Do you like sport?", part: "phrase", phrase: true, audio: true },
    { id: "welchen-sport-machst-du", de: "Welchen Sport machst du?", en: "Which sport do you do?", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-hobbys",
      type: "matching",
      title: "Übung 1: Die Hobbys",
      instruction: "Match each hobby to its meaning.",
      pairs: [
        ["Musik machen", "to make music"],
        ["Fußball spielen", "to play football"],
        ["Klavier spielen", "to play piano"],
        ["lesen", "to read"],
        ["schwimmen", "to swim"],
        ["kochen", "to cook"],
      ],
    },
    {
      id: "ex-machen-spielen",
      type: "multiple-choice",
      title: "Übung 2: machen oder spielen",
      instruction: "Choose the correct verb.",
      prompt: "I play football.",
      options: ["Ich spiele Fußball.", "Ich mache Fußball.", "Ich mache Fußball spielen."],
      correctIndex: 0,
      explain: "Ball games take spielen.",
    },
    {
      id: "ex-machen",
      type: "multiple-choice",
      title: "Übung 3: machen",
      instruction: "Choose the correct verb.",
      prompt: "I do sport.",
      options: ["Ich mache Sport.", "Ich spiele Sport.", "Ich mache Sport spielen."],
      correctIndex: 0,
      explain: "Sport takes machen.",
    },
    {
      id: "ex-moegen",
      type: "multiple-choice",
      title: "Übung 4: mögen",
      instruction: "Choose the correct sentence.",
      prompt: "I like football.",
      options: ["Ich mag Fußball.", "Ich möge Fußball.", "Ich bin Fußball."],
      correctIndex: 0,
      explain: "Likes use mögen.",
    },
    {
      id: "ex-gern",
      type: "multiple-choice",
      title: "Übung 5: gern",
      instruction: "Choose the correct sentence.",
      prompt: "I like playing tennis.",
      options: ["Ich spiele gern Tennis.", "Ich gern spiele Tennis.", "Ich spiele Tennis gern."],
      correctIndex: 0,
      explain: "gern follows the verb.",
    },
    {
      id: "ex-keine",
      type: "multiple-choice",
      title: "Übung 6: keine",
      instruction: "Choose the correct sentence.",
      prompt: "I do not like music.",
      options: ["Ich mag keine Musik.", "Ich mag nicht Musik.", "Ich nicht mag Musik."],
      correctIndex: 0,
      explain: "Nouns need kein/keine.",
    },
    {
      id: "ex-frage",
      type: "multiple-choice",
      title: "Übung 7: Die Freizeitfrage",
      instruction: "Choose the free time question.",
      prompt: "You ask what someone does in their free time.",
      options: ["Was machst du in deiner Freizeit?", "Was spielst du in deiner Freizeit?", "Wo machst du Freizeit?"],
      correctIndex: 0,
      explain: "The free time question: Was machst du ...?",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 8: Hören",
      instruction: "Play the audio and pick the hobby you heard.",
      prompt: "Fußball spielen",
      options: ["Fußball spielen", "Tennis spielen", "Klavier spielen"],
      correctIndex: 0,
      explain: "The hobby heard: football.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 9: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Ich spiele gern Tennis.",
      options: ["Ich spiele gern Tennis.", "Ich spiele gern Fußball.", "Ich mache gern Sport."],
      correctIndex: 0,
      explain: "The like sentence heard.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 10: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Ich spiele gern Fußball.", "Ich gern spiele Fußball.", "Ich spiele Fußball gern."],
      correctIndex: 0,
      explain: "gern follows the verb.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 11: Der Satz",
      instruction: "Build the sentence: I do sport in my free time.",
      chunks: ["Ich", "mache", "in", "meiner", "Freizeit", "Sport."],
      explain: "The hobby sentence.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 12: Der Satz",
      instruction: "Build the sentence: I play football.",
      chunks: ["Ich", "spiele", "Fußball."],
      explain: "The ball game verb.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 13: Hobbykarten",
      instruction: "Say the German out loud before revealing.",
      items: [
        { front: "der Fußball", back: "the football", frontAudio: true },
        { front: "das Tennis", back: "the tennis", frontAudio: true },
        { front: "das Schwimmen", back: "the swimming", frontAudio: true },
        { front: "die Musik", back: "the music", frontAudio: true },
        { front: "Ich mache Sport.", back: "I do sport.", frontAudio: true },
        { front: "Ich spiele Fußball.", back: "I play football.", frontAudio: true },
        { front: "Ich mag Fußball.", back: "I like football.", frontAudio: true },
        { front: "Ich spiele gern Tennis.", back: "I like playing tennis.", frontAudio: true },
        { front: "Magst du Sport?", back: "Do you like sport?", frontAudio: true },
        { front: "Was machst du in deiner Freizeit?", back: "What do you do in your free time?", frontAudio: true },
        { front: "Welchen Sport machst du?", back: "Which sport do you do?", frontAudio: true },
        { front: "die Freizeit", back: "the free time", frontAudio: true },
      ],
    },
  ],
};

export const nachBerlin: Lesson = {
  id: "nach-berlin",
  title: "Nach Berlin",
  summary:
    "Travelling to Berlin: the journey verbs, the destination prepositions, the ticket and transport, and the trip dialogue for A1.",
  status: "ready",
  sections: [
    {
      heading: "Die Reise nach Berlin",
      blocks: [
        {
          type: "paragraph",
          text: "A trip to Berlin runs on the journey verbs: fahren (to travel), fliegen (to fly), reisen (to travel), ankommen (to arrive), abfahren (to depart). The destination: nach Berlin (to Berlin), with nach for cities and countries. The question: Wohin fährst du? Ich fahre nach Berlin.",
        },
        {
          type: "table",
          caption: "The journey verbs",
          head: ["Verb", "English", "Example"],
          rows: [
            ["fahren", "to travel", "Ich fahre nach Berlin."],
            ["fliegen", "to fly", "Wir fliegen nach Berlin."],
            ["reisen", "to travel", "Ich reise gern."],
            ["ankommen", "to arrive", "Ich komme um 10 Uhr an."],
            ["abfahren", "to depart", "Der Zug fährt um 9 Uhr ab."],
            ["übernachten", "to stay overnight", "Wir übernachten im Hotel."],
          ],
        },
        {
          type: "example",
          de: "Ich fahre am Samstag nach Berlin und komme um 10 Uhr an. Am Abend übernachte ich im Hotel.",
          en: "The journey plan.",
        },
        {
          type: "tip",
          text: "The destination pair: nach for cities and countries (nach Berlin, nach Deutschland), zu for people and buildings. Wohin fährst du? Nach Berlin.",
        },
      ],
    },
    {
      heading: "Die Sehenswürdigkeiten",
      blocks: [
        {
          type: "paragraph",
          text: "Berlin's sights (die Sehenswürdigkeiten): das Brandenburger Tor (the Brandenburg Gate), der Fernsehturm (the TV tower), die Berliner Mauer (the Berlin Wall), das Museum (the museum), der Reichstag (the Reichstag), der Zoo (the zoo). The phrase: Ich möchte das Brandenburger Tor sehen.",
        },
        {
          type: "table",
          caption: "The sights",
          head: ["German", "English"],
          rows: [
            ["das Brandenburger Tor", "the Brandenburg Gate"],
            ["der Fernsehturm", "the TV tower"],
            ["die Berliner Mauer", "the Berlin Wall"],
            ["der Reichstag", "the Reichstag"],
            ["das Museum", "the museum"],
            ["der Zoo", "the zoo"],
          ],
        },
        {
          type: "example",
          de: "In Berlin möchte ich das Brandenburger Tor und den Fernsehturm sehen. Am Sonntag besuche ich das Museum.",
          en: "The sightseeing list.",
        },
        {
          type: "tip",
          text: "The sightseeing phrase: Ich möchte + sight + sehen. Die Sehenswürdigkeiten are what you see on the trip.",
        },
      ],
    },
    {
      heading: "Der Urlaub",
      blocks: [
        {
          type: "paragraph",
          text: "The holiday (der Urlaub) vocabulary: in Urlaub fahren (to go on holiday), der Urlaubstag (the holiday day), das Hotel (the hotel), das Zimmer (the room), das Einzelzimmer (single room), das Doppelzimmer (double room), der Strand (the beach). The phrase: Ich fahre in Urlaub. (I am going on holiday.)",
        },
        {
          type: "table",
          caption: "The holiday",
          head: ["German", "English"],
          rows: [
            ["in Urlaub fahren", "to go on holiday"],
            ["das Hotel", "the hotel"],
            ["das Zimmer", "the room"],
            ["das Einzelzimmer", "the single room"],
            ["das Doppelzimmer", "the double room"],
            ["der Strand", "the beach"],
            ["das Meer", "the sea"],
            ["die Berge", "the mountains"],
          ],
        },
        {
          type: "example",
          de: "Wir fahren im Sommer in Urlaub ans Meer. Das Hotel hat ein Doppelzimmer mit Balkon.",
          en: "The holiday plan.",
        },
        {
          type: "tip",
          text: "The holiday phrase: in Urlaub fahren, ans Meer, in die Berge. The room pair: das Einzelzimmer, das Doppelzimmer.",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: the wrong destination preposition, the separable ankommen/abfahren, and the holiday phrases.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["destination", "Ich fahre zu Berlin.", "Ich fahre nach Berlin.", "cities take nach"],
            ["ankommen split", "Ich ankomme um 10 Uhr.", "Ich komme um 10 Uhr an.", "ankommen is separable"],
            ["holiday phrase", "Ich fahre Urlaub.", "Ich fahre in Urlaub.", "the holiday phrase takes in"],
            ["room mix", "das Doppelzimmer? Nein, das Einzelzimmer.", "correct forms", "know both room types"],
            ["sight phrase", "Ich möchte die Berliner Mauer sehen.", "correct", "sehen takes the accusative"],
          ],
        },
        {
          type: "tip",
          text: "The trip to Berlin is a script: fahren + nach Berlin, the sights with sehen, and the holiday with in Urlaub fahren.",
        },
      ],
    },
  ],
  vocab: [
    { id: "die-reise", de: "die Reise", en: "the trip", part: "noun f.", plural: "die Reisen", audio: true },
    { id: "der-urlaub", de: "der Urlaub", en: "the holiday", part: "noun m.", plural: "die Urlaube", audio: true },
    { id: "der-tourist", de: "der Tourist", en: "the tourist", part: "noun m.", plural: "die Touristen", audio: true },
    { id: "das-hotel", de: "das Hotel", en: "the hotel", part: "noun n.", plural: "die Hotels", audio: true },
    { id: "das-zimmer", de: "das Zimmer", en: "the room", part: "noun n.", plural: "die Zimmer", audio: true },
    { id: "das-einzelzimmer", de: "das Einzelzimmer", en: "the single room", part: "noun n.", plural: "die Einzelzimmer", audio: true },
    { id: "das-doppelzimmer", de: "das Doppelzimmer", en: "the double room", part: "noun n.", plural: "die Doppelzimmer", audio: true },
    { id: "der-strand", de: "der Strand", en: "the beach", part: "noun m.", plural: "die Strände", audio: true },
    { id: "das-meer", de: "das Meer", en: "the sea", part: "noun n.", plural: "die Meere", audio: true },
    { id: "die-berge", de: "die Berge", en: "the mountains", part: "noun pl.", audio: true },
    { id: "das-brandenburger-tor", de: "das Brandenburger Tor", en: "the Brandenburg Gate", part: "noun n.", audio: true },
    { id: "der-fernsehturm", de: "der Fernsehturm", en: "the TV tower", part: "noun m.", plural: "die Fernsehtürme", audio: true },
    { id: "die-berliner-mauer", de: "die Berliner Mauer", en: "the Berlin Wall", part: "noun f.", audio: true },
    { id: "der-reichstag", de: "der Reichstag", en: "the Reichstag", part: "noun m.", audio: true },
    { id: "fahren", de: "fahren", en: "to travel", part: "verb", audio: true },
    { id: "fliegen", de: "fliegen", en: "to fly", part: "verb", audio: true },
    { id: "reisen", de: "reisen", en: "to travel", part: "verb", audio: true },
    { id: "ankommen", de: "ankommen", en: "to arrive", part: "verb", audio: true },
    { id: "abfahren", de: "abfahren", en: "to depart", part: "verb", audio: true },
    { id: "uebernachten", de: "übernachten", en: "to stay overnight", part: "verb", audio: true },
    { id: "ich-fahre-nach-berlin", de: "Ich fahre nach Berlin.", en: "I am travelling to Berlin.", part: "phrase", phrase: true, audio: true },
    { id: "ich-moechte-das-brandenburger-tor-sehen", de: "Ich möchte das Brandenburger Tor sehen.", en: "I would like to see the Brandenburg Gate.", part: "phrase", phrase: true, audio: true },
    { id: "ich-fahre-in-urlaub", de: "Ich fahre in Urlaub.", en: "I am going on holiday.", part: "phrase", phrase: true, audio: true },
    { id: "wir-uebernachten-im-hotel", de: "Wir übernachten im Hotel.", en: "We are staying at the hotel.", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-nach",
      type: "multiple-choice",
      title: "Übung 1: nach",
      instruction: "Choose the correct destination.",
      prompt: "I am travelling to Berlin.",
      options: ["Ich fahre nach Berlin.", "Ich fahre zu Berlin.", "Ich fahre in Berlin."],
      correctIndex: 0,
      explain: "Cities take nach.",
    },
    {
      id: "ex-ankommen",
      type: "multiple-choice",
      title: "Übung 2: ankommen",
      instruction: "Choose the correct sentence.",
      prompt: "I arrive at 10 o'clock.",
      options: ["Ich komme um 10 Uhr an.", "Ich ankomme um 10 Uhr.", "Ich komme an um 10 Uhr."],
      correctIndex: 0,
      explain: "ankommen is separable.",
    },
    {
      id: "ex-sehenswuerdigkeiten",
      type: "matching",
      title: "Übung 3: Die Sehenswürdigkeiten",
      instruction: "Match each sight to its meaning.",
      pairs: [
        ["das Brandenburger Tor", "the Brandenburg Gate"],
        ["der Fernsehturm", "the TV tower"],
        ["die Berliner Mauer", "the Berlin Wall"],
        ["der Reichstag", "the Reichstag"],
        ["das Museum", "the museum"],
        ["der Zoo", "the zoo"],
      ],
    },
    {
      id: "ex-urlaub",
      type: "multiple-choice",
      title: "Übung 4: in Urlaub",
      instruction: "Choose the correct phrase.",
      prompt: "I am going on holiday.",
      options: ["Ich fahre in Urlaub.", "Ich fahre Urlaub.", "Ich mache Urlaub fahren."],
      correctIndex: 0,
      explain: "The holiday phrase: in Urlaub fahren.",
    },
    {
      id: "ex-zimmer",
      type: "multiple-choice",
      title: "Übung 5: Das Zimmer",
      instruction: "Choose the correct room.",
      prompt: "A single room.",
      options: ["das Einzelzimmer", "das Doppelzimmer", "das Zimmerdoppel"],
      correctIndex: 0,
      explain: "The single room: das Einzelzimmer.",
    },
    {
      id: "ex-uebernachten",
      type: "multiple-choice",
      title: "Übung 6: übernachten",
      instruction: "Choose the correct sentence.",
      prompt: "We are staying at the hotel.",
      options: ["Wir übernachten im Hotel.", "Wir übernachten in Hotel.", "Wir sind im Hotel übernacht."],
      correctIndex: 0,
      explain: "Staying overnight: im Hotel.",
    },
    {
      id: "ex-strand",
      type: "multiple-choice",
      title: "Übung 7: Der Strand",
      instruction: "Choose the correct phrase.",
      prompt: "We are going to the sea.",
      options: ["Wir fahren ans Meer.", "Wir fahren nach das Meer.", "Wir fahren im Meer."],
      correctIndex: 0,
      explain: "The sea direction: ans Meer.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 8: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Ich fahre nach Berlin.",
      options: ["Ich fahre nach Berlin.", "Ich fliege nach Berlin.", "Ich fahre nach München."],
      correctIndex: 0,
      explain: "The destination heard: Berlin.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 9: Hören",
      instruction: "Play the audio and pick the sight you heard.",
      prompt: "das Brandenburger Tor",
      options: ["das Brandenburger Tor", "der Fernsehturm", "die Berliner Mauer"],
      correctIndex: 0,
      explain: "The sight heard: the gate.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 10: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Ich komme um 10 Uhr an.", "Ich ankomme um 10 Uhr.", "Ich komme an um 10 Uhr."],
      correctIndex: 0,
      explain: "ankommen is separable.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 11: Der Satz",
      instruction: "Build the sentence: I am travelling to Berlin.",
      chunks: ["Ich", "fahre", "nach", "Berlin."],
      explain: "The destination nach.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 12: Der Satz",
      instruction: "Build the sentence: We are staying at the hotel.",
      chunks: ["Wir", "übernachten", "im", "Hotel."],
      explain: "Staying overnight: im Hotel.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 13: Reisekarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "Ich fahre nach Berlin.", back: "I am travelling to Berlin.", frontAudio: true },
        { front: "Ich fahre in Urlaub.", back: "I am going on holiday.", frontAudio: true },
        { front: "Wir übernachten im Hotel.", back: "We are staying at the hotel.", frontAudio: true },
        { front: "das Einzelzimmer", back: "the single room", frontAudio: true },
        { front: "das Doppelzimmer", back: "the double room", frontAudio: true },
        { front: "der Strand", back: "the beach", frontAudio: true },
        { front: "das Meer", back: "the sea", frontAudio: true },
        { front: "das Brandenburger Tor", back: "the Brandenburg Gate", frontAudio: true },
        { front: "der Fernsehturm", back: "the TV tower", frontAudio: true },
        { front: "ankommen", back: "to arrive", frontAudio: true },
        { front: "abfahren", back: "to depart", frontAudio: true },
        { front: "übernachten", back: "to stay overnight", frontAudio: true },
      ],
    },
  ],
};

export const reisen: Lesson = {
  id: "reisen",
  title: "Reisen",
  summary:
    "The complete travel system for A1: the transport, the hotel check-in, the questions of the trip, and the full travel dialogue.",
  status: "ready",
  sections: [
    {
      heading: "Mit dem Verkehrsmittel reisen",
      blocks: [
        {
          type: "paragraph",
          text: "Travel runs on the transport pattern: mit + vehicle in the dative (mit dem Zug, mit dem Auto, mit dem Flugzeug), and the questions: Womit fährst du? (How do you travel?) and Wie lange dauert die Fahrt? (How long does the journey take?).",
        },
        {
          type: "table",
          caption: "The transport pattern",
          head: ["German", "English", "Question"],
          rows: [
            ["mit dem Zug", "by train", "Fährst du mit dem Zug?"],
            ["mit dem Auto", "by car", "Fährst du mit dem Auto?"],
            ["mit dem Bus", "by bus", "Fährst du mit dem Bus?"],
            ["mit dem Flugzeug", "by plane", "Fliegst du?"],
            ["mit dem Fahrrad", "by bike", "Fährst du mit dem Fahrrad?"],
          ],
        },
        {
          type: "example",
          de: "Ich fahre mit dem Zug nach Hamburg. Die Fahrt dauert zwei Stunden.",
          en: "The journey by train.",
        },
        {
          type: "tip",
          text: "The travel pattern: mit + vehicle. Womit fährst du? Mit dem Zug. The duration: Die Fahrt dauert zwei Stunden.",
        },
      ],
    },
    {
      heading: "Im Hotel",
      blocks: [
        {
          type: "paragraph",
          text: "The hotel check-in: Ich habe ein Zimmer reserviert (I have reserved a room), the questions: Wie lange bleiben Sie? (How long are you staying?), Haben Sie ein Einzelzimmer? (Do you have a single room?), Was kostet das Zimmer pro Nacht? (How much is the room per night?).",
        },
        {
          type: "table",
          caption: "The hotel script",
          head: ["German", "English"],
          rows: [
            ["Guten Tag, ich habe ein Zimmer reserviert.", "Hello, I have reserved a room."],
            ["Wie lange bleiben Sie?", "How long are you staying?"],
            ["Drei Nächte.", "Three nights."],
            ["Was kostet das Zimmer pro Nacht?", "How much is the room per night?"],
            ["Das Frühstück ist inklusive.", "Breakfast is included."],
            ["Hier ist Ihre Schlüsselkarte.", "Here is your key card."],
          ],
        },
        {
          type: "example",
          de: "Guten Tag, ich habe ein Zimmer reserviert. Wie lange bleiben Sie? Drei Nächte. Was kostet das Zimmer pro Nacht? 80 Euro, das Frühstück ist inklusive.",
          en: "The hotel check-in.",
        },
        {
          type: "tip",
          text: "The hotel script: reserviert, wie lange, pro Nacht, das Frühstück ist inklusive, die Schlüsselkarte.",
        },
      ],
    },
    {
      heading: "Die Reisefragen",
      blocks: [
        {
          type: "paragraph",
          text: "The trip questions: Wann fährst du? (When do you travel?), Womit fährst du? (How do you travel?), Wie lange dauert die Fahrt? (How long does the journey take?), Wo übernachtest du? (Where do you stay?), Wie gefällt dir der Urlaub? (How do you like the holiday?).",
        },
        {
          type: "table",
          caption: "The travel questions",
          head: ["Question", "English"],
          rows: [
            ["Wann fährst du?", "When do you travel?"],
            ["Womit fährst du?", "How do you travel?"],
            ["Wie lange dauert die Fahrt?", "How long does the journey take?"],
            ["Wo übernachtest du?", "Where do you stay?"],
            ["Wie gefällt dir der Urlaub?", "How do you like the holiday?"],
            ["Was machst du im Urlaub?", "What do you do on holiday?"],
          ],
        },
        {
          type: "example",
          de: "Wann fährst du? Am Samstag. Womit? Mit dem Zug. Wie lange? Drei Stunden. Wo übernachtest du? Im Hotel.",
          en: "The trip question dialogue.",
        },
        {
          type: "tip",
          text: "The travel questions: Wann, Womit, Wie lange, Wo, Was. Each opens one part of the trip story.",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: the missing mit, the wrong destination, and the separable ankommen.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["missing mit", "Ich fahre dem Zug.", "Ich fahre mit dem Zug.", "travel takes mit"],
            ["wrong destination", "Ich fahre zu Hamburg.", "Ich fahre nach Hamburg.", "cities take nach"],
            ["ankommen split", "Ich ankomme um 10 Uhr.", "Ich komme um 10 Uhr an.", "ankommen is separable"],
            ["hotel room", "das Doppelzimmer vs Einzelzimmer", "the right room type", "know both rooms"],
            ["duration verb", "Die Fahrt ist zwei Stunden.", "Die Fahrt dauert zwei Stunden.", "duration takes dauern"],
          ],
        },
        {
          type: "tip",
          text: "The travel topic is a script: the vehicle (mit dem Zug), the destination (nach Hamburg), the hotel (reserviert), and the questions (Wann, Womit, Wie lange).",
        },
      ],
    },
  ],
  vocab: [
    { id: "die-reise", de: "die Reise", en: "the trip", part: "noun f.", plural: "die Reisen", audio: true },
    { id: "die-fahrt", de: "die Fahrt", en: "the journey", part: "noun f.", plural: "die Fahrten", audio: true },
    { id: "das-reiseziel", de: "das Reiseziel", en: "the destination", part: "noun n.", plural: "die Reiseziele", audio: true },
    { id: "das-gepaeck", de: "das Gepäck", en: "the luggage", part: "noun n.", audio: true },
    { id: "der-koffer", de: "der Koffer", en: "the suitcase", part: "noun m.", plural: "die Koffer", audio: true },
    { id: "der-rucksack", de: "der Rucksack", en: "the backpack", part: "noun m.", plural: "die Rucksäcke", audio: true },
    { id: "der-pass", de: "der Pass", en: "the passport", part: "noun m.", plural: "die Pässe", audio: true },
    { id: "der-ausweis", de: "der Ausweis", en: "the ID card", part: "noun m.", plural: "die Ausweise", audio: true },
    { id: "die-fahrkarte", de: "die Fahrkarte", en: "the ticket", part: "noun f.", plural: "die Fahrkarten", audio: true },
    { id: "die-schluesselkarte", de: "die Schlüsselkarte", en: "the key card", part: "noun f.", plural: "die Schlüsselkarten", audio: true },
    { id: "die-rezeption", de: "die Rezeption", en: "the reception", part: "noun f.", plural: "die Rezeptionen", audio: true },
    { id: "reservieren", de: "reservieren", en: "to reserve", part: "verb", audio: true },
    { id: "buchen", de: "buchen", en: "to book", part: "verb", audio: true },
    { id: "uebernachten", de: "übernachten", en: "to stay overnight", part: "verb", audio: true },
    { id: "dauern", de: "dauern", en: "to last", part: "verb", audio: true },
    { id: "ich-fahre-mit-dem-zug", de: "Ich fahre mit dem Zug.", en: "I travel by train.", part: "phrase", phrase: true, audio: true },
    { id: "ich-habe-ein-zimmer-reserviert", de: "Ich habe ein Zimmer reserviert.", en: "I have reserved a room.", part: "phrase", phrase: true, audio: true },
    { id: "wie-lange-bleiben-sie", de: "Wie lange bleiben Sie?", en: "How long are you staying?", part: "phrase", phrase: true, audio: true },
    { id: "was-kostet-das-zimmer-pro-nacht", de: "Was kostet das Zimmer pro Nacht?", en: "How much is the room per night?", part: "phrase", phrase: true, audio: true },
    { id: "das-fruehstueck-ist-inklusive", de: "Das Frühstück ist inklusive.", en: "Breakfast is included.", part: "phrase", phrase: true, audio: true },
    { id: "womit-faehrst-du", de: "Womit fährst du?", en: "How do you travel?", part: "phrase", phrase: true, audio: true },
    { id: "wie-lange-dauert-die-fahrt", de: "Wie lange dauert die Fahrt?", en: "How long does the journey take?", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-mit",
      type: "multiple-choice",
      title: "Übung 1: mit",
      instruction: "Choose the correct phrase.",
      prompt: "I travel by train.",
      options: ["Ich fahre mit dem Zug.", "Ich fahre dem Zug.", "Ich fahre auf dem Zug."],
      correctIndex: 0,
      explain: "Travel takes mit.",
    },
    {
      id: "ex-reiseziel",
      type: "multiple-choice",
      title: "Übung 2: Das Reiseziel",
      instruction: "Choose the correct destination.",
      prompt: "I am travelling to Hamburg.",
      options: ["Ich fahre nach Hamburg.", "Ich fahre zu Hamburg.", "Ich fahre in Hamburg."],
      correctIndex: 0,
      explain: "Cities take nach.",
    },
    {
      id: "ex-hotel",
      type: "multiple-choice",
      title: "Übung 3: Im Hotel",
      instruction: "Choose the check-in sentence.",
      prompt: "I have reserved a room.",
      options: ["Ich habe ein Zimmer reserviert.", "Ich habe ein Zimmer gebucht.", "Ich reserviere ein Zimmer."],
      correctIndex: 0,
      explain: "The check-in: ich habe ... reserviert.",
    },
    {
      id: "ex-lange",
      type: "multiple-choice",
      title: "Übung 4: Wie lange",
      instruction: "Choose the duration question.",
      prompt: "The receptionist asks how long you stay.",
      options: ["Wie lange bleiben Sie?", "Wie lange fahren Sie?", "Wie lange reservieren Sie?"],
      correctIndex: 0,
      explain: "The stay question: Wie lange bleiben Sie?",
    },
    {
      id: "ex-nacht",
      type: "multiple-choice",
      title: "Übung 5: pro Nacht",
      instruction: "Choose the price question.",
      prompt: "You ask the price per night.",
      options: ["Was kostet das Zimmer pro Nacht?", "Was kostet das Zimmer pro Woche?", "Was kostet die Nacht pro Zimmer?"],
      correctIndex: 0,
      explain: "The nightly price: pro Nacht.",
    },
    {
      id: "ex-inklusive",
      type: "multiple-choice",
      title: "Übung 6: inklusive",
      instruction: "Choose the correct sentence.",
      prompt: "Breakfast is included.",
      options: ["Das Frühstück ist inklusive.", "Das Frühstück ist dabei.", "Das Frühstück ist extra."],
      correctIndex: 0,
      explain: "The included phrase: ist inklusive.",
    },
    {
      id: "ex-dauern",
      type: "multiple-choice",
      title: "Übung 7: dauern",
      instruction: "Choose the correct sentence.",
      prompt: "The journey takes two hours.",
      options: ["Die Fahrt dauert zwei Stunden.", "Die Fahrt ist zwei Stunden.", "Die Fahrt macht zwei Stunden."],
      correctIndex: 0,
      explain: "Duration takes dauern.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 8: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Ich fahre mit dem Zug.",
      options: ["Ich fahre mit dem Zug.", "Ich fahre mit dem Auto.", "Ich fahre mit dem Bus."],
      correctIndex: 0,
      explain: "The transport sentence heard.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 9: Hören",
      instruction: "Play the audio and pick the question you heard.",
      prompt: "Wie lange bleiben Sie?",
      options: ["Wie lange bleiben Sie?", "Wie lange fahren Sie?", "Wie lange dauert die Fahrt?"],
      correctIndex: 0,
      explain: "The stay question heard.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 10: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Die Fahrt dauert zwei Stunden.", "Die Fahrt ist zwei Stunden.", "Die Fahrt macht zwei Stunden."],
      correctIndex: 0,
      explain: "Duration takes dauern.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 11: Der Satz",
      instruction: "Build the sentence: I travel by train.",
      chunks: ["Ich", "fahre", "mit", "dem", "Zug."],
      explain: "The travel pattern: mit + vehicle.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 12: Der Satz",
      instruction: "Build the sentence: I have reserved a room.",
      chunks: ["Ich", "habe", "ein", "Zimmer", "reserviert."],
      explain: "The check-in sentence.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 13: Reisekarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "Ich fahre mit dem Zug.", back: "I travel by train.", frontAudio: true },
        { front: "Ich habe ein Zimmer reserviert.", back: "I have reserved a room.", frontAudio: true },
        { front: "Wie lange bleiben Sie?", back: "How long are you staying?", frontAudio: true },
        { front: "Was kostet das Zimmer pro Nacht?", back: "How much is the room per night?", frontAudio: true },
        { front: "Das Frühstück ist inklusive.", back: "Breakfast is included.", frontAudio: true },
        { front: "Womit fährst du?", back: "How do you travel?", frontAudio: true },
        { front: "Wie lange dauert die Fahrt?", back: "How long does the journey take?", frontAudio: true },
        { front: "der Koffer", back: "the suitcase", frontAudio: true },
        { front: "der Pass", back: "the passport", frontAudio: true },
        { front: "das Gepäck", back: "the luggage", frontAudio: true },
        { front: "reservieren", back: "to reserve", frontAudio: true },
        { front: "übernachten", back: "to stay overnight", frontAudio: true },
      ],
    },
  ],
};

export const einladungen: Lesson = {
  id: "einladungen",
  title: "Einladungen",
  summary:
    "Invitations for A1: inviting, accepting, declining, the reasons, and the full invitation dialogue.",
  status: "ready",
  sections: [
    {
      heading: "Einladen",
      blocks: [
        {
          type: "paragraph",
          text: "The invitation (die Einladung) uses the verbs: einladen (to invite), kommen (to come), mitkommen (to come along). The phrases: Ich lade dich ein (I invite you), Kommst du mit? (Are you coming along?), Hast du am Samstag Zeit? (Do you have time on Saturday?).",
        },
        {
          type: "table",
          caption: "The invitation",
          head: ["German", "English"],
          rows: [
            ["Ich lade dich ein.", "I invite you."],
            ["Kommst du mit?", "Are you coming along?"],
            ["Hast du am Samstag Zeit?", "Do you have time on Saturday?"],
            ["Willst du mitkommen?", "Do you want to come along?"],
            ["Möchtest du mitgehen?", "Would you like to come?"],
            ["Wir machen eine Party.", "We are having a party."],
          ],
        },
        {
          type: "example",
          de: "Hallo Anna, am Samstag machen wir eine Party. Hast du Zeit? Kommst du mit?",
          en: "The invitation.",
        },
        {
          type: "tip",
          text: "The invitation verbs: einladen (ein + laden), mitkommen (mit + kommen). The question: Hast du am Samstag Zeit?",
        },
      ],
    },
    {
      heading: "Annehmen",
      blocks: [
        {
          type: "paragraph",
          text: "Accepting an invitation: Ja, gern! (Yes, gladly!), Ja, ich komme gern mit. (Yes, I would love to come.), Das ist eine gute Idee! (That is a good idea!). The response keeps it short and positive.",
        },
        {
          type: "table",
          caption: "Accepting",
          head: ["German", "English"],
          rows: [
            ["Ja, gern!", "Yes, gladly!"],
            ["Ja, ich komme gern mit.", "Yes, I would love to come."],
            ["Das ist eine gute Idee!", "That is a good idea!"],
            ["Wann und wo?", "When and where?"],
            ["Um wie viel Uhr?", "At what time?"],
            ["Ich bringe etwas mit.", "I will bring something."],
          ],
        },
        {
          type: "example",
          de: "Kommst du mit ins Kino? Ja, gern! Wann? Am Samstag um 8 Uhr. Perfekt!",
          en: "The acceptance.",
        },
        {
          type: "tip",
          text: "The acceptance: Ja, gern! The follow-up questions: Wann und wo? Um wie viel Uhr?",
        },
      ],
    },
    {
      heading: "Ablehnen",
      blocks: [
        {
          type: "paragraph",
          text: "Declining politely: Nein, danke. (No, thank you.), Ich habe keine Zeit. (I have no time.), Ich kann leider nicht kommen. (Unfortunately I cannot come.), Ich habe schon etwas vor. (I already have plans.). The polite decline gives a short reason.",
        },
        {
          type: "table",
          caption: "Declining",
          head: ["German", "English"],
          rows: [
            ["Nein, danke.", "No, thank you."],
            ["Ich habe keine Zeit.", "I have no time."],
            ["Ich kann leider nicht kommen.", "Unfortunately I cannot come."],
            ["Ich habe schon etwas vor.", "I already have plans."],
            ["Ich bin schon verabredet.", "I already have a date."],
            ["Vielleicht ein anderes Mal.", "Maybe another time."],
          ],
        },
        {
          type: "example",
          de: "Kommst du mit? Nein, danke, ich habe keine Zeit. Ich bin schon verabredet. Vielleicht ein anderes Mal!",
          en: "The polite decline.",
        },
        {
          type: "tip",
          text: "The decline: Nein, danke + a short reason. Ich habe keine Zeit, ich bin schon verabredet, ich kann leider nicht kommen.",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: the separable einladen, the wrong time question, and the polite decline.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["einladen split", "Ich einlade dich.", "Ich lade dich ein.", "einladen is separable"],
            ["time question", "Wann Uhr?", "Um wie viel Uhr?", "the time question is fixed"],
            ["rude decline", "Nein.", "Nein, danke.", "the polite decline needs danke"],
            ["mitkommen split", "Kommst mit du?", "Kommst du mit?", "mitkommen splits"],
            ["invitation noun", "die Einladung? Ja.", "die Einladung", "the invitation is feminine"],
          ],
        },
        {
          type: "tip",
          text: "The invitation topic is a script: the invite (Kommst du mit?), the accept (Ja, gern!), and the decline (Nein, danke).",
        },
      ],
    },
  ],
  vocab: [
    { id: "die-einladung", de: "die Einladung", en: "the invitation", part: "noun f.", plural: "die Einladungen", audio: true },
    { id: "die-party", de: "die Party", en: "the party", part: "noun f.", plural: "die Partys", audio: true },
    { id: "der-geburtstag", de: "der Geburtstag", en: "the birthday", part: "noun m.", plural: "die Geburtstage", audio: true },
    { id: "die-feier", de: "die Feier", en: "the celebration", part: "noun f.", plural: "die Feiern", audio: true },
    { id: "einladen", de: "einladen", en: "to invite", part: "verb", audio: true },
    { id: "mitkommen", de: "mitkommen", en: "to come along", part: "verb", audio: true },
    { id: "mitgehen", de: "mitgehen", en: "to go along", part: "verb", audio: true },
    { id: "mitbringen", de: "mitbringen", en: "to bring along", part: "verb", audio: true },
    { id: "ich-lade-dich-ein", de: "Ich lade dich ein.", en: "I invite you.", part: "phrase", phrase: true, audio: true },
    { id: "kommst-du-mit", de: "Kommst du mit?", en: "Are you coming along?", part: "phrase", phrase: true, audio: true },
    { id: "hast-du-am-samstag-zeit", de: "Hast du am Samstag Zeit?", en: "Do you have time on Saturday?", part: "phrase", phrase: true, audio: true },
    { id: "ja-gern", de: "Ja, gern!", en: "Yes, gladly!", part: "phrase", phrase: true, audio: true },
    { id: "wann-und-wo", de: "Wann und wo?", en: "When and where?", part: "phrase", phrase: true, audio: true },
    { id: "um-wie-viel-uhr", de: "Um wie viel Uhr?", en: "At what time?", part: "phrase", phrase: true, audio: true },
    { id: "ich-kann-leider-nicht-kommen", de: "Ich kann leider nicht kommen.", en: "Unfortunately I cannot come.", part: "phrase", phrase: true, audio: true },
    { id: "ich-habe-keine-zeit", de: "Ich habe keine Zeit.", en: "I have no time.", part: "phrase", phrase: true, audio: true },
    { id: "ich-habe-schon-etwas-vor", de: "Ich habe schon etwas vor.", en: "I already have plans.", part: "phrase", phrase: true, audio: true },
    { id: "vielleicht-ein-anderes-mal", de: "Vielleicht ein anderes Mal!", en: "Maybe another time!", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-einladen",
      type: "multiple-choice",
      title: "Übung 1: einladen",
      instruction: "Choose the correct sentence.",
      prompt: "I invite you.",
      options: ["Ich lade dich ein.", "Ich einlade dich.", "Ich lade ein dich."],
      correctIndex: 0,
      explain: "einladen is separable.",
    },
    {
      id: "ex-mitkommen",
      type: "multiple-choice",
      title: "Übung 2: mitkommen",
      instruction: "Choose the correct question.",
      prompt: "Are you coming along?",
      options: ["Kommst du mit?", "Mitkommst du?", "Kommst mit du?"],
      correctIndex: 0,
      explain: "mitkommen splits.",
    },
    {
      id: "ex-zeit",
      type: "multiple-choice",
      title: "Übung 3: Zeit",
      instruction: "Choose the time question.",
      prompt: "You ask if someone has time on Saturday.",
      options: ["Hast du am Samstag Zeit?", "Hast du Samstag Zeit?", "Hast du am Samstag Uhr?"],
      correctIndex: 0,
      explain: "The free time question: am Samstag Zeit.",
    },
    {
      id: "ex-ja",
      type: "multiple-choice",
      title: "Übung 4: Annehmen",
      instruction: "Choose the acceptance.",
      prompt: "You accept the invitation.",
      options: ["Ja, gern!", "Nein, danke.", "Ich habe keine Zeit."],
      correctIndex: 0,
      explain: "The acceptance: Ja, gern!",
    },
    {
      id: "ex-nein",
      type: "multiple-choice",
      title: "Übung 5: Ablehnen",
      instruction: "Choose the polite decline.",
      prompt: "You decline politely.",
      options: ["Ich kann leider nicht kommen.", "Nein.", "Ich gehe nicht."],
      correctIndex: 0,
      explain: "The polite decline gives a reason.",
    },
    {
      id: "ex-uhr",
      type: "multiple-choice",
      title: "Übung 6: Um wie viel Uhr?",
      instruction: "Choose the time question.",
      prompt: "You ask the time of the event.",
      options: ["Um wie viel Uhr?", "Wie viel Uhr?", "Was Uhr?"],
      correctIndex: 0,
      explain: "The time question: Um wie viel Uhr?",
    },
    {
      id: "ex-vor",
      type: "multiple-choice",
      title: "Übung 7: schon etwas vor",
      instruction: "Choose the plans sentence.",
      prompt: "I already have plans.",
      options: ["Ich habe schon etwas vor.", "Ich habe etwas vor schon.", "Ich schon habe etwas vor."],
      correctIndex: 0,
      explain: "The plans phrase: schon etwas vor.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 8: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Kommst du mit?",
      options: ["Kommst du mit?", "Willst du mitkommen?", "Hast du Zeit?"],
      correctIndex: 0,
      explain: "The invitation heard.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 9: Hören",
      instruction: "Play the audio and pick the answer you heard.",
      prompt: "Ja, gern!",
      options: ["Ja, gern!", "Nein, danke.", "Vielleicht ein anderes Mal!"],
      correctIndex: 0,
      explain: "The acceptance heard.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 10: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Ich lade dich ein.", "Ich einlade dich.", "Ich lade ein dich."],
      correctIndex: 0,
      explain: "einladen is separable.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 11: Der Satz",
      instruction: "Build the sentence: I invite you.",
      chunks: ["Ich", "lade", "dich", "ein."],
      explain: "The separable einladen.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 12: Der Satz",
      instruction: "Build the sentence: Do you have time on Saturday?",
      chunks: ["Hast", "du", "am", "Samstag", "Zeit?"],
      explain: "The time question.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 13: Einladungskarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "Ich lade dich ein.", back: "I invite you.", frontAudio: true },
        { front: "Kommst du mit?", back: "Are you coming along?", frontAudio: true },
        { front: "Hast du am Samstag Zeit?", back: "Do you have time on Saturday?", frontAudio: true },
        { front: "Ja, gern!", back: "Yes, gladly!", frontAudio: true },
        { front: "Wann und wo?", back: "When and where?", frontAudio: true },
        { front: "Um wie viel Uhr?", back: "At what time?", frontAudio: true },
        { front: "Ich kann leider nicht kommen.", back: "Unfortunately I cannot come.", frontAudio: true },
        { front: "Ich habe keine Zeit.", back: "I have no time.", frontAudio: true },
        { front: "Ich habe schon etwas vor.", back: "I already have plans.", frontAudio: true },
        { front: "Vielleicht ein anderes Mal!", back: "Maybe another time!", frontAudio: true },
        { front: "die Einladung", back: "the invitation", frontAudio: true },
        { front: "der Geburtstag", back: "the birthday", frontAudio: true },
      ],
    },
  ],
};

export const wiederholung: Lesson = {
  id: "wiederholung",
  title: "Wiederholung",
  summary:
    "The complete review of Freizeit und Reisen: the verbs, the prepositions, the cases, and the exam-style exercises.",
  status: "ready",
  sections: [
    {
      heading: "Was wir gelernt haben",
      blocks: [
        {
          type: "paragraph",
          text: "This lesson reviews the whole Freizeit und Reisen unit: the hobbies with machen/spielen, the trips with fahren + nach, the transport with mit + dative, the hotel with reserviert, the invitations with einladen, and the past with the Perfekt.",
        },
        {
          type: "table",
          caption: "The unit summary",
          head: ["Topic", "Key pattern", "Example"],
          rows: [
            ["hobbies", "machen/spielen", "Ich mache Sport, ich spiele Fußball."],
            ["trips", "fahren + nach", "Ich fahre nach Berlin."],
            ["transport", "mit + dative", "mit dem Zug"],
            ["hotel", "reserviert", "Ich habe ein Zimmer reserviert."],
            ["invitations", "einladen", "Ich lade dich ein."],
            ["past", "Perfekt", "Ich bin gefahren."],
          ],
        },
        {
          type: "tip",
          text: "The unit test: can you answer Womit fährst du? (Mit dem Zug), Wohin fährst du? (Nach Berlin), and Hast du am Samstag Zeit? (Ja, gern!)?",
        },
      ],
    },
    {
      heading: "Die Fehler der Einheit",
      blocks: [
        {
          type: "paragraph",
          text: "The unit's classic errors: machen/spielen mix, the missing mit, the wrong destination, and the separable einladen.",
        },
        {
          type: "table",
          caption: "The unit errors",
          head: ["Mistake", "Wrong", "Right"],
          rows: [
            ["machen/spielen mix", "Ich mache Fußball.", "Ich spiele Fußball."],
            ["missing mit", "Ich fahre dem Zug.", "Ich fahre mit dem Zug."],
            ["wrong destination", "Ich fahre zu Hamburg.", "Ich fahre nach Hamburg."],
            ["einladen split", "Ich einlade dich.", "Ich lade dich ein."],
            ["seat reservation", "Ich habe ein Zimmer gebucht statt reserviert.", "Ich habe ein Zimmer reserviert."],
          ],
        },
        {
          type: "tip",
          text: "The unit test: watch the pair machen/spielen, the mit, the nach, and the separable verbs.",
        },
      ],
    },
  ],
  vocab: [
    { id: "die-wiederholung", de: "die Wiederholung", en: "the review", part: "noun f.", plural: "die Wiederholungen", audio: true },
    { id: "wiederholen", de: "wiederholen", en: "to review, repeat", part: "verb", audio: true },
    { id: "die-uebung", de: "die Übung", en: "the exercise", part: "noun f.", plural: "die Übungen", audio: true },
    { id: "ich-fahre-mit-dem-zug", de: "Ich fahre mit dem Zug.", en: "I travel by train.", part: "phrase", phrase: true, audio: true },
    { id: "ich-fahre-nach-berlin", de: "Ich fahre nach Berlin.", en: "I am travelling to Berlin.", part: "phrase", phrase: true, audio: true },
    { id: "ich-spiele-fussball", de: "Ich spiele Fußball.", en: "I play football.", part: "phrase", phrase: true, audio: true },
    { id: "ich-mache-sport", de: "Ich mache Sport.", en: "I do sport.", part: "phrase", phrase: true, audio: true },
    { id: "ich-lade-dich-ein", de: "Ich lade dich ein.", en: "I invite you.", part: "phrase", phrase: true, audio: true },
    { id: "hast-du-zeit", de: "Hast du Zeit?", en: "Do you have time?", part: "phrase", phrase: true, audio: true },
    { id: "ich-habe-ein-zimmer-reserviert", de: "Ich habe ein Zimmer reserviert.", en: "I have reserved a room.", part: "phrase", phrase: true, audio: true },
    { id: "ich-bin-nach-berlin-gefahren", de: "Ich bin nach Berlin gefahren.", en: "I travelled to Berlin.", part: "phrase", phrase: true, audio: true },
    { id: "ja-gern", de: "Ja, gern!", en: "Yes, gladly!", part: "phrase", phrase: true, audio: true },
    { id: "nein-danke", de: "Nein, danke.", en: "No, thank you.", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-machen-spielen",
      type: "multiple-choice",
      title: "Übung 1: machen oder spielen",
      instruction: "Choose the correct verb.",
      prompt: "Ich ___ Sport.",
      options: ["mache", "spiele", "mach"],
      correctIndex: 0,
      explain: "Sport takes machen.",
    },
    {
      id: "ex-machen-spielen-2",
      type: "multiple-choice",
      title: "Übung 2: machen oder spielen",
      instruction: "Choose the correct verb.",
      prompt: "Ich ___ Fußball.",
      options: ["spiele", "mache", "spiel"],
      correctIndex: 0,
      explain: "Ball games take spielen.",
    },
    {
      id: "ex-mit",
      type: "multiple-choice",
      title: "Übung 3: mit",
      instruction: "Choose the correct phrase.",
      prompt: "I travel by train.",
      options: ["mit dem Zug", "auf dem Zug", "dem Zug"],
      correctIndex: 0,
      explain: "Transport takes mit.",
    },
    {
      id: "ex-nach",
      type: "multiple-choice",
      title: "Übung 4: nach",
      instruction: "Choose the correct destination.",
      prompt: "I am travelling to Berlin.",
      options: ["Ich fahre nach Berlin.", "Ich fahre zu Berlin.", "Ich fahre in Berlin."],
      correctIndex: 0,
      explain: "Cities take nach.",
    },
    {
      id: "ex-separabel",
      type: "multiple-choice",
      title: "Übung 5: Das trennbare Verb",
      instruction: "Choose the correct sentence.",
      prompt: "I invite you.",
      options: ["Ich lade dich ein.", "Ich einlade dich.", "Ich lade ein dich."],
      correctIndex: 0,
      explain: "einladen is separable.",
    },
    {
      id: "ex-perfekt",
      type: "multiple-choice",
      title: "Übung 6: Das Perfekt",
      instruction: "Choose the correct sentence.",
      prompt: "I travelled to Berlin.",
      options: ["Ich bin nach Berlin gefahren.", "Ich habe nach Berlin gefahren.", "Ich bin nach Berlin fahren."],
      correctIndex: 0,
      explain: "Movement takes sein.",
    },
    {
      id: "ex-hotel",
      type: "multiple-choice",
      title: "Übung 7: Das Hotel",
      instruction: "Choose the check-in sentence.",
      prompt: "I have reserved a room.",
      options: ["Ich habe ein Zimmer reserviert.", "Ich habe ein Zimmer gebucht.", "Ich reserviere ein Zimmer."],
      correctIndex: 0,
      explain: "The check-in: ich habe ... reserviert.",
    },
    {
      id: "ex-ja",
      type: "multiple-choice",
      title: "Übung 8: Annehmen",
      instruction: "Choose the acceptance.",
      prompt: "You accept the invitation.",
      options: ["Ja, gern!", "Nein, danke.", "Ich habe keine Zeit."],
      correctIndex: 0,
      explain: "The acceptance: Ja, gern!",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 9: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Ich fahre mit dem Zug.",
      options: ["Ich fahre mit dem Zug.", "Ich fahre mit dem Auto.", "Ich fahre mit dem Bus."],
      correctIndex: 0,
      explain: "The transport sentence heard.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 10: Hören",
      instruction: "Play the audio and pick the question you heard.",
      prompt: "Hast du Zeit?",
      options: ["Hast du Zeit?", "Kommst du mit?", "Wohin fährst du?"],
      correctIndex: 0,
      explain: "The time question heard.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 11: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Ich spiele Fußball.", "Ich mache Fußball.", "Ich spiele Sport."],
      correctIndex: 0,
      explain: "Ball games take spielen, sport takes machen.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 12: Der Satz",
      instruction: "Build the sentence: I travel by train.",
      chunks: ["Ich", "fahre", "mit", "dem", "Zug."],
      explain: "Transport with mit.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 13: Der Satz",
      instruction: "Build the sentence: I travelled to Berlin.",
      chunks: ["Ich", "bin", "nach", "Berlin", "gefahren."],
      explain: "The perfect with movement.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 14: Wiederholungskarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "Ich fahre mit dem Zug.", back: "I travel by train.", frontAudio: true },
        { front: "Ich fahre nach Berlin.", back: "I am travelling to Berlin.", frontAudio: true },
        { front: "Ich spiele Fußball.", back: "I play football.", frontAudio: true },
        { front: "Ich mache Sport.", back: "I do sport.", frontAudio: true },
        { front: "Ich lade dich ein.", back: "I invite you.", frontAudio: true },
        { front: "Hast du Zeit?", back: "Do you have time?", frontAudio: true },
        { front: "Ich habe ein Zimmer reserviert.", back: "I have reserved a room.", frontAudio: true },
        { front: "Ich bin nach Berlin gefahren.", back: "I travelled to Berlin.", frontAudio: true },
        { front: "Ja, gern!", back: "Yes, gladly!", frontAudio: true },
        { front: "Nein, danke.", back: "No, thank you.", frontAudio: true },
        { front: "wiederholen", back: "to review, repeat", frontAudio: true },
        { front: "die Wiederholung", back: "the review", frontAudio: true },
      ],
    },
  ],
};

const goetheMockExam: Lesson = {
  id: "goethe-a1-mock-exam",
  title: "Goethe-Style A1 Mock Exam",
  summary: "A full A1-style practice round for everyday life in Germany.",
  status: "ready",
  sections: [
    {
      heading: "So funktioniert die Prüfung",
      blocks: [
        {
          type: "paragraph",
          text: "The real Goethe A1 exam has four parts: Hören (listening), Lesen (reading), Schreiben (writing), and Sprechen (speaking). This mock exam practises the same skills with the same kind of tasks: listening and choosing, filling forms, matching notices, and building correct sentences.",
        },
        {
          type: "table",
          caption: "The exam parts",
          head: ["Part", "What happens", "Here you practise"],
          rows: [
            ["Hören", "you hear short texts and pick answers", "listening exercises"],
            ["Lesen", "you read notices and forms", "reading and matching"],
            ["Schreiben", "you fill in forms and write short messages", "fill-blank tasks"],
            ["Sprechen", "you introduce yourself and ask questions", "word-order sentences"],
          ],
        },
        {
          type: "tip",
          text: "Exam vocabulary you will actually meet: der Termin, die Anmeldung, das Formular, das Bürgeramt, die Krankenversicherung, der Aufenthaltstitel, das Konto. Learn these as a set, they appear in every A1 paper.",
        },
      ],
    },
    {
      heading: "Teil 1: Wortschatz für den Alltag",
      blocks: [
        {
          type: "paragraph",
          text: "Goethe A1 loves the practical Germany: appointments, forms, and documents. These words are the exam's favourite topic and the words you really need after landing.",
        },
        {
          type: "table",
          caption: "Exam vocabulary",
          head: ["German", "English"],
          rows: [
            ["der Termin", "the appointment"],
            ["die Anmeldung", "the registration"],
            ["das Formular", "the form"],
            ["das Bürgeramt", "the citizen's office"],
            ["die Krankenversicherung", "the health insurance"],
            ["der Aufenthaltstitel", "the residence permit"],
            ["das Konto", "the bank account"],
            ["die Meldebescheinigung", "the registration certificate"],
          ],
        },
        {
          type: "example",
          de: "Ich habe morgen einen Termin beim Bürgeramt.",
          en: "I have an appointment at the citizen's office tomorrow.",
        },
      ],
    },
    {
      heading: "Teil 2: Grammatik in der Prüfung",
      blocks: [
        {
          type: "paragraph",
          text: "The exam checks the same grammar you already know: articles, cases, the Perfekt, modals, and word order. The exercises below mix all of it the way the exam does.",
        },
        {
          type: "example",
          de: "Ich möchte einen Termin machen. Kann ich das Formular hier bekommen?",
          en: "I would like to make an appointment. Can I get the form here?",
        },
      ],
    },
  ],
  vocab: [
    { id: "die-pruefung", de: "die Prüfung", en: "the exam", part: "noun f.", plural: "die Prüfungen", audio: true },
    { id: "der-termin", de: "der Termin", en: "the appointment", part: "noun m.", plural: "die Termine", audio: true },
    { id: "die-anmeldung", de: "die Anmeldung", en: "the registration", part: "noun f.", plural: "die Anmeldungen", audio: true },
    { id: "das-formular", de: "das Formular", en: "the form", part: "noun n.", plural: "die Formulare", audio: true },
    { id: "das-buergeramt", de: "das Bürgeramt", en: "the citizen's office", part: "noun n.", plural: "die Bürgerämter", audio: true },
    { id: "die-krankenversicherung", de: "die Krankenversicherung", en: "the health insurance", part: "noun f.", plural: "die Krankenversicherungen", audio: true },
    { id: "der-aufenthaltstitel", de: "der Aufenthaltstitel", en: "the residence permit", part: "noun m.", plural: "die Aufenthaltstitel", audio: true },
    { id: "das-konto", de: "das Konto", en: "the bank account", part: "noun n.", plural: "die Konten", audio: true },
    { id: "die-meldebescheinigung", de: "die Meldebescheinigung", en: "the registration certificate", part: "noun f.", plural: "die Meldebescheinigungen", audio: true },
    { id: "die-hoeren", de: "das Hören", en: "the listening (exam part)", part: "noun n.", audio: true },
    { id: "das-lesen", de: "das Lesen", en: "the reading (exam part)", part: "noun n.", audio: true },
    { id: "das-schreiben", de: "das Schreiben", en: "the writing (exam part)", part: "noun n.", audio: true },
  ],
  exercises: [
    {
      id: "mc-goethe-woerter",
      type: "multiple-choice",
      title: "Teil 1: Wortschatz",
      instruction: "Choose the word that fits the exam sentence.",
      prompt: "Ich habe morgen einen ___ beim Bürgeramt.",
      options: ["Termin", "Formular", "Aufenthaltstitel"],
      correctIndex: 0,
      explain: "The appointment is der Termin: einen Termin haben.",
    },
    {
      id: "listening-goethe-hoeren",
      type: "listening",
      title: "Teil: Hören",
      instruction: "Play the audio and pick what you heard.",
      prompt: "Ich möchte einen Termin machen.",
      options: [
        "Ich möchte einen Termin machen.",
        "Ich möchte ein Formular machen.",
        "Ich möchte einen Termin haben.",
      ],
      correctIndex: 0,
    },
    {
      id: "fill-goethe-formular",
      type: "fill-blank",
      title: "Teil: Schreiben",
      instruction: "Fill in the form sentences.",
      sentence: "Mein ___ ist Anna Müller. (last name) Ich habe ___ Termin. (an, masculine)",
      blanks: [
        { answers: ["Nachname"], hint: "last name" },
        { answers: ["einen"], hint: "accusative, masculine" },
      ],
    },
    {
      id: "matching-goethe-lesen",
      type: "matching",
      title: "Teil: Lesen",
      instruction: "Match each document word to its meaning.",
      pairs: [
        ["die Anmeldung", "the registration"],
        ["das Formular", "the form"],
        ["der Aufenthaltstitel", "the residence permit"],
        ["die Krankenversicherung", "the health insurance"],
        ["das Konto", "the bank account"],
      ],
    },
    {
      id: "word-order-goethe",
      type: "word-order",
      title: "Teil: Sprechen",
      instruction: "Build the sentence: I have an appointment at the citizen's office tomorrow.",
      chunks: ["Ich", "habe", "morgen", "einen", "Termin", "beim", "Bürgeramt."],
      explain: "Time (morgen) comes before the object.",
    },
    {
      id: "flashcard-goethe",
      type: "flashcard",
      title: "Prüfungswortschatz",
      instruction: "Say the German exam word out loud before revealing.",
      items: [
        { front: "der Termin", back: "the appointment", frontAudio: true },
        { front: "die Anmeldung", back: "the registration", frontAudio: true },
        { front: "das Formular", back: "the form", frontAudio: true },
        { front: "das Bürgeramt", back: "the citizen's office", frontAudio: true },
        { front: "der Aufenthaltstitel", back: "the residence permit", frontAudio: true },
        { front: "die Krankenversicherung", back: "the health insurance", frontAudio: true },
      ],
    },
  ],
};

const telcMockExam: Lesson = {
  id: "telc-a1-mock-exam",
  title: "telc-Style A1 Mock Exam",
  summary: "Housing and city life: apartment notices, transport, shops, directions.",
  status: "ready",
  sections: [
    {
      heading: "So funktioniert telc",
      blocks: [
        {
          type: "paragraph",
          text: "The telc A1 exam is organized like Goethe A1: Hören, Lesen, Schreiben, and Sprechen. Its favourite topics are housing and city life: apartment notices, transport, shops, and directions. This mock exam practises exactly those.",
        },
        {
          type: "table",
          caption: "telc topics",
          head: ["Topic", "Words you need"],
          rows: [
            ["Housing", "die Miete, der Vermieter, die Wohnung, der Stock"],
            ["Transport", "die Haltestelle, der Bahnsteig, die Fahrkarte"],
            ["Shops", "der Supermarkt, die Apotheke, öffnen, schließen"],
            ["Directions", "links, rechts, geradeaus, an der Ampel"],
          ],
        },
        {
          type: "tip",
          text: "telc notices are short and use the imperative: Bitte links abbiegen. Öffnungszeiten: Mo-Fr 9-18 Uhr. Learn to read the imperative in notices: it is the same form you already know.",
        },
      ],
    },
    {
      heading: "Die Wohnung",
      blocks: [
        {
          type: "paragraph",
          text: "Apartment notices are a telc classic. They are packed with abbreviations and numbers: 2-Zimmer-Wohnung, 58 qm, 3. Stock, 850 Euro kalt, zzgl. Nebenkosten.",
        },
        {
          type: "example",
          de: "2-Zimmer-Wohnung, 58 qm, Balkon, 850 Euro kalt.",
          en: "Two-room apartment, 58 sqm, balcony, 850 euros cold.",
        },
        {
          type: "example",
          de: "Die Wohnung ist im dritten Stock. Der Vermieter heißt Herr Weber.",
          en: "The apartment is on the third floor. The landlord is called Mr Weber.",
        },
      ],
    },
    {
      heading: "Unterwegs",
      blocks: [
        {
          type: "paragraph",
          text: "The transport section of telc checks directions and timetables: when the bus leaves, where the platform is, how to change trains.",
        },
        {
          type: "example",
          de: "Entschuldigung, wo ist der Bahnsteig? Gehen Sie geradeaus, dann links.",
          en: "Excuse me, where is the platform? Go straight ahead, then left.",
        },
        {
          type: "example",
          de: "Der Bus hat zehn Minuten Verspätung.",
          en: "The bus is ten minutes late.",
        },
        {
          type: "tip",
          text: "Notice the imperative inside directions: Gehen Sie geradeaus. The polite form with Sie is what appears in exam listening texts.",
        },
      ],
    },
  ],
  vocab: [
    { id: "der-vermieter", de: "der Vermieter", en: "the landlord", part: "noun m.", plural: "die Vermieter", audio: true },
    { id: "die-miete", de: "die Miete", en: "the rent", part: "noun f.", plural: "die Mieten", audio: true },
    { id: "die-nebenkosten", de: "die Nebenkosten", en: "the utilities", part: "noun pl.", audio: true },
    { id: "der-supermarkt", de: "der Supermarkt", en: "the supermarket", part: "noun m.", plural: "die Supermärkte", audio: true },
    { id: "oeffnen", de: "öffnen", en: "to open", part: "verb", audio: true },
    { id: "schliessen", de: "schließen", en: "to close", part: "verb", audio: true },
    { id: "die-oefnungszeiten", de: "die Öffnungszeiten", en: "the opening hours", part: "noun pl.", audio: true },
    { id: "die-haltestelle", de: "die Haltestelle", en: "the stop", part: "noun f.", plural: "die Haltestellen", audio: true },
    { id: "der-bahnsteig", de: "der Bahnsteig", en: "the platform", part: "noun m.", plural: "die Bahnsteige", audio: true },
    { id: "die-fahrkarte", de: "die Fahrkarte", en: "the ticket", part: "noun f.", plural: "die Fahrkarten", audio: true },
    { id: "die-verspaetung", de: "die Verspätung", en: "the delay", part: "noun f.", plural: "die Verspätungen", audio: true },
    { id: "abbiegen", de: "abbiegen", en: "to turn (a corner)", part: "verb", audio: true },
  ],
  exercises: [
    {
      id: "mc-telc-anzeige",
      type: "multiple-choice",
      title: "Teil: Lesen",
      instruction: "Read the notice and answer.",
      prompt: "In einer Anzeige steht: 2-Zimmer-Wohnung, 3. Stock. Wo ist die Wohnung?",
      options: ["im dritten Stock", "im Erdgeschoss", "im zweiten Stock"],
      correctIndex: 0,
      explain: "3. Stock means the third floor.",
    },
    {
      id: "listening-telc-hoeren",
      type: "listening",
      title: "Teil: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Der Bus hat zehn Minuten Verspätung.",
      options: [
        "Der Bus hat zehn Minuten Verspätung.",
        "Der Bus hat zehn Minuten Haltestelle.",
        "Der Zug hat zehn Minuten Verspätung.",
      ],
      correctIndex: 0,
    },
    {
      id: "fill-telc-schreiben",
      type: "fill-blank",
      title: "Teil: Schreiben",
      instruction: "Complete the housing sentences.",
      sentence: "Die Wohnung ist im dritten ___. (floor) Die Miete ist 850 Euro ___.",
      blanks: [
        { answers: ["Stock"], hint: "the floor" },
        { answers: ["kalt"], hint: "without utilities" },
      ],
    },
    {
      id: "matching-telc-lesen",
      type: "matching",
      title: "Teil: Lesen",
      instruction: "Match each word to its meaning.",
      pairs: [
        ["die Haltestelle", "the stop"],
        ["der Bahnsteig", "the platform"],
        ["die Fahrkarte", "the ticket"],
        ["die Öffnungszeiten", "the opening hours"],
        ["der Supermarkt", "the supermarket"],
      ],
    },
    {
      id: "word-order-telc",
      type: "word-order",
      title: "Teil: Sprechen",
      instruction: "Build the directions: Go straight ahead, then left.",
      chunks: ["Gehen", "Sie", "geradeaus,", "dann", "links."],
      explain: "The imperative leads, the direction follows.",
    },
    {
      id: "flashcard-telc",
      type: "flashcard",
      title: "telc-Wortschatz",
      instruction: "Say the German word out loud before revealing.",
      items: [
        { front: "die Haltestelle", back: "the stop", frontAudio: true },
        { front: "der Bahnsteig", back: "the platform", frontAudio: true },
        { front: "die Fahrkarte", back: "the ticket", frontAudio: true },
        { front: "die Miete", back: "the rent", frontAudio: true },
        { front: "der Vermieter", back: "the landlord", frontAudio: true },
        { front: "die Öffnungszeiten", back: "the opening hours", frontAudio: true },
      ],
    },
  ],
};

export const freizeitUndReisen: Unit = {
  id: "freizeit-und-reisen",
  title: "Freizeit und Reisen",
  theme: "Free time and travel",
  lessons: [
    hobbysUndSport,
    nachBerlin,
    reisen,
    einladungen,
    wiederholung,
    goetheMockExam,
    telcMockExam,
    goethePracticeExam,
  ],
};