import type { Lesson, Unit } from "../../schema";

export const derKoerper: Lesson = {
  id: "der-koerper",
  title: "Der Körper",
  summary:
    "The complete body vocabulary for A1: the body parts, the verbs of the body, and the pains and complaints.",
  status: "ready",
  sections: [
    {
      heading: "Der Körper: die Teile",
      blocks: [
        {
          type: "paragraph",
          text: "The body (der Körper) is made of parts with strong genders: der Kopf (head, m.), das Gesicht (face, n.), die Hand (hand, f.), der Arm (arm, m.), das Bein (leg, n.), der Fuß (foot, m.). The classic question: Was tut dir weh? (What hurts you?).",
        },
        {
          type: "table",
          caption: "The body parts",
          head: ["German", "English", "Plural"],
          rows: [
            ["der Kopf", "the head", "die Köpfe"],
            ["das Gesicht", "the face", "die Gesichter"],
            ["das Auge", "the eye", "die Augen"],
            ["die Nase", "the nose", "die Nasen"],
            ["der Mund", "the mouth", "die Münder"],
            ["das Ohr", "the ear", "die Ohren"],
            ["die Hand", "the hand", "die Hände"],
            ["der Arm", "the arm", "die Arme"],
            ["das Bein", "the leg", "die Beine"],
            ["der Fuß", "the foot", "die Füße"],
            ["der Finger", "the finger", "die Finger"],
            ["der Rücken", "the back", "die Rücken"],
          ],
        },
        {
          type: "example",
          de: "Der Kopf, das Gesicht, die Hand: das sind Teile des Körpers. Wir haben zwei Augen, zwei Ohren, zwei Hände und zwei Füße.",
          en: "The head, the face, the hand: those are parts of the body. We have two eyes, two ears, two hands and two feet.",
        },
        {
          type: "tip",
          text: "The body parts learn with the article: der Kopf, das Gesicht, die Hand. The plural pattern: feminine hands and eyes take -e with umlaut (die Hände, die Füße).",
        },
      ],
    },
    {
      heading: "Die Körperverben",
      blocks: [
        {
          type: "paragraph",
          text: "The body verbs describe what the parts do: sehen (to see, with the eyes), hören (to hear, with the ears), riechen (to smell, with the nose), sprechen (to speak, with the mouth), fühlen (to feel, with the hands). The phrase: Ich sehe mit den Augen. Ich höre mit den Ohren.",
        },
        {
          type: "table",
          caption: "The body verbs",
          head: ["Verb", "English", "With"],
          rows: [
            ["sehen", "to see", "mit den Augen"],
            ["hören", "to hear", "mit den Ohren"],
            ["riechen", "to smell", "mit der Nase"],
            ["sprechen", "to speak", "mit dem Mund"],
            ["fühlen", "to feel", "mit den Händen"],
            ["laufen", "to run", "mit den Beinen"],
          ],
        },
        {
          type: "example",
          de: "Ich sehe mit den Augen, höre mit den Ohren und spreche mit dem Mund.",
          en: "The senses in one line.",
        },
        {
          type: "tip",
          text: "The sense pattern: verb + mit + body part in the dative. mit den Augen, mit den Ohren, mit dem Mund.",
        },
      ],
    },
    {
      heading: "Die Schmerzen",
      blocks: [
        {
          type: "paragraph",
          text: "Talking about pain uses the dative: Mir tut der Kopf weh (My head hurts), Mir tut der Rücken weh (My back hurts), Mir tut die Hand weh. The question: Was tut dir weh? (What hurts?). The phrase Ich habe Kopfschmerzen (I have a headache) covers the pains too.",
        },
        {
          type: "table",
          caption: "The pains",
          head: ["German", "English"],
          rows: [
            ["Mir tut der Kopf weh.", "My head hurts."],
            ["Mir tut der Rücken weh.", "My back hurts."],
            ["Mir tun die Füße weh.", "My feet hurt."],
            ["Ich habe Kopfschmerzen.", "I have a headache."],
            ["Ich habe Bauchschmerzen.", "I have a stomach ache."],
            ["Ich habe Halsschmerzen.", "I have a sore throat."],
          ],
        },
        {
          type: "example",
          de: "Mir tut der Kopf weh und ich habe Halsschmerzen. Ich möchte zum Arzt.",
          en: "My head hurts and I have a sore throat. I would like to go to the doctor.",
        },
        {
          type: "tip",
          text: "The pain pattern: Mir + tut + body part + weh. The Schmerzen pattern: Ich habe + Kopfschmerzen, Bauchschmerzen, Halsschmerzen.",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: wrong gender, confusing weh tun with haben, and forgetting the dative.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["wrong gender", "der Auge", "das Auge", "Auge is neuter"],
            ["dative loss", "Ich tut der Kopf weh.", "Mir tut der Kopf weh.", "weh tun takes the dative"],
            ["habe/weh mix", "Ich habe Kopf weh.", "Ich habe Kopfschmerzen.", "the Schmerzen form takes habe"],
            ["sense phrase", "Ich sehe mit den Augen? Nein, mit die Augen.", "mit den Augen", "mit takes the dative"],
            ["body plural", "die Hande statt die Hände", "die Hände", "the umlaut plural"],
          ],
        },
        {
          type: "tip",
          text: "The body topic is a script: the part with the article, the sense verb with mit, and the pain with mir ... weh.",
        },
      ],
    },
  ],
  vocab: [
    { id: "der-koerper", de: "der Körper", en: "the body", part: "noun m.", plural: "die Körper", audio: true },
    { id: "der-kopf", de: "der Kopf", en: "the head", part: "noun m.", plural: "die Köpfe", audio: true },
    { id: "das-gesicht", de: "das Gesicht", en: "the face", part: "noun n.", plural: "die Gesichter", audio: true },
    { id: "das-auge", de: "das Auge", en: "the eye", part: "noun n.", plural: "die Augen", audio: true },
    { id: "die-nase", de: "die Nase", en: "the nose", part: "noun f.", plural: "die Nasen", audio: true },
    { id: "der-mund", de: "der Mund", en: "the mouth", part: "noun m.", plural: "die Münder", audio: true },
    { id: "das-ohr", de: "das Ohr", en: "the ear", part: "noun n.", plural: "die Ohren", audio: true },
    { id: "die-hand", de: "die Hand", en: "the hand", part: "noun f.", plural: "die Hände", audio: true },
    { id: "der-arm", de: "der Arm", en: "the arm", part: "noun m.", plural: "die Arme", audio: true },
    { id: "das-bein", de: "das Bein", en: "the leg", part: "noun n.", plural: "die Beine", audio: true },
    { id: "der-fuss", de: "der Fuß", en: "the foot", part: "noun m.", plural: "die Füße", audio: true },
    { id: "der-finger", de: "der Finger", en: "the finger", part: "noun m.", plural: "die Finger", audio: true },
    { id: "der-ruecken", de: "der Rücken", en: "the back", part: "noun m.", plural: "die Rücken", audio: true },
    { id: "der-bauch", de: "der Bauch", en: "the stomach", part: "noun m.", plural: "die Bäuche", audio: true },
    { id: "das-herz", de: "das Herz", en: "the heart", part: "noun n.", plural: "die Herzen", audio: true },
    { id: "sehen", de: "sehen", en: "to see", part: "verb", audio: true },
    { id: "hoeren", de: "hören", en: "to hear", part: "verb", audio: true },
    { id: "riechen", de: "riechen", en: "to smell", part: "verb", audio: true },
    { id: "sprechen", de: "sprechen", en: "to speak", part: "verb", audio: true },
    { id: "fuehlen", de: "fühlen", en: "to feel", part: "verb", audio: true },
    { id: "laufen", de: "laufen", en: "to run", part: "verb", audio: true },
    { id: "die-kopfschmerzen", de: "die Kopfschmerzen", en: "the headache", part: "noun pl.", audio: true },
    { id: "die-bauchschmerzen", de: "die Bauchschmerzen", en: "the stomach ache", part: "noun pl.", audio: true },
    { id: "die-halsschmerzen", de: "die Halsschmerzen", en: "the sore throat", part: "noun pl.", audio: true },
    { id: "mir-tut-der-kopf-weh", de: "Mir tut der Kopf weh.", en: "My head hurts.", part: "phrase", phrase: true, audio: true },
    { id: "was-tut-dir-weh", de: "Was tut dir weh?", en: "What hurts?", part: "phrase", phrase: true, audio: true },
    { id: "ich-sehe-mit-den-augen", de: "Ich sehe mit den Augen.", en: "I see with my eyes.", part: "phrase", phrase: true, audio: true },
    { id: "ich-habe-kopfschmerzen", de: "Ich habe Kopfschmerzen.", en: "I have a headache.", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-teile",
      type: "matching",
      title: "Übung 1: Die Körperteile",
      instruction: "Match each body part to its meaning.",
      pairs: [
        ["der Kopf", "the head"],
        ["das Auge", "the eye"],
        ["die Nase", "the nose"],
        ["das Ohr", "the ear"],
        ["die Hand", "the hand"],
        ["das Bein", "the leg"],
      ],
    },
    {
      id: "ex-genus",
      type: "multiple-choice",
      title: "Übung 2: Das Genus",
      instruction: "Choose the correct article.",
      prompt: "___ Auge ist braun.",
      options: ["Das", "Die", "Der"],
      correctIndex: 0,
      explain: "Auge is neuter: das Auge.",
    },
    {
      id: "ex-genus-2",
      type: "multiple-choice",
      title: "Übung 3: Das Genus",
      instruction: "Choose the correct article.",
      prompt: "___ Hand ist klein.",
      options: ["Die", "Das", "Der"],
      correctIndex: 0,
      explain: "Hand is feminine: die Hand.",
    },
    {
      id: "ex-sinn",
      type: "multiple-choice",
      title: "Übung 4: Die Sinne",
      instruction: "Choose the correct phrase.",
      prompt: "I see with my eyes.",
      options: ["Ich sehe mit den Augen.", "Ich sehe mit die Augen.", "Ich sehe mit dem Augen."],
      correctIndex: 0,
      explain: "mit takes the dative: mit den Augen.",
    },
    {
      id: "ex-weh",
      type: "multiple-choice",
      title: "Übung 5: weh tun",
      instruction: "Choose the correct sentence.",
      prompt: "My head hurts.",
      options: ["Mir tut der Kopf weh.", "Ich tut der Kopf weh.", "Der Kopf tut mich weh."],
      correctIndex: 0,
      explain: "weh tun takes the dative: mir.",
    },
    {
      id: "ex-schmerzen",
      type: "multiple-choice",
      title: "Übung 6: Die Schmerzen",
      instruction: "Choose the correct sentence.",
      prompt: "I have a stomach ache.",
      options: ["Ich habe Bauchschmerzen.", "Ich habe Bauch weh.", "Mir habe Bauchschmerzen."],
      correctIndex: 0,
      explain: "The Schmerzen form takes habe.",
    },
    {
      id: "ex-frage",
      type: "multiple-choice",
      title: "Übung 7: Die Frage",
      instruction: "Choose the pain question.",
      prompt: "The doctor asks what hurts.",
      options: ["Was tut dir weh?", "Wo ist dein Kopf?", "Was ist dein Schmerz?"],
      correctIndex: 0,
      explain: "The pain question: Was tut dir weh?",
    },
    {
      id: "ex-hals",
      type: "multiple-choice",
      title: "Übung 8: Der Hals",
      instruction: "Choose the sore throat phrase.",
      prompt: "I have a sore throat.",
      options: ["Ich habe Halsschmerzen.", "Ich habe Halswehkopf.", "Ich habe Halskopf."],
      correctIndex: 0,
      explain: "The throat pain: Halsschmerzen.",
    },
    {
      id: "ex-plural",
      type: "multiple-choice",
      title: "Übung 9: Der Plural",
      instruction: "Choose the correct plural.",
      prompt: "die Hand → ...",
      options: ["die Hände", "die Hande", "die Händen"],
      correctIndex: 0,
      explain: "The umlaut plural: die Hände.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 10: Hören",
      instruction: "Play the audio and pick the body part you heard.",
      prompt: "die Hand",
      options: ["die Hand", "die Nase", "das Bein"],
      correctIndex: 0,
      explain: "The part heard: hand.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 11: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Mir tut der Kopf weh.",
      options: ["Mir tut der Kopf weh.", "Mir tut der Rücken weh.", "Mir tun die Füße weh."],
      correctIndex: 0,
      explain: "The pain heard: head.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 12: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Ich sehe mit den Augen.", "Ich sehe mit die Augen.", "Ich sehe mit der Augen."],
      correctIndex: 0,
      explain: "mit takes the dative.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 13: Der Satz",
      instruction: "Build the sentence: My head hurts.",
      chunks: ["Mir", "tut", "der", "Kopf", "weh."], translation: "My head hurts.",
      explain: "The pain sentence with the dative.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 14: Der Satz",
      instruction: "Build the sentence: I have a headache.",
      chunks: ["Ich", "habe", "Kopfschmerzen."], translation: "I have a headache.",
      explain: "The Schmerzen sentence.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 15: Körperkarten",
      instruction: "Say the German with the article out loud.",
      items: [
        { front: "der Kopf", back: "the head", frontAudio: true },
        { front: "das Auge", back: "the eye", frontAudio: true },
        { front: "die Nase", back: "the nose", frontAudio: true },
        { front: "das Ohr", back: "the ear", frontAudio: true },
        { front: "die Hand", back: "the hand", frontAudio: true },
        { front: "das Bein", back: "the leg", frontAudio: true },
        { front: "der Fuß", back: "the foot", frontAudio: true },
        { front: "der Rücken", back: "the back", frontAudio: true },
        { front: "Mir tut der Kopf weh.", back: "My head hurts.", frontAudio: true },
        { front: "Ich habe Kopfschmerzen.", back: "I have a headache.", frontAudio: true },
        { front: "Ich sehe mit den Augen.", back: "I see with my eyes.", frontAudio: true },
        { front: "Was tut dir weh?", back: "What hurts?", frontAudio: true },
      ],
    },
  ],
};

export const beimArzt: Lesson = {
  id: "beim-arzt",
  title: "Beim Arzt",
  summary:
    "The complete doctor visit for A1: the appointment, the complaint, the doctor's questions, and the prescription.",
  status: "ready",
  sections: [
    {
      heading: "Der Termin",
      blocks: [
        {
          type: "paragraph",
          text: "The doctor visit starts with the appointment: einen Termin machen (to make an appointment), die Praxis (the practice), die Sprechstunde (the surgery hours). The phrase: Ich möchte einen Termin machen. (I would like to make an appointment.) The receptionist asks: Was fehlt Ihnen? (What is wrong with you?).",
        },
        {
          type: "table",
          caption: "The appointment script",
          head: ["German", "English"],
          rows: [
            ["Ich möchte einen Termin machen.", "I would like to make an appointment."],
            ["Was fehlt Ihnen?", "What is wrong with you?"],
            ["Ich habe Fieber.", "I have a fever."],
            ["Wann haben Sie Zeit?", "When do you have time?"],
            ["Morgen um 9 Uhr.", "Tomorrow at 9 o'clock."],
            ["Die Praxis ist in der Hauptstraße.", "The practice is on the main street."],
          ],
        },
        {
          type: "example",
          de: "Guten Tag, ich möchte einen Termin machen. Was fehlt Ihnen? Ich habe Fieber und Husten.",
          en: "Good day, I would like to make an appointment. What is wrong with you? I have a fever and a cough.",
        },
        {
          type: "tip",
          text: "The appointment pair: einen Termin machen and Was fehlt Ihnen? The symptom words: Fieber, Husten, Schnupfen.",
        },
      ],
    },
    {
      heading: "Die Symptome",
      blocks: [
        {
          type: "paragraph",
          text: "The symptoms (die Symptome): das Fieber (fever), der Husten (cough), der Schnupfen (cold, runny nose), die Erkältung (a cold), die Grippe (flu), die Allergie (allergy). The phrase: Ich habe Fieber und Husten. (I have a fever and a cough.)",
        },
        {
          type: "table",
          caption: "The symptoms",
          head: ["German", "English"],
          rows: [
            ["das Fieber", "the fever"],
            ["der Husten", "the cough"],
            ["der Schnupfen", "the runny nose"],
            ["die Erkältung", "the cold"],
            ["die Grippe", "the flu"],
            ["die Allergie", "the allergy"],
            ["der Schwindel", "the dizziness"],
          ],
        },
        {
          type: "example",
          de: "Ich habe eine Erkältung: Husten, Schnupfen und leichtes Fieber.",
          en: "The cold symptom list.",
        },
        {
          type: "tip",
          text: "The symptom phrase: Ich habe + symptom. Fieber, Husten, Schnupfen, Erkältung, Grippe.",
        },
      ],
    },
    {
      heading: "Die Untersuchung",
      blocks: [
        {
          type: "paragraph",
          text: "The doctor examines with fixed questions: Wo tut es weh? (Where does it hurt?), Seit wann haben Sie das? (Since when do you have this?), and the instructions: Öffnen Sie den Mund! (Open your mouth!), Atmen Sie tief! (Breathe deeply!). The response: Der Arzt untersucht mich (The doctor examines me).",
        },
        {
          type: "table",
          caption: "The examination",
          head: ["German", "English"],
          rows: [
            ["Wo tut es weh?", "Where does it hurt?"],
            ["Seit wann haben Sie das?", "Since when do you have this?"],
            ["Öffnen Sie den Mund!", "Open your mouth!"],
            ["Atmen Sie tief!", "Breathe deeply!"],
            ["Der Arzt untersucht mich.", "The doctor examines me."],
            ["Es ist nichts Schlimmes.", "It is nothing serious."],
          ],
        },
        {
          type: "example",
          de: "Der Arzt sagt: Öffnen Sie den Mund! Dann: Atmen Sie tief! Am Ende: Es ist nichts Schlimmes, nur eine Erkältung.",
          en: "The doctor says: Open your mouth! Then: Breathe deeply! At the end: It's nothing serious, just a cold.",
        },
        {
          type: "tip",
          text: "The examination runs on two imperatives: Öffnen Sie and Atmen Sie. The reassurance: Es ist nichts Schlimmes.",
        },
      ],
    },
    {
      heading: "Das Rezept und die Medizin",
      blocks: [
        {
          type: "paragraph",
          text: "The outcome: das Rezept (the prescription), die Medizin (the medicine), die Tabletten (the tablets), die Tropfen (the drops), die Salbe (the ointment), die Krankschreibung (the sick note). The doctor says: Ich verschreibe Ihnen etwas. (I will prescribe something for you.) and Nehmen Sie dreimal täglich eine Tablette. (Take one tablet three times a day.)",
        },
        {
          type: "table",
          caption: "The medicine",
          head: ["German", "English"],
          rows: [
            ["das Rezept", "the prescription"],
            ["die Medizin", "the medicine"],
            ["die Tabletten", "the tablets"],
            ["die Tropfen", "the drops"],
            ["die Salbe", "the ointment"],
            ["die Krankschreibung", "the sick note"],
          ],
        },
        {
          type: "example",
          de: "Der Arzt verschreibt mir Tabletten und eine Salbe. Ich soll dreimal täglich eine Tablette nehmen.",
          en: "The doctor prescribes me tablets and an ointment. I should take one tablet three times a day.",
        },
        {
          type: "tip",
          text: "The medicine phrase: Nehmen Sie dreimal täglich eine Tablette. The pair: das Rezept and die Krankschreibung.",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: confusing the symptoms, forgetting the modal soll, and the wrong article on the medicine words.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["symptom mix", "Ich habe Grippe statt Erkältung.", "Ich habe eine Erkältung.", "the cold is die Erkältung"],
            ["soll loss", "Ich nehme dreimal täglich eine Tablette.", "Ich soll dreimal täglich eine Tablette nehmen.", "the doctor instructs with sollen"],
            ["wrong article", "das Medizin", "die Medizin", "Medizin is feminine"],
            ["missing imperativ", "Öffnen den Mund!", "Öffnen Sie den Mund!", "the formal imperative keeps Sie"],
            ["seit wann mix", "Seit wann haben Sie das? Nein, wann.", "Seit wann haben Sie das?", "seit asks the duration"],
          ],
        },
        {
          type: "tip",
          text: "The doctor visit is a script: the appointment, the symptom (Ich habe Fieber), the examination (Öffnen Sie den Mund), and the prescription (Nehmen Sie dreimal täglich).",
        },
      ],
    },
  ],
  vocab: [
    { id: "der-arzt", de: "der Arzt", en: "the doctor (male)", part: "noun m.", plural: "die Ärzte", audio: true },
    { id: "die-aerztin", de: "die Ärztin", en: "the doctor (female)", part: "noun f.", plural: "die Ärztinnen", audio: true },
    { id: "die-praxis", de: "die Praxis", en: "the practice", part: "noun f.", plural: "die Praxen", audio: true },
    { id: "der-termin", de: "der Termin", en: "the appointment", part: "noun m.", plural: "die Termine", audio: true },
    { id: "die-sprechstunde", de: "die Sprechstunde", en: "the surgery hours", part: "noun f.", plural: "die Sprechstunden", audio: true },
    { id: "das-fieber", de: "das Fieber", en: "the fever", part: "noun n.", audio: true },
    { id: "der-husten", de: "der Husten", en: "the cough", part: "noun m.", audio: true },
    { id: "der-schnupfen", de: "der Schnupfen", en: "the runny nose", part: "noun m.", audio: true },
    { id: "die-erkaeltung", de: "die Erkältung", en: "the cold", part: "noun f.", plural: "die Erkältungen", audio: true },
    { id: "die-grippe", de: "die Grippe", en: "the flu", part: "noun f.", audio: true },
    { id: "die-allergie", de: "die Allergie", en: "the allergy", part: "noun f.", plural: "die Allergien", audio: true },
    { id: "das-rezept", de: "das Rezept", en: "the prescription", part: "noun n.", plural: "die Rezepte", audio: true },
    { id: "die-medizin", de: "die Medizin", en: "the medicine", part: "noun f.", audio: true },
    { id: "die-tabletten", de: "die Tabletten", en: "the tablets", part: "noun pl.", audio: true },
    { id: "die-tropfen", de: "die Tropfen", en: "the drops", part: "noun pl.", audio: true },
    { id: "die-salbe", de: "die Salbe", en: "the ointment", part: "noun f.", plural: "die Salben", audio: true },
    { id: "die-krankschreibung", de: "die Krankschreibung", en: "the sick note", part: "noun f.", plural: "die Krankschreibungen", audio: true },
    { id: "untersuchen", de: "untersuchen", en: "to examine", part: "verb", audio: true },
    { id: "verschreiben", de: "verschreiben", en: "to prescribe", part: "verb", audio: true },
    { id: "ich-moechte-einen-termin-machen", de: "Ich möchte einen Termin machen.", en: "I would like to make an appointment.", part: "phrase", phrase: true, audio: true },
    { id: "was-fehlt-ihnen", de: "Was fehlt Ihnen?", en: "What is wrong with you?", part: "phrase", phrase: true, audio: true },
    { id: "ich-habe-fieber", de: "Ich habe Fieber.", en: "I have a fever.", part: "phrase", phrase: true, audio: true },
    { id: "wo-tut-es-weh", de: "Wo tut es weh?", en: "Where does it hurt?", part: "phrase", phrase: true, audio: true },
    { id: "oeffnen-sie-den-mund", de: "Öffnen Sie den Mund!", en: "Open your mouth!", part: "phrase", phrase: true, audio: true },
    { id: "atmen-sie-tief", de: "Atmen Sie tief!", en: "Breathe deeply!", part: "phrase", phrase: true, audio: true },
    { id: "es-ist-nichts-schlimmes", de: "Es ist nichts Schlimmes.", en: "It is nothing serious.", part: "phrase", phrase: true, audio: true },
    { id: "nehmen-sie-dreimal-taeglich", de: "Nehmen Sie dreimal täglich eine Tablette.", en: "Take one tablet three times a day.", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-termin",
      type: "multiple-choice",
      title: "Übung 1: Der Termin",
      instruction: "Choose the appointment sentence.",
      prompt: "You want to make an appointment.",
      options: ["Ich möchte einen Termin machen.", "Ich möchte einen Termin haben.", "Ich bin einen Termin."],
      correctIndex: 0,
      explain: "The appointment verb: einen Termin machen.",
    },
    {
      id: "ex-fehlt",
      type: "multiple-choice",
      title: "Übung 2: Was fehlt Ihnen?",
      instruction: "Choose the receptionist question.",
      prompt: "The receptionist asks what is wrong.",
      options: ["Was fehlt Ihnen?", "Was ist Ihnen?", "Wo fehlen Sie?"],
      correctIndex: 0,
      explain: "The health question: Was fehlt Ihnen?",
    },
    {
      id: "ex-symptom",
      type: "matching",
      title: "Übung 3: Die Symptome",
      instruction: "Match each symptom to its meaning.",
      pairs: [
        ["das Fieber", "the fever"],
        ["der Husten", "the cough"],
        ["der Schnupfen", "the runny nose"],
        ["die Erkältung", "the cold"],
        ["die Grippe", "the flu"],
        ["die Allergie", "the allergy"],
      ],
    },
    {
      id: "ex-habe",
      type: "multiple-choice",
      title: "Übung 4: Ich habe",
      instruction: "Choose the symptom sentence.",
      prompt: "I have a fever and a cough.",
      options: ["Ich habe Fieber und Husten.", "Ich bin Fieber und Husten.", "Ich mache Fieber und Husten."],
      correctIndex: 0,
      explain: "Symptoms take haben.",
    },
    {
      id: "ex-weh",
      type: "multiple-choice",
      title: "Übung 5: Wo tut es weh?",
      instruction: "Choose the pain question.",
      prompt: "The doctor asks where it hurts.",
      options: ["Wo tut es weh?", "Was tut es weh?", "Wie tut es weh?"],
      correctIndex: 0,
      explain: "The pain location: Wo tut es weh?",
    },
    {
      id: "ex-seit",
      type: "multiple-choice",
      title: "Übung 6: Seit wann",
      instruction: "Choose the duration question.",
      prompt: "The doctor asks since when you have it.",
      options: ["Seit wann haben Sie das?", "Wann haben Sie das?", "Wo haben Sie das?"],
      correctIndex: 0,
      explain: "The duration question: Seit wann?",
    },
    {
      id: "ex-imperativ",
      type: "multiple-choice",
      title: "Übung 7: Der Imperativ",
      instruction: "Choose the doctor instruction.",
      prompt: "Open your mouth!",
      options: ["Öffnen Sie den Mund!", "Öffnen den Mund!", "Sie öffnen den Mund!"],
      correctIndex: 0,
      explain: "The formal imperative: Öffnen Sie.",
    },
    {
      id: "ex-rezept",
      type: "multiple-choice",
      title: "Übung 8: Das Rezept",
      instruction: "Choose the prescription phrase.",
      prompt: "The doctor prescribes you something.",
      options: ["Ich verschreibe Ihnen etwas.", "Ich gebe Ihnen ein Rezept etwas.", "Ich verschreibe Ihnen das."],
      correctIndex: 0,
      explain: "The prescription verb: verschreiben.",
    },
    {
      id: "ex-tablette",
      type: "multiple-choice",
      title: "Übung 9: Die Tablette",
      instruction: "Choose the medicine instruction.",
      prompt: "Take one tablet three times a day.",
      options: ["Nehmen Sie dreimal täglich eine Tablette.", "Nehmen Sie dreimal täglich Tabletten.", "Sie nehmen dreimal täglich eine Tablette."],
      correctIndex: 0,
      explain: "The medicine instruction.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 10: Hören",
      instruction: "Play the audio and pick the symptom you heard.",
      prompt: "das Fieber",
      options: ["das Fieber", "der Husten", "der Schnupfen"],
      correctIndex: 0,
      explain: "The symptom heard: fever.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 11: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Was fehlt Ihnen?",
      options: ["Was fehlt Ihnen?", "Wo tut es weh?", "Seit wann haben Sie das?"],
      correctIndex: 0,
      explain: "The doctor question heard.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 12: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Ich habe Fieber und Husten.", "Ich bin Fieber und Husten.", "Ich habe Fieber und bin Husten."],
      correctIndex: 0,
      explain: "Symptoms take haben.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 13: Der Satz",
      instruction: "Build the sentence: I would like to make an appointment.",
      chunks: ["Ich", "möchte", "einen", "Termin", "machen."], translation: "I would like to make an appointment.",
      explain: "The appointment sentence.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 14: Der Satz",
      instruction: "Build the sentence: I have a fever.",
      chunks: ["Ich", "habe", "Fieber."], translation: "I have a fever.",
      explain: "The symptom sentence.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 15: Arztkarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "Ich möchte einen Termin machen.", back: "I would like to make an appointment.", frontAudio: true },
        { front: "Was fehlt Ihnen?", back: "What is wrong with you?", frontAudio: true },
        { front: "Ich habe Fieber.", back: "I have a fever.", frontAudio: true },
        { front: "Wo tut es weh?", back: "Where does it hurt?", frontAudio: true },
        { front: "Öffnen Sie den Mund!", back: "Open your mouth!", frontAudio: true },
        { front: "Atmen Sie tief!", back: "Breathe deeply!", frontAudio: true },
        { front: "Es ist nichts Schlimmes.", back: "It is nothing serious.", frontAudio: true },
        { front: "Nehmen Sie dreimal täglich eine Tablette.", back: "Take one tablet three times a day.", frontAudio: true },
        { front: "das Rezept", back: "the prescription", frontAudio: true },
        { front: "die Krankschreibung", back: "the sick note", frontAudio: true },
        { front: "die Erkältung", back: "the cold", frontAudio: true },
        { front: "die Grippe", back: "the flu", frontAudio: true },
      ],
    },
  ],
};

export const gesundheitstipps: Lesson = {
  id: "gesundheitstipps",
  title: "Gesundheitstipps",
  summary:
    "Health tips and advice: the modal verbs for health, the imperative advice, and the complete healthy living vocabulary for A1.",
  status: "ready",
  sections: [
    {
      heading: "Gesund leben",
      blocks: [
        {
          type: "paragraph",
          text: "The health advice (die Gesundheitstipps) covers: gesund essen (to eat healthily), viel Wasser trinken (to drink lots of water), Sport treiben (to do sport), genug schlafen (to sleep enough), sich ausruhen (to rest). The modal advice: Du sollst mehr Sport machen. (You should do more sport.)",
        },
        {
          type: "table",
          caption: "The health tips",
          head: ["German", "English"],
          rows: [
            ["gesund essen", "to eat healthily"],
            ["viel Wasser trinken", "to drink lots of water"],
            ["Sport treiben", "to do sport"],
            ["genug schlafen", "to sleep enough"],
            ["sich ausruhen", "to rest"],
            ["sich bewegen", "to move around"],
            ["nicht rauchen", "not to smoke"],
          ],
        },
        {
          type: "example",
          de: "Du sollst gesund essen, viel Wasser trinken und genug schlafen.",
          en: "The health advice with sollen.",
        },
        {
          type: "tip",
          text: "The advice verb: sollen (should). Du sollst + healthy activity. The activity nouns: der Sport, die Bewegung, der Schlaf.",
        },
      ],
    },
    {
      heading: "Die Modalverben für Gesundheit",
      blocks: [
        {
          type: "paragraph",
          text: "The health modals: sollen for advice (Du sollst mehr schlafen), müssen for necessity (Ich muss zum Arzt), dürfen for permission (Du darfst nicht rauchen), können for ability (Ich kann heute nicht kommen). The pair: Du musst (you must) and Du darfst nicht (you must not).",
        },
        {
          type: "table",
          caption: "The health modals",
          head: ["Modal", "English", "Example"],
          rows: [
            ["sollen", "should", "Du sollst gesund essen."],
            ["müssen", "must", "Ich muss zum Arzt."],
            ["dürfen", "may (not)", "Du darfst nicht rauchen."],
            ["können", "can", "Ich kann gut schlafen."],
            ["wollen", "want", "Ich will abnehmen."],
          ],
        },
        {
          type: "example",
          de: "Du sollst mehr Sport machen. Du musst genug schlafen. Du darfst nicht rauchen.",
          en: "You should do more sport. You must sleep enough. You must not smoke.",
        },
        {
          type: "tip",
          text: "The health modal trio: sollen (advice), müssen (necessity), dürfen nicht (prohibition). The bracket structure: modal in second place, infinitive at the end.",
        },
      ],
    },
    {
      heading: "Der Ratschlag im Imperativ",
      blocks: [
        {
          type: "paragraph",
          text: "The health advice also uses the imperative: Trink mehr Wasser! (Drink more water!), Mach mehr Sport! (Do more sport!), Schlaf genug! (Sleep enough!), Ruhe dich aus! (Rest!). The informal du-forms and the ihr-forms: Trinkt mehr Wasser!",
        },
        {
          type: "table",
          caption: "The advice imperative",
          head: ["Formal", "Informal (du)", "Informal (ihr)"],
          rows: [
            ["Trinken Sie mehr Wasser!", "Trink mehr Wasser!", "Trinkt mehr Wasser!"],
            ["Machen Sie Sport!", "Mach Sport!", "Macht Sport!"],
            ["Schlafen Sie genug!", "Schlaf genug!", "Schlaft genug!"],
          ],
        },
        {
          type: "example",
          de: "Trink mehr Wasser und mach mehr Sport! Dann fühlst du dich besser.",
          en: "Drink more water and do more sport! Then you will feel better.",
        },
        {
          type: "tip",
          text: "The du-imperative: the bare stem (Trink, Mach, Schlaf). The ihr-imperative: stem + t (Trinkt, Macht, Schlaft).",
        },
      ],
    },
    {
      heading: "Gesund essen",
      blocks: [
        {
          type: "paragraph",
          text: "Healthy eating covers: das Gemüse (vegetables), das Obst (fruit), der Salat (salad), das Vollkornbrot (wholemeal bread), das Wasser (water), and the unhealthy: der Zucker (sugar), die Süßigkeiten (sweets), die Pommes (chips), das Fast Food (fast food). The advice: Iss viel Obst und Gemüse! (Eat lots of fruit and vegetables!).",
        },
        {
          type: "table",
          caption: "Healthy and unhealthy",
          head: ["Healthy", "Unhealthy"],
          rows: [
            ["das Gemüse", "der Zucker"],
            ["das Obst", "die Süßigkeiten"],
            ["der Salat", "die Pommes"],
            ["das Vollkornbrot", "das Fast Food"],
            ["das Wasser", "die Limonade"],
          ],
        },
        {
          type: "example",
          de: "Iss viel Obst und Gemüse, aber wenig Zucker und Süßigkeiten.",
          en: "The healthy eating advice.",
        },
        {
          type: "tip",
          text: "The healthy eating pair: viel (lots of) and wenig (little). Iss viel Obst, aber wenig Zucker.",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: mixing the modals, wrong imperative forms, and confusing the healthy words.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["sollen/müssen mix", "Du musst gesund essen, nein du sollst.", "Du sollst gesund essen.", "advice takes sollen"],
            ["dürfen loss", "Du nicht rauchen.", "Du darfst nicht rauchen.", "the modal carries the prohibition"],
            ["imperative form", "Trinkt du mehr Wasser.", "Trink mehr Wasser!", "the du-imperative drops the -st"],
            ["bracket structure", "Du sollst mehr Sport machen? Nein, du Sport machen sollst.", "Du sollst mehr Sport machen.", "modal second, infinitive last"],
            ["much/little mix", "viel Zucker? Nein, wenig Zucker.", "wenig Zucker", "too much sugar is unhealthy"],
          ],
        },
        {
          type: "tip",
          text: "The health topic is a script: the tip with sollen, the necessity with müssen, the prohibition with dürfen nicht, and the healthy foods.",
        },
      ],
    },
  ],
  vocab: [
    { id: "die-gesundheit", de: "die Gesundheit", en: "the health", part: "noun f.", audio: true },
    { id: "gesund", de: "gesund", en: "healthy", part: "adjective", audio: true },
    { id: "krank", de: "krank", en: "sick", part: "adjective", audio: true },
    { id: "der-sport", de: "der Sport", en: "the sport", part: "noun m.", audio: true },
    { id: "sport-treiben", de: "Sport treiben", en: "to do sport", part: "phrase", phrase: true, audio: true },
    { id: "schlafen", de: "schlafen", en: "to sleep", part: "verb", audio: true },
    { id: "sich-ausruhen", de: "sich ausruhen", en: "to rest", part: "verb", audio: true },
    { id: "sich-bewegen", de: "sich bewegen", en: "to move around", part: "verb", audio: true },
    { id: "rauchen", de: "rauchen", en: "to smoke", part: "verb", audio: true },
    { id: "abnehmen", de: "abnehmen", en: "to lose weight", part: "verb", audio: true },
    { id: "das-gemuese", de: "das Gemüse", en: "the vegetables", part: "noun n.", audio: true },
    { id: "das-obst", de: "das Obst", en: "the fruit", part: "noun n.", audio: true },
    { id: "das-vollkornbrot", de: "das Vollkornbrot", en: "the wholemeal bread", part: "noun n.", plural: "die Vollkornbrote", audio: true },
    { id: "der-zucker", de: "der Zucker", en: "the sugar", part: "noun m.", audio: true },
    { id: "die-suessigkeiten", de: "die Süßigkeiten", en: "the sweets", part: "noun pl.", audio: true },
    { id: "die-pommes", de: "die Pommes", en: "the chips", part: "noun pl.", audio: true },
    { id: "das-fast-food", de: "das Fast Food", en: "the fast food", part: "noun n.", audio: true },
    { id: "du-sollst-gesund-essen", de: "Du sollst gesund essen.", en: "You should eat healthily.", part: "phrase", phrase: true, audio: true },
    { id: "du-sollst-mehr-sport-machen", de: "Du sollst mehr Sport machen.", en: "You should do more sport.", part: "phrase", phrase: true, audio: true },
    { id: "du-musst-zum-arzt", de: "Du musst zum Arzt.", en: "You must go to the doctor.", part: "phrase", phrase: true, audio: true },
    { id: "du-darfst-nicht-rauchen", de: "Du darfst nicht rauchen.", en: "You must not smoke.", part: "phrase", phrase: true, audio: true },
    { id: "trink-mehr-wasser", de: "Trink mehr Wasser!", en: "Drink more water!", part: "phrase", phrase: true, audio: true },
    { id: "iss-viel-obst", de: "Iss viel Obst und Gemüse!", en: "Eat lots of fruit and vegetables!", part: "phrase", phrase: true, audio: true },
    { id: "genug-schlafen", de: "genug schlafen", en: "to sleep enough", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-tipps",
      type: "matching",
      title: "Übung 1: Die Tipps",
      instruction: "Match each health tip to its meaning.",
      pairs: [
        ["gesund essen", "to eat healthily"],
        ["viel Wasser trinken", "to drink lots of water"],
        ["Sport treiben", "to do sport"],
        ["genug schlafen", "to sleep enough"],
        ["sich ausruhen", "to rest"],
        ["nicht rauchen", "not to smoke"],
      ],
    },
    {
      id: "ex-sollen",
      type: "multiple-choice",
      title: "Übung 2: sollen",
      instruction: "Choose the advice sentence.",
      prompt: "You should do more sport.",
      options: ["Du sollst mehr Sport machen.", "Du musst mehr Sport machen.", "Du darfst mehr Sport machen."],
      correctIndex: 0,
      explain: "Advice takes sollen.",
    },
    {
      id: "ex-muessen",
      type: "multiple-choice",
      title: "Übung 3: müssen",
      instruction: "Choose the necessity sentence.",
      prompt: "You must go to the doctor.",
      options: ["Du musst zum Arzt.", "Du sollst zum Arzt.", "Du darfst zum Arzt."],
      correctIndex: 0,
      explain: "Necessity takes müssen.",
    },
    {
      id: "ex-duerfen",
      type: "multiple-choice",
      title: "Übung 4: dürfen",
      instruction: "Choose the prohibition sentence.",
      prompt: "You must not smoke.",
      options: ["Du darfst nicht rauchen.", "Du sollst nicht rauchen.", "Du musst nicht rauchen."],
      correctIndex: 0,
      explain: "The prohibition takes dürfen nicht.",
    },
    {
      id: "ex-bracket",
      type: "multiple-choice",
      title: "Übung 5: Die Klammer",
      instruction: "Choose the correct sentence.",
      prompt: "You should eat healthily.",
      options: ["Du sollst gesund essen.", "Du gesund essen sollst.", "Du sollst essen gesund."],
      correctIndex: 0,
      explain: "The modal bracket: sollen second, infinitive last.",
    },
    {
      id: "ex-imperativ",
      type: "multiple-choice",
      title: "Übung 6: Der Imperativ",
      instruction: "Choose the du-imperative.",
      prompt: "Drink more water! (informal)",
      options: ["Trink mehr Wasser!", "Trinkst mehr Wasser!", "Trinken mehr Wasser!"],
      correctIndex: 0,
      explain: "The du-imperative is the bare stem.",
    },
    {
      id: "ex-imperativ-2",
      type: "multiple-choice",
      title: "Übung 7: Der Imperativ",
      instruction: "Choose the correct imperative.",
      prompt: "Do more sport! (informal)",
      options: ["Mach mehr Sport!", "Macht du mehr Sport!", "Machen mehr Sport!"],
      correctIndex: 0,
      explain: "The du-imperative: Mach.",
    },
    {
      id: "ex-essen",
      type: "matching",
      title: "Übung 8: Gesund essen",
      instruction: "Sort into healthy and unhealthy.",
      pairs: [
        ["das Gemüse", "healthy"],
        ["das Obst", "healthy"],
        ["der Zucker", "unhealthy"],
        ["die Süßigkeiten", "unhealthy"],
        ["das Wasser", "healthy"],
        ["die Pommes", "unhealthy"],
      ],
    },
    {
      id: "ex-iss",
      type: "multiple-choice",
      title: "Übung 9: Iss",
      instruction: "Choose the eating advice.",
      prompt: "Eat lots of fruit and vegetables!",
      options: ["Iss viel Obst und Gemüse!", "Iss wenig Obst und Gemüse!", "Iss viel Zucker und Süßigkeiten!"],
      correctIndex: 0,
      explain: "The healthy eating advice.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 10: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Du sollst mehr Sport machen.",
      options: ["Du sollst mehr Sport machen.", "Du sollst gesund essen.", "Du musst mehr Sport machen."],
      correctIndex: 0,
      explain: "The advice heard: more sport.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 11: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Trink mehr Wasser!",
      options: ["Trink mehr Wasser!", "Trinkt mehr Wasser!", "Trinken Sie mehr Wasser!"],
      correctIndex: 0,
      explain: "The imperative heard: du-form.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 12: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Du sollst genug schlafen.", "Du genug schlafen sollst.", "Du sollst schlafen genug."],
      correctIndex: 0,
      explain: "The modal bracket structure.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 13: Der Satz",
      instruction: "Build the sentence: You should do more sport.",
      chunks: ["Du", "sollst", "mehr", "Sport", "machen."], translation: "You should do more sport.",
      explain: "The modal bracket.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 14: Der Satz",
      instruction: "Build the sentence: You must not smoke.",
      chunks: ["Du", "darfst", "nicht", "rauchen."], translation: "You must not smoke.",
      explain: "The prohibition sentence.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 15: Gesundheitskarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "Du sollst gesund essen.", back: "You should eat healthily.", frontAudio: true },
        { front: "Du sollst mehr Sport machen.", back: "You should do more sport.", frontAudio: true },
        { front: "Du musst zum Arzt.", back: "You must go to the doctor.", frontAudio: true },
        { front: "Du darfst nicht rauchen.", back: "You must not smoke.", frontAudio: true },
        { front: "Trink mehr Wasser!", back: "Drink more water!", frontAudio: true },
        { front: "Iss viel Obst und Gemüse!", back: "Eat lots of fruit and vegetables!", frontAudio: true },
        { front: "genug schlafen", back: "to sleep enough", frontAudio: true },
        { front: "Sport treiben", back: "to do sport", frontAudio: true },
        { front: "das Gemüse", back: "the vegetables", frontAudio: true },
        { front: "das Obst", back: "the fruit", frontAudio: true },
        { front: "gesund", back: "healthy", frontAudio: true },
        { front: "krank", back: "sick", frontAudio: true },
      ],
    },
  ],
};

export const gesundheitUndKoerper: Unit = {
  id: "gesundheit-und-koerper",
  title: "Gesundheit und Körper",
  theme: "Health and body",
  lessons: [
    derKoerper,
    beimArzt,
    gesundheitstipps,
  ],
};