import type { Lesson, Unit } from "../../schema";

const derKoerper: Lesson = {
  id: "der-koerper",
  title: "Der Körper",
  summary: "Body parts and simple ailments.",
  status: "ready",
  sections: [
    {
      heading: "Die Körperteile",
      blocks: [
        {
          type: "table",
          caption: "Body parts",
          head: ["German", "English"],
          rows: [
            ["der Kopf", "the head"],
            ["das Haar", "the hair"],
            ["das Gesicht", "the face"],
            ["das Auge", "the eye"],
            ["die Nase", "the nose"],
            ["der Mund", "the mouth"],
            ["das Ohr", "the ear"],
            ["der Hals", "the neck"],
            ["die Schulter", "the shoulder"],
            ["der Arm", "the arm"],
            ["die Hand", "the hand"],
            ["der Finger", "the finger"],
            ["der Bauch", "the belly"],
            ["der Rücken", "the back"],
            ["das Bein", "the leg"],
            ["das Knie", "the knee"],
            ["der Fuß", "the foot"],
            ["der Zahn", "the tooth"],
          ],
        },
        {
          type: "tip",
          text: "Pain is expressed with weh tun: Mein Kopf tut weh. (My head hurts.) The body part is the subject.",
        },
      ],
    },
    {
      heading: "Der Körper im Satz",
      blocks: [
        {
          type: "example",
          de: "Mein Kopf tut weh.",
          en: "My head hurts.",
        },
        {
          type: "example",
          de: "Ich habe kalte Hände.",
          en: "I have cold hands.",
        },
        {
          type: "example",
          de: "Der Rücken tut mir weh.",
          en: "My back hurts (to me).",
        },
        {
          type: "tip",
          text: "weh tun is separable: tut ... weh. With people, the dative pronoun joins: Der Rücken tut mir weh.",
        },
      ],
    },
  ],
  vocab: [
    { id: "der-kopf", de: "der Kopf", en: "the head", part: "noun m.", plural: "die Köpfe", audio: true },
    { id: "das-haar", de: "das Haar", en: "the hair", part: "noun n.", plural: "die Haare", audio: true },
    { id: "das-gesicht", de: "das Gesicht", en: "the face", part: "noun n.", plural: "die Gesichter", audio: true },
    { id: "das-auge", de: "das Auge", en: "the eye", part: "noun n.", plural: "die Augen", audio: true },
    { id: "die-nase", de: "die Nase", en: "the nose", part: "noun f.", plural: "die Nasen", audio: true },
    { id: "der-mund", de: "der Mund", en: "the mouth", part: "noun m.", plural: "die Münder", audio: true },
    { id: "das-ohr", de: "das Ohr", en: "the ear", part: "noun n.", plural: "die Ohren", audio: true },
    { id: "der-hals", de: "der Hals", en: "the neck", part: "noun m.", plural: "die Hälse", audio: true },
    { id: "die-hand", de: "die Hand", en: "the hand", part: "noun f.", plural: "die Hände", audio: true },
    { id: "der-arm", de: "der Arm", en: "the arm", part: "noun m.", plural: "die Arme", audio: true },
    { id: "der-bauch", de: "der Bauch", en: "the belly", part: "noun m.", plural: "die Bäuche", audio: true },
    { id: "der-ruecken", de: "der Rücken", en: "the back", part: "noun m.", plural: "die Rücken", audio: true },
    { id: "das-bein", de: "das Bein", en: "the leg", part: "noun n.", plural: "die Beine", audio: true },
    { id: "der-fuss", de: "der Fuß", en: "the foot", part: "noun m.", plural: "die Füße", audio: true },
    { id: "der-zahn", de: "der Zahn", en: "the tooth", part: "noun m.", plural: "die Zähne", audio: true },
    { id: "weh-tun", de: "weh tun", en: "to hurt", part: "verb", audio: true },
    { id: "mein-kopf-tut-weh", de: "Mein Kopf tut weh.", en: "My head hurts.", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "mc-koerper",
      type: "multiple-choice",
      title: "Der Körper",
      instruction: "Choose the body part.",
      prompt: "Du siehst mit den ...",
      options: ["Augen", "Ohren", "Händen"],
      correctIndex: 0,
      explain: "You see with the eyes: die Augen.",
    },
    {
      id: "listening-koerper",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the body part you heard.",
      prompt: "die Schulter",
      options: ["die Schulter", "der Bauch", "das Knie"],
      correctIndex: 0,
    },
    {
      id: "fill-koerper",
      type: "fill-blank",
      title: "Der Körper",
      instruction: "Complete the sentences.",
      sentence: "Mein ___ tut weh. (head) Ich habe kalte ___.",
      blanks: [
        { answers: ["Kopf"], hint: "head" },
        { answers: ["Hände"], hint: "hands" },
      ],
    },
    {
      id: "matching-koerper",
      type: "matching",
      title: "Körperteile",
      instruction: "Match each German word to its meaning.",
      pairs: [
        ["der Kopf", "the head"],
        ["das Auge", "the eye"],
        ["die Hand", "the hand"],
        ["der Fuß", "the foot"],
        ["das Bein", "the leg"],
      ],
    },
    {
      id: "word-order-koerper",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: My head hurts.",
      chunks: ["Mein", "Kopf", "tut", "weh."],
      explain: "The prefix weh closes the sentence.",
    },
    {
      id: "flashcard-koerper",
      type: "flashcard",
      title: "Körperkarten",
      instruction: "Say the German word out loud before revealing.",
      items: [
        { front: "der Kopf", back: "the head", frontAudio: true },
        { front: "das Auge", back: "the eye", frontAudio: true },
        { front: "die Nase", back: "the nose", frontAudio: true },
        { front: "die Hand", back: "the hand", frontAudio: true },
        { front: "der Fuß", back: "the foot", frontAudio: true },
        { front: "Mein Kopf tut weh.", back: "My head hurts.", frontAudio: true },
      ],
    },
  ],
};

const beimArzt: Lesson = {
  id: "beim-arzt",
  title: "Beim Arzt",
  summary: "At the doctor: describing how you feel.",
  status: "ready",
  sections: [
    {
      heading: "Beim Arzt",
      blocks: [
        {
          type: "table",
          caption: "Doctor visit vocabulary",
          head: ["German", "English"],
          rows: [
            ["der Arzt / die Ärztin", "the doctor"],
            ["die Praxis", "the practice"],
            ["der Termin", "the appointment"],
            ["krank", "sick"],
            ["gesund", "healthy"],
            ["der Schmerz", "the pain"],
            ["das Fieber", "the fever"],
            ["der Husten", "the cough"],
            ["der Schnupfen", "the cold (runny nose)"],
            ["die Medizin", "the medicine"],
            ["das Rezept", "the prescription"],
            ["die Tablette", "the pill"],
            ["die Apotheke", "the pharmacy"],
          ],
        },
        {
          type: "tip",
          text: "The doctor is beim Arzt, the pharmacy die Apotheke. Medicine is die Medizin, a prescription das Rezept.",
        },
      ],
    },
    {
      heading: "Die Symptome",
      blocks: [
        {
          type: "table",
          caption: "Saying how you feel",
          head: ["German", "English"],
          rows: [
            ["Ich bin krank.", "I am sick."],
            ["Ich habe Fieber.", "I have a fever."],
            ["Ich habe Husten.", "I have a cough."],
            ["Mir tut der Kopf weh.", "My head hurts."],
            ["Mir tut der Bauch weh.", "My belly hurts."],
            ["Was fehlt Ihnen?", "What is wrong with you?"],
          ],
        },
        {
          type: "example",
          de: "Arzt: Was fehlt Ihnen? Patient: Ich habe Fieber und Husten. Mein Kopf tut weh.",
          en: "Doctor: What is wrong? Patient: I have a fever and a cough. My head hurts.",
        },
        {
          type: "example",
          de: "Nehmen Sie diese Tabletten und trinken Sie viel Wasser.",
          en: "Take these pills and drink lots of water.",
        },
      ],
    },
  ],
  vocab: [
    { id: "die-praxis", de: "die Praxis", en: "the practice", part: "noun f.", plural: "die Praxen", audio: true },
    { id: "krank", de: "krank", en: "sick", part: "adjective", audio: true },
    { id: "gesund", de: "gesund", en: "healthy", part: "adjective", audio: true },
    { id: "der-schmerz", de: "der Schmerz", en: "the pain", part: "noun m.", plural: "die Schmerzen", audio: true },
    { id: "das-fieber", de: "das Fieber", en: "the fever", part: "noun n.", audio: true },
    { id: "der-husten", de: "der Husten", en: "the cough", part: "noun m.", audio: true },
    { id: "der-schnupfen", de: "der Schnupfen", en: "the cold (runny nose)", part: "noun m.", audio: true },
    { id: "die-medizin", de: "die Medizin", en: "the medicine", part: "noun f.", plural: "die Medizinen", audio: true },
    { id: "das-rezept", de: "das Rezept", en: "the prescription", part: "noun n.", plural: "die Rezepte", audio: true },
    { id: "die-tablette", de: "die Tablette", en: "the pill", part: "noun f.", plural: "die Tabletten", audio: true },
    { id: "ich-habe-fieber", de: "Ich habe Fieber.", en: "I have a fever.", part: "phrase", phrase: true, audio: true },
    { id: "was-fehlt-ihnen", de: "Was fehlt Ihnen?", en: "What is wrong with you?", part: "phrase", phrase: true, audio: true },
    { id: "mir-tut-weh", de: "Mir tut der Kopf weh.", en: "My head hurts.", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "mc-arzt",
      type: "multiple-choice",
      title: "Beim Arzt",
      instruction: "Choose the right phrase.",
      prompt: "You have a fever. You say ...",
      options: ["Ich habe Fieber.", "Ich habe Husten.", "Ich habe Schnupfen."],
      correctIndex: 0,
      explain: "Fever is das Fieber: Ich habe Fieber.",
    },
    {
      id: "listening-arzt",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Ich habe Husten und Schnupfen.",
      options: [
        "Ich habe Husten und Schnupfen.",
        "Ich habe Fieber und Husten.",
        "Ich habe Fieber und Schnupfen.",
      ],
      correctIndex: 0,
    },
    {
      id: "fill-arzt",
      type: "fill-blank",
      title: "Die Symptome",
      instruction: "Complete the sentences.",
      sentence: "Ich habe ___. (fever) Mir tut der ___ weh. (head)",
      blanks: [
        { answers: ["Fieber"], hint: "fever" },
        { answers: ["Kopf"], hint: "head" },
      ],
    },
    {
      id: "matching-arzt",
      type: "matching",
      title: "Beim Arzt",
      instruction: "Match each German word to its meaning.",
      pairs: [
        ["das Fieber", "the fever"],
        ["der Husten", "the cough"],
        ["das Rezept", "the prescription"],
        ["die Tablette", "the pill"],
        ["die Apotheke", "the pharmacy"],
      ],
    },
    {
      id: "word-order-arzt",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: I am sick.",
      chunks: ["Ich", "bin", "krank."],
      explain: "The adjective follows sein.",
    },
    {
      id: "flashcard-arzt",
      type: "flashcard",
      title: "Arztkarten",
      instruction: "Say the German out loud before revealing.",
      items: [
        { front: "Ich bin krank.", back: "I am sick.", frontAudio: true },
        { front: "Ich habe Fieber.", back: "I have a fever.", frontAudio: true },
        { front: "Ich habe Husten.", back: "I have a cough.", frontAudio: true },
        { front: "Mir tut der Kopf weh.", back: "My head hurts.", frontAudio: true },
        { front: "das Rezept", back: "the prescription", frontAudio: true },
        { front: "die Apotheke", back: "the pharmacy", frontAudio: true },
      ],
    },
  ],
};

const gesundheitstipps: Lesson = {
  id: "gesundheitstipps",
  title: "Gesundheitstipps",
  summary: "Healthy habits with sollen and imperatives.",
  status: "ready",
  sections: [
    {
      heading: "Tipps geben mit sollen",
      blocks: [
        {
          type: "paragraph",
          text: "Advice uses sollen: you should. It conjugates like a modal: du sollst, Sie sollen. The advice verb waits at the end.",
        },
        {
          type: "example",
          de: "Du sollst mehr Wasser trinken.",
          en: "You should drink more water.",
        },
        {
          type: "example",
          de: "Sie sollen genug schlafen.",
          en: "You should sleep enough.",
        },
        {
          type: "example",
          de: "Wir sollen mehr Obst essen.",
          en: "We should eat more fruit.",
        },
      ],
    },
    {
      heading: "Gesund leben",
      blocks: [
        {
          type: "table",
          caption: "Healthy habits",
          head: ["German", "English"],
          rows: [
            ["Sport machen", "to do sports"],
            ["sich bewegen", "to exercise"],
            ["viel Wasser trinken", "to drink lots of water"],
            ["genug schlafen", "to sleep enough"],
            ["Obst und Gemüse essen", "to eat fruit and vegetables"],
            ["nicht rauchen", "not to smoke"],
            ["wenig Zucker", "little sugar"],
          ],
        },
        {
          type: "example",
          de: "Mach mehr Sport! Iss mehr Obst!",
          en: "Do more sports! Eat more fruit!",
        },
        {
          type: "tip",
          text: "Advice has two shapes: sollen with a verb (Du sollst schlafen.) or the imperative (Schlaf mehr!). Both appear at the doctor's.",
        },
      ],
    },
  ],
  vocab: [
    { id: "sport-machen", de: "Sport machen", en: "to do sports", part: "phrase", phrase: true, audio: true },
    { id: "sich-bewegen", de: "sich bewegen", en: "to exercise, move", part: "phrase", phrase: true, audio: true },
    { id: "viel-wasser", de: "viel Wasser trinken", en: "to drink lots of water", part: "phrase", phrase: true, audio: true },
    { id: "genug-schlafen", de: "genug schlafen", en: "to sleep enough", part: "phrase", phrase: true, audio: true },
    { id: "rauchen", de: "rauchen", en: "to smoke", part: "verb", audio: true },
    { id: "der-zucker", de: "der Zucker", en: "the sugar", part: "noun m.", audio: true },
    { id: "wenig", de: "wenig", en: "little (amount)", part: "adjective", audio: true },
    { id: "mehr", de: "mehr", en: "more", part: "adjective", audio: true },
    { id: "du-sollst", de: "Du sollst ...", en: "You should ...", part: "phrase", phrase: true, audio: true },
    { id: "gesund-leben", de: "gesund leben", en: "to live healthily", part: "phrase", phrase: true, audio: true },
    { id: "der-tipp", de: "der Tipp", en: "the tip", part: "noun m.", plural: "die Tipps", audio: true },
  ],
  exercises: [
    {
      id: "mc-tipps",
      type: "multiple-choice",
      title: "Der Rat",
      instruction: "Choose the correct form of sollen.",
      prompt: "Du ___ mehr Wasser trinken.",
      options: ["sollst", "soll", "sollen"],
      correctIndex: 0,
      explain: "du takes sollst.",
    },
    {
      id: "listening-tipps",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the advice you heard.",
      prompt: "Du sollst genug schlafen.",
      options: [
        "Du sollst genug schlafen.",
        "Du sollst mehr Sport machen.",
        "Du sollst mehr Obst essen.",
      ],
      correctIndex: 0,
    },
    {
      id: "fill-tipps",
      type: "fill-blank",
      title: "Die Tipps",
      instruction: "Complete the advice.",
      sentence: "Du ___ mehr Wasser trinken. (should) Mach mehr ___! (sports)",
      blanks: [
        { answers: ["sollst"], hint: "sollen, du" },
        { answers: ["Sport"], hint: "Sport machen" },
      ],
    },
    {
      id: "matching-tipps",
      type: "matching",
      title: "Gesundheit",
      instruction: "Match each phrase to its meaning.",
      pairs: [
        ["Sport machen", "to do sports"],
        ["genug schlafen", "to sleep enough"],
        ["nicht rauchen", "not to smoke"],
        ["wenig Zucker", "little sugar"],
        ["gesund leben", "to live healthily"],
      ],
    },
    {
      id: "word-order-tipps",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: You should drink more water.",
      chunks: ["Du", "sollst", "mehr", "Wasser", "trinken."],
      explain: "The infinitive closes the sentence.",
    },
    {
      id: "flashcard-tipps",
      type: "flashcard",
      title: "Tippkarten",
      instruction: "Say the German out loud before revealing.",
      items: [
        { front: "Du sollst mehr Wasser trinken.", back: "You should drink more water.", frontAudio: true },
        { front: "Du sollst genug schlafen.", back: "You should sleep enough.", frontAudio: true },
        { front: "Mach mehr Sport!", back: "Do more sports!", frontAudio: true },
        { front: "Iss mehr Obst!", back: "Eat more fruit!", frontAudio: true },
        { front: "Sport machen", back: "to do sports", frontAudio: true },
        { front: "gesund leben", back: "to live healthily", frontAudio: true },
      ],
    },
  ],
};

export const gesundheitUndKoerper: Unit = {
  id: "gesundheit-und-koerper",
  title: "Gesundheit und Körper",
  theme: "Health and body",
  lessons: [
    derKoerper,
    beimArzt,
    gesundheitstipps,
  ],
};