import type { Lesson, Unit } from "../../schema";

const dieStadt: Lesson = {
  id: "die-stadt",
  title: "Die Stadt",
  summary: "Places in the city: der Bahnhof, die Apotheke, das Kino.",
  status: "ready",
  sections: [
    {
      heading: "Die Orte",
      blocks: [
        {
          type: "table",
          caption: "Places in the city",
          head: ["German", "English"],
          rows: [
            ["der Bahnhof", "the train station"],
            ["die Apotheke", "the pharmacy"],
            ["das Kino", "the cinema"],
            ["das Restaurant", "the restaurant"],
            ["das Café", "the café"],
            ["die Kirche", "the church"],
            ["das Museum", "the museum"],
            ["das Krankenhaus", "the hospital"],
            ["die Schule", "the school"],
            ["das Rathaus", "the town hall"],
            ["der Park", "the park"],
            ["das Schwimmbad", "the swimming pool"],
            ["das Geschäft", "the shop"],
            ["die Bank", "the bank"],
            ["die Post", "the post office"],
            ["die Bibliothek", "the library"],
          ],
        },
        {
          type: "tip",
          text: "Ask for places with the pattern Wo ist + place? Entschuldigung, wo ist die Apotheke? The answer starts with a direction or a landmark.",
        },
      ],
    },
    {
      heading: "In der Stadt",
      blocks: [
        {
          type: "example",
          de: "Ich gehe in die Stadt. Ich brauche die Apotheke.",
          en: "I am going into town. I need the pharmacy.",
        },
        {
          type: "example",
          de: "Das Kino ist neben dem Museum.",
          en: "The cinema is next to the museum.",
        },
        {
          type: "example",
          de: "Entschuldigung, wo ist der Bahnhof?",
          en: "Excuse me, where is the train station?",
        },
      ],
    },
  ],
  vocab: [
    { id: "der-bahnhof", de: "der Bahnhof", en: "the train station", part: "noun m.", plural: "die Bahnhöfe", audio: true },
    { id: "die-apotheke", de: "die Apotheke", en: "the pharmacy", part: "noun f.", plural: "die Apotheken", audio: true },
    { id: "das-kino", de: "das Kino", en: "the cinema", part: "noun n.", plural: "die Kinos", audio: true },
    { id: "das-restaurant", de: "das Restaurant", en: "the restaurant", part: "noun n.", plural: "die Restaurants", audio: true },
    { id: "das-museum", de: "das Museum", en: "the museum", part: "noun n.", plural: "die Museen", audio: true },
    { id: "das-krankenhaus", de: "das Krankenhaus", en: "the hospital", part: "noun n.", plural: "die Krankenhäuser", audio: true },
    { id: "die-schule", de: "die Schule", en: "the school", part: "noun f.", plural: "die Schulen", audio: true },
    { id: "das-rathaus", de: "das Rathaus", en: "the town hall", part: "noun n.", plural: "die Rathäuser", audio: true },
    { id: "der-park", de: "der Park", en: "the park", part: "noun m.", plural: "die Parks", audio: true },
    { id: "das-schwimmbad", de: "das Schwimmbad", en: "the swimming pool", part: "noun n.", plural: "die Schwimmbäder", audio: true },
    { id: "das-geschaeft", de: "das Geschäft", en: "the shop", part: "noun n.", plural: "die Geschäfte", audio: true },
    { id: "die-bank", de: "die Bank", en: "the bank", part: "noun f.", plural: "die Banken", audio: true },
    { id: "die-post", de: "die Post", en: "the post office", part: "noun f.", audio: true },
    { id: "die-bibliothek", de: "die Bibliothek", en: "the library", part: "noun f.", plural: "die Bibliotheken", audio: true },
    { id: "entschuldigung", de: "Entschuldigung", en: "excuse me", part: "interjection", audio: true },
  ],
  exercises: [
    {
      id: "mc-ort",
      type: "multiple-choice",
      title: "Wo ist das?",
      instruction: "Choose the place for the activity.",
      prompt: "Wo kaufst du Medikamente? In der ...",
      options: ["Apotheke", "Bibliothek", "Bank"],
      correctIndex: 0,
      explain: "Medicines come from die Apotheke.",
    },
    {
      id: "listening-ort",
      type: "listening",
      title: "Welcher Ort?",
      instruction: "Play the audio and pick the place you heard.",
      prompt: "das Krankenhaus",
      options: ["das Krankenhaus", "das Rathaus", "das Museum"],
      correctIndex: 0,
    },
    {
      id: "fill-ort",
      type: "fill-blank",
      title: "In der Stadt",
      instruction: "Complete the sentences.",
      sentence: "Das Kino ist neben dem ___. Ich brauche die ___.",
      blanks: [
        { answers: ["Museum"], hint: "the museum" },
        { answers: ["Apotheke"], hint: "the pharmacy" },
      ],
    },
    {
      id: "matching-ort",
      type: "matching",
      title: "Orte",
      instruction: "Match each German word to its meaning.",
      pairs: [
        ["der Bahnhof", "the train station"],
        ["das Kino", "the cinema"],
        ["die Apotheke", "the pharmacy"],
        ["die Schule", "the school"],
        ["der Park", "the park"],
      ],
    },
    {
      id: "word-order-ort",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: The cinema is next to the museum.",
      chunks: ["Das", "Kino", "ist", "neben", "dem", "Museum."],
      explain: "The dative phrase closes the sentence.",
    },
    {
      id: "flashcard-ort",
      type: "flashcard",
      title: "Stadtkarten",
      instruction: "Say the German place out loud before revealing.",
      items: [
        { front: "der Bahnhof", back: "the train station", frontAudio: true },
        { front: "die Apotheke", back: "the pharmacy", frontAudio: true },
        { front: "das Kino", back: "the cinema", frontAudio: true },
        { front: "das Krankenhaus", back: "the hospital", frontAudio: true },
        { front: "der Park", back: "the park", frontAudio: true },
        { front: "die Bibliothek", back: "the library", frontAudio: true },
      ],
    },
  ],
};

const richtungen: Lesson = {
  id: "richtungen",
  title: "Richtungen und Wege",
  summary: "Asking and giving directions: links, rechts, geradeaus.",
  status: "ready",
  sections: [
    {
      heading: "Die Richtungen",
      blocks: [
        {
          type: "table",
          caption: "Directions",
          head: ["German", "English"],
          rows: [
            ["links", "left"],
            ["rechts", "right"],
            ["geradeaus", "straight ahead"],
            ["an der Ampel", "at the traffic light"],
            ["an der Kreuzung", "at the crossing"],
            ["um die Ecke", "around the corner"],
            ["die zweite Straße", "the second street"],
            ["gegenüber", "opposite"],
            ["der Stadtplan", "the city map"],
          ],
        },
        {
          type: "tip",
          text: "Directions usually come as imperatives: Gehen Sie geradeaus. An der Ampel links. Short and direct is correct.",
        },
      ],
    },
    {
      heading: "Nach dem Weg fragen",
      blocks: [
        {
          type: "example",
          de: "Entschuldigung, wie komme ich zum Bahnhof?",
          en: "Excuse me, how do I get to the station?",
        },
        {
          type: "example",
          de: "Gehen Sie geradeaus. An der Ampel links. Dann die zweite Straße rechts.",
          en: "Go straight ahead. At the traffic light turn left. Then the second street on the right.",
        },
        {
          type: "example",
          de: "Das Kino ist um die Ecke, gegenüber der Bank.",
          en: "The cinema is around the corner, opposite the bank.",
        },
        {
          type: "tip",
          text: "The answer verbs: biegen (to turn), bleiben (to stay), gehen (to go). In commands they appear as biegen Sie ab, bleiben Sie auf der Straße, gehen Sie geradeaus.",
        },
      ],
    },
  ],
  vocab: [
    { id: "links", de: "links", en: "left", part: "adverb", audio: true },
    { id: "rechts", de: "rechts", en: "right", part: "adverb", audio: true },
    { id: "geradeaus", de: "geradeaus", en: "straight ahead", part: "adverb", audio: true },
    { id: "die-ampel", de: "die Ampel", en: "the traffic light", part: "noun f.", plural: "die Ampeln", audio: true },
    { id: "die-kreuzung", de: "die Kreuzung", en: "the crossing", part: "noun f.", plural: "die Kreuzungen", audio: true },
    { id: "die-ecke", de: "die Ecke", en: "the corner", part: "noun f.", plural: "die Ecken", audio: true },
    { id: "gegenueber", de: "gegenüber", en: "opposite", part: "adverb", audio: true },
    { id: "der-stadtplan", de: "der Stadtplan", en: "the city map", part: "noun m.", plural: "die Stadtpläne", audio: true },
    { id: "wie-komme-ich", de: "Wie komme ich zum Bahnhof?", en: "How do I get to the station?", part: "phrase", phrase: true, audio: true },
    { id: "um-die-ecke", de: "um die Ecke", en: "around the corner", part: "phrase", phrase: true, audio: true },
    { id: "biegen", de: "biegen", en: "to turn", part: "verb", audio: true },
    { id: "ab-biegen", de: "abbiegen", en: "to turn off (a road)", part: "verb", audio: true },
  ],
  exercises: [
    {
      id: "mc-richtung",
      type: "multiple-choice",
      title: "Die Richtung",
      instruction: "Choose the direction word.",
      prompt: "Not left, not right, but ...",
      options: ["geradeaus", "gegenüber", "um die Ecke"],
      correctIndex: 0,
      explain: "Straight ahead is geradeaus.",
    },
    {
      id: "listening-richtung",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the phrase you heard.",
      prompt: "an der Ampel links",
      options: ["an der Ampel links", "an der Ampel rechts", "die zweite Straße links"],
      correctIndex: 0,
    },
    {
      id: "fill-richtung",
      type: "fill-blank",
      title: "Der Weg",
      instruction: "Complete the directions.",
      sentence: "Gehen Sie ___ (straight). An der Ampel ___ (left).",
      blanks: [
        { answers: ["geradeaus"], hint: "straight ahead" },
        { answers: ["links"], hint: "left" },
      ],
    },
    {
      id: "matching-richtung",
      type: "matching",
      title: "Richtungen",
      instruction: "Match each German word to its meaning.",
      pairs: [
        ["links", "left"],
        ["rechts", "right"],
        ["geradeaus", "straight ahead"],
        ["die Ampel", "the traffic light"],
        ["gegenüber", "opposite"],
      ],
    },
    {
      id: "word-order-richtung",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: At the traffic light, turn left.",
      chunks: ["An", "der", "Ampel", "links."],
      explain: "The landmark comes first, the direction last.",
    },
    {
      id: "flashcard-richtung",
      type: "flashcard",
      title: "Richtungskarten",
      instruction: "Say the German out loud before revealing.",
      items: [
        { front: "links", back: "left", frontAudio: true },
        { front: "rechts", back: "right", frontAudio: true },
        { front: "geradeaus", back: "straight ahead", frontAudio: true },
        { front: "an der Ampel", back: "at the traffic light", frontAudio: true },
        { front: "um die Ecke", back: "around the corner", frontAudio: true },
        { front: "Wie komme ich zum Bahnhof?", back: "How do I get to the station?", frontAudio: true },
      ],
    },
  ],
};

const woWoherWohin: Lesson = {
  id: "wo-woher-wohin",
  title: "Wo, woher, wohin?",
  summary: "Location, origin, and destination with the right preposition.",
  status: "ready",
  sections: [
    {
      heading: "Drei Fragen, drei Präpositionen",
      blocks: [
        {
          type: "table",
          caption: "The three direction questions",
          head: ["Question", "Meaning", "Preposition", "Example"],
          rows: [
            ["Wo?", "where (static)", "in, an, auf, bei + dative", "Ich bin in der Stadt."],
            ["Woher?", "where from", "aus, von + dative", "Ich komme aus dem Büro."],
            ["Wohin?", "where to", "nach, in, zu", "Ich gehe in die Stadt."],
          ],
        },
        {
          type: "tip",
          text: "woher pairs with aus and von, wohin with nach, in and zu. Mixing them up is the most common learner mistake, so drill these three pairs.",
        },
      ],
    },
    {
      heading: "wohin im Detail",
      blocks: [
        {
          type: "paragraph",
          text: "nach goes with places without an article: cities and countries. in goes with article places, zu with people and buildings.",
        },
        {
          type: "table",
          caption: "wohin choices",
          head: ["Target", "Preposition", "Example"],
          rows: [
            ["city", "nach", "nach Berlin"],
            ["country (no article)", "nach", "nach Italien"],
            ["article country", "in", "in die Schweiz"],
            ["building", "zu", "zum Bahnhof"],
            ["person", "zu", "zu Anna"],
            ["home", "nach", "nach Hause"],
          ],
        },
        {
          type: "example",
          de: "Ich fahre nach Berlin. Ich fliege in die Schweiz. Ich gehe zum Bahnhof.",
          en: "I drive to Berlin. I fly to Switzerland. I walk to the station.",
        },
      ],
    },
    {
      heading: "Woher im Detail",
      blocks: [
        {
          type: "paragraph",
          text: "aus names the origin, von names the point you are coming from. In practice, aus for countries and places, von for people and buildings.",
        },
        {
          type: "example",
          de: "Ich komme aus Deutschland. Er kommt gerade aus dem Büro.",
          en: "I come from Germany. He is just coming from the office.",
        },
        {
          type: "example",
          de: "Ich komme von Anna. Wir kommen vom Bahnhof.",
          en: "I come from Anna's place. We come from the station.",
        },
      ],
    },
  ],
  vocab: [
    { id: "wo-wo", de: "wo", en: "where (static)", part: "question word", audio: true },
    { id: "woher", de: "woher", en: "where from", part: "question word", audio: true },
    { id: "wohin", de: "wohin", en: "where to", part: "question word", audio: true },
    { id: "nach-berlin", de: "nach Berlin", en: "to Berlin", part: "phrase", phrase: true, audio: true },
    { id: "in-die-schweiz", de: "in die Schweiz", en: "to Switzerland", part: "phrase", phrase: true, audio: true },
    { id: "zum-bahnhof", de: "zum Bahnhof", en: "to the station", part: "phrase", phrase: true, audio: true },
    { id: "zu-anna", de: "zu Anna", en: "to Anna's", part: "phrase", phrase: true, audio: true },
    { id: "nach-hause", de: "nach Hause", en: "home (direction)", part: "phrase", phrase: true, audio: true },
    { id: "aus-deutschland", de: "aus Deutschland", en: "from Germany", part: "phrase", phrase: true, audio: true },
    { id: "aus-dem-buero", de: "aus dem Büro", en: "from the office", part: "phrase", phrase: true, audio: true },
    { id: "vom-bahnhof", de: "vom Bahnhof", en: "from the station", part: "phrase", phrase: true, audio: true },
    { id: "zu-hause", de: "zu Hause", en: "at home (static)", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "mc-wo-woher-wohin",
      type: "multiple-choice",
      title: "Die Frage",
      instruction: "Choose the matching question word.",
      prompt: "___ kommst du? Aus Deutschland.",
      options: ["Woher", "Wo", "Wohin"],
      correctIndex: 0,
      explain: "Origin asks woher.",
    },
    {
      id: "listening-wo-woher-wohin",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the phrase you heard.",
      prompt: "in die Schweiz",
      options: ["in die Schweiz", "aus der Schweiz", "nach der Schweiz"],
      correctIndex: 0,
    },
    {
      id: "fill-wo-woher-wohin",
      type: "fill-blank",
      title: "Nach oder in?",
      instruction: "Complete with the right preposition.",
      sentence: "Ich fahre ___ Berlin. Ich fliege ___ die Türkei.",
      blanks: [
        { answers: ["nach"], hint: "city without article" },
        { answers: ["in"], hint: "article country" },
      ],
    },
    {
      id: "matching-wo-woher-wohin",
      type: "matching",
      title: "Frage und Präposition",
      instruction: "Match each question to its preposition.",
      pairs: [
        ["Wo?", "in, an, auf"],
        ["Woher?", "aus, von"],
        ["Wohin?", "nach, zu"],
        ["home direction", "nach Hause"],
        ["home static", "zu Hause"],
      ],
    },
    {
      id: "word-order-wo-woher-wohin",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: I am driving to Berlin.",
      chunks: ["Ich", "fahre", "nach", "Berlin."],
      explain: "The destination follows the verb.",
    },
    {
      id: "flashcard-wo-woher-wohin",
      type: "flashcard",
      title: "Richtungskarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "nach Berlin", back: "to Berlin", frontAudio: true },
        { front: "in die Schweiz", back: "to Switzerland", frontAudio: true },
        { front: "zum Bahnhof", back: "to the station", frontAudio: true },
        { front: "aus Deutschland", back: "from Germany", frontAudio: true },
        { front: "vom Bahnhof", back: "from the station", frontAudio: true },
        { front: "nach Hause", back: "home (direction)", frontAudio: true },
      ],
    },
  ],
};

const oeffentlicheVerkehrsmittel: Lesson = {
  id: "oeffentliche-verkehrsmittel",
  title: "Öffentliche Verkehrsmittel",
  summary: "Buses and trains: tickets and times.",
  status: "ready",
  sections: [
    {
      heading: "Die Verkehrsmittel",
      blocks: [
        {
          type: "table",
          caption: "Public transport",
          head: ["German", "English"],
          rows: [
            ["der Bus", "the bus"],
            ["die Straßenbahn", "the tram"],
            ["die U-Bahn", "the subway"],
            ["der Zug", "the train"],
            ["das Taxi", "the taxi"],
            ["die Haltestelle", "the stop"],
            ["das Ticket / die Fahrkarte", "the ticket"],
            ["der Bahnsteig", "the platform"],
            ["die Verspätung", "the delay"],
            ["umsteigen", "to change (trains)"],
          ],
        },
        {
          type: "tip",
          text: "U-Bahn is the underground, S-Bahn the city railway. Both are just die Bahn. Die Haltestelle is a bus or tram stop, der Bahnhof the train station.",
        },
      ],
    },
    {
      heading: "Am Bahnhof",
      blocks: [
        {
          type: "example",
          de: "Ich brauche eine Fahrkarte nach Berlin.",
          en: "I need a ticket to Berlin.",
        },
        {
          type: "example",
          de: "Wann fährt der Zug ab? Um 14:30 Uhr.",
          en: "When does the train depart? At 2:30 p.m.",
        },
        {
          type: "example",
          de: "Sie müssen in Hamburg umsteigen.",
          en: "You have to change trains in Hamburg.",
        },
        {
          type: "example",
          de: "Der Zug hat zehn Minuten Verspätung.",
          en: "The train is ten minutes late.",
        },
      ],
    },
  ],
  vocab: [
    { id: "der-bus", de: "der Bus", en: "the bus", part: "noun m.", plural: "die Busse", audio: true },
    { id: "die-strassenbahn", de: "die Straßenbahn", en: "the tram", part: "noun f.", plural: "die Straßenbahnen", audio: true },
    { id: "die-u-bahn", de: "die U-Bahn", en: "the subway", part: "noun f.", plural: "die U-Bahnen", audio: true },
    { id: "der-zug", de: "der Zug", en: "the train", part: "noun m.", plural: "die Züge", audio: true },
    { id: "das-taxi", de: "das Taxi", en: "the taxi", part: "noun n.", plural: "die Taxis", audio: true },
    { id: "die-haltestelle", de: "die Haltestelle", en: "the stop", part: "noun f.", plural: "die Haltestellen", audio: true },
    { id: "die-fahrkarte", de: "die Fahrkarte", en: "the ticket", part: "noun f.", plural: "die Fahrkarten", audio: true },
    { id: "der-bahnsteig", de: "der Bahnsteig", en: "the platform", part: "noun m.", plural: "die Bahnsteige", audio: true },
    { id: "die-verspaetung", de: "die Verspätung", en: "the delay", part: "noun f.", plural: "die Verspätungen", audio: true },
    { id: "umsteigen", de: "umsteigen", en: "to change (trains)", part: "verb", audio: true },
    { id: "abfahren", de: "abfahren", en: "to depart", part: "verb", audio: true },
    { id: "ankommen", de: "ankommen", en: "to arrive", part: "verb", audio: true },
  ],
  exercises: [
    {
      id: "mc-verkehr",
      type: "multiple-choice",
      title: "Das Verkehrsmittel",
      instruction: "Choose the right vehicle.",
      prompt: "Which one goes underground?",
      options: ["die U-Bahn", "die Straßenbahn", "der Bus"],
      correctIndex: 0,
      explain: "U-Bahn runs underground.",
    },
    {
      id: "listening-verkehr",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the word you heard.",
      prompt: "die Verspätung",
      options: ["die Verspätung", "die Haltestelle", "die Fahrkarte"],
      correctIndex: 0,
    },
    {
      id: "fill-verkehr",
      type: "fill-blank",
      title: "Am Bahnhof",
      instruction: "Complete the sentences.",
      sentence: "Wann fährt der Zug ___? (depart) Ich brauche eine ___ nach Berlin.",
      blanks: [
        { answers: ["ab"], hint: "separable prefix" },
        { answers: ["Fahrkarte"], hint: "ticket" },
      ],
    },
    {
      id: "matching-verkehr",
      type: "matching",
      title: "Verkehr",
      instruction: "Match each German word to its meaning.",
      pairs: [
        ["der Zug", "the train"],
        ["die Haltestelle", "the stop"],
        ["die Fahrkarte", "the ticket"],
        ["der Bahnsteig", "the platform"],
        ["umsteigen", "to change trains"],
      ],
    },
    {
      id: "word-order-verkehr",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: The train departs at 2:30.",
      chunks: ["Der", "Zug", "fährt", "um", "14:30", "Uhr", "ab."],
      explain: "The prefix ab closes the sentence.",
    },
    {
      id: "flashcard-verkehr",
      type: "flashcard",
      title: "Verkehrskarten",
      instruction: "Say the German out loud before revealing.",
      items: [
        { front: "der Zug", back: "the train", frontAudio: true },
        { front: "die Haltestelle", back: "the stop", frontAudio: true },
        { front: "die Fahrkarte", back: "the ticket", frontAudio: true },
        { front: "der Bahnsteig", back: "the platform", frontAudio: true },
        { front: "umsteigen", back: "to change trains", frontAudio: true },
        { front: "die Verspätung", back: "the delay", frontAudio: true },
      ],
    },
  ],
};

const dasWetter: Lesson = {
  id: "das-wetter",
  title: "Das Wetter",
  summary: "Weather basics: Es regnet, die Sonne scheint.",
  status: "ready",
  sections: [
    {
      heading: "Das Wetter",
      blocks: [
        {
          type: "table",
          caption: "Weather vocabulary",
          head: ["German", "English"],
          rows: [
            ["die Sonne", "the sun"],
            ["der Regen", "the rain"],
            ["der Schnee", "the snow"],
            ["der Wind", "the wind"],
            ["die Wolke", "the cloud"],
            ["das Gewitter", "the thunderstorm"],
            ["die Temperatur", "the temperature"],
            ["der Grad", "the degree"],
          ],
        },
        {
          type: "example",
          de: "Es regnet. Die Sonne scheint.",
          en: "It is raining. The sun is shining.",
        },
        {
          type: "example",
          de: "Es schneit. Der Wind ist stark.",
          en: "It is snowing. The wind is strong.",
        },
      ],
    },
    {
      heading: "Wie ist das Wetter?",
      blocks: [
        {
          type: "table",
          caption: "Weather phrases",
          head: ["German", "English"],
          rows: [
            ["Es ist sonnig.", "It is sunny."],
            ["Es ist bewölkt.", "It is cloudy."],
            ["Es ist windig.", "It is windy."],
            ["Es ist kalt.", "It is cold."],
            ["Es ist warm.", "It is warm."],
            ["Es ist 20 Grad.", "It is 20 degrees."],
          ],
        },
        {
          type: "tip",
          text: "Two patterns: the weather verb (Es regnet, Es schneit) and the adjective after sein (Es ist kalt). Both start with Es.",
        },
      ],
    },
  ],
  vocab: [
    { id: "die-sonne", de: "die Sonne", en: "the sun", part: "noun f.", plural: "die Sonnen", audio: true },
    { id: "der-regen", de: "der Regen", en: "the rain", part: "noun m.", audio: true },
    { id: "der-schnee", de: "der Schnee", en: "the snow", part: "noun m.", audio: true },
    { id: "der-wind", de: "der Wind", en: "the wind", part: "noun m.", plural: "die Winde", audio: true },
    { id: "die-wolke", de: "die Wolke", en: "the cloud", part: "noun f.", plural: "die Wolken", audio: true },
    { id: "das-gewitter", de: "das Gewitter", en: "the thunderstorm", part: "noun n.", plural: "die Gewitter", audio: true },
    { id: "die-temperatur", de: "die Temperatur", en: "the temperature", part: "noun f.", plural: "die Temperaturen", audio: true },
    { id: "regnen", de: "regnen", en: "to rain", part: "verb", audio: true },
    { id: "schneien", de: "schneien", en: "to snow", part: "verb", audio: true },
    { id: "scheinen", de: "scheinen", en: "to shine", part: "verb", audio: true },
    { id: "bewoelkt", de: "bewölkt", en: "cloudy", part: "adjective", audio: true },
    { id: "windig", de: "windig", en: "windy", part: "adjective", audio: true },
    { id: "sonnig", de: "sonnig", en: "sunny", part: "adjective", audio: true },
    { id: "wie-ist-das-wetter", de: "Wie ist das Wetter?", en: "How is the weather?", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "mc-wetter",
      type: "multiple-choice",
      title: "Das Wetter",
      instruction: "Choose the weather word.",
      prompt: "Die Sonne ___.",
      options: ["scheint", "regnet", "schneit"],
      correctIndex: 0,
      explain: "The sun shines: scheint.",
    },
    {
      id: "listening-wetter",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Es ist windig.",
      options: ["Es ist windig.", "Es ist bewölkt.", "Es ist sonnig."],
      correctIndex: 0,
    },
    {
      id: "fill-wetter",
      type: "fill-blank",
      title: "Das Wetter",
      instruction: "Complete the sentences.",
      sentence: "Es ___. (raining) Es ist 20 ___.",
      blanks: [
        { answers: ["regnet"], hint: "weather verb" },
        { answers: ["Grad"], hint: "degrees" },
      ],
    },
    {
      id: "matching-wetter",
      type: "matching",
      title: "Wetter",
      instruction: "Match each German word to its meaning.",
      pairs: [
        ["der Regen", "the rain"],
        ["der Schnee", "the snow"],
        ["die Wolke", "the cloud"],
        ["der Wind", "the wind"],
        ["das Gewitter", "the thunderstorm"],
      ],
    },
    {
      id: "word-order-wetter",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: The sun shines today.",
      chunks: ["Die", "Sonne", "scheint", "heute."],
      explain: "The time adverb follows the verb.",
    },
    {
      id: "flashcard-wetter",
      type: "flashcard",
      title: "Wetterkarten",
      instruction: "Say the German out loud before revealing.",
      items: [
        { front: "die Sonne", back: "the sun", frontAudio: true },
        { front: "der Regen", back: "the rain", frontAudio: true },
        { front: "Es regnet.", back: "It is raining.", frontAudio: true },
        { front: "Es ist kalt.", back: "It is cold.", frontAudio: true },
        { front: "Es ist sonnig.", back: "It is sunny.", frontAudio: true },
        { front: "Es ist 20 Grad.", back: "It is 20 degrees.", frontAudio: true },
      ],
    },
  ],
};

export const stadtUndOrientierung: Unit = {
  id: "stadt-und-orientierung",
  title: "Stadt und Orientierung",
  theme: "City and getting around",
  lessons: [
    dieStadt,
    richtungen,
    woWoherWohin,
    oeffentlicheVerkehrsmittel,
    dasWetter,
  ],
};