import type { Lesson, Unit } from "../../schema";

export const dieStadt: Lesson = {
  id: "die-stadt",
  title: "Die Stadt",
  summary:
    "The complete city vocabulary for A1: the places in town, the buildings, the question patterns, and giving simple directions.",
  status: "ready",
  sections: [
    {
      heading: "Die Orte in der Stadt",
      blocks: [
        {
          type: "paragraph",
          text: "The city (die Stadt) is made of places with strong genders: der Bahnhof (station, m.), die Kirche (church, f.), das Rathaus (town hall, n.), der Markt (market, m.), die Bank (bank, f.), das Kaufhaus (department store, n.), die Apotheke (pharmacy, f.), das Krankenhaus (hospital, n.). The classic question: Wo ist ...? (Where is ...?).",
        },
        {
          type: "table",
          caption: "The places in town",
          head: ["German", "English", "Plural"],
          rows: [
            ["der Bahnhof", "the station", "die Bahnhöfe"],
            ["die Kirche", "the church", "die Kirchen"],
            ["das Rathaus", "the town hall", "die Rathäuser"],
            ["der Markt", "the market", "die Märkte"],
            ["die Bank", "the bank", "die Banken"],
            ["das Kaufhaus", "the department store", "die Kaufhäuser"],
            ["die Apotheke", "the pharmacy", "die Apotheken"],
            ["das Krankenhaus", "the hospital", "die Krankenhäuser"],
            ["das Kino", "the cinema", "die Kinos"],
            ["das Museum", "the museum", "die Museen"],
            ["der Park", "the park", "die Parks"],
            ["der Supermarkt", "the supermarket", "die Supermärkte"],
          ],
        },
        {
          type: "example",
          de: "In der Stadt gibt es einen Bahnhof, eine Kirche, ein Rathaus und viele Geschäfte.",
          en: "Describing your town.",
        },
        {
          type: "tip",
          text: "The city places follow the pattern: der (masculine: Bahnhof, Markt, Park), die (feminine: Kirche, Bank, Apotheke), das (neuter: Rathaus, Kaufhaus, Museum).",
        },
      ],
    },
    {
      heading: "Die Fragen in der Stadt",
      blocks: [
        {
          type: "paragraph",
          text: "The city runs on three questions: Wo ist ...? (Where is ...?) for position, Wie komme ich zum/zur ...? (How do I get to ...?) for directions, and Entschuldigung, wo ist ...? (Excuse me, where is ...?) as the polite opener. The answer pattern: Gehen Sie geradeaus, dann links/rechts.",
        },
        {
          type: "table",
          caption: "The city questions",
          head: ["German", "English"],
          rows: [
            ["Entschuldigung, wo ist der Bahnhof?", "Excuse me, where is the station?"],
            ["Wie komme ich zum Bahnhof?", "How do I get to the station?"],
            ["Wie komme ich zur Kirche?", "How do I get to the church?"],
            ["Ist es weit?", "Is it far?"],
            ["Wo ist die nächste Apotheke?", "Where is the nearest pharmacy?"],
            ["Wie weit ist es bis zum Markt?", "How far is it to the market?"],
          ],
        },
        {
          type: "example",
          de: "Entschuldigung, wie komme ich zum Bahnhof? Gehen Sie geradeaus bis zur Kirche, dann rechts. Danke schön!",
          en: "Excuse me, how do I get to the station? Go straight ahead to the church, then right. Thank you very much!",
        },
        {
          type: "tip",
          text: "The direction question pairs zum for masculine/neuter targets and zur for feminine ones: zum Bahnhof, zur Kirche, zum Rathaus.",
        },
      ],
    },
    {
      heading: "Die Wegbeschreibung",
      blocks: [
        {
          type: "paragraph",
          text: "Giving directions uses the imperative and the direction words: geradeaus (straight ahead), links (left), rechts (right), bis zur (up to), an der Ampel (at the traffic light), um die Ecke (around the corner), die Kreuzung (the crossroads). The pattern: Gehen Sie + direction + bis + target.",
        },
        {
          type: "table",
          caption: "Direction words",
          head: ["German", "English"],
          rows: [
            ["geradeaus", "straight ahead"],
            ["links", "left"],
            ["rechts", "right"],
            ["die Ampel", "the traffic light"],
            ["die Kreuzung", "the crossroads"],
            ["um die Ecke", "around the corner"],
            ["bis zum / bis zur", "up to"],
            ["an der Ampel", "at the traffic light"],
          ],
        },
        {
          type: "example",
          de: "Gehen Sie geradeaus bis zur Ampel, dann links. Das Kaufhaus ist auf der rechten Seite.",
          en: "Go straight ahead to the traffic light, then left. The department store is on the right side.",
        },
        {
          type: "tip",
          text: "The direction script: geradeaus, an der Ampel links/rechts, bis zum/zur, dann ist es auf der rechten/linken Seite.",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: wrong gender, mixing zum and zur, and forgetting the imperative form.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["wrong gender", "der Apotheke", "die Apotheke", "Apotheke is feminine"],
            ["zum/zur mix", "zur Bahnhof", "zum Bahnhof", "Bahnhof is masculine"],
            ["wrong imperative", "Gehen geradeaus!", "Gehen Sie geradeaus!", "the formal imperative keeps Sie"],
            ["missing bis", "Gehen Sie die Ampel.", "Gehen Sie bis zur Ampel.", "direction needs bis"],
            ["apotheke word", "die Apothek", "die Apotheke", "the pharmacy is die Apotheke"],
          ],
        },
        {
          type: "tip",
          text: "The city topic is a script: ask with Entschuldigung, answer with geradeaus/links/rechts, and name the target with zum/zur.",
        },
      ],
    },
  ],
  vocab: [
    { id: "die-stadt", de: "die Stadt", en: "the city", part: "noun f.", plural: "die Städte", audio: true },
    { id: "der-bahnhof", de: "der Bahnhof", en: "the station", part: "noun m.", plural: "die Bahnhöfe", audio: true },
    { id: "die-kirche", de: "die Kirche", en: "the church", part: "noun f.", plural: "die Kirchen", audio: true },
    { id: "das-rathaus", de: "das Rathaus", en: "the town hall", part: "noun n.", plural: "die Rathäuser", audio: true },
    { id: "der-markt", de: "der Markt", en: "the market", part: "noun m.", plural: "die Märkte", audio: true },
    { id: "die-bank", de: "die Bank", en: "the bank", part: "noun f.", plural: "die Banken", audio: true },
    { id: "das-kaufhaus", de: "das Kaufhaus", en: "the department store", part: "noun n.", plural: "die Kaufhäuser", audio: true },
    { id: "die-apotheke", de: "die Apotheke", en: "the pharmacy", part: "noun f.", plural: "die Apotheken", audio: true },
    { id: "das-krankenhaus", de: "das Krankenhaus", en: "the hospital", part: "noun n.", plural: "die Krankenhäuser", audio: true },
    { id: "das-kino", de: "das Kino", en: "the cinema", part: "noun n.", plural: "die Kinos", audio: true },
    { id: "das-museum", de: "das Museum", en: "the museum", part: "noun n.", plural: "die Museen", audio: true },
    { id: "der-park", de: "der Park", en: "the park", part: "noun m.", plural: "die Parks", audio: true },
    { id: "der-supermarkt", de: "der Supermarkt", en: "the supermarket", part: "noun m.", plural: "die Supermärkte", audio: true },
    { id: "das-geschaeft", de: "das Geschäft", en: "the shop", part: "noun n.", plural: "die Geschäfte", audio: true },
    { id: "geradeaus", de: "geradeaus", en: "straight ahead", part: "adverb", audio: true },
    { id: "links", de: "links", en: "left", part: "adverb", audio: true },
    { id: "rechts", de: "rechts", en: "right", part: "adverb", audio: true },
    { id: "die-ampel", de: "die Ampel", en: "the traffic light", part: "noun f.", plural: "die Ampeln", audio: true },
    { id: "die-kreuzung", de: "die Kreuzung", en: "the crossroads", part: "noun f.", plural: "die Kreuzungen", audio: true },
    { id: "wo-ist-der-bahnhof", de: "Entschuldigung, wo ist der Bahnhof?", en: "Excuse me, where is the station?", part: "phrase", phrase: true, audio: true },
    { id: "wie-komme-ich-zum-bahnhof", de: "Wie komme ich zum Bahnhof?", en: "How do I get to the station?", part: "phrase", phrase: true, audio: true },
    { id: "gehen-sie-geradeaus", de: "Gehen Sie geradeaus.", en: "Go straight ahead.", part: "phrase", phrase: true, audio: true },
    { id: "an-der-ampel-links", de: "an der Ampel links", en: "left at the traffic light", part: "phrase", phrase: true, audio: true },
    { id: "ist-es-weit", de: "Ist es weit?", en: "Is it far?", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-orte",
      type: "matching",
      title: "Übung 1: Die Orte",
      instruction: "Match each place to its meaning.",
      pairs: [
        ["der Bahnhof", "the station"],
        ["die Kirche", "the church"],
        ["das Rathaus", "the town hall"],
        ["die Apotheke", "the pharmacy"],
        ["das Krankenhaus", "the hospital"],
        ["das Kaufhaus", "the department store"],
      ],
    },
    {
      id: "ex-genus",
      type: "multiple-choice",
      title: "Übung 2: Das Genus",
      instruction: "Choose the correct article.",
      prompt: "___ Rathaus ist alt.",
      options: ["Das", "Die", "Der"],
      correctIndex: 0,
      explain: "Rathaus is neuter.",
    },
    {
      id: "ex-genus-2",
      type: "multiple-choice",
      title: "Übung 3: Das Genus",
      instruction: "Choose the correct article.",
      prompt: "___ Apotheke ist neben der Bank.",
      options: ["Die", "Das", "Der"],
      correctIndex: 0,
      explain: "Apotheke is feminine.",
    },
    {
      id: "ex-frage",
      type: "multiple-choice",
      title: "Übung 4: Die Frage",
      instruction: "Choose the direction question.",
      prompt: "You ask how to get to the station.",
      options: ["Wie komme ich zum Bahnhof?", "Wo ist der Bahnhof gestern?", "Wie weit ist der Bahnhof?"],
      correctIndex: 0,
      explain: "The getting-there question.",
    },
    {
      id: "ex-zum-zur",
      type: "multiple-choice",
      title: "Übung 5: zum oder zur",
      instruction: "Choose the correct form.",
      prompt: "Wie komme ich ___ Kirche?",
      options: ["zur", "zum", "zu der"],
      correctIndex: 0,
      explain: "Kirche is feminine: zur.",
    },
    {
      id: "ex-richtung",
      type: "multiple-choice",
      title: "Übung 6: Die Richtung",
      instruction: "Choose the direction answer.",
      prompt: "The pharmacy is around the corner.",
      options: ["Die Apotheke ist um die Ecke.", "Die Apotheke ist geradeaus links.", "Die Apotheke ist am Markt rechts."],
      correctIndex: 0,
      explain: "The corner phrase: um die Ecke.",
    },
    {
      id: "ex-weit",
      type: "multiple-choice",
      title: "Übung 7: Ist es weit?",
      instruction: "Choose the distance answer.",
      prompt: "Is it far? No, ...",
      options: ["Nein, es ist nicht weit.", "Nein, es ist weit.", "Ja, es ist hier."],
      correctIndex: 0,
      explain: "The far answer: nicht weit.",
    },
    {
      id: "ex-imperativ",
      type: "multiple-choice",
      title: "Übung 8: Der Imperativ",
      instruction: "Choose the correct direction.",
      prompt: "Go straight ahead (formal).",
      options: ["Gehen Sie geradeaus.", "Geh geradeaus.", "Geradeaus gehen Sie."],
      correctIndex: 0,
      explain: "The formal imperative: Gehen Sie geradeaus.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 9: Hören",
      instruction: "Play the audio and pick the place you heard.",
      prompt: "die Apotheke",
      options: ["die Apotheke", "die Bank", "die Kirche"],
      correctIndex: 0,
      explain: "The place heard: pharmacy.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 10: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Gehen Sie geradeaus bis zur Ampel.",
      options: ["Gehen Sie geradeaus bis zur Ampel.", "Gehen Sie links bis zur Ampel.", "Gehen Sie geradeaus bis zur Kirche."],
      correctIndex: 0,
      explain: "The direction heard.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 11: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Wie komme ich zum Bahnhof?", "Wie komme ich zur Bahnhof?", "Wie komme ich in dem Bahnhof?"],
      correctIndex: 0,
      explain: "Bahnhof is masculine: zum.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 12: Der Satz",
      instruction: "Build the sentence: How do I get to the station?",
      chunks: ["Wie", "komme", "ich", "zum", "Bahnhof?"], translation: "How do I get to the station?",
      explain: "The direction question.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 13: Der Satz",
      instruction: "Build the sentence: The pharmacy is around the corner.",
      chunks: ["Die", "Apotheke", "ist", "um", "die", "Ecke."], translation: "The pharmacy is around the corner.",
      explain: "The corner position.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 14: Stadtkarten",
      instruction: "Say the German with the article out loud.",
      items: [
        { front: "der Bahnhof", back: "the station", frontAudio: true },
        { front: "die Kirche", back: "the church", frontAudio: true },
        { front: "das Rathaus", back: "the town hall", frontAudio: true },
        { front: "die Apotheke", back: "the pharmacy", frontAudio: true },
        { front: "das Krankenhaus", back: "the hospital", frontAudio: true },
        { front: "das Museum", back: "the museum", frontAudio: true },
        { front: "geradeaus", back: "straight ahead", frontAudio: true },
        { front: "Wie komme ich zum Bahnhof?", back: "How do I get to the station?", frontAudio: true },
        { front: "Ist es weit?", back: "Is it far?", frontAudio: true },
        { front: "um die Ecke", back: "around the corner", frontAudio: true },
        { front: "an der Ampel links", back: "left at the traffic light", frontAudio: true },
        { front: "Gehen Sie geradeaus.", back: "Go straight ahead.", frontAudio: true },
      ],
    },
    {
      id: "ex-wiederholung",
      type: "multiple-choice",
      title: "Übung 15: Die Wiederholung",
      instruction: "Choose the correct answer.",
      prompt: "You need a pharmacy urgently.",
      options: ["Wo ist die nächste Apotheke?", "Wo ist das nächste Museum?", "Wo ist der nächste Park?"],
      correctIndex: 0,
      explain: "The nearest pharmacy question.",
    },
  ],
};

export const richtungen: Lesson = {
  id: "richtungen",
  title: "Richtungen",
  summary:
    "Giving and understanding directions: the imperative, the direction words, the landmarks, and the complete direction dialogue for A1.",
  status: "ready",
  sections: [
    {
      heading: "Die Richtungswörter",
      blocks: [
        {
          type: "paragraph",
          text: "Directions run on a small set of words: geradeaus (straight ahead), links (left), rechts (right), vor (in front of), hinter (behind), neben (next to), zwischen (between), gegenüber (opposite), und bis (up to). The question: Wie komme ich ...? The answer starts with the imperative.",
        },
        {
          type: "table",
          caption: "Direction words",
          head: ["German", "English", "Example"],
          rows: [
            ["geradeaus", "straight ahead", "Gehen Sie geradeaus."],
            ["links", "left", "Dann links."],
            ["rechts", "right", "An der Ampel rechts."],
            ["gegenüber", "opposite", "Das Hotel ist gegenüber."],
            ["neben", "next to", "Die Bank ist neben der Kirche."],
            ["zwischen", "between", "zwischen Bahnhof und Markt"],
            ["bis", "up to", "bis zur Ampel"],
          ],
        },
        {
          type: "example",
          de: "Gehen Sie geradeaus, an der Ampel links, dann bis zur Kirche. Die Bank ist gegenüber der Kirche.",
          en: "Go straight ahead, left at the traffic light, then on to the church. The bank is opposite the church.",
        },
        {
          type: "tip",
          text: "The direction order: verb first (Gehen Sie), then geradeaus/links/rechts, then bis + target. The landmarks: die Ampel, die Kreuzung, die Kirche.",
        },
      ],
    },
    {
      heading: "Der Imperativ der Richtung",
      blocks: [
        {
          type: "paragraph",
          text: "Directions use the imperative: the formal Gehen Sie (you go), and the informal geh (you, singular) and geht (you, plural). The pair: Gehen Sie geradeaus (formal) and Geh geradeaus (informal). The exam mostly uses the formal form.",
        },
        {
          type: "table",
          caption: "The direction imperative",
          head: ["Verb", "Formal", "Informal (du)", "Informal (ihr)"],
          rows: [
            ["gehen", "Gehen Sie", "geh", "geht"],
            ["fahren", "Fahren Sie", "fahr", "fahrt"],
            ["nehmen", "Nehmen Sie", "nimm", "nehmt"],
            ["biegen", "Biegen Sie", "bieg", "biegt"],
          ],
        },
        {
          type: "example",
          de: "Nehmen Sie die zweite Straße rechts. Biegen Sie an der Ampel links ab.",
          en: "Take the second street on the right. Turn left at the traffic light.",
        },
        {
          type: "tip",
          text: "The formal imperative: infinitive stem + Sie. Nehmen Sie, Fahren Sie, Biegen Sie. The informal: just the stem, geh, fahr, nimm.",
        },
      ],
    },
    {
      heading: "Der komplette Dialog",
      blocks: [
        {
          type: "paragraph",
          text: "Here is the full direction dialogue, the exam's classic listening task.",
        },
        {
          type: "example",
          de: "Entschuldigung, wie komme ich zum Bahnhof? Gehen Sie geradeaus bis zur Ampel, dann biegen Sie links ab. Dann ist der Bahnhof auf der rechten Seite. Wie weit ist es? Ungefähr zehn Minuten zu Fuß. Danke schön! Gern geschehen!",
          en: "Excuse me, how do I get to the station? Go straight ahead to the traffic light, then turn left. Then the station is on the right side. How far is it? About ten minutes on foot. Thank you very much! You're welcome!",
        },
        {
          type: "tip",
          text: "The dialogue covers the exam points: the question, the imperative, the landmarks, the distance (zehn Minuten zu Fuß), and the polite close.",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: wrong imperative form, confusing the prepositions, and forgetting the landmarks.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["informal for formal", "Geh Sie geradeaus.", "Gehen Sie geradeaus.", "the formal keeps the infinitive"],
            ["links/rechts mix", "an der Ampel rechts statt links", "an der Ampel links", "left and right swap the route"],
            ["wrong bis", "bis die Ampel", "bis zur Ampel", "bis needs the article"],
            ["missing abbiegen", "Biegen links.", "Biegen Sie links ab.", "abbiegen is separable"],
            ["gegenüber case", "gegenüber der Kirche", "gegenüber der Kirche", "gegenüber takes the dative"],
          ],
        },
        {
          type: "tip",
          text: "The direction is a route: the start (geradeaus), the turn (an der Ampel links/rechts), the target (bis zum/zur), and the distance (zu Fuß).",
        },
      ],
    },
  ],
  vocab: [
    { id: "geradeaus", de: "geradeaus", en: "straight ahead", part: "adverb", audio: true },
    { id: "links", de: "links", en: "left", part: "adverb", audio: true },
    { id: "rechts", de: "rechts", en: "right", part: "adverb", audio: true },
    { id: "gegenueber", de: "gegenüber", en: "opposite", part: "adverb", audio: true },
    { id: "neben", de: "neben", en: "next to", part: "preposition", audio: true },
    { id: "zwischen", de: "zwischen", en: "between", part: "preposition", audio: true },
    { id: "bis", de: "bis", en: "up to", part: "preposition", audio: true },
    { id: "abbiegen", de: "abbiegen", en: "to turn", part: "verb", audio: true },
    { id: "biegen", de: "biegen", en: "to turn", part: "verb", audio: true },
    { id: "zu-fuss", de: "zu Fuß", en: "on foot", part: "phrase", phrase: true, audio: true },
    { id: "die-seite", de: "die Seite", en: "the side", part: "noun f.", plural: "die Seiten", audio: true },
    { id: "die-ecke", de: "die Ecke", en: "the corner", part: "noun f.", plural: "die Ecken", audio: true },
    { id: "die-zweite-strasse", de: "die zweite Straße", en: "the second street", part: "phrase", phrase: true, audio: true },
    { id: "auf-der-rechten-seite", de: "auf der rechten Seite", en: "on the right side", part: "phrase", phrase: true, audio: true },
    { id: "auf-der-linken-seite", de: "auf der linken Seite", en: "on the left side", part: "phrase", phrase: true, audio: true },
    { id: "wie-komme-ich-zum-bahnhof", de: "Wie komme ich zum Bahnhof?", en: "How do I get to the station?", part: "phrase", phrase: true, audio: true },
    { id: "gehen-sie-geradeaus", de: "Gehen Sie geradeaus.", en: "Go straight ahead.", part: "phrase", phrase: true, audio: true },
    { id: "biegen-sie-links-ab", de: "Biegen Sie links ab.", en: "Turn left.", part: "phrase", phrase: true, audio: true },
    { id: "ungefaehr-zehn-minuten", de: "Ungefähr zehn Minuten zu Fuß.", en: "About ten minutes on foot.", part: "phrase", phrase: true, audio: true },
    { id: "gern-geschehen", de: "Gern geschehen!", en: "You are welcome!", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-woerter",
      type: "matching",
      title: "Übung 1: Die Richtungswörter",
      instruction: "Match each direction word to its meaning.",
      pairs: [
        ["geradeaus", "straight ahead"],
        ["links", "left"],
        ["rechts", "right"],
        ["gegenüber", "opposite"],
        ["neben", "next to"],
        ["zwischen", "between"],
      ],
    },
    {
      id: "ex-imperativ",
      type: "multiple-choice",
      title: "Übung 2: Der Imperativ",
      instruction: "Choose the formal direction.",
      prompt: "Go straight ahead (formal).",
      options: ["Gehen Sie geradeaus.", "Geh geradeaus.", "Geht geradeaus."],
      correctIndex: 0,
      explain: "The formal imperative: Gehen Sie.",
    },
    {
      id: "ex-ab",
      type: "multiple-choice",
      title: "Übung 3: abbiegen",
      instruction: "Choose the correct turn.",
      prompt: "Turn left at the traffic light.",
      options: ["Biegen Sie an der Ampel links ab.", "Biegen Sie links an der Ampel.", "Sie biegen links ab an der Ampel."],
      correctIndex: 0,
      explain: "The separable verb: biegen ... ab.",
    },
    {
      id: "ex-bis",
      type: "multiple-choice",
      title: "Übung 4: bis",
      instruction: "Choose the correct phrase.",
      prompt: "up to the traffic light",
      options: ["bis zur Ampel", "bis die Ampel", "bis Ampel"],
      correctIndex: 0,
      explain: "bis + article: bis zur Ampel.",
    },
    {
      id: "ex-zu-fuss",
      type: "multiple-choice",
      title: "Übung 5: zu Fuß",
      instruction: "Choose the distance answer.",
      prompt: "About ten minutes on foot.",
      options: ["Ungefähr zehn Minuten zu Fuß.", "Ungefähr zehn Minuten mit Fuß.", "Zehn Minuten Fuß."],
      correctIndex: 0,
      explain: "The distance phrase: zu Fuß.",
    },
    {
      id: "ex-gegenueber",
      type: "multiple-choice",
      title: "Übung 6: gegenüber",
      instruction: "Choose the correct sentence.",
      prompt: "The bank is opposite the church.",
      options: ["Die Bank ist gegenüber der Kirche.", "Die Bank ist gegenüber Kirche.", "Die Bank ist gegenüber die Kirche."],
      correctIndex: 0,
      explain: "gegenüber takes the dative.",
    },
    {
      id: "ex-dialog",
      type: "matching",
      title: "Übung 7: Der Dialog",
      instruction: "Put the direction dialogue in order.",
      pairs: [
        ["Entschuldigung, wie komme ich zum Bahnhof?", "the question"],
        ["Gehen Sie geradeaus bis zur Ampel.", "the start"],
        ["Dann biegen Sie links ab.", "the turn"],
        ["Der Bahnhof ist auf der rechten Seite.", "the target"],
        ["Ungefähr zehn Minuten zu Fuß.", "the distance"],
      ],
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 8: Hören",
      instruction: "Play the audio and pick the direction you heard.",
      prompt: "an der Ampel links",
      options: ["an der Ampel links", "an der Ampel rechts", "an der Kirche links"],
      correctIndex: 0,
      explain: "The direction heard: left at the light.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 9: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Der Bahnhof ist auf der rechten Seite.",
      options: ["Der Bahnhof ist auf der rechten Seite.", "Der Bahnhof ist auf der linken Seite.", "Das Rathaus ist auf der rechten Seite."],
      correctIndex: 0,
      explain: "The target sentence heard.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 10: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Biegen Sie an der Ampel links ab.", "Biegen Sie an der Ampel links.", "Sie abbiegen an der Ampel links."],
      correctIndex: 0,
      explain: "The separable verb splits.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 11: Der Satz",
      instruction: "Build the sentence: Turn left at the traffic light.",
      chunks: ["Biegen", "Sie", "an", "der", "Ampel", "links", "ab."], translation: "Turn left at the traffic light.",
      explain: "The separable imperative.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 12: Der Satz",
      instruction: "Build the sentence: The bank is opposite the church.",
      chunks: ["Die", "Bank", "ist", "gegenüber", "der", "Kirche."], translation: "The bank is opposite the church.",
      explain: "gegenüber with the dative.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 13: Richtungskarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "Gehen Sie geradeaus.", back: "Go straight ahead.", frontAudio: true },
        { front: "Biegen Sie links ab.", back: "Turn left.", frontAudio: true },
        { front: "an der Ampel rechts", back: "right at the traffic light", frontAudio: true },
        { front: "bis zur Ampel", back: "up to the traffic light", frontAudio: true },
        { front: "auf der rechten Seite", back: "on the right side", frontAudio: true },
        { front: "auf der linken Seite", back: "on the left side", frontAudio: true },
        { front: "gegenüber der Kirche", back: "opposite the church", frontAudio: true },
        { front: "zu Fuß", back: "on foot", frontAudio: true },
        { front: "Ungefähr zehn Minuten zu Fuß.", back: "About ten minutes on foot.", frontAudio: true },
        { front: "Gern geschehen!", back: "You are welcome!", frontAudio: true },
        { front: "abbiegen", back: "to turn", frontAudio: true },
        { front: "geradeaus", back: "straight ahead", frontAudio: true },
      ],
    },
  ],
};

export const woWoherWohin: Lesson = {
  id: "wo-woher-wohin",
  title: "Wo, woher, wohin?",
  summary:
    "The three location questions: Wo (where), Woher (where from), Wohin (where to), and their preposition systems for A1.",
  status: "ready",
  sections: [
    {
      heading: "Die drei Fragen",
      blocks: [
        {
          type: "paragraph",
          text: "German asks about place in three directions: Wo? (Where?) asks where something is, Woher? (Where from?) asks the origin, Wohin? (Where to?) asks the destination. Each has its own preposition: Wo takes in/an/bei with the dative, Woher takes aus/von with the dative, Wohin takes in/an/auf with the accusative.",
        },
        {
          type: "table",
          caption: "The three questions",
          head: ["Question", "English", "Answer preposition", "Case"],
          rows: [
            ["Wo?", "Where?", "in, an, bei", "dative"],
            ["Woher?", "Where from?", "aus, von", "dative"],
            ["Wohin?", "Where to?", "in, an, auf", "accusative"],
          ],
        },
        {
          type: "example",
          de: "Wo bist du? Ich bin in der Stadt. Woher kommst du? Ich komme aus Berlin. Wohin gehst du? Ich gehe in die Stadt.",
          en: "Where are you? I am in town. Where are you from? I'm from Berlin. Where are you going? I'm going into town.",
        },
        {
          type: "tip",
          text: "The triple test: Wo (in der Stadt), Woher (aus Berlin), Wohin (in die Stadt). The Wo pair takes the dative, Wohin the accusative.",
        },
      ],
    },
    {
      heading: "aus und von: Woher",
      blocks: [
        {
          type: "paragraph",
          text: "The Woher answers: aus for origin in a place (aus Berlin, aus Deutschland, aus der Wohnung), von for coming off or from a person or building (vom Bahnhof, von der Arbeit, von Anna). The question: Woher kommst du? Ich komme aus Berlin.",
        },
        {
          type: "table",
          caption: "aus and von",
          head: ["Preposition", "When", "Example"],
          rows: [
            ["aus", "origin, country, city, inside", "aus Berlin, aus Deutschland"],
            ["aus", "out of a room", "aus der Küche"],
            ["von", "from a person, building, surface", "vom Bahnhof, von Anna"],
            ["von", "coming from a place", "von der Arbeit"],
          ],
        },
        {
          type: "example",
          de: "Ich komme aus Deutschland, aus Berlin. Jetzt komme ich vom Bahnhof und gehe nach Hause.",
          en: "I come from Germany, from Berlin. Now I'm coming from the station and going home.",
        },
        {
          type: "tip",
          text: "The pair test: aus for origin in a place, von for departure from a point. Woher kommst du? Aus Berlin. Woher kommst du gerade? Vom Bahnhof.",
        },
      ],
    },
    {
      heading: "Wo: die Position",
      blocks: [
        {
          type: "paragraph",
          text: "The Wo answers use in, an, auf and bei with the dative: in der Stadt (in the city), an der Ampel (at the light), auf dem Markt (at the market), bei der Oma (at grandma's). The contractions: im, am, beim. The question pair: Wo bist du? and Wo wohnst du?.",
        },
        {
          type: "table",
          caption: "Wo answers",
          head: ["Preposition", "Example", "Meaning"],
          rows: [
            ["in", "in der Stadt", "in the city"],
            ["an", "an der Ampel", "at the traffic light"],
            ["auf", "auf dem Markt", "at the market"],
            ["bei", "bei der Oma", "at grandma's"],
          ],
        },
        {
          type: "example",
          de: "Ich bin in der Stadt, auf dem Markt. Am Abend bin ich bei meiner Oma.",
          en: "I am in town, at the market. In the evening I am at my grandma's.",
        },
        {
          type: "tip",
          text: "Wo is the position: in der Stadt, auf dem Markt, bei der Oma. The three contractions: im, am, beim.",
        },
      ],
    },
    {
      heading: "Wohin: die Richtung",
      blocks: [
        {
          type: "paragraph",
          text: "The Wohin answers use in, an, auf and nach with the accusative: in die Stadt (into the city), ans Fenster (to the window), auf den Markt (onto the market), nach Hause (home). The contractions: ins, ans, aufs. The question: Wohin gehst du? Ich gehe in die Stadt.",
        },
        {
          type: "table",
          caption: "Wohin answers",
          head: ["Preposition", "Example", "Meaning"],
          rows: [
            ["in", "in die Stadt", "into the city"],
            ["an", "ans Fenster", "to the window"],
            ["auf", "auf den Markt", "onto the market"],
            ["nach", "nach Hause", "home"],
          ],
        },
        {
          type: "example",
          de: "Wohin gehst du? Ich gehe in die Stadt, auf den Markt, und dann nach Hause.",
          en: "Where are you going? I'm going into town, to the market, and then home.",
        },
        {
          type: "tip",
          text: "The direction pair test: Wo (dative) becomes Wohin (accusative): in der Stadt → in die Stadt, auf dem Markt → auf den Markt.",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: mixing aus and von, mixing wo and wohin, and forgetting the article contractions.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["aus/von mix", "Ich komme von Deutschland.", "Ich komme aus Deutschland.", "countries take aus"],
            ["wo/wohin mix", "Wohin bist du?", "Wo bist du?", "position takes wo"],
            ["dative after wohin", "Ich gehe in der Stadt.", "Ich gehe in die Stadt.", "direction takes the accusative"],
            ["missing nach Hause", "Ich gehe zu Hause.", "Ich gehe nach Hause.", "home direction takes nach"],
            ["contraction loss", "Ich bin in dem Büro.", "Ich bin im Büro.", "in + dem = im"],
          ],
        },
        {
          type: "tip",
          text: "The whole system in three lines: Wo (dative position), Woher (aus/von origin), Wohin (accusative direction). Ask the three questions and the prepositions answer themselves.",
        },
      ],
    },
  ],
  vocab: [
    { id: "wo", de: "Wo bist du?", en: "Where are you?", part: "phrase", phrase: true, audio: true },
    { id: "woher", de: "Woher kommst du?", en: "Where are you from?", part: "phrase", phrase: true, audio: true },
    { id: "wohin", de: "Wohin gehst du?", en: "Where are you going?", part: "phrase", phrase: true, audio: true },
    { id: "ich-komme-aus-berlin", de: "Ich komme aus Berlin.", en: "I am from Berlin.", part: "phrase", phrase: true, audio: true },
    { id: "ich-binne-in-der-stadt", de: "Ich bin in der Stadt.", en: "I am in the city.", part: "phrase", phrase: true, audio: true },
    { id: "ich-gehe-in-die-stadt", de: "Ich gehe in die Stadt.", en: "I am going into the city.", part: "phrase", phrase: true, audio: true },
    { id: "nach-hause", de: "nach Hause", en: "home (direction)", part: "phrase", phrase: true, audio: true },
    { id: "aus-deutschland", de: "aus Deutschland", en: "from Germany", part: "phrase", phrase: true, audio: true },
    { id: "vom-bahnhof", de: "vom Bahnhof", en: "from the station", part: "phrase", phrase: true, audio: true },
    { id: "aus-der-kueche", de: "aus der Küche", en: "out of the kitchen", part: "phrase", phrase: true, audio: true },
    { id: "auf-dem-markt", de: "auf dem Markt", en: "at the market", part: "phrase", phrase: true, audio: true },
    { id: "auf-den-markt", de: "auf den Markt", en: "onto the market", part: "phrase", phrase: true, audio: true },
    { id: "bei-der-oma", de: "bei der Oma", en: "at grandma's", part: "phrase", phrase: true, audio: true },
    { id: "an-der-ampel", de: "an der Ampel", en: "at the traffic light", part: "phrase", phrase: true, audio: true },
    { id: "in-der-schule", de: "in der Schule", en: "at school", part: "phrase", phrase: true, audio: true },
    { id: "in-die-schule", de: "in die Schule", en: "to school", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-drei",
      type: "matching",
      title: "Übung 1: Die drei Fragen",
      instruction: "Match each question to its use.",
      pairs: [
        ["Wo?", "position (dative)"],
        ["Woher?", "origin (aus/von)"],
        ["Wohin?", "direction (accusative)"],
      ],
    },
    {
      id: "ex-wo",
      type: "multiple-choice",
      title: "Übung 2: Wo?",
      instruction: "Choose the Wo answer.",
      prompt: "Wo bist du?",
      options: ["Ich bin in der Stadt.", "Ich gehe in die Stadt.", "Ich komme aus der Stadt."],
      correctIndex: 0,
      explain: "Wo takes the dative position.",
    },
    {
      id: "ex-wohin",
      type: "multiple-choice",
      title: "Übung 3: Wohin?",
      instruction: "Choose the Wohin answer.",
      prompt: "Wohin gehst du?",
      options: ["Ich gehe in die Stadt.", "Ich bin in der Stadt.", "Ich komme aus der Stadt."],
      correctIndex: 0,
      explain: "Direction takes the accusative.",
    },
    {
      id: "ex-woher",
      type: "multiple-choice",
      title: "Übung 4: Woher?",
      instruction: "Choose the Woher answer.",
      prompt: "Woher kommst du?",
      options: ["Ich komme aus Berlin.", "Ich gehe nach Berlin.", "Ich bin in Berlin."],
      correctIndex: 0,
      explain: "Origin takes aus.",
    },
    {
      id: "ex-aus-von",
      type: "multiple-choice",
      title: "Übung 5: aus oder von",
      instruction: "Choose the correct preposition.",
      prompt: "Ich komme ___ der Küche.",
      options: ["aus", "von", "nach"],
      correctIndex: 0,
      explain: "Out of a room takes aus.",
    },
    {
      id: "ex-aus-von-2",
      type: "multiple-choice",
      title: "Übung 6: aus oder von",
      instruction: "Choose the correct preposition.",
      prompt: "Ich komme gerade ___ Bahnhof.",
      options: ["vom", "aus", "nach"],
      correctIndex: 0,
      explain: "Departure from a building takes von: vom Bahnhof.",
    },
    {
      id: "ex-nach-hause",
      type: "multiple-choice",
      title: "Übung 7: nach Hause",
      instruction: "Choose the correct phrase.",
      prompt: "I am going home.",
      options: ["Ich gehe nach Hause.", "Ich gehe zu Hause.", "Ich gehe in Hause."],
      correctIndex: 0,
      explain: "Home direction takes nach Hause.",
    },
    {
      id: "ex-im",
      type: "multiple-choice",
      title: "Übung 8: im",
      instruction: "Choose the correct phrase.",
      prompt: "I am at the office.",
      options: ["im Büro", "in das Büro", "am Büro"],
      correctIndex: 0,
      explain: "Position in the office: im Büro.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 9: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Ich komme aus Berlin.",
      options: ["Ich komme aus Berlin.", "Ich komme aus Deutschland.", "Ich bin aus Berlin."],
      correctIndex: 0,
      explain: "The origin sentence heard.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 10: Hören",
      instruction: "Play the audio and pick the question you heard.",
      prompt: "Wohin gehst du?",
      options: ["Wohin gehst du?", "Wo bist du?", "Woher kommst du?"],
      correctIndex: 0,
      explain: "The direction question heard.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 11: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Ich gehe in die Schule.", "Ich gehe in der Schule.", "Ich gehe in dem Schule."],
      correctIndex: 0,
      explain: "Direction takes the accusative.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 12: Der Satz",
      instruction: "Build the sentence: I am from Germany.",
      chunks: ["Ich", "komme", "aus", "Deutschland."], translation: "I come from Germany.",
      explain: "Origin takes aus.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 13: Der Satz",
      instruction: "Build the sentence: I am going home.",
      chunks: ["Ich", "gehe", "nach", "Hause."], translation: "I am going home.",
      explain: "The home direction: nach Hause.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 14: Ortskarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "Wo bist du?", back: "Where are you?", frontAudio: true },
        { front: "Woher kommst du?", back: "Where are you from?", frontAudio: true },
        { front: "Wohin gehst du?", back: "Where are you going?", frontAudio: true },
        { front: "Ich komme aus Berlin.", back: "I am from Berlin.", frontAudio: true },
        { front: "Ich bin in der Stadt.", back: "I am in the city.", frontAudio: true },
        { front: "Ich gehe in die Stadt.", back: "I am going into the city.", frontAudio: true },
        { front: "nach Hause", back: "home (direction)", frontAudio: true },
        { front: "aus Deutschland", back: "from Germany", frontAudio: true },
        { front: "auf dem Markt", back: "at the market", frontAudio: true },
        { front: "bei der Oma", back: "at grandma's", frontAudio: true },
        { front: "an der Ampel", back: "at the traffic light", frontAudio: true },
        { front: "im Büro", back: "at the office", frontAudio: true },
      ],
    },
  ],
};

export const oeffentlicheVerkehrsmittel: Lesson = {
  id: "oeffentliche-verkehrsmittel",
  title: "Öffentliche Verkehrsmittel",
  summary:
    "The complete public transport system for A1: the vehicles, the tickets, the questions at the ticket office, and the platform announcements.",
  status: "ready",
  sections: [
    {
      heading: "Die Verkehrsmittel",
      blocks: [
        {
          type: "paragraph",
          text: "The public transport (die öffentlichen Verkehrsmittel) runs on: die U-Bahn (underground), die S-Bahn (suburban train), die Straßenbahn (tram), der Bus (bus), der Zug (train), and das Flugzeug (plane). The question: Wie komme ich zum Flughafen? (How do I get to the airport?).",
        },
        {
          type: "table",
          caption: "The transport",
          head: ["German", "English", "Plural"],
          rows: [
            ["die U-Bahn", "the underground", "die U-Bahnen"],
            ["die S-Bahn", "the suburban train", "die S-Bahnen"],
            ["die Straßenbahn", "the tram", "die Straßenbahnen"],
            ["der Bus", "the bus", "die Busse"],
            ["der Zug", "the train", "die Züge"],
            ["das Flugzeug", "the plane", "die Flugzeuge"],
            ["das Taxi", "the taxi", "die Taxis"],
            ["das Fahrrad", "the bicycle", "die Fahrräder"],
          ],
        },
        {
          type: "example",
          de: "Ich fahre mit der U-Bahn zur Arbeit. Am Wochenende nehme ich den Zug nach Hamburg.",
          en: "I take the underground to work. At the weekend I take the train to Hamburg.",
        },
        {
          type: "tip",
          text: "Travelling by a vehicle takes mit + article: mit der U-Bahn, mit dem Bus, mit dem Zug. The vehicle words: die Bahn (f.), der Bus (m.), der Zug (m.).",
        },
      ],
    },
    {
      heading: "Das Ticket kaufen",
      blocks: [
        {
          type: "paragraph",
          text: "Buying a ticket (das Ticket, die Fahrkarte) runs on the script: Ich hätte gern eine Fahrkarte (I would like a ticket), the questions: Einfach oder hin und zurück? (Single or return?), Erste oder zweite Klasse? (First or second class?), and the price. The machine: der Fahrscheinautomat (ticket machine).",
        },
        {
          type: "table",
          caption: "The ticket script",
          head: ["German", "English"],
          rows: [
            ["Ich hätte gern eine Fahrkarte.", "I would like a ticket."],
            ["Einfach oder hin und zurück?", "Single or return?"],
            ["Eine Fahrkarte nach Berlin, bitte.", "A ticket to Berlin, please."],
            ["Was kostet die Fahrkarte?", "How much is the ticket?"],
            ["Erste oder zweite Klasse?", "First or second class?"],
            ["Der Fahrscheinautomat ist dort.", "The ticket machine is over there."],
          ],
        },
        {
          type: "example",
          de: "Ich hätte gern eine Fahrkarte nach Berlin. Einfach oder hin und zurück? Einfach, bitte. Das macht 29 Euro.",
          en: "I'd like a ticket to Berlin. Single or return? Single, please. That makes 29 euros.",
        },
        {
          type: "tip",
          text: "The ticket pair: Einfach (single) and hin und zurück (return). The ticket words: die Fahrkarte, das Ticket, der Fahrschein.",
        },
      ],
    },
    {
      heading: "Die Fragen am Bahnhof",
      blocks: [
        {
          type: "paragraph",
          text: "The station questions: Von welchem Gleis fährt der Zug ab? (From which platform does the train leave?), Wann kommt der Zug an? (When does the train arrive?), Wie lange dauert die Fahrt? (How long does the journey take?). The platform: das Gleis, the arrival: die Ankunft, the departure: die Abfahrt.",
        },
        {
          type: "table",
          caption: "The station questions",
          head: ["German", "English"],
          rows: [
            ["Von welchem Gleis fährt der Zug ab?", "From which platform does the train leave?"],
            ["Gleis 5.", "Platform 5."],
            ["Wann kommt der Zug in Hamburg an?", "When does the train arrive in Hamburg?"],
            ["Wie lange dauert die Fahrt?", "How long does the journey take?"],
            ["Der Zug hat Verspätung.", "The train is delayed."],
            ["Ankunft um 10 Uhr.", "Arrival at 10 o'clock."],
          ],
        },
        {
          type: "example",
          de: "Entschuldigung, von welchem Gleis fährt der Zug nach Hamburg ab? Gleis 5. Wann kommt er an? Um 10 Uhr.",
          en: "Excuse me, which platform does the train to Hamburg leave from? Platform 5. When does it arrive? At 10 o'clock.",
        },
        {
          type: "tip",
          text: "The station words: das Gleis (platform), die Ankunft (arrival), die Abfahrt (departure), die Verspätung (delay). The verb pair: abfahren and ankommen.",
        },
      ],
    },
    {
      heading: "Im Flugzeug",
      blocks: [
        {
          type: "paragraph",
          text: "The plane has its own words: der Flughafen (airport), der Flug (flight), das Flugzeug (plane), das Gepäck (luggage), die Sicherheitskontrolle (security check), die Bordkarte (boarding card). The phrase: Wo ist die Sicherheitskontrolle? (Where is the security check?).",
        },
        {
          type: "table",
          caption: "The plane",
          head: ["German", "English"],
          rows: [
            ["der Flughafen", "the airport"],
            ["der Flug", "the flight"],
            ["das Gepäck", "the luggage"],
            ["die Bordkarte", "the boarding card"],
            ["die Sicherheitskontrolle", "the security check"],
            ["das Gate", "the gate"],
          ],
        },
        {
          type: "example",
          de: "Wir fliegen morgen nach Spanien. Am Flughafen gehen wir zuerst zur Sicherheitskontrolle, dann zum Gate.",
          en: "We fly to Spain tomorrow. At the airport we first go to security control, then to the gate.",
        },
        {
          type: "tip",
          text: "The airport pair: der Flughafen and das Flugzeug, der Flug. The verb fliegen (to fly): Wir fliegen nach Spanien.",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: wrong mit, mixing the vehicles, and forgetting the verb pair abfahren/ankommen.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["missing mit", "Ich fahre der U-Bahn.", "Ich fahre mit der U-Bahn.", "travelling takes mit"],
            ["vehicle mix", "Ich fliege mit dem Zug.", "Ich fahre mit dem Zug.", "planes fly, trains go"],
            ["abfahren split", "Wann abfährt der Zug?", "Wann fährt der Zug ab?", "abfahren is separable"],
            ["wrong ticket word", "das Fahrkarte", "die Fahrkarte", "Fahrkarte is feminine"],
            ["direction mix", "Ich fahre nach Spanien, nicht nach Spanien.", "Ich fahre nach Spanien.", "countries take nach"],
          ],
        },
        {
          type: "tip",
          text: "The transport topic is a script: the vehicle (mit der U-Bahn), the ticket (eine Fahrkarte), the platform (Gleis 5), and the arrival (Ankunft).",
        },
      ],
    },
  ],
  vocab: [
    { id: "die-ubahn", de: "die U-Bahn", en: "the underground", part: "noun f.", plural: "die U-Bahnen", audio: true },
    { id: "die-sbahn", de: "die S-Bahn", en: "the suburban train", part: "noun f.", plural: "die S-Bahnen", audio: true },
    { id: "die-strassenbahn", de: "die Straßenbahn", en: "the tram", part: "noun f.", plural: "die Straßenbahnen", audio: true },
    { id: "der-bus", de: "der Bus", en: "the bus", part: "noun m.", plural: "die Busse", audio: true },
    { id: "der-zug", de: "der Zug", en: "the train", part: "noun m.", plural: "die Züge", audio: true },
    { id: "das-flugzeug", de: "das Flugzeug", en: "the plane", part: "noun n.", plural: "die Flugzeuge", audio: true },
    { id: "das-taxi", de: "das Taxi", en: "the taxi", part: "noun n.", plural: "die Taxis", audio: true },
    { id: "das-fahrrad", de: "das Fahrrad", en: "the bicycle", part: "noun n.", plural: "die Fahrräder", audio: true },
    { id: "das-ticket", de: "das Ticket", en: "the ticket", part: "noun n.", plural: "die Tickets", audio: true },
    { id: "die-fahrkarte", de: "die Fahrkarte", en: "the ticket", part: "noun f.", plural: "die Fahrkarten", audio: true },
    { id: "der-fahrschein", de: "der Fahrschein", en: "the ticket", part: "noun m.", plural: "die Fahrscheine", audio: true },
    { id: "der-fahrkartenautomat", de: "der Fahrkartenautomat", en: "the ticket machine", part: "noun m.", plural: "die Fahrkartenautomaten", audio: true },
    { id: "das-gleis", de: "das Gleis", en: "the platform", part: "noun n.", plural: "die Gleise", audio: true },
    { id: "die-ankunft", de: "die Ankunft", en: "the arrival", part: "noun f.", plural: "die Ankünfte", audio: true },
    { id: "die-abfahrt", de: "die Abfahrt", en: "the departure", part: "noun f.", plural: "die Abfahrten", audio: true },
    { id: "die-verspaetung", de: "die Verspätung", en: "the delay", part: "noun f.", plural: "die Verspätungen", audio: true },
    { id: "abfahren", de: "abfahren", en: "to depart", part: "verb", audio: true },
    { id: "ankommen", de: "ankommen", en: "to arrive", part: "verb", audio: true },
    { id: "der-flughafen", de: "der Flughafen", en: "the airport", part: "noun m.", plural: "die Flughäfen", audio: true },
    { id: "das-gepaeck", de: "das Gepäck", en: "the luggage", part: "noun n.", audio: true },
    { id: "die-bordkarte", de: "die Bordkarte", en: "the boarding card", part: "noun f.", plural: "die Bordkarten", audio: true },
    { id: "mit-der-ubahn", de: "mit der U-Bahn", en: "by underground", part: "phrase", phrase: true, audio: true },
    { id: "mit-dem-zug", de: "mit dem Zug", en: "by train", part: "phrase", phrase: true, audio: true },
    { id: "eine-fahrkarte-nach-berlin", de: "Eine Fahrkarte nach Berlin, bitte.", en: "A ticket to Berlin, please.", part: "phrase", phrase: true, audio: true },
    { id: "einfach-oder-hin-und-zurueck", de: "Einfach oder hin und zurück?", en: "Single or return?", part: "phrase", phrase: true, audio: true },
    { id: "von-welchem-gleis", de: "Von welchem Gleis fährt der Zug ab?", en: "From which platform does the train leave?", part: "phrase", phrase: true, audio: true },
    { id: "gleis-fuenf", de: "Gleis 5.", en: "Platform 5.", part: "phrase", phrase: true, audio: true },
    { id: "wann-kommt-der-zug-an", de: "Wann kommt der Zug an?", en: "When does the train arrive?", part: "phrase", phrase: true, audio: true },
    { id: "der-zug-hat-verspaetung", de: "Der Zug hat Verspätung.", en: "The train is delayed.", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-fahrzeuge",
      type: "matching",
      title: "Übung 1: Die Fahrzeuge",
      instruction: "Match each vehicle to its meaning.",
      pairs: [
        ["die U-Bahn", "the underground"],
        ["die Straßenbahn", "the tram"],
        ["der Bus", "the bus"],
        ["der Zug", "the train"],
        ["das Flugzeug", "the plane"],
        ["das Fahrrad", "the bicycle"],
      ],
    },
    {
      id: "ex-mit",
      type: "multiple-choice",
      title: "Übung 2: mit",
      instruction: "Choose the correct phrase.",
      prompt: "I travel by train.",
      options: ["mit dem Zug", "auf dem Zug", "in den Zug"],
      correctIndex: 0,
      explain: "Travelling takes mit.",
    },
    {
      id: "ex-ticket",
      type: "multiple-choice",
      title: "Übung 3: Die Fahrkarte",
      instruction: "Choose the ticket phrase.",
      prompt: "You want a ticket to Berlin.",
      options: ["Eine Fahrkarte nach Berlin, bitte.", "Eine Fahrkarte zu Berlin, bitte.", "Ein Ticket in Berlin, bitte."],
      correctIndex: 0,
      explain: "Destinations take nach.",
    },
    {
      id: "ex-einfach",
      type: "multiple-choice",
      title: "Übung 4: Einfach oder zurück?",
      instruction: "Choose the ticket question.",
      prompt: "The clerk asks single or return.",
      options: ["Einfach oder hin und zurück?", "Ein oder zwei Fahrkarten?", "Heute oder morgen?"],
      correctIndex: 0,
      explain: "The single/return question.",
    },
    {
      id: "ex-gleis",
      type: "multiple-choice",
      title: "Übung 5: Das Gleis",
      instruction: "Choose the platform question.",
      prompt: "You ask which platform the train leaves from.",
      options: ["Von welchem Gleis fährt der Zug ab?", "Wann fährt der Zug an?", "Wo ist der Zug?"],
      correctIndex: 0,
      explain: "The platform question: von welchem Gleis.",
    },
    {
      id: "ex-ab",
      type: "multiple-choice",
      title: "Übung 6: abfahren",
      instruction: "Choose the correct sentence.",
      prompt: "The train leaves from platform 5.",
      options: ["Der Zug fährt von Gleis 5 ab.", "Der Zug abfährt von Gleis 5.", "Der Zug fährt ab von Gleis 5."],
      correctIndex: 0,
      explain: "abfahren is separable.",
    },
    {
      id: "ex-ankommen",
      type: "multiple-choice",
      title: "Übung 7: ankommen",
      instruction: "Choose the correct sentence.",
      prompt: "The train arrives at 10 o'clock.",
      options: ["Der Zug kommt um 10 Uhr an.", "Der Zug ankommt um 10 Uhr.", "Der Zug kommt um 10 Uhr."],
      correctIndex: 0,
      explain: "ankommen is separable.",
    },
    {
      id: "ex-verspaetung",
      type: "multiple-choice",
      title: "Übung 8: Die Verspätung",
      instruction: "Choose the delay sentence.",
      prompt: "The train is delayed.",
      options: ["Der Zug hat Verspätung.", "Der Zug ist Verspätung.", "Der Zug macht Verspätung."],
      correctIndex: 0,
      explain: "The delay phrase: Verspätung haben.",
    },
    {
      id: "ex-flughafen",
      type: "multiple-choice",
      title: "Übung 9: Der Flughafen",
      instruction: "Choose the airport question.",
      prompt: "You ask where the security check is.",
      options: ["Wo ist die Sicherheitskontrolle?", "Wo ist die Bordkarte?", "Wo ist das Gepäck?"],
      correctIndex: 0,
      explain: "The security check question.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 10: Hören",
      instruction: "Play the audio and pick the vehicle you heard.",
      prompt: "die U-Bahn",
      options: ["die U-Bahn", "die S-Bahn", "die Straßenbahn"],
      correctIndex: 0,
      explain: "The vehicle heard: underground.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 11: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Der Zug hat Verspätung.",
      options: ["Der Zug hat Verspätung.", "Der Zug kommt pünktlich.", "Der Zug hat Abfahrt."],
      correctIndex: 0,
      explain: "The delay sentence heard.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 12: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Ich fahre mit der U-Bahn.", "Ich fahre der U-Bahn.", "Ich fahre in der U-Bahn."],
      correctIndex: 0,
      explain: "Travelling takes mit.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 13: Der Satz",
      instruction: "Build the sentence: I travel by train.",
      chunks: ["Ich", "fahre", "mit", "dem", "Zug."], translation: "I am travelling by train.",
      explain: "Travelling with mit.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 14: Der Satz",
      instruction: "Build the sentence: The train leaves from platform 5.",
      chunks: ["Der", "Zug", "fährt", "von", "Gleis", "5", "ab."], translation: "The train departs from platform 5.",
      explain: "The separable departure verb.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 15: Verkehrskarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "mit der U-Bahn", back: "by underground", frontAudio: true },
        { front: "mit dem Zug", back: "by train", frontAudio: true },
        { front: "Eine Fahrkarte nach Berlin, bitte.", back: "A ticket to Berlin, please.", frontAudio: true },
        { front: "Einfach oder hin und zurück?", back: "Single or return?", frontAudio: true },
        { front: "Von welchem Gleis fährt der Zug ab?", back: "From which platform does the train leave?", frontAudio: true },
        { front: "Gleis 5.", back: "Platform 5.", frontAudio: true },
        { front: "Wann kommt der Zug an?", back: "When does the train arrive?", frontAudio: true },
        { front: "Der Zug hat Verspätung.", back: "The train is delayed.", frontAudio: true },
        { front: "die U-Bahn", back: "the underground", frontAudio: true },
        { front: "das Gleis", back: "the platform", frontAudio: true },
        { front: "der Flughafen", back: "the airport", frontAudio: true },
        { front: "das Gepäck", back: "the luggage", frontAudio: true },
      ],
    },
  ],
};

export const dasWetter: Lesson = {
  id: "das-wetter",
  title: "Das Wetter",
  summary:
    "The complete weather system for A1: the weather verbs, the adjectives, the seasons, and the temperature in German.",
  status: "ready",
  sections: [
    {
      heading: "Das Wetter: die Grundfragen",
      blocks: [
        {
          type: "paragraph",
          text: "The weather (das Wetter) runs on one fixed question: Wie ist das Wetter? (How is the weather?). The answer uses the es-verbs: Es ist schön (It is nice), Es regnet (It is raining), Es schneit (It is snowing), Es ist kalt (It is cold). The weather is always es in German.",
        },
        {
          type: "table",
          caption: "The weather basics",
          head: ["German", "English"],
          rows: [
            ["Wie ist das Wetter?", "How is the weather?"],
            ["Es ist schön.", "It is nice."],
            ["Es ist schlecht.", "It is bad."],
            ["Es regnet.", "It is raining."],
            ["Es schneit.", "It is snowing."],
            ["Es ist kalt.", "It is cold."],
            ["Es ist warm.", "It is warm."],
          ],
        },
        {
          type: "example",
          de: "Wie ist das Wetter heute? Es ist schön und warm. Die Sonne scheint.",
          en: "What is the weather like today? It is nice and warm. The sun is shining.",
        },
        {
          type: "tip",
          text: "The weather is always es: Es regnet, Es schneit, Es ist kalt. The three weather verbs: regnen, schneien, scheinen.",
        },
      ],
    },
    {
      heading: "Die Wetterverben",
      blocks: [
        {
          type: "paragraph",
          text: "Three verbs carry the weather: regnen (to rain), schneien (to snow), scheinen (to shine, of the sun). The pairs: die Sonne scheint (the sun shines), es regnet (it rains), es schneit (it snows). The noun forms: der Regen (rain), der Schnee (snow), die Sonne (sun), der Wind (wind), die Wolke (cloud).",
        },
        {
          type: "table",
          caption: "The weather verbs and nouns",
          head: ["Verb", "Noun", "English"],
          rows: [
            ["regnen", "der Regen", "rain"],
            ["schneien", "der Schnee", "snow"],
            ["scheinen", "die Sonne", "sun"],
            ["wehen", "der Wind", "wind"],
            ["-", "die Wolke", "cloud"],
            ["-", "der Himmel", "sky"],
          ],
        },
        {
          type: "example",
          de: "Heute regnet es, aber morgen scheint die Sonne. Der Wind weht stark.",
          en: "Today it is raining, but tomorrow the sun is shining. The wind is blowing strongly.",
        },
        {
          type: "tip",
          text: "The pair test: the verb forms the sentence (Es regnet), the noun names the phenomenon (der Regen).",
        },
      ],
    },
    {
      heading: "Die Jahreszeiten",
      blocks: [
        {
          type: "paragraph",
          text: "The four seasons (die Jahreszeiten): der Frühling (spring), der Sommer (summer), der Herbst (autumn), der Winter (winter). The preposition: im Frühling, im Sommer, im Herbst, im Winter. The classic question: Welche Jahreszeit magst du? (Which season do you like?).",
        },
        {
          type: "table",
          caption: "The seasons",
          head: ["Season", "German", "Typical weather"],
          rows: [
            ["spring", "der Frühling", "warm, die Blumen blühen"],
            ["summer", "der Sommer", "heiß, die Sonne scheint"],
            ["autumn", "der Herbst", "kühl, es regnet"],
            ["winter", "der Winter", "kalt, es schneit"],
          ],
        },
        {
          type: "example",
          de: "Im Sommer scheint die Sonne und es ist heiß. Im Winter schneit es und es ist kalt.",
          en: "In summer the sun shines and it is hot. In winter it snows and it is cold.",
        },
        {
          type: "tip",
          text: "The seasons take im: im Frühling, im Sommer, im Herbst, im Winter. The temperature pair: es ist heiß (hot) and es ist kalt (cold).",
        },
      ],
    },
    {
      heading: "Die Temperatur",
      blocks: [
        {
          type: "paragraph",
          text: "The temperature (die Temperatur) is measured in Grad: Es ist 20 Grad (It is 20 degrees). The questions: Wie viel Grad ist es? (How many degrees is it?) and the range words: über 20 Grad (above 20), unter 10 Grad (below 10), minus 5 Grad (minus 5).",
        },
        {
          type: "table",
          caption: "The temperature",
          head: ["German", "English"],
          rows: [
            ["Wie viel Grad ist es?", "How many degrees is it?"],
            ["Es ist 20 Grad.", "It is 20 degrees."],
            ["über 20 Grad", "above 20 degrees"],
            ["unter 10 Grad", "below 10 degrees"],
            ["minus 5 Grad", "minus 5 degrees"],
            ["Es ist kalt / warm / heiß.", "It is cold / warm / hot."],
          ],
        },
        {
          type: "example",
          de: "Es ist heute sehr heiß, über 30 Grad. Morgen wird es kühler, unter 20 Grad.",
          en: "It is very hot today, over 30 degrees. Tomorrow it will be cooler, under 20 degrees.",
        },
        {
          type: "tip",
          text: "The temperature phrase: Es ist + number + Grad. The scale: kalt (cold), kühl (cool), warm (warm), heiß (hot).",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: using the noun instead of the verb, forgetting es, and confusing the seasons.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["noun instead of verb", "Es ist Regen.", "Es regnet.", "the verb carries the weather"],
            ["missing es", "Regnet heute.", "Es regnet heute.", "the weather is always es"],
            ["season preposition", "in Sommer", "im Sommer", "seasons take im"],
            ["hot/cold mix", "Es ist heiß im Winter.", "Es ist kalt im Winter.", "winter is cold"],
            ["weather article", "das Wetter, der Regen", "das Wetter, der Regen", "learn the genders"],
          ],
        },
        {
          type: "tip",
          text: "The weather topic is a script: Wie ist das Wetter? Es ist/regnet/schneit + the season (im Sommer) + the temperature (20 Grad).",
        },
      ],
    },
  ],
  vocab: [
    { id: "das-wetter", de: "das Wetter", en: "the weather", part: "noun n.", audio: true },
    { id: "die-sonne", de: "die Sonne", en: "the sun", part: "noun f.", plural: "die Sonnen", audio: true },
    { id: "der-regen", de: "der Regen", en: "the rain", part: "noun m.", audio: true },
    { id: "der-schnee", de: "der Schnee", en: "the snow", part: "noun m.", audio: true },
    { id: "der-wind", de: "der Wind", en: "the wind", part: "noun m.", plural: "die Winde", audio: true },
    { id: "die-wolke", de: "die Wolke", en: "the cloud", part: "noun f.", plural: "die Wolken", audio: true },
    { id: "der-himmel", de: "der Himmel", en: "the sky", part: "noun m.", plural: "die Himmel", audio: true },
    { id: "regnen", de: "regnen", en: "to rain", part: "verb", audio: true },
    { id: "schneien", de: "schneien", en: "to snow", part: "verb", audio: true },
    { id: "scheinen", de: "scheinen", en: "to shine", part: "verb", audio: true },
    { id: "wehen", de: "wehen", en: "to blow (wind)", part: "verb", audio: true },
    { id: "heiss", de: "heiß", en: "hot", part: "adjective", audio: true },
    { id: "warm", de: "warm", en: "warm", part: "adjective", audio: true },
    { id: "kuehl", de: "kühl", en: "cool", part: "adjective", audio: true },
    { id: "kalt", de: "kalt", en: "cold", part: "adjective", audio: true },
    { id: "der-fruehling", de: "der Frühling", en: "the spring", part: "noun m.", plural: "die Frühlinge", audio: true },
    { id: "der-sommer", de: "der Sommer", en: "the summer", part: "noun m.", plural: "die Sommer", audio: true },
    { id: "der-herbst", de: "der Herbst", en: "the autumn", part: "noun m.", plural: "die Herbste", audio: true },
    { id: "der-winter", de: "der Winter", en: "the winter", part: "noun m.", plural: "die Winter", audio: true },
    { id: "wie-ist-das-wetter", de: "Wie ist das Wetter?", en: "How is the weather?", part: "phrase", phrase: true, audio: true },
    { id: "es-ist-schoen", de: "Es ist schön.", en: "It is nice.", part: "phrase", phrase: true, audio: true },
    { id: "es-regnet", de: "Es regnet.", en: "It is raining.", part: "phrase", phrase: true, audio: true },
    { id: "es-schneit", de: "Es schneit.", en: "It is snowing.", part: "phrase", phrase: true, audio: true },
    { id: "die-sonne-scheint", de: "Die Sonne scheint.", en: "The sun is shining.", part: "phrase", phrase: true, audio: true },
    { id: "es-ist-20-grad", de: "Es ist 20 Grad.", en: "It is 20 degrees.", part: "phrase", phrase: true, audio: true },
    { id: "im-sommer", de: "im Sommer", en: "in summer", part: "phrase", phrase: true, audio: true },
    { id: "im-winter", de: "im Winter", en: "in winter", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-basics",
      type: "matching",
      title: "Übung 1: Das Wetter",
      instruction: "Match each weather sentence to its meaning.",
      pairs: [
        ["Es ist schön.", "It is nice."],
        ["Es regnet.", "It is raining."],
        ["Es schneit.", "It is snowing."],
        ["Es ist kalt.", "It is cold."],
        ["Die Sonne scheint.", "The sun is shining."],
        ["Der Wind weht.", "The wind is blowing."],
      ],
    },
    {
      id: "ex-frage",
      type: "multiple-choice",
      title: "Übung 2: Die Wetterfrage",
      instruction: "Choose the weather question.",
      prompt: "You ask how the weather is.",
      options: ["Wie ist das Wetter?", "Was ist das Wetter?", "Wo ist das Wetter?"],
      correctIndex: 0,
      explain: "The weather question: Wie ist das Wetter?",
    },
    {
      id: "ex-verb",
      type: "multiple-choice",
      title: "Übung 3: Das Wetterverb",
      instruction: "Choose the correct sentence.",
      prompt: "It is raining.",
      options: ["Es regnet.", "Es ist Regen.", "Es ist regnen."],
      correctIndex: 0,
      explain: "The verb carries the weather.",
    },
    {
      id: "ex-es",
      type: "multiple-choice",
      title: "Übung 4: es",
      instruction: "Choose the correct sentence.",
      prompt: "It is snowing today.",
      options: ["Es schneit heute.", "Schneit heute.", "Heute ist Schnee."],
      correctIndex: 0,
      explain: "The weather is always es.",
    },
    {
      id: "ex-jahreszeit",
      type: "matching",
      title: "Übung 5: Die Jahreszeiten",
      instruction: "Match each season to its German name.",
      pairs: [
        ["spring", "der Frühling"],
        ["summer", "der Sommer"],
        ["autumn", "der Herbst"],
        ["winter", "der Winter"],
      ],
    },
    {
      id: "ex-sommer",
      type: "multiple-choice",
      title: "Übung 6: Der Sommer",
      instruction: "Choose the correct phrase.",
      prompt: "In summer it is hot.",
      options: ["Im Sommer ist es heiß.", "Am Sommer ist es heiß.", "In Sommer ist es heiß."],
      correctIndex: 0,
      explain: "Seasons take im.",
    },
    {
      id: "ex-temperatur",
      type: "multiple-choice",
      title: "Übung 7: Die Temperatur",
      instruction: "Choose the temperature question.",
      prompt: "You ask how many degrees it is.",
      options: ["Wie viel Grad ist es?", "Wie ist die Temperatur Grad?", "Was Grad ist es?"],
      correctIndex: 0,
      explain: "The degree question: Wie viel Grad?",
    },
    {
      id: "ex-grad",
      type: "multiple-choice",
      title: "Übung 8: Die Grad",
      instruction: "Choose the temperature answer.",
      prompt: "It is 20 degrees.",
      options: ["Es ist 20 Grad.", "Es ist 20 Grade.", "Es hat 20 Grad."],
      correctIndex: 0,
      explain: "The temperature: Es ist 20 Grad.",
    },
    {
      id: "ex-sonne",
      type: "multiple-choice",
      title: "Übung 9: Die Sonne",
      instruction: "Choose the correct sentence.",
      prompt: "The sun is shining.",
      options: ["Die Sonne scheint.", "Die Sonne regnet.", "Die Sonne weht."],
      correctIndex: 0,
      explain: "The sun shines: scheinen.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 10: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Es regnet.",
      options: ["Es regnet.", "Es schneit.", "Die Sonne scheint."],
      correctIndex: 0,
      explain: "The weather heard: raining.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 11: Hören",
      instruction: "Play the audio and pick the phrase you heard.",
      prompt: "im Sommer",
      options: ["im Sommer", "im Winter", "im Herbst"],
      correctIndex: 0,
      explain: "The season heard: summer.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 12: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Im Winter schneit es.", "Am Winter schneit es.", "In Winter schneit es."],
      correctIndex: 0,
      explain: "Seasons take im.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 13: Der Satz",
      instruction: "Build the sentence: The sun is shining.",
      chunks: ["Die", "Sonne", "scheint."], translation: "The sun is shining.",
      explain: "The sun verb: scheinen.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 14: Der Satz",
      instruction: "Build the sentence: It is 20 degrees.",
      chunks: ["Es", "ist", "20", "Grad."], translation: "It is 20 degrees.",
      explain: "The temperature sentence.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 15: Wetterkarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "Wie ist das Wetter?", back: "How is the weather?", frontAudio: true },
        { front: "Es regnet.", back: "It is raining.", frontAudio: true },
        { front: "Es schneit.", back: "It is snowing.", frontAudio: true },
        { front: "Die Sonne scheint.", back: "The sun is shining.", frontAudio: true },
        { front: "Es ist kalt.", back: "It is cold.", frontAudio: true },
        { front: "Es ist heiß.", back: "It is hot.", frontAudio: true },
        { front: "im Sommer", back: "in summer", frontAudio: true },
        { front: "im Winter", back: "in winter", frontAudio: true },
        { front: "Es ist 20 Grad.", back: "It is 20 degrees.", frontAudio: true },
        { front: "der Frühling", back: "the spring", frontAudio: true },
        { front: "der Regen", back: "the rain", frontAudio: true },
        { front: "der Schnee", back: "the snow", frontAudio: true },
      ],
    },
  ],
};

export const stadtUndOrientierung: Unit = {
  id: "stadt-und-orientierung",
  title: "Stadt und Orientierung",
  theme: "City and getting around",
  lessons: [
    dieStadt,
    richtungen,
    woWoherWohin,
    oeffentlicheVerkehrsmittel,
    dasWetter,
  ],
};