import type { Lesson, Unit } from "../../schema";

export const dieUhrzeit: Lesson = {
  id: "die-uhrzeit",
  title: "Die Uhrzeit",
  summary:
    "Every way to tell the time in German: the official 24-hour system, the everyday halb/Viertel system, regional variants, questions, and time prepositions.",
  status: "ready",
  sections: [
    {
      heading: "Die offizielle Zeit: die 24-Stunden-Uhr",
      blocks: [
        {
          type: "paragraph",
          text: "The official way to say the time is simple: hour, then the word Uhr, then the minutes. Es ist acht Uhr. (It is eight o'clock.) Es ist acht Uhr fünf. (It is eight oh five.) This system is used in schedules, announcements, timetables, and anything written. It always runs on 24 hours: afternoon times keep counting past twelve.",
        },
        {
          type: "paragraph",
          text: "The official system is the same for every hour, and the minutes are simply the number: eight thirty is acht Uhr dreißig, not 'half'. There is no halb, no Viertel, no nach and no vor in the official style. That is the whole rule.",
        },
        {
          type: "table",
          caption: "The official system, minute by minute",
          head: ["Clock", "Official German", "Clock", "Official German"],
          rows: [
            ["8:00", "acht Uhr", "8:30", "acht Uhr dreißig"],
            ["8:05", "acht Uhr fünf", "8:35", "acht Uhr fünfunddreißig"],
            ["8:10", "acht Uhr zehn", "8:40", "acht Uhr vierzig"],
            ["8:15", "acht Uhr fünfzehn", "8:45", "acht Uhr fünfundvierzig"],
            ["8:20", "acht Uhr zwanzig", "8:50", "acht Uhr fünfzig"],
            ["8:25", "acht Uhr fünfundzwanzig", "8:55", "acht Uhr fünfundfünfzig"],
            ["8:30", "acht Uhr dreißig", "9:00", "neun Uhr"],
          ],
        },
        {
          type: "table",
          caption: "The full 24-hour clock",
          head: ["Clock", "Official German", "Clock", "Official German"],
          rows: [
            ["0:00", "null Uhr / Mitternacht", "13:00", "dreizehn Uhr"],
            ["1:00", "ein Uhr", "14:00", "vierzehn Uhr"],
            ["6:00", "sechs Uhr", "15:30", "fünfzehn Uhr dreißig"],
            ["9:00", "neun Uhr", "17:45", "siebzehn Uhr fünfundvierzig"],
            ["12:00", "zwölf Uhr / Mittag", "20:15", "zwanzig Uhr fünfzehn"],
            ["12:30", "zwölf Uhr dreißig", "23:55", "dreiundzwanzig Uhr fünfundfünfzig"],
            ["24:00", "vierundzwanzig Uhr / Mitternacht", "0:05", "null Uhr fünf"],
          ],
        },
        {
          type: "tip",
          text: "In the official system the minutes are always a plain number: 17:45 is siebzehn Uhr fünfundvierzig, never 'Viertel vor sechs'. Write and announce times officially, speak them informally. That split is the key to telling time in German.",
        },
      ],
    },
    {
      heading: "Die inoffizielle Zeit: halb, Viertel, nach, vor",
      blocks: [
        {
          type: "paragraph",
          text: "In everyday conversation Germans do not count minutes after the hour. They split the hour into quarters and count toward the next hour. The system has four building blocks: nach (past the hour), vor (before the next hour), Viertel (quarter), and halb (half, which always points FORWARD to the next hour).",
        },
        {
          type: "paragraph",
          text: "The famous trap: halb neun is not 9:30. Halb means 'halfway toward', so halb neun is halfway from eight to nine, which is 8:30. Germans think in the next hour: halb drei is 2:30, halb zwölf is 11:30. Train yourself to translate halb X as 'half past X minus one'.",
        },
        {
          type: "table",
          caption: "The everyday system, every five minutes from 8:00 to 9:00",
          head: ["Clock", "Everyday German", "Clock", "Everyday German"],
          rows: [
            ["8:00", "acht Uhr", "8:30", "halb neun"],
            ["8:05", "fünf nach acht", "8:35", "fünf nach halb neun"],
            ["8:10", "zehn nach acht", "8:40", "zehn nach halb neun / zwanzig vor neun"],
            ["8:15", "Viertel nach acht", "8:45", "Viertel vor neun"],
            ["8:20", "zwanzig nach acht / zehn vor halb neun", "8:50", "zehn vor neun"],
            ["8:25", "fünf vor halb neun", "8:55", "fünf vor neun"],
            ["8:30", "halb neun", "9:00", "neun Uhr"],
          ],
        },
        {
          type: "table",
          caption: "The same hour, both systems side by side",
          head: ["Clock", "Official", "Everyday"],
          rows: [
            ["8:05", "acht Uhr fünf", "fünf nach acht"],
            ["8:15", "acht Uhr fünfzehn", "Viertel nach acht"],
            ["8:25", "acht Uhr fünfundzwanzig", "fünf vor halb neun"],
            ["8:30", "acht Uhr dreißig", "halb neun"],
            ["8:35", "acht Uhr fünfunddreißig", "fünf nach halb neun"],
            ["8:45", "acht Uhr fünfundvierzig", "Viertel vor neun"],
            ["8:55", "acht Uhr fünfundfünfzig", "fünf vor neun"],
          ],
        },
        {
          type: "tip",
          text: "After the half hour, everything counts toward the NEXT hour: 8:40 is zehn vor halb neun (ten before half-nine) or zwanzig vor neun (twenty before nine). Both are correct; the first is more common in the north, the second in the south.",
        },
      ],
    },
    {
      heading: "Regionale Varianten",
      blocks: [
        {
          type: "paragraph",
          text: "In southern Germany, Austria, and Switzerland you will hear a different system: the quarter is counted toward the next hour without nach or vor. viertel neun means 8:15 (a quarter toward nine) and dreiviertel neun means 8:45 (three quarters toward nine). The official and standard northern systems are safe everywhere; the regional system is good to recognize.",
        },
        {
          type: "table",
          caption: "Regional ways to say 8:15 and 8:45",
          head: ["Region", "8:15", "8:45"],
          rows: [
            ["standard", "Viertel nach acht", "Viertel vor neun"],
            ["south / Austria / Switzerland", "viertel neun", "dreiviertel neun"],
          ],
        },
        {
          type: "tip",
          text: "If someone says dreiviertel neun, think 'three quarters of the way to nine': 8:45. You will pass the Goethe exam using the standard forms, but knowing the regional ones prevents real confusion at work.",
        },
      ],
    },
    {
      heading: "Die Tageszeiten",
      blocks: [
        {
          type: "paragraph",
          text: "The day is split into six parts, and each has its own greeting and its own preposition: am Morgen, am Vormittag, am Mittag, am Nachmittag, am Abend, in der Nacht. The greetings follow the clock: Guten Morgen until about 11, Guten Tag during the day, Guten Abend after about 18, Gute Nacht when going to bed.",
        },
        {
          type: "table",
          caption: "The day parts",
          head: ["Day part", "Time", "Preposition", "Greeting"],
          rows: [
            ["der Morgen", "about 5-10", "am Morgen", "Guten Morgen"],
            ["der Vormittag", "about 10-12", "am Vormittag", "Guten Tag"],
            ["der Mittag", "about 12-14", "am Mittag", "Guten Tag"],
            ["der Nachmittag", "about 14-18", "am Nachmittag", "Guten Tag"],
            ["der Abend", "about 18-22", "am Abend", "Guten Abend"],
            ["die Nacht", "about 22-5", "in der Nacht", "Gute Nacht"],
          ],
        },
        {
          type: "example",
          de: "Am Morgen trinke ich Kaffee. Am Abend sehe ich fern. In der Nacht schlafe ich.",
          en: "In the morning I drink coffee. In the evening I watch TV. At night I sleep.",
        },
        {
          type: "tip",
          text: "Day parts take am, nights take in der: am Morgen, am Vormittag, am Mittag, am Nachmittag, am Abend, in der Nacht. Only die Nacht switches to in der.",
        },
      ],
    },
    {
      heading: "Fragen nach der Zeit",
      blocks: [
        {
          type: "paragraph",
          text: "There are three everyday questions: Wie spät ist es? (What time is it?) and Wie viel Uhr ist es? (same meaning, equally common), and Um wie viel Uhr ...? for at what time something happens. Wann? is the general when-question and accepts any answer.",
        },
        {
          type: "table",
          caption: "The questions",
          head: ["Question", "Means", "Answer"],
          rows: [
            ["Wie spät ist es?", "What time is it?", "Es ist halb drei."],
            ["Wie viel Uhr ist es?", "What time is it?", "Es ist 14:30 Uhr."],
            ["Um wie viel Uhr beginnt der Kurs?", "At what time does the course start?", "Um neun Uhr."],
            ["Wann hast du Zeit?", "When do you have time?", "Am Nachmittag."],
          ],
        },
        {
          type: "example",
          de: "Wie spät ist es? Es ist Viertel nach acht. Um wie viel Uhr fährt der Zug? Um 14:30 Uhr.",
          en: "What time is it? It is 8:15. At what time does the train leave? At 2:30 p.m.",
        },
      ],
    },
    {
      heading: "Zeit und Präpositionen",
      blocks: [
        {
          type: "paragraph",
          text: "Times come with their own prepositions: um for exact clock times (um acht Uhr), von ... bis for ranges (von neun bis fünf), gegen for approximately (gegen acht, about eight), bis for until (bis acht), ab for from onward (ab acht Uhr), and seit for since with the present tense (seit acht Uhr, since eight).",
        },
        {
          type: "table",
          caption: "Time prepositions",
          head: ["Preposition", "Meaning", "Example"],
          rows: [
            ["um", "at (exact time)", "um acht Uhr"],
            ["von ... bis", "from ... until", "von neun bis fünf"],
            ["gegen", "about, around", "gegen acht Uhr"],
            ["bis", "until", "bis zwölf Uhr"],
            ["ab", "from ... on", "ab acht Uhr"],
            ["seit", "since (ongoing)", "seit acht Uhr"],
          ],
        },
        {
          type: "example",
          de: "Ich arbeite von neun bis fünf. Der Laden ist ab acht Uhr geöffnet. Wir treffen uns gegen sieben.",
          en: "I work from nine to five. The shop opens at eight. We meet around seven.",
        },
      ],
    },
    {
      heading: "Dauer: Wie lange?",
      blocks: [
        {
          type: "paragraph",
          text: "Duration answers wie lange? (how long?). The building blocks: die Stunde (hour), die halbe Stunde (half hour), die Viertelstunde (quarter hour), die Minute (minute). Note that the adjective changes: eine halbe Stunde, eine Viertelstunde, anderthalb Stunden (one and a half hours).",
        },
        {
          type: "table",
          caption: "Durations",
          head: ["German", "English"],
          rows: [
            ["eine Stunde", "one hour"],
            ["eine halbe Stunde", "half an hour"],
            ["eine Viertelstunde", "a quarter of an hour"],
            ["anderthalb Stunden", "one and a half hours"],
            ["zwei Stunden", "two hours"],
            ["zwanzig Minuten", "twenty minutes"],
          ],
        },
        {
          type: "example",
          de: "Wie lange dauert der Kurs? Eine Stunde. Die Reise dauert zwei Stunden und zwanzig Minuten.",
          en: "How long does the course last? One hour. The journey lasts two hours and twenty minutes.",
        },
      ],
    },
    {
      heading: "Ein ganzer Tag",
      blocks: [
        {
          type: "paragraph",
          text: "Here is a full day told with every time pattern you just learned. Read it aloud, then build your own day with the same skeleton: um for the exact times, halb and Viertel for the everyday times, von ... bis for the working hours.",
        },
        {
          type: "example",
          de: "Ich wache um halb sieben auf. Um Viertel nach sieben frühstücke ich. Um acht Uhr fahre ich zur Arbeit. Ich arbeite von neun bis fünf. Um halb sechs bin ich zu Hause. Am Abend koche ich und sehe fern. Um zehn Uhr gehe ich schlafen.",
          en: "I wake up at 6:30. At 7:15 I have breakfast. At eight I drive to work. I work from nine to five. At 5:30 I am at home. In the evening I cook and watch TV. At ten I go to bed.",
        },
        {
          type: "tip",
          text: "Notice the pattern: exact times with um, ranges with von ... bis, day parts with am. One day, all three systems working together.",
        },
      ],
    },
  ],
  vocab: [
    { id: "die-uhr", de: "die Uhr", en: "the clock, the watch", part: "noun f.", plural: "die Uhren", audio: true },
    { id: "die-uhrzeit", de: "die Uhrzeit", en: "the time of day", part: "noun f.", plural: "die Uhrzeiten", audio: true },
    { id: "die-stunde", de: "die Stunde", en: "the hour", part: "noun f.", plural: "die Stunden", audio: true },
    { id: "die-halbe-stunde", de: "die halbe Stunde", en: "half an hour", part: "phrase", phrase: true, audio: true },
    { id: "die-viertelstunde", de: "die Viertelstunde", en: "a quarter of an hour", part: "noun f.", plural: "die Viertelstunden", audio: true },
    { id: "die-minute", de: "die Minute", en: "the minute", part: "noun f.", plural: "die Minuten", audio: true },
    { id: "halb", de: "halb", en: "half (halfway to the next hour)", part: "adjective", audio: true },
    { id: "das-viertel", de: "das Viertel", en: "the quarter", part: "noun n.", plural: "die Viertel", audio: true },
    { id: "nach", de: "nach", en: "past, after", part: "preposition", audio: true },
    { id: "vor", de: "vor", en: "before, to (minutes)", part: "preposition", audio: true },
    { id: "gegen", de: "gegen", en: "about, around (time)", part: "preposition", audio: true },
    { id: "ab", de: "ab", en: "from ... on (time)", part: "preposition", audio: true },
    { id: "wie-spaet", de: "Wie spät ist es?", en: "What time is it?", part: "phrase", phrase: true, audio: true },
    { id: "wie-viel-uhr", de: "Wie viel Uhr ist es?", en: "What time is it?", part: "phrase", phrase: true, audio: true },
    { id: "um-wie-viel-uhr", de: "Um wie viel Uhr?", en: "At what time?", part: "phrase", phrase: true, audio: true },
    { id: "mitternacht", de: "Mitternacht", en: "midnight", part: "noun f.", audio: true },
    { id: "mittag", de: "der Mittag", en: "noon, midday", part: "noun m.", audio: true },
    { id: "anderthalb", de: "anderthalb", en: "one and a half", part: "number", audio: true },
  ],
  exercises: [
    {
      id: "ex-offiziell",
      type: "multiple-choice",
      title: "Übung 1: Die offizielle Zeit",
      instruction: "Read the official time. What time is it?",
      prompt: "Es ist vierzehn Uhr dreißig.",
      options: ["14:30", "4:30", "14:03"],
      correctIndex: 0,
      explain: "Vierzehn Uhr dreißig is 14:30 in the 24-hour system.",
    },
    {
      id: "ex-halb",
      type: "multiple-choice",
      title: "Übung 2: Die halb-Falle",
      instruction: "The famous trap: what time is halb neun?",
      prompt: "Es ist halb neun.",
      options: ["8:30", "9:30", "8:15"],
      correctIndex: 0,
      explain: "halb neun is halfway toward nine, so 8:30.",
    },
    {
      id: "ex-viertel",
      type: "multiple-choice",
      title: "Übung 3: Viertel",
      instruction: "Choose the correct time.",
      prompt: "Es ist Viertel vor neun.",
      options: ["8:45", "8:15", "9:15"],
      correctIndex: 0,
      explain: "A quarter before nine is 8:45.",
    },
    {
      id: "ex-fuenf-minuten",
      type: "multiple-choice",
      title: "Übung 4: Fünf Minuten",
      instruction: "Choose the correct time.",
      prompt: "Es ist fünf vor halb neun.",
      options: ["8:25", "8:35", "8:55"],
      correctIndex: 0,
      explain: "Five minutes before half-nine (8:30) is 8:25.",
    },
    {
      id: "ex-hoeren-offiziell",
      type: "listening",
      title: "Übung 5: Hören, offiziell",
      instruction: "Play the audio and pick the time you heard.",
      prompt: "siebzehn Uhr fünfundvierzig",
      options: ["17:45", "7:45", "17:15"],
      correctIndex: 0,
      explain: "Siebzehn Uhr fünfundvierzig is 17:45.",
    },
    {
      id: "ex-hoeren-informell",
      type: "listening",
      title: "Übung 6: Hören, informell",
      instruction: "Play the audio and pick the time you heard.",
      prompt: "zwanzig nach acht",
      options: ["8:20", "8:40", "8:10"],
      correctIndex: 0,
      explain: "Twenty minutes past eight is 8:20.",
    },
    {
      id: "ex-fill-offiziell",
      type: "fill-blank",
      title: "Übung 7: Offiziell schreiben",
      instruction: "Write the official time in words.",
      sentence: "14:15 ist ___ Uhr ___. 20:30 ist ___ Uhr ___.",
      blanks: [
        { answers: ["vierzehn"], hint: "the hour" },
        { answers: ["fünfzehn"], hint: "the minutes" },
        { answers: ["zwanzig"], hint: "the hour" },
        { answers: ["dreißig"], hint: "the minutes" },
      ],
    },
    {
      id: "ex-fill-informell",
      type: "fill-blank",
      title: "Übung 8: Informell schreiben",
      instruction: "Write the everyday time in words.",
      sentence: "8:25 ist ___ vor ___ neun. 8:35 ist ___ nach ___ neun.",
      blanks: [
        { answers: ["fünf"], hint: "five minutes" },
        { answers: ["halb"], hint: "half past eight" },
        { answers: ["fünf"], hint: "five minutes" },
        { answers: ["halb"], hint: "half past eight" },
      ],
    },
    {
      id: "ex-matching-zeiten",
      type: "matching",
      title: "Übung 9: Uhr und Sprache",
      instruction: "Match each clock time to the German words.",
      pairs: [
        ["7:15", "Viertel nach sieben"],
        ["7:30", "halb acht"],
        ["7:45", "Viertel vor acht"],
        ["21:05", "einundzwanzig Uhr fünf"],
        ["12:00", "zwölf Uhr / Mittag"],
        ["0:00", "Mitternacht"],
        ["9:50", "zehn vor zehn"],
        ["10:40", "zehn vor halb elf"],
      ],
    },
    {
      id: "ex-praepositionen",
      type: "fill-blank",
      title: "Übung 10: Zeit und Präpositionen",
      instruction: "Complete with the right time preposition.",
      sentence: "Ich arbeite ___ neun ___ fünf. Der Laden ist ___ acht Uhr geöffnet. Wir treffen uns ___ sieben. (about)",
      blanks: [
        { answers: ["von"], hint: "from" },
        { answers: ["bis"], hint: "until" },
        { answers: ["ab"], hint: "from ... on" },
        { answers: ["gegen"], hint: "about, around" },
      ],
    },
    {
      id: "ex-tageszeiten",
      type: "multiple-choice",
      title: "Übung 11: Tageszeiten",
      instruction: "Choose the correct preposition.",
      prompt: "___ Abend sehe ich fern.",
      options: ["Am", "Im", "Um"],
      correctIndex: 0,
      explain: "Day parts take am: am Abend.",
    },
    {
      id: "ex-dauer",
      type: "multiple-choice",
      title: "Übung 12: Dauer",
      instruction: "Choose the correct duration.",
      prompt: "Wie lange dauert der Kurs? Eine ___ Stunde.",
      options: ["halbe", "halb", "Halb"],
      correctIndex: 0,
      explain: "The adjective follows the noun's gender: eine halbe Stunde.",
    },
    {
      id: "ex-wortfolge",
      type: "word-order",
      title: "Übung 13: Der Satz",
      instruction: "Build the sentence: The train departs at 2:30.",
      chunks: ["Der", "Zug", "fährt", "um", "14:30", "Uhr", "ab."],
      explain: "Time with um, then the separable prefix ab closes the sentence.",
    },
    {
      id: "ex-tagesablauf-satz",
      type: "word-order",
      title: "Übung 14: Der Tag",
      instruction: "Build the sentence: I get up at 6:30.",
      chunks: ["Ich", "stehe", "um", "halb", "sieben", "auf."],
      explain: "The everyday time with um, the prefix auf at the end.",
    },
    {
      id: "ex-uhrzeit-karten",
      type: "flashcard",
      title: "Übung 15: Uhrzeitkarten",
      instruction: "Say the German time out loud before revealing the clock.",
      items: [
        { front: "acht Uhr", back: "8:00", frontAudio: true },
        { front: "fünf nach acht", back: "8:05", frontAudio: true },
        { front: "Viertel nach acht", back: "8:15", frontAudio: true },
        { front: "halb neun", back: "8:30", frontAudio: true },
        { front: "Viertel vor neun", back: "8:45", frontAudio: true },
        { front: "fünf vor neun", back: "8:55", frontAudio: true },
        { front: "vierzehn Uhr dreißig", back: "14:30", frontAudio: true },
        { front: "zwanzig Uhr fünfzehn", back: "20:15", frontAudio: true },
        { front: "Mitternacht", back: "0:00", frontAudio: true },
        { front: "fünf vor halb neun", back: "8:25", frontAudio: true },
        { front: "fünf nach halb neun", back: "8:35", frontAudio: true },
        { front: "zehn vor zehn", back: "9:50", frontAudio: true },
      ],
    },
  ],
};

const wochentageUndMonate: Lesson = {
  id: "wochentage-und-monate",
  title: "Wochentage und Monate",
  summary: "Days, months, seasons, and dates.",
  status: "ready",
  sections: [
    {
      heading: "Die Wochentage",
      blocks: [
        {
          type: "table",
          caption: "Days of the week",
          head: ["German", "English"],
          rows: [
            ["der Montag", "Monday"],
            ["der Dienstag", "Tuesday"],
            ["der Mittwoch", "Wednesday"],
            ["der Donnerstag", "Thursday"],
            ["der Freitag", "Friday"],
            ["der Samstag", "Saturday"],
            ["der Sonntag", "Sunday"],
          ],
        },
        {
          type: "example",
          de: "Am Montag arbeite ich. Montags gehe ich schwimmen.",
          en: "On Monday I work. On Mondays I go swimming.",
        },
        {
          type: "tip",
          text: "am + day means one specific day; the plain day word with -s (montags) means every week. The weekend is das Wochenende: am Wochenende.",
        },
      ],
    },
    {
      heading: "Die Monate",
      blocks: [
        {
          type: "table",
          caption: "Months",
          head: ["German", "English"],
          rows: [
            ["der Januar", "January"],
            ["der Februar", "February"],
            ["der März", "March"],
            ["der April", "April"],
            ["der Mai", "May"],
            ["der Juni", "June"],
            ["der Juli", "July"],
            ["der August", "August"],
            ["der September", "September"],
            ["der Oktober", "October"],
            ["der November", "November"],
            ["der Dezember", "December"],
          ],
        },
        {
          type: "example",
          de: "Im Juli habe ich Urlaub.",
          en: "In July I have vacation.",
        },
      ],
    },
    {
      heading: "Die Jahreszeiten und das Datum",
      blocks: [
        {
          type: "table",
          caption: "Seasons",
          head: ["German", "English"],
          rows: [
            ["der Frühling", "spring"],
            ["der Sommer", "summer"],
            ["der Herbst", "autumn"],
            ["der Winter", "winter"],
          ],
        },
        {
          type: "paragraph",
          text: "Dates use ordinals: der erste Mai, der zweite Juni, der dritte Juli. With a preposition: am ersten Mai.",
        },
        {
          type: "example",
          de: "Wann hast du Geburtstag? Am fünften Mai.",
          en: "When is your birthday? On May 5th.",
        },
        {
          type: "example",
          de: "Heute ist der 1. April. Der erste April!",
          en: "Today is April 1st. April Fools!",
        },
      ],
    },
  ],
  vocab: [
    { id: "der-montag", de: "der Montag", en: "Monday", part: "noun m.", plural: "die Montage", audio: true },
    { id: "der-dienstag", de: "der Dienstag", en: "Tuesday", part: "noun m.", plural: "die Dienstage", audio: true },
    { id: "der-mittwoch", de: "der Mittwoch", en: "Wednesday", part: "noun m.", plural: "die Mittwoche", audio: true },
    { id: "der-donnerstag", de: "der Donnerstag", en: "Thursday", part: "noun m.", plural: "die Donnerstage", audio: true },
    { id: "der-freitag", de: "der Freitag", en: "Friday", part: "noun m.", plural: "die Freitage", audio: true },
    { id: "der-samstag", de: "der Samstag", en: "Saturday", part: "noun m.", plural: "die Samstage", audio: true },
    { id: "der-sonntag", de: "der Sonntag", en: "Sunday", part: "noun m.", plural: "die Sonntage", audio: true },
    { id: "der-januar", de: "der Januar", en: "January", part: "noun m.", audio: true },
    { id: "der-maerz", de: "der März", en: "March", part: "noun m.", audio: true },
    { id: "der-mai", de: "der Mai", en: "May", part: "noun m.", audio: true },
    { id: "der-juli", de: "der Juli", en: "July", part: "noun m.", audio: true },
    { id: "der-dezember", de: "der Dezember", en: "December", part: "noun m.", audio: true },
    { id: "der-fruehling", de: "der Frühling", en: "spring", part: "noun m.", audio: true },
    { id: "der-sommer", de: "der Sommer", en: "summer", part: "noun m.", audio: true },
    { id: "der-herbst", de: "der Herbst", en: "autumn", part: "noun m.", audio: true },
    { id: "der-winter", de: "der Winter", en: "winter", part: "noun m.", audio: true },
    { id: "das-wochenende", de: "das Wochenende", en: "the weekend", part: "noun n.", plural: "die Wochenenden", audio: true },
    { id: "der-geburtstag", de: "der Geburtstag", en: "the birthday", part: "noun m.", plural: "die Geburtstage", audio: true },
    { id: "wann-hast-du", de: "Wann hast du Geburtstag?", en: "When is your birthday?", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "mc-wochentage",
      type: "multiple-choice",
      title: "Der Wochentag",
      instruction: "Choose the right day.",
      prompt: "The day between Friday and Sunday is ...",
      options: ["der Samstag", "der Donnerstag", "der Montag"],
      correctIndex: 0,
      explain: "Samstag sits between Friday and Sunday.",
    },
    {
      id: "listening-wochentage",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the word you heard.",
      prompt: "der Donnerstag",
      options: ["der Donnerstag", "der Dienstag", "der Sonntag"],
      correctIndex: 0,
    },
    {
      id: "fill-wochentage",
      type: "fill-blank",
      title: "Wann?",
      instruction: "Complete the sentences.",
      sentence: "___ Montag arbeite ich. ___ Juli habe ich Urlaub.",
      blanks: [
        { answers: ["Am"], hint: "on Monday" },
        { answers: ["Im"], hint: "in July" },
      ],
    },
    {
      id: "matching-wochentage",
      type: "matching",
      title: "Tage und Monate",
      instruction: "Match each German word to its meaning.",
      pairs: [
        ["der Mittwoch", "Wednesday"],
        ["der Freitag", "Friday"],
        ["der März", "March"],
        ["der Herbst", "autumn"],
        ["das Wochenende", "the weekend"],
      ],
    },
    {
      id: "word-order-wochentage",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: Today is the first of May.",
      chunks: ["Heute", "ist", "der", "erste", "Mai."],
      explain: "ist sits in second position; the date follows.",
    },
    {
      id: "flashcard-wochentage",
      type: "flashcard",
      title: "Wochentagskarten",
      instruction: "Say the German day or month out loud before revealing.",
      items: [
        { front: "der Montag", back: "Monday", frontAudio: true },
        { front: "der Mittwoch", back: "Wednesday", frontAudio: true },
        { front: "der Freitag", back: "Friday", frontAudio: true },
        { front: "der Sonntag", back: "Sunday", frontAudio: true },
        { front: "der Mai", back: "May", frontAudio: true },
        { front: "der Winter", back: "winter", frontAudio: true },
      ],
    },
  ],
};

const meinTagesablauf: Lesson = {
  id: "mein-tagesablauf",
  title: "Mein Tagesablauf",
  summary: "Daily routine verbs and sequencing: zuerst, dann, danach.",
  status: "ready",
  sections: [
    {
      heading: "Der Tag",
      blocks: [
        {
          type: "paragraph",
          text: "Daily routines are built from a handful of verbs. Many of them are separable, so the prefix travels to the end of the sentence.",
        },
        {
          type: "table",
          caption: "Daily routine verbs",
          head: ["German", "English"],
          rows: [
            ["aufwachen", "to wake up"],
            ["aufstehen", "to get up"],
            ["duschen", "to shower"],
            ["frühstücken", "to have breakfast"],
            ["zur Arbeit gehen", "to go to work"],
            ["arbeiten", "to work"],
            ["Mittag essen", "to have lunch"],
            ["einkaufen", "to go shopping"],
            ["kochen", "to cook"],
            ["fernsehen", "to watch TV"],
            ["schlafen gehen", "to go to bed"],
          ],
        },
        {
          type: "tip",
          text: "In statements the conjugated verb is second and separable prefixes wait at the end: Ich stehe um sieben Uhr auf.",
        },
      ],
    },
    {
      heading: "Eine Geschichte",
      blocks: [
        {
          type: "example",
          de: "Ich wache um halb sieben auf. Dann dusche ich und frühstücke.",
          en: "I wake up at 6:30. Then I shower and have breakfast.",
        },
        {
          type: "example",
          de: "Um acht Uhr fahre ich zur Arbeit. Ich arbeite von neun bis fünf.",
          en: "At eight I drive to work. I work from nine to five.",
        },
        {
          type: "example",
          de: "Am Abend koche ich und sehe fern.",
          en: "In the evening I cook and watch TV.",
        },
      ],
    },
    {
      heading: "Zuerst, dann, danach",
      blocks: [
        {
          type: "paragraph",
          text: "Sequencing words order your story. They sit at the front and push the verb to second position.",
        },
        {
          type: "example",
          de: "Zuerst stehe ich auf, dann frühstücke ich.",
          en: "First I get up, then I have breakfast.",
        },
        {
          type: "example",
          de: "Danach fahre ich zur Arbeit. Zum Schluss schlafe ich.",
          en: "After that I drive to work. Finally I sleep.",
        },
        {
          type: "tip",
          text: "The sequence: zuerst, dann, danach, später, zum Schluss. All five behave the same: front position, verb follows.",
        },
      ],
    },
  ],
  vocab: [
    { id: "aufwachen", de: "aufwachen", en: "to wake up", part: "verb", audio: true },
    { id: "aufstehen", de: "aufstehen", en: "to get up", part: "verb", audio: true },
    { id: "duschen", de: "duschen", en: "to shower", part: "verb", audio: true },
    { id: "fruehstuecken", de: "frühstücken", en: "to have breakfast", part: "verb", audio: true },
    { id: "arbeiten", de: "arbeiten", en: "to work", part: "verb", audio: true },
    { id: "einkaufen", de: "einkaufen", en: "to go shopping", part: "verb", audio: true },
    { id: "kochen", de: "kochen", en: "to cook", part: "verb", audio: true },
    { id: "fernsehen", de: "fernsehen", en: "to watch TV", part: "verb", audio: true },
    { id: "schlafen", de: "schlafen gehen", en: "to go to bed", part: "phrase", phrase: true, audio: true },
    { id: "die-arbeit", de: "die Arbeit", en: "the work", part: "noun f.", plural: "die Arbeiten", audio: true },
    { id: "zuerst", de: "zuerst", en: "first", part: "adverb", audio: true },
    { id: "dann", de: "dann", en: "then", part: "adverb", audio: true },
    { id: "danach", de: "danach", en: "after that", part: "adverb", audio: true },
    { id: "zum-schluss", de: "zum Schluss", en: "finally", part: "adverb", audio: true },
  ],
  exercises: [
    {
      id: "mc-tagesablauf",
      type: "multiple-choice",
      title: "Der Tagesablauf",
      instruction: "Choose the correct verb.",
      prompt: "Zuerst ___ ich auf, dann frühstücke ich.",
      options: ["stehe", "steh", "steht"],
      correctIndex: 0,
      explain: "Ich stehe auf; the prefix auf waits at the end.",
    },
    {
      id: "listening-tagesablauf",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Zuerst stehe ich auf.",
      options: ["Zuerst stehe ich auf.", "Zuerst stehe ich auf? Dann.", "Danach stehe ich auf."],
      correctIndex: 0,
    },
    {
      id: "fill-tagesablauf",
      type: "fill-blank",
      title: "Der Tag",
      instruction: "Complete the routine.",
      sentence: "Ich ___ um sieben Uhr ___. Danach ___ ich früh.",
      blanks: [
        { answers: ["stehe"], hint: "conjugated part of aufstehen" },
        { answers: ["auf"], hint: "the prefix" },
        { answers: ["frühstücke"], hint: "frühstücken, ich-form" },
      ],
    },
    {
      id: "matching-tagesablauf",
      type: "matching",
      title: "Verben",
      instruction: "Match each verb to its meaning.",
      pairs: [
        ["aufstehen", "to get up"],
        ["frühstücken", "to have breakfast"],
        ["einkaufen", "to go shopping"],
        ["fernsehen", "to watch TV"],
        ["schlafen gehen", "to go to bed"],
      ],
    },
    {
      id: "word-order-tagesablauf",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: First I get up, then I have breakfast.",
      chunks: ["Zuerst", "stehe", "ich", "auf,", "dann", "frühstücke", "ich."],
      explain: "Zuerst pushes the verb up; auf closes the first clause.",
    },
    {
      id: "flashcard-tagesablauf",
      type: "flashcard",
      title: "Tagesablaufkarten",
      instruction: "Say the German verb out loud before revealing.",
      items: [
        { front: "aufwachen", back: "to wake up", frontAudio: true },
        { front: "aufstehen", back: "to get up", frontAudio: true },
        { front: "frühstücken", back: "to have breakfast", frontAudio: true },
        { front: "arbeiten", back: "to work", frontAudio: true },
        { front: "fernsehen", back: "to watch TV", frontAudio: true },
        { front: "schlafen gehen", back: "to go to bed", frontAudio: true },
      ],
    },
  ],
};

const trennbareVerben: Lesson = {
  id: "trennbare-verben",
  title: "Trennbare Verben",
  summary: "Separable verbs: aufstehen, einkaufen, mitkommen and the prefix at the end.",
  status: "ready",
  sections: [
    {
      heading: "Die Präfixe",
      blocks: [
        {
          type: "paragraph",
          text: "Separable verbs are built from a prefix plus a normal verb: auf + stehen. The prefix is stressed and, in a main clause, it splits off and waits at the end.",
        },
        {
          type: "table",
          caption: "Common separable prefixes",
          head: ["Prefix", "Example", "English"],
          rows: [
            ["auf-", "aufstehen", "to get up"],
            ["ab-", "abfahren", "to depart"],
            ["an-", "anfangen", "to begin"],
            ["aus-", "ausgehen", "to go out"],
            ["ein-", "einkaufen", "to shop"],
            ["mit-", "mitkommen", "to come along"],
            ["nach-", "nachschauen", "to look up"],
            ["vor-", "vorhaben", "to plan"],
            ["weg-", "weggehen", "to go away"],
            ["zurück-", "zurückkommen", "to come back"],
            ["zu-", "zumachen", "to close"],
            ["fern-", "fernsehen", "to watch TV"],
          ],
        },
      ],
    },
    {
      heading: "Der Satzbau",
      blocks: [
        {
          type: "paragraph",
          text: "In present-tense main clauses the prefix jumps to the end. The conjugated verb stays in second position.",
        },
        {
          type: "example",
          de: "Ich stehe um sieben Uhr auf.",
          en: "I get up at seven o'clock.",
        },
        {
          type: "example",
          de: "Kommst du mit? Wir kaufen heute ein.",
          en: "Are you coming along? We are shopping today.",
        },
        {
          type: "tip",
          text: "With modal verbs and in the infinitive, the verb stays together: Ich muss um sieben aufstehen. Only the conjugated verb splits.",
        },
      ],
    },
    {
      heading: "Wichtige Verben",
      blocks: [
        {
          type: "table",
          caption: "Everyday separable verbs",
          head: ["Infinitive", "Sentence"],
          rows: [
            ["anfangen", "Der Kurs fängt um neun an."],
            ["anrufen", "Ich rufe dich heute an."],
            ["ankommen", "Der Zug kommt um zehn an."],
            ["aufmachen", "Mach das Fenster auf!"],
            ["einladen", "Wir laden dich ein."],
            ["mitnehmen", "Nimmst du den Regenschirm mit?"],
            ["zurückkommen", "Er kommt morgen zurück."],
          ],
        },
      ],
    },
  ],
  vocab: [
    { id: "anfangen", de: "anfangen", en: "to begin", part: "verb", audio: true },
    { id: "anrufen", de: "anrufen", en: "to call (someone)", part: "verb", audio: true },
    { id: "ankommen", de: "ankommen", en: "to arrive", part: "verb", audio: true },
    { id: "abfahren", de: "abfahren", en: "to depart", part: "verb", audio: true },
    { id: "aufmachen", de: "aufmachen", en: "to open", part: "verb", audio: true },
    { id: "zumachen", de: "zumachen", en: "to close", part: "verb", audio: true },
    { id: "einladen", de: "einladen", en: "to invite", part: "verb", audio: true },
    { id: "mitkommen", de: "mitkommen", en: "to come along", part: "verb", audio: true },
    { id: "mitnehmen", de: "mitnehmen", en: "to take along", part: "verb", audio: true },
    { id: "zurueckkommen", de: "zurückkommen", en: "to come back", part: "verb", audio: true },
    { id: "weggehen", de: "weggehen", en: "to go away", part: "verb", audio: true },
    { id: "ausgehen", de: "ausgehen", en: "to go out", part: "verb", audio: true },
  ],
  exercises: [
    {
      id: "mc-trennbare",
      type: "multiple-choice",
      title: "Der Satz",
      instruction: "Choose the correct word order.",
      prompt: "Ich ___ um sieben ___.",
      options: ["stehe ... auf", "aufstehe ... -", "stehe auf ... -"],
      correctIndex: 0,
      explain: "The prefix auf goes to the end: Ich stehe um sieben auf.",
    },
    {
      id: "listening-trennbare",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Wir kaufen heute ein.",
      options: ["Wir kaufen heute ein.", "Wir einkaufen heute.", "Wir kaufen ein heute."],
      correctIndex: 0,
    },
    {
      id: "fill-trennbare",
      type: "fill-blank",
      title: "Präfixe",
      instruction: "Complete with the missing parts.",
      sentence: "Ich ___ dich heute ___ (anrufen). Der Kurs ___ um neun ___ (anfangen).",
      blanks: [
        { answers: ["rufe"], hint: "anrufen, ich" },
        { answers: ["an"], hint: "the prefix" },
        { answers: ["fängt"], hint: "anfangen, er" },
        { answers: ["an"], hint: "the prefix" },
      ],
    },
    {
      id: "matching-trennbare",
      type: "matching",
      title: "Verben",
      instruction: "Match each verb to its meaning.",
      pairs: [
        ["anrufen", "to call"],
        ["ankommen", "to arrive"],
        ["einladen", "to invite"],
        ["mitkommen", "to come along"],
        ["zurückkommen", "to come back"],
      ],
    },
    {
      id: "word-order-trennbare",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: I am calling you today.",
      chunks: ["Ich", "rufe", "dich", "heute", "an."],
      explain: "The prefix an closes the sentence.",
    },
    {
      id: "flashcard-trennbare",
      type: "flashcard",
      title: "Präfixkarten",
      instruction: "Say the German verb out loud before revealing.",
      items: [
        { front: "aufstehen", back: "to get up", frontAudio: true },
        { front: "anrufen", back: "to call", frontAudio: true },
        { front: "ankommen", back: "to arrive", frontAudio: true },
        { front: "einkaufen", back: "to shop", frontAudio: true },
        { front: "einladen", back: "to invite", frontAudio: true },
        { front: "mitkommen", back: "to come along", frontAudio: true },
      ],
    },
  ],
};

const derImperativ: Lesson = {
  id: "der-imperativ",
  title: "Der Imperativ",
  summary: "Imperatives for du, ihr, and Sie.",
  status: "ready",
  sections: [
    {
      heading: "Der Imperativ mit du",
      blocks: [
        {
          type: "paragraph",
          text: "The du imperative is the verb stem, often with a friendly -e. Vowel-changing verbs keep their change: e becomes i(e) in the du-form.",
        },
        {
          type: "table",
          caption: "du imperatives",
          head: ["Infinitive", "Imperative"],
          rows: [
            ["kommen", "Komm! / Komme!"],
            ["sagen", "Sag! / Sage!"],
            ["arbeiten", "Arbeite!"],
            ["sprechen", "Sprich!"],
            ["essen", "Iss!"],
            ["geben", "Gib!"],
            ["nehmen", "Nimm!"],
            ["sein", "Sei!"],
            ["haben", "Hab!"],
          ],
        },
        {
          type: "tip",
          text: "The du pronoun disappears in the imperative. The e-ending softens the tone: Komm mal her! is casual, Komme bitte! is softer.",
        },
      ],
    },
    {
      heading: "ihr und Sie",
      blocks: [
        {
          type: "paragraph",
          text: "The ihr imperative is simply the ihr-form without the pronoun. The Sie imperative is the infinitive with Sie after it, like a question without the question mark.",
        },
        {
          type: "table",
          caption: "All three forms",
          head: ["du", "ihr", "Sie"],
          rows: [
            ["Komm!", "Kommt!", "Kommen Sie!"],
            ["Sprich!", "Sprecht!", "Sprechen Sie!"],
            ["Iss!", "Esst!", "Essen Sie!"],
            ["Sei!", "Seid!", "Seien Sie!"],
            ["Hab!", "Habt!", "Haben Sie!"],
          ],
        },
        {
          type: "example",
          de: "Kommen Sie bitte! Komm mal her! Kommt alle mit!",
          en: "Please come (formal)! Come here (informal)! Come along, everyone!",
        },
      ],
    },
    {
      heading: "Aufforderungen im Alltag",
      blocks: [
        {
          type: "example",
          de: "Steh auf! Mach das Fenster auf!",
          en: "Get up! Open the window!",
        },
        {
          type: "example",
          de: "Komm nicht so spät!",
          en: "Don't come so late!",
        },
        {
          type: "example",
          de: "Gehen wir ins Kino!",
          en: "Let's go to the cinema!",
        },
        {
          type: "tip",
          text: "Separable verbs split in the imperative too: Steh auf! The wir-form with the verb first (Gehen wir!) is the way to suggest doing something together.",
        },
      ],
    },
  ],
  vocab: [
    { id: "komm", de: "Komm!", en: "Come!", part: "phrase", phrase: true, audio: true },
    { id: "sprich", de: "Sprich!", en: "Speak!", part: "phrase", phrase: true, audio: true },
    { id: "iss", de: "Iss!", en: "Eat!", part: "phrase", phrase: true, audio: true },
    { id: "gib", de: "Gib!", en: "Give!", part: "phrase", phrase: true, audio: true },
    { id: "nimm", de: "Nimm!", en: "Take!", part: "phrase", phrase: true, audio: true },
    { id: "sei", de: "Sei!", en: "Be!", part: "phrase", phrase: true, audio: true },
    { id: "kommt", de: "Kommt!", en: "Come! (you all)", part: "phrase", phrase: true, audio: true },
    { id: "kommen-sie", de: "Kommen Sie!", en: "Come! (formal)", part: "phrase", phrase: true, audio: true },
    { id: "seien-sie", de: "Seien Sie!", en: "Be! (formal)", part: "phrase", phrase: true, audio: true },
    { id: "steh-auf", de: "Steh auf!", en: "Get up!", part: "phrase", phrase: true, audio: true },
    { id: "bitte", de: "bitte", en: "please", part: "adverb", audio: true },
    { id: "mal", de: "mal", en: "just (softener)", part: "adverb", audio: true },
  ],
  exercises: [
    {
      id: "mc-imperativ",
      type: "multiple-choice",
      title: "Der Imperativ",
      instruction: "Choose the du imperative.",
      prompt: "sprechen (du): ___ bitte!",
      options: ["Sprich", "Sprech", "Spricht"],
      correctIndex: 0,
      explain: "sprechen changes e to i in the du imperative: Sprich!",
    },
    {
      id: "listening-imperativ",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the imperative you heard.",
      prompt: "Kommen Sie bitte!",
      options: ["Kommen Sie bitte!", "Kommt bitte!", "Komm bitte!"],
      correctIndex: 0,
    },
    {
      id: "fill-imperativ",
      type: "fill-blank",
      title: "Die Form",
      instruction: "Complete the imperatives.",
      sentence: "___ Sie bitte! (kommen) ___ auf! (aufstehen, du)",
      blanks: [
        { answers: ["Kommen"], hint: "formal" },
        { answers: ["Steh"], hint: "du, prefix at the end" },
      ],
    },
    {
      id: "matching-imperativ",
      type: "matching",
      title: "Du, ihr oder Sie?",
      instruction: "Match each form to its register.",
      pairs: [
        ["Komm!", "du"],
        ["Kommt!", "ihr"],
        ["Kommen Sie!", "Sie"],
        ["Sei!", "du"],
        ["Seien Sie!", "Sie"],
      ],
    },
    {
      id: "word-order-imperativ",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: Get up at seven!",
      chunks: ["Steh", "um", "sieben", "auf!"],
      explain: "The prefix auf closes the command.",
    },
    {
      id: "flashcard-imperativ",
      type: "flashcard",
      title: "Imperativkarten",
      instruction: "Say the imperative out loud before revealing.",
      items: [
        { front: "Komm!", back: "Come!", frontAudio: true },
        { front: "Sprich!", back: "Speak!", frontAudio: true },
        { front: "Iss!", back: "Eat!", frontAudio: true },
        { front: "Kommt!", back: "Come! (you all)", frontAudio: true },
        { front: "Kommen Sie!", back: "Come! (formal)", frontAudio: true },
        { front: "Steh auf!", back: "Get up!", frontAudio: true },
      ],
    },
  ],
};

const zeitangaben: Lesson = {
  id: "zeitangaben",
  title: "Zeitangaben",
  summary: "um, am, im, von ... bis: time prepositions.",
  status: "ready",
  sections: [
    {
      heading: "Die Präpositionen",
      blocks: [
        {
          type: "table",
          caption: "Time prepositions",
          head: ["Preposition", "Used with", "Example"],
          rows: [
            ["um", "clock times", "um acht Uhr"],
            ["am", "days and day parts", "am Montag, am Abend"],
            ["im", "months, seasons, years", "im Juli, im Winter, im Jahr 2026"],
            ["von ... bis", "ranges", "von neun bis fünf"],
            ["seit", "since, for (ongoing)", "seit einem Jahr"],
            ["in", "future distance", "in zwei Tagen"],
          ],
        },
        {
          type: "tip",
          text: "am is the contraction of an dem, im of in dem. That is why day parts take am (am Morgen) and months take im (im Juli).",
        },
      ],
    },
    {
      heading: "Fragen nach der Zeit",
      blocks: [
        {
          type: "table",
          caption: "Time questions",
          head: ["Question", "Asks for", "Answer"],
          rows: [
            ["Wann?", "any time", "Am Montag. Im Juli."],
            ["Um wie viel Uhr?", "a clock time", "Um neun Uhr."],
            ["Seit wann?", "the start of an ongoing action", "Seit einem Jahr."],
            ["Wie lange?", "a duration", "Von neun bis fünf."],
          ],
        },
      ],
    },
    {
      heading: "Im Alltag",
      blocks: [
        {
          type: "example",
          de: "Ich arbeite von neun bis fünf. Am Abend koche ich.",
          en: "I work from nine to five. In the evening I cook.",
        },
        {
          type: "example",
          de: "Im Winter schneit es. In zwei Tagen ist Weihnachten.",
          en: "In winter it snows. In two days it is Christmas.",
        },
        {
          type: "example",
          de: "Ich lerne seit einem Jahr Deutsch.",
          en: "I have been learning German for a year.",
        },
      ],
    },
  ],
  vocab: [
    { id: "um", de: "um", en: "at (clock time)", part: "preposition", audio: true },
    { id: "am", de: "am", en: "on (day), in (day part)", part: "preposition", audio: true },
    { id: "im", de: "im", en: "in (month, season)", part: "preposition", audio: true },
    { id: "seit", de: "seit", en: "since, for", part: "preposition", audio: true },
    { id: "bis", de: "bis", en: "until", part: "preposition", audio: true },
    { id: "in", de: "in", en: "in (future distance)", part: "preposition", audio: true },
    { id: "wann", de: "wann", en: "when", part: "question word", audio: true },
    { id: "wie-lange", de: "Wie lange?", en: "How long?", part: "phrase", phrase: true, audio: true },
    { id: "seit-wann", de: "Seit wann?", en: "Since when?", part: "phrase", phrase: true, audio: true },
    { id: "der-morgen", de: "der Morgen", en: "the morning", part: "noun m.", plural: "die Morgen", audio: true },
    { id: "der-abend", de: "der Abend", en: "the evening", part: "noun m.", plural: "die Abende", audio: true },
    { id: "die-nacht", de: "die Nacht", en: "the night", part: "noun f.", plural: "die Nächte", audio: true },
    { id: "der-tag", de: "der Tag", en: "the day", part: "noun m.", plural: "die Tage", audio: true },
  ],
  exercises: [
    {
      id: "mc-zeitangaben",
      type: "multiple-choice",
      title: "Die Präposition",
      instruction: "Choose the correct preposition.",
      prompt: "___ Montag arbeite ich.",
      options: ["Am", "Um", "Im"],
      correctIndex: 0,
      explain: "Days take am.",
    },
    {
      id: "listening-zeitangaben",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the phrase you heard.",
      prompt: "seit einem Jahr",
      options: ["seit einem Jahr", "in einem Jahr", "für ein Jahr"],
      correctIndex: 0,
    },
    {
      id: "fill-zeitangaben",
      type: "fill-blank",
      title: "Zeitangaben",
      instruction: "Complete with the right preposition.",
      sentence: "___ acht Uhr beginne ich. ___ Juli habe ich Urlaub. Ich lerne ___ einem Jahr Deutsch.",
      blanks: [
        { answers: ["Um"], hint: "clock time" },
        { answers: ["Im"], hint: "month" },
        { answers: ["seit"], hint: "ongoing since" },
      ],
    },
    {
      id: "matching-zeitangaben",
      type: "matching",
      title: "Präpositionen",
      instruction: "Match each preposition to its use.",
      pairs: [
        ["um", "clock times"],
        ["am", "days"],
        ["im", "months"],
        ["seit", "ongoing since"],
        ["von ... bis", "ranges"],
      ],
    },
    {
      id: "word-order-zeitangaben",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: I work from nine to five.",
      chunks: ["Ich", "arbeite", "von", "neun", "bis", "fünf."],
      explain: "The range von ... bis forms one time block after the verb.",
    },
    {
      id: "flashcard-zeitangaben",
      type: "flashcard",
      title: "Zeitkarten",
      instruction: "Say the German out loud before revealing.",
      items: [
        { front: "um acht Uhr", back: "at eight o'clock", frontAudio: true },
        { front: "am Montag", back: "on Monday", frontAudio: true },
        { front: "im Juli", back: "in July", frontAudio: true },
        { front: "am Abend", back: "in the evening", frontAudio: true },
        { front: "von neun bis fünf", back: "from nine to five", frontAudio: true },
        { front: "seit einem Jahr", back: "for a year (ongoing)", frontAudio: true },
      ],
    },
  ],
};

const perfektEinfuehrung: Lesson = {
  id: "perfekt-einfuehrung",
  title: "Das Perfekt (Einführung)",
  summary: "Talking about the past: haben or sein plus the participle.",
  status: "ready",
  sections: [
    {
      heading: "Die Form",
      blocks: [
        {
          type: "paragraph",
          text: "The Perfekt is the spoken past. It is made of haben or sein in the present, plus the participle at the end of the sentence.",
        },
        {
          type: "example",
          de: "Ich habe gestern Pizza gegessen.",
          en: "I ate pizza yesterday.",
        },
        {
          type: "example",
          de: "Wir sind nach Berlin gefahren.",
          en: "We drove to Berlin.",
        },
        {
          type: "tip",
          text: "The participle closes the sentence, just like a separable prefix: Ich habe gestern Pizza gegessen. This is the Satzklammer again.",
        },
      ],
    },
    {
      heading: "Regelmäßige Verben",
      blocks: [
        {
          type: "paragraph",
          text: "Regular verbs take ge + stem + t. Verbs ending in -ieren skip the ge-.",
        },
        {
          type: "table",
          caption: "Regular participles",
          head: ["Infinitive", "Partizip II"],
          rows: [
            ["machen", "gemacht"],
            ["wohnen", "gewohnt"],
            ["arbeiten", "gearbeitet"],
            ["lernen", "gelernt"],
            ["studieren", "studiert"],
            ["kochen", "gekocht"],
          ],
        },
      ],
    },
    {
      heading: "Unregelmäßige Verben",
      blocks: [
        {
          type: "paragraph",
          text: "Irregular verbs change their vowel and end in -en. The most common ones are worth memorizing now.",
        },
        {
          type: "table",
          caption: "Irregular participles",
          head: ["Infinitive", "Partizip II", "English"],
          rows: [
            ["essen", "gegessen", "to eat"],
            ["trinken", "getrunken", "to drink"],
            ["sehen", "gesehen", "to see"],
            ["schreiben", "geschrieben", "to write"],
            ["sprechen", "gesprochen", "to speak"],
            ["nehmen", "genommen", "to take"],
            ["lesen", "gelesen", "to read"],
            ["sein", "gewesen", "to be"],
            ["haben", "gehabt", "to have"],
          ],
        },
      ],
    },
    {
      heading: "sein oder haben?",
      blocks: [
        {
          type: "paragraph",
          text: "sein builds the Perfekt for movement and change of state. Everything else takes haben.",
        },
        {
          type: "example",
          de: "Ich bin nach Hause gegangen. Er ist aufgestanden.",
          en: "I went home. He got up.",
        },
        {
          type: "example",
          de: "Wir sind nach Berlin gefahren. Sie ist gekommen.",
          en: "We drove to Berlin. She came.",
        },
        {
          type: "tip",
          text: "Movement verbs: gehen, kommen, fahren, fliegen, laufen, aufstehen, bleiben. Everything else: haben. Ich habe gelesen, geschrieben, gegessen.",
        },
      ],
    },
    {
      heading: "Trennbar und untrennbar",
      blocks: [
        {
          type: "table",
          caption: "Participles of prefixed verbs",
          head: ["Infinitive", "Partizip II"],
          rows: [
            ["aufstehen", "aufgestanden"],
            ["einkaufen", "eingekauft"],
            ["fernsehen", "ferngesehen"],
            ["verstehen", "verstanden"],
            ["bezahlen", "bezahlt"],
            ["erzählen", "erzählt"],
          ],
        },
        {
          type: "tip",
          text: "Separable prefixes put ge- in the middle: auf + ge + standen. Inseparable prefixes (be-, ver-, er-) never take ge-: verstanden.",
        },
      ],
    },
  ],
  vocab: [
    { id: "gemacht", de: "gemacht", en: "made, done", part: "participle", audio: true },
    { id: "gegessen", de: "gegessen", en: "eaten", part: "participle", audio: true },
    { id: "getrunken", de: "getrunken", en: "drunk", part: "participle", audio: true },
    { id: "gesehen", de: "gesehen", en: "seen", part: "participle", audio: true },
    { id: "geschrieben", de: "geschrieben", en: "written", part: "participle", audio: true },
    { id: "gesprochen", de: "gesprochen", en: "spoken", part: "participle", audio: true },
    { id: "gefahren", de: "gefahren", en: "driven, traveled", part: "participle", audio: true },
    { id: "gekommen", de: "gekommen", en: "come", part: "participle", audio: true },
    { id: "aufgestanden", de: "aufgestanden", en: "got up", part: "participle", audio: true },
    { id: "verstanden", de: "verstanden", en: "understood", part: "participle", audio: true },
    { id: "gewesen", de: "gewesen", en: "been", part: "participle", audio: true },
    { id: "gehabt", de: "gehabt", en: "had", part: "participle", audio: true },
    { id: "gestern", de: "gestern", en: "yesterday", part: "adverb", audio: true },
    { id: "das-perfekt", de: "das Perfekt", en: "the perfect tense", part: "noun n.", audio: true },
  ],
  exercises: [
    {
      id: "mc-perfekt",
      type: "multiple-choice",
      title: "Das Partizip",
      instruction: "Choose the correct participle.",
      prompt: "Ich habe gestern Pizza ___ (essen).",
      options: ["gegessen", "geesst", "gegesst"],
      correctIndex: 0,
      explain: "essen is irregular: ge + gess + en = gegessen.",
    },
    {
      id: "listening-perfekt",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Wir sind nach Berlin gefahren.",
      options: [
        "Wir sind nach Berlin gefahren.",
        "Wir haben nach Berlin gefahren.",
        "Wir sind nach Berlin geflogen.",
      ],
      correctIndex: 0,
    },
    {
      id: "fill-perfekt",
      type: "fill-blank",
      title: "Das Perfekt",
      instruction: "Complete with the participle and the helper.",
      sentence: "Ich habe gestern Pizza ___ (essen). Wir ___ nach Berlin gefahren.",
      blanks: [
        { answers: ["gegessen"], hint: "participle of essen" },
        { answers: ["sind"], hint: "movement takes sein" },
      ],
    },
    {
      id: "matching-perfekt",
      type: "matching",
      title: "Infinitiv und Partizip",
      instruction: "Match each infinitive to its participle.",
      pairs: [
        ["essen", "gegessen"],
        ["trinken", "getrunken"],
        ["sehen", "gesehen"],
        ["schreiben", "geschrieben"],
        ["aufstehen", "aufgestanden"],
      ],
    },
    {
      id: "word-order-perfekt",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: I ate pizza yesterday.",
      chunks: ["Ich", "habe", "gestern", "Pizza", "gegessen."],
      explain: "The participle closes the sentence bracket.",
    },
    {
      id: "flashcard-perfekt",
      type: "flashcard",
      title: "Partizipkarten",
      instruction: "Say the participle out loud before revealing.",
      items: [
        { front: "essen", back: "gegessen", frontAudio: true },
        { front: "trinken", back: "getrunken", frontAudio: true },
        { front: "sehen", back: "gesehen", frontAudio: true },
        { front: "schreiben", back: "geschrieben", frontAudio: true },
        { front: "aufstehen", back: "aufgestanden", frontAudio: true },
        { front: "verstehen", back: "verstanden", frontAudio: true },
      ],
    },
  ],
};

const perfektMitHaben: Lesson = {
  id: "perfekt-mit-haben",
  title: "Das Perfekt mit haben",
  summary: "Talk about what you did at the weekend: haben + participle.",
  status: "ready",
  sections: [
    {
      heading: "Wann haben?",
      blocks: [
        {
          type: "paragraph",
          text: "Most verbs build their past tense with haben. The rule of thumb: if the action stays with the subject, if nothing moves and nothing changes, haben is the helper. Eating, learning, watching, buying, writing: all haben.",
        },
        {
          type: "table",
          caption: "Verbs with haben",
          head: ["Infinitive", "Participle", "English"],
          rows: [
            ["machen", "gemacht", "to make, do"],
            ["lernen", "gelernt", "to learn"],
            ["spielen", "gespielt", "to play"],
            ["kaufen", "gekauft", "to buy"],
            ["kochen", "gekocht", "to cook"],
            ["arbeiten", "gearbeitet", "to work"],
            ["studieren", "studiert", "to study (at university)"],
            ["essen", "gegessen", "to eat"],
            ["trinken", "getrunken", "to drink"],
            ["sehen", "gesehen", "to see"],
            ["schreiben", "geschrieben", "to write"],
            ["lesen", "gelesen", "to read"],
            ["haben", "gehabt", "to have"],
          ],
        },
        {
          type: "tip",
          text: "The helper haben is conjugated in the present and stands in position two. The participle waits at the very end. Ich habe gestern Pizza gegessen: that is the whole pattern.",
        },
      ],
    },
    {
      heading: "Die Partizipien",
      blocks: [
        {
          type: "paragraph",
          text: "Regular verbs form the participle with ge + stem + t: machen becomes gemacht. Verbs ending in -ieren skip the ge-: studieren becomes studiert. Irregular verbs change their vowel and end in -en: essen becomes gegessen.",
        },
        {
          type: "table",
          caption: "Regular and irregular participles",
          head: ["Regular (ge + stem + t)", "Irregular (ge + stem + en)"],
          rows: [
            ["machen -> gemacht", "essen -> gegessen"],
            ["lernen -> gelernt", "trinken -> getrunken"],
            ["spielen -> gespielt", "sehen -> gesehen"],
            ["kaufen -> gekauft", "schreiben -> geschrieben"],
            ["arbeiten -> gearbeitet", "lesen -> gelesen"],
            ["studieren -> studiert (no ge-)", "nehmen -> genommen"],
          ],
        },
        {
          type: "tip",
          text: "The irregular list is short and worth memorizing as a poem: essen gegessen, trinken getrunken, sehen gesehen, schreiben geschrieben, lesen gelesen, nehmen genommen.",
        },
      ],
    },
    {
      heading: "Am Wochenende",
      blocks: [
        {
          type: "example",
          de: "Ich habe am Wochenende Fußball gespielt.",
          en: "I played football at the weekend.",
        },
        {
          type: "example",
          de: "Wir haben gestern einen Film gesehen.",
          en: "We watched a film yesterday.",
        },
        {
          type: "example",
          de: "Sie hat einen Brief geschrieben.",
          en: "She wrote a letter.",
        },
        {
          type: "tip",
          text: "Time markers for the spoken past: gestern (yesterday), am Wochenende (at the weekend), letzte Woche (last week), heute Morgen (this morning).",
        },
      ],
    },
  ],
  vocab: [
    { id: "gemacht", de: "gemacht", en: "made, done", part: "participle", audio: true },
    { id: "gelernt", de: "gelernt", en: "learned", part: "participle", audio: true },
    { id: "gespielt", de: "gespielt", en: "played", part: "participle", audio: true },
    { id: "gekauft", de: "gekauft", en: "bought", part: "participle", audio: true },
    { id: "gekocht", de: "gekocht", en: "cooked", part: "participle", audio: true },
    { id: "gearbeitet", de: "gearbeitet", en: "worked", part: "participle", audio: true },
    { id: "studiert", de: "studiert", en: "studied", part: "participle", audio: true },
    { id: "gegessen", de: "gegessen", en: "eaten", part: "participle", audio: true },
    { id: "getrunken", de: "getrunken", en: "drunk", part: "participle", audio: true },
    { id: "gesehen", de: "gesehen", en: "seen", part: "participle", audio: true },
    { id: "geschrieben", de: "geschrieben", en: "written", part: "participle", audio: true },
    { id: "gelesen", de: "gelesen", en: "read", part: "participle", audio: true },
    { id: "gehabt", de: "gehabt", en: "had", part: "participle", audio: true },
    { id: "am-wochenende", de: "am Wochenende", en: "at the weekend", part: "phrase", phrase: true, audio: true },
    { id: "letzte-woche", de: "letzte Woche", en: "last week", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "mc-haben",
      type: "multiple-choice",
      title: "Das Partizip",
      instruction: "Choose the correct participle.",
      prompt: "Ich habe gestern einen Film ___ (sehen).",
      options: ["gesehen", "geseht", "sehen"],
      correctIndex: 0,
      explain: "sehen is irregular: gesehen.",
    },
    {
      id: "listening-haben",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Wir haben gestern einen Film gesehen.",
      options: [
        "Wir haben gestern einen Film gesehen.",
        "Wir haben gestern einen Film gekauft.",
        "Wir haben gestern einen Film gespielt.",
      ],
      correctIndex: 0,
    },
    {
      id: "fill-haben",
      type: "fill-blank",
      title: "Das Perfekt",
      instruction: "Complete with the participle.",
      sentence: "Ich habe am Wochenende Fußball ___ (spielen). Sie hat einen Brief ___ (schreiben).",
      blanks: [
        { answers: ["gespielt"], hint: "regular participle" },
        { answers: ["geschrieben"], hint: "irregular participle" },
      ],
    },
    {
      id: "matching-haben",
      type: "matching",
      title: "Infinitiv und Partizip",
      instruction: "Match each infinitive to its participle.",
      pairs: [
        ["machen", "gemacht"],
        ["kaufen", "gekauft"],
        ["essen", "gegessen"],
        ["lesen", "gelesen"],
        ["studieren", "studiert"],
      ],
    },
    {
      id: "word-order-haben",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: I played football at the weekend.",
      chunks: ["Ich", "habe", "am", "Wochenende", "Fußball", "gespielt."],
      explain: "The participle closes the sentence bracket.",
    },
    {
      id: "flashcard-haben",
      type: "flashcard",
      title: "Partizipkarten",
      instruction: "Say the infinitive and the participle out loud.",
      items: [
        { front: "machen", back: "gemacht", frontAudio: true },
        { front: "spielen", back: "gespielt", frontAudio: true },
        { front: "essen", back: "gegessen", frontAudio: true },
        { front: "sehen", back: "gesehen", frontAudio: true },
        { front: "schreiben", back: "geschrieben", frontAudio: true },
        { front: "lesen", back: "gelesen", frontAudio: true },
      ],
    },
  ],
};

const perfektMitSein: Lesson = {
  id: "perfekt-mit-sein",
  title: "Das Perfekt mit sein",
  summary: "Talk about trips, arrivals, and movement in the past.",
  status: "ready",
  sections: [
    {
      heading: "Wann sein?",
      blocks: [
        {
          type: "paragraph",
          text: "A small group of verbs builds its past with sein instead of haben. The rule: movement and change of state. If the subject actually moves from A to B, or if it changes in some way, use sein. Ich bin nach Berlin gefahren: I moved, so sein.",
        },
        {
          type: "table",
          caption: "Verbs with sein",
          head: ["Infinitive", "Participle", "English"],
          rows: [
            ["gehen", "gegangen", "to go (walk)"],
            ["kommen", "gekommen", "to come"],
            ["fahren", "gefahren", "to drive, travel"],
            ["fliegen", "geflogen", "to fly"],
            ["laufen", "gelaufen", "to run"],
            ["aufstehen", "aufgestanden", "to get up"],
            ["bleiben", "geblieben", "to stay"],
            ["sein", "gewesen", "to be"],
            ["werden", "geworden", "to become"],
          ],
        },
        {
          type: "tip",
          text: "The test: did the subject move or change? Ich bin gelaufen: movement, sein. Ich habe gegessen: no movement, haben. If you are unsure, haben is the safe default.",
        },
      ],
    },
    {
      heading: "Die Formen",
      blocks: [
        {
          type: "paragraph",
          text: "sein is conjugated in the present and stands in position two, exactly like haben in the other past. The participle still closes the sentence.",
        },
        {
          type: "example",
          de: "Wir sind nach Berlin gefahren.",
          en: "We drove to Berlin.",
        },
        {
          type: "example",
          de: "Ich bin gestern zu Hause geblieben.",
          en: "I stayed at home yesterday.",
        },
        {
          type: "example",
          de: "Sie ist um sieben Uhr aufgestanden.",
          en: "She got up at seven o'clock.",
        },
        {
          type: "tip",
          text: "Separable verbs keep their pattern with sein too: aufstehen -> aufgestanden. The ge- sits between prefix and stem.",
        },
      ],
    },
    {
      heading: "Reisen und Alltag",
      blocks: [
        {
          type: "example",
          de: "Ich bin nach Hamburg gefahren. Wir sind mit dem Zug gekommen.",
          en: "I drove to Hamburg. We came by train.",
        },
        {
          type: "example",
          de: "Er ist gestern nach Berlin geflogen.",
          en: "He flew to Berlin yesterday.",
        },
        {
          type: "example",
          de: "Wir sind den ganzen Tag gelaufen.",
          en: "We walked all day.",
        },
      ],
    },
  ],
  vocab: [
    { id: "gegangen", de: "gegangen", en: "gone, walked", part: "participle", audio: true },
    { id: "gekommen", de: "gekommen", en: "come", part: "participle", audio: true },
    { id: "gefahren", de: "gefahren", en: "driven, traveled", part: "participle", audio: true },
    { id: "geflogen", de: "geflogen", en: "flown", part: "participle", audio: true },
    { id: "gelaufen", de: "gelaufen", en: "run, walked", part: "participle", audio: true },
    { id: "aufgestanden", de: "aufgestanden", en: "got up", part: "participle", audio: true },
    { id: "geblieben", de: "geblieben", en: "stayed", part: "participle", audio: true },
    { id: "gewesen", de: "gewesen", en: "been", part: "participle", audio: true },
    { id: "geworden", de: "geworden", en: "become", part: "participle", audio: true },
    { id: "zu-hause-bleiben", de: "zu Hause bleiben", en: "to stay at home", part: "phrase", phrase: true, audio: true },
    { id: "den-ganzen-tag", de: "den ganzen Tag", en: "all day", part: "phrase", phrase: true, audio: true },
    { id: "die-bewegung", de: "die Bewegung", en: "the movement", part: "noun f.", plural: "die Bewegungen", audio: true },
  ],
  exercises: [
    {
      id: "mc-sein-hilfsverb",
      type: "multiple-choice",
      title: "Haben oder sein?",
      instruction: "Choose the correct helper.",
      prompt: "Wir ___ nach Berlin gefahren.",
      options: ["sind", "haben", "habe"],
      correctIndex: 0,
      explain: "Movement takes sein: sind gefahren.",
    },
    {
      id: "listening-sein-hilfsverb",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Ich bin gestern zu Hause geblieben.",
      options: [
        "Ich bin gestern zu Hause geblieben.",
        "Ich habe gestern zu Hause gearbeitet.",
        "Ich bin gestern nach Hause gefahren.",
      ],
      correctIndex: 0,
    },
    {
      id: "fill-sein-hilfsverb",
      type: "fill-blank",
      title: "Das Perfekt",
      instruction: "Complete with the helper and the participle.",
      sentence: "Wir ___ nach Berlin gefahren. Ich bin zu Hause ___ (bleiben).",
      blanks: [
        { answers: ["sind"], hint: "movement, wir" },
        { answers: ["geblieben"], hint: "participle of bleiben" },
      ],
    },
    {
      id: "matching-sein-hilfsverb",
      type: "matching",
      title: "Infinitiv und Partizip",
      instruction: "Match each infinitive to its participle.",
      pairs: [
        ["gehen", "gegangen"],
        ["kommen", "gekommen"],
        ["fahren", "gefahren"],
        ["fliegen", "geflogen"],
        ["aufstehen", "aufgestanden"],
      ],
    },
    {
      id: "word-order-sein-hilfsverb",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: We drove to Berlin.",
      chunks: ["Wir", "sind", "nach", "Berlin", "gefahren."],
      explain: "The helper is second; the participle closes.",
    },
    {
      id: "flashcard-sein-hilfsverb",
      type: "flashcard",
      title: "Sein-Karten",
      instruction: "Say the participle out loud before revealing.",
      items: [
        { front: "gehen", back: "gegangen", frontAudio: true },
        { front: "kommen", back: "gekommen", frontAudio: true },
        { front: "fahren", back: "gefahren", frontAudio: true },
        { front: "fliegen", back: "geflogen", frontAudio: true },
        { front: "aufstehen", back: "aufgestanden", frontAudio: true },
        { front: "bleiben", back: "geblieben", frontAudio: true },
      ],
    },
  ],
};

export const tagesablaufUndZeit: Unit = {
  id: "tagesablauf-und-zeit",
  title: "Tagesablauf und Zeit",
  theme: "Daily routine and time",
  lessons: [
    dieUhrzeit,
    wochentageUndMonate,
    meinTagesablauf,
    trennbareVerben,
    derImperativ,
    zeitangaben,
    perfektEinfuehrung,
    perfektMitHaben,
    perfektMitSein,
  ],
};