import type { Lesson } from "../../schema";

export const trennbareVerbenTief: Lesson = {
  id: "trennbare-untrennbare-verben-erklaert",
  title: "Trennbare und untrennbare Verben erklärt",
  summary:
    "The complete system of German verb prefixes: how separable verbs split their prefix to the end of the sentence, how the prefix behaves in the perfect tense and with modal verbs and imperatives, and why inseparable verbs like verstehen and besuchen never split and take no ge-.",
  status: "ready",
  sections: [
    {
      heading: "Was sind trennbare Verben?",
      blocks: [
        {
          type: "paragraph",
          text: "A separable verb is a verb with a prefix that breaks away in the sentence. The conjugated part stands in position 2, and the prefix travels to the very end, like the closing part of the sentence frame. Ich stehe um sieben Uhr auf. The dictionary form keeps them together: aufstehen. In the sentence they split: auf...stehen.",
        },
        {
          type: "gloss",
          de: "Ich stehe um sieben Uhr auf.",
          en: "I get up at seven o'clock.",
          words: [
            { word: "Ich", pos: "Pronomen", en: "I", detail: "Subject" },
            { word: "stehe", pos: "Verb", en: "get up", detail: "Conjugated part, position 2" },
            { word: "um sieben Uhr", pos: "Nomen", en: "at seven", detail: "Time" },
            { word: "auf.", pos: "Verb", en: "up", detail: "Separable prefix, closes the frame" },
          ],
        },
        {
          type: "example",
          de: "Ich kaufe heute ein.",
          en: "I am going shopping today. (einkaufen: ein...kaufen)",
        },
        {
          type: "tip",
          text: "The prefix is the key to the meaning: aufstehen (up + stand = get up), einkaufen (in + buy = shop). The conjugated verb carries the tense; the prefix carries the meaning and sits at the end.",
        },
      ],
    },
    {
      heading: "Die häufigsten trennbaren Präfixe",
      blocks: [
        {
          type: "paragraph",
          text: "Most separable prefixes are themselves small words you already know: ab, an, auf, aus, bei, ein, mit, nach, vor, zu, weg, zurück. Each one twists the meaning of the verb in a predictable way.",
        },
        {
          type: "table",
          caption: "Separable prefixes and their verbs",
          head: ["Prefix", "Example", "Meaning"],
          rows: [
            ["ab-", "abfahren", "to depart"],
            ["an-", "ankommen", "to arrive"],
            ["auf-", "aufstehen", "to get up"],
            ["aus-", "aussteigen", "to get out (of a vehicle)"],
            ["ein-", "einkaufen", "to shop"],
            ["mit-", "mitkommen", "to come along"],
            ["nach-", "nachdenken", "to think over"],
            ["vor-", "vorstellen", "to introduce"],
            ["zu-", "zumachen", "to close"],
            ["weg-", "weggehen", "to go away"],
            ["zurück-", "zurückkommen", "to come back"],
          ],
          rowSpeak: ["abfahren", "ankommen", "aufstehen", "aussteigen", "einkaufen", "mitkommen", "nachdenken", "vorstellen", "zumachen", "weggehen", "zurückkommen"],
        },
        {
          type: "tip",
          text: "Learn the prefix together with the verb and a picture: aufstehen is standing up, aussteigen is stepping out, mitkommen is coming along. The prefix is a small word with its own meaning.",
        },
      ],
    },
    {
      heading: "Trennbare Verben im Perfekt",
      blocks: [
        {
          type: "paragraph",
          text: "In the perfect tense the participle of a separable verb puts ge- between the prefix and the stem: aufstehen becomes aufgestanden, einkaufen becomes eingekauft. The participle closes the sentence frame, and the auxiliary haben or sein stands in position 2.",
        },
        {
          type: "gloss",
          de: "Wir haben gestern eingekauft.",
          en: "We went shopping yesterday.",
          words: [
            { word: "Wir", pos: "Pronomen", en: "we", detail: "Subject" },
            { word: "haben", pos: "Verb", en: "have", detail: "Auxiliary, position 2" },
            { word: "gestern", pos: "Adverb", en: "yesterday", detail: "Time" },
            { word: "eingekauft.", pos: "Verb", en: "shopped", detail: "ge- between ein- and the stem" },
          ],
        },
        {
          type: "table",
          caption: "The participle of separable verbs",
          head: ["Infinitive", "Participle", "Example"],
          rows: [
            ["aufstehen", "aufgestanden", "Ich bin früh aufgestanden."],
            ["anfangen", "angefangen", "Der Kurs hat angefangen."],
            ["einkaufen", "eingekauft", "Wir haben gestern eingekauft."],
            ["mitkommen", "mitgekommen", "Du bist mitgekommen."],
          ],
          rowSpeak: ["Ich bin früh aufgestanden.", "Der Kurs hat begonnen.", "Wir haben gestern eingekauft.", "Du bist mitgekommen."],
        },
        {
          type: "tip",
          text: "Stress the prefix: AUFgestanden, EINgekauft. The ge- always slides in right after the prefix, never before it.",
        },
      ],
    },
    {
      heading: "Trennbare Verben mit Modalverben",
      blocks: [
        {
          type: "paragraph",
          text: "With a modal verb there is no sentence frame to close, because the separable infinitive stands at the end as one whole word. The prefix stays attached: Ich muss um sieben Uhr aufstehen. The modal is the conjugated part in position 2, and the full infinitive closes the sentence.",
        },
        {
          type: "example",
          de: "Ich muss um sieben Uhr aufstehen.",
          en: "I have to get up at seven o'clock.",
        },
        {
          type: "example",
          de: "Wir wollen morgen einkaufen.",
          en: "We want to go shopping tomorrow.",
        },
        {
          type: "tip",
          text: "Compare the two patterns: with a modal the prefix stays glued to the infinitive at the end; without a modal it splits away to the very end of the sentence.",
        },
      ],
    },
    {
      heading: "Der Imperativ trennbarer Verben",
      blocks: [
        {
          type: "paragraph",
          text: "In the imperative the verb comes first and the prefix still closes the sentence: Steh auf! Mach die Tür zu! With the polite Sie form the verb stays in position 1 and the prefix goes to the end: Stehen Sie bitte auf!",
        },
        {
          type: "example",
          de: "Steh auf!",
          en: "Get up!",
        },
        {
          type: "example",
          de: "Mach die Tür zu!",
          en: "Close the door! (zumachen: zu...mach)",
        },
        {
          type: "example",
          de: "Stehen Sie bitte auf!",
          en: "Please stand up! (polite)",
        },
      ],
    },
    {
      heading: "Die untrennbaren Verben: be-, ent-, er-, ge-, ver-, zer-",
      blocks: [
        {
          type: "paragraph",
          text: "Some prefixes never split: be-, ent-, er-, ge-, miss-, ver- and zer-. They stay attached to the verb, and they take no ge- in the perfect tense. verstehen becomes verstanden, not ge-verstanden; besuchen becomes besucht, not ge-besucht. You can always rely on these prefixes being inseparable.",
        },
        {
          type: "gloss",
          de: "Er hat die Frage verstanden.",
          en: "He understood the question.",
          words: [
            { word: "Er", pos: "Pronomen", en: "he", detail: "Subject" },
            { word: "hat", pos: "Verb", en: "has", detail: "Auxiliary, position 2" },
            { word: "die Frage", pos: "Nomen", en: "the question", detail: "Accusative object" },
            { word: "verstanden.", pos: "Verb", en: "understood", detail: "No ge-: the prefix never splits" },
          ],
        },
        {
          type: "table",
          caption: "Inseparable prefixes",
          head: ["Prefix", "Example", "Meaning", "Participle"],
          rows: [
            ["be-", "besuchen", "to visit", "besucht"],
            ["ent-", "entschuldigen", "to excuse", "entschuldigt"],
            ["er-", "erklären", "to explain", "erklärt"],
            ["ge-", "gehören", "to belong", "gehört"],
            ["miss-", "missverstehen", "to misunderstand", "missverstanden"],
            ["ver-", "verstehen", "to understand", "verstanden"],
            ["zer-", "zerbrechen", "to break", "zerbrochen"],
          ],
          rowSpeak: ["besuchen", "entschuldigen", "erklären", "gehören", "missverstehen", "verstehen", "zerbrechen"],
        },
        {
          type: "tip",
          text: "The inseparable prefixes change the meaning of the verb: stehen becomes verstehen (understand), gehen becomes begehen. The perfect tense is the test: verstanden has no ge-, aufgestanden does.",
        },
      ],
    },
    {
      heading: "Vorsicht: Verben mit beiden Formen",
      blocks: [
        {
          type: "paragraph",
          text: "A few verbs change meaning depending on whether the prefix is separable or inseparable. umfahren is inseparable and means to drive around something; umfahren is separable and means to knock something over. übersetzen is inseparable and means to translate; übersetzen is separable and means to ferry across. Context tells you which one you are reading.",
        },
        {
          type: "example",
          de: "Er umfährt die Stadt. (untrennbar)",
          en: "He drives around the city.",
        },
        {
          type: "example",
          de: "Er fährt den Pfosten um. (trennbar)",
          en: "He knocks the post over.",
        },
        {
          type: "example",
          de: "Sie übersetzt den Text. (untrennbar)",
          en: "She translates the text.",
        },
        {
          type: "tip",
          text: "The stress reveals the type: the separable version stresses the prefix (UMfahren), the inseparable version stresses the stem (umFAHRen).",
        },
      ],
    },
  ],
  vocab: [
    { id: "das-trennbare-verb", de: "das trennbare Verb", en: "the separable verb", part: "noun n.", plural: "die trennbaren Verben", audio: true },
    { id: "das-untrennbare-verb", de: "das untrennbare Verb", en: "the inseparable verb", part: "noun n.", plural: "die untrennbaren Verben", audio: true },
    { id: "das-praefix", de: "das Präfix", en: "the prefix", part: "noun n.", plural: "die Präfixe", audio: true },
    { id: "der-verbstamm", de: "der Verbstamm", en: "the verb stem", part: "noun m.", plural: "die Verbstämme", audio: true },
    { id: "das-perfekt", de: "das Perfekt", en: "the perfect tense", part: "noun n.", audio: true },
    { id: "das-partizip-2", de: "das Partizip II", en: "the past participle", part: "noun n.", plural: "die Partizipien", audio: true },
    { id: "das-modalverb", de: "das Modalverb", en: "the modal verb", part: "noun n.", plural: "die Modalverben", audio: true },
    { id: "der-imperativ", de: "der Imperativ", en: "the imperative", part: "noun m.", plural: "die Imperative", audio: true },
    { id: "die-betonung", de: "die Betonung", en: "the stress", part: "noun f.", plural: "die Betonungen", audio: true },
    { id: "aufstehen", de: "aufstehen", en: "to get up", part: "verb", audio: true },
    { id: "einkaufen", de: "einkaufen", en: "to shop", part: "verb", audio: true },
    { id: "verstehen", de: "verstehen", en: "to understand", part: "verb", audio: true },
    { id: "besuchen", de: "besuchen", en: "to visit", part: "verb", audio: true },
    { id: "mitkommen", de: "mitkommen", en: "to come along", part: "verb", audio: true },
  ],
  exercises: [
    {
      id: "ex-tv-trennbar-praefix",
      type: "multiple-choice",
      title: "Übung 1: Trennbare Präfixe",
      instruction: "Which prefix is always separable?",
      prompt: "Welches Präfix ist immer trennbar?",
      options: ["auf-", "ver-", "be-"],
      correctIndex: 0,
      explain: "auf- is separable: aufstehen, aufräumen. ver- and be- never split.",
    },
    {
      id: "ex-tv-untrennbar-praefix",
      type: "multiple-choice",
      title: "Übung 2: Untrennbare Präfixe",
      instruction: "Which prefix is always inseparable?",
      prompt: "Welches Präfix ist immer untrennbar?",
      options: ["er-", "ein-", "auf-"],
      correctIndex: 0,
      explain: "er- is inseparable: erklären, erzählen. ein- and auf- split.",
    },
    {
      id: "ex-tv-satzrahmen",
      type: "word-order",
      title: "Übung 3: Der Satzrahmen",
      instruction: "Build the sentence: I get up at seven o'clock.",
      chunks: ["Ich", "stehe", "um sieben Uhr", "auf."],
      translation: "I get up at seven o'clock.",
      explain: "The separable prefix auf closes the sentence frame.",
    },
    {
      id: "ex-tv-perfekt-sein",
      type: "word-order",
      title: "Übung 4: Perfekt mit sein",
      instruction: "Build the sentence: I got up at seven today.",
      chunks: ["Ich", "bin", "heute", "um sieben Uhr", "aufgestanden."],
      translation: "I got up at seven today.",
      explain: "aufstehen takes sein, and the participle is aufgestanden: ge- sits between auf- and the stem.",
    },
    {
      id: "ex-tv-perfekt-haben",
      type: "word-order",
      title: "Übung 5: Perfekt mit haben",
      instruction: "Build the sentence: We went shopping yesterday.",
      chunks: ["Wir", "haben", "gestern", "eingekauft."],
      translation: "We went shopping yesterday.",
      explain: "einkaufen takes haben; eingekauft closes the frame.",
    },
    {
      id: "ex-tv-modal",
      type: "word-order",
      title: "Übung 6: Mit Modalverb",
      instruction: "Build the sentence: I have to get up at seven o'clock.",
      chunks: ["Ich", "muss", "um sieben Uhr", "aufstehen."],
      translation: "I have to get up at seven o'clock.",
      explain: "With a modal the prefix stays attached: the full infinitive aufstehen closes the sentence.",
    },
    {
      id: "ex-tv-imperativ",
      type: "word-order",
      title: "Übung 7: Der Imperativ",
      instruction: "Build the sentence: Please get up!",
      chunks: ["Steh", "bitte", "auf!"],
      translation: "Please get up!",
      explain: "The imperative opens with the verb and the prefix still closes the sentence.",
    },
    {
      id: "ex-tv-untrennbar-satz",
      type: "word-order",
      title: "Übung 8: Untrennbar im Satz",
      instruction: "Build the sentence: I don't understand the question.",
      chunks: ["Ich", "verstehe", "die Frage", "nicht."],
      translation: "I don't understand the question.",
      explain: "ver- never splits: the whole verb stays in position 2.",
    },
    {
      id: "ex-tv-untrennbar-perfekt",
      type: "word-order",
      title: "Übung 9: Untrennbar im Perfekt",
      instruction: "Build the sentence: He understood the question.",
      chunks: ["Er", "hat", "die Frage", "verstanden."],
      translation: "He understood the question.",
      explain: "Inseparable verbs take no ge- in the participle: verstanden.",
    },
    {
      id: "ex-tv-partizip-trennbar",
      type: "fill-blank",
      title: "Übung 10: Partizip trennbar",
      instruction: "Complete the participle of aufstehen.",
      sentence: "Ich bin heute früh ___.",
      translation: "I got up early today.",
      blanks: [{ answers: ["aufgestanden"] }],
      explain: "aufstehen → aufgestanden: ge- goes between auf- and the stem.",
    },
    {
      id: "ex-tv-partizip-untrennbar",
      type: "fill-blank",
      title: "Übung 11: Partizip untrennbar",
      instruction: "Complete the participle of verstehen.",
      sentence: "Wir haben die Aufgabe ___.",
      translation: "We understood the task.",
      blanks: [{ answers: ["verstanden"] }],
      explain: "ver- is inseparable, so the participle has no ge-: verstanden.",
    },
    {
      id: "ex-tv-praefix-bedeutung",
      type: "matching",
      title: "Übung 12: Präfixe und Verben",
      instruction: "Match each verb with its meaning.",
      pairs: [
        ["abfahren", "to depart"],
        ["ankommen", "to arrive"],
        ["aufstehen", "to get up"],
        ["aussteigen", "to get out"],
        ["einkaufen", "to shop"],
        ["mitkommen", "to come along"],
        ["verstehen", "to understand"],
        ["besuchen", "to visit"],
      ],
      explain: "The prefix carries the meaning: ab- (away), an- (arrival), auf- (up), ver- (inseparable).",
    },
    {
      id: "ex-tv-hoeren",
      type: "listening",
      title: "Übung 13: Hörverstehen",
      instruction: "Listen and choose the sentence you hear.",
      prompt: "Wir haben gestern eingekauft.",
      options: [
        "Wir haben gestern eingekauft.",
        "Wir sind gestern eingekauft.",
        "Wir haben gestern gekauft.",
      ],
      correctIndex: 0,
      explain: "einkaufen takes haben, and the participle is eingekauft, not gekauft.",
    },
    {
      id: "ex-tv-karten",
      type: "flashcard",
      title: "Übung 14: Die Verben",
      instruction: "Say the German verb before revealing the meaning.",
      items: [
        { front: "aufstehen", back: "to get up", frontAudio: true },
        { front: "anfangen", back: "to begin", frontAudio: true },
        { front: "einkaufen", back: "to shop", frontAudio: true },
        { front: "mitkommen", back: "to come along", frontAudio: true },
        { front: "zumachen", back: "to close", frontAudio: true },
        { front: "verstehen", back: "to understand", frontAudio: true },
        { front: "besuchen", back: "to visit", frontAudio: true },
        { front: "erklären", back: "to explain", frontAudio: true },
      ],
    },
  ],
};