import type { Lesson, Unit } from "../../schema";

export const meinZuhause: Lesson = {
  id: "mein-zuhause",
  title: "Mein Zuhause",
  summary:
    "The complete home vocabulary for A1: the rooms of the house, the furniture, the grammar of living and sleeping, and the classic errors.",
  status: "ready",
  sections: [
    {
      heading: "Die Wohnung und das Haus",
      blocks: [
        {
          type: "paragraph",
          text: "The home has two forms: das Haus (the house, a whole building) and die Wohnung (the apartment, rooms in a building). You live (wohnen) in a house or an apartment, and the question about your home is: Wo wohnst du? (Where do you live?).",
        },
        {
          type: "table",
          caption: "Home basics",
          head: ["German", "English", "Plural"],
          rows: [
            ["das Haus", "the house", "die Häuser"],
            ["die Wohnung", "the apartment", "die Wohnungen"],
            ["die Etage / der Stock", "the floor", "die Etagen"],
            ["das Stockwerk", "the storey", "die Stockwerke"],
            ["der Balkon", "the balcony", "die Balkone"],
            ["der Garten", "the garden", "die Gärten"],
            ["die Garage", "the garage", "die Garagen"],
            ["der Keller", "the cellar", "die Keller"],
          ],
        },
        {
          type: "example",
          de: "Ich wohne in einer Wohnung im zweiten Stock. Die Wohnung hat einen Balkon und die Garage ist unten.",
          en: "I live in a flat on the second floor. The flat has a balcony and the garage is downstairs.",
        },
        {
          type: "tip",
          text: "wohnen uses in + dative: Ich wohne in einer Wohnung. The stock phrase: im Erdgeschoss, im ersten Stock, im zweiten Stock.",
        },
      ],
    },
    {
      heading: "Die Zimmer",
      blocks: [
        {
          type: "paragraph",
          text: "The rooms are mostly neuter with -zimmer: das Schlafzimmer (bedroom), das Wohnzimmer (living room), das Kinderzimmer (children's room), das Badezimmer (bathroom). Two special words: die Küche (kitchen, feminine) and der Flur (hallway, masculine).",
        },
        {
          type: "table",
          caption: "The rooms",
          head: ["German", "English", "Plural"],
          rows: [
            ["das Schlafzimmer", "the bedroom", "die Schlafzimmer"],
            ["das Wohnzimmer", "the living room", "die Wohnzimmer"],
            ["das Kinderzimmer", "the children's room", "die Kinderzimmer"],
            ["das Badezimmer / das Bad", "the bathroom", "die Badezimmer"],
            ["die Küche", "the kitchen", "die Küchen"],
            ["der Flur", "the hallway", "die Flure"],
            ["das Arbeitszimmer", "the study", "die Arbeitszimmer"],
            ["das Esszimmer", "the dining room", "die Esszimmer"],
          ],
        },
        {
          type: "example",
          de: "Unsere Wohnung hat drei Zimmer: ein Wohnzimmer, ein Schlafzimmer und ein Kinderzimmer. Die Küche ist klein, aber das Badezimmer ist modern.",
          en: "Our flat has three rooms: a living room, a bedroom and a children's room. The kitchen is small, but the bathroom is modern.",
        },
        {
          type: "tip",
          text: "The room formula: Wie viele Zimmer hat die Wohnung? Die Wohnung hat drei Zimmer. The neuter -zimmer words never change in the plural.",
        },
      ],
    },
    {
      heading: "Die Möbel",
      blocks: [
        {
          type: "paragraph",
          text: "Furniture follows the same three-gender system: der Tisch (table, m.), der Stuhl (chair, m.), das Sofa (sofa, n.), das Bett (bed, n.), die Lampe (lamp, f.). With furniture you use stehen (to stand) for things and liegen (to lie) for flat things, plus in + dative for location.",
        },
        {
          type: "table",
          caption: "Furniture",
          head: ["German", "English", "Plural"],
          rows: [
            ["der Tisch", "the table", "die Tische"],
            ["der Stuhl", "the chair", "die Stühle"],
            ["das Sofa", "the sofa", "die Sofas"],
            ["das Bett", "the bed", "die Betten"],
            ["der Schrank", "the wardrobe, cupboard", "die Schränke"],
            ["das Regal", "the shelf", "die Regale"],
            ["die Lampe", "the lamp", "die Lampen"],
            ["der Sessel", "the armchair", "die Sessel"],
            ["der Teppich", "the carpet", "die Teppiche"],
            ["der Spiegel", "the mirror", "die Spiegel"],
          ],
        },
        {
          type: "example",
          de: "Das Sofa steht im Wohnzimmer. Die Lampe steht auf dem Tisch. Das Buch liegt auf dem Bett.",
          en: "The sofa stands in the living room. The lamp stands on the table. The book lies on the bed.",
        },
        {
          type: "tip",
          text: "stehen is for standing objects, liegen for flat ones: Die Lampe steht, das Buch liegt. Position takes in/auf + dative.",
        },
      ],
    },
    {
      heading: "In der Küche",
      blocks: [
        {
          type: "paragraph",
          text: "The kitchen holds the appliances and the classic exam room-description: der Herd (stove), der Kühlschrank (fridge), der Geschirrspüler (dishwasher), die Spüle (sink), der Backofen (oven). The kitchen words are mostly masculine because they are things made with -er or -schrank.",
        },
        {
          type: "table",
          caption: "The kitchen",
          head: ["German", "English"],
          rows: [
            ["der Herd", "the stove"],
            ["der Backofen", "the oven"],
            ["der Kühlschrank", "the fridge"],
            ["die Spüle", "the sink"],
            ["der Geschirrspüler", "the dishwasher"],
            ["die Mikrowelle", "the microwave"],
            ["der Wasserkocher", "the kettle"],
          ],
        },
        {
          type: "tip",
          text: "The kitchen room description is an exam standard: In der Küche stehen der Herd, der Kühlschrank und der Geschirrspüler.",
        },
      ],
    },
    {
      heading: "Wohnen und die Verben",
      blocks: [
        {
          type: "paragraph",
          text: "The three home verbs: wohnen (to live, permanent), leben (to live, existence), and liegen/stehen for objects. The questions: Wo wohnst du? Wo wohnen Sie? The answer pattern: Ich wohne in + city (in Berlin), or in + type of home (in einer Wohnung), or auf dem Land (in the country), or im Zentrum (in the centre).",
        },
        {
          type: "table",
          caption: "Home verbs",
          head: ["Verb", "English", "Example"],
          rows: [
            ["wohnen", "to live (residence)", "Ich wohne in Berlin."],
            ["leben", "to live (existence)", "Er lebt mit seiner Familie."],
            ["mieten", "to rent", "Wir mieten eine Wohnung."],
            ["kaufen", "to buy", "Sie kaufen ein Haus."],
            ["einziehen", "to move in", "Wir ziehen nächste Woche ein."],
          ],
        },
        {
          type: "example",
          de: "Ich wohne mit meiner Familie in einem Haus auf dem Land. Wir haben einen großen Garten und zwei Balkone.",
          en: "I live with my family in a house in the countryside. We have a big garden and two balconies.",
        },
        {
          type: "tip",
          text: "wohnen takes in + dative: in einem Haus, in einer Wohnung, in Berlin. The two variants: in der Stadt (in the city) and auf dem Land (in the countryside).",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: confusing Haus and Wohnung, wrong prepositions for living, and using sein instead of haben with the rooms.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["Haus/Wohnung mix", "Ich wohne in einem Wohnung.", "Ich wohne in einer Wohnung.", "Wohnung is feminine"],
            ["wrong preposition", "Ich wohne an Berlin.", "Ich wohne in Berlin.", "living takes in"],
            ["missing article", "Ich wohne in Zentrum.", "Ich wohne im Zentrum.", "im = in dem"],
            ["wrong gender", "die Haus", "das Haus", "Haus is neuter"],
            ["stehen/liegen mix", "Das Buch steht auf dem Bett.", "Das Buch liegt auf dem Bett.", "flat things lie"],
          ],
        },
        {
          type: "tip",
          text: "The home topic is a script: describe the building, the rooms, the furniture, then the location. Learn the prepositions in/auf/unter with the dative and the home is solved.",
        },
      ],
    },
  ],
  vocab: [
    { id: "das-haus", de: "das Haus", en: "the house", part: "noun n.", plural: "die Häuser", audio: true },
    { id: "die-wohnung", de: "die Wohnung", en: "the apartment", part: "noun f.", plural: "die Wohnungen", audio: true },
    { id: "der-balkon", de: "der Balkon", en: "the balcony", part: "noun m.", plural: "die Balkone", audio: true },
    { id: "der-garten", de: "der Garten", en: "the garden", part: "noun m.", plural: "die Gärten", audio: true },
    { id: "die-garage", de: "die Garage", en: "the garage", part: "noun f.", plural: "die Garagen", audio: true },
    { id: "der-keller", de: "der Keller", en: "the cellar", part: "noun m.", plural: "die Keller", audio: true },
    { id: "das-schlafzimmer", de: "das Schlafzimmer", en: "the bedroom", part: "noun n.", plural: "die Schlafzimmer", audio: true },
    { id: "das-wohnzimmer", de: "das Wohnzimmer", en: "the living room", part: "noun n.", plural: "die Wohnzimmer", audio: true },
    { id: "das-kinderzimmer", de: "das Kinderzimmer", en: "the children's room", part: "noun n.", plural: "die Kinderzimmer", audio: true },
    { id: "das-badezimmer", de: "das Badezimmer", en: "the bathroom", part: "noun n.", plural: "die Badezimmer", audio: true },
    { id: "die-kueche", de: "die Küche", en: "the kitchen", part: "noun f.", plural: "die Küchen", audio: true },
    { id: "der-flur", de: "der Flur", en: "the hallway", part: "noun m.", plural: "die Flure", audio: true },
    { id: "das-esszimmer", de: "das Esszimmer", en: "the dining room", part: "noun n.", plural: "die Esszimmer", audio: true },
    { id: "das-arbeitszimmer", de: "das Arbeitszimmer", en: "the study", part: "noun n.", plural: "die Arbeitszimmer", audio: true },
    { id: "der-tisch", de: "der Tisch", en: "the table", part: "noun m.", plural: "die Tische", audio: true },
    { id: "der-stuhl", de: "der Stuhl", en: "the chair", part: "noun m.", plural: "die Stühle", audio: true },
    { id: "das-sofa", de: "das Sofa", en: "the sofa", part: "noun n.", plural: "die Sofas", audio: true },
    { id: "das-bett", de: "das Bett", en: "the bed", part: "noun n.", plural: "die Betten", audio: true },
    { id: "der-schrank", de: "der Schrank", en: "the wardrobe", part: "noun m.", plural: "die Schränke", audio: true },
    { id: "das-regal", de: "das Regal", en: "the shelf", part: "noun n.", plural: "die Regale", audio: true },
    { id: "die-lampe", de: "die Lampe", en: "the lamp", part: "noun f.", plural: "die Lampen", audio: true },
    { id: "der-sessel", de: "der Sessel", en: "the armchair", part: "noun m.", plural: "die Sessel", audio: true },
    { id: "der-teppich", de: "der Teppich", en: "the carpet", part: "noun m.", plural: "die Teppiche", audio: true },
    { id: "der-spiegel", de: "der Spiegel", en: "the mirror", part: "noun m.", plural: "die Spiegel", audio: true },
    { id: "der-herd", de: "der Herd", en: "the stove", part: "noun m.", plural: "die Herde", audio: true },
    { id: "der-kuehlschrank", de: "der Kühlschrank", en: "the fridge", part: "noun m.", plural: "die Kühlschränke", audio: true },
    { id: "die-spuele", de: "die Spüle", en: "the sink", part: "noun f.", plural: "die Spülen", audio: true },
    { id: "der-geschirrspueler", de: "der Geschirrspüler", en: "the dishwasher", part: "noun m.", plural: "die Geschirrspüler", audio: true },
    { id: "wohnen", de: "wohnen", en: "to live (residence)", part: "verb", audio: true },
    { id: "leben", de: "leben", en: "to live (existence)", part: "verb", audio: true },
    { id: "mieten", de: "mieten", en: "to rent", part: "verb", audio: true },
    { id: "einziehen", de: "einziehen", en: "to move in", part: "verb", audio: true },
    { id: "wo-wohnst-du", de: "Wo wohnst du?", en: "Where do you live?", part: "phrase", phrase: true, audio: true },
    { id: "ich-wohne-in", de: "Ich wohne in Berlin.", en: "I live in Berlin.", part: "phrase", phrase: true, audio: true },
    { id: "im-zentrum", de: "im Zentrum", en: "in the centre", part: "phrase", phrase: true, audio: true },
    { id: "auf-dem-land", de: "auf dem Land", en: "in the countryside", part: "phrase", phrase: true, audio: true },
    { id: "im-ersten-stock", de: "im ersten Stock", en: "on the first floor", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-haus-wohnung",
      type: "matching",
      title: "Übung 1: Das Haus und die Wohnung",
      instruction: "Match each home word to its meaning.",
      pairs: [
        ["das Haus", "the house"],
        ["die Wohnung", "the apartment"],
        ["der Balkon", "the balcony"],
        ["der Garten", "the garden"],
        ["der Keller", "the cellar"],
        ["die Garage", "the garage"],
      ],
    },
    {
      id: "ex-zimmer",
      type: "matching",
      title: "Übung 2: Die Zimmer",
      instruction: "Match each room to its meaning.",
      pairs: [
        ["das Schlafzimmer", "the bedroom"],
        ["das Wohnzimmer", "the living room"],
        ["die Küche", "the kitchen"],
        ["das Badezimmer", "the bathroom"],
        ["der Flur", "the hallway"],
        ["das Arbeitszimmer", "the study"],
      ],
    },
    {
      id: "ex-furniture",
      type: "matching",
      title: "Übung 3: Die Möbel",
      instruction: "Match each furniture word to its meaning.",
      pairs: [
        ["der Tisch", "the table"],
        ["der Stuhl", "the chair"],
        ["das Sofa", "the sofa"],
        ["das Bett", "the bed"],
        ["der Schrank", "the wardrobe"],
        ["die Lampe", "the lamp"],
      ],
    },
    {
      id: "ex-genus",
      type: "multiple-choice",
      title: "Übung 4: Das Genus",
      instruction: "Choose the correct article.",
      prompt: "___ Küche ist modern.",
      options: ["Die", "Das", "Der"],
      correctIndex: 0,
      explain: "Küche is feminine: die Küche.",
    },
    {
      id: "ex-genus-2",
      type: "multiple-choice",
      title: "Übung 5: Das Genus",
      instruction: "Choose the correct article.",
      prompt: "___ Sofa steht im Wohnzimmer.",
      options: ["Das", "Der", "Die"],
      correctIndex: 0,
      explain: "Sofa is neuter: das Sofa.",
    },
    {
      id: "ex-wohnen",
      type: "multiple-choice",
      title: "Übung 6: Wohnen",
      instruction: "Choose the correct sentence.",
      prompt: "I live in an apartment.",
      options: ["Ich wohne in einer Wohnung.", "Ich wohne in einem Wohnung.", "Ich wohne auf einer Wohnung."],
      correctIndex: 0,
      explain: "Wohnung is feminine: in einer Wohnung.",
    },
    {
      id: "ex-stock",
      type: "multiple-choice",
      title: "Übung 7: Der Stock",
      instruction: "Choose the correct phrase.",
      prompt: "I live on the first floor.",
      options: ["Ich wohne im ersten Stock.", "Ich wohne im erste Stock.", "Ich wohne im erst Stock."],
      correctIndex: 0,
      explain: "The floor phrase: im ersten Stock.",
    },
    {
      id: "ex-liegen",
      type: "multiple-choice",
      title: "Übung 8: stehen oder liegen",
      instruction: "Choose the correct verb.",
      prompt: "Das Buch ___ auf dem Bett.",
      options: ["liegt", "steht", "sitzt"],
      correctIndex: 0,
      explain: "Flat things lie: liegen.",
    },
    {
      id: "ex-kueche",
      type: "multiple-choice",
      title: "Übung 9: Die Küche",
      instruction: "Choose the correct word.",
      prompt: "The fridge.",
      options: ["der Kühlschrank", "der Herd", "der Geschirrspüler"],
      correctIndex: 0,
      explain: "The fridge is der Kühlschrank.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 10: Hören",
      instruction: "Play the audio and pick the room you heard.",
      prompt: "das Schlafzimmer",
      options: ["das Schlafzimmer", "das Wohnzimmer", "das Kinderzimmer"],
      correctIndex: 0,
      explain: "The room heard: bedroom.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 11: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Ich wohne in einem Haus mit Garten.",
      options: ["Ich wohne in einem Haus mit Garten.", "Ich wohne in einer Wohnung mit Balkon.", "Ich wohne in einem Haus mit Balkon."],
      correctIndex: 0,
      explain: "The home sentence heard.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 12: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Ich wohne in Berlin.", "Ich wohne an Berlin.", "Ich wohne auf Berlin."],
      correctIndex: 0,
      explain: "Cities take in.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 13: Der Satz",
      instruction: "Build the sentence: We live in a house.",
      chunks: ["Wir", "wohnen", "in", "einem", "Haus."], translation: "We live in a house.",
      explain: "wohnen in + dative.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 14: Der Satz",
      instruction: "Build the sentence: The apartment has three rooms.",
      chunks: ["Die", "Wohnung", "hat", "drei", "Zimmer."], translation: "The flat has three rooms.",
      explain: "The room count with haben.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 15: Hauskarten",
      instruction: "Say the German with the article out loud.",
      items: [
        { front: "das Haus", back: "the house", frontAudio: true },
        { front: "die Wohnung", back: "the apartment", frontAudio: true },
        { front: "das Schlafzimmer", back: "the bedroom", frontAudio: true },
        { front: "die Küche", back: "the kitchen", frontAudio: true },
        { front: "das Badezimmer", back: "the bathroom", frontAudio: true },
        { front: "der Tisch", back: "the table", frontAudio: true },
        { front: "das Sofa", back: "the sofa", frontAudio: true },
        { front: "das Bett", back: "the bed", frontAudio: true },
        { front: "der Schrank", back: "the wardrobe", frontAudio: true },
        { front: "der Kühlschrank", back: "the fridge", frontAudio: true },
        { front: "Ich wohne in Berlin.", back: "I live in Berlin.", frontAudio: true },
        { front: "Wo wohnst du?", back: "Where do you live?", frontAudio: true },
      ],
    },
  ],
};

export const woWohntWas: Lesson = {
  id: "wo-wohnt-was",
  title: "Wo wohnt was?",
  summary:
    "Where things live: rooms, furniture and their positions with in, auf, unter, neben, vor, hinter and the dative. The complete placement system for A1.",
  status: "ready",
  sections: [
    {
      heading: "Die Positionsfrage: Wo?",
      blocks: [
        {
          type: "paragraph",
          text: "The question Wo? (Where?) asks for a position and the answer uses in + dative: Wo ist die Lampe? Die Lampe ist auf dem Tisch. The position prepositions: in (in), auf (on), unter (under), neben (next to), vor (in front of), hinter (behind), zwischen (between). With Wo? they all take the dative.",
        },
        {
          type: "table",
          caption: "The position prepositions",
          head: ["Preposition", "English", "Dative example"],
          rows: [
            ["in", "in", "in der Küche"],
            ["auf", "on", "auf dem Tisch"],
            ["unter", "under", "unter dem Bett"],
            ["neben", "next to", "neben dem Schrank"],
            ["vor", "in front of", "vor dem Haus"],
            ["hinter", "behind", "hinter der Tür"],
            ["zwischen", "between", "zwischen den Stühlen"],
          ],
        },
        {
          type: "example",
          de: "Das Sofa steht vor dem Tisch. Die Lampe hängt über dem Tisch. Die Katze liegt unter dem Sofa.",
          en: "The sofa stands in front of the table. The lamp hangs above the table. The cat lies under the sofa.",
        },
        {
          type: "tip",
          text: "Wo? + position = dative. The pair test: Wo (position) takes the dative, Wohin (direction) takes the accusative. This lesson is about Wo?",
        },
      ],
    },
    {
      heading: "Die zusammengesetzten Präpositionen",
      blocks: [
        {
          type: "paragraph",
          text: "Three prepositions combine with the article into one word: in + dem = im, an + dem = am, auf + das = aufs. The im form is essential for rooms: im Wohnzimmer, im Schlafzimmer, im Bad, im Erdgeschoss.",
        },
        {
          type: "table",
          caption: "Contracted prepositions",
          head: ["Full form", "Contracted", "Example"],
          rows: [
            ["in + dem", "im", "im Wohnzimmer"],
            ["an + dem", "am", "am Fenster"],
            ["in + das", "ins", "ins Wohnzimmer (direction)"],
            ["an + das", "ans", "ans Fenster"],
            ["auf + das", "aufs", "aufs Sofa (direction)"],
          ],
        },
        {
          type: "example",
          de: "Das Bild hängt an der Wand. Der Schrank steht im Schlafzimmer. Die Blumen stehen auf dem Fensterbrett.",
          en: "The picture hangs on the wall. The cupboard stands in the bedroom. The flowers stand on the windowsill.",
        },
        {
          type: "tip",
          text: "im is the most common contracted form. In the exam you hear: Wo ist der Schlüssel? Er ist im Wohnzimmer.",
        },
      ],
    },
    {
      heading: "Die Verben der Position",
      blocks: [
        {
          type: "paragraph",
          text: "Three verbs describe where things are: stehen (to stand) for upright objects, liegen (to lie) for flat objects, hängen (to hang) for things on walls and hooks. The verb follows the shape of the object: Der Tisch steht, das Buch liegt, das Bild hängt.",
        },
        {
          type: "table",
          caption: "The position verbs",
          head: ["Verb", "English", "Typical subject"],
          rows: [
            ["stehen", "to stand", "Tisch, Schrank, Sofa, Lampe"],
            ["liegen", "to lie", "Buch, Teppich, Schlüssel"],
            ["hängen", "to hang", "Bild, Spiegel, Jacke"],
          ],
        },
        {
          type: "example",
          de: "Der Tisch steht in der Küche. Der Teppich liegt im Wohnzimmer. Der Spiegel hängt im Flur.",
          en: "The table stands in the kitchen. The carpet lies in the living room. The mirror hangs in the hallway.",
        },
        {
          type: "tip",
          text: "The object decides the verb: something tall stands, something flat lies, something on the wall hangs. This is an exam favourite.",
        },
      ],
    },
    {
      heading: "Die Frage nach dem Wohnort",
      blocks: [
        {
          type: "paragraph",
          text: "The question Wo wohnst du? (Where do you live?) asks for your home. The answers: in der Stadt (in the city), auf dem Land (in the countryside), im Zentrum (in the centre), am Stadtrand (on the edge of town). The larger answers: in einem Haus, in einer Wohnung.",
        },
        {
          type: "table",
          caption: "Where do you live?",
          head: ["German", "English"],
          rows: [
            ["Ich wohne in der Stadt.", "I live in the city."],
            ["Ich wohne auf dem Land.", "I live in the countryside."],
            ["Ich wohne im Zentrum.", "I live in the centre."],
            ["Ich wohne am Stadtrand.", "I live on the edge of town."],
            ["Ich wohne in einem Haus.", "I live in a house."],
            ["Ich wohne in einer Wohnung.", "I live in an apartment."],
          ],
        },
        {
          type: "example",
          de: "Wo wohnst du? Ich wohne im Zentrum, in einer Wohnung im dritten Stock.",
          en: "Where do you live? I live in the centre, in a flat on the third floor.",
        },
        {
          type: "tip",
          text: "The pattern: in der Stadt, auf dem Land, im Zentrum, am Stadtrand. Four fixed phrases, four prepositions, four datives.",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: using the accusative after Wo?, forgetting the contracted im, and mixing stehen with liegen.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["wrong case after Wo?", "Die Lampe ist auf den Tisch.", "Die Lampe ist auf dem Tisch.", "Wo? takes the dative"],
            ["missing im", "Ich wohne in Wohnzimmer.", "Ich wohne im Wohnzimmer.", "in + dem = im"],
            ["stehen/liegen mix", "Der Teppich steht.", "Der Teppich liegt.", "flat objects lie"],
            ["wrong preposition", "Die Lampe ist über dem Tisch? Nein.", "Die Lampe ist auf dem Tisch.", "use the right position"],
            ["article loss", "Das Sofa steht vor Tisch.", "Das Sofa steht vor dem Tisch.", "the preposition needs the article"],
          ],
        },
        {
          type: "tip",
          text: "The whole system: Wo? + dative + position verb. Ask the exam question first: Wo ist ...? Then answer with the verb and the dative preposition.",
        },
      ],
    },
  ],
  vocab: [
    { id: "die-wand", de: "die Wand", en: "the wall", part: "noun f.", plural: "die Wände", audio: true },
    { id: "der-boden", de: "der Boden", en: "the floor", part: "noun m.", plural: "die Böden", audio: true },
    { id: "die-decke", de: "die Decke", en: "the ceiling", part: "noun f.", plural: "die Decken", audio: true },
    { id: "das-fenster", de: "das Fenster", en: "the window", part: "noun n.", plural: "die Fenster", audio: true },
    { id: "die-tuer", de: "die Tür", en: "the door", part: "noun f.", plural: "die Türen", audio: true },
    { id: "das-regal", de: "das Regal", en: "the shelf", part: "noun n.", plural: "die Regale", audio: true },
    { id: "das-bild", de: "das Bild", en: "the picture", part: "noun n.", plural: "die Bilder", audio: true },
    { id: "der-schluessel", de: "der Schlüssel", en: "the key", part: "noun m.", plural: "die Schlüssel", audio: true },
    { id: "stehen", de: "stehen", en: "to stand", part: "verb", audio: true },
    { id: "liegen", de: "liegen", en: "to lie", part: "verb", audio: true },
    { id: "haengen", de: "hängen", en: "to hang", part: "verb", audio: true },
    { id: "sitzen", de: "sitzen", en: "to sit", part: "verb", audio: true },
    { id: "auf-dem-tisch", de: "auf dem Tisch", en: "on the table", part: "phrase", phrase: true, audio: true },
    { id: "unter-dem-bett", de: "unter dem Bett", en: "under the bed", part: "phrase", phrase: true, audio: true },
    { id: "neben-dem-schrank", de: "neben dem Schrank", en: "next to the wardrobe", part: "phrase", phrase: true, audio: true },
    { id: "vor-dem-haus", de: "vor dem Haus", en: "in front of the house", part: "phrase", phrase: true, audio: true },
    { id: "hinter-der-tuer", de: "hinter der Tür", en: "behind the door", part: "phrase", phrase: true, audio: true },
    { id: "an-der-wand", de: "an der Wand", en: "on the wall", part: "phrase", phrase: true, audio: true },
    { id: "im-wohnzimmer", de: "im Wohnzimmer", en: "in the living room", part: "phrase", phrase: true, audio: true },
    { id: "wo-ist-der-schluessel", de: "Wo ist der Schlüssel?", en: "Where is the key?", part: "phrase", phrase: true, audio: true },
    { id: "in-der-stadt", de: "in der Stadt", en: "in the city", part: "phrase", phrase: true, audio: true },
    { id: "am-stadtrand", de: "am Stadtrand", en: "on the edge of town", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-praepositionen",
      type: "matching",
      title: "Übung 1: Die Präpositionen",
      instruction: "Match each preposition to its meaning.",
      pairs: [
        ["auf", "on"],
        ["unter", "under"],
        ["neben", "next to"],
        ["vor", "in front of"],
        ["hinter", "behind"],
        ["zwischen", "between"],
      ],
    },
    {
      id: "ex-dativ",
      type: "multiple-choice",
      title: "Übung 2: Der Dativ",
      instruction: "Choose the correct phrase.",
      prompt: "Die Lampe ist ___ Tisch. (on the table)",
      options: ["auf dem", "auf den", "auf der"],
      correctIndex: 0,
      explain: "Wo? takes the dative: auf dem Tisch.",
    },
    {
      id: "ex-dativ-2",
      type: "multiple-choice",
      title: "Übung 3: Der Dativ",
      instruction: "Choose the correct phrase.",
      prompt: "Die Katze ist ___ Bett. (under the bed)",
      options: ["unter dem", "unter den", "unter die"],
      correctIndex: 0,
      explain: "Wo? takes the dative: unter dem Bett.",
    },
    {
      id: "ex-im",
      type: "multiple-choice",
      title: "Übung 4: im",
      instruction: "Choose the correct phrase.",
      prompt: "The key is in the living room.",
      options: ["im Wohnzimmer", "in Wohnzimmer", "in das Wohnzimmer"],
      correctIndex: 0,
      explain: "in + dem = im.",
    },
    {
      id: "ex-stehen-liegen",
      type: "matching",
      title: "Übung 5: stehen oder liegen",
      instruction: "Match each object to its verb.",
      pairs: [
        ["der Tisch", "steht"],
        ["das Buch", "liegt"],
        ["der Schrank", "steht"],
        ["der Teppich", "liegt"],
        ["das Bild", "hängt"],
        ["der Spiegel", "hängt"],
      ],
    },
    {
      id: "ex-verb",
      type: "multiple-choice",
      title: "Übung 6: Das richtige Verb",
      instruction: "Choose the correct verb.",
      prompt: "Der Teppich ___ im Wohnzimmer.",
      options: ["liegt", "steht", "hängt"],
      correctIndex: 0,
      explain: "Flat objects lie.",
    },
    {
      id: "ex-verb-2",
      type: "multiple-choice",
      title: "Übung 7: Das richtige Verb",
      instruction: "Choose the correct verb.",
      prompt: "Das Bild ___ an der Wand.",
      options: ["hängt", "steht", "liegt"],
      correctIndex: 0,
      explain: "Pictures hang.",
    },
    {
      id: "ex-wohnen",
      type: "multiple-choice",
      title: "Übung 8: Wo wohnst du?",
      instruction: "Choose the correct sentence.",
      prompt: "I live in the centre.",
      options: ["Ich wohne im Zentrum.", "Ich wohne in Zentrum.", "Ich wohne am Zentrum."],
      correctIndex: 0,
      explain: "The centre phrase: im Zentrum.",
    },
    {
      id: "ex-wohnen-2",
      type: "multiple-choice",
      title: "Übung 9: Wo wohnst du?",
      instruction: "Choose the correct sentence.",
      prompt: "I live in the countryside.",
      options: ["Ich wohne auf dem Land.", "Ich wohne in dem Land.", "Ich wohne auf das Land."],
      correctIndex: 0,
      explain: "The countryside phrase: auf dem Land.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 10: Hören",
      instruction: "Play the audio and pick the phrase you heard.",
      prompt: "auf dem Tisch",
      options: ["auf dem Tisch", "unter dem Tisch", "neben dem Tisch"],
      correctIndex: 0,
      explain: "The position heard: on the table.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 11: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Der Schlüssel liegt auf dem Tisch.",
      options: ["Der Schlüssel liegt auf dem Tisch.", "Der Schlüssel steht auf dem Tisch.", "Der Schlüssel hängt auf dem Tisch."],
      correctIndex: 0,
      explain: "The key sentence heard.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 12: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Das Sofa steht vor dem Tisch.", "Das Sofa steht vor den Tisch.", "Das Sofa steht vor die Tisch."],
      correctIndex: 0,
      explain: "Wo? takes the dative: vor dem Tisch.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 13: Der Satz",
      instruction: "Build the sentence: The lamp is on the table.",
      chunks: ["Die", "Lampe", "ist", "auf", "dem", "Tisch."], translation: "The lamp is on the table.",
      explain: "Position with the dative.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 14: Der Satz",
      instruction: "Build the sentence: I live in the city.",
      chunks: ["Ich", "wohne", "in", "der", "Stadt."], translation: "I live in the city.",
      explain: "Living in the city: in der Stadt.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 15: Positionskarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "auf dem Tisch", back: "on the table", frontAudio: true },
        { front: "unter dem Bett", back: "under the bed", frontAudio: true },
        { front: "neben dem Schrank", back: "next to the wardrobe", frontAudio: true },
        { front: "vor dem Haus", back: "in front of the house", frontAudio: true },
        { front: "hinter der Tür", back: "behind the door", frontAudio: true },
        { front: "an der Wand", back: "on the wall", frontAudio: true },
        { front: "im Wohnzimmer", back: "in the living room", frontAudio: true },
        { front: "Wo ist der Schlüssel?", back: "Where is the key?", frontAudio: true },
        { front: "stehen", back: "to stand", frontAudio: true },
        { front: "liegen", back: "to lie", frontAudio: true },
        { front: "hängen", back: "to hang", frontAudio: true },
        { front: "Ich wohne im Zentrum.", back: "I live in the centre.", frontAudio: true },
      ],
    },
  ],
};

export const wohinGehtEs: Lesson = {
  id: "wohin-geht-es",
  title: "Wohin geht es?",
  summary:
    "Direction and movement: wohin with the accusative, the two-way prepositions, the Wechselpräpositionen, and the verbs of going.",
  status: "ready",
  sections: [
    {
      heading: "Wohin? und die Wechselpräpositionen",
      blocks: [
        {
          type: "paragraph",
          text: "The question Wohin? (Where to?) asks for a direction, and the answer takes the accusative: Wohin gehst du? Ich gehe in die Küche. The same prepositions as Wo? but with the accusative: in, auf, unter, neben, vor, hinter, zwischen. These seven are the Wechselpräpositionen (two-way prepositions).",
        },
        {
          type: "table",
          caption: "Wo? against Wohin?",
          head: ["Wo? (position, dative)", "Wohin? (direction, accusative)"],
          rows: [
            ["in der Küche", "in die Küche"],
            ["auf dem Tisch", "auf den Tisch"],
            ["unter dem Bett", "unter das Bett"],
            ["neben dem Schrank", "neben den Schrank"],
            ["vor dem Haus", "vor das Haus"],
            ["hinter der Tür", "hinter die Tür"],
          ],
        },
        {
          type: "example",
          de: "Wo ist der Schlüssel? Er ist auf dem Tisch. Wohin legst du den Schlüssel? Ich lege ihn auf den Tisch.",
          en: "Where is the key? It is on the table. Where are you putting the key? I'm putting it on the table.",
        },
        {
          type: "tip",
          text: "The test: Wo? asks where something is (dative), Wohin? asks where something goes (accusative). Position stays, direction moves.",
        },
      ],
    },
    {
      heading: "Die Verben der Bewegung",
      blocks: [
        {
          type: "paragraph",
          text: "Movement verbs take the accusative after a two-way preposition: gehen (to go), kommen (to come), fahren (to drive, travel), fliegen (to fly), laufen (to run), schwimmen (to swim), legen (to lay), stellen (to stand something), hängen (to hang something). The position verbs stehen, liegen, sitzen stay with the dative.",
        },
        {
          type: "table",
          caption: "Movement verbs",
          head: ["Verb", "English", "Example"],
          rows: [
            ["gehen", "to go", "Ich gehe in die Stadt."],
            ["kommen", "to come", "Er kommt ins Büro."],
            ["fahren", "to drive, travel", "Wir fahren aufs Land."],
            ["laufen", "to run", "Sie läuft zum Bahnhof."],
            ["legen", "to lay (flat)", "Ich lege das Buch auf den Tisch."],
            ["stellen", "to stand (upright)", "Er stellt den Stuhl neben den Tisch."],
          ],
        },
        {
          type: "example",
          de: "Ich lege das Buch auf den Tisch. Er stellt die Lampe auf den Schrank. Wir gehen ins Kino.",
          en: "I put the book on the table. He puts the lamp on the cupboard. We go to the cinema.",
        },
        {
          type: "tip",
          text: "The pair legen/stehen: legen lays a flat object (legen → liegen), stellen stands an upright one (stellen → stehen). Both take the accusative with wohin.",
        },
      ],
    },
    {
      heading: "Die kontrahierten Formen",
      blocks: [
        {
          type: "paragraph",
          text: "With direction, the prepositions contract with the neuter article: in + das = ins, an + das = ans, auf + das = aufs. The neuter rooms take ins: ins Wohnzimmer, ins Bad, ins Kino, ins Büro. The masculine takes in den, the feminine in die.",
        },
        {
          type: "table",
          caption: "Direction contractions",
          head: ["Full", "Contracted", "Example"],
          rows: [
            ["in + das", "ins", "ins Kino"],
            ["an + das", "ans", "ans Fenster"],
            ["auf + das", "aufs", "aufs Land"],
            ["in + den", "in den", "in den Garten"],
            ["in + die", "in die", "in die Stadt"],
          ],
        },
        {
          type: "example",
          de: "Wir gehen heute ins Kino. Danach fahren wir aufs Land. Die Kinder laufen in den Garten.",
          en: "We're going to the cinema today. Afterwards we drive to the countryside. The children run into the garden.",
        },
        {
          type: "tip",
          text: "ins is the direction twin of im: im Wohnzimmer (where), ins Wohnzimmer (where to). Learn the pairs im/ins, am/ans, aufs.",
        },
      ],
    },
    {
      heading: "nach, zu und die Städte",
      blocks: [
        {
          type: "paragraph",
          text: "Direction uses three more prepositions: nach + city or country without article (nach Berlin, nach Deutschland), zu + person or building (zum Bahnhof, zur Schule, zu Anna), and in + articles. The rule: nach for bare places, zu for named targets with people and buildings, in for rooms with the article.",
        },
        {
          type: "table",
          caption: "nach, zu, in",
          head: ["Preposition", "When", "Example"],
          rows: [
            ["nach", "cities and countries, bare", "nach Berlin, nach Deutschland"],
            ["zu", "people, buildings, directions", "zum Bahnhof, zur Schule"],
            ["in", "rooms, inside places", "in die Küche, ins Kino"],
          ],
        },
        {
          type: "example",
          de: "Ich fahre nach Berlin. Er geht zum Bahnhof. Wir gehen in die Schule.",
          en: "I'm driving to Berlin. He is going to the station. We are going to school.",
        },
        {
          type: "tip",
          text: "The question Wohin fährst du? uses nach for cities: Nach Berlin, nach Hamburg, nach Deutschland. Never nach die Stadt.",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: using the dative after wohin, mixing nach and zu, and forgetting the contracted forms.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["dative after wohin", "Ich gehe in der Küche.", "Ich gehe in die Küche.", "direction takes the accusative"],
            ["nach with article", "Ich fahre nach die Stadt.", "Ich fahre in die Stadt.", "nach takes no article"],
            ["zu/nach mix", "Ich fahre zu Berlin.", "Ich fahre nach Berlin.", "cities take nach"],
            ["missing ins", "Wir gehen in Kino.", "Wir gehen ins Kino.", "in + das = ins"],
            ["position verb with wohin", "Ich stehe das Buch auf den Tisch.", "Ich lege das Buch auf den Tisch.", "movement needs the movement verb"],
          ],
        },
        {
          type: "tip",
          text: "The direction question decides everything: Wohin? takes the accusative and the movement verb. Ask the pair test on every preposition: Wo (dative) or Wohin (accusative)?",
        },
      ],
    },
  ],
  vocab: [
    { id: "gehen", de: "gehen", en: "to go", part: "verb", audio: true },
    { id: "kommen", de: "kommen", en: "to come", part: "verb", audio: true },
    { id: "fahren", de: "fahren", en: "to drive, travel", part: "verb", audio: true },
    { id: "fliegen", de: "fliegen", en: "to fly", part: "verb", audio: true },
    { id: "laufen", de: "laufen", en: "to run", part: "verb", audio: true },
    { id: "schwimmen", de: "schwimmen", en: "to swim", part: "verb", audio: true },
    { id: "legen", de: "legen", en: "to lay (flat)", part: "verb", audio: true },
    { id: "stellen", de: "stellen", en: "to stand (upright)", part: "verb", audio: true },
    { id: "das-kino", de: "das Kino", en: "the cinema", part: "noun n.", plural: "die Kinos", audio: true },
    { id: "das-buero", de: "das Büro", en: "the office", part: "noun n.", plural: "die Büros", audio: true },
    { id: "die-schule", de: "die Schule", en: "the school", part: "noun f.", plural: "die Schulen", audio: true },
    { id: "der-bahnhof", de: "der Bahnhof", en: "the train station", part: "noun m.", plural: "die Bahnhöfe", audio: true },
    { id: "in-die-kueche", de: "in die Küche", en: "into the kitchen", part: "phrase", phrase: true, audio: true },
    { id: "ins-kino", de: "ins Kino", en: "to the cinema", part: "phrase", phrase: true, audio: true },
    { id: "ins-buero", de: "ins Büro", en: "to the office", part: "phrase", phrase: true, audio: true },
    { id: "auf-den-tisch", de: "auf den Tisch", en: "onto the table", part: "phrase", phrase: true, audio: true },
    { id: "nach-berlin", de: "nach Berlin", en: "to Berlin", part: "phrase", phrase: true, audio: true },
    { id: "nach-deutschland", de: "nach Deutschland", en: "to Germany", part: "phrase", phrase: true, audio: true },
    { id: "zum-bahnhof", de: "zum Bahnhof", en: "to the train station", part: "phrase", phrase: true, audio: true },
    { id: "zur-schule", de: "zur Schule", en: "to school", part: "phrase", phrase: true, audio: true },
    { id: "in-den-garten", de: "in den Garten", en: "into the garden", part: "phrase", phrase: true, audio: true },
    { id: "auf-das-land", de: "aufs Land", en: "to the countryside", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-wo-wohin",
      type: "matching",
      title: "Übung 1: Wo oder wohin?",
      instruction: "Match each question to its case.",
      pairs: [
        ["Wo? (position)", "dative"],
        ["Wohin? (direction)", "accusative"],
      ],
    },
    {
      id: "ex-akkusativ",
      type: "multiple-choice",
      title: "Übung 2: Der Akkusativ",
      instruction: "Choose the correct phrase.",
      prompt: "Ich gehe in ___ Küche.",
      options: ["die", "der", "dem"],
      correctIndex: 0,
      explain: "Direction takes the accusative: in die Küche.",
    },
    {
      id: "ex-akkusativ-2",
      type: "multiple-choice",
      title: "Übung 3: Der Akkusativ",
      instruction: "Choose the correct phrase.",
      prompt: "Wir fahren aufs Land. The full form is ...",
      options: ["auf das Land", "auf dem Land", "auf der Land"],
      correctIndex: 0,
      explain: "aufs = auf das.",
    },
    {
      id: "ex-nach",
      type: "multiple-choice",
      title: "Übung 4: nach",
      instruction: "Choose the correct sentence.",
      prompt: "I am going to Berlin.",
      options: ["Ich fahre nach Berlin.", "Ich fahre zu Berlin.", "Ich fahre in Berlin."],
      correctIndex: 0,
      explain: "Cities take nach.",
    },
    {
      id: "ex-zu",
      type: "multiple-choice",
      title: "Übung 5: zu",
      instruction: "Choose the correct phrase.",
      prompt: "I am going to the train station.",
      options: ["zum Bahnhof", "nach Bahnhof", "in Bahnhof"],
      correctIndex: 0,
      explain: "Buildings and directions take zu: zum Bahnhof.",
    },
    {
      id: "ex-wohnzimmer",
      type: "multiple-choice",
      title: "Übung 6: im oder ins",
      instruction: "Choose the correct phrase.",
      prompt: "Wohin? → ___ Wohnzimmer.",
      options: ["ins", "im", "in den"],
      correctIndex: 0,
      explain: "Direction into the neuter room: ins.",
    },
    {
      id: "ex-verb",
      type: "multiple-choice",
      title: "Übung 7: Das Bewegungsverb",
      instruction: "Choose the correct verb.",
      prompt: "Ich ___ das Buch auf den Tisch.",
      options: ["lege", "liege", "stehe"],
      correctIndex: 0,
      explain: "Laying a flat object: legen.",
    },
    {
      id: "ex-verb-2",
      type: "multiple-choice",
      title: "Übung 8: Das Bewegungsverb",
      instruction: "Choose the correct verb.",
      prompt: "Er ___ den Stuhl neben den Tisch.",
      options: ["stellt", "steht", "liegt"],
      correctIndex: 0,
      explain: "Standing an upright object: stellen.",
    },
    {
      id: "ex-kino",
      type: "multiple-choice",
      title: "Übung 9: ins Kino",
      instruction: "Choose the correct sentence.",
      prompt: "We are going to the cinema today.",
      options: ["Wir gehen heute ins Kino.", "Wir gehen heute im Kino.", "Wir gehen heute in Kino."],
      correctIndex: 0,
      explain: "Direction into the cinema: ins Kino.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 10: Hören",
      instruction: "Play the audio and pick the phrase you heard.",
      prompt: "in die Küche",
      options: ["in die Küche", "in der Küche", "in das Küche"],
      correctIndex: 0,
      explain: "The direction heard: into the kitchen.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 11: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Ich fahre nach Berlin.",
      options: ["Ich fahre nach Berlin.", "Ich fahre nach Deutschland.", "Ich fahre zum Bahnhof."],
      correctIndex: 0,
      explain: "The destination heard: Berlin.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 12: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Ich gehe in die Stadt.", "Ich gehe in der Stadt.", "Ich gehe auf der Stadt."],
      correctIndex: 0,
      explain: "Direction takes the accusative: in die Stadt.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 13: Der Satz",
      instruction: "Build the sentence: I am going into the kitchen.",
      chunks: ["Ich", "gehe", "in", "die", "Küche."], translation: "I am going into the kitchen.",
      explain: "Direction with the accusative.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 14: Der Satz",
      instruction: "Build the sentence: We are going to the cinema.",
      chunks: ["Wir", "gehen", "ins", "Kino."], translation: "We are going to the cinema.",
      explain: "ins = in + das.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 15: Richtungskarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "in die Küche", back: "into the kitchen", frontAudio: true },
        { front: "ins Kino", back: "to the cinema", frontAudio: true },
        { front: "auf den Tisch", back: "onto the table", frontAudio: true },
        { front: "nach Berlin", back: "to Berlin", frontAudio: true },
        { front: "zum Bahnhof", back: "to the train station", frontAudio: true },
        { front: "zur Schule", back: "to school", frontAudio: true },
        { front: "in den Garten", back: "into the garden", frontAudio: true },
        { front: "aufs Land", back: "to the countryside", frontAudio: true },
        { front: "gehen", back: "to go", frontAudio: true },
        { front: "legen", back: "to lay (flat)", frontAudio: true },
        { front: "stellen", back: "to stand (upright)", frontAudio: true },
        { front: "Ich fahre nach Berlin.", back: "I am going to Berlin.", frontAudio: true },
      ],
    },
  ],
};

export const farben: Lesson = {
  id: "farben",
  title: "Farben",
  summary:
    "The complete colour system for A1: the eleven basic colours, the adjective endings, the noun Farben, and describing objects.",
  status: "ready",
  sections: [
    {
      heading: "Die Grundfarben",
      blocks: [
        {
          type: "paragraph",
          text: "The eleven basic colours cover almost everything at A1: rot (red), blau (blue), grün (green), gelb (yellow), schwarz (black), weiß (white), grau (grey), braun (brown), orange (orange), lila (purple), pink (pink). The question: Welche Farbe hat ...? (What colour does ... have?).",
        },
        {
          type: "table",
          caption: "The basic colours",
          head: ["German", "English"],
          rows: [
            ["rot", "red"],
            ["blau", "blue"],
            ["grün", "green"],
            ["gelb", "yellow"],
            ["schwarz", "black"],
            ["weiß", "white"],
            ["grau", "grey"],
            ["braun", "brown"],
            ["orange", "orange"],
            ["lila", "purple"],
            ["pink", "pink"],
          ],
        },
        {
          type: "example",
          de: "Welche Farbe hat das Auto? Das Auto ist rot. Und der Stuhl? Der Stuhl ist blau.",
          en: "What colour is the car? The car is red. And the chair? The chair is blue.",
        },
        {
          type: "tip",
          text: "orange, lila and pink never take an ending: ein orangefarbenes Auto. The others take endings: ein rotes Auto.",
        },
      ],
    },
    {
      heading: "Die Farbadjektive",
      blocks: [
        {
          type: "paragraph",
          text: "The colours are adjectives and they take the adjective endings: ein rotes Auto, eine rote Blume, ein roter Stuhl. The noun form is die Farbe with the colour as a noun: das Rot, das Blau. The compound words: die Farbe + the colour: die Farbe Rot, die Farbe Blau.",
        },
        {
          type: "table",
          caption: "Colour as adjective and noun",
          head: ["Adjective", "Noun (the colour)", "Example"],
          rows: [
            ["rot", "das Rot", "ein rotes Auto"],
            ["blau", "das Blau", "der blaue Himmel"],
            ["grün", "das Grün", "die grüne Wiese"],
            ["schwarz", "das Schwarz", "der schwarze Kaffee"],
            ["weiß", "das Weiß", "das weiße Hemd"],
          ],
        },
        {
          type: "example",
          de: "Ich kaufe ein rotes Auto. Der Himmel ist heute blau. Sie trägt ein weißes Hemd.",
          en: "I'm buying a red car. The sky is blue today. She is wearing a white shirt.",
        },
        {
          type: "tip",
          text: "The colour question test: Welche Farbe hat ...? Answer: ... ist + colour. The ending comes when the colour stands before a noun.",
        },
      ],
    },
    {
      heading: "Die Farben der Dinge",
      blocks: [
        {
          type: "paragraph",
          text: "Everyday objects have natural colours you should be able to name: der Himmel (sky, blue), die Sonne (sun, yellow), das Gras (grass, green), die Milch (milk, white), der Kaffee (coffee, black or brown). The question pair: Welche Farbe hat der Himmel? Der Himmel ist blau.",
        },
        {
          type: "table",
          caption: "Colours of the world",
          head: ["Object", "Colour"],
          rows: [
            ["der Himmel", "blau"],
            ["die Sonne", "gelb"],
            ["das Gras", "grün"],
            ["die Milch", "weiß"],
            ["der Kaffee", "schwarz oder braun"],
            ["die Banane", "gelb"],
            ["die Tomate", "rot"],
          ],
        },
        {
          type: "example",
          de: "Welche Farbe hat die Banane? Die Banane ist gelb. Welche Farbe hat die Tomate? Die Tomate ist rot.",
          en: "What colour is the banana? The banana is yellow. What colour is the tomato? The tomato is red.",
        },
        {
          type: "tip",
          text: "The exam asks colour about real objects: the sky, the banana, the tomato. Practise the pattern on everything around you.",
        },
      ],
    },
    {
      heading: "Die Farben im Kleidungsdialog",
      blocks: [
        {
          type: "paragraph",
          text: "Colours are essential for shopping: the seller asks Welche Farbe möchten Sie? and you answer the colour with the accusative: Ich möchte ein rotes Hemd, bitte. The neuter pattern: ein rotes Hemd, ein blaues T-Shirt, ein grünes Kleid.",
        },
        {
          type: "table",
          caption: "Colours in the shop",
          head: ["German", "English"],
          rows: [
            ["Welche Farbe möchten Sie?", "What colour would you like?"],
            ["Ich möchte ein rotes Hemd.", "I would like a red shirt."],
            ["Haben Sie das in Blau?", "Do you have it in blue?"],
            ["Die Bluse ist weiß.", "The blouse is white."],
            ["Die Hose ist schwarz.", "The trousers are black."],
          ],
        },
        {
          type: "example",
          de: "Guten Tag! Ich suche ein Kleid. Welche Farbe möchten Sie? Ein grünes Kleid, bitte.",
          en: "Good day! I'm looking for a dress. What colour would you like? A green dress, please.",
        },
        {
          type: "tip",
          text: "The shop phrase: Haben Sie das in Blau? with the colour as a noun. The adjective answer: ein grünes Kleid.",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: wrong adjective endings, using the noun instead of the adjective, and forgetting that orange, lila and pink stay bare.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["wrong ending", "ein rot Auto", "ein rotes Auto", "neuter adjectives take -es"],
            ["noun instead of adjective", "Das Auto ist Rot.", "Das Auto ist rot.", "after sein comes the adjective"],
            ["ending on orange", "ein oranges Kleid", "ein orangefarbenes Kleid", "orange stays bare"],
            ["wrong gender ending", "eine roter Blume", "eine rote Blume", "feminine adjectives take -e"],
            ["missing article", "rotes Auto ist da.", "Das rote Auto ist da.", "the noun needs the article"],
          ],
        },
        {
          type: "tip",
          text: "The colour system: adjective after sein (Das Auto ist rot), adjective before the noun with an ending (ein rotes Auto). Say the pair aloud and the endings become automatic.",
        },
      ],
    },
  ],
  vocab: [
    { id: "rot", de: "rot", en: "red", part: "adjective", audio: true },
    { id: "blau", de: "blau", en: "blue", part: "adjective", audio: true },
    { id: "gruen", de: "grün", en: "green", part: "adjective", audio: true },
    { id: "gelb", de: "gelb", en: "yellow", part: "adjective", audio: true },
    { id: "schwarz", de: "schwarz", en: "black", part: "adjective", audio: true },
    { id: "weiss", de: "weiß", en: "white", part: "adjective", audio: true },
    { id: "grau", de: "grau", en: "grey", part: "adjective", audio: true },
    { id: "braun", de: "braun", en: "brown", part: "adjective", audio: true },
    { id: "orange", de: "orange", en: "orange (colour)", part: "adjective", audio: true },
    { id: "lila", de: "lila", en: "purple", part: "adjective", audio: true },
    { id: "pink", de: "pink", en: "pink", part: "adjective", audio: true },
    { id: "die-farbe", de: "die Farbe", en: "the colour", part: "noun f.", plural: "die Farben", audio: true },
    { id: "der-himmel", de: "der Himmel", en: "the sky", part: "noun m.", plural: "die Himmel", audio: true },
    { id: "die-sonne", de: "die Sonne", en: "the sun", part: "noun f.", plural: "die Sonnen", audio: true },
    { id: "das-gras", de: "das Gras", en: "the grass", part: "noun n.", audio: true },
    { id: "das-kleid", de: "das Kleid", en: "the dress", part: "noun n.", plural: "die Kleider", audio: true },
    { id: "das-hemd", de: "das Hemd", en: "the shirt", part: "noun n.", plural: "die Hemden", audio: true },
    { id: "die-bluse", de: "die Bluse", en: "the blouse", part: "noun f.", plural: "die Blusen", audio: true },
    { id: "die-hose", de: "die Hose", en: "the trousers", part: "noun f.", plural: "die Hosen", audio: true },
    { id: "welche-farbe", de: "Welche Farbe hat ...?", en: "What colour does ... have?", part: "phrase", phrase: true, audio: true },
    { id: "das-auto-ist-rot", de: "Das Auto ist rot.", en: "The car is red.", part: "phrase", phrase: true, audio: true },
    { id: "ein-rotes-auto", de: "ein rotes Auto", en: "a red car", part: "phrase", phrase: true, audio: true },
    { id: "ein-weisses-hemd", de: "ein weißes Hemd", en: "a white shirt", part: "phrase", phrase: true, audio: true },
    { id: "in-blau", de: "Haben Sie das in Blau?", en: "Do you have it in blue?", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-farben",
      type: "matching",
      title: "Übung 1: Die Farben",
      instruction: "Match each colour to its English name.",
      pairs: [
        ["rot", "red"],
        ["blau", "blue"],
        ["grün", "green"],
        ["gelb", "yellow"],
        ["schwarz", "black"],
        ["weiß", "white"],
      ],
    },
    {
      id: "ex-farben-2",
      type: "matching",
      title: "Übung 2: Die Farben 2",
      instruction: "Match each colour to its English name.",
      pairs: [
        ["grau", "grey"],
        ["braun", "brown"],
        ["orange", "orange (colour)"],
        ["lila", "purple"],
        ["pink", "pink"],
      ],
    },
    {
      id: "ex-frage",
      type: "multiple-choice",
      title: "Übung 3: Die Farbfrage",
      instruction: "Choose the colour question.",
      prompt: "You ask what colour the car is.",
      options: ["Welche Farbe hat das Auto?", "Was Farbe hat das Auto?", "Wie Farbe ist das Auto?"],
      correctIndex: 0,
      explain: "The colour question uses welche Farbe.",
    },
    {
      id: "ex-antwort",
      type: "multiple-choice",
      title: "Übung 4: Die Farbantwort",
      instruction: "Choose the colour answer.",
      prompt: "The car is red.",
      options: ["Das Auto ist rot.", "Das Auto ist Rot.", "Das Auto hat rot."],
      correctIndex: 0,
      explain: "After sein comes the lowercase adjective.",
    },
    {
      id: "ex-endung",
      type: "multiple-choice",
      title: "Übung 5: Die Endung",
      instruction: "Choose the correct ending.",
      prompt: "ein ___ Auto (red)",
      options: ["rotes", "rote", "roter"],
      correctIndex: 0,
      explain: "Neuter adjectives take -es.",
    },
    {
      id: "ex-endung-2",
      type: "multiple-choice",
      title: "Übung 6: Die Endung",
      instruction: "Choose the correct ending.",
      prompt: "eine ___ Blume (red)",
      options: ["rote", "rotes", "roter"],
      correctIndex: 0,
      explain: "Feminine adjectives take -e.",
    },
    {
      id: "ex-endung-3",
      type: "multiple-choice",
      title: "Übung 7: Die Endung",
      instruction: "Choose the correct ending.",
      prompt: "ein ___ Stuhl (blue)",
      options: ["blauer", "blaues", "blaue"],
      correctIndex: 0,
      explain: "Masculine adjectives take -er.",
    },
    {
      id: "ex-orange",
      type: "multiple-choice",
      title: "Übung 8: orange und lila",
      instruction: "Choose the correct phrase.",
      prompt: "A purple bag.",
      options: ["eine lila Tasche", "eine lilane Tasche", "eine lilaer Tasche"],
      correctIndex: 0,
      explain: "lila stays bare.",
    },
    {
      id: "ex-welt",
      type: "matching",
      title: "Übung 9: Die Farben der Welt",
      instruction: "Match each object to its natural colour.",
      pairs: [
        ["der Himmel", "blau"],
        ["die Sonne", "gelb"],
        ["das Gras", "grün"],
        ["die Milch", "weiß"],
        ["die Tomate", "rot"],
        ["der Kaffee", "schwarz oder braun"],
      ],
    },
    {
      id: "ex-kleidung",
      type: "multiple-choice",
      title: "Übung 10: Die Farben im Geschäft",
      instruction: "Choose the correct phrase.",
      prompt: "You want a green dress.",
      options: ["ein grünes Kleid", "ein grüner Kleid", "ein grüne Kleid"],
      correctIndex: 0,
      explain: "Neuter Kleid takes -es.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 11: Hören",
      instruction: "Play the audio and pick the colour you heard.",
      prompt: "grün",
      options: ["grün", "grau", "braun"],
      correctIndex: 0,
      explain: "The colour heard: green.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 12: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Das Auto ist rot.",
      options: ["Das Auto ist rot.", "Das Auto ist blau.", "Das Auto ist grün."],
      correctIndex: 0,
      explain: "The colour sentence heard: red car.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 13: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Ich möchte ein weißes Hemd.", "Ich möchte ein weiß Hemd.", "Ich möchte ein weißer Hemd."],
      correctIndex: 0,
      explain: "Neuter Hemd takes -es.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 14: Der Satz",
      instruction: "Build the sentence: The sky is blue.",
      chunks: ["Der", "Himmel", "ist", "blau."], translation: "The sky is blue.",
      explain: "Colour after sein.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 15: Der Satz",
      instruction: "Build the sentence: I would like a red car.",
      chunks: ["Ich", "möchte", "ein", "rotes", "Auto."], translation: "I would like a red car.",
      explain: "Adjective before the noun with the ending.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 16: Farbkarten",
      instruction: "Say the colour out loud before revealing.",
      items: [
        { front: "rot", back: "red", frontAudio: true },
        { front: "blau", back: "blue", frontAudio: true },
        { front: "grün", back: "green", frontAudio: true },
        { front: "gelb", back: "yellow", frontAudio: true },
        { front: "schwarz", back: "black", frontAudio: true },
        { front: "weiß", back: "white", frontAudio: true },
        { front: "grau", back: "grey", frontAudio: true },
        { front: "braun", back: "brown", frontAudio: true },
        { front: "lila", back: "purple", frontAudio: true },
        { front: "ein rotes Auto", back: "a red car", frontAudio: true },
        { front: "Das Auto ist rot.", back: "The car is red.", frontAudio: true },
        { front: "Welche Farbe hat das Auto?", back: "What colour is the car?", frontAudio: true },
      ],
    },
  ],
};

export const wohnungsanzeigen: Lesson = {
  id: "wohnungsanzeigen",
  title: "Wohnungsanzeigen",
  summary:
    "Reading and understanding apartment ads: the abbreviations, the rooms, the rent and deposit, and the complete viewing dialogue.",
  status: "ready",
  sections: [
    {
      heading: "Die Anzeige lesen",
      blocks: [
        {
          type: "paragraph",
          text: "Apartment ads (die Wohnungsanzeigen) are written in abbreviations. The key letters: Zi. (Zimmer, rooms), KM (Kaltmiete, cold rent without utilities), NK (Nebenkosten, utilities), warm (KM + NK together), EBK (Einbauküche, fitted kitchen), B. or Balk. (Balkon), DHH (Doppelhaushälfte, semi-detached house), OG (Obergeschoss), DG (Dachgeschoss).",
        },
        {
          type: "table",
          caption: "The ad abbreviations",
          head: ["Abbreviation", "Full form", "English"],
          rows: [
            ["Zi.", "Zimmer", "room"],
            ["KM", "Kaltmiete", "cold rent (no utilities)"],
            ["NK", "Nebenkosten", "utilities"],
            ["warm", "warmmiete", "rent incl. utilities"],
            ["EBK", "Einbauküche", "fitted kitchen"],
            ["Balk.", "Balkon", "balcony"],
            ["OG", "Obergeschoss", "upper floor"],
            ["DG", "Dachgeschoss", "attic"],
            ["DHH", "Doppelhaushälfte", "semi-detached house"],
          ],
        },
        {
          type: "example",
          de: "3-Zi.-Wohnung, 2. OG, 75 qm, Balk., EBK, warm 850 Euro. Verfügbar ab 1. Oktober.",
          en: "3-room flat, 2nd floor, 75 sqm, balcony, fitted kitchen, 850 euros including heating. Available from 1 October.",
        },
        {
          type: "tip",
          text: "The ad says: 3 rooms, 2nd floor, 75 square metres, balcony, fitted kitchen, 850 euros warm, available from 1 October. Read qm as Quadratmeter.",
        },
      ],
    },
    {
      heading: "Die Kosten der Wohnung",
      blocks: [
        {
          type: "paragraph",
          text: "The money of an apartment has three parts: die Kaltmiete (cold rent), die Nebenkosten (utilities: heating, water), and die Warmmiete (Kaltmiete + Nebenkosten). Plus two one-time payments: die Kaution (deposit, usually 3 months rent) and die Provision (the broker fee).",
        },
        {
          type: "table",
          caption: "The costs",
          head: ["German", "English"],
          rows: [
            ["die Kaltmiete", "the cold rent"],
            ["die Nebenkosten", "the utilities"],
            ["die Warmmiete", "the rent incl. utilities"],
            ["die Kaution", "the deposit"],
            ["die Provision", "the broker fee"],
            ["die Miete / mieten", "the rent / to rent"],
            ["der Vermieter", "the landlord"],
            ["die Vermieterin", "the landlady"],
          ],
        },
        {
          type: "example",
          de: "Die Warmmiete ist 850 Euro. Die Kaution ist drei Monatsmieten, also 2550 Euro. Die Provision kostet zwei Monatsmieten.",
          en: "The rent including heating is 850 euros. The deposit is three months' rent, so 2550 euros. The commission costs two months' rent.",
        },
        {
          type: "tip",
          text: "The classic question: Wie hoch ist die Miete? The answer names the Kaltmiete, the NK, and then the warm price.",
        },
      ],
    },
    {
      heading: "Die Besichtigung",
      blocks: [
        {
          type: "paragraph",
          text: "The viewing (die Besichtigung) is the exam's housing scenario: you arrange the appointment, ask questions at the viewing, and decide. The key sentences: Wann können wir die Wohnung besichtigen? (When can we view the apartment?), Wie hoch ist die Miete? (How high is the rent?), Ist die Wohnung noch frei? (Is the apartment still available?).",
        },
        {
          type: "table",
          caption: "The viewing dialogue",
          head: ["German", "English"],
          rows: [
            ["Wann können wir besichtigen?", "When can we view it?"],
            ["Wie hoch ist die Miete?", "How high is the rent?"],
            ["Ist die Wohnung noch frei?", "Is the apartment still available?"],
            ["Wie groß ist die Wohnung?", "How big is the apartment?"],
            ["Haben Sie einen Balkon?", "Do you have a balcony?"],
            ["Gibt es einen Fahrstuhl?", "Is there a lift?"],
            ["Ist die Küche in der Miete enthalten?", "Is the kitchen included?"],
            ["Wir nehmen die Wohnung.", "We will take the apartment."],
          ],
        },
        {
          type: "example",
          de: "Guten Tag, wir möchten die Wohnung besichtigen. Die Wohnung hat drei Zimmer und 75 Quadratmeter. Wie hoch ist die Miete? 850 Euro warm. Wir nehmen die Wohnung.",
          en: "Good day, we would like to view the flat. The flat has three rooms and 75 square metres. How high is the rent? 850 euros including heating. We'll take the flat.",
        },
        {
          type: "tip",
          text: "The viewing questions are a fixed set: available, size, rent, kitchen, lift, balcony. Ask them all and the scenario is covered.",
        },
      ],
    },
    {
      heading: "Der Umzug",
      blocks: [
        {
          type: "paragraph",
          text: "After the contract comes the move (der Umzug): der Umzugskarton (moving box), der Umzugswagen (moving van), einpacken (to pack up), auspacken (to unpack), the verb umziehen (to move). The sentence: Wir ziehen nächste Woche um. (We move next week.)",
        },
        {
          type: "table",
          caption: "The move",
          head: ["German", "English"],
          rows: [
            ["der Umzug", "the move"],
            ["umziehen", "to move house"],
            ["einpacken", "to pack up"],
            ["auspacken", "to unpack"],
            ["der Umzugskarton", "the moving box"],
            ["der Umzugswagen", "the moving van"],
          ],
        },
        {
          type: "example",
          de: "Wir ziehen nächste Woche um. Am Samstag packen wir ein, am Sonntag kommt der Umzugswagen.",
          en: "We're moving next week. On Saturday we pack, on Sunday the removal van comes.",
        },
        {
          type: "tip",
          text: "umziehen is a separable verb: Wir ziehen um. The prefix goes to the end in the main clause.",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: mixing Kaltmiete and Warmmiete, forgetting the separable verb, and reading the ad abbreviations wrong.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["Kaltmiete/Warmmiete mix", "KM ist mit Strom.", "KM ist ohne Nebenkosten.", "cold rent excludes utilities"],
            ["separabe verb", "Wir umziehen nächste Woche.", "Wir ziehen nächste Woche um.", "umziehen splits"],
            ["qm reading", "75 Quadrat.", "75 Quadratmeter.", "qm = Quadratmeter"],
            ["deposit amount", "Die Kaution ist ein Monat.", "Die Kaution ist drei Monatsmieten.", "the standard deposit is three months"],
            ["availability", "Ist die Wohnung frei? Ich bin frei.", "Ist die Wohnung noch frei?", "frei refers to the apartment"],
          ],
        },
        {
          type: "tip",
          text: "The ad is the exam text: read the abbreviations, the size, the floor, the costs. Then the viewing questions follow the ad line by line.",
        },
      ],
    },
  ],
  vocab: [
    { id: "die-wohnungsanzeige", de: "die Wohnungsanzeige", en: "the apartment ad", part: "noun f.", plural: "die Wohnungsanzeigen", audio: true },
    { id: "die-miete", de: "die Miete", en: "the rent", part: "noun f.", plural: "die Mieten", audio: true },
    { id: "die-kaltmiete", de: "die Kaltmiete", en: "the cold rent", part: "noun f.", plural: "die Kaltmieten", audio: true },
    { id: "die-nebenkosten", de: "die Nebenkosten", en: "the utilities", part: "noun pl.", audio: true },
    { id: "die-warmmiete", de: "die Warmmiete", en: "the rent incl. utilities", part: "noun f.", plural: "die Warmmieten", audio: true },
    { id: "die-kaution", de: "die Kaution", en: "the deposit", part: "noun f.", plural: "die Kautionsen", audio: true },
    { id: "die-provision", de: "die Provision", en: "the broker fee", part: "noun f.", plural: "die Provisionen", audio: true },
    { id: "der-vermieter", de: "der Vermieter", en: "the landlord", part: "noun m.", plural: "die Vermieter", audio: true },
    { id: "die-vermieterin", de: "die Vermieterin", en: "the landlady", part: "noun f.", plural: "die Vermieterinnen", audio: true },
    { id: "der-mietvertrag", de: "der Mietvertrag", en: "the rental contract", part: "noun m.", plural: "die Mietverträge", audio: true },
    { id: "der-quadratmeter", de: "der Quadratmeter", en: "the square metre", part: "noun m.", plural: "die Quadratmeter", audio: true },
    { id: "die-besichtigung", de: "die Besichtigung", en: "the viewing", part: "noun f.", plural: "die Besichtigungen", audio: true },
    { id: "der-umzug", de: "der Umzug", en: "the move", part: "noun m.", plural: "die Umzüge", audio: true },
    { id: "umziehen", de: "umziehen", en: "to move house", part: "verb", audio: true },
    { id: "einpacken", de: "einpacken", en: "to pack up", part: "verb", audio: true },
    { id: "auspacken", de: "auspacken", en: "to unpack", part: "verb", audio: true },
    { id: "ist-die-wohnung-noch-frei", de: "Ist die Wohnung noch frei?", en: "Is the apartment still available?", part: "phrase", phrase: true, audio: true },
    { id: "wie-hoch-ist-die-miete", de: "Wie hoch ist die Miete?", en: "How high is the rent?", part: "phrase", phrase: true, audio: true },
    { id: "wann-koennen-wir-besichtigen", de: "Wann können wir besichtigen?", en: "When can we view it?", part: "phrase", phrase: true, audio: true },
    { id: "wie-gross-ist-die-wohnung", de: "Wie groß ist die Wohnung?", en: "How big is the apartment?", part: "phrase", phrase: true, audio: true },
    { id: "drei-zimmer", de: "drei Zimmer", en: "three rooms", part: "phrase", phrase: true, audio: true },
    { id: "wir-nehmen-die-wohnung", de: "Wir nehmen die Wohnung.", en: "We will take the apartment.", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-abk",
      type: "matching",
      title: "Übung 1: Die Abkürzungen",
      instruction: "Match each abbreviation to its meaning.",
      pairs: [
        ["Zi.", "Zimmer"],
        ["KM", "Kaltmiete"],
        ["NK", "Nebenkosten"],
        ["EBK", "Einbauküche"],
        ["Balk.", "Balkon"],
        ["OG", "Obergeschoss"],
      ],
    },
    {
      id: "ex-anzeige",
      type: "multiple-choice",
      title: "Übung 2: Die Anzeige",
      instruction: "Read: 3-Zi., 2. OG, 75 qm, warm 850 Euro.",
      prompt: "How many rooms?",
      options: ["drei", "zwei", "fünf"],
      correctIndex: 0,
      explain: "3-Zi. means three rooms.",
    },
    {
      id: "ex-anzeige-2",
      type: "multiple-choice",
      title: "Übung 3: Die Anzeige",
      instruction: "Read: 3-Zi., 2. OG, 75 qm, warm 850 Euro.",
      prompt: "On which floor?",
      options: ["2. OG", "EG", "DG"],
      correctIndex: 0,
      explain: "2. OG is the second floor.",
    },
    {
      id: "ex-kosten",
      type: "matching",
      title: "Übung 4: Die Kosten",
      instruction: "Match each cost to its meaning.",
      pairs: [
        ["die Kaltmiete", "rent without utilities"],
        ["die Nebenkosten", "the utilities"],
        ["die Warmmiete", "rent incl. utilities"],
        ["die Kaution", "the deposit"],
        ["die Provision", "the broker fee"],
      ],
    },
    {
      id: "ex-kaution",
      type: "multiple-choice",
      title: "Übung 5: Die Kaution",
      instruction: "Choose the correct statement.",
      prompt: "The standard Kaution is ...",
      options: ["three months' rent", "one month's rent", "ten months' rent"],
      correctIndex: 0,
      explain: "The deposit is usually three Monatsmieten.",
    },
    {
      id: "ex-frage",
      type: "multiple-choice",
      title: "Übung 6: Die Fragen",
      instruction: "Choose the rent question.",
      prompt: "You ask how high the rent is.",
      options: ["Wie hoch ist die Miete?", "Wie groß ist die Miete?", "Wo ist die Miete?"],
      correctIndex: 0,
      explain: "Rent height: Wie hoch ist die Miete?",
    },
    {
      id: "ex-frage-2",
      type: "multiple-choice",
      title: "Übung 7: Die Fragen",
      instruction: "Choose the availability question.",
      prompt: "You ask if the apartment is still free.",
      options: ["Ist die Wohnung noch frei?", "Ist die Wohnung noch groß?", "Ist die Wohnung noch teuer?"],
      correctIndex: 0,
      explain: "Availability: noch frei.",
    },
    {
      id: "ex-umzug",
      type: "multiple-choice",
      title: "Übung 8: Der Umzug",
      instruction: "Choose the correct sentence.",
      prompt: "We move next week.",
      options: ["Wir ziehen nächste Woche um.", "Wir umziehen nächste Woche.", "Wir ziehen um nächste Woche."],
      correctIndex: 0,
      explain: "umziehen splits: ziehen ... um.",
    },
    {
      id: "ex-besichtigung",
      type: "multiple-choice",
      title: "Übung 9: Die Besichtigung",
      instruction: "Choose the viewing sentence.",
      prompt: "You want to view the apartment.",
      options: ["Wir möchten die Wohnung besichtigen.", "Wir möchten die Wohnung mieten sofort.", "Wir möchten die Wohnung sehen heute."],
      correctIndex: 0,
      explain: "The viewing verb: besichtigen.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 10: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Ist die Wohnung noch frei?",
      options: ["Ist die Wohnung noch frei?", "Ist die Wohnung noch groß?", "Wie hoch ist die Miete?"],
      correctIndex: 0,
      explain: "The availability question heard.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 11: Hören",
      instruction: "Play the audio and pick the phrase you heard.",
      prompt: "850 Euro warm",
      options: ["850 Euro warm", "850 Euro kalt", "815 Euro warm"],
      correctIndex: 0,
      explain: "The rent heard: 850 warm.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 12: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Wir ziehen nächste Woche um.", "Wir umziehen nächste Woche.", "Wir ziehen um nächste Woche."],
      correctIndex: 0,
      explain: "The separable verb splits.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 13: Der Satz",
      instruction: "Build the sentence: The apartment has three rooms.",
      chunks: ["Die", "Wohnung", "hat", "drei", "Zimmer."], translation: "The flat has three rooms.",
      explain: "Room count with haben.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 14: Der Satz",
      instruction: "Build the sentence: The rent is 850 euros warm.",
      chunks: ["Die", "Miete", "ist", "850", "Euro", "warm."], translation: "The rent is 850 euros including heating.",
      explain: "The warm rent sentence.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 15: Anzeigenkarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "Ist die Wohnung noch frei?", back: "Is the apartment still available?", frontAudio: true },
        { front: "Wie hoch ist die Miete?", back: "How high is the rent?", frontAudio: true },
        { front: "Wann können wir besichtigen?", back: "When can we view it?", frontAudio: true },
        { front: "die Kaltmiete", back: "the cold rent", frontAudio: true },
        { front: "die Warmmiete", back: "the rent incl. utilities", frontAudio: true },
        { front: "die Kaution", back: "the deposit", frontAudio: true },
        { front: "der Mietvertrag", back: "the rental contract", frontAudio: true },
        { front: "umziehen", back: "to move house", frontAudio: true },
        { front: "Wir ziehen nächste Woche um.", back: "We move next week.", frontAudio: true },
        { front: "drei Zimmer", back: "three rooms", frontAudio: true },
        { front: "75 Quadratmeter", back: "75 square metres", frontAudio: true },
        { front: "Wir nehmen die Wohnung.", back: "We will take the apartment.", frontAudio: true },
      ],
    },
  ],
};

export const adjektivendungen: Lesson = {
  id: "adjektivendungen",
  title: "Adjektivendungen",
  summary:
    "The complete adjective ending system for A1: after der-words, after ein-words, and without an article. The three declension tables that unlock every adjective.",
  status: "ready",
  sections: [
    {
      heading: "Das System der Endungen",
      blocks: [
        {
          type: "paragraph",
          text: "German adjectives only take endings when they stand before a noun: das rote Auto. After sein the adjective stays bare: Das Auto ist rot. The ending depends on three things: the gender (m./f./n./pl.), the case (nominative/accusative/dative), and the article before the adjective (der-word, ein-word, or none).",
        },
        {
          type: "table",
          caption: "The three situations",
          head: ["Situation", "Example", "Ending set"],
          rows: [
            ["after der-word", "der neue Tisch", "strong: -e, -en"],
            ["after ein-word", "ein neuer Tisch", "mixed: -er, -e, -es, -en"],
            ["without article", "neuer Kaffee", "strong: -er, -e, -es"],
          ],
        },
        {
          type: "example",
          de: "Das Auto ist rot. Das rote Auto steht da. Ein rotes Auto fährt vorbei.",
          en: "The car is red. The red car stands there. A red car drives past.",
        },
        {
          type: "tip",
          text: "The shortcut: after a der-word the adjective is mostly -e or -en; after ein-word it shows the article ending that the ein-word hides (ein neuer for der).",
        },
      ],
    },
    {
      heading: "Nach den der-Wörtern",
      blocks: [
        {
          type: "paragraph",
          text: "After der, die, das and the other der-words (dieser, jeder, dieser) the adjective takes only two endings: -e in the nominative singular and the accusative feminine/neuter, -en everywhere else. The table is simple because the article already shows the gender.",
        },
        {
          type: "table",
          caption: "Adjective after der-words",
          head: ["Case", "masculine", "feminine", "neuter", "plural"],
          rows: [
            ["Nominative", "der neue Tisch", "die neue Lampe", "das neue Haus", "die neuen Tische"],
            ["Accusative", "den neuen Tisch", "die neue Lampe", "das neue Haus", "die neuen Tische"],
            ["Dative", "dem neuen Tisch", "der neuen Lampe", "dem neuen Haus", "den neuen Tischen"],
          ],
        },
        {
          type: "example",
          de: "Der neue Tisch steht in der neuen Küche. Ich kaufe den neuen Tisch.",
          en: "The new table stands in the new kitchen. I'm buying the new table.",
        },
        {
          type: "tip",
          text: "The memory hook: -e in the nominative singular, -en everywhere else. Only der-neue, die-neue, das-neue and the plural take -en after the dative plural.",
        },
      ],
    },
    {
      heading: "Nach den ein-Wörtern",
      blocks: [
        {
          type: "paragraph",
          text: "After ein, eine, kein and the possessives (mein, dein, sein, unser, euer, ihr) the adjective takes the mixed endings: it shows the gender that the ein-word hides. In the nominative masculine the article ein is bare, so the adjective carries the -er: ein neuer Tisch. In the feminine ein takes -e, so the adjective takes -e: eine neue Lampe.",
        },
        {
          type: "table",
          caption: "Adjective after ein-words",
          head: ["Case", "masculine", "feminine", "neuter"],
          rows: [
            ["Nominative", "ein neuer Tisch", "eine neue Lampe", "ein neues Haus"],
            ["Accusative", "einen neuen Tisch", "eine neue Lampe", "ein neues Haus"],
            ["Dative", "einem neuen Tisch", "einer neuen Lampe", "einem neuen Haus"],
          ],
        },
        {
          type: "example",
          de: "Ich habe einen neuen Computer. Sie kauft eine neue Tasche. Wir brauchen ein neues Haus.",
          en: "I have a new computer. She buys a new bag. We need a new house.",
        },
        {
          type: "tip",
          text: "The accent lands on the ending the article does not carry: ein (no ending) + neuer (carries it). The dative always takes -en: einem neuen.",
        },
      ],
    },
    {
      heading: "Die Pluralendungen",
      blocks: [
        {
          type: "paragraph",
          text: "In the plural the adjective always takes -en, with one exception: the bare plural without an article takes -e. Die neuen Tische (with der), neue Tische (without article). The plural is the simplest case: -en after articles, -e bare.",
        },
        {
          type: "table",
          caption: "The plural endings",
          head: ["With article", "Without article"],
          rows: [
            ["die neuen Tische", "neue Tische"],
            ["die neuen Lampen", "neue Lampen"],
            ["keine neuen Häuser", "neue Häuser"],
          ],
        },
        {
          type: "example",
          de: "Die neuen Tische sind teuer. Aber neue Tische gibt es auch günstig.",
          en: "The new tables are expensive. But there are also cheap new tables.",
        },
        {
          type: "tip",
          text: "The plural rule in one line: after articles -en, bare -e. No umlaut, no exceptions at A1.",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "The classic errors: putting an ending after sein, using -er after der, and forgetting the dative -en.",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["ending after sein", "Das Auto ist rotes.", "Das Auto ist rot.", "after sein the adjective stays bare"],
            ["-er after der", "der neuer Tisch", "der neue Tisch", "the article already shows the gender"],
            ["wrong accusative", "Ich kaufe den neue Tisch.", "Ich kaufe den neuen Tisch.", "after den comes -en"],
            ["missing dative -en", "mit einem neuen Auto? Nein, mit einem neue Auto.", "mit einem neuen Auto", "the dative takes -en"],
            ["bare plural", "die neu Tische", "die neuen Tische", "the plural takes -en after articles"],
          ],
        },
        {
          type: "tip",
          text: "The test: ask where the adjective stands. After sein it is bare, before the noun it takes the ending. Then read the article: der-word (mostly -en), ein-word (the missing ending), none (strong).",
        },
      ],
    },
  ],
  vocab: [
    { id: "neu", de: "neu", en: "new", part: "adjective", audio: true },
    { id: "alt", de: "alt", en: "old", part: "adjective", audio: true },
    { id: "gross", de: "groß", en: "big", part: "adjective", audio: true },
    { id: "klein", de: "klein", en: "small", part: "adjective", audio: true },
    { id: "schoen", de: "schön", en: "beautiful, nice", part: "adjective", audio: true },
    { id: "gut", de: "gut", en: "good", part: "adjective", audio: true },
    { id: "teuer", de: "teuer", en: "expensive", part: "adjective", audio: true },
    { id: "billig", de: "billig", en: "cheap", part: "adjective", audio: true },
    { id: "modern", de: "modern", en: "modern", part: "adjective", audio: true },
    { id: "schnell", de: "schnell", en: "fast", part: "adjective", audio: true },
    { id: "langsam", de: "langsam", en: "slow", part: "adjective", audio: true },
    { id: "heiss", de: "heiß", en: "hot", part: "adjective", audio: true },
    { id: "kalt", de: "kalt", en: "cold", part: "adjective", audio: true },
    { id: "der-neue-tisch", de: "der neue Tisch", en: "the new table", part: "phrase", phrase: true, audio: true },
    { id: "ein-neuer-tisch", de: "ein neuer Tisch", en: "a new table", part: "phrase", phrase: true, audio: true },
    { id: "das-auto-ist-neu", de: "Das Auto ist neu.", en: "The car is new.", part: "phrase", phrase: true, audio: true },
    { id: "einen-neuen-computer", de: "einen neuen Computer", en: "a new computer (acc.)", part: "phrase", phrase: true, audio: true },
    { id: "die-neuen-tische", de: "die neuen Tische", en: "the new tables", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-sein",
      type: "multiple-choice",
      title: "Übung 1: Nach sein",
      instruction: "Choose the correct form.",
      prompt: "Das Auto ist ___.",
      options: ["neu", "neues", "neuer"],
      correctIndex: 0,
      explain: "After sein the adjective stays bare.",
    },
    {
      id: "ex-der",
      type: "multiple-choice",
      title: "Übung 2: Nach der",
      instruction: "Choose the correct form.",
      prompt: "der ___ Tisch",
      options: ["neue", "neuer", "neues"],
      correctIndex: 0,
      explain: "After der comes -e.",
    },
    {
      id: "ex-ein-m",
      type: "multiple-choice",
      title: "Übung 3: Nach ein (m.)",
      instruction: "Choose the correct form.",
      prompt: "ein ___ Tisch",
      options: ["neuer", "neue", "neuen"],
      correctIndex: 0,
      explain: "ein hides the gender, the adjective shows -er.",
    },
    {
      id: "ex-ein-f",
      type: "multiple-choice",
      title: "Übung 4: Nach ein (f.)",
      instruction: "Choose the correct form.",
      prompt: "eine ___ Lampe",
      options: ["neue", "neuer", "neues"],
      correctIndex: 0,
      explain: "Feminine after ein takes -e.",
    },
    {
      id: "ex-ein-n",
      type: "multiple-choice",
      title: "Übung 5: Nach ein (n.)",
      instruction: "Choose the correct form.",
      prompt: "ein ___ Haus",
      options: ["neues", "neue", "neuer"],
      correctIndex: 0,
      explain: "Neuter after ein takes -es.",
    },
    {
      id: "ex-akk",
      type: "multiple-choice",
      title: "Übung 6: Der Akkusativ",
      instruction: "Choose the correct form.",
      prompt: "Ich kaufe einen ___ Tisch.",
      options: ["neuen", "neue", "neuer"],
      correctIndex: 0,
      explain: "After einen comes -en.",
    },
    {
      id: "ex-dativ",
      type: "multiple-choice",
      title: "Übung 7: Der Dativ",
      instruction: "Choose the correct form.",
      prompt: "Ich sitze auf einem ___ Stuhl.",
      options: ["neuen", "neue", "neuer"],
      correctIndex: 0,
      explain: "The dative always takes -en.",
    },
    {
      id: "ex-plural",
      type: "multiple-choice",
      title: "Übung 8: Der Plural",
      instruction: "Choose the correct form.",
      prompt: "die ___ Tische",
      options: ["neuen", "neue", "neuer"],
      correctIndex: 0,
      explain: "The plural after articles takes -en.",
    },
    {
      id: "ex-plural-bare",
      type: "multiple-choice",
      title: "Übung 9: Der Plural ohne Artikel",
      instruction: "Choose the correct form.",
      prompt: "___ Tische (new, no article)",
      options: ["neue", "neuen", "neuer"],
      correctIndex: 0,
      explain: "The bare plural takes -e.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 10: Hören",
      instruction: "Play the audio and pick the phrase you heard.",
      prompt: "ein neues Haus",
      options: ["ein neues Haus", "ein neues Auto", "ein neues Buch"],
      correctIndex: 0,
      explain: "The phrase heard: a new house.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 11: Hören",
      instruction: "Play the audio and pick the sentence you heard.",
      prompt: "Der neue Tisch ist teuer.",
      options: ["Der neue Tisch ist teuer.", "Der neue Tisch ist billig.", "Ein neuer Tisch ist teuer."],
      correctIndex: 0,
      explain: "The sentence heard: the new table.",
    },
    {
      id: "ex-fehler",
      type: "multiple-choice",
      title: "Übung 12: Die Fehler",
      instruction: "Choose the correct sentence.",
      prompt: "Which sentence is correct?",
      options: ["Das Auto ist neu.", "Das Auto ist neues.", "Das Auto ist neue."],
      correctIndex: 0,
      explain: "After sein the adjective stays bare.",
    },
    {
      id: "ex-satz-1",
      type: "word-order",
      title: "Übung 13: Der Satz",
      instruction: "Build the sentence: I would like a new computer.",
      chunks: ["Ich", "möchte", "einen", "neuen", "Computer."], translation: "I would like a new computer.",
      explain: "Accusative masculine: einen neuen.",
    },
    {
      id: "ex-satz-2",
      type: "word-order",
      title: "Übung 14: Der Satz",
      instruction: "Build the sentence: The old house is beautiful.",
      chunks: ["Das", "alte", "Haus", "ist", "schön."], translation: "The old house is beautiful.",
      explain: "The der-word ending and sein.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 15: Endungskarten",
      instruction: "Say the phrase with the correct ending out loud.",
      items: [
        { front: "der neue Tisch", back: "the new table", frontAudio: true },
        { front: "ein neuer Tisch", back: "a new table", frontAudio: true },
        { front: "eine neue Lampe", back: "a new lamp", frontAudio: true },
        { front: "ein neues Haus", back: "a new house", frontAudio: true },
        { front: "einen neuen Computer", back: "a new computer (acc.)", frontAudio: true },
        { front: "die neuen Tische", back: "the new tables", frontAudio: true },
        { front: "Das Auto ist neu.", back: "The car is new.", frontAudio: true },
        { front: "mit einem neuen Auto", back: "with a new car", frontAudio: true },
      ],
    },
  ],
};

export const wohnen: Unit = {
  id: "wohnen",
  title: "Wohnen",
  theme: "Living",
  lessons: [
    meinZuhause,
    woWohntWas,
    wohinGehtEs,
    adjektivendungen,
    farben,
    wohnungsanzeigen,
  ],
};