import type { Lesson, Unit } from "../../schema";

const meinZuhause: Lesson = {
  id: "mein-zuhause",
  title: "Mein Zuhause",
  summary: "Rooms, furniture, and describing where things are.",
  status: "ready",
  sections: [
    {
      heading: "Die Räume",
      blocks: [
        {
          type: "table",
          caption: "Rooms",
          head: ["German", "English"],
          rows: [
            ["die Wohnung", "the apartment"],
            ["das Haus", "the house"],
            ["das Wohnzimmer", "the living room"],
            ["die Küche", "the kitchen"],
            ["das Schlafzimmer", "the bedroom"],
            ["das Kinderzimmer", "the children's room"],
            ["das Bad", "the bathroom"],
            ["der Flur", "the hallway"],
            ["der Balkon", "the balcony"],
            ["die Toilette", "the toilet"],
          ],
        },
      ],
    },
    {
      heading: "Die Möbel",
      blocks: [
        {
          type: "table",
          caption: "Furniture",
          head: ["German", "English"],
          rows: [
            ["der Tisch", "the table"],
            ["der Stuhl", "the chair"],
            ["das Sofa", "the sofa"],
            ["der Sessel", "the armchair"],
            ["der Schrank", "the cupboard"],
            ["das Bett", "the bed"],
            ["das Regal", "the shelf"],
            ["die Lampe", "the lamp"],
            ["der Kühlschrank", "the fridge"],
            ["der Herd", "the stove"],
            ["das Fenster", "the window"],
            ["die Tür", "the door"],
          ],
        },
        {
          type: "example",
          de: "Das Sofa steht im Wohnzimmer.",
          en: "The sofa stands in the living room.",
        },
        {
          type: "example",
          de: "Ich wohne in einer Wohnung im dritten Stock.",
          en: "I live in an apartment on the third floor.",
        },
        {
          type: "tip",
          text: "Zimmer is already a room; it does not need a second word. Das Wohnzimmer is the living room, das Schlafzimmer the bedroom.",
        },
      ],
    },
  ],
  vocab: [
    { id: "die-wohnung", de: "die Wohnung", en: "the apartment", part: "noun f.", plural: "die Wohnungen", audio: true },
    { id: "das-wohnzimmer", de: "das Wohnzimmer", en: "the living room", part: "noun n.", plural: "die Wohnzimmer", audio: true },
    { id: "die-kueche", de: "die Küche", en: "the kitchen", part: "noun f.", plural: "die Küchen", audio: true },
    { id: "das-schlafzimmer", de: "das Schlafzimmer", en: "the bedroom", part: "noun n.", plural: "die Schlafzimmer", audio: true },
    { id: "das-bad", de: "das Bad", en: "the bathroom", part: "noun n.", plural: "die Bäder", audio: true },
    { id: "der-balkon", de: "der Balkon", en: "the balcony", part: "noun m.", plural: "die Balkone", audio: true },
    { id: "der-tisch", de: "der Tisch", en: "the table", part: "noun m.", plural: "die Tische", audio: true },
    { id: "der-stuhl", de: "der Stuhl", en: "the chair", part: "noun m.", plural: "die Stühle", audio: true },
    { id: "das-sofa", de: "das Sofa", en: "the sofa", part: "noun n.", plural: "die Sofas", audio: true },
    { id: "der-schrank", de: "der Schrank", en: "the cupboard", part: "noun m.", plural: "die Schränke", audio: true },
    { id: "das-bett", de: "das Bett", en: "the bed", part: "noun n.", plural: "die Betten", audio: true },
    { id: "das-fenster", de: "das Fenster", en: "the window", part: "noun n.", plural: "die Fenster", audio: true },
    { id: "die-tuer", de: "die Tür", en: "the door", part: "noun f.", plural: "die Türen", audio: true },
    { id: "die-lampe", de: "die Lampe", en: "the lamp", part: "noun f.", plural: "die Lampen", audio: true },
    { id: "der-kuehlschrank", de: "der Kühlschrank", en: "the fridge", part: "noun m.", plural: "die Kühlschränke", audio: true },
  ],
  exercises: [
    {
      id: "mc-raum",
      type: "multiple-choice",
      title: "Welcher Raum?",
      instruction: "Choose the room for the activity.",
      prompt: "Wo kochst du? In der ...",
      options: ["Küche", "Toilette", "Bad"],
      correctIndex: 0,
      explain: "You cook in der Küche.",
    },
    {
      id: "listening-raum",
      type: "listening",
      title: "Welcher Raum?",
      instruction: "Play the audio and pick the room you heard.",
      prompt: "das Schlafzimmer",
      options: ["das Schlafzimmer", "das Wohnzimmer", "das Kinderzimmer"],
      correctIndex: 0,
    },
    {
      id: "fill-raum",
      type: "fill-blank",
      title: "Mein Zuhause",
      instruction: "Complete the sentences.",
      sentence: "Ich wohne in einer ___. Das Sofa steht im ___.",
      blanks: [
        { answers: ["Wohnung"], hint: "apartment" },
        { answers: ["Wohnzimmer"], hint: "living room" },
      ],
    },
    {
      id: "matching-raum",
      type: "matching",
      title: "Räume und Möbel",
      instruction: "Match each German word to its meaning.",
      pairs: [
        ["die Küche", "the kitchen"],
        ["das Bett", "the bed"],
        ["der Schrank", "the cupboard"],
        ["das Fenster", "the window"],
        ["der Balkon", "the balcony"],
      ],
    },
    {
      id: "word-order-raum",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: The sofa stands in the living room.",
      chunks: ["Das", "Sofa", "steht", "im", "Wohnzimmer."],
      explain: "im is in dem, the dative contraction.",
    },
    {
      id: "flashcard-raum",
      type: "flashcard",
      title: "Raumkarten",
      instruction: "Say the German word out loud before revealing.",
      items: [
        { front: "die Küche", back: "the kitchen", frontAudio: true },
        { front: "das Schlafzimmer", back: "the bedroom", frontAudio: true },
        { front: "das Bad", back: "the bathroom", frontAudio: true },
        { front: "das Sofa", back: "the sofa", frontAudio: true },
        { front: "das Bett", back: "the bed", frontAudio: true },
        { front: "der Balkon", back: "the balcony", frontAudio: true },
      ],
    },
  ],
};

const woWohntWas: Lesson = {
  id: "wo-wohnt-was",
  title: "Wo? Mit dem Dativ",
  summary: "Locations: auf dem Tisch, in der Küche.",
  status: "ready",
  sections: [
    {
      heading: "Wo? Der Dativ",
      blocks: [
        {
          type: "paragraph",
          text: "To say where something is, German uses a preposition plus the dative. The classic table: in the kitchen is in der Küche, on the table is auf dem Tisch.",
        },
        {
          type: "table",
          caption: "Location phrases",
          head: ["German", "English"],
          rows: [
            ["auf dem Tisch", "on the table"],
            ["in der Küche", "in the kitchen"],
            ["in dem Wohnzimmer", "in the living room"],
            ["an der Wand", "on the wall"],
            ["unter dem Bett", "under the bed"],
            ["vor dem Haus", "in front of the house"],
            ["hinter dem Sofa", "behind the sofa"],
            ["neben dem Schrank", "next to the cupboard"],
            ["zwischen den Stühlen", "between the chairs"],
          ],
        },
        {
          type: "tip",
          text: "The question is Wo? (where, static). With a static location, masculine and neuter articles become dem, feminine and plural become der and den.",
        },
      ],
    },
    {
      heading: "Die Kontraktionen",
      blocks: [
        {
          type: "paragraph",
          text: "in dem and an dem almost always contract in speech.",
        },
        {
          type: "table",
          caption: "Contractions",
          head: ["Full form", "Contracted"],
          rows: [
            ["in dem Wohnzimmer", "im Wohnzimmer"],
            ["an dem Tisch", "am Tisch"],
            ["auf das Sofa", "aufs Sofa"],
            ["in das Bett", "ins Bett"],
          ],
        },
      ],
    },
    {
      heading: "stehen, liegen, hängen",
      blocks: [
        {
          type: "example",
          de: "Das Buch liegt auf dem Tisch.",
          en: "The book lies on the table.",
        },
        {
          type: "example",
          de: "Die Lampe hängt an der Wand.",
          en: "The lamp hangs on the wall.",
        },
        {
          type: "example",
          de: "Der Hund schläft unter dem Bett.",
          en: "The dog sleeps under the bed.",
        },
        {
          type: "tip",
          text: "Three static verbs: stehen (standing up), liegen (lying flat), hängen (hanging). They always pair with Wo? + dative.",
        },
      ],
    },
  ],
  vocab: [
    { id: "auf", de: "auf", en: "on", part: "preposition", audio: true },
    { id: "unter", de: "unter", en: "under", part: "preposition", audio: true },
    { id: "ueber", de: "über", en: "over, above", part: "preposition", audio: true },
    { id: "neben", de: "neben", en: "next to", part: "preposition", audio: true },
    { id: "zwischen", de: "zwischen", en: "between", part: "preposition", audio: true },
    { id: "stehen", de: "stehen", en: "to stand", part: "verb", audio: true },
    { id: "liegen", de: "liegen", en: "to lie (flat)", part: "verb", audio: true },
    { id: "haengen", de: "hängen", en: "to hang", part: "verb", audio: true },
    { id: "auf-dem-tisch", de: "auf dem Tisch", en: "on the table", part: "phrase", phrase: true, audio: true },
    { id: "in-der-kueche", de: "in der Küche", en: "in the kitchen", part: "phrase", phrase: true, audio: true },
    { id: "an-der-wand", de: "an der Wand", en: "on the wall", part: "phrase", phrase: true, audio: true },
    { id: "unter-dem-bett", de: "unter dem Bett", en: "under the bed", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "mc-wo",
      type: "multiple-choice",
      title: "Wo ist es?",
      instruction: "Choose the correct location phrase.",
      prompt: "Das Buch liegt ___.",
      options: ["auf dem Tisch", "auf den Tisch", "auf der Tisch"],
      correctIndex: 0,
      explain: "Static location takes the dative: auf dem Tisch.",
    },
    {
      id: "listening-wo",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the phrase you heard.",
      prompt: "unter dem Bett",
      options: ["unter dem Bett", "neben dem Bett", "auf dem Bett"],
      correctIndex: 0,
    },
    {
      id: "fill-wo",
      type: "fill-blank",
      title: "Wo?",
      instruction: "Complete the location phrases.",
      sentence: "Das Buch liegt ___ dem Tisch. Die Lampe hängt ___ der Wand.",
      blanks: [
        { answers: ["auf"], hint: "on" },
        { answers: ["an"], hint: "on the wall" },
      ],
    },
    {
      id: "matching-wo",
      type: "matching",
      title: "Lage",
      instruction: "Match each German phrase to its meaning.",
      pairs: [
        ["auf dem Tisch", "on the table"],
        ["in der Küche", "in the kitchen"],
        ["unter dem Bett", "under the bed"],
        ["an der Wand", "on the wall"],
        ["neben dem Schrank", "next to the cupboard"],
      ],
    },
    {
      id: "word-order-wo",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: The lamp hangs on the wall.",
      chunks: ["Die", "Lampe", "hängt", "an", "der", "Wand."],
      explain: "hängt is second; the dative phrase closes the sentence.",
    },
    {
      id: "flashcard-wo",
      type: "flashcard",
      title: "Lagekarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "auf dem Tisch", back: "on the table", frontAudio: true },
        { front: "in der Küche", back: "in the kitchen", frontAudio: true },
        { front: "unter dem Bett", back: "under the bed", frontAudio: true },
        { front: "an der Wand", back: "on the wall", frontAudio: true },
        { front: "neben dem Sofa", back: "next to the sofa", frontAudio: true },
        { front: "im Wohnzimmer", back: "in the living room", frontAudio: true },
      ],
    },
  ],
};

const wohinGehtEs: Lesson = {
  id: "wohin-geht-es",
  title: "Wohin? Mit dem Akkusativ",
  summary: "Movement: Ich lege das Buch auf den Tisch.",
  status: "ready",
  sections: [
    {
      heading: "Wohin? Der Akkusativ",
      blocks: [
        {
          type: "paragraph",
          text: "Movement toward a place asks Wohin? and takes the accusative. The same preposition changes case: Wo? says dative, Wohin? says accusative.",
        },
        {
          type: "table",
          caption: "Wo? vs Wohin?",
          head: ["Wo? (dative)", "Wohin? (accusative)"],
          rows: [
            ["auf dem Tisch", "auf den Tisch"],
            ["in der Küche", "in die Küche"],
            ["in dem Wohnzimmer", "in das Wohnzimmer"],
            ["an der Wand", "an die Wand"],
            ["unter dem Bett", "unter das Bett"],
          ],
        },
        {
          type: "example",
          de: "Ich lege das Buch auf den Tisch.",
          en: "I put the book on the table.",
        },
        {
          type: "tip",
          text: "The question decides: Wo liegt das Buch? (dative) or Wohin legst du das Buch? (accusative). Movement through a door, into a room, onto a table: all accusative.",
        },
      ],
    },
    {
      heading: "legen, stellen, setzen",
      blocks: [
        {
          type: "paragraph",
          text: "For every static verb there is a movement twin: legen puts something flat, stellen puts something upright, setzen puts someone on a seat.",
        },
        {
          type: "table",
          caption: "Movement and result",
          head: ["Movement (wohin)", "Result (wo)"],
          rows: [
            ["Ich lege das Buch auf den Tisch.", "Das Buch liegt auf dem Tisch."],
            ["Ich stelle die Lampe auf den Tisch.", "Die Lampe steht auf dem Tisch."],
            ["Ich setze das Kind auf den Stuhl.", "Das Kind sitzt auf dem Stuhl."],
          ],
        },
        {
          type: "tip",
          text: "legen -> liegen, stellen -> stehen, setzen -> sitzen. Learn them as pairs; they cover most furniture sentences.",
        },
      ],
    },
  ],
  vocab: [
    { id: "legen", de: "legen", en: "to put (lying flat)", part: "verb", audio: true },
    { id: "stellen", de: "stellen", en: "to put (standing up)", part: "verb", audio: true },
    { id: "setzen", de: "setzen", en: "to sit (someone) down", part: "verb", audio: true },
    { id: "sitzen", de: "sitzen", en: "to sit", part: "verb", audio: true },
    { id: "auf-den-tisch", de: "auf den Tisch", en: "onto the table", part: "phrase", phrase: true, audio: true },
    { id: "in-die-kueche", de: "in die Küche", en: "into the kitchen", part: "phrase", phrase: true, audio: true },
    { id: "in-das-zimmer", de: "in das Zimmer", en: "into the room", part: "phrase", phrase: true, audio: true },
    { id: "an-die-wand", de: "an die Wand", en: "onto the wall", part: "phrase", phrase: true, audio: true },
    { id: "wohin", de: "wohin", en: "where to", part: "question word", audio: true },
  ],
  exercises: [
    {
      id: "mc-wohin",
      type: "multiple-choice",
      title: "Wohin?",
      instruction: "Choose the correct phrase.",
      prompt: "Ich lege das Buch ___.",
      options: ["auf den Tisch", "auf dem Tisch", "auf der Tisch"],
      correctIndex: 0,
      explain: "Movement takes the accusative: auf den Tisch.",
    },
    {
      id: "listening-wohin",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the phrase you heard.",
      prompt: "in die Küche",
      options: ["in die Küche", "in der Küche", "in das Küche"],
      correctIndex: 0,
    },
    {
      id: "fill-wohin",
      type: "fill-blank",
      title: "Wo oder wohin?",
      instruction: "Complete with the right case.",
      sentence: "Ich lege das Buch ___ den Tisch. Das Buch liegt ___ dem Tisch.",
      blanks: [
        { answers: ["auf"], hint: "wohin, accusative" },
        { answers: ["auf"], hint: "wo, dative" },
      ],
    },
    {
      id: "matching-wohin",
      type: "matching",
      title: "Paare",
      instruction: "Match each movement verb to its result verb.",
      pairs: [
        ["legen", "liegen"],
        ["stellen", "stehen"],
        ["setzen", "sitzen"],
        ["gehen", "sein"],
        ["legen (book)", "liegt"],
      ],
    },
    {
      id: "word-order-wohin",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: I put the lamp on the table.",
      chunks: ["Ich", "stelle", "die", "Lampe", "auf", "den", "Tisch."],
      explain: "The accusative direction phrase closes the sentence.",
    },
    {
      id: "flashcard-wohin",
      type: "flashcard",
      title: "Wohin-Karten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "auf den Tisch", back: "onto the table", frontAudio: true },
        { front: "in die Küche", back: "into the kitchen", frontAudio: true },
        { front: "an die Wand", back: "onto the wall", frontAudio: true },
        { front: "legen", back: "to put (flat)", frontAudio: true },
        { front: "stellen", back: "to put (upright)", frontAudio: true },
        { front: "wohin", back: "where to", frontAudio: true },
      ],
    },
  ],
};

const farben: Lesson = {
  id: "farben",
  title: "Farben",
  summary: "Colors and simple adjective use.",
  status: "ready",
  sections: [
    {
      heading: "Die Farben",
      blocks: [
        {
          type: "table",
          caption: "Colors",
          head: ["German", "English"],
          rows: [
            ["rot", "red"],
            ["blau", "blue"],
            ["grün", "green"],
            ["gelb", "yellow"],
            ["orange", "orange"],
            ["lila", "purple"],
            ["braun", "brown"],
            ["schwarz", "black"],
            ["weiß", "white"],
            ["grau", "grey"],
            ["rosa", "pink"],
            ["hellblau", "light blue"],
            ["dunkelgrün", "dark green"],
          ],
        },
        {
          type: "tip",
          text: "hell- makes a color light (hellblau), dunkel- makes it dark (dunkelgrün). Build new colors freely.",
        },
      ],
    },
    {
      heading: "Farben im Satz",
      blocks: [
        {
          type: "example",
          de: "Das Haus ist weiß. Das Auto ist rot.",
          en: "The house is white. The car is red.",
        },
        {
          type: "example",
          de: "Mein Fahrrad ist grün und alt.",
          en: "My bike is green and old.",
        },
        {
          type: "example",
          de: "Welche Farbe hat dein Auto? Es ist blau.",
          en: "What color is your car? It is blue.",
        },
        {
          type: "tip",
          text: "After sein, colors stay bare: Das Auto ist rot. In front of a noun they take endings, which you will learn in A2.",
        },
      ],
    },
  ],
  vocab: [
    { id: "rot", de: "rot", en: "red", part: "adjective", audio: true },
    { id: "blau", de: "blau", en: "blue", part: "adjective", audio: true },
    { id: "gruen", de: "grün", en: "green", part: "adjective", audio: true },
    { id: "gelb", de: "gelb", en: "yellow", part: "adjective", audio: true },
    { id: "braun", de: "braun", en: "brown", part: "adjective", audio: true },
    { id: "schwarz", de: "schwarz", en: "black", part: "adjective", audio: true },
    { id: "weiss", de: "weiß", en: "white", part: "adjective", audio: true },
    { id: "grau", de: "grau", en: "grey", part: "adjective", audio: true },
    { id: "rosa", de: "rosa", en: "pink", part: "adjective", audio: true },
    { id: "lila", de: "lila", en: "purple", part: "adjective", audio: true },
    { id: "hellblau", de: "hellblau", en: "light blue", part: "adjective", audio: true },
    { id: "dunkelgruen", de: "dunkelgrün", en: "dark green", part: "adjective", audio: true },
    { id: "die-farbe", de: "die Farbe", en: "the color", part: "noun f.", plural: "die Farben", audio: true },
    { id: "welche-farbe", de: "Welche Farbe hat ...?", en: "What color is ...?", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "mc-farben",
      type: "multiple-choice",
      title: "Das Gegenteil",
      instruction: "Choose the opposite color.",
      prompt: "Das Gegenteil von weiß ist ...",
      options: ["schwarz", "grau", "braun"],
      correctIndex: 0,
      explain: "white and black are opposites.",
    },
    {
      id: "listening-farben",
      type: "listening",
      title: "Welche Farbe?",
      instruction: "Play the audio and pick the color you heard.",
      prompt: "grün",
      options: ["grün", "grau", "gelb"],
      correctIndex: 0,
    },
    {
      id: "fill-farben",
      type: "fill-blank",
      title: "Die Farbe",
      instruction: "Complete the sentences.",
      sentence: "Das Auto ist ___. (red) Meine Tür ist ___. (white)",
      blanks: [
        { answers: ["rot"], hint: "red" },
        { answers: ["weiß"], hint: "white" },
      ],
    },
    {
      id: "matching-farben",
      type: "matching",
      title: "Farben",
      instruction: "Match each color to its meaning.",
      pairs: [
        ["rot", "red"],
        ["blau", "blue"],
        ["grün", "green"],
        ["schwarz", "black"],
        ["weiß", "white"],
      ],
    },
    {
      id: "word-order-farben",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: My bike is green.",
      chunks: ["Mein", "Fahrrad", "ist", "grün."],
      explain: "The color follows sein without an ending.",
    },
    {
      id: "flashcard-farben",
      type: "flashcard",
      title: "Farbkarten",
      instruction: "Say the German color out loud before revealing.",
      items: [
        { front: "rot", back: "red", frontAudio: true },
        { front: "blau", back: "blue", frontAudio: true },
        { front: "grün", back: "green", frontAudio: true },
        { front: "gelb", back: "yellow", frontAudio: true },
        { front: "schwarz", back: "black", frontAudio: true },
        { front: "weiß", back: "white", frontAudio: true },
      ],
    },
  ],
};

const wohnungsanzeigen: Lesson = {
  id: "wohnungsanzeigen",
  title: "Wohnungsanzeigen",
  summary: "Reading apartment ads: Zimmer, Miete, Balkon.",
  status: "ready",
  sections: [
    {
      heading: "Die Anzeige",
      blocks: [
        {
          type: "example",
          de: "2-Zimmer-Wohnung, 58 qm, 3. Stock, Balkon, renoviert. Miete 850 Euro kalt, zzgl. Nebenkosten.",
          en: "Two-room apartment, 58 sqm, third floor, balcony, renovated. Rent 850 euros cold, plus utilities.",
        },
        {
          type: "table",
          caption: "Ad vocabulary",
          head: ["German", "English"],
          rows: [
            ["die Wohnung", "the apartment"],
            ["das Zimmer", "the room"],
            ["der Quadratmeter (qm)", "the square meter"],
            ["der Stock / das Erdgeschoss", "the floor / ground floor"],
            ["der Balkon", "the balcony"],
            ["renoviert", "renovated"],
            ["die Miete", "the rent"],
            ["kalt (Kaltmiete)", "without utilities"],
            ["warm (Warmmiete)", "including utilities"],
            ["die Nebenkosten", "the utilities"],
            ["die Kaution", "the deposit"],
            ["der Vermieter", "the landlord"],
          ],
        },
      ],
    },
    {
      heading: "Die Anzeige verstehen",
      blocks: [
        {
          type: "paragraph",
          text: "Kalt means rent without utilities, warm means everything included. Advertisements almost always quote the cold rent and add zzgl. Nebenkosten (plus utilities).",
        },
        {
          type: "example",
          de: "Die Wohnung ist im dritten Stock. Sie hat zwei Zimmer und einen Balkon.",
          en: "The apartment is on the third floor. It has two rooms and a balcony.",
        },
        {
          type: "example",
          de: "Die Miete ist 850 Euro kalt. Die Kaution ist 1.700 Euro.",
          en: "The rent is 850 euros cold. The deposit is 1,700 euros.",
        },
        {
          type: "tip",
          text: "Floor counting starts at the ground floor: das Erdgeschoss, then der erste Stock, der zweite Stock, der dritte Stock. The first floor is NOT the ground floor.",
        },
      ],
    },
  ],
  vocab: [
    { id: "das-zimmer", de: "das Zimmer", en: "the room", part: "noun n.", plural: "die Zimmer", audio: true },
    { id: "der-quadratmeter", de: "der Quadratmeter", en: "the square meter", part: "noun m.", plural: "die Quadratmeter", audio: true },
    { id: "der-stock", de: "der Stock", en: "the floor", part: "noun m.", plural: "die Stockwerke", audio: true },
    { id: "das-erdgeschoss", de: "das Erdgeschoss", en: "the ground floor", part: "noun n.", plural: "die Erdgeschosse", audio: true },
    { id: "die-miete", de: "die Miete", en: "the rent", part: "noun f.", plural: "die Mieten", audio: true },
    { id: "die-nebenkosten", de: "die Nebenkosten", en: "the utilities", part: "noun pl.", plural: "-", audio: true },
    { id: "die-kaution", de: "die Kaution", en: "the deposit", part: "noun f.", plural: "die Kautionen", audio: true },
    { id: "der-vermieter", de: "der Vermieter", en: "the landlord", part: "noun m.", plural: "die Vermieter", audio: true },
    { id: "renoviert", de: "renoviert", en: "renovated", part: "adjective", audio: true },
    { id: "kalt", de: "kalt", en: "cold (rent without utilities)", part: "adjective", audio: true },
    { id: "warm", de: "warm", en: "warm (rent with utilities)", part: "adjective", audio: true },
    { id: "mieten", de: "mieten", en: "to rent", part: "verb", audio: true },
  ],
  exercises: [
    {
      id: "mc-anzeigen",
      type: "multiple-choice",
      title: "Die Anzeige",
      instruction: "Read the ad and answer.",
      prompt: "In einer Anzeige steht: 2-Zimmer-Wohnung, 3. Stock. Wie viele Zimmer hat die Wohnung?",
      options: ["zwei", "drei", "58"],
      correctIndex: 0,
      explain: "2-Zimmer means two rooms.",
    },
    {
      id: "listening-anzeigen",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the word you heard.",
      prompt: "die Nebenkosten",
      options: ["die Nebenkosten", "die Kaution", "die Miete"],
      correctIndex: 0,
    },
    {
      id: "fill-anzeigen",
      type: "fill-blank",
      title: "Die Anzeige",
      instruction: "Complete the ad sentences.",
      sentence: "Die Wohnung ist im dritten ___. Die Miete ist 850 Euro ___.",
      blanks: [
        { answers: ["Stock"], hint: "floor" },
        { answers: ["kalt"], hint: "without utilities" },
      ],
    },
    {
      id: "matching-anzeigen",
      type: "matching",
      title: "Anzeigenvokabular",
      instruction: "Match each German word to its meaning.",
      pairs: [
        ["die Miete", "the rent"],
        ["die Kaution", "the deposit"],
        ["der Balkon", "the balcony"],
        ["das Erdgeschoss", "the ground floor"],
        ["renoviert", "renovated"],
      ],
    },
    {
      id: "word-order-anzeigen",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: The apartment has two rooms.",
      chunks: ["Die", "Wohnung", "hat", "zwei", "Zimmer."],
      explain: "hat is second; the rooms follow.",
    },
    {
      id: "flashcard-anzeigen",
      type: "flashcard",
      title: "Anzeigenkarten",
      instruction: "Say the German word out loud before revealing.",
      items: [
        { front: "die Miete", back: "the rent", frontAudio: true },
        { front: "die Nebenkosten", back: "the utilities", frontAudio: true },
        { front: "die Kaution", back: "the deposit", frontAudio: true },
        { front: "das Erdgeschoss", back: "the ground floor", frontAudio: true },
        { front: "der Balkon", back: "the balcony", frontAudio: true },
        { front: "der Vermieter", back: "the landlord", frontAudio: true },
      ],
    },
  ],
};

const adjektivendungen: Lesson = {
  id: "adjektivendungen",
  title: "Adjektivendungen",
  summary: "Describe people and places with simple, correct adjective endings.",
  status: "ready",
  sections: [
    {
      heading: "Adjektive vor Nomen",
      blocks: [
        {
          type: "paragraph",
          text: "After sein, adjectives stay bare: Das Haus ist groß. But in front of a noun, the adjective takes an ending that matches the noun's gender: ein großes Haus, eine große Küche, ein neuer Computer. The ending tells the listener which gender follows.",
        },
        {
          type: "table",
          caption: "Endings after ein (nominative)",
          head: ["Gender", "Noun", "Example"],
          rows: [
            ["masculine", "der Computer", "ein neuer Computer"],
            ["feminine", "die Küche", "eine neue Küche"],
            ["neuter", "das Haus", "ein neues Haus"],
            ["plural", "die Schuhe", "meine neuen Schuhe"],
          ],
        },
        {
          type: "tip",
          text: "The endings rhyme with the article: ein neuter r (neuer), eine with e (neue), ein neuter s (neues). Say them aloud and your ear will learn them faster than your eyes.",
        },
      ],
    },
    {
      heading: "Endungen nach der, die, das",
      blocks: [
        {
          type: "paragraph",
          text: "After the definite article the endings change: -e appears after der and die and das, and the plural takes -en. This is the other half of the system.",
        },
        {
          type: "table",
          caption: "Endings after der/die/das (nominative)",
          head: ["Gender", "Example"],
          rows: [
            ["masculine", "der neue Computer"],
            ["feminine", "die neue Küche"],
            ["neuter", "das neue Haus"],
            ["plural", "die neuen Schuhe"],
          ],
        },
        {
          type: "example",
          de: "Das ist der neue Computer. Das ist ein neuer Computer.",
          en: "This is the new computer. This is a new computer.",
        },
      ],
    },
    {
      heading: "Der Akkusativ",
      blocks: [
        {
          type: "paragraph",
          text: "In the accusative, only the masculine changes: ein neuen becomes einen neuen, and after den the ending is -en. Everything else stays the same.",
        },
        {
          type: "table",
          caption: "Accusative endings",
          head: ["Noun", "After ein", "After der"],
          rows: [
            ["der Computer (m.)", "einen neuen Computer", "den neuen Computer"],
            ["die Küche (f.)", "eine neue Küche", "die neue Küche"],
            ["das Haus (n.)", "ein neues Haus", "das neue Haus"],
            ["die Schuhe (pl.)", "neue Schuhe", "die neuen Schuhe"],
          ],
        },
        {
          type: "example",
          de: "Ich kaufe einen neuen Computer. Sie hat ein neues Auto.",
          en: "I am buying a new computer. She has a new car.",
        },
        {
          type: "tip",
          text: "A1 only needs these two rows: nominative and accusative, and only the masculine changes in the accusative. The full system arrives in A2; this is already enough to describe your things correctly.",
        },
      ],
    },
  ],
  vocab: [
    { id: "neu", de: "neu", en: "new", part: "adjective", audio: true },
    { id: "gross", de: "groß", en: "big", part: "adjective", audio: true },
    { id: "klein", de: "klein", en: "small", part: "adjective", audio: true },
    { id: "jung", de: "jung", en: "young", part: "adjective", audio: true },
    { id: "schoen", de: "schön", en: "beautiful", part: "adjective", audio: true },
    { id: "teuer", de: "teuer", en: "expensive", part: "adjective", audio: true },
    { id: "billig", de: "billig", en: "cheap", part: "adjective", audio: true },
    { id: "gut", de: "gut", en: "good", part: "adjective", audio: true },
    { id: "ein-neuer-computer", de: "ein neuer Computer", en: "a new computer", part: "phrase", phrase: true, audio: true },
    { id: "eine-neue-kueche", de: "eine neue Küche", en: "a new kitchen", part: "phrase", phrase: true, audio: true },
    { id: "ein-neues-haus", de: "ein neues Haus", en: "a new house", part: "phrase", phrase: true, audio: true },
    { id: "einen-neuen", de: "einen neuen Computer", en: "a new computer (accusative)", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "mc-adjektivendung",
      type: "multiple-choice",
      title: "Die Endung",
      instruction: "Choose the correct adjective ending.",
      prompt: "Das ist ein ___ Computer.",
      options: ["neuer", "neue", "neues"],
      correctIndex: 0,
      explain: "Masculine after ein takes -er: neuer.",
    },
    {
      id: "listening-adjektivendung",
      type: "listening",
      title: "Was hörst du?",
      instruction: "Play the audio and pick the phrase you heard.",
      prompt: "ein neues Haus",
      options: ["ein neues Haus", "ein neuer Haus", "eine neue Haus"],
      correctIndex: 0,
    },
    {
      id: "fill-adjektivendung",
      type: "fill-blank",
      title: "Die Endungen",
      instruction: "Complete with the right endings.",
      sentence: "Das ist ein ___ Computer. (neu) Ich kaufe einen ___ Computer. (neu)",
      blanks: [
        { answers: ["neuer"], hint: "nominative, masculine" },
        { answers: ["neuen"], hint: "accusative, masculine" },
      ],
    },
    {
      id: "matching-adjektivendung",
      type: "matching",
      title: "Artikel und Endung",
      instruction: "Match each article to its ending.",
      pairs: [
        ["ein Computer", "-er"],
        ["eine Küche", "-e"],
        ["ein Haus", "-es"],
        ["den Computer", "-en"],
        ["die neuen Schuhe", "-en (plural)"],
      ],
    },
    {
      id: "word-order-adjektivendung",
      type: "word-order",
      title: "Der Satz",
      instruction: "Build the sentence: I am buying a new computer.",
      chunks: ["Ich", "kaufe", "einen", "neuen", "Computer."],
      explain: "Accusative masculine: einen neuen.",
    },
    {
      id: "flashcard-adjektivendung",
      type: "flashcard",
      title: "Endungskarten",
      instruction: "Say the German phrase out loud before revealing.",
      items: [
        { front: "ein neuer Computer", back: "a new computer", frontAudio: true },
        { front: "eine neue Küche", back: "a new kitchen", frontAudio: true },
        { front: "ein neues Haus", back: "a new house", frontAudio: true },
        { front: "der neue Computer", back: "the new computer", frontAudio: true },
        { front: "einen neuen Computer", back: "a new computer (accusative)", frontAudio: true },
        { front: "meine neuen Schuhe", back: "my new shoes", frontAudio: true },
      ],
    },
  ],
};

export const wohnen: Unit = {
  id: "wohnen",
  title: "Wohnen",
  theme: "Living",
  lessons: [
    meinZuhause,
    woWohntWas,
    wohinGehtEs,
    adjektivendungen,
    farben,
    wohnungsanzeigen,
  ],
};