import type { Lesson } from "../../schema";

export const wortstellungIntensiv: Lesson = {
  id: "wortstellung-intensiv",
  title: "Wortstellung intensiv: alle Verbpositionen im Überblick",
  summary:
    "The complete word order system beyond the basics: the three verb positions, the sentence frame with the full verb complex, object order, adverb order with nicht, subordinate and relative clauses, and prepositional questions, all with glossed examples and intensive practice.",
  status: "ready",
  sections: [
    {
      heading: "Die drei Positionen des Verbs",
      blocks: [
        {
          type: "paragraph",
          text: "Every German sentence puts its finite verb in one of exactly three places. Position 2 for statements and W-questions: Ich lerne Deutsch. / Wo wohnst du? Position 1 for yes/no questions, imperatives, and the main clause that follows a subordinate clause: Lernst du Deutsch? / Komm her! / Weil es regnet, bleibe ich zu Hause. Verb-last for subordinate clauses: weil es regnet. If you know which of the three applies, you know where the verb goes.",
        },
        {
          type: "table",
          caption: "One verb, three positions",
          head: ["Clause type", "Position 1", "Position 2", "Verb position", "Example"],
          rows: [
            ["Statement", "subject or topic", "verb", "2", "Ich lerne Deutsch."],
            ["W-question", "question word", "verb", "2", "Wo wohnst du?"],
            ["Yes/no question", "verb", "subject", "1", "Lernst du Deutsch?"],
            ["Imperative", "verb", "rest", "1", "Komm her!"],
            ["Subordinate clause", "conjunction", "rest", "last", "weil es regnet."],
          ],
          rowSpeak: ["Ich lerne Deutsch.", "Wo wohnst du?", "Lernst du Deutsch?", "Komm her!", "weil es regnet"],
        },
        {
          type: "gloss",
          de: "Weil es regnet, bleibe ich zu Hause.",
          en: "Because it is raining, I stay at home.",
          words: [
            { word: "Weil", pos: "Konjunktion", en: "because", detail: "Subordinating conjunction" },
            { word: "es", pos: "Pronomen", en: "it", detail: "Subject of the subordinate clause" },
            { word: "regnet,", pos: "Verb", en: "is raining", detail: "Verb last in the subordinate clause" },
            { word: "bleibe", pos: "Verb", en: "stay", detail: "Main clause starts with the verb (position 1)" },
            { word: "ich", pos: "Pronomen", en: "I", detail: "Subject after the verb" },
            { word: "zu Hause.", pos: "Adverb", en: "at home", detail: "Place" },
          ],
        },
        {
          type: "tip",
          text: "The verb position changes, but the verb itself never moves to a fourth place. Spot the clause type first, then the verb falls into position 1, 2, or last.",
        },
      ],
    },
    {
      heading: "Der Satzrahmen und der Verbkomplex",
      blocks: [
        {
          type: "paragraph",
          text: "The sentence frame already works with one closing part. When a verb group has several parts, they all pile up at the end in a fixed order. With a modal verb, the infinitive closes the frame: Ich möchte einen Kaffee trinken. In the perfect tense the participle closes it: Ich habe den Kaffee getrunken. In the perfect tense of a modal verb, both the main infinitive and the modal infinitive stand at the end: Ich habe den Kaffee trinken wollen.",
        },
        {
          type: "gloss",
          de: "Ich habe das Buch lesen wollen.",
          en: "I wanted to read the book.",
          words: [
            { word: "Ich", pos: "Pronomen", en: "I", detail: "Subject" },
            { word: "habe", pos: "Verb", en: "have", detail: "Auxiliary, opens the frame" },
            { word: "das Buch", pos: "Nomen", en: "the book", detail: "Accusative object" },
            { word: "lesen", pos: "Verb", en: "to read", detail: "Main verb infinitive" },
            { word: "wollen.", pos: "Verb", en: "to want", detail: "Modal infinitive, closes the frame" },
          ],
        },
        {
          type: "table",
          caption: "The verb complex at the end",
          head: ["Opening", "Middle", "Closing"],
          rows: [
            ["Ich möchte", "einen Kaffee", "trinken."],
            ["Ich habe", "den Kaffee", "getrunken."],
            ["Ich habe", "den Kaffee trinken", "wollen."],
            ["Du musst", "um acht Uhr", "aufstehen."],
          ],
          rowSpeak: ["Ich möchte einen Kaffee trinken.", "Ich habe den Kaffee getrunken.", "Ich habe den Kaffee trinken wollen.", "Du musst um acht Uhr aufstehen."],
        },
        {
          type: "tip",
          text: "Nothing comes after the closing part. Ich habe den Kaffee trinken wollen. is complete. English spreads these parts out; German stacks them at the end, so wait for the last word before you know the full meaning.",
        },
      ],
    },
    {
      heading: "Die Reihenfolge der Objekte",
      blocks: [
        {
          type: "paragraph",
          text: "With two objects the order follows one rule: pronouns first, nouns after. If both are nouns, the dative comes before the accusative: Ich gebe dem Mann das Buch. If both are pronouns, the accusative comes before the dative: Ich gebe es ihm. A pronoun always pushes past a noun, even a dative noun: Ich gebe es dem Mann.",
        },
        {
          type: "gloss",
          de: "Ich gebe dem Mann das Buch.",
          en: "I give the man the book.",
          words: [
            { word: "Ich", pos: "Pronomen", en: "I", detail: "Subject" },
            { word: "gebe", pos: "Verb", en: "give", detail: "Verb in position 2" },
            { word: "dem Mann", pos: "Nomen", en: "the man", detail: "Dative object, before the accusative" },
            { word: "das Buch.", pos: "Nomen", en: "the book", detail: "Accusative object" },
          ],
        },
        {
          type: "table",
          caption: "Nouns vs pronouns",
          head: ["Both nouns", "One pronoun", "Both pronouns"],
          rows: [
            ["Ich gebe dem Mann das Buch.", "Ich gebe es dem Mann.", "Ich gebe es ihm."],
            ["Er schickt der Mutter einen Brief.", "Er schickt ihn der Mutter.", "Er schickt ihn ihr."],
          ],
          rowSpeak: ["Ich gebe dem Mann das Buch.", "Er schickt der Mutter einen Brief."],
        },
        {
          type: "tip",
          text: "The shortest words go first: pronouns before nouns, and among pronouns accusative before dative. Ich gebe es ihm. sounds natural; Ich gebe ihm es. does not.",
        },
      ],
    },
    {
      heading: "Te-ka-mo-lo und die Stellung von nicht",
      blocks: [
        {
          type: "paragraph",
          text: "Adverbials run in a fixed order: time (temporal), reason (kausal), manner (modal), place (lokal) — te-ka-mo-lo. At A2 you mostly need time, manner, place: Ich fahre morgen mit dem Zug nach Berlin. The negation nicht stands directly before the element it negates, and before the closing part of a frame when it negates the whole action: Ich habe das Buch nicht gelesen.",
        },
        {
          type: "example",
          de: "Ich fahre morgen mit dem Zug nach Berlin.",
          en: "I am travelling to Berlin by train tomorrow. (time, manner, place)",
        },
        {
          type: "example",
          de: "Ich habe das Buch nicht gelesen.",
          en: "I did not read the book. (nicht before the participle)",
        },
        {
          type: "table",
          caption: "nicht in context",
          head: ["Sentence", "What nicht negates"],
          rows: [
            ["Ich komme nicht.", "the whole action"],
            ["Ich komme nicht mit.", "the separable prefix (not coming along)"],
            ["Ich habe das Buch nicht gelesen.", "the whole action, before the frame closer"],
            ["Ich habe nicht das Buch gelesen.", "the book (I read something else)"],
          ],
          rowSpeak: ["Ich komme nicht.", "Ich komme nicht mit.", "Ich habe das Buch nicht gelesen.", "Ich habe nicht das Buch gelesen."],
        },
        {
          type: "tip",
          text: "nicht negates what follows it. Move it and the meaning changes: nicht das Buch means not the book, das Buch nicht means I did not read it.",
        },
      ],
    },
    {
      heading: "Nebensätze im Detail",
      blocks: [
        {
          type: "paragraph",
          text: "Subordinating conjunctions send the verb to the end. The most common ones are weil (because), dass (that), wenn (when, if), obwohl (although), als (when, one past occasion), bevor (before) and nachdem (after). The main clause keeps its own order, and when the subordinate clause comes first, the main clause opens with the verb.",
        },
        {
          type: "example",
          de: "Ich komme, wenn ich Zeit habe.",
          en: "I am coming when I have time.",
        },
        {
          type: "example",
          de: "Bevor ich schlafe, lese ich ein Buch.",
          en: "Before I sleep, I read a book.",
        },
        {
          type: "table",
          caption: "Subordinating conjunctions",
          head: ["Conjunction", "English", "Example"],
          rows: [
            ["weil", "because", "Ich bleibe zu Hause, weil es regnet."],
            ["dass", "that", "Ich weiß, dass du Deutsch lernst."],
            ["wenn", "when, if", "Ich komme, wenn ich Zeit habe."],
            ["obwohl", "although", "Obwohl es kalt ist, gehe ich spazieren."],
            ["als", "when (past)", "Als ich klein war, wohnte ich in Berlin."],
            ["bevor", "before", "Bevor ich schlafe, lese ich ein Buch."],
            ["nachdem", "after", "Nachdem ich aufstehe, frühstücke ich."],
          ],
          rowSpeak: ["Ich bleibe zu Hause, weil es regnet.", "Ich weiß, dass du Deutsch lernst.", "Ich komme, wenn ich Zeit habe.", "Obwohl es kalt ist, gehe ich spazieren.", "Als ich klein war, wohnte ich in Berlin.", "Bevor ich schlafe, lese ich ein Buch.", "Nachdem ich aufstehe, frühstücke ich."],
        },
        {
          type: "tip",
          text: "wenn means when or if and is for present and future situations. als means when for one completed moment in the past: Als ich klein war. Do not use wenn for that.",
        },
      ],
    },
    {
      heading: "Relativsätze: der, die, das mit Verb am Ende",
      blocks: [
        {
          type: "paragraph",
          text: "Relative clauses describe a noun and behave like subordinate clauses: the verb goes to the end. The relative pronoun der, die or das matches the noun it refers to. Das ist der Mann, der Deutsch lernt. Das ist die Frau, die in Berlin wohnt. Das ist das Buch, das ich lese.",
        },
        {
          type: "example",
          de: "Das ist der Mann, der Deutsch lernt.",
          en: "This is the man who is learning German.",
        },
        {
          type: "gloss",
          de: "Das ist die Frau, die in Berlin wohnt.",
          en: "This is the woman who lives in Berlin.",
          words: [
            { word: "Das", pos: "Pronomen", en: "this", detail: "Demonstrative pronoun" },
            { word: "ist", pos: "Verb", en: "is", detail: "Verb in position 2" },
            { word: "die Frau,", pos: "Nomen", en: "the woman", detail: "Noun the clause describes" },
            { word: "die", pos: "Pronomen", en: "who", detail: "Relative pronoun, feminine" },
            { word: "in Berlin", pos: "Nomen", en: "in Berlin", detail: "Place" },
            { word: "wohnt.", pos: "Verb", en: "lives", detail: "Verb last in the relative clause" },
          ],
        },
        {
          type: "tip",
          text: "The relative pronoun looks like the article: der, die, das. The clause always ends with the verb, so listen for the verb at the very end.",
        },
      ],
    },
    {
      heading: "W-Fragen mit Präpositionen und der Imperativ",
      blocks: [
        {
          type: "paragraph",
          text: "To ask about a prepositional object, German fuses wo or woher with the preposition: womit (with what), woran (on what), wofür (for what), worüber (about what). These question words take position 1, the verb position 2: Womit fährst du zur Arbeit? The imperative also opens with the verb, and with a separable verb the prefix closes the sentence: Steh bitte um sieben Uhr auf!",
        },
        {
          type: "example",
          de: "Womit fährst du zur Arbeit?",
          en: "What do you drive to work with?",
        },
        {
          type: "example",
          de: "Worüber sprecht ihr?",
          en: "What are you talking about?",
        },
        {
          type: "gloss",
          de: "Steh bitte um sieben Uhr auf!",
          en: "Please get up at seven!",
          words: [
            { word: "Steh", pos: "Verb", en: "get up", detail: "Imperative, verb first" },
            { word: "bitte", pos: "Adverb", en: "please", detail: "Politeness marker" },
            { word: "um sieben Uhr", pos: "Nomen", en: "at seven", detail: "Time" },
            { word: "auf!", pos: "Verb", en: "up", detail: "Separable prefix, closes the sentence" },
          ],
        },
        {
          type: "table",
          caption: "Prepositional question words",
          head: ["Question word", "English", "Example"],
          rows: [
            ["womit", "with what", "Womit fährst du?"],
            ["woran", "on what", "Woran denkst du?"],
            ["wofür", "for what", "Wofür brauchst du das?"],
            ["worüber", "about what", "Worüber sprecht ihr?"],
            ["woher", "from where", "Woher kommst du?"],
          ],
          rowSpeak: ["womit", "woran", "wofür", "worüber", "woher"],
        },
        {
          type: "tip",
          text: "wo + preposition becomes wor- before a vowel: worüber, woran. The question word always fills position 1, so the verb follows it directly.",
        },
      ],
    },
  ],
  vocab: [
    { id: "der-satzrahmen", de: "der Satzrahmen", en: "the sentence frame", part: "noun m.", plural: "die Satzrahmen", audio: true },
    { id: "das-vorfeld", de: "das Vorfeld", en: "the first position", part: "noun n.", plural: "die Vorfelder", audio: true },
    { id: "der-nebensatz", de: "der Nebensatz", en: "the subordinate clause", part: "noun m.", plural: "die Nebensätze", audio: true },
    { id: "der-relativsatz", de: "der Relativsatz", en: "the relative clause", part: "noun m.", plural: "die Relativsätze", audio: true },
    { id: "das-dativobjekt", de: "das Dativobjekt", en: "the dative object", part: "noun n.", plural: "die Dativobjekte", audio: true },
    { id: "das-akkusativobjekt", de: "das Akkusativobjekt", en: "the accusative object", part: "noun n.", plural: "die Akkusativobjekte", audio: true },
    { id: "die-reihenfolge", de: "die Reihenfolge", en: "the order", part: "noun f.", plural: "die Reihenfolgen", audio: true },
    { id: "die-verneinung", de: "die Verneinung", en: "the negation", part: "noun f.", plural: "die Verneinungen", audio: true },
    { id: "der-imperativ", de: "der Imperativ", en: "the imperative", part: "noun m.", plural: "die Imperative", audio: true },
    { id: "das-modalverb", de: "das Modalverb", en: "the modal verb", part: "noun n.", plural: "die Modalverben", audio: true },
    { id: "das-partizip-2", de: "das Partizip II", en: "the past participle", part: "noun n.", plural: "die Partizipien", audio: true },
    { id: "die-stellung", de: "die Stellung", en: "the position", part: "noun f.", plural: "die Stellungen", audio: true },
  ],
  exercises: [
    {
      id: "ex-woi-aussage",
      type: "multiple-choice",
      title: "Übung 1: Die Aussage",
      instruction: "Where does the finite verb stand in a statement?",
      prompt: "In einem Aussagesatz steht das Verb an ___ Stelle.",
      options: ["zweiter", "erster", "letzter"],
      correctIndex: 0,
      explain: "Statements put the verb in position 2, whatever opens the sentence.",
    },
    {
      id: "ex-woi-nebensatz",
      type: "multiple-choice",
      title: "Übung 2: Der Nebensatz",
      instruction: "Where does the verb stand in a subordinate clause?",
      prompt: "In einem Nebensatz steht das Verb ___.",
      options: ["am Ende", "an zweiter Stelle", "an erster Stelle"],
      correctIndex: 0,
      explain: "Subordinating conjunctions send the verb to the very end.",
    },
    {
      id: "ex-woi-dativ-akkusativ",
      type: "word-order",
      title: "Übung 3: Dativ vor Akkusativ",
      instruction: "Build the sentence: I give the man the book.",
      chunks: ["Ich", "gebe", "dem Mann", "das", "Buch."],
      translation: "I give the man the book.",
      explain: "With two nouns, the dative (dem Mann) comes before the accusative (das Buch).",
    },
    {
      id: "ex-woi-pronomen",
      type: "word-order",
      title: "Übung 4: Pronomen vor Nomen",
      instruction: "Build the sentence: I give it to him.",
      chunks: ["Ich", "gebe", "es", "ihm."],
      translation: "I give it to him.",
      explain: "Pronouns come first; the accusative pronoun (es) before the dative pronoun (ihm).",
    },
    {
      id: "ex-woi-nicht",
      type: "word-order",
      title: "Übung 5: nicht im Perfekt",
      instruction: "Build the sentence: I did not read the book.",
      chunks: ["Ich", "habe", "das Buch", "nicht", "gelesen."],
      translation: "I did not read the book.",
      explain: "nicht stands before the participle that closes the frame.",
    },
    {
      id: "ex-woi-doppelinfinitiv",
      type: "word-order",
      title: "Übung 6: Perfekt mit Modalverb",
      instruction: "Build the sentence: I wanted to read the book.",
      chunks: ["Ich", "habe", "das Buch", "lesen", "wollen."],
      translation: "I wanted to read the book.",
      explain: "In the perfect tense of a modal, the infinitive and the modal infinitive close the frame together.",
    },
    {
      id: "ex-woi-weil-zuerst",
      type: "word-order",
      title: "Übung 7: Nebensatz zuerst",
      instruction: "Build the sentence: Because it is raining, I stay at home.",
      chunks: ["Weil", "es", "regnet,", "bleibe", "ich", "zu Hause."],
      translation: "Because it is raining, I stay at home.",
      explain: "The subordinate clause comes first, so the main clause opens with the verb.",
    },
    {
      id: "ex-woi-relativsatz",
      type: "word-order",
      title: "Übung 8: Der Relativsatz",
      instruction: "Build the sentence: This is the man who is learning German.",
      chunks: ["Das", "ist", "der Mann,", "der", "Deutsch", "lernt."],
      translation: "This is the man who is learning German.",
      explain: "The relative clause ends with the verb: der ... lernt.",
    },
    {
      id: "ex-woi-womit",
      type: "word-order",
      title: "Übung 9: Die W-Frage mit Präposition",
      instruction: "Build the question: What do you drive to work with?",
      chunks: ["Womit", "fährst", "du", "zur Arbeit?"],
      translation: "What do you drive to work with?",
      explain: "The prepositional question word fills position 1, the verb follows in position 2.",
    },
    {
      id: "ex-woi-imperativ",
      type: "word-order",
      title: "Übung 10: Der Imperativ",
      instruction: "Build the sentence: Please get up at seven!",
      chunks: ["Steh", "bitte", "um sieben Uhr", "auf!"],
      translation: "Please get up at seven!",
      explain: "The imperative opens with the verb; the separable prefix closes the sentence.",
    },
    {
      id: "ex-woi-nicht-fill",
      type: "fill-blank",
      title: "Übung 11: nicht",
      instruction: "Complete the sentence: I don't understand you.",
      sentence: "Ich verstehe dich ___.",
      translation: "I don't understand you.",
      blanks: [{ answers: ["nicht"] }],
      explain: "nicht negates the whole sentence and stands after the pronoun object.",
    },
    {
      id: "ex-woi-tekamolo",
      type: "multiple-choice",
      title: "Übung 12: Te-ka-mo-lo",
      instruction: "Which element comes first in te-ka-mo-lo?",
      prompt: "In der Reihenfolge te-ka-mo-lo kommt zuerst die ___.",
      options: ["Zeit", "Art und Weise", "der Ort"],
      correctIndex: 0,
      explain: "temporal (time) comes first, then kausal, modal, lokal.",
    },
    {
      id: "ex-woi-konjunktionen",
      type: "matching",
      title: "Übung 13: Konjunktionen",
      instruction: "Match each conjunction with its meaning.",
      pairs: [
        ["als", "when (past)"],
        ["bevor", "before"],
        ["nachdem", "after"],
        ["obwohl", "although"],
        ["während", "while"],
        ["damit", "so that"],
      ],
      explain: "All six are subordinating: they send the verb to the end.",
    },
    {
      id: "ex-woi-hoeren",
      type: "listening",
      title: "Übung 14: Hörverstehen",
      instruction: "Listen and choose the sentence you hear.",
      prompt: "Womit fährst du zur Arbeit?",
      options: [
        "Womit fährst du zur Arbeit?",
        "Wohin fährst du zur Arbeit?",
        "Wann fährst du zur Arbeit?",
      ],
      correctIndex: 0,
      explain: "womit asks about the means of travel.",
    },
    {
      id: "ex-woi-karten",
      type: "flashcard",
      title: "Übung 15: Fachbegriffe",
      instruction: "Say the German term before revealing the meaning.",
      items: [
        { front: "das Vorfeld", back: "the first position", frontAudio: true },
        { front: "der Satzrahmen", back: "the sentence frame", frontAudio: true },
        { front: "der Nebensatz", back: "the subordinate clause", frontAudio: true },
        { front: "der Relativsatz", back: "the relative clause", frontAudio: true },
        { front: "das Dativobjekt", back: "the dative object", frontAudio: true },
        { front: "das Akkusativobjekt", back: "the accusative object", frontAudio: true },
        { front: "die Verneinung", back: "the negation", frontAudio: true },
        { front: "das Partizip II", back: "the past participle", frontAudio: true },
      ],
    },
  ],
};