import type { Lesson } from "../../schema";

export const wortstellungTief: Lesson = {
  id: "wortstellung-erklaert",
  title: "Wortstellung erklärt: German word order",
  summary:
    "The complete German word order system: the verb-second rule, questions, inversion, time-manner-place, the sentence frame, subordinate clauses, and negation, explained in depth with glossed examples and sentence-building practice.",
  status: "ready",
  sections: [
    {
      heading: "Der Aussagesatz: the verb is always second",
      blocks: [
        {
          type: "paragraph",
          text: "German statements follow one rule that never changes: the finite verb is the second element of the sentence. Not the second word, the second element. An element is one logical unit: a subject, a verb, an object, a time phrase, a whole group like nach Berlin. German does not care which element is first, as long as the verb stays in position 2.",
        },
        {
          type: "example",
          de: "Ich lerne Deutsch.",
          en: "I am learning German. (Ich = element 1, lerne = element 2)",
        },
        {
          type: "gloss",
          de: "Heute lerne ich Deutsch.",
          en: "Today I am learning German.",
          words: [
            { word: "Heute", pos: "Adverb", en: "today", detail: "Adverb in position 1" },
            { word: "lerne", pos: "Verb", en: "learn", detail: "Finite verb, still position 2" },
            { word: "ich", pos: "Pronomen", en: "I", detail: "Subject, moved after the verb" },
            { word: "Deutsch", pos: "Nomen", en: "German", detail: "Object, at the end" },
          ],
        },
        {
          type: "tip",
          text: "Position 2 is a slot, not a word count. Heute lerne ich Deutsch. has the verb second even though the sentence starts with Heute. The subject is no longer first, so it moves after the verb. That is inversion, and the verb never leaves position 2.",
        },
        {
          type: "table",
          caption: "Same rule, different openings",
          head: ["Sentence", "Element 1", "Element 2", "Rest"],
          rows: [
            ["Ich lerne Deutsch.", "Ich", "lerne", "Deutsch."],
            ["Heute lerne ich Deutsch.", "Heute", "lerne", "ich Deutsch."],
            ["Im Sommer fahren wir nach Italien.", "Im Sommer", "fahren", "wir nach Italien."],
          ],
          rowSpeak: [
            "Ich lerne Deutsch.",
            "Heute lerne ich Deutsch.",
            "Im Sommer fahren wir nach Italien.",
          ],
        },
      ],
    },
    {
      heading: "Ja/Nein-Fragen: the verb goes first",
      blocks: [
        {
          type: "paragraph",
          text: "A yes/no question swaps the subject and the verb: the verb becomes element 1 and the subject follows it. There is no question word, and the answer is simply ja or nein. The rest of the sentence keeps its normal order.",
        },
        {
          type: "example",
          de: "Lernst du Deutsch?",
          en: "Are you learning German? (verb first, then subject)",
        },
        {
          type: "example",
          de: "Kommst du morgen mit?",
          en: "Are you coming along tomorrow? (separable mit still closes the sentence)",
        },
        {
          type: "table",
          caption: "Statement becomes question",
          head: ["Statement", "Question"],
          rows: [
            ["Du lernst Deutsch.", "Lernst du Deutsch?"],
            ["Sie wohnt in Berlin.", "Wohnt sie in Berlin?"],
            ["Wir gehen ins Kino.", "Gehen wir ins Kino?"],
          ],
          rowSpeak: ["Du lernst Deutsch.", "Sie wohnt in Berlin.", "Wir gehen ins Kino."],
        },
        {
          type: "tip",
          text: "This is exactly the same swap as inversion, just the other way: the verb steps into position 1 because the sentence is a question.",
        },
      ],
    },
    {
      heading: "W-Fragen: question word, verb, subject",
      blocks: [
        {
          type: "paragraph",
          text: "Questions with a question word follow the pattern: question word, verb, subject, rest. The question word is element 1, the verb is element 2, and the subject comes third. This is the same verb-second skeleton, only the question word fills position 1.",
        },
        {
          type: "gloss",
          de: "Wo wohnst du?",
          en: "Where do you live?",
          words: [
            { word: "Wo", pos: "Adverb", en: "where", detail: "Question word in position 1" },
            { word: "wohnst", pos: "Verb", en: "live", detail: "Finite verb in position 2" },
            { word: "du", pos: "Pronomen", en: "you", detail: "Subject in position 3" },
          ],
        },
        {
          type: "table",
          caption: "The most useful question words",
          head: ["Question word", "English", "Example"],
          rows: [
            ["wo", "where", "Wo wohnst du?"],
            ["wann", "when", "Wann kommst du?"],
            ["was", "what", "Was machst du?"],
            ["wer", "who", "Wer ist das?"],
            ["warum", "why", "Warum lernst du Deutsch?"],
            ["wie", "how", "Wie heißt du?"],
            ["wohin", "where to", "Wohin fährst du?"],
          ],
          rowSpeak: ["wo", "wann", "was", "wer", "warum", "wie", "wohin"],
        },
        {
          type: "tip",
          text: "wer, was, wann and warum are question words; wenn is a conjunction that means when or if and pushes the verb to the end. Never mix them up: wer asks, wenn connects.",
        },
      ],
    },
    {
      heading: "Inversion: something else first, subject after the verb",
      blocks: [
        {
          type: "paragraph",
          text: "Statements do not have to start with the subject. Put a time word (heute, morgen, dann), a place, or any other element first, and the verb still stays second. The subject then moves behind the verb. This swap is called inversion, and it is completely normal in German, especially with time words.",
        },
        {
          type: "example",
          de: "Dann gehen wir ins Kino.",
          en: "Then we are going to the cinema.",
        },
        {
          type: "example",
          de: "Im Sommer fahre ich nach Italien.",
          en: "In the summer I am driving to Italy.",
        },
        {
          type: "gloss",
          de: "Morgen besuche ich meine Oma.",
          en: "Tomorrow I am visiting my grandma.",
          words: [
            { word: "Morgen", pos: "Adverb", en: "tomorrow", detail: "Time adverb in position 1" },
            { word: "besuche", pos: "Verb", en: "visit", detail: "Finite verb in position 2" },
            { word: "ich", pos: "Pronomen", en: "I", detail: "Subject after the verb" },
            { word: "meine Oma", pos: "Nomen", en: "my grandma", detail: "Accusative object" },
          ],
        },
        {
          type: "tip",
          text: "Use inversion to put the most important information first. Morgen besuche ich meine Oma. stresses morgen; Ich besuche meine Oma morgen. is neutral. Both are correct: the verb never leaves position 2.",
        },
      ],
    },
    {
      heading: "Te-ka-mo-lo: time, manner, place",
      blocks: [
        {
          type: "paragraph",
          text: "When a sentence has several adverbials, German arranges them in a fixed order: time first, then manner (how), then place (where). The mnemonic te-ka-mo-lo comes from temporal, kausal, modal, lokal; at A1 you mainly need time, manner, place.",
        },
        {
          type: "example",
          de: "Ich fahre morgen mit dem Zug nach Berlin.",
          en: "I am travelling to Berlin by train tomorrow. (time, then manner, then place)",
        },
        {
          type: "table",
          caption: "Building a sentence with all three adverbials",
          head: ["Subject", "Verb", "Time", "Manner", "Place"],
          rows: [
            ["Ich", "fahre", "morgen", "mit dem Zug", "nach Berlin."],
            ["Wir", "treffen uns", "heute Abend", "im Café", "in der Stadt."],
            ["Er", "geht", "jeden Tag", "zu Fuß", "zur Arbeit."],
          ],
          rowSpeak: ["Ich fahre morgen mit dem Zug nach Berlin.", "Wir treffen uns heute Abend im Café in der Stadt.", "Er geht jeden Tag zu Fuß zur Arbeit."],
        },
        {
          type: "tip",
          text: "English often says place before time (I am going to Berlin tomorrow). German does the opposite: time before place. Ich fahre morgen nach Berlin., never Ich fahre nach Berlin morgen.",
        },
      ],
    },
    {
      heading: "Der Satzrahmen: the sentence frame",
      blocks: [
        {
          type: "paragraph",
          text: "Many German verbs are built in two parts. The conjugated part stands in position 2, and the rest closes the sentence at the very end, like a bracket. This is the sentence frame, die Satzklammer. Modal verbs close with an infinitive: Ich möchte einen Kaffee trinken. The perfect tense closes with the participle: Ich habe Deutsch gelernt. Separable verbs close with their prefix: Ich stehe um sieben Uhr auf.",
        },
        {
          type: "gloss",
          de: "Ich habe gestern Deutsch gelernt.",
          en: "I learned German yesterday.",
          words: [
            { word: "Ich", pos: "Pronomen", en: "I", detail: "Subject" },
            { word: "habe", pos: "Verb", en: "have", detail: "Auxiliary, opens the frame" },
            { word: "gestern", pos: "Adverb", en: "yesterday", detail: "Time adverb" },
            { word: "Deutsch", pos: "Nomen", en: "German", detail: "Object" },
            { word: "gelernt", pos: "Verb", en: "learned", detail: "Partizip II, closes the frame" },
          ],
        },
        {
          type: "table",
          caption: "The frame in action",
          head: ["Opening (position 2)", "Middle", "Closing (end)"],
          rows: [
            ["Ich möchte", "einen Kaffee", "trinken."],
            ["Ich habe", "gestern Deutsch", "gelernt."],
            ["Ich stehe", "um sieben Uhr", "auf."],
            ["Der Zug fährt", "um 14:30 Uhr", "ab."],
          ],
          rowSpeak: ["Ich möchte einen Kaffee trinken.", "Ich habe gestern Deutsch gelernt.", "Ich stehe um sieben Uhr auf.", "Der Zug fährt um 14:30 Uhr ab."],
        },
        {
          type: "tip",
          text: "Nothing may come after the closing part. Ich habe gestern Deutsch gelernt. is complete; adding anything after gelernt breaks the frame. When you read or hear a German sentence, wait for the end: the verb group often finishes the sentence.",
        },
      ],
    },
    {
      heading: "Der Nebensatz: subordinate clauses put the verb last",
      blocks: [
        {
          type: "paragraph",
          text: "Conjunctions like weil, dass, wenn and obwohl introduce subordinate clauses, and they change the word order completely: the conjugated verb moves from position 2 to the very END of the clause. Ich bleibe zu Hause, weil es regnet. The main clause keeps its normal order; only the subordinate clause bends.",
        },
        {
          type: "example",
          de: "Ich bleibe zu Hause, weil es regnet.",
          en: "I stay at home because it is raining.",
        },
        {
          type: "example",
          de: "Ich weiß, dass du Deutsch lernst.",
          en: "I know that you are learning German.",
        },
        {
          type: "gloss",
          de: "Weil es regnet, bleibe ich zu Hause.",
          en: "Because it is raining, I stay at home.",
          words: [
            { word: "Weil", pos: "Konjunktion", en: "because", detail: "Subordinating conjunction" },
            { word: "es", pos: "Pronomen", en: "it", detail: "Subject of the subordinate clause" },
            { word: "regnet,", pos: "Verb", en: "is raining", detail: "Verb last in the subordinate clause" },
            { word: "bleibe", pos: "Verb", en: "stay", detail: "Main clause starts with the verb" },
            { word: "ich", pos: "Pronomen", en: "I", detail: "Subject after the verb" },
            { word: "zu Hause.", pos: "Adverb", en: "at home", detail: "Place" },
          ],
        },
        {
          type: "tip",
          text: "When the subordinate clause comes first, the main clause starts with the verb: Weil es regnet, bleibe ich zu Hause. The comma always separates the two clauses.",
        },
        {
          type: "table",
          caption: "The most common subordinating conjunctions",
          head: ["Conjunction", "English", "Example"],
          rows: [
            ["weil", "because", "Ich bleibe zu Hause, weil es regnet."],
            ["dass", "that", "Ich weiß, dass du Deutsch lernst."],
            ["wenn", "when, if", "Ich komme, wenn ich Zeit habe."],
            ["obwohl", "although", "Obwohl es kalt ist, gehe ich spazieren."],
          ],
          rowSpeak: ["weil", "dass", "wenn", "obwohl"],
        },
      ],
    },
    {
      heading: "Negation and imperatives",
      blocks: [
        {
          type: "paragraph",
          text: "nicht stands before the element it negates and closes a whole-sentence negation: Ich verstehe nicht. If a sentence has a frame, nicht goes before the closing part: Ich habe das Buch nicht gelesen. Imperatives are simple: the verb comes first, just like a yes/no question: Komm her! Öffnen Sie bitte die Tür.",
        },
        {
          type: "example",
          de: "Ich verstehe nicht.",
          en: "I do not understand.",
        },
        {
          type: "example",
          de: "Ich habe das Buch nicht gelesen.",
          en: "I did not read the book. (nicht before the closing participle)",
        },
        {
          type: "example",
          de: "Komm her!",
          en: "Come here! (imperative: verb first)",
        },
        {
          type: "tip",
          text: "nicht negates what follows it. Ich trinke keinen Kaffee. uses keinen because the whole object is negated; nicht would be for negating the verb or the rest of the sentence.",
        },
      ],
    },
  ],
  vocab: [
    { id: "der-satz", de: "der Satz", en: "the sentence", part: "noun m.", plural: "die Sätze", audio: true },
    { id: "die-wortstellung", de: "die Wortstellung", en: "the word order", part: "noun f.", plural: "die Wortstellungen", audio: true },
    { id: "das-verb", de: "das Verb", en: "the verb", part: "noun n.", plural: "die Verben", audio: true },
    { id: "das-subjekt", de: "das Subjekt", en: "the subject", part: "noun n.", plural: "die Subjekte", audio: true },
    { id: "das-objekt", de: "das Objekt", en: "the object", part: "noun n.", plural: "die Objekte", audio: true },
    { id: "die-frage", de: "die Frage", en: "the question", part: "noun f.", plural: "die Fragen", audio: true },
    { id: "die-inversion", de: "die Inversion", en: "the inversion", part: "noun f.", plural: "die Inversionen", audio: true },
    { id: "der-satzrahmen", de: "der Satzrahmen", en: "the sentence frame", part: "noun m.", plural: "die Satzrahmen", audio: true },
    { id: "der-nebensatz", de: "der Nebensatz", en: "the subordinate clause", part: "noun m.", plural: "die Nebensätze", audio: true },
    { id: "die-konjunktion", de: "die Konjunktion", en: "the conjunction", part: "noun f.", plural: "die Konjunktionen", audio: true },
    { id: "das-adverb", de: "das Adverb", en: "the adverb", part: "noun n.", plural: "die Adverbien", audio: true },
    { id: "die-zeit", de: "die Zeit", en: "the time", part: "noun f.", plural: "die Zeiten", audio: true },
    { id: "der-ort", de: "der Ort", en: "the place", part: "noun m.", plural: "die Orte", audio: true },
    { id: "die-art-und-weise", de: "die Art und Weise", en: "the manner", part: "noun f.", audio: true },
    { id: "nicht", de: "nicht", en: "not", part: "adverb", audio: true },
  ],
  exercises: [
    {
      id: "ex-verb-second",
      type: "multiple-choice",
      title: "Übung 1: Die Position des Verbs",
      instruction: "Where does the finite verb stand in a German statement?",
      prompt: "In einem Aussagesatz steht das Verb immer an ___ Stelle.",
      options: ["zweiter", "erster", "letzter"],
      correctIndex: 0,
      explain: "The verb is the second element. Position 1 is the topic: a subject, a time word, anything.",
    },
    {
      id: "ex-v2-basic",
      type: "word-order",
      title: "Übung 2: Grundstellung",
      instruction: "Build the sentence: I am learning German.",
      chunks: ["Ich", "lerne", "Deutsch."],
      translation: "I am learning German.",
      explain: "Subject first, verb second, object third: the standard statement.",
    },
    {
      id: "ex-v2-inversion",
      type: "word-order",
      title: "Übung 3: Inversion",
      instruction: "Build the sentence: Today I am learning German.",
      chunks: ["Heute", "lerne", "ich", "Deutsch."],
      translation: "Today I am learning German.",
      explain: "A time word first: the verb stays second and the subject moves after it.",
    },
    {
      id: "ex-ja-nein-position",
      type: "multiple-choice",
      title: "Übung 4: Die Ja/Nein-Frage",
      instruction: "Where does the verb stand in a yes/no question?",
      prompt: "In einer Ja/Nein-Frage steht das Verb an ___ Stelle.",
      options: ["erster", "zweiter", "letzter"],
      correctIndex: 0,
      explain: "Yes/no questions swap subject and verb: the verb opens the sentence.",
    },
    {
      id: "ex-ja-nein",
      type: "word-order",
      title: "Übung 5: Die Ja/Nein-Frage",
      instruction: "Build the question: Are you learning German?",
      chunks: ["Lernst", "du", "Deutsch?"],
      translation: "Are you learning German?",
      explain: "Yes/no question: verb first, subject second.",
    },
    {
      id: "ex-w-frage",
      type: "word-order",
      title: "Übung 6: Die W-Frage",
      instruction: "Build the question: Where do you live?",
      chunks: ["Wo", "wohnst", "du?"],
      translation: "Where do you live?",
      explain: "W-question: question word, verb, subject.",
    },
    {
      id: "ex-dann-inversion",
      type: "word-order",
      title: "Übung 7: Inversion mit dann",
      instruction: "Build the sentence: Then I go home.",
      chunks: ["Dann", "gehe", "ich", "nach", "Hause."],
      translation: "Then I go home.",
      explain: "dann first: the verb stays second, the subject moves after it.",
    },
    {
      id: "ex-tmp",
      type: "word-order",
      title: "Übung 8: Zeit, Art und Weise, Ort",
      instruction: "Build the sentence: I am travelling to Berlin by train tomorrow.",
      chunks: ["Ich", "fahre", "morgen", "mit dem Zug", "nach", "Berlin."],
      translation: "I am travelling to Berlin by train tomorrow.",
      explain: "Time (morgen) before manner (mit dem Zug) before place (nach Berlin).",
    },
    {
      id: "ex-modal-frame",
      type: "word-order",
      title: "Übung 9: Der Satzrahmen mit Modalverb",
      instruction: "Build the sentence: I would like to drink a coffee.",
      chunks: ["Ich", "möchte", "einen Kaffee", "trinken."],
      translation: "I would like to drink a coffee.",
      explain: "The modal is second; the infinitive closes the frame.",
    },
    {
      id: "ex-perfekt-frame",
      type: "word-order",
      title: "Übung 10: Das Perfekt",
      instruction: "Build the sentence: I learned German yesterday.",
      chunks: ["Ich", "habe", "gestern", "Deutsch", "gelernt."],
      translation: "I learned German yesterday.",
      explain: "haben is second; the participle closes the frame.",
    },
    {
      id: "ex-separable-frame",
      type: "word-order",
      title: "Übung 11: Trennbare Verben",
      instruction: "Build the sentence: I get up at seven o'clock.",
      chunks: ["Ich", "stehe", "um sieben Uhr", "auf."],
      translation: "I get up at seven o'clock.",
      explain: "The separable prefix auf closes the frame.",
    },
    {
      id: "ex-weil-verb-last",
      type: "word-order",
      title: "Übung 12: weil + Verb am Ende",
      instruction: "Build the sentence: I stay at home because it is raining.",
      chunks: ["Ich", "bleibe", "zu Hause,", "weil", "es", "regnet."],
      translation: "I stay at home because it is raining.",
      explain: "weil pushes the verb to the end of the subordinate clause.",
    },
    {
      id: "ex-weil-main-first",
      type: "word-order",
      title: "Übung 13: Nebensatz zuerst",
      instruction: "Build the sentence: Because it is raining, I stay at home.",
      chunks: ["Weil", "es", "regnet,", "bleibe", "ich", "zu Hause."],
      translation: "Because it is raining, I stay at home.",
      explain: "Subordinate clause first; the main clause then starts with the verb.",
    },
    {
      id: "ex-nicht",
      type: "fill-blank",
      title: "Übung 14: nicht",
      instruction: "Complete the sentence: I do not understand.",
      sentence: "Ich verstehe ___.",
      translation: "I do not understand.",
      blanks: [{ answers: ["nicht"] }],
      explain: "nicht closes a whole-sentence negation.",
    },
    {
      id: "ex-imperative",
      type: "word-order",
      title: "Übung 15: Der Imperativ",
      instruction: "Build the sentence: Please open the door.",
      chunks: ["Öffnen", "Sie", "bitte", "die Tür."],
      translation: "Please open the door.",
      explain: "Imperative: the verb comes first, like a question.",
    },
    {
      id: "ex-connectives",
      type: "matching",
      title: "Übung 16: Konjunktionen",
      instruction: "Match each conjunction with its meaning.",
      pairs: [
        ["weil", "because"],
        ["dass", "that"],
        ["wenn", "when, if"],
        ["obwohl", "although"],
        ["dann", "then"],
        ["nicht", "not"],
      ],
      explain: "weil, dass, wenn and obwohl send the verb to the end; dann and nicht do not.",
    },
    {
      id: "ex-word-order-terms",
      type: "flashcard",
      title: "Übung 17: Die Fachbegriffe",
      instruction: "Say the German term before revealing the meaning.",
      items: [
        { front: "die Wortstellung", back: "the word order", frontAudio: true },
        { front: "der Satz", back: "the sentence", frontAudio: true },
        { front: "das Subjekt", back: "the subject", frontAudio: true },
        { front: "das Objekt", back: "the object", frontAudio: true },
        { front: "der Satzrahmen", back: "the sentence frame", frontAudio: true },
        { front: "der Nebensatz", back: "the subordinate clause", frontAudio: true },
        { front: "die Inversion", back: "the inversion", frontAudio: true },
        { front: "die Konjunktion", back: "the conjunction", frontAudio: true },
      ],
    },
  ],
};