import type { Lesson } from "../../schema";

export const wortstellungTief: Lesson = {
  id: "wortstellung-erklaert",
  title: "Wortstellung erklärt: German word order",
  summary:
    "The complete German word order system built around the four basic patterns: standard, inverted, transposed and subordinated word order. Learn what the conjugated verb is, why position 2 means the second sentence element, how the second verb travels to the end, and how subordinate and relative clauses flip the verb to last.",
  status: "ready",
  sections: [
    {
      heading: "Was ist die Wortstellung? Die vier Grundmuster",
      blocks: [
        {
          type: "paragraph",
          text: "Word order, die Wortstellung, is the set of rules that decides how words are arranged in a sentence so the meaning comes out correctly. German word order can look complicated because German does not always arrange words the same way English does, but German sentences follow a very systematic structure. The biggest difference is the position of the verb. The easiest way to understand German word order is to learn the four basic patterns: standard, inverted, transposed and subordinated word order.",
        },
        {
          type: "table",
          caption: "The four basic patterns",
          head: ["Pattern", "Example", "Verb position"],
          rows: [
            ["Standard", "Ich lerne Deutsch.", "position 2"],
            ["Inverted", "Lernst du Deutsch?", "position 1"],
            ["Transposed", "Heute lerne ich Deutsch.", "position 2"],
            ["Subordinated", "Ich weiß, dass du Deutsch lernst.", "end of the clause"],
          ],
          rowSpeak: ["Ich lerne Deutsch.", "Lernst du Deutsch?", "Heute lerne ich Deutsch.", "Ich weiß, dass du Deutsch lernst."],
        },
        {
          type: "example",
          de: "Ich lerne Deutsch. Lernst du Deutsch? Heute lerne ich Deutsch. Ich weiß, dass du Deutsch lernst.",
          en: "The same sentence in all four patterns: the verb is the element that moves.",
        },
        {
          type: "tip",
          text: "Throughout this whole topic, watch the conjugated verb. Its position is what changes from pattern to pattern, and it is the key to every sentence.",
        },
      ],
    },
    {
      heading: "Das konjugierte Verb und die Position 2",
      blocks: [
        {
          type: "paragraph",
          text: "Before learning word order, you need to know what a conjugated verb is. A conjugated verb is the verb that changes according to the subject: Ich lerne Deutsch. / Du lernst Deutsch. / Er lernt Deutsch. The verb changes with the person. The conjugated verb is the main verb that controls the sentence's word order, and its position changes depending on the type of sentence.",
        },
        {
          type: "gloss",
          de: "Heute Morgen lerne ich Deutsch.",
          en: "This morning I am learning German.",
          words: [
            { word: "Heute Morgen", pos: "Adverb", en: "this morning", detail: "Two words, one sentence element, position 1" },
            { word: "lerne", pos: "Verb", en: "learn", detail: "Conjugated verb, position 2" },
            { word: "ich", pos: "Pronomen", en: "I", detail: "Subject, after the verb" },
            { word: "Deutsch.", pos: "Nomen", en: "German", detail: "Object" },
          ],
        },
        {
          type: "paragraph",
          text: "When we say the verb is in position 2, we do not mean it is the second individual word. We mean it is the second sentence element. An element is one logical unit: a subject, a verb, an object, a time phrase, or a whole group like nach der Schule. Heute Morgen consists of two words, but together they form one element, so lerne is still in position 2.",
        },
        {
          type: "table",
          caption: "Position 2 = the second element, not the second word",
          head: ["Element 1", "Element 2 (verb)", "Rest"],
          rows: [
            ["Ich", "lerne", "Deutsch."],
            ["Heute Morgen", "lerne", "ich Deutsch."],
            ["Nach der Schule", "gehe", "ich nach Hause."],
            ["Maria", "kauft", "ein Buch."],
          ],
          rowSpeak: ["Ich lerne Deutsch.", "Heute Morgen lerne ich Deutsch.", "Nach der Schule gehe ich nach Hause.", "Maria kauft ein Buch."],
        },
        {
          type: "tip",
          text: "Position 2 is a slot, not a word count. Nach der Schule is three words but one element, so gehe still sits in slot 2. Count the elements, not the words.",
        },
      ],
    },
    {
      heading: "A. Die Standardwortstellung",
      blocks: [
        {
          type: "paragraph",
          text: "Standard word order is the normal order of an ordinary German statement. With one verb the structure is SUBJECT + CONJUGATED VERB + OTHER INFORMATION: Ich lerne Deutsch. With two verbs the structure is SUBJECT + CONJUGATED VERB + INFORMATION + OTHER VERB, and the second verb travels to the very end of the sentence. This separating of the two verbs is one of the most important characteristics of German word order.",
        },
        {
          type: "gloss",
          de: "Ich möchte meinem Nachbarn einen Kuchen backen.",
          en: "I want to bake my neighbour a cake.",
          words: [
            { word: "Ich", pos: "Pronomen", en: "I", detail: "Subject, position 1" },
            { word: "möchte", pos: "Verb", en: "want to", detail: "Conjugated verb, position 2" },
            { word: "meinem Nachbarn", pos: "Nomen", en: "my neighbour", detail: "Dative object" },
            { word: "einen Kuchen", pos: "Nomen", en: "a cake", detail: "Accusative object" },
            { word: "backen.", pos: "Verb", en: "to bake", detail: "Second verb, at the end" },
          ],
        },
        {
          type: "table",
          caption: "English vs German: two verbs split",
          head: ["English", "German"],
          rows: [
            ["I want to bake my neighbour a cake.", "Ich möchte meinem Nachbarn einen Kuchen backen."],
            ["I want to learn German.", "Ich möchte Deutsch lernen."],
            ["I can speak German.", "Ich kann Deutsch sprechen."],
            ["I have to work today.", "Ich muss heute arbeiten."],
            ["I want to travel to Germany.", "Ich will nach Deutschland reisen."],
          ],
          rowSpeak: ["Ich möchte meinem Nachbarn einen Kuchen backen.", "Ich möchte Deutsch lernen.", "Ich kann Deutsch sprechen.", "Ich muss heute arbeiten.", "Ich will nach Deutschland reisen."],
        },
        {
          type: "table",
          caption: "The two formulas",
          head: ["Structure", "Formula", "Example"],
          rows: [
            ["one verb", "SUBJECT + CONJUGATED VERB + INFORMATION", "Ich lerne Deutsch."],
            ["two verbs", "SUBJECT + CONJUGATED VERB + INFORMATION + SECOND VERB", "Ich möchte Deutsch lernen."],
          ],
          rowSpeak: ["Ich lerne Deutsch.", "Ich möchte Deutsch lernen."],
        },
        {
          type: "tip",
          text: "English keeps both verbs together: I want to learn. German splits them: Ich möchte ... lernen. The conjugated verb opens the frame in position 2 and the second verb closes it at the end.",
        },
      ],
    },
    {
      heading: "B. Die Inversion: Ja/Nein-Fragen",
      blocks: [
        {
          type: "paragraph",
          text: "In inverted word order the subject and the conjugated verb change places. Instead of SUBJECT + VERB you get VERB + SUBJECT. The most common use is the yes/no question. With one verb the pattern is CONJUGATED VERB + SUBJECT + INFORMATION: Lernst du Deutsch? With two verbs it is CONJUGATED VERB + SUBJECT + INFORMATION + OTHER VERB: Möchtest du Deutsch lernen? The only major change from the statement is that the verb steps in front of the subject.",
        },
        {
          type: "gloss",
          de: "Lernst du Deutsch?",
          en: "Are you learning German?",
          words: [
            { word: "Lernst", pos: "Verb", en: "learn", detail: "Conjugated verb first, position 1" },
            { word: "du", pos: "Pronomen", en: "you", detail: "Subject, after the verb" },
            { word: "Deutsch?", pos: "Nomen", en: "German", detail: "Object" },
          ],
        },
        {
          type: "table",
          caption: "Statement becomes a question",
          head: ["Statement", "Question"],
          rows: [
            ["Ich lerne Deutsch.", "Lerne ich Deutsch?"],
            ["Du lernst Deutsch.", "Lernst du Deutsch?"],
            ["Du kannst Deutsch sprechen.", "Kannst du Deutsch sprechen?"],
            ["Ich möchte Deutsch lernen.", "Möchte ich Deutsch lernen?"],
          ],
          rowSpeak: ["Ich lerne Deutsch.", "Lernst du Deutsch?", "Du kannst Deutsch sprechen.", "Kannst du Deutsch sprechen?"],
        },
        {
          type: "table",
          caption: "The inverted formulas",
          head: ["Structure", "Formula", "Example"],
          rows: [
            ["one verb", "CONJUGATED VERB + SUBJECT + INFORMATION", "Lernst du Deutsch?"],
            ["two verbs", "CONJUGATED VERB + SUBJECT + INFORMATION + OTHER VERB", "Möchtest du Deutsch lernen?"],
          ],
          rowSpeak: ["Lernst du Deutsch?", "Möchtest du Deutsch lernen?"],
        },
        {
          type: "tip",
          text: "Inversion is only a swap: subject and verb change places, everything else stays where it is. Lernst du Deutsch? is Ich lerne Deutsch? with the first two elements reversed.",
        },
      ],
    },
    {
      heading: "C. Die Transposition: etwas anderes zuerst",
      blocks: [
        {
          type: "paragraph",
          text: "Transposed word order moves something other than the subject to the beginning of the sentence. You can move an object, an adverb, a time expression, a place expression, a prepositional phrase, or any other element. The most important rule is that the conjugated verb must still be in position 2. This is exactly what separates transposed word order from inverted word order.",
        },
        {
          type: "gloss",
          de: "Heute lerne ich Deutsch.",
          en: "Today I am learning German.",
          words: [
            { word: "Heute", pos: "Adverb", en: "today", detail: "Time adverb, position 1" },
            { word: "lerne", pos: "Verb", en: "learn", detail: "Conjugated verb, still position 2" },
            { word: "ich", pos: "Pronomen", en: "I", detail: "Subject, after the verb" },
            { word: "Deutsch.", pos: "Nomen", en: "German", detail: "Object" },
          ],
        },
        {
          type: "paragraph",
          text: "Take a full sentence and transpose different elements. The original is: Ich möchte meinem netten Nachbarn schnell einen großen Kuchen backen. Move the dative object, the accusative object, or the adverb to the front, and in every version the conjugated verb möchte stays in position 2.",
        },
        {
          type: "table",
          caption: "Transposed variants of one sentence",
          head: ["Element in position 1", "Sentence"],
          rows: [
            ["dative object", "Meinem netten Nachbarn möchte ich schnell einen großen Kuchen backen."],
            ["accusative object", "Einen großen Kuchen möchte ich meinem netten Nachbarn schnell backen."],
            ["adverb", "Schnell möchte ich meinem netten Nachbarn einen großen Kuchen backen."],
          ],
          rowSpeak: ["Meinem netten Nachbarn möchte ich schnell einen großen Kuchen backen.", "Einen großen Kuchen möchte ich meinem netten Nachbarn schnell backen.", "Schnell möchte ich meinem netten Nachbarn einen großen Kuchen backen."],
        },
        {
          type: "table",
          caption: "Transposed with time and place",
          head: ["Normal", "Transposed"],
          rows: [
            ["Ich lerne zu Hause Deutsch.", "Zu Hause lerne ich Deutsch."],
            ["Ich gehe morgen zur Schule.", "Morgen gehe ich zur Schule."],
          ],
          rowSpeak: ["Ich lerne zu Hause Deutsch.", "Ich gehe morgen zur Schule."],
        },
        {
          type: "table",
          caption: "Inverted vs transposed",
          head: ["Pattern", "What comes first", "Example"],
          rows: [
            ["Inverted", "the verb", "Lerne ich Deutsch?"],
            ["Transposed", "something other than the subject", "Heute lerne ich Deutsch."],
          ],
          rowSpeak: ["Lerne ich Deutsch?", "Heute lerne ich Deutsch."],
        },
        {
          type: "tip",
          text: "Moving an element to the front gives it emphasis or makes it the topic. Ich lerne heute Deutsch. is neutral; Heute lerne ich Deutsch. focuses on heute. Either way the verb never leaves position 2.",
        },
      ],
    },
    {
      heading: "D. Die Subordination: Nebensätze",
      blocks: [
        {
          type: "paragraph",
          text: "The fourth pattern is subordinated word order. A subordinate clause is a clause that depends on another clause, and it is often introduced by a subordinating conjunction or a relative pronoun. The conjugated verb of a subordinate clause moves to the very end. Common subordinating conjunctions are weil, dass, wenn, obwohl, bevor, nachdem, während, damit and ob.",
        },
        {
          type: "gloss",
          de: "Ich weiß, dass du Deutsch lernst.",
          en: "I know that you are learning German.",
          words: [
            { word: "Ich", pos: "Pronomen", en: "I", detail: "Subject of the main clause" },
            { word: "weiß,", pos: "Verb", en: "know", detail: "Main clause verb, position 2" },
            { word: "dass", pos: "Konjunktion", en: "that", detail: "Subordinating conjunction" },
            { word: "du", pos: "Pronomen", en: "you", detail: "Subject of the subordinate clause" },
            { word: "Deutsch", pos: "Nomen", en: "German", detail: "Object" },
            { word: "lernst.", pos: "Verb", en: "learn", detail: "Verb at the end of the clause" },
          ],
        },
        {
          type: "table",
          caption: "Subordinating conjunctions",
          head: ["Conjunction", "English", "Example"],
          rows: [
            ["weil", "because", "Ich bleibe zu Hause, weil ich müde bin."],
            ["dass", "that", "Ich weiß, dass du Deutsch lernst."],
            ["wenn", "when, if", "Ich komme, wenn ich Zeit habe."],
            ["obwohl", "although", "Obwohl es kalt ist, gehe ich spazieren."],
            ["bevor", "before", "Bevor ich schlafe, lese ich ein Buch."],
            ["nachdem", "after", "Nachdem ich aufstehe, frühstücke ich."],
            ["während", "while", "Während ich arbeite, höre ich Musik."],
            ["damit", "so that", "Ich lerne, damit ich Deutsch spreche."],
            ["ob", "whether", "Ich weiß nicht, ob er kommt."],
          ],
          rowSpeak: ["weil", "dass", "wenn", "obwohl", "bevor", "nachdem", "während", "damit", "ob"],
        },
        {
          type: "paragraph",
          text: "A subordinate clause can come after the main clause, or it can come first. When it comes first, the whole subordinate clause occupies position 1. German main clauses require the conjugated verb in position 2, so the main clause then begins with its verb. This is the same transposed rule applied to a whole clause.",
        },
        {
          type: "gloss",
          de: "Weil ich müde bin, bleibe ich zu Hause.",
          en: "Because I am tired, I stay at home.",
          words: [
            { word: "Weil ich müde bin,", pos: "Konjunktion", en: "because I am tired", detail: "Whole subordinate clause, position 1" },
            { word: "bleibe", pos: "Verb", en: "stay", detail: "Main clause verb, position 2" },
            { word: "ich", pos: "Pronomen", en: "I", detail: "Subject, position 3" },
            { word: "zu Hause.", pos: "Adverb", en: "at home", detail: "Place" },
          ],
        },
        {
          type: "example",
          de: "Weil ich müde bin, bleibe ich zu Hause.",
          en: "Because I am tired, I stay at home.",
        },
        {
          type: "example",
          de: "Ich bleibe zu Hause, weil ich müde bin.",
          en: "I stay at home because I am tired.",
        },
        {
          type: "tip",
          text: "Never write: Weil ich müde bin, ich bleibe zu Hause. The subordinate clause Weil ich müde bin is one element in position 1, so the main clause must start with its verb: bleibe.",
        },
      ],
    },
    {
      heading: "Relativsätze: das Verb bleibt am Ende",
      blocks: [
        {
          type: "paragraph",
          text: "Subordinated word order is also used in relative clauses. A relative clause gives additional information about a noun and starts with a relative pronoun: der, die, das, den, dem, deren or dessen. The conjugated verb stands at the end of the relative clause.",
        },
        {
          type: "gloss",
          de: "Das ist die Frau, die ich in der Stadt gesehen habe.",
          en: "That is the woman whom I saw in the city.",
          words: [
            { word: "Das ist die Frau,", pos: "Pronomen", en: "that is the woman", detail: "Main clause" },
            { word: "die", pos: "Pronomen", en: "who", detail: "Relative pronoun, feminine" },
            { word: "ich", pos: "Pronomen", en: "I", detail: "Subject of the relative clause" },
            { word: "in der Stadt", pos: "Nomen", en: "in the city", detail: "Place" },
            { word: "gesehen", pos: "Verb", en: "seen", detail: "Participle" },
            { word: "habe.", pos: "Verb", en: "have", detail: "Conjugated verb, at the end" },
          ],
        },
        {
          type: "table",
          caption: "Relative pronouns",
          head: ["Pronoun", "Use", "Example"],
          rows: [
            ["der", "masculine", "Das ist der Mann, der Deutsch lernt."],
            ["die", "feminine", "Das ist die Frau, die in Berlin wohnt."],
            ["das", "neuter", "Das ist das Buch, das ich lese."],
            ["den", "masculine (acc.)", "Das ist der Mann, den ich kenne."],
            ["dem", "masculine (dat.)", "Das ist der Mann, dem ich helfe."],
            ["deren", "possessive plural", "Das ist die Frau, deren Sohn arbeitet."],
          ],
          rowSpeak: ["Das ist der Mann, der Deutsch lernt.", "Das ist die Frau, die in Berlin wohnt.", "Das ist das Buch, das ich lese.", "Das ist der Mann, den ich kenne.", "Das ist der Mann, dem ich helfe.", "Das ist die Frau, deren Sohn arbeitet."],
        },
        {
          type: "tip",
          text: "The relative pronoun looks like the article. The relative clause is a subordinate clause, so its verb goes to the very end: die ... gesehen habe.",
        },
      ],
    },
    {
      heading: "Te-ka-mo-lo: Zeit, Art und Weise, Ort",
      blocks: [
        {
          type: "paragraph",
          text: "Inside the middle of the sentence, adverbials run in a fixed order: time (temporal), then manner (modal), then place (lokal) — te-ka-mo-lo. Ich fahre morgen mit dem Zug nach Berlin. English often says place before time; German always puts time first.",
        },
        {
          type: "table",
          caption: "Building a sentence with all three adverbials",
          head: ["Subject", "Verb", "Time", "Manner", "Place"],
          rows: [
            ["Ich", "fahre", "morgen", "mit dem Zug", "nach Berlin."],
            ["Wir", "treffen uns", "heute Abend", "im Café", "in der Stadt."],
            ["Er", "geht", "jeden Tag", "zu Fuß", "zur Arbeit."],
          ],
          rowSpeak: ["Ich fahre morgen mit dem Zug nach Berlin.", "Wir treffen uns heute Abend im Café in der Stadt.", "Er geht jeden Tag zu Fuß zur Arbeit."],
        },
        {
          type: "tip",
          text: "The word order test: when (morgen), how (mit dem Zug), where (nach Berlin). The order is always time, manner, place.",
        },
      ],
    },
    {
      heading: "Der Satzrahmen: die Satzklammer",
      blocks: [
        {
          type: "paragraph",
          text: "Many German verbs are built from a conjugated part and a closing part, and the two hold the sentence together like a bracket. A modal verb closes with the infinitive: Ich möchte einen Kaffee trinken. The perfect tense closes with the participle: Ich habe Deutsch gelernt. A separable verb closes with its prefix: Ich stehe um sieben Uhr auf.",
        },
        {
          type: "table",
          caption: "The sentence frame in action",
          head: ["Opening (position 2)", "Middle", "Closing (end)"],
          rows: [
            ["Ich möchte", "einen Kaffee", "trinken."],
            ["Ich habe", "gestern Deutsch", "gelernt."],
            ["Ich stehe", "um sieben Uhr", "auf."],
            ["Der Zug fährt", "um 14:30 Uhr", "ab."],
          ],
          rowSpeak: ["Ich möchte einen Kaffee trinken.", "Ich habe gestern Deutsch gelernt.", "Ich stehe um sieben Uhr auf.", "Der Zug fährt um 14:30 Uhr ab."],
        },
        {
          type: "tip",
          text: "Nothing may come after the closing part. Ich habe gestern Deutsch gelernt. is complete. When you read a German sentence, wait for the end: the verb group often finishes the sentence.",
        },
      ],
    },
    {
      heading: "Die Negation mit nicht",
      blocks: [
        {
          type: "paragraph",
          text: "nicht stands directly before the element it negates, and it closes a whole-sentence negation: Ich verstehe nicht. Inside a frame, nicht goes before the closing part: Ich habe das Buch nicht gelesen. Move nicht and the meaning changes: nicht das Buch means not the book, das Buch nicht means I did not read it.",
        },
        {
          type: "table",
          caption: "Where nicht sits",
          head: ["Sentence", "What nicht negates"],
          rows: [
            ["Ich komme nicht.", "the whole action"],
            ["Ich arbeite nicht im Büro.", "the place"],
            ["Ich habe das Buch nicht gelesen.", "the whole action, before the frame closer"],
            ["Ich habe nicht das Buch gelesen.", "the book (I read something else)"],
          ],
          rowSpeak: ["Ich komme nicht.", "Ich arbeite nicht im Büro.", "Ich habe das Buch nicht gelesen.", "Ich habe nicht das Buch gelesen."],
        },
        {
          type: "tip",
          text: "nicht negates what follows it. Place it before the element you want to negate, or at the end of a whole-sentence negation.",
        },
      ],
    },
    {
      heading: "Die häufigsten Fehler",
      blocks: [
        {
          type: "paragraph",
          text: "Every common mistake is a verb in the wrong position. Test each sentence with the four patterns: where is the conjugated verb, and does the pattern allow it there?",
        },
        {
          type: "table",
          caption: "The classic mistakes",
          head: ["Mistake", "Wrong", "Right", "Why"],
          rows: [
            ["verb not in position 2", "Ich heute lerne Deutsch.", "Heute lerne ich Deutsch.", "the verb stays in slot 2"],
            ["subject not moved after transposition", "Heute ich lerne Deutsch.", "Heute lerne ich Deutsch.", "the subject follows the verb"],
            ["two verbs kept together", "Ich möchte lernen Deutsch.", "Ich möchte Deutsch lernen.", "the second verb goes to the end"],
            ["inverted instead of transposed", "Lerne ich heute Deutsch?", "Heute lerne ich Deutsch.", "a statement keeps the verb in position 2"],
            ["subordinate verb in the middle", "weil ich lerne Deutsch", "weil ich Deutsch lerne", "the verb goes to the end"],
            ["main clause after weil starts wrong", "Weil ich müde bin, ich bleibe zu Hause.", "Weil ich müde bin, bleibe ich zu Hause.", "the whole weil-clause fills position 1"],
            ["relative clause verb misplaced", "die ich habe gesehen", "die ich gesehen habe", "the verb ends the relative clause"],
          ],
          rowSpeak: ["Heute lerne ich Deutsch.", "Heute lerne ich Deutsch.", "Ich möchte Deutsch lernen.", "Heute lerne ich Deutsch.", "weil ich Deutsch lerne", "Weil ich müde bin, bleibe ich zu Hause.", "die ich gesehen habe"],
        },
        {
          type: "tip",
          text: "One sentence, one question: which of the four patterns is this? Then check that the conjugated verb is where the pattern demands it.",
        },
      ],
    },
  ],
  vocab: [
    { id: "die-wortstellung", de: "die Wortstellung", en: "the word order", part: "noun f.", plural: "die Wortstellungen", audio: true },
    { id: "der-satz", de: "der Satz", en: "the sentence", part: "noun m.", plural: "die Sätze", audio: true },
    { id: "das-satzelement", de: "das Satzelement", en: "the sentence element", part: "noun n.", plural: "die Satzelemente", audio: true },
    { id: "die-position", de: "die Position", en: "the position", part: "noun f.", plural: "die Positionen", audio: true },
    { id: "das-konjugierte-verb", de: "das konjugierte Verb", en: "the conjugated verb", part: "noun n.", plural: "die konjugierten Verben", audio: true },
    { id: "das-subjekt", de: "das Subjekt", en: "the subject", part: "noun n.", plural: "die Subjekte", audio: true },
    { id: "das-objekt", de: "das Objekt", en: "the object", part: "noun n.", plural: "die Objekte", audio: true },
    { id: "die-standardwortstellung", de: "die Standardwortstellung", en: "the standard word order", part: "noun f.", audio: true },
    { id: "die-inversion", de: "die Inversion", en: "the inversion", part: "noun f.", plural: "die Inversionen", audio: true },
    { id: "die-transposition", de: "die Transposition", en: "the transposed word order", part: "noun f.", plural: "die Transpositionen", audio: true },
    { id: "der-nebensatz", de: "der Nebensatz", en: "the subordinate clause", part: "noun m.", plural: "die Nebensätze", audio: true },
    { id: "der-relativsatz", de: "der Relativsatz", en: "the relative clause", part: "noun m.", plural: "die Relativsätze", audio: true },
    { id: "die-konjunktion", de: "die Konjunktion", en: "the conjunction", part: "noun f.", plural: "die Konjunktionen", audio: true },
    { id: "das-relativpronomen", de: "das Relativpronomen", en: "the relative pronoun", part: "noun n.", plural: "die Relativpronomen", audio: true },
    { id: "das-vorfeld", de: "das Vorfeld", en: "the first position", part: "noun n.", plural: "die Vorfelder", audio: true },
    { id: "das-modalverb", de: "das Modalverb", en: "the modal verb", part: "noun n.", plural: "die Modalverben", audio: true },
    { id: "das-partizip-2", de: "das Partizip II", en: "the past participle", part: "noun n.", plural: "die Partizipien", audio: true },
    { id: "der-satzrahmen", de: "der Satzrahmen", en: "the sentence frame", part: "noun m.", plural: "die Satzrahmen", audio: true },
    { id: "die-verneinung", de: "die Verneinung", en: "the negation", part: "noun f.", plural: "die Verneinungen", audio: true },
    { id: "ich-lerne-deutsch", de: "Ich lerne Deutsch.", en: "I am learning German.", part: "phrase", phrase: true, audio: true },
    { id: "heute-lerne-ich-deutsch", de: "Heute lerne ich Deutsch.", en: "Today I am learning German.", part: "phrase", phrase: true, audio: true },
    { id: "ich-moechte-deutsch-lernen", de: "Ich möchte Deutsch lernen.", en: "I want to learn German.", part: "phrase", phrase: true, audio: true },
    { id: "ich-weiss-dass-du-deutsch-lernst", de: "Ich weiß, dass du Deutsch lernst.", en: "I know that you are learning German.", part: "phrase", phrase: true, audio: true },
  ],
  exercises: [
    {
      id: "ex-vier-muster",
      type: "multiple-choice",
      title: "Übung 1: Die vier Grundmuster",
      instruction: "Which pattern is this sentence?",
      prompt: "Lernst du Deutsch? ist ein Beispiel für die ___.",
      options: ["Inversion", "Standardwortstellung", "Transposition"],
      correctIndex: 0,
      explain: "A yes/no question puts the verb first: that is inverted word order.",
    },
    {
      id: "ex-position",
      type: "multiple-choice",
      title: "Übung 2: Die Position 2",
      instruction: "What does position 2 mean?",
      prompt: "Position 2 bedeutet: das Verb ist das ___ Satzelement.",
      options: ["zweite", "zweite Wort", "erste"],
      correctIndex: 0,
      explain: "Position 2 is the second element, not the second word: Heute Morgen lerne ich Deutsch.",
    },
    {
      id: "ex-standard",
      type: "multiple-choice",
      title: "Übung 3: Die Standardwortstellung",
      instruction: "Choose the standard sentence.",
      prompt: "I am learning German.",
      options: ["Ich lerne Deutsch.", "Lerne ich Deutsch?", "Heute lerne ich Deutsch."],
      correctIndex: 0,
      explain: "Standard order: subject, verb, other information.",
    },
    {
      id: "ex-zwei-verben",
      type: "multiple-choice",
      title: "Übung 4: Zwei Verben",
      instruction: "Choose the correct sentence.",
      prompt: "I want to learn German.",
      options: ["Ich möchte Deutsch lernen.", "Ich lerne Deutsch möchte.", "Möchte ich Deutsch lernen?"],
      correctIndex: 0,
      explain: "The conjugated verb is second; the infinitive goes to the end.",
    },
    {
      id: "ex-invertiert",
      type: "multiple-choice",
      title: "Übung 5: Die Inversion",
      instruction: "Turn the statement into a yes/no question.",
      prompt: "Ich lerne Deutsch.",
      options: ["Lerne ich Deutsch?", "Ich lerne Deutsch?", "Deutsch lerne ich?"],
      correctIndex: 0,
      explain: "Inverted word order: verb first, then the subject.",
    },
    {
      id: "ex-invertiert-zwei",
      type: "multiple-choice",
      title: "Übung 6: Inversion mit zwei Verben",
      instruction: "Turn the statement into a yes/no question.",
      prompt: "Du kannst Deutsch sprechen.",
      options: ["Kannst du Deutsch sprechen?", "Du kannst Deutsch sprechen?", "Deutsch kannst du sprechen?"],
      correctIndex: 0,
      explain: "Inverted with two verbs: verb, subject, information, second verb.",
    },
    {
      id: "ex-transponiert",
      type: "multiple-choice",
      title: "Übung 7: Die Transposition",
      instruction: "Which pattern is this sentence?",
      prompt: "Heute lerne ich Deutsch. ist ein Beispiel für die ___.",
      options: ["Transposition", "Inversion", "Subordination"],
      correctIndex: 0,
      explain: "A time word opens the sentence and the verb stays in position 2: transposed word order.",
    },
    {
      id: "ex-transponiert-objekt",
      type: "multiple-choice",
      title: "Übung 8: Transposition mit Objekt",
      instruction: "What is in position 1?",
      prompt: "Meinem netten Nachbarn möchte ich schnell einen großen Kuchen backen.",
      options: ["das Dativobjekt", "das Subjekt", "das Verb"],
      correctIndex: 0,
      explain: "The dative object opens the sentence; möchte still stands in position 2.",
    },
    {
      id: "ex-unterschied",
      type: "multiple-choice",
      title: "Übung 9: Inversion oder Transposition?",
      instruction: "What separates inverted from transposed word order?",
      prompt: "Bei der Inversion kommt das ___ zuerst, bei der Transposition etwas anderes.",
      options: ["Verb", "Subjekt", "Objekt"],
      correctIndex: 0,
      explain: "Inverted: the verb comes first. Transposed: something other than the subject comes first, and the verb stays in position 2.",
    },
    {
      id: "ex-nebensatz-verb",
      type: "multiple-choice",
      title: "Übung 10: Der Nebensatz",
      instruction: "Choose the correct subordinate clause.",
      prompt: "Ich weiß, dass du Deutsch ___.",
      options: ["lernst", "lernen", "lernst du"],
      correctIndex: 0,
      explain: "dass sends the verb to the end of the clause.",
    },
    {
      id: "ex-weil-inversion",
      type: "multiple-choice",
      title: "Übung 11: weil zuerst",
      instruction: "Choose the correct sentence.",
      prompt: "Weil ich müde bin, ___ ich zu Hause.",
      options: ["bleibe", "ich bleibe", "bleiben"],
      correctIndex: 0,
      explain: "The weil-clause fills position 1, so the main clause starts with its verb.",
    },
    {
      id: "ex-relativ-verb",
      type: "multiple-choice",
      title: "Übung 12: Der Relativsatz",
      instruction: "Choose the correct relative clause.",
      prompt: "Das ist die Frau, die ___.",
      options: ["in der Stadt wohnt", "wohnt in der Stadt", "wohnt sie in der Stadt"],
      correctIndex: 0,
      explain: "The relative clause ends with its verb: die ... wohnt.",
    },
    {
      id: "ex-wo-standard",
      type: "word-order",
      title: "Übung 13: Die Standardwortstellung",
      instruction: "Build the sentence: I am learning German.",
      chunks: ["Ich", "lerne", "Deutsch."],
      translation: "I am learning German.",
      explain: "Subject, conjugated verb, information: standard order.",
    },
    {
      id: "ex-wo-zwei-verben",
      type: "word-order",
      title: "Übung 14: Zwei Verben",
      instruction: "Build the sentence: I want to bake my neighbour a cake.",
      chunks: ["Ich", "möchte", "meinem Nachbarn", "einen Kuchen", "backen."],
      translation: "I want to bake my neighbour a cake.",
      explain: "möchte in position 2, the second verb backen at the end.",
    },
    {
      id: "ex-wo-invertiert",
      type: "word-order",
      title: "Übung 15: Die Inversion",
      instruction: "Build the question: Are you learning German?",
      chunks: ["Lernst", "du", "Deutsch?"],
      translation: "Are you learning German?",
      explain: "Inverted order: verb, subject, information.",
    },
    {
      id: "ex-wo-invertiert-zwei",
      type: "word-order",
      title: "Übung 16: Inversion mit zwei Verben",
      instruction: "Build the question: Would you like to learn German?",
      chunks: ["Möchtest", "du", "Deutsch", "lernen?"],
      translation: "Would you like to learn German?",
      explain: "Verb, subject, information, second verb.",
    },
    {
      id: "ex-wo-transponiert",
      type: "word-order",
      title: "Übung 17: Die Transposition",
      instruction: "Build the sentence: Today I am learning German.",
      chunks: ["Heute", "lerne", "ich", "Deutsch."],
      translation: "Today I am learning German.",
      explain: "Time word first, verb still second, subject third.",
    },
    {
      id: "ex-wo-transponiert-ort",
      type: "word-order",
      title: "Übung 18: Transposition mit Ort",
      instruction: "Build the sentence: At home I am learning German.",
      chunks: ["Zu Hause", "lerne", "ich", "Deutsch."],
      translation: "At home I am learning German.",
      explain: "Place first, verb second, subject third.",
    },
    {
      id: "ex-wo-transponiert-zeit",
      type: "word-order",
      title: "Übung 19: Transposition mit Zeit",
      instruction: "Build the sentence: Tomorrow I am going to school.",
      chunks: ["Morgen", "gehe", "ich", "zur Schule."],
      translation: "Tomorrow I am going to school.",
      explain: "Time first, verb second, subject third.",
    },
    {
      id: "ex-wo-transponiert-objekt",
      type: "word-order",
      title: "Übung 20: Transposition mit Objekt",
      instruction: "Build the sentence: A cake I want to bake.",
      chunks: ["Einen Kuchen", "möchte", "ich", "backen."],
      translation: "A cake I want to bake.",
      explain: "Object first, verb still second, subject third.",
    },
    {
      id: "ex-wo-weil",
      type: "word-order",
      title: "Übung 21: weil zuerst",
      instruction: "Build the sentence: Because it is raining, I stay at home.",
      chunks: ["Weil", "es", "regnet,", "bleibe", "ich", "zu Hause."],
      translation: "Because it is raining, I stay at home.",
      explain: "The weil-clause fills position 1, so the main clause starts with its verb.",
    },
    {
      id: "ex-wo-relativ",
      type: "word-order",
      title: "Übung 22: Der Relativsatz",
      instruction: "Build the sentence: This is the woman who lives in Berlin.",
      chunks: ["Das", "ist", "die Frau,", "die", "in Berlin", "wohnt."],
      translation: "This is the woman who lives in Berlin.",
      explain: "The relative clause ends with its verb: die ... wohnt.",
    },
    {
      id: "ex-fill-nebensatz",
      type: "fill-blank",
      title: "Übung 23: Der Nebensatz",
      instruction: "Complete the subordinate clause of lernen.",
      sentence: "Ich weiß, dass du Deutsch ___.",
      translation: "I know that you are learning German.",
      blanks: [{ answers: ["lernst"] }],
      explain: "dass sends the verb to the end: lernst.",
    },
    {
      id: "ex-fill-transponiert",
      type: "fill-blank",
      title: "Übung 24: Die Transposition",
      instruction: "Complete the sentence with the time word.",
      sentence: "___ lerne ich Deutsch.",
      translation: "Today I am learning German.",
      blanks: [{ answers: ["Heute", "heute"] }],
      explain: "The time word opens the sentence and the verb stays second.",
    },
    {
      id: "ex-match-muster",
      type: "matching",
      title: "Übung 25: Die vier Muster",
      instruction: "Match each pattern to its example.",
      pairs: [
        ["Standard", "Ich lerne Deutsch."],
        ["Inverted", "Lernst du Deutsch?"],
        ["Transposed", "Heute lerne ich Deutsch."],
        ["Subordinated", "Ich weiß, dass du Deutsch lernst."],
      ],
      explain: "Watch the conjugated verb: it is the element that moves.",
    },
    {
      id: "ex-match-konjunktionen",
      type: "matching",
      title: "Übung 26: Die Konjunktionen",
      instruction: "Match each conjunction with its meaning.",
      pairs: [
        ["weil", "because"],
        ["dass", "that"],
        ["wenn", "when, if"],
        ["obwohl", "although"],
        ["bevor", "before"],
        ["nachdem", "after"],
      ],
      explain: "All six are subordinating: they send the verb to the end.",
    },
    {
      id: "ex-hoeren-1",
      type: "listening",
      title: "Übung 27: Hörverstehen",
      instruction: "Listen and choose the sentence you hear.",
      prompt: "Ich möchte Deutsch lernen.",
      options: ["Ich möchte Deutsch lernen.", "Ich lerne Deutsch möchte.", "Möchte ich Deutsch lernen?"],
      correctIndex: 0,
      explain: "Two verbs: möchte second, lernen at the end.",
    },
    {
      id: "ex-hoeren-2",
      type: "listening",
      title: "Übung 28: Hörverstehen",
      instruction: "Listen and choose the sentence you hear.",
      prompt: "Heute lerne ich Deutsch.",
      options: ["Heute lerne ich Deutsch.", "Heute ich lerne Deutsch.", "Ich lerne heute Deutsch."],
      correctIndex: 0,
      explain: "Transposed order: time word first, verb second.",
    },
    {
      id: "ex-karten",
      type: "flashcard",
      title: "Übung 29: Wortstellungskarten",
      instruction: "Say the German term before revealing the meaning.",
      items: [
        { front: "die Standardwortstellung", back: "the standard word order", frontAudio: true },
        { front: "die Inversion", back: "the inversion", frontAudio: true },
        { front: "die Transposition", back: "the transposed word order", frontAudio: true },
        { front: "der Nebensatz", back: "the subordinate clause", frontAudio: true },
        { front: "der Relativsatz", back: "the relative clause", frontAudio: true },
        { front: "das Satzelement", back: "the sentence element", frontAudio: true },
        { front: "das konjugierte Verb", back: "the conjugated verb", frontAudio: true },
        { front: "das Vorfeld", back: "the first position", frontAudio: true },
        { front: "Ich möchte Deutsch lernen.", back: "I want to learn German.", frontAudio: true },
        { front: "Heute lerne ich Deutsch.", back: "Today I am learning German.", frontAudio: true },
        { front: "Ich weiß, dass du Deutsch lernst.", back: "I know that you are learning German.", frontAudio: true },
        { front: "Weil ich müde bin, bleibe ich zu Hause.", back: "Because I am tired, I stay at home.", frontAudio: true },
      ],
    },
  ],
};
