/** @generated by scripts/generate-tts.ts — do not edit. */
export const ttsAudioHashes: string[] = [
  "c7a9e567",
  "942be0bb",
  "70cc70dc",
  "91d0eeb4",
  "cd461014",
  "7600f378",
  "f1d633e0"
];
