#!/usr/bin/env python3
"""Generates natural German audio for every spoken string using Microsoft Edge
TTS (free, no API key). Reads scripts/tts-strings.json, writes:
  public/tts/<voice>/<hash>.mp3
  lib/tts/audio-manifest.ts  (hash lists per voice)

Usage:
  python3 scripts/generate-tts-edge.py
"""

import asyncio
import hashlib
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STRINGS_FILE = ROOT / "scripts" / "tts-strings.json"
OUT_DIR = ROOT / "public" / "tts"
MANIFEST = ROOT / "lib" / "tts" / "audio-manifest.ts"

# Voices exposed in the voice picker as "Edge" options.
VOICES = {
    "Seraphina": "de-DE-SeraphinaMultilingualNeural",
    "Florian": "de-DE-FlorianMultilingualNeural",
}

RATE = os.environ.get("EDGE_TTS_RATE", "+0%")


def tts_hash(text: str) -> str:
    """FNV-1a 32-bit, matching lib/tts/hash.ts exactly."""
    hash_value = 2166136261
    for char in text:
        hash_value ^= ord(char)
        hash_value = (hash_value * 16777619) & 0xFFFFFFFF
    return f"{hash_value:08x}"


async def synthesize_one(voice_key: str, voice_name: str, text: str) -> bytes:
    import edge_tts

    communicate = edge_tts.Communicate(text, voice_name, rate=RATE)
    output = bytearray()
    async for chunk in communicate.stream():
        if chunk["type"] == "audio":
            output.extend(chunk["data"])
    return bytes(output)


async def main() -> None:
    import edge_tts  # noqa: F401 (verify importable)

    strings = json.loads(STRINGS_FILE.read_text(encoding="utf-8"))
    print(f"Generating {len(strings)} strings for {list(VOICES)}")

    manifest: dict[str, list[str]] = {}
    for voice_key in VOICES:
        manifest[voice_key] = []

    for voice_key, voice_name in VOICES.items():
        voice_dir = OUT_DIR / voice_key
        voice_dir.mkdir(parents=True, exist_ok=True)
        done = 0
        skipped = 0
        failed = 0
        for text in strings:
            h = tts_hash(text)
            target = voice_dir / f"{h}.mp3"
            if target.exists():
                skipped += 1
                manifest[voice_key].append(h)
                continue
            try:
                audio = await synthesize_one(voice_key, voice_name, text)
                target.write_bytes(audio)
                manifest[voice_key].append(h)
                done += 1
            except Exception as exc:  # noqa: BLE001
                failed += 1
                print(f"  FAILED ({voice_key}): {text!r} -> {exc}")
            if done % 100 == 0 and done > 0:
                print(f"  [{voice_key}] {done} generated, {skipped} skipped, {failed} failed")
        print(f"  [{voice_key}] done: {done} generated, {skipped} skipped, {failed} failed")

    # Build the full manifest: Gemini (existing .wav files) + Edge voices.
    gemini_file = ROOT / "scripts" / "gemini-hashes.json"
    gemini_hashes = (
        json.loads(gemini_file.read_text(encoding="utf-8")) if gemini_file.exists() else []
    )
    voices_manifest = [
        {
            "id": "Gemini",
            "label": "Gemini (natural)",
            "ext": "wav",
            "hashes": sorted(gemini_hashes),
        },
        {
            "id": "Seraphina",
            "label": "Seraphina (Edge)",
            "ext": "mp3",
            "hashes": sorted(manifest["Seraphina"]),
        },
        {
            "id": "Florian",
            "label": "Florian (Edge)",
            "ext": "mp3",
            "hashes": sorted(manifest["Florian"]),
        },
    ]

    manifest_ts = (
        "/** @generated by scripts/generate-tts-edge.py — do not edit. */\n"
        "export interface TtsVoiceManifest {\n"
        "  id: string;\n"
        "  label: string;\n"
        "  ext: \"wav\" | \"mp3\";\n"
        "  hashes: string[];\n"
        "}\n\n"
        "export const ttsAudioVoices: TtsVoiceManifest[] = "
        + json.dumps(voices_manifest, indent=2)
        + ";\n"
    )
    MANIFEST.write_text(manifest_ts, encoding="utf-8")
    total = sum(len(v["hashes"]) for v in voices_manifest)
    print(f"Manifest written: {total} clips across {len(voices_manifest)} voices")


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("Interrupted")
        sys.exit(1)