#!/usr/bin/env python3
"""Concurrent natural German audio generation using Microsoft Edge TTS.

Reads scripts/tts-strings.json and synthesizes every string for each voice in
VOICES using a worker pool. Writes:
  public/tts/<voice>/<hash>.mp3
  lib/tts/audio-manifest.ts

Usage:
  python3 scripts/generate-tts-edge.py            # all strings, all voices
  python3 scripts/generate-tts-edge.py 100        # first 100 strings per voice
"""

import asyncio
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STRINGS_FILE = ROOT / "scripts" / "tts-strings.json"
OUT_DIR = ROOT / "public" / "tts"
MANIFEST = ROOT / "lib" / "tts" / "audio-manifest.ts"

# The six site voices, in auto-play order.
VOICES = {
    "Katja": "de-DE-KatjaNeural",
    "Conrad": "de-DE-ConradNeural",
    "Killian": "de-DE-KillianNeural",
    "Amala": "de-DE-AmalaNeural",
    "Seraphina": "de-DE-SeraphinaMultilingualNeural",
    "Florian": "de-DE-FlorianMultilingualNeural",
}

RATE = os.environ.get("EDGE_TTS_RATE", "+0%")
CONCURRENCY = int(os.environ.get("EDGE_TTS_CONCURRENCY", "20"))


def tts_hash(text: str) -> str:
    """FNV-1a 32-bit, matching lib/tts/hash.ts exactly."""
    hash_value = 2166136261
    for char in text:
        hash_value ^= ord(char)
        hash_value = (hash_value * 16777619) & 0xFFFFFFFF
    return f"{hash_value:08x}"


async def synthesize_one(voice_name: str, text: str) -> bytes:
    import edge_tts

    communicate = edge_tts.Communicate(text, voice_name, rate=RATE)
    output = bytearray()
    async for chunk in communicate.stream():
        if chunk["type"] == "audio":
            output.extend(chunk["data"])
    return bytes(output)


async def worker(
    semaphore: asyncio.Semaphore,
    voice_name: str,
    text: str,
    target: Path,
) -> bool:
    async with semaphore:
        try:
            if target.exists():
                return True
            audio = await synthesize_one(voice_name, text)
            target.write_bytes(audio)
            return True
        except Exception:  # noqa: BLE001
            return False


async def generate_voice(voice_key: str, voice_name: str, strings: list[str]) -> list[str]:
    voice_dir = OUT_DIR / voice_key
    voice_dir.mkdir(parents=True, exist_ok=True)

    semaphore = asyncio.Semaphore(CONCURRENCY)
    skipped = 0
    hashes: list[str] = []

    tasks = []
    for text in strings:
        h = tts_hash(text)
        target = voice_dir / f"{h}.mp3"
        hashes.append(h)
        if target.exists():
            skipped += 1
            continue
        tasks.append(worker(semaphore, voice_name, text, target))

    results = await asyncio.gather(*tasks)
    done = sum(1 for ok in results if ok)
    failed = len(tasks) - done
    print(f"  [{voice_key}] done: {done} generated, {skipped} skipped, {failed} failed")
    return hashes


async def main() -> None:
    import edge_tts  # noqa: F401

    limit = None
    if len(sys.argv) > 1:
        limit = int(sys.argv[1])

    strings = json.loads(STRINGS_FILE.read_text(encoding="utf-8"))
    if limit:
        strings = strings[:limit]
    print(f"Generating {len(strings)} strings for {list(VOICES)} (concurrency {CONCURRENCY})")

    edge_hashes: dict[str, list[str]] = {}
    for voice_key, voice_name in VOICES.items():
        edge_hashes[voice_key] = await generate_voice(voice_key, voice_name, strings)

    voices_manifest = [
        {
            "id": voice_key,
            "label": f"{voice_key} (Edge)",
            "ext": "mp3",
            "hashes": sorted(edge_hashes[voice_key]),
        }
        for voice_key in VOICES
    ]

    manifest_ts = (
        "/** @generated by scripts/generate-tts-edge.py — do not edit. */\n"
        "export interface TtsVoiceManifest {\n"
        '  id: string;\n  label: string;\n  ext: "wav" | "mp3";\n  hashes: string[];\n'
        "}\n\n"
        "export const ttsAudioVoices: TtsVoiceManifest[] = "
        + json.dumps(voices_manifest, indent=2)
        + ";\n"
    )
    MANIFEST.write_text(manifest_ts, encoding="utf-8")
    total = sum(len(v["hashes"]) for v in voices_manifest)
    print(f"Manifest written: {total} clips across {len(voices_manifest)} voices")


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("Interrupted")
        sys.exit(1)