import type { Lesson, Exercise } from "../../../schema";
import { translationForSentence, translationForChunks } from "./translations";

/**
 * Goethe A1 practice exam: 300 questions, one per exercise card, in the
 * Ankommo exercise style. Factories keep the authoring compact: each line
 * is one exam question with distractors and a rule explanation.
 */

function h(
  n: number,
  prompt: string,
  options: [string, string, string],
  correct: number,
  explain: string,
): Exercise {
  return {
    id: `f${String(n).padStart(3, "0")}`,
    type: "listening",
    title: `Frage ${n}: Hören`,
    instruction: "Play the audio and pick what you heard.",
    prompt,
    options: [...options],
    correctIndex: correct,
    explain,
  };
}

function m(
  n: number,
  part: string,
  prompt: string,
  options: [string, string, string],
  correct: number,
  explain: string,
  hint = "",
): Exercise {
  return {
    id: `f${String(n).padStart(3, "0")}`,
    type: "multiple-choice",
    title: `Frage ${n}: ${part}`,
    instruction: hint || "Which word fits the gap?",
    prompt,
    options: [...options],
    correctIndex: correct,
    explain,
  };
}

function fb(
  n: number,
  sentence: string,
  blanks: { answers: string[]; hint?: string }[],
  hint = "Type the missing word.",
): Exercise {
  return {
    id: `f${String(n).padStart(3, "0")}`,
    type: "fill-blank",
    title: `Frage ${n}: Schreiben`,
    instruction: hint,
    sentence,
    translation: translationForSentence(sentence),
    blanks,
  };
}

function wo(
  n: number,
  instruction: string,
  chunks: string[],
  explain: string,
): Exercise {
  return {
    id: `f${String(n).padStart(3, "0")}`,
    type: "word-order",
    title: `Frage ${n}: Satz bauen`,
    instruction,
    chunks,
    translation: translationForChunks(chunks),
    explain,
  };
}

export const goethePracticeExam: Lesson = {
  id: "goethe-a1-practice-exam",
  title: "Goethe A1 Practice Exam (300 Fragen)",
  summary:
    "A very detailed Goethe-standard practice exam: 300 individual questions across listening, reading, writing, vocabulary, and sentence building.",
  status: "ready",
  sections: [
    {
      heading: "So ist die Prüfung aufgebaut",
      blocks: [
        {
          type: "paragraph",
          text: "This practice exam mirrors the real Goethe A1 paper with 300 individual questions in six parts: Hören (listening), Wortwahl (reading, gap questions), Artikel und Formen (grammar), Schreiben (writing), Wortschatz (vocabulary), and Sätze bauen (sentence building). Each question is its own exercise card, so you always know exactly where you stand.",
        },
        {
          type: "table",
          caption: "The six parts",
          head: ["Part", "Questions", "Format"],
          rows: [
            ["1. Hören", "1-75", "Play the audio, pick what you heard"],
            ["2. Wortwahl", "76-165", "Which word fits the gap?"],
            ["3. Artikel und Formen", "166-225", "Choose the correct article or verb form"],
            ["4. Schreiben", "226-270", "Type the missing word"],
            ["5. Wortschatz", "271-285", "Translate the word"],
            ["6. Sätze bauen", "286-300", "Build the sentence in order"],
          ],
        },
        {
          type: "tip",
          text: "The real Goethe A1 exam needs about 60 percent per part to pass. Aim for 45 of 75 in listening, 54 of 90 in word choice, and so on. Everything you need to score those points is explained in the Grammatik Kompakt lessons.",
        },
      ],
    },
    {
      heading: "Teil 1: Hören (Fragen 1-75)",
      blocks: [
        {
          type: "paragraph",
          text: "The listening part covers the five exam topics in depth: greetings and leave-takings, numbers and prices, personal data, daily routine, and directions. Every question has a one-line explanation, so a wrong answer teaches you the rule.",
        },
        {
          type: "tip",
          text: "Read the three options before pressing play. You are not listening for every word, only for the detail that separates the options.",
        },
      ],
    },
    {
      heading: "Teil 2: Wortwahl (Fragen 76-165)",
      blocks: [
        {
          type: "paragraph",
          text: "The gap question is the heart of the Goethe reading part: a real German sentence with one word missing. The sentence gives the grammar, the options are real words, and only one completes it naturally.",
        },
        {
          type: "tip",
          text: "Read the whole sentence before looking at the options. The missing word must fit the grammar of its sentence: einen Termin, die Apotheke, zur Arbeit.",
        },
      ],
    },
    {
      heading: "Teil 3: Artikel und Formen (Fragen 166-225)",
      blocks: [
        {
          type: "paragraph",
          text: "This part checks the A1 grammar system: der, die, das and ein, keine; the accusative and dative articles; and the verb forms of regular, strong, and modal verbs.",
        },
        {
          type: "tip",
          text: "Ask the case question: wer? nominative, wen? accusative, wem? dative. For verbs, the person decides the ending.",
        },
      ],
    },
    {
      heading: "Teil 4: Schreiben (Fragen 226-270)",
      blocks: [
        {
          type: "paragraph",
          text: "The writing part covers the form you fill in on your first days in Germany, then the Perfekt, prepositions, modals, and negation.",
        },
        {
          type: "tip",
          text: "Type without thinking: Nachname, Vorname, Adresse, Telefonnummer, Jahre alt. The checker accepts ae/oe/ue for umlauts.",
        },
      ],
    },
    {
      heading: "Teil 5: Wortschatz und Sätze (Fragen 271-300)",
      blocks: [
        {
          type: "paragraph",
          text: "The last thirty questions translate the vocabulary of life in Germany and build sentences with correct word order: verb second, time before place, participle or prefix at the end.",
        },
        {
          type: "tip",
          text: "Build each sentence out loud first, then tap the words. Speaking forces your brain to use the word order.",
        },
      ],
    },
  ],
  vocab: [
    { id: "die-pruefung", de: "die Prüfung", en: "the exam", part: "noun f.", plural: "die Prüfungen", audio: true },
    { id: "das-hoeren", de: "das Hören", en: "the listening (part)", part: "noun n.", audio: true },
    { id: "das-lesen", de: "das Lesen", en: "the reading (part)", part: "noun n.", audio: true },
    { id: "das-schreiben", de: "das Schreiben", en: "the writing (part)", part: "noun n.", audio: true },
    { id: "das-sprechen", de: "das Sprechen", en: "the speaking (part)", part: "noun n.", audio: true },
    { id: "der-termin", de: "der Termin", en: "the appointment", part: "noun m.", plural: "die Termine", audio: true },
    { id: "die-anmeldung", de: "die Anmeldung", en: "the registration", part: "noun f.", plural: "die Anmeldungen", audio: true },
    { id: "das-formular", de: "das Formular", en: "the form", part: "noun n.", plural: "die Formulare", audio: true },
    { id: "die-fahrkarte", de: "die Fahrkarte", en: "the ticket", part: "noun f.", plural: "die Fahrkarten", audio: true },
    { id: "die-oefnungszeiten", de: "die Öffnungszeiten", en: "the opening hours", part: "noun pl.", audio: true },
    { id: "der-eingang", de: "der Eingang", en: "the entrance", part: "noun m.", plural: "die Eingänge", audio: true },
    { id: "bestehen", de: "bestehen", en: "to pass (an exam)", part: "verb", audio: true },
  ],
  exercises: [
    // ---------- Teil 1: Hören (1-75) ----------
    h(1, "Guten Morgen", ["Guten Morgen", "Guten Abend", "Gute Nacht"], 0, "The morning greeting is Guten Morgen."),
    h(2, "Guten Abend", ["Guten Abend", "Guten Morgen", "Gute Nacht"], 0, "The evening greeting is Guten Abend."),
    h(3, "Gute Nacht", ["Gute Nacht", "Guten Morgen", "Guten Tag"], 0, "Gute Nacht is said when going to bed."),
    h(4, "Guten Tag", ["Guten Tag", "Guten Abend", "Gute Nacht"], 0, "The neutral daytime greeting is Guten Tag."),
    h(5, "Hallo", ["Hallo", "Tschüss", "Bis bald"], 0, "Hallo is the all-purpose informal hello."),
    h(6, "Auf Wiedersehen", ["Auf Wiedersehen", "Bis bald", "Tschüss"], 0, "Auf Wiedersehen is the formal goodbye."),
    h(7, "Tschüss", ["Tschüss", "Auf Wiedersehen", "Guten Tag"], 0, "Tschüss is the informal bye."),
    h(8, "Bis bald", ["Bis bald", "Bis morgen", "Auf Wiedersehen"], 0, "Bis bald means see you soon."),
    h(9, "Bis morgen", ["Bis morgen", "Bis bald", "Guten Abend"], 0, "Bis morgen means see you tomorrow."),
    h(10, "Schönen Tag noch", ["Schönen Tag noch", "Guten Morgen", "Gute Nacht"], 0, "Schönen Tag noch is the polite daytime farewell."),
    h(11, "Wie geht es dir?", ["Wie geht es dir?", "Wie geht es Ihnen?", "Wie heißen Sie?"], 0, "The informal how-are-you uses dir."),
    h(12, "Wie geht es Ihnen?", ["Wie geht es Ihnen?", "Wie geht es dir?", "Wie alt sind Sie?"], 0, "The formal how-are-you uses Ihnen."),
    h(13, "Mir geht es gut.", ["Mir geht es gut.", "Mir geht es schlecht.", "Es geht so."], 0, "The answer heard was Mir geht es gut."),
    h(14, "Es geht so.", ["Es geht so.", "Sehr gut!", "Nicht so gut."], 0, "Es geht so means so so."),
    h(15, "Und dir?", ["Und dir?", "Und Ihnen?", "Wie heißt du?"], 0, "Und dir is the informal asking back."),
    h(16, "Ich heiße Anna.", ["Ich heiße Anna.", "Ich heiße Anna Müller.", "Ich bin Anna Müller."], 0, "The first name heard is Anna."),
    h(17, "Ich heiße Anna Müller.", ["Ich heiße Anna Müller.", "Ich heiße Anna Maier.", "Ich heiße Anna Schmidt."], 0, "The last name heard is Müller."),
    h(18, "Ich komme aus Italien.", ["Ich komme aus Italien.", "Ich komme aus Spanien.", "Ich komme aus Frankreich."], 0, "The origin heard is Italy."),
    h(19, "Ich komme aus der Schweiz.", ["Ich komme aus der Schweiz.", "Ich komme aus Österreich.", "Ich komme aus Deutschland."], 0, "The country heard is Switzerland."),
    h(20, "Ich bin Lehrer.", ["Ich bin Lehrer.", "Ich bin Ärztin.", "Ich bin Student."], 0, "The profession heard is teacher."),
    h(21, "Ich bin Studentin.", ["Ich bin Studentin.", "Ich bin Student.", "Ich bin Lehrerin."], 0, "The female student form is Studentin."),
    h(22, "Ich wohne in Berlin.", ["Ich wohne in Berlin.", "Ich wohne in Hamburg.", "Ich wohne in München."], 0, "The city heard is Berlin."),
    h(23, "Ich wohne in der Hauptstraße 5.", ["Ich wohne in der Hauptstraße 5.", "Ich wohne in der Bahnhofstraße 5.", "Ich wohne in der Schulstraße 5."], 0, "The street heard is Hauptstraße."),
    h(24, "Meine Telefonnummer ist 0172 34 56 78.", ["Meine Telefonnummer ist 0172 34 56 78.", "Meine Telefonnummer ist 0173 34 56 78.", "Meine Telefonnummer ist 0174 34 56 78."], 0, "The number starts with 0172."),
    h(25, "Meine Handynummer ist 0151 22 33 44.", ["Meine Handynummer ist 0151 22 33 44.", "Meine Handynummer ist 0152 22 33 44.", "Meine Handynummer ist 0151 22 44 33."], 0, "The mobile number heard starts 0151."),
    h(26, "Ich bin 25 Jahre alt.", ["Ich bin 25 Jahre alt.", "Ich bin 35 Jahre alt.", "Ich bin 26 Jahre alt."], 0, "The age heard is 25."),
    h(27, "Ich bin 1995 geboren.", ["Ich bin 1995 geboren.", "Ich bin 1990 geboren.", "Ich bin 1955 geboren."], 0, "The year heard is 1995."),
    h(28, "Mein Geburtstag ist am fünften Mai.", ["Mein Geburtstag ist am fünften Mai.", "Mein Geburtstag ist am fünften März.", "Mein Geburtstag ist am ersten Mai."], 0, "The birthday heard is May 5th."),
    h(29, "Ich spreche ein bisschen Deutsch.", ["Ich spreche ein bisschen Deutsch.", "Ich spreche gut Deutsch.", "Ich spreche kein Deutsch."], 0, "The person speaks a little German."),
    h(30, "Ich spreche sehr gut Deutsch.", ["Ich spreche sehr gut Deutsch.", "Ich spreche ein bisschen Deutsch.", "Ich spreche nicht gut Deutsch."], 0, "The person speaks German very well."),
    h(31, "eins", ["eins", "zwei", "drei"], 0, "The number heard is one."),
    h(32, "zwei", ["zwei", "zwölf", "zwanzig"], 0, "The number heard is two."),
    h(33, "drei", ["drei", "dreißig", "dreizehn"], 0, "The number heard is three."),
    h(34, "fünf", ["fünf", "fünfzehn", "fünfzig"], 0, "The number heard is five."),
    h(35, "acht", ["acht", "achtzehn", "achtzig"], 0, "The number heard is eight."),
    h(36, "zehn", ["zehn", "drei", "tausend"], 0, "The number heard is ten."),
    h(37, "elf", ["elf", "eins", "zwölf"], 0, "The number heard is eleven."),
    h(38, "zwölf", ["zwölf", "zwei", "zwanzig"], 0, "The number heard is twelve."),
    h(39, "zwanzig", ["zwanzig", "zwölf", "zwei"], 0, "The number heard is twenty."),
    h(40, "dreißig", ["dreißig", "dreizehn", "drei"], 0, "The number heard is thirty."),
    h(41, "einundzwanzig", ["einundzwanzig", "eins", "einzig"], 0, "The number heard is twenty-one."),
    h(42, "siebenundvierzig", ["siebenundvierzig", "vierundsiebzig", "vierzig"], 0, "The number heard is forty-seven."),
    h(43, "hundert", ["hundert", "tausend", "eine Million"], 0, "The number heard is one hundred."),
    h(44, "tausend", ["tausend", "hundert", "eine Million"], 0, "The number heard is one thousand."),
    h(45, "eine Million", ["eine Million", "tausend", "hundert"], 0, "The number heard is one million."),
    h(46, "zehn Euro", ["zehn Euro", "zehn Cent", "zehn Uhr"], 0, "The price heard is ten euros."),
    h(47, "zehn Euro neunzig", ["zehn Euro neunzig", "neun Euro zehn", "neunzehn Euro"], 0, "The price heard is 10.90 euros."),
    h(48, "fünfundzwanzig Euro", ["fünfundzwanzig Euro", "fünfzehn Euro", "fünfzig Euro"], 0, "The price heard is 25 euros."),
    h(49, "drei Euro zwanzig", ["drei Euro zwanzig", "drei Euro zwei", "zwanzig Euro drei"], 0, "The price heard is 3.20 euros."),
    h(50, "fünf Cent", ["fünf Cent", "fünfzig Cent", "fünf Euro"], 0, "The amount heard is five cents."),
    h(51, "Ich stehe um sechs Uhr auf.", ["Ich stehe um sechs Uhr auf.", "Ich stehe um sieben Uhr auf.", "Ich stehe um acht Uhr auf."], 0, "The wake-up time is six."),
    h(52, "Ich stehe um sieben Uhr auf.", ["Ich stehe um sieben Uhr auf.", "Ich stehe um sechs Uhr auf.", "Ich stehe um neun Uhr auf."], 0, "The wake-up time is seven."),
    h(53, "Ich frühstücke um acht Uhr.", ["Ich frühstücke um acht Uhr.", "Ich frühstücke um sieben Uhr.", "Ich frühstücke um neun Uhr."], 0, "Breakfast is at eight."),
    h(54, "Ich arbeite von neun bis fünf.", ["Ich arbeite von neun bis fünf.", "Ich arbeite von acht bis vier.", "Ich arbeite von zehn bis sechs."], 0, "The working hours are nine to five."),
    h(55, "Ich fahre mit dem Bus zur Arbeit.", ["Ich fahre mit dem Bus zur Arbeit.", "Ich fahre mit dem Zug zur Arbeit.", "Ich fahre mit dem Auto zur Arbeit."], 0, "The transport heard is the bus."),
    h(56, "Ich gehe um halb acht zur Arbeit.", ["Ich gehe um halb acht zur Arbeit.", "Ich gehe um halb sieben zur Arbeit.", "Ich gehe um halb neun zur Arbeit."], 0, "The time heard is half past seven."),
    h(57, "Um zwölf Uhr esse ich Mittag.", ["Um zwölf Uhr esse ich Mittag.", "Um elf Uhr esse ich Mittag.", "Um eins esse ich Mittag."], 0, "Lunch is at twelve."),
    h(58, "Am Abend sehe ich fern.", ["Am Abend sehe ich fern.", "Am Morgen sehe ich fern.", "Am Mittag sehe ich fern."], 0, "TV happens in the evening."),
    h(59, "Am Abend koche ich.", ["Am Abend koche ich.", "Am Morgen koche ich.", "Am Nachmittag koche ich."], 0, "Cooking happens in the evening."),
    h(60, "Am Wochenende treffe ich Freunde.", ["Am Wochenende treffe ich Freunde.", "Am Montag treffe ich Freunde.", "Am Dienstag treffe ich Freunde."], 0, "Friends are met at the weekend."),
    h(61, "Ich schlafe um zehn Uhr.", ["Ich schlafe um zehn Uhr.", "Ich schlafe um elf Uhr.", "Ich schlafe um neun Uhr."], 0, "Bedtime is ten o'clock."),
    h(62, "Ich lerne jeden Tag Deutsch.", ["Ich lerne jeden Tag Deutsch.", "Ich lerne jeden Montag Deutsch.", "Ich lerne jeden Morgen Deutsch."], 0, "German is learned every day."),
    h(63, "Ich gehe zweimal pro Woche schwimmen.", ["Ich gehe zweimal pro Woche schwimmen.", "Ich gehe einmal pro Woche schwimmen.", "Ich gehe dreimal pro Woche schwimmen."], 0, "Swimming happens twice a week."),
    h(64, "Am Montag habe ich einen Termin.", ["Am Montag habe ich einen Termin.", "Am Dienstag habe ich einen Termin.", "Am Mittwoch habe ich einen Termin."], 0, "The appointment is on Monday."),
    h(65, "Der Kurs beginnt um neun Uhr.", ["Der Kurs beginnt um neun Uhr.", "Der Kurs beginnt um zehn Uhr.", "Der Kurs beginnt um acht Uhr."], 0, "The course starts at nine."),
    h(66, "Gehen Sie geradeaus.", ["Gehen Sie geradeaus.", "Gehen Sie links.", "Gehen Sie rechts."], 0, "The direction heard is straight ahead."),
    h(67, "An der Ampel links.", ["An der Ampel links.", "An der Ampel rechts.", "An der Ampel geradeaus."], 0, "At the traffic light, turn left."),
    h(68, "An der Kreuzung rechts.", ["An der Kreuzung rechts.", "An der Kreuzung links.", "An der Ampel rechts."], 0, "At the crossing, turn right."),
    h(69, "Die zweite Straße rechts.", ["Die zweite Straße rechts.", "Die erste Straße rechts.", "Die dritte Straße rechts."], 0, "The second street on the right."),
    h(70, "Die Apotheke ist um die Ecke.", ["Die Apotheke ist um die Ecke.", "Die Apotheke ist gegenüber.", "Die Apotheke ist neben dem Kino."], 0, "The pharmacy is around the corner."),
    h(71, "Der Bahnhof ist gegenüber der Bank.", ["Der Bahnhof ist gegenüber der Bank.", "Der Bahnhof ist neben der Bank.", "Der Bahnhof ist hinter der Bank."], 0, "The station is opposite the bank."),
    h(72, "Das Kino ist neben dem Museum.", ["Das Kino ist neben dem Museum.", "Das Kino ist gegenüber dem Museum.", "Das Kino ist hinter dem Museum."], 0, "The cinema is next to the museum."),
    h(73, "Der Bus hat zehn Minuten Verspätung.", ["Der Bus hat zehn Minuten Verspätung.", "Der Bus hat fünf Minuten Verspätung.", "Der Zug hat zehn Minuten Verspätung."], 0, "The delay heard is ten minutes."),
    h(74, "Ich brauche eine Fahrkarte nach Berlin.", ["Ich brauche eine Fahrkarte nach Berlin.", "Ich brauche eine Fahrkarte nach Hamburg.", "Ich brauche eine Fahrkarte nach München."], 0, "The ticket is for Berlin."),
    h(75, "Sie müssen in Hamburg umsteigen.", ["Sie müssen in Hamburg umsteigen.", "Sie müssen in München umsteigen.", "Sie müssen in Berlin umsteigen."], 0, "The change is in Hamburg."),
    // ---------- Teil 2: Wortwahl (76-165) ----------
    m(76, "Wortwahl", "Ich habe morgen einen ___ beim Bürgeramt.", ["Termin", "Formular", "Ausweis"], 0, "The appointment is der Termin: einen Termin haben."),
    m(77, "Wortwahl", "Bitte füllen Sie dieses ___ aus.", ["Formular", "Termin", "Konto"], 0, "The form is das Formular: ein Formular ausfüllen."),
    m(78, "Wortwahl", "Ich muss mich beim Bürgeramt ___.", ["anmelden", "anrufen", "ankommen"], 0, "Registering is sich anmelden."),
    m(79, "Wortwahl", "Die ___ für diese Wohnung ist 600 Euro.", ["Miete", "Kaution", "Quittung"], 0, "The rent is die Miete."),
    m(80, "Wortwahl", "Unser ___ heißt Huber.", ["Vermieter", "Kunde", "Chef"], 0, "The landlord is der Vermieter."),
    m(81, "Wortwahl", "Ich brauche eine Fahrkarte ___ Berlin.", ["nach", "in", "bei"], 0, "Cities take nach: nach Berlin."),
    m(82, "Wortwahl", "Der Zug fährt um 14:30 Uhr ___.", ["ab", "auf", "an"], 0, "abfahren is separable: the prefix ab waits at the end."),
    m(83, "Wortwahl", "Wann kommt der Zug in Hamburg ___?", ["an", "ab", "auf"], 0, "ankommen is separable: kommt ... an."),
    m(84, "Wortwahl", "Sie müssen in Hamburg ___.", ["umsteigen", "anrufen", "aufstehen"], 0, "Changing trains is umsteigen."),
    m(85, "Wortwahl", "Der Bus hat zehn Minuten ___.", ["Verspätung", "Haltestelle", "Fahrkarte"], 0, "The delay is die Verspätung."),
    m(86, "Wortwahl", "Ich brauche ein ___ nach München.", ["Ticket", "Zimmer", "Bett"], 0, "The ticket is das Ticket."),
    m(87, "Wortwahl", "Der Bahnsteig für den Zug nach Berlin ist Gleis 4.", ["der Bahnsteig", "die Haltestelle", "die Straße"], 0, "The platform is der Bahnsteig."),
    m(88, "Wortwahl", "Ich suche eine ___ in Größe 38.", ["Hose", "Hemd", "Schal"], 0, "Pants are die Hose, feminine: eine Hose."),
    m(89, "Wortwahl", "Kann ich das ___?", ["anprobieren", "anrufen", "aufstehen"], 0, "Trying on is anprobieren."),
    m(90, "Wortwahl", "Die Jacke ist zu ___.", ["teuer", "billig", "frei"], 0, "zu teuer means too expensive."),
    m(91, "Wortwahl", "Ich möchte mein Geld ___.", ["zurück", "vor", "mit"], 0, "Money back is das Geld zurück."),
    m(92, "Wortwahl", "Ich möchte diese Hose ___.", ["umtauschen", "mitkommen", "aufstehen"], 0, "Exchanging is umtauschen."),
    m(93, "Wortwahl", "Haben Sie den ___?", ["Kassenbon", "Termin", "Bericht"], 0, "The receipt is der Kassenbon."),
    m(94, "Wortwahl", "Die Wohnung hat zwei ___ und einen Balkon.", ["Zimmer", "Stunden", "Straßen"], 0, "Rooms are die Zimmer, plural unchanged."),
    m(95, "Wortwahl", "Die Miete ist 850 Euro ___.", ["kalt", "heiß", "warm"], 0, "Kaltmiete is rent without utilities."),
    m(96, "Wortwahl", "Die Wohnung ist im dritten ___.", ["Stock", "Zimmer", "Balkon"], 0, "The floor is der Stock."),
    m(97, "Wortwahl", "Das Sofa steht im ___.", ["Wohnzimmer", "Bahnhof", "Büro"], 0, "The living room is das Wohnzimmer."),
    m(98, "Wortwahl", "Der Kühlschrank steht in der ___.", ["Küche", "Schule", "Apotheke"], 0, "The kitchen is die Küche."),
    m(99, "Wortwahl", "Entschuldigung, wo ist die ___?", ["Apotheke", "Bahnhof", "Park"], 0, "The pharmacy is die Apotheke, feminine."),
    m(100, "Wortwahl", "Gehen Sie ___ und dann links.", ["geradeaus", "rechts", "gegenüber"], 0, "Straight ahead is geradeaus."),
    m(101, "Wortwahl", "Das Kino ist um die ___.", ["Ecke", "Stunde", "Straße"], 0, "The corner is die Ecke."),
    m(102, "Wortwahl", "Ich gehe heute ___ ins Kino.", ["Abend", "Morgen", "Tag"], 0, "Tonight is heute Abend."),
    m(103, "Wortwahl", "Ich habe ___ und Husten.", ["Fieber", "Jacke", "Termin"], 0, "A fever is das Fieber."),
    m(104, "Wortwahl", "Mir tut der ___ weh.", ["Kopf", "Handschuh", "Schuh"], 0, "The head is der Kopf: Mir tut der Kopf weh."),
    m(105, "Wortwahl", "Ich habe einen Termin beim ___.", ["Arzt", "Bus", "Kino"], 0, "The doctor is der Arzt: beim Arzt."),
    m(106, "Wortwahl", "Nehmen Sie diese ___.", ["Tabletten", "Zimmer", "Karten"], 0, "Pills are die Tabletten."),
    m(107, "Wortwahl", "Das ___ bekommen Sie in der Apotheke.", ["Medikament", "Termin", "Ticket"], 0, "The medicine is das Medikament."),
    m(108, "Wortwahl", "Ich bin ___ von Beruf.", ["Lehrer", "Berlin", "Deutsch"], 0, "Professions come without an article."),
    m(109, "Wortwahl", "Ich arbeite als ___ in einem Restaurant.", ["Koch", "Bus", "Zimmer"], 0, "The cook is der Koch."),
    m(110, "Wortwahl", "Um zehn Uhr haben wir eine ___.", ["Besprechung", "Wohnung", "Fahrkarte"], 0, "The meeting is die Besprechung."),
    m(111, "Wortwahl", "Ich brauche den Bericht ___ Freitag.", ["bis", "seit", "um"], 0, "By Friday is bis Freitag."),
    m(112, "Wortwahl", "Ich lerne Deutsch, ___ ich in Deutschland lebe.", ["denn", "oder", "aber"], 0, "denn gives the reason and keeps the verb second."),
    m(113, "Wortwahl", "Ich habe kein Auto, ___ ein Fahrrad.", ["sondern", "aber", "denn"], 0, "After a negation, the alternative is sondern."),
    m(114, "Wortwahl", "___ Sie bitte das Formular aus?", ["Füllen", "Füllt", "Füll"], 0, "The polite imperative is the infinitive plus Sie."),
    m(115, "Wortwahl", "Wie ___ kostet das?", ["viel", "viele", "oft"], 0, "Uncountable amounts take wie viel."),
    m(116, "Wortwahl", "Der Kurs ___ um neun an.", ["fängt", "fangt", "fing"], 0, "anfangen with an umlaut: fängt an."),
    m(117, "Wortwahl", "Ich ___ dich heute Abend an.", ["rufe", "rufst", "ruft"], 0, "ich takes rufe: Ich rufe dich an."),
    m(118, "Wortwahl", "Ich habe gestern Pizza ___.", ["gegessen", "gespielt", "gekocht"], 0, "Pizza is eaten: gegessen."),
    m(119, "Wortwahl", "Wir ___ gestern nach Berlin gefahren.", ["sind", "haben", "sein"], 0, "Movement takes sein: sind gefahren."),
    m(120, "Wortwahl", "Ich habe ___ Schwester.", ["keine", "nicht", "kein"], 0, "Schwester is feminine: keine."),
    m(121, "Wortwahl", "Ich wohne ___ in Berlin.", ["nicht", "keine", "kein"], 0, "The place is negated with nicht."),
    m(122, "Wortwahl", "Das schmeckt ___.", ["mir", "mich", "ich"], 0, "schmecken takes the dative: mir."),
    m(123, "Wortwahl", "Kannst du ___ helfen?", ["mir", "mich", "ich"], 0, "helfen takes the dative: mir."),
    m(124, "Wortwahl", "Ich gehe ___ Kino.", ["ins", "im", "zum"], 0, "Movement into a place: ins Kino."),
    m(125, "Wortwahl", "Der Termin ist ___ Montag.", ["am", "um", "im"], 0, "Days take am: am Montag."),
    m(126, "Wortwahl", "Ich fahre ___ Deutschland.", ["nach", "in", "aus"], 0, "Countries without article take nach."),
    m(127, "Wortwahl", "Wir fliegen ___ die Schweiz.", ["in", "nach", "zu"], 0, "Article countries take in: in die Schweiz."),
    m(128, "Wortwahl", "Ich komme ___ der Schweiz.", ["aus", "nach", "in"], 0, "Origin takes aus: aus der Schweiz."),
    m(129, "Wortwahl", "Ich gehe ___ Hause.", ["nach", "zu", "aus"], 0, "Home direction is nach Hause."),
    m(130, "Wortwahl", "Ich bin ___ Hause.", ["zu", "nach", "bei"], 0, "Home static is zu Hause."),
    m(131, "Wortwahl", "Wir treffen uns ___ Samstag im Park.", ["am", "um", "im"], 0, "Days take am: am Samstag."),
    m(132, "Wortwahl", "Der Kurs beginnt ___ neun Uhr.", ["um", "am", "im"], 0, "Clock times take um."),
    m(133, "Wortwahl", "___ Juli habe ich Urlaub.", ["Im", "Am", "Um"], 0, "Months take im."),
    m(134, "Wortwahl", "Ich lerne ___ einem Jahr Deutsch.", ["seit", "bis", "um"], 0, "Ongoing since takes seit."),
    m(135, "Wortwahl", "Ich arbeite ___ neun bis fünf.", ["von", "seit", "um"], 0, "Ranges take von ... bis."),
    m(136, "Wortwahl", "___ zwei Tagen ist Weihnachten.", ["In", "Am", "Um"], 0, "Future distance takes in."),
    m(137, "Wortwahl", "Kommst du ___?", ["mit", "auf", "an"], 0, "mitkommen splits: Kommst du mit?"),
    m(138, "Wortwahl", "Ich muss um sieben Uhr ___.", ["aufstehen", "ausgehen", "ankommen"], 0, "Getting up is aufstehen."),
    m(139, "Wortwahl", "Wir laden dich ___.", ["ein", "aus", "ab"], 0, "einladen splits: laden ... ein."),
    m(140, "Wortwahl", "Nimmst du den Regenschirm ___?", ["mit", "ein", "auf"], 0, "mitnehmen splits: nimmst ... mit."),
    m(141, "Wortwahl", "Er kommt morgen ___.", ["zurück", "vor", "auf"], 0, "zurückkommen splits: kommt ... zurück."),
    m(142, "Wortwahl", "Wann fährst du ___?", ["ab", "ein", "mit"], 0, "abfahren splits: fährst ... ab."),
    m(143, "Wortwahl", "Ich möchte mich ___.", ["anmelden", "abmelden", "ankommen"], 0, "Registering is sich anmelden."),
    m(144, "Wortwahl", "Es ist 14:30 Uhr. Das ist ___ Uhr dreißig.", ["vierzehn", "vier", "halb"], 0, "Formal time: vierzehn Uhr dreißig."),
    m(145, "Wortwahl", "Es ist halb neun. Das ist ___.", ["8:30", "9:30", "8:15"], 0, "halb neun is halfway to nine: 8:30."),
    m(146, "Wortwahl", "Es ist Viertel nach acht. Das ist ___.", ["8:15", "8:45", "9:15"], 0, "Viertel nach acht is 8:15."),
    m(147, "Wortwahl", "Der wievielte ist heute? Heute ist der ___ Mai.", ["erste", "eins", "ein"], 0, "Ordinals: der erste Mai."),
    m(148, "Wortwahl", "Wann hast du ___? Am fünften Mai.", ["Geburtstag", "Uhrzeit", "Wochentag"], 0, "The birthday is der Geburtstag."),
    m(149, "Wortwahl", "Ich kaufe ein Pfund ___.", ["Äpfel", "Apfels", "Apfel"], 0, "The plural is die Äpfel."),
    m(150, "Wortwahl", "Die Frau isst das ___.", ["Brot", "Brote", "Broten"], 0, "das Brot is the singular bread."),
    m(151, "Wortwahl", "Ich trinke gern ___.", ["Tee", "Teen", "Tees"], 0, "das Tee? No: der Tee, here accusative-less: Ich trinke gern Tee."),
    m(152, "Wortwahl", "Haben Sie ___?", ["Hunger", "hungrig", "hungern"], 0, "Having hunger is Hunger: Ich habe Hunger."),
    m(153, "Wortwahl", "Ich habe ___.", ["Durst", "dursten", "durstig"], 0, "Having thirst is Durst: Ich habe Durst."),
    m(154, "Wortwahl", "Guten ___!", ["Appetit", "Essen", "Hunger"], 0, "Guten Appetit is the table greeting."),
    m(155, "Wortwahl", "Ich möchte die ___ bitte.", ["Speisekarte", "Fahrkarte", "Kreditkarte"], 0, "The menu is die Speisekarte."),
    m(156, "Wortwahl", "Zahlen ___!", ["bitte", "danke", "gern"], 0, "Zahlen bitte is the way to ask for the bill."),
    m(157, "Wortwahl", "Stimmt so! Das heißt: behalten Sie das ___.", ["Wechselgeld", "Bargeld", "Geld"], 0, "The change is das Wechselgeld."),
    m(158, "Wortwahl", "Ich bezahle mit ___.", ["Karte", "Zimmer", "Termin"], 0, "Paying by card: mit Karte."),
    m(159, "Wortwahl", "Das ist zu teuer. Ich nehme das ___.", ["billig", "teuer", "günstig"], 0, "Cheap is billig or günstig."),
    m(160, "Wortwahl", "Wo ist die ___? Ich möchte ein Paket schicken.", ["Post", "Apotheke", "Schule"], 0, "The post office is die Post."),
    m(161, "Wortwahl", "Ich möchte ein ___ schicken.", ["Paket", "Termin", "Zimmer"], 0, "The parcel is das Paket."),
    m(162, "Wortwahl", "Ich brauche eine ___ auf dem Formular.", ["Unterschrift", "Miete", "Fahrkarte"], 0, "The signature is die Unterschrift."),
    m(163, "Wortwahl", "Schreiben Sie auch eine ___ und einen Gruß.", ["Anrede", "Adresse", "Antwort"], 0, "The form of address is die Anrede."),
    m(164, "Wortwahl", "Ich habe Ihre ___ in der Zeitung gelesen.", ["Anzeige", "Anmeldung", "Antwort"], 0, "The ad is die Anzeige."),
    m(165, "Wortwahl", "Der Unterricht ___ gleich an.", ["fängt", "fangt", "fing"], 0, "Der Unterricht fängt an: anfangen."),
    // ---------- Teil 3: Artikel und Formen (166-225) ----------
    m(166, "Artikel", "___ Mann liest ein Buch.", ["Der", "Die", "Das"], 0, "Mann is masculine: der Mann."),
    m(167, "Artikel", "___ Frau arbeitet im Büro.", ["Die", "Der", "Das"], 0, "Frau is feminine: die Frau."),
    m(168, "Artikel", "___ Kind schläft.", ["Das", "Der", "Die"], 0, "Kind is neuter: das Kind."),
    m(169, "Artikel", "___ Kinder spielen im Park.", ["Die", "Der", "Das"], 0, "The plural article is always die."),
    m(170, "Artikel", "___ Tisch ist neu.", ["Der", "Die", "Das"], 0, "Tisch is masculine: der Tisch."),
    m(171, "Artikel", "___ Lampe ist kaputt.", ["Die", "Der", "Das"], 0, "Lampe is feminine: die Lampe."),
    m(172, "Artikel", "___ Bett ist groß.", ["Das", "Der", "Die"], 0, "Bett is neuter: das Bett."),
    m(173, "Artikel", "___ Wohnung ist im dritten Stock.", ["Die", "Der", "Das"], 0, "Wohnung ends in -ung, feminine."),
    m(174, "Artikel", "___ Bahnhof ist weit weg.", ["Der", "Die", "Das"], 0, "Bahnhof is masculine: der Bahnhof."),
    m(175, "Artikel", "___ Apotheke ist um die Ecke.", ["Die", "Der", "Das"], 0, "Apotheke is feminine: die Apotheke."),
    m(176, "Artikel", "Ich kaufe ___ Apfel.", ["einen", "ein", "eine"], 0, "Masculine accusative: einen Apfel."),
    m(177, "Artikel", "Ich brauche ___ Uhr.", ["eine", "einen", "ein"], 0, "Uhr is feminine: eine Uhr."),
    m(178, "Artikel", "Er hat ___ Bruder.", ["einen", "ein", "eine"], 0, "Masculine accusative: einen Bruder."),
    m(179, "Artikel", "Ich habe ___ Termin.", ["einen", "ein", "eine"], 0, "Masculine accusative: einen Termin."),
    m(180, "Artikel", "Sie hat ___ Schwester.", ["eine", "einen", "ein"], 0, "Feminine: eine Schwester."),
    m(181, "Artikel", "Das ist ___ Kind.", ["ein", "einen", "eine"], 0, "Neuter nominative: ein Kind."),
    m(182, "Artikel", "Ich sehe ___ Mann.", ["den", "der", "dem"], 0, "Accusative masculine: den Mann."),
    m(183, "Artikel", "Ich sehe ___ Frau.", ["die", "der", "dem"], 0, "Accusative feminine stays die."),
    m(184, "Artikel", "Ich sehe ___ Kind.", ["das", "den", "dem"], 0, "Accusative neuter stays das."),
    m(185, "Artikel", "Ich gebe ___ Kind einen Apfel.", ["dem", "den", "der"], 0, "Dative neuter: dem Kind."),
    m(186, "Artikel", "Das Buch liegt auf ___ Tisch.", ["dem", "den", "der"], 0, "Static location: auf dem Tisch."),
    m(187, "Artikel", "Die Lampe hängt an ___ Wand.", ["der", "dem", "den"], 0, "Feminine dative: an der Wand."),
    m(188, "Artikel", "Wir fahren mit ___ Zug.", ["dem", "den", "der"], 0, "Dative after mit: mit dem Zug."),
    m(189, "Artikel", "Ich fahre mit ___ Bus zur Arbeit.", ["dem", "den", "der"], 0, "Dative after mit: mit dem Bus."),
    m(190, "Artikel", "Er ist beim ___ .", ["Arzt", "Arzten", "Ärzte"], 0, "beim is bei dem: beim Arzt."),
    m(191, "Artikel", "Ich gehe zum ___ .", ["Bahnhof", "Bahnhofs", "Bahnhöfe"], 0, "zum is zu dem: zum Bahnhof."),
    m(192, "Artikel", "Wir gehen zur ___.", ["Schule", "Schulen", "Schuler"], 0, "zur is zu der: zur Schule."),
    m(193, "Artikel", "Ich wohne in ___ Wohnung.", ["einer", "einen", "ein"], 0, "Feminine dative: in einer Wohnung."),
    m(194, "Artikel", "Das Sofa steht in ___ Wohnzimmer.", ["dem", "den", "der"], 0, "Neuter dative: im (in dem) Wohnzimmer."),
    m(195, "Artikel", "Ich habe ___ Auto.", ["kein", "keine", "keinen"], 0, "Neuter: kein Auto."),
    m(196, "Artikel", "Ich habe ___ Bruder.", ["keinen", "kein", "keine"], 0, "Masculine accusative: keinen Bruder."),
    m(197, "Artikel", "Ich habe ___ Schwester.", ["keine", "kein", "keinen"], 0, "Feminine: keine Schwester."),
    m(198, "Artikel", "Ich habe ___ Kinder.", ["keine", "kein", "keinen"], 0, "Plural: keine Kinder."),
    m(199, "Artikel", "Ich habe ___ Zeit.", ["keine", "kein", "keinen"], 0, "Feminine: keine Zeit."),
    m(200, "Artikel", "Ich habe ___ Hunger.", ["keinen", "kein", "keine"], 0, "Masculine accusative: keinen Hunger."),
    m(201, "Verbform", "Ich ___ Deutsch.", ["lerne", "lernst", "lernt"], 0, "ich takes -e: lerne."),
    m(202, "Verbform", "Du ___ Englisch.", ["lernst", "lerne", "lernt"], 0, "du takes -st: lernst."),
    m(203, "Verbform", "Er ___ Deutsch.", ["lernt", "lerne", "lernst"], 0, "er takes -t: lernt."),
    m(204, "Verbform", "Wir ___ Deutsch.", ["lernen", "lernt", "lerne"], 0, "wir takes -en: lernen."),
    m(205, "Verbform", "Ihr ___ Deutsch.", ["lernt", "lernen", "lernst"], 0, "ihr takes -t: lernt."),
    m(206, "Verbform", "Ich ___ Anna.", ["bin", "bist", "ist"], 0, "sein, ich: bin."),
    m(207, "Verbform", "Du ___ müde.", ["bist", "bin", "ist"], 0, "sein, du: bist."),
    m(208, "Verbform", "Wir ___ aus Berlin.", ["sind", "seid", "ist"], 0, "sein, wir: sind."),
    m(209, "Verbform", "Ihr ___ müde.", ["seid", "sind", "bist"], 0, "sein, ihr: seid."),
    m(210, "Verbform", "Sie ___ einen Bruder.", ["hat", "hast", "haben"], 0, "haben, sie: hat."),
    m(211, "Verbform", "Ich ___ einen Bruder.", ["habe", "hast", "hat"], 0, "haben, ich: habe."),
    m(212, "Verbform", "Du ___ ein Auto.", ["hast", "habe", "hat"], 0, "haben, du: hast."),
    m(213, "Verbform", "Er ___ nach Berlin.", ["fährt", "fährst", "fahren"], 0, "Strong verb, er: fährt."),
    m(214, "Verbform", "Du ___ nach Berlin.", ["fährst", "fährt", "fahren"], 0, "Strong verb, du: fährst."),
    m(215, "Verbform", "Er ___ Deutsch.", ["spricht", "sprichst", "sprechen"], 0, "Strong verb, er: spricht."),
    m(216, "Verbform", "Du ___ das Buch.", ["liest", "list", "lesen"], 0, "Strong verb, du: liest."),
    m(217, "Verbform", "Was ___ du?", ["isst", "esst", "essen"], 0, "Strong verb, du: isst."),
    m(218, "Verbform", "Ich ___ gut schwimmen.", ["kann", "kannst", "können"], 0, "ich: kann."),
    m(219, "Verbform", "Du ___ schwimmen.", ["kannst", "kann", "können"], 0, "du: kannst."),
    m(220, "Verbform", "Wir ___ nach Berlin fahren.", ["wollen", "will", "willst"], 0, "wir: wollen."),
    m(221, "Verbform", "Ich ___ einen Kaffee.", ["möchte", "möchtest", "möchten"], 0, "ich: möchte."),
    m(222, "Verbform", "Du ___ mehr Wasser trinken.", ["sollst", "soll", "sollen"], 0, "du: sollst."),
    m(223, "Verbform", "Er ___ um sieben aufstehen.", ["muss", "musst", "müssen"], 0, "er: muss."),
    m(224, "Verbform", "Ich habe gestern einen Film ___.", ["gesehen", "sehen", "sieht"], 0, "The participle of sehen is gesehen."),
    m(225, "Verbform", "Wir ___ gestern nach Berlin gefahren.", ["sind", "haben", "habt"], 0, "Movement takes sein: sind gefahren."),
    // ---------- Teil 4: Schreiben (226-270) ----------
    fb(226, "Mein ___ ist Müller.", [{ answers: ["Nachname"], hint: "last name" }], "Type the missing word. (My last name is Müller.)"),
    fb(227, "Mein ___ ist Anna.", [{ answers: ["Vorname"], hint: "first name" }], "Type the missing word. (My first name is Anna.)"),
    fb(228, "Ich wohne in der ___ 5.", [{ answers: ["Hauptstraße"], hint: "the street" }], "Type the missing word. (I live at Hauptstraße 5.)"),
    fb(229, "Meine ___ ist 0172 34 56 78.", [{ answers: ["Telefonnummer"], hint: "phone number" }], "Type the missing word. (My phone number is ...)"),
    fb(230, "Meine ___ ist 0151 22 33 44.", [{ answers: ["Handynummer"], hint: "mobile number" }], "Type the missing word. (My mobile number is ...)"),
    fb(231, "Ich bin 25 ___ alt.", [{ answers: ["Jahre"], hint: "years" }], "Type the missing word. (I am 25 years old.)"),
    fb(232, "Ich bin 1995 ___.", [{ answers: ["geboren"], hint: "born" }], "Type the missing word. (I was born in 1995.)"),
    fb(233, "Mein Geburtstag ist am fünften ___.", [{ answers: ["Mai"], hint: "May" }], "Type the missing word. (My birthday is on May 5th.)"),
    fb(234, "Ich wohne in ___.", [{ answers: ["Berlin"], hint: "the city" }], "Type the missing word. (I live in Berlin.)"),
    fb(235, "Ich komme aus ___.", [{ answers: ["Italien"], hint: "Italy" }], "Type the missing word. (I come from Italy.)"),
    fb(236, "Ich ___ Anna.", [{ answers: ["bin"], hint: "sein, ich" }], "Type the missing verb. (I am Anna.)"),
    fb(237, "Du ___ müde.", [{ answers: ["bist"], hint: "sein, du" }], "Type the missing verb. (You are tired.)"),
    fb(238, "Wir ___ aus Berlin.", [{ answers: ["sind"], hint: "sein, wir" }], "Type the missing verb. (We are from Berlin.)"),
    fb(239, "Sie ___ einen Bruder.", [{ answers: ["hat"], hint: "haben, sie" }], "Type the missing verb. (She has a brother.)"),
    fb(240, "Ich ___ ein Auto.", [{ answers: ["habe"], hint: "haben, ich" }], "Type the missing verb. (I have a car.)"),
    fb(241, "Wir ___ gestern nach Berlin gefahren.", [{ answers: ["sind"], hint: "movement takes sein" }], "Type the missing helper. (We drove to Berlin yesterday.)"),
    fb(242, "Ich habe einen Film ___.", [{ answers: ["gesehen"], hint: "participle of sehen" }], "Type the missing participle. (I have watched a film.)"),
    fb(243, "Ich habe gestern Pizza ___.", [{ answers: ["gegessen"], hint: "participle of essen" }], "Type the missing participle. (I ate pizza yesterday.)"),
    fb(244, "Wir sind nach Berlin ___.", [{ answers: ["gefahren"], hint: "participle of fahren" }], "Type the missing participle. (We drove to Berlin.)"),
    fb(245, "Ich habe einen Brief ___.", [{ answers: ["geschrieben"], hint: "participle of schreiben" }], "Type the missing participle. (I have written a letter.)"),
    fb(246, "Ich ___ gut kochen.", [{ answers: ["kann"], hint: "ability, ich" }], "Type the missing modal. (I can cook well.)"),
    fb(247, "Du ___ mehr Wasser trinken.", [{ answers: ["sollst"], hint: "should, du" }], "Type the missing modal. (You should drink more water.)"),
    fb(248, "Er ___ um sieben aufstehen.", [{ answers: ["muss"], hint: "must, er" }], "Type the missing modal. (He has to get up at seven.)"),
    fb(249, "Ich ___ einen Kaffee.", [{ answers: ["möchte"], hint: "would like, ich" }], "Type the missing modal. (I would like a coffee.)"),
    fb(250, "Wir ___ nach Berlin fahren.", [{ answers: ["wollen"], hint: "want, wir" }], "Type the missing modal. (We want to drive to Berlin.)"),
    fb(251, "Ich muss um sieben Uhr ___.", [{ answers: ["aufstehen"], hint: "separable infinitive" }], "Type the missing verb. (I have to get up at seven.)"),
    fb(252, "Ich ___ dich heute an.", [{ answers: ["rufe"], hint: "anrufen, ich" }], "Type the missing verb. (I am calling you today.)"),
    fb(253, "Der Kurs ___ um neun an.", [{ answers: ["fängt"], hint: "anfangen, er" }], "Type the missing verb. (The course starts at nine.)"),
    fb(254, "Wir ___ dich ein.", [{ answers: ["laden"], hint: "einladen, wir" }], "Type the missing verb. (We are inviting you.)"),
    fb(255, "Der Zug ___ um zehn Uhr ab.", [{ answers: ["fährt"], hint: "abfahren, er" }], "Type the missing verb. (The train departs at ten.)"),
    fb(256, "Der Termin ist ___ Montag.", [{ answers: ["am"], hint: "day of the week" }], "Type the missing preposition. (The appointment is on Monday.)"),
    fb(257, "Ich fahre ___ Berlin.", [{ answers: ["nach"], hint: "city without article" }], "Type the missing preposition. (I drive to Berlin.)"),
    fb(258, "Wir fliegen ___ die Schweiz.", [{ answers: ["in"], hint: "article country" }], "Type the missing preposition. (We fly to Switzerland.)"),
    fb(259, "Ich komme ___ Italien.", [{ answers: ["aus"], hint: "origin" }], "Type the missing preposition. (I come from Italy.)"),
    fb(260, "Ich gehe ___ Kino.", [{ answers: ["ins"], hint: "in + das" }], "Type the missing contraction. (I am going to the cinema.)"),
    fb(261, "Ich fahre mit ___ Zug.", [{ answers: ["dem"], hint: "dative after mit" }], "Type the missing article. (I travel by train.)"),
    fb(262, "Ich habe ___ Auto.", [{ answers: ["kein"], hint: "neuter noun" }], "Type the missing negation. (I have no car.)"),
    fb(263, "Ich habe ___ Schwester.", [{ answers: ["keine"], hint: "feminine noun" }], "Type the missing negation. (I have no sister.)"),
    fb(264, "Ich wohne ___ in Berlin.", [{ answers: ["nicht"], hint: "negation of the place" }], "Type the missing negation. (I do not live in Berlin.)"),
    fb(265, "Ich lerne Deutsch, ___ ich in Deutschland lebe.", [{ answers: ["denn"], hint: "reason, verb stays second" }], "Type the missing conjunction. (I learn German because I live in Germany.)"),
    fb(266, "Ich habe kein Auto, ___ ein Fahrrad.", [{ answers: ["sondern"], hint: "after negation" }], "Type the missing conjunction. (I have no car but a bicycle.)"),
    fb(267, "___ kommst du? Aus Italien.", [{ answers: ["Woher"], hint: "origin" }], "Type the missing question word. (Where are you from?)"),
    fb(268, "___ alt bist du? 25.", [{ answers: ["Wie"], hint: "how" }], "Type the missing question word. (How old are you?)"),
    fb(269, "___ du Deutsch? Ja, ich lerne.", [{ answers: ["Lernst"], hint: "yes/no question, verb first" }], "Type the missing verb. (Are you learning German?)"),
    fb(270, "Kannst du ___ helfen? (me)", [{ answers: ["mir"], hint: "dative pronoun" }], "Type the missing pronoun. (Can you help me?)"),
    // ---------- Teil 5: Wortschatz (271-285) ----------
    m(271, "Wortschatz", "die Anmeldung", ["the registration", "the appointment", "the form"], 0, "die Anmeldung is the registration."),
    m(272, "Wortschatz", "der Termin", ["the appointment", "the ticket", "the rent"], 0, "der Termin is the appointment."),
    m(273, "Wortschatz", "das Formular", ["the form", "the key", "the street"], 0, "das Formular is the form."),
    m(274, "Wortschatz", "die Fahrkarte", ["the ticket", "the key", "the street"], 0, "die Fahrkarte is the ticket."),
    m(275, "Wortschatz", "die Öffnungszeiten", ["the opening hours", "the working day", "the office"], 0, "die Öffnungszeiten are the opening hours."),
    m(276, "Wortschatz", "der Eingang", ["the entrance", "the exit", "the door"], 0, "der Eingang is the entrance."),
    m(277, "Wortschatz", "der Ausgang", ["the exit", "the entrance", "the arrival"], 0, "der Ausgang is the exit."),
    m(278, "Wortschatz", "die Miete", ["the rent", "the ticket", "the key"], 0, "die Miete is the rent."),
    m(279, "Wortschatz", "die Kaution", ["the deposit", "the rent", "the bill"], 0, "die Kaution is the deposit."),
    m(280, "Wortschatz", "der Vermieter", ["the landlord", "the tenant", "the seller"], 0, "der Vermieter is the landlord."),
    m(281, "Wortschatz", "gegessen", ["eaten", "drunk", "seen"], 0, "gegessen is eaten."),
    m(282, "Wortschatz", "gefahren", ["driven, traveled", "flown", "gone"], 0, "gefahren is driven."),
    m(283, "Wortschatz", "aufgestanden", ["got up", "gone out", "arrived"], 0, "aufgestanden is got up."),
    m(284, "Wortschatz", "der Kühlschrank", ["the fridge", "the cupboard", "the stove"], 0, "der Kühlschrank is the fridge."),
    m(285, "Wortschatz", "die Haltestelle", ["the stop", "the station", "the platform"], 0, "die Haltestelle is the stop."),
    // ---------- Teil 6: Sätze bauen (286-300) ----------
    wo(286, "Build the sentence: My name is Anna.", ["Ich", "heiße", "Anna."], "The verb heiße stays in second position."),
    wo(287, "Build the sentence: I come from Italy.", ["Ich", "komme", "aus", "Italien."], "Origin takes aus: aus Italien."),
    wo(288, "Build the sentence: I would like a coffee, please.", ["Ich", "möchte", "einen", "Kaffee,", "bitte."], "The modal is second; bitte closes the order."),
    wo(289, "Build the sentence: The train departs at ten o'clock.", ["Der", "Zug", "fährt", "um", "zehn", "Uhr", "ab."], "The separable prefix ab closes the sentence."),
    wo(290, "Build the sentence: We drove to Berlin yesterday.", ["Wir", "sind", "gestern", "nach", "Berlin", "gefahren."], "Movement takes sein; the participle closes."),
    wo(291, "Build the sentence: I watched a film yesterday.", ["Ich", "habe", "gestern", "einen", "Film", "gesehen."], "The participle gesehen closes the bracket."),
    wo(292, "Build the sentence: Can you help me?", ["Kannst", "du", "mir", "helfen?"], "The modal leads the question; helfen closes it."),
    wo(293, "Build the sentence: The apartment is on the third floor.", ["Die", "Wohnung", "ist", "im", "dritten", "Stock."], "The dative phrase im dritten Stock closes the sentence."),
    wo(294, "Build the sentence: I learn German because I live in Germany.", ["Ich", "lerne", "Deutsch,", "denn", "ich", "lebe", "in", "Deutschland."], "denn keeps the second verb in position two."),
    wo(295, "Build the sentence: On Monday I work.", ["Am", "Montag", "arbeite", "ich."], "The fronted time forces the inversion."),
    wo(296, "Build the sentence: I am buying a new computer.", ["Ich", "kaufe", "einen", "neuen", "Computer."], "The accusative object follows the verb."),
    wo(297, "Build the sentence: The book lies on the table.", ["Das", "Buch", "liegt", "auf", "dem", "Tisch."], "Static location takes the dative."),
    wo(298, "Build the sentence: I give the child an apple.", ["Ich", "gebe", "dem", "Kind", "einen", "Apfel."], "Dative receiver first, accusative thing second."),
    wo(299, "Build the sentence: I have to get up at seven.", ["Ich", "muss", "um", "sieben", "Uhr", "aufstehen."], "The separable infinitive closes the sentence."),
    wo(300, "Build the sentence: Today I am learning German.", ["Heute", "lerne", "ich", "Deutsch."], "The fronted time pushes the verb to second position."),
  ],
};