import type { Lesson } from "../../../schema";

/**
 * Goethe A1 practice exam: 100 questions, one per exercise card.
 * Ankommo-style formats: sentence-gap multiple choice ("Which word fits the
 * gap?"), article selection, typed fill-in-the-blank, translation practice,
 * and word order. Mirrors the real Goethe paper structure (Hören, Lesen,
 * Schreiben, Wortschatz, Sätze bauen).
 */
export const goethePracticeExam: Lesson = {
  id: "goethe-a1-practice-exam",
  title: "Goethe A1 Practice Exam (100 Fragen)",
  summary:
    "A very detailed Goethe-standard practice exam: 100 individual questions across listening, reading, writing, vocabulary, and sentence building.",
  status: "ready",
  sections: [
    {
      heading: "So ist die Prüfung aufgebaut",
      blocks: [
        {
          type: "paragraph",
          text: "This practice exam mirrors the real Goethe A1 paper, question by question. It contains 100 individual questions in five parts: Hören (listening), Lesen (reading), Schreiben (writing and grammar), Wortschatz (vocabulary), and Sätze bauen (sentence building). Each question is its own exercise, so you always know exactly how many you have done and how many remain. Work through it without notes, like the real exam, then review everything you missed.",
        },
        {
          type: "table",
          caption: "The five parts",
          head: ["Part", "Questions", "Format"],
          rows: [
            ["1. Hören", "1-25", "Play the audio, pick what you heard"],
            ["2. Wortwahl", "26-55", "Which word fits the gap?"],
            ["3. Artikel und Formen", "56-75", "Choose the correct article or verb form"],
            ["4. Schreiben", "76-90", "Type the missing word"],
            ["5. Wortschatz und Sätze", "91-100", "Translate and build sentences"],
          ],
        },
        {
          type: "tip",
          text: "The real Goethe A1 exam needs about 60 percent per part to pass. Aim for at least 60 percent in every part here too: 15 of 25 in listening, 18 of 30 in word choice, and so on.",
        },
      ],
    },
    {
      heading: "Teil 1: Hören (Fragen 1-25)",
      blocks: [
        {
          type: "paragraph",
          text: "In the listening part you hear short, slow sentences and pick what you heard. The exam topics are always the everyday ones: greetings, numbers, personal data, daily routine, and directions. Tap the play button, listen, and choose. Each question has a one-line explanation so a wrong answer teaches you as much as a right one.",
        },
        {
          type: "tip",
          text: "Listening strategy: read the three options before you press play. You are not listening for every word, only for the one detail that separates the options. The exam speaks slowly and twice in the real test, here you can replay as often as you like.",
        },
      ],
    },
    {
      heading: "Teil 2: Wortwahl (Fragen 26-55)",
      blocks: [
        {
          type: "paragraph",
          text: "The Ankommo-style gap question is the heart of the Goethe reading part: a real German sentence with one word missing, and you choose the word that fits. The sentence gives the context, the options are real German words, and only one completes the sentence naturally.",
        },
        {
          type: "tip",
          text: "Read the whole sentence before looking at the options. The missing word must fit the grammar of its sentence: einen Termin, die Apotheke, zur Arbeit. Grammar first, meaning second.",
        },
      ],
    },
    {
      heading: "Teil 3: Artikel und Formen (Fragen 56-75)",
      blocks: [
        {
          type: "paragraph",
          text: "This part checks the A1 grammar system in exam form: der, die, das and ein, eine; the accusative and dative articles; and the verb forms of regular, strong, and modal verbs. Every question is a mini rule test.",
        },
        {
          type: "tip",
          text: "For articles, ask the case question: subject (wer?) takes the nominative, direct object (wen?) the accusative, receiver (wem?) the dative. For verbs, identify the person first: ich, du, er. The person decides the ending.",
        },
      ],
    },
    {
      heading: "Teil 4: Schreiben (Fragen 76-90)",
      blocks: [
        {
          type: "paragraph",
          text: "The writing part of the real exam asks you to fill in forms and write short sentences. Here you type the missing word into real exam sentences. The first five questions are the form you fill on your first day in Germany: name, address, phone number, age.",
        },
        {
          type: "tip",
          text: "Typing without thinking: Nachname, Vorname, Adresse, Telefonnummer, Jahre alt. If you mistype an umlaut, try the ae/oe/ue spelling: the answer checker accepts both.",
        },
      ],
    },
    {
      heading: "Teil 5: Wortschatz und Sätze (Fragen 91-100)",
      blocks: [
        {
          type: "paragraph",
          text: "The last ten questions combine the two remaining exam skills: translating the vocabulary of life in Germany, and building sentences with correct word order. Every sentence here follows a rule you know: verb second, time before place, participle or prefix at the end.",
        },
        {
          type: "tip",
          text: "Build each sentence out loud first, then tap the words. Speaking forces your brain to use the word order instead of just recognizing it.",
        },
      ],
    },
  ],
  vocab: [
    { id: "die-pruefung", de: "die Prüfung", en: "the exam", part: "noun f.", plural: "die Prüfungen", audio: true },
    { id: "das-hoeren", de: "das Hören", en: "the listening (part)", part: "noun n.", audio: true },
    { id: "das-lesen", de: "das Lesen", en: "the reading (part)", part: "noun n.", audio: true },
    { id: "das-schreiben", de: "das Schreiben", en: "the writing (part)", part: "noun n.", audio: true },
    { id: "das-sprechen", de: "das Sprechen", en: "the speaking (part)", part: "noun n.", audio: true },
    { id: "der-termin", de: "der Termin", en: "the appointment", part: "noun m.", plural: "die Termine", audio: true },
    { id: "die-anmeldung", de: "die Anmeldung", en: "the registration", part: "noun f.", plural: "die Anmeldungen", audio: true },
    { id: "das-formular", de: "das Formular", en: "the form", part: "noun n.", plural: "die Formulare", audio: true },
    { id: "die-fahrkarte", de: "die Fahrkarte", en: "the ticket", part: "noun f.", plural: "die Fahrkarten", audio: true },
    { id: "die-oefnungszeiten", de: "die Öffnungszeiten", en: "the opening hours", part: "noun pl.", audio: true },
    { id: "der-eingang", de: "der Eingang", en: "the entrance", part: "noun m.", plural: "die Eingänge", audio: true },
    { id: "bestehen", de: "bestehen", en: "to pass (an exam)", part: "verb", audio: true },
  ],
  exercises: [
    {
      id: "f01-hoeren",
      type: "listening",
      title: "Frage 1: Hören",
      instruction: "Play the audio. Which greeting did you hear?",
      prompt: "Guten Morgen",
      options: ["Guten Morgen", "Guten Abend", "Gute Nacht"],
      correctIndex: 0,
      explain: "Guten Morgen is the morning greeting. You heard the morning greeting.",
    },
    {
      id: "f02-hoeren",
      type: "listening",
      title: "Frage 2: Hören",
      instruction: "Play the audio. Which leave-taking did you hear?",
      prompt: "Auf Wiedersehen",
      options: ["Auf Wiedersehen", "Bis bald", "Tschüss"],
      correctIndex: 0,
      explain: "Auf Wiedersehen is the formal goodbye. You heard the formal goodbye.",
    },
    {
      id: "f03-hoeren",
      type: "listening",
      title: "Frage 3: Hören",
      instruction: "Play the audio. Which question did you hear?",
      prompt: "Wie geht es dir?",
      options: ["Wie geht es dir?", "Wie geht es Ihnen?", "Wie heißen Sie?"],
      correctIndex: 0,
      explain: "The informal form asks dir. You heard the informal question.",
    },
    {
      id: "f04-hoeren",
      type: "listening",
      title: "Frage 4: Hören",
      instruction: "Play the audio. What did you hear about the person?",
      prompt: "Ich heiße Anna.",
      options: ["Ich heiße Anna.", "Ich komme aus Berlin.", "Ich bin Lehrer."],
      correctIndex: 0,
      explain: "The sentence names the person: Ich heiße Anna.",
    },
    {
      id: "f05-hoeren",
      type: "listening",
      title: "Frage 5: Hören",
      instruction: "Play the audio. Which country did you hear?",
      prompt: "Ich komme aus Italien.",
      options: ["Ich komme aus Italien.", "Ich komme aus Spanien.", "Ich komme aus Frankreich."],
      correctIndex: 0,
      explain: "Origin with aus: aus Italien.",
    },
    {
      id: "f06-hoeren",
      type: "listening",
      title: "Frage 6: Hören",
      instruction: "Play the audio. Which number did you hear?",
      prompt: "fünfundzwanzig",
      options: ["fünfundzwanzig", "fünfzehn", "fünfzig"],
      correctIndex: 0,
      explain: "25 is fünfundzwanzig: unit first, then und, then the ten.",
    },
    {
      id: "f07-hoeren",
      type: "listening",
      title: "Frage 7: Hören",
      instruction: "Play the audio. Which number did you hear?",
      prompt: "dreißig",
      options: ["dreißig", "dreizehn", "drei"],
      correctIndex: 0,
      explain: "30 is dreißig, written with ß.",
    },
    {
      id: "f08-hoeren",
      type: "listening",
      title: "Frage 8: Hören",
      instruction: "Play the audio. Which number did you hear?",
      prompt: "siebenundvierzig",
      options: ["siebenundvierzig", "vierundsiebzig", "vierzig"],
      correctIndex: 0,
      explain: "47 is siebenundvierzig: seven-and-forty.",
    },
    {
      id: "f09-hoeren",
      type: "listening",
      title: "Frage 9: Hören",
      instruction: "Play the audio. Which number did you hear?",
      prompt: "hundert",
      options: ["hundert", "hunderttausend", "eine Million"],
      correctIndex: 0,
      explain: "100 is hundert. You heard the hundred, not the million.",
    },
    {
      id: "f10-hoeren",
      type: "listening",
      title: "Frage 10: Hören",
      instruction: "Play the audio. Which price did you hear?",
      prompt: "zehn Euro neunzig",
      options: ["zehn Euro neunzig", "neun Euro zehn", "neunzehn Euro"],
      correctIndex: 0,
      explain: "10,90 is zehn neunzig: euros then cents in one breath.",
    },
    {
      id: "f11-hoeren",
      type: "listening",
      title: "Frage 11: Hören",
      instruction: "Play the audio. What is the person's name?",
      prompt: "Mein Name ist Anna Müller.",
      options: ["Mein Name ist Anna Müller.", "Mein Name ist Anna Maier.", "Mein Name ist Anna Schmidt."],
      correctIndex: 0,
      explain: "The last name heard is Müller.",
    },
    {
      id: "f12-hoeren",
      type: "listening",
      title: "Frage 12: Hören",
      instruction: "Play the audio. Which street did you hear?",
      prompt: "Ich wohne in der Hauptstraße 5.",
      options: ["Ich wohne in der Hauptstraße 5.", "Ich wohne in der Bahnhofstraße 5.", "Ich wohne in der Schulstraße 5."],
      correctIndex: 0,
      explain: "The street heard is the Hauptstraße.",
    },
    {
      id: "f13-hoeren",
      type: "listening",
      title: "Frage 13: Hören",
      instruction: "Play the audio. Which phone number did you hear?",
      prompt: "Meine Telefonnummer ist 0172 34 56 78.",
      options: ["Meine Telefonnummer ist 0172 34 56 78.", "Meine Telefonnummer ist 0173 34 56 78.", "Meine Telefonnummer ist 0174 34 56 78."],
      correctIndex: 0,
      explain: "The number starts with 0172.",
    },
    {
      id: "f14-hoeren",
      type: "listening",
      title: "Frage 14: Hören",
      instruction: "Play the audio. How old is the person?",
      prompt: "Ich bin 25 Jahre alt.",
      options: ["Ich bin 25 Jahre alt.", "Ich bin 35 Jahre alt.", "Ich bin 26 Jahre alt."],
      correctIndex: 0,
      explain: "The age heard is 25 years.",
    },
    {
      id: "f15-hoeren",
      type: "listening",
      title: "Frage 15: Hören",
      instruction: "Play the audio. How well does the person speak German?",
      prompt: "Ich spreche ein bisschen Deutsch.",
      options: ["Ich spreche ein bisschen Deutsch.", "Ich spreche gut Deutsch.", "Ich spreche kein Deutsch."],
      correctIndex: 0,
      explain: "The person speaks a little German: ein bisschen.",
    },
    {
      id: "f16-hoeren",
      type: "listening",
      title: "Frage 16: Hören",
      instruction: "Play the audio. When does the person get up?",
      prompt: "Ich stehe um sechs Uhr auf.",
      options: ["Ich stehe um sechs Uhr auf.", "Ich stehe um sieben Uhr auf.", "Ich stehe um acht Uhr auf."],
      correctIndex: 0,
      explain: "The time heard is six o'clock.",
    },
    {
      id: "f17-hoeren",
      type: "listening",
      title: "Frage 17: Hören",
      instruction: "Play the audio. When does the person have breakfast?",
      prompt: "Ich frühstücke um sieben Uhr.",
      options: ["Ich frühstücke um sieben Uhr.", "Ich frühstücke um acht Uhr.", "Ich frühstücke um neun Uhr."],
      correctIndex: 0,
      explain: "Breakfast is at seven o'clock.",
    },
    {
      id: "f18-hoeren",
      type: "listening",
      title: "Frage 18: Hören",
      instruction: "Play the audio. Which working hours did you hear?",
      prompt: "Ich arbeite von neun bis fünf.",
      options: ["Ich arbeite von neun bis fünf.", "Ich arbeite von acht bis vier.", "Ich arbeite von zehn bis sechs."],
      correctIndex: 0,
      explain: "The working hours are nine to five.",
    },
    {
      id: "f19-hoeren",
      type: "listening",
      title: "Frage 19: Hören",
      instruction: "Play the audio. When does the person watch TV?",
      prompt: "Am Abend sehe ich fern.",
      options: ["Am Abend sehe ich fern.", "Am Morgen sehe ich fern.", "Am Mittag sehe ich fern."],
      correctIndex: 0,
      explain: "The person watches TV in the evening: am Abend.",
    },
    {
      id: "f20-hoeren",
      type: "listening",
      title: "Frage 20: Hören",
      instruction: "Play the audio. When does the person go to bed?",
      prompt: "Ich schlafe um zehn Uhr.",
      options: ["Ich schlafe um zehn Uhr.", "Ich schlafe um elf Uhr.", "Ich schlafe um zwölf Uhr."],
      correctIndex: 0,
      explain: "The bedtime heard is ten o'clock.",
    },
    {
      id: "f21-hoeren",
      type: "listening",
      title: "Frage 21: Hören",
      instruction: "Play the audio. Which direction did you hear?",
      prompt: "Gehen Sie geradeaus.",
      options: ["Gehen Sie geradeaus.", "Gehen Sie links.", "Gehen Sie rechts."],
      correctIndex: 0,
      explain: "The direction heard is straight ahead.",
    },
    {
      id: "f22-hoeren",
      type: "listening",
      title: "Frage 22: Hören",
      instruction: "Play the audio. Which turn did you hear?",
      prompt: "An der Ampel links.",
      options: ["An der Ampel links.", "An der Ampel rechts.", "An der Ampel geradeaus."],
      correctIndex: 0,
      explain: "At the traffic light, turn left.",
    },
    {
      id: "f23-hoeren",
      type: "listening",
      title: "Frage 23: Hören",
      instruction: "Play the audio. Where is the pharmacy?",
      prompt: "Die Apotheke ist um die Ecke.",
      options: ["Die Apotheke ist um die Ecke.", "Die Apotheke ist gegenüber.", "Die Apotheke ist neben dem Kino."],
      correctIndex: 0,
      explain: "The pharmacy is around the corner.",
    },
    {
      id: "f24-hoeren",
      type: "listening",
      title: "Frage 24: Hören",
      instruction: "Play the audio. Where is the station?",
      prompt: "Der Bahnhof ist gegenüber der Bank.",
      options: ["Der Bahnhof ist gegenüber der Bank.", "Der Bahnhof ist neben der Bank.", "Der Bahnhof ist hinter der Bank."],
      correctIndex: 0,
      explain: "The station is opposite the bank.",
    },
    {
      id: "f25-hoeren",
      type: "listening",
      title: "Frage 25: Hören",
      instruction: "Play the audio. Which street did you hear?",
      prompt: "Die zweite Straße rechts.",
      options: ["Die zweite Straße rechts.", "Die erste Straße rechts.", "Die dritte Straße rechts."],
      correctIndex: 0,
      explain: "The second street on the right.",
    },
    {
      id: "f26-wortwahl",
      type: "multiple-choice",
      title: "Frage 26: Wortwahl",
      instruction: "Which word fits the gap? (I have an appointment at the citizen's office tomorrow.)",
      prompt: "Ich habe morgen einen ___ beim Bürgeramt.",
      options: ["Termin", "Formular", "Ausweis"],
      correctIndex: 0,
      explain: "The appointment is der Termin: einen Termin haben. The classic exam sentence.",
    },
    {
      id: "f27-wortwahl",
      type: "multiple-choice",
      title: "Frage 27: Wortwahl",
      instruction: "Which word fits the gap? (Please fill out this form.)",
      prompt: "Bitte füllen Sie dieses ___ aus.",
      options: ["Formular", "Termin", "Konto"],
      correctIndex: 0,
      explain: "The form is das Formular: ein Formular ausfüllen. ausfüllen is the verb for filling in forms.",
    },
    {
      id: "f28-wortwahl",
      type: "multiple-choice",
      title: "Frage 28: Wortwahl",
      instruction: "Which word fits the gap? (I need a ticket to Berlin.)",
      prompt: "Ich brauche eine Fahrkarte ___ Berlin.",
      options: ["nach", "in", "bei"],
      correctIndex: 0,
      explain: "Cities take nach: nach Berlin.",
    },
    {
      id: "f29-wortwahl",
      type: "multiple-choice",
      title: "Frage 29: Wortwahl",
      instruction: "Which word fits the gap? (The train departs at 2:30.)",
      prompt: "Der Zug fährt um 14:30 Uhr ___.",
      options: ["ab", "auf", "an"],
      correctIndex: 0,
      explain: "abfahren is separable: the prefix ab waits at the end.",
    },
    {
      id: "f30-wortwahl",
      type: "multiple-choice",
      title: "Frage 30: Wortwahl",
      instruction: "Which word fits the gap? (You have to change trains in Hamburg.)",
      prompt: "Sie müssen in Hamburg ___.",
      options: ["umsteigen", "anrufen", "aufstehen"],
      correctIndex: 0,
      explain: "Changing trains is umsteigen. You meet it in every timetable announcement.",
    },
    {
      id: "f31-wortwahl",
      type: "multiple-choice",
      title: "Frage 31: Wortwahl",
      instruction: "Which word fits the gap? (I am looking for pants in size 38.)",
      prompt: "Ich suche eine ___ in Größe 38.",
      options: ["Hose", "Hemd", "Schal"],
      correctIndex: 0,
      explain: "Pants are die Hose, feminine, so eine Hose.",
    },
    {
      id: "f32-wortwahl",
      type: "multiple-choice",
      title: "Frage 32: Wortwahl",
      instruction: "Which word fits the gap? (Can I try this on?)",
      prompt: "Kann ich das ___?",
      options: ["anprobieren", "anrufen", "aufstehen"],
      correctIndex: 0,
      explain: "Trying on clothes is anprobieren, a separable verb.",
    },
    {
      id: "f33-wortwahl",
      type: "multiple-choice",
      title: "Frage 33: Wortwahl",
      instruction: "Which word fits the gap? (The jacket is too expensive.)",
      prompt: "Die Jacke ist zu ___.",
      options: ["teuer", "billig", "frei"],
      correctIndex: 0,
      explain: "zu teuer means too expensive. The bargain-hunter word billig is the opposite.",
    },
    {
      id: "f34-wortwahl",
      type: "multiple-choice",
      title: "Frage 34: Wortwahl",
      instruction: "Which word fits the gap? (I would like my money back.)",
      prompt: "Ich möchte mein Geld ___.",
      options: ["zurück", "vor", "mit"],
      correctIndex: 0,
      explain: "Money back is das Geld zurück: zurück is the adverb at the end.",
    },
    {
      id: "f35-wortwahl",
      type: "multiple-choice",
      title: "Frage 35: Wortwahl",
      instruction: "Which word fits the gap? (The apartment has two rooms and a balcony.)",
      prompt: "Die Wohnung hat zwei ___ und einen Balkon.",
      options: ["Zimmer", "Stunden", "Straßen"],
      correctIndex: 0,
      explain: "Rooms are die Zimmer, plural unchanged: zwei Zimmer.",
    },
    {
      id: "f36-wortwahl",
      type: "multiple-choice",
      title: "Frage 36: Wortwahl",
      instruction: "Which word fits the gap? (The rent is 850 euros cold, plus utilities.)",
      prompt: "Die Miete ist 850 Euro ___.",
      options: ["kalt", "heiß", "warm"],
      correctIndex: 0,
      explain: "Kaltmiete means rent without utilities; zzgl. Nebenkosten follows in the ad.",
    },
    {
      id: "f37-wortwahl",
      type: "multiple-choice",
      title: "Frage 37: Wortwahl",
      instruction: "Which word fits the gap? (Excuse me, where is the pharmacy?)",
      prompt: "Entschuldigung, wo ist die ___?",
      options: ["Apotheke", "Bahnhof", "Park"],
      correctIndex: 0,
      explain: "The pharmacy is die Apotheke, feminine, so the question uses die.",
    },
    {
      id: "f38-wortwahl",
      type: "multiple-choice",
      title: "Frage 38: Wortwahl",
      instruction: "Which word fits the gap? (Go straight ahead and then left.)",
      prompt: "Gehen Sie ___ und dann links.",
      options: ["geradeaus", "rechts", "gegenüber"],
      correctIndex: 0,
      explain: "Straight ahead is geradeaus, the first word of every direction.",
    },
    {
      id: "f39-wortwahl",
      type: "multiple-choice",
      title: "Frage 39: Wortwahl",
      instruction: "Which word fits the gap? (I have a fever and a cough.)",
      prompt: "Ich habe ___ und Husten.",
      options: ["Fieber", "Jacke", "Termin"],
      correctIndex: 0,
      explain: "A fever is das Fieber: Ich habe Fieber. Husten is the cough.",
    },
    {
      id: "f40-wortwahl",
      type: "multiple-choice",
      title: "Frage 40: Wortwahl",
      instruction: "Which word fits the gap? (My head hurts.)",
      prompt: "Mir tut der ___ weh.",
      options: ["Kopf", "Handschuh", "Schuh"],
      correctIndex: 0,
      explain: "The head is der Kopf: Mir tut der Kopf weh. Note the dative mir.",
    },
    {
      id: "f41-wortwahl",
      type: "multiple-choice",
      title: "Frage 41: Wortwahl",
      instruction: "Which word fits the gap? (I am a teacher by profession.)",
      prompt: "Ich bin ___ von Beruf.",
      options: ["Lehrer", "Berlin", "Deutsch"],
      correctIndex: 0,
      explain: "Professions come without an article: Ich bin Lehrer.",
    },
    {
      id: "f42-wortwahl",
      type: "multiple-choice",
      title: "Frage 42: Wortwahl",
      instruction: "Which word fits the gap? (I learn German because I live in Germany.)",
      prompt: "Ich lerne Deutsch, ___ ich in Deutschland lebe.",
      options: ["denn", "oder", "aber"],
      correctIndex: 0,
      explain: "denn gives the reason and keeps the verb in position two.",
    },
    {
      id: "f43-wortwahl",
      type: "multiple-choice",
      title: "Frage 43: Wortwahl",
      instruction: "Which word fits the gap? (I have no car, but a bicycle.)",
      prompt: "Ich habe kein Auto, ___ ein Fahrrad.",
      options: ["sondern", "aber", "denn"],
      correctIndex: 0,
      explain: "After a negation, the alternative is sondern, not aber.",
    },
    {
      id: "f44-wortwahl",
      type: "multiple-choice",
      title: "Frage 44: Wortwahl",
      instruction: "Which word fits the gap? (Please fill in the form.)",
      prompt: "___ Sie bitte das Formular aus?",
      options: ["Füllen", "Füllt", "Füll"],
      correctIndex: 0,
      explain: "The polite imperative is the infinitive plus Sie: Füllen Sie.",
    },
    {
      id: "f45-wortwahl",
      type: "multiple-choice",
      title: "Frage 45: Wortwahl",
      instruction: "Which word fits the gap? (How much does that cost?)",
      prompt: "Wie ___ kostet das?",
      options: ["viel", "viele", "oft"],
      correctIndex: 0,
      explain: "Uncountable amounts take wie viel: Wie viel kostet das?",
    },
    {
      id: "f46-wortwahl",
      type: "multiple-choice",
      title: "Frage 46: Wortwahl",
      instruction: "Which word fits the gap? (The course starts at nine.)",
      prompt: "Der Kurs ___ um neun an.",
      options: ["fängt", "fangt", "fing"],
      correctIndex: 0,
      explain: "anfangen is separable with an umlaut: der Kurs fängt an.",
    },
    {
      id: "f47-wortwahl",
      type: "multiple-choice",
      title: "Frage 47: Wortwahl",
      instruction: "Which word fits the gap? (I am calling you this evening.)",
      prompt: "Ich ___ dich heute Abend an.",
      options: ["rufe", "rufst", "ruft"],
      correctIndex: 0,
      explain: "ich takes rufe: Ich rufe dich an.",
    },
    {
      id: "f48-wortwahl",
      type: "multiple-choice",
      title: "Frage 48: Wortwahl",
      instruction: "Which word fits the gap? (I ate pizza yesterday.)",
      prompt: "Ich habe gestern Pizza ___.",
      options: ["gegessen", "gespielt", "gekocht"],
      correctIndex: 0,
      explain: "Pizza is eaten, not played or cooked here: gegessen.",
    },
    {
      id: "f49-wortwahl",
      type: "multiple-choice",
      title: "Frage 49: Wortwahl",
      instruction: "Which word fits the gap? (We drove to Berlin yesterday.)",
      prompt: "Wir ___ gestern nach Berlin gefahren.",
      options: ["sind", "haben", "sein"],
      correctIndex: 0,
      explain: "Movement takes sein: Wir sind gefahren.",
    },
    {
      id: "f50-wortwahl",
      type: "multiple-choice",
      title: "Frage 50: Wortwahl",
      instruction: "Which word fits the gap? (I have no sister.)",
      prompt: "Ich habe ___ Schwester.",
      options: ["keine", "nicht", "kein"],
      correctIndex: 0,
      explain: "Schwester is feminine, so keine: Ich habe keine Schwester.",
    },
    {
      id: "f51-wortwahl",
      type: "multiple-choice",
      title: "Frage 51: Wortwahl",
      instruction: "Which word fits the gap? (I do not live in Berlin.)",
      prompt: "Ich wohne ___ in Berlin.",
      options: ["nicht", "keine", "kein"],
      correctIndex: 0,
      explain: "The place is negated with nicht: Ich wohne nicht in Berlin.",
    },
    {
      id: "f52-wortwahl",
      type: "multiple-choice",
      title: "Frage 52: Wortwahl",
      instruction: "Which word fits the gap? (That tastes good to me.)",
      prompt: "Das schmeckt ___.",
      options: ["mir", "mich", "ich"],
      correctIndex: 0,
      explain: "schmecken takes the dative: Das schmeckt mir.",
    },
    {
      id: "f53-wortwahl",
      type: "multiple-choice",
      title: "Frage 53: Wortwahl",
      instruction: "Which word fits the gap? (Can you help me?)",
      prompt: "Kannst du ___ helfen?",
      options: ["mir", "mich", "ich"],
      correctIndex: 0,
      explain: "helfen takes the dative: Kannst du mir helfen?",
    },
    {
      id: "f54-wortwahl",
      type: "multiple-choice",
      title: "Frage 54: Wortwahl",
      instruction: "Which word fits the gap? (I am going to the cinema.)",
      prompt: "Ich gehe ___ Kino.",
      options: ["ins", "im", "zum"],
      correctIndex: 0,
      explain: "Movement into a place: in das Kino contracts to ins Kino.",
    },
    {
      id: "f55-wortwahl",
      type: "multiple-choice",
      title: "Frage 55: Wortwahl",
      instruction: "Which word fits the gap? (The appointment is on Monday.)",
      prompt: "Der Termin ist ___ Montag.",
      options: ["am", "um", "im"],
      correctIndex: 0,
      explain: "Days take am: am Montag.",
    },
    {
      id: "f56-artikel",
      type: "multiple-choice",
      title: "Frage 56: Artikel",
      instruction: "Choose the correct article. (The man is reading a book.)",
      prompt: "___ Mann liest ein Buch.",
      options: ["Der", "Die", "Das"],
      correctIndex: 0,
      explain: "Mann is masculine: der Mann.",
    },
    {
      id: "f57-artikel",
      type: "multiple-choice",
      title: "Frage 57: Artikel",
      instruction: "Choose the correct article. (The woman works in an office.)",
      prompt: "___ Frau arbeitet im Büro.",
      options: ["Die", "Der", "Das"],
      correctIndex: 0,
      explain: "Frau is feminine: die Frau.",
    },
    {
      id: "f58-artikel",
      type: "multiple-choice",
      title: "Frage 58: Artikel",
      instruction: "Choose the correct article. (The child is sleeping.)",
      prompt: "___ Kind schläft.",
      options: ["Das", "Der", "Die"],
      correctIndex: 0,
      explain: "Kind is neuter: das Kind.",
    },
    {
      id: "f59-artikel",
      type: "multiple-choice",
      title: "Frage 59: Artikel",
      instruction: "Choose the correct article. (The children are playing in the park.)",
      prompt: "___ Kinder spielen im Park.",
      options: ["Die", "Der", "Das"],
      correctIndex: 0,
      explain: "The plural article is always die: die Kinder.",
    },
    {
      id: "f60-artikel",
      type: "multiple-choice",
      title: "Frage 60: Artikel",
      instruction: "Choose the correct article. (I am buying an apple.)",
      prompt: "Ich kaufe ___ Apfel.",
      options: ["einen", "ein", "eine"],
      correctIndex: 0,
      explain: "Apfel is masculine and the direct object: einen Apfel.",
    },
    {
      id: "f61-artikel",
      type: "multiple-choice",
      title: "Frage 61: Artikel",
      instruction: "Choose the correct article. (I need a clock.)",
      prompt: "Ich brauche ___ Uhr.",
      options: ["eine", "einen", "ein"],
      correctIndex: 0,
      explain: "Uhr is feminine: eine Uhr.",
    },
    {
      id: "f62-artikel",
      type: "multiple-choice",
      title: "Frage 62: Artikel",
      instruction: "Choose the correct article. (He has a brother.)",
      prompt: "Er hat ___ Bruder.",
      options: ["einen", "ein", "eine"],
      correctIndex: 0,
      explain: "Bruder is masculine, after haben accusative: einen Bruder.",
    },
    {
      id: "f63-artikel",
      type: "multiple-choice",
      title: "Frage 63: Artikel",
      instruction: "Choose the correct article. (I see the man.)",
      prompt: "Ich sehe ___ Mann.",
      options: ["den", "der", "dem"],
      correctIndex: 0,
      explain: "sehe takes the accusative: den Mann.",
    },
    {
      id: "f64-artikel",
      type: "multiple-choice",
      title: "Frage 64: Artikel",
      instruction: "Choose the correct article. (I give the child an apple.)",
      prompt: "Ich gebe ___ Kind einen Apfel.",
      options: ["dem", "den", "der"],
      correctIndex: 0,
      explain: "The receiver is dative, neuter: dem Kind.",
    },
    {
      id: "f65-artikel",
      type: "multiple-choice",
      title: "Frage 65: Artikel",
      instruction: "Choose the correct article. (The book lies on the table.)",
      prompt: "Das Buch liegt auf ___ Tisch.",
      options: ["dem", "den", "der"],
      correctIndex: 0,
      explain: "Static location takes the dative: auf dem Tisch.",
    },
    {
      id: "f66-verben",
      type: "multiple-choice",
      title: "Frage 66: Verbform",
      instruction: "Choose the correct verb form. (I learn German.)",
      prompt: "Ich ___ Deutsch.",
      options: ["lerne", "lernst", "lernt"],
      correctIndex: 0,
      explain: "ich takes -e: lerne.",
    },
    {
      id: "f67-verben",
      type: "multiple-choice",
      title: "Frage 67: Verbform",
      instruction: "Choose the correct verb form. (You learn English.)",
      prompt: "Du ___ Englisch.",
      options: ["lernst", "lerne", "lernt"],
      correctIndex: 0,
      explain: "du takes -st: lernst.",
    },
    {
      id: "f68-verben",
      type: "multiple-choice",
      title: "Frage 68: Verbform",
      instruction: "Choose the correct verb form. (He drives to Berlin.)",
      prompt: "Er ___ nach Berlin.",
      options: ["fährt", "fährst", "fahren"],
      correctIndex: 0,
      explain: "Strong verb, er takes fährt with the vowel change.",
    },
    {
      id: "f69-verben",
      type: "multiple-choice",
      title: "Frage 69: Verbform",
      instruction: "Choose the correct verb form. (We are tired.)",
      prompt: "Wir ___ müde.",
      options: ["sind", "seid", "ist"],
      correctIndex: 0,
      explain: "wir takes sind: Wir sind müde.",
    },
    {
      id: "f70-verben",
      type: "multiple-choice",
      title: "Frage 70: Verbform",
      instruction: "Choose the correct verb form. (She has a brother.)",
      prompt: "Sie ___ einen Bruder.",
      options: ["hat", "hast", "haben"],
      correctIndex: 0,
      explain: "sie (she) takes hat: Sie hat einen Bruder.",
    },
    {
      id: "f71-verben",
      type: "multiple-choice",
      title: "Frage 71: Verbform",
      instruction: "Choose the correct verb form. (I can swim well.)",
      prompt: "Ich ___ gut schwimmen.",
      options: ["kann", "kannst", "können"],
      correctIndex: 0,
      explain: "ich takes kann; the infinitive waits at the end.",
    },
    {
      id: "f72-verben",
      type: "multiple-choice",
      title: "Frage 72: Verbform",
      instruction: "Choose the correct verb form. (You should drink more water.)",
      prompt: "Du ___ mehr Wasser trinken.",
      options: ["sollst", "soll", "sollen"],
      correctIndex: 0,
      explain: "du takes sollst.",
    },
    {
      id: "f73-verben",
      type: "multiple-choice",
      title: "Frage 73: Verbform",
      instruction: "Choose the correct verb form. (I watched a film yesterday.)",
      prompt: "Ich habe gestern einen Film ___.",
      options: ["gesehen", "sehen", "sieht"],
      correctIndex: 0,
      explain: "The participle of sehen is gesehen.",
    },
    {
      id: "f74-verben",
      type: "multiple-choice",
      title: "Frage 74: Verbform",
      instruction: "Choose the correct verb form. (We drove to Berlin yesterday.)",
      prompt: "Wir ___ gestern nach Berlin gefahren.",
      options: ["sind", "haben", "habt"],
      correctIndex: 0,
      explain: "Movement takes sein: sind gefahren.",
    },
    {
      id: "f75-verben",
      type: "multiple-choice",
      title: "Frage 75: Verbform",
      instruction: "Choose the correct verb form. (Are you coming along?)",
      prompt: "Kommst du ___?",
      options: ["mit", "auf", "an"],
      correctIndex: 0,
      explain: "mitkommen splits: Kommst du mit?",
    },
    {
      id: "f76-schreiben",
      type: "fill-blank",
      title: "Frage 76: Schreiben",
      instruction: "Type the missing word. (My last name is Müller.)",
      sentence: "Mein ___ ist Müller.",
      blanks: [{ answers: ["Nachname"], hint: "last name" }],
    },
    {
      id: "f77-schreiben",
      type: "fill-blank",
      title: "Frage 77: Schreiben",
      instruction: "Type the missing word. (My first name is Anna.)",
      sentence: "Mein ___ ist Anna.",
      blanks: [{ answers: ["Vorname"], hint: "first name" }],
    },
    {
      id: "f78-schreiben",
      type: "fill-blank",
      title: "Frage 78: Schreiben",
      instruction: "Type the missing word. (I live on Hauptstraße 5.)",
      sentence: "Ich wohne in der ___ 5.",
      blanks: [{ answers: ["Hauptstraße"], hint: "the street" }],
    },
    {
      id: "f79-schreiben",
      type: "fill-blank",
      title: "Frage 79: Schreiben",
      instruction: "Type the missing word. (My phone number is 0172 34 56 78.)",
      sentence: "Meine ___ ist 0172 34 56 78.",
      blanks: [{ answers: ["Telefonnummer"], hint: "phone number" }],
    },
    {
      id: "f80-schreiben",
      type: "fill-blank",
      title: "Frage 80: Schreiben",
      instruction: "Type the missing word. (I am 25 years old.)",
      sentence: "Ich bin 25 ___ alt.",
      blanks: [{ answers: ["Jahre"], hint: "years" }],
    },
    {
      id: "f81-schreiben",
      type: "fill-blank",
      title: "Frage 81: Schreiben",
      instruction: "Type the missing verb. (I come from Italy.)",
      sentence: "Ich ___ aus Italien.",
      blanks: [{ answers: ["komme"], hint: "kommen, ich" }],
    },
    {
      id: "f82-schreiben",
      type: "fill-blank",
      title: "Frage 82: Schreiben",
      instruction: "Type the missing helper. (We drove to Berlin yesterday.)",
      sentence: "Wir ___ gestern nach Berlin gefahren.",
      blanks: [{ answers: ["sind"], hint: "movement takes sein" }],
    },
    {
      id: "f83-schreiben",
      type: "fill-blank",
      title: "Frage 83: Schreiben",
      instruction: "Type the missing participle. (I have watched a film.)",
      sentence: "Ich habe einen Film ___.",
      blanks: [{ answers: ["gesehen"], hint: "participle of sehen" }],
    },
    {
      id: "f84-schreiben",
      type: "fill-blank",
      title: "Frage 84: Schreiben",
      instruction: "Type the missing modal. (I can cook well.)",
      sentence: "Ich ___ gut kochen.",
      blanks: [{ answers: ["kann"], hint: "ability, ich" }],
    },
    {
      id: "f85-schreiben",
      type: "fill-blank",
      title: "Frage 85: Schreiben",
      instruction: "Type the missing modal. (You should drink more water.)",
      sentence: "Du ___ mehr Wasser trinken.",
      blanks: [{ answers: ["sollst"], hint: "should, du" }],
    },
    {
      id: "f86-schreiben",
      type: "fill-blank",
      title: "Frage 86: Schreiben",
      instruction: "Type the missing verb. (I have to get up at seven.)",
      sentence: "Ich muss um sieben Uhr ___.",
      blanks: [{ answers: ["aufstehen"], hint: "separable infinitive" }],
    },
    {
      id: "f87-schreiben",
      type: "fill-blank",
      title: "Frage 87: Schreiben",
      instruction: "Type the missing preposition. (The appointment is on Monday.)",
      sentence: "Der Termin ist ___ Montag.",
      blanks: [{ answers: ["am"], hint: "day of the week" }],
    },
    {
      id: "f88-schreiben",
      type: "fill-blank",
      title: "Frage 88: Schreiben",
      instruction: "Type the missing preposition. (I drive to Berlin.)",
      sentence: "Ich fahre ___ Berlin.",
      blanks: [{ answers: ["nach"], hint: "city without article" }],
    },
    {
      id: "f89-schreiben",
      type: "fill-blank",
      title: "Frage 89: Schreiben",
      instruction: "Type the missing negation. (I have no car.)",
      sentence: "Ich habe ___ Auto.",
      blanks: [{ answers: ["kein"], hint: "neuter noun" }],
    },
    {
      id: "f90-schreiben",
      type: "fill-blank",
      title: "Frage 90: Schreiben",
      instruction: "Type the missing conjunction. (I learn German because I live in Germany.)",
      sentence: "Ich lerne Deutsch, ___ ich in Deutschland lebe.",
      blanks: [{ answers: ["denn"], hint: "reason, verb stays second" }],
    },
    {
      id: "f91-uebersetzung",
      type: "multiple-choice",
      title: "Frage 91: Übersetzung",
      instruction: "What does this word mean?",
      prompt: "die Anmeldung",
      options: ["the registration", "the appointment", "the form"],
      correctIndex: 0,
      explain: "die Anmeldung is the registration, your first task in Germany.",
    },
    {
      id: "f92-uebersetzung",
      type: "multiple-choice",
      title: "Frage 92: Übersetzung",
      instruction: "What does this word mean?",
      prompt: "der Termin",
      options: ["the appointment", "the ticket", "the rent"],
      correctIndex: 0,
      explain: "der Termin is the appointment. Remember: einen Termin machen.",
    },
    {
      id: "f93-uebersetzung",
      type: "multiple-choice",
      title: "Frage 93: Übersetzung",
      instruction: "What does this word mean?",
      prompt: "die Fahrkarte",
      options: ["the ticket", "the key", "the street"],
      correctIndex: 0,
      explain: "die Fahrkarte is the ticket for trains and buses.",
    },
    {
      id: "f94-uebersetzung",
      type: "multiple-choice",
      title: "Frage 94: Übersetzung",
      instruction: "What does this word mean?",
      prompt: "die Öffnungszeiten",
      options: ["the opening hours", "the working day", "the office"],
      correctIndex: 0,
      explain: "die Öffnungszeiten are the opening hours, on every shop door.",
    },
    {
      id: "f95-uebersetzung",
      type: "multiple-choice",
      title: "Frage 95: Übersetzung",
      instruction: "What does this word mean?",
      prompt: "gegessen",
      options: ["eaten", "drunk", "seen"],
      correctIndex: 0,
      explain: "gegessen is the participle of essen: eaten.",
    },
    {
      id: "f96-satz",
      type: "word-order",
      title: "Frage 96: Satz bauen",
      instruction: "Build the sentence: My name is Anna.",
      chunks: ["Ich", "heiße", "Anna."],
      explain: "The verb heiße stays in second position.",
    },
    {
      id: "f97-satz",
      type: "word-order",
      title: "Frage 97: Satz bauen",
      instruction: "Build the sentence: I come from Italy.",
      chunks: ["Ich", "komme", "aus", "Italien."],
      explain: "Origin takes aus: aus Italien.",
    },
    {
      id: "f98-satz",
      type: "word-order",
      title: "Frage 98: Satz bauen",
      instruction: "Build the sentence: I would like a coffee, please.",
      chunks: ["Ich", "möchte", "einen", "Kaffee,", "bitte."],
      explain: "The modal is second; bitte closes the order.",
    },
    {
      id: "f99-satz",
      type: "word-order",
      title: "Frage 99: Satz bauen",
      instruction: "Build the sentence: The train departs at ten o'clock.",
      chunks: ["Der", "Zug", "fährt", "um", "zehn", "Uhr", "ab."],
      explain: "The separable prefix ab closes the sentence.",
    },
    {
      id: "f100-satz",
      type: "word-order",
      title: "Frage 100: Satz bauen",
      instruction: "Build the sentence: We drove to Berlin yesterday.",
      chunks: ["Wir", "sind", "gestern", "nach", "Berlin", "gefahren."],
      explain: "Movement takes sein; the participle closes.",
    },
  ],
};