import type { Game } from "./schema";

export const caseDetectiveGame: Game = {
  id: "case-detective",
  title: "Case Detective",
  emoji: "🕵️",
  description:
    "Spot the case: nominative, accusative, or dative? Be the grammar detective.",
  category: "grammar",
  tags: ["A1", "A2"],
  levels: [
    {
      id: "case-detective-1",
      title: "Level 1: Nominativ or Akkusativ?",
      rounds: [
        {
          kind: "exercise",
          exercise: {
            id: "cd-001",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Der Mann schläft. (the man)",
            options: ["Nominativ","Akkusativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The man is the subject doing the sleeping: nominative.",
            explainWrong: "The man is the subject doing the sleeping: nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-002",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Die Frau arbeitet. (the woman)",
            options: ["Nominativ","Akkusativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The woman is the subject: nominative.",
            explainWrong: "The woman is the subject: nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-003",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Das Kind spielt. (the child)",
            options: ["Nominativ","Akkusativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The child is the subject: nominative.",
            explainWrong: "The child is the subject: nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-004",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Der Hund bellt. (the dog)",
            options: ["Nominativ","Akkusativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The dog is the subject barking: nominative.",
            explainWrong: "The dog is the subject barking: nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-005",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Die Katze schläft. (the cat)",
            options: ["Nominativ","Akkusativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The cat is the subject: nominative.",
            explainWrong: "The cat is the subject: nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-006",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Die Kinder lernen Deutsch. (the children)",
            options: ["Nominativ","Akkusativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The children are the subject: nominative.",
            explainWrong: "The children are the subject: nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-007",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Der Lehrer erklärt die Grammatik. (the teacher)",
            options: ["Nominativ","Akkusativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The teacher is the subject: nominative.",
            explainWrong: "The teacher is the subject: nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-008",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Die Ärztin arbeitet im Krankenhaus. (the doctor)",
            options: ["Nominativ","Akkusativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The doctor is the subject: nominative.",
            explainWrong: "The doctor is the subject: nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-009",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Der Kellner bringt das Essen. (the waiter)",
            options: ["Nominativ","Akkusativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The waiter is the subject: nominative.",
            explainWrong: "The waiter is the subject: nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-010",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Das Mädchen singt ein Lied. (the girl)",
            options: ["Nominativ","Akkusativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The girl is the subject: nominative.",
            explainWrong: "The girl is the subject: nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-011",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Der Vater kocht das Abendessen. (the father)",
            options: ["Nominativ","Akkusativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The father is the subject: nominative.",
            explainWrong: "The father is the subject: nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-012",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Die Mutter liest eine Zeitung. (the mother)",
            options: ["Nominativ","Akkusativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The mother is the subject: nominative.",
            explainWrong: "The mother is the subject: nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-013",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Der Bruder fährt Fahrrad. (the brother)",
            options: ["Nominativ","Akkusativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The brother is the subject: nominative.",
            explainWrong: "The brother is the subject: nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-014",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Die Schwester tanzt gern. (the sister)",
            options: ["Nominativ","Akkusativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The sister is the subject: nominative.",
            explainWrong: "The sister is the subject: nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-015",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Der Student lernt für die Prüfung. (the student)",
            options: ["Nominativ","Akkusativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The student is the subject: nominative.",
            explainWrong: "The student is the subject: nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-016",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Die Oma backt einen Kuchen. (the grandma)",
            options: ["Nominativ","Akkusativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The grandma is the subject: nominative.",
            explainWrong: "The grandma is the subject: nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-017",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Der Opa geht spazieren. (the grandpa)",
            options: ["Nominativ","Akkusativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The grandpa is the subject: nominative.",
            explainWrong: "The grandpa is the subject: nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-018",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Der Nachbar repariert das Auto. (the neighbor)",
            options: ["Nominativ","Akkusativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The neighbor is the subject: nominative.",
            explainWrong: "The neighbor is the subject: nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-019",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Die Lehrerin korrigiert die Hausaufgaben. (the teacher)",
            options: ["Nominativ","Akkusativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The teacher is the subject: nominative.",
            explainWrong: "The teacher is the subject: nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-020",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Der Bus fährt nach Berlin. (the bus)",
            options: ["Nominativ","Akkusativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The bus is the subject: nominative.",
            explainWrong: "The bus is the subject: nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-021",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Der Zug kommt um zwölf Uhr an. (the train)",
            options: ["Nominativ","Akkusativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The train is the subject: nominative.",
            explainWrong: "The train is the subject: nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-022",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Die Sonne scheint. (the sun)",
            options: ["Nominativ","Akkusativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The sun is the subject: nominative.",
            explainWrong: "The sun is the subject: nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-023",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Der Regen fällt. (the rain)",
            options: ["Nominativ","Akkusativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The rain is the subject: nominative.",
            explainWrong: "The rain is the subject: nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-024",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Das Wetter ist schön. (the weather)",
            options: ["Nominativ","Akkusativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The weather is the subject: nominative.",
            explainWrong: "The weather is the subject: nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-025",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Die Blumen blühen im Garten. (the flowers)",
            options: ["Nominativ","Akkusativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The flowers are the subject: nominative.",
            explainWrong: "The flowers are the subject: nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-026",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich sehe den Mann. (the man)",
            options: ["Akkusativ","Nominativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The man is the direct object of sehen: accusative (den).",
            explainWrong: "The man is the direct object of sehen: accusative (den).",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-027",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Wir kaufen einen Apfel. (an apple)",
            options: ["Akkusativ","Nominativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The apple is what is bought: accusative (einen).",
            explainWrong: "The apple is what is bought: accusative (einen).",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-028",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Sie liest das Buch. (the book)",
            options: ["Akkusativ","Nominativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The book is the direct object of lesen: accusative.",
            explainWrong: "The book is the direct object of lesen: accusative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-029",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich trinke den Kaffee. (the coffee)",
            options: ["Akkusativ","Nominativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The coffee is what is drunk: accusative (den).",
            explainWrong: "The coffee is what is drunk: accusative (den).",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-030",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Er öffnet die Tür. (the door)",
            options: ["Akkusativ","Nominativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The door is what is opened: accusative.",
            explainWrong: "The door is what is opened: accusative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-031",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich kenne die Frau. (the woman)",
            options: ["Akkusativ","Nominativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The woman is the direct object of kennen: accusative.",
            explainWrong: "The woman is the direct object of kennen: accusative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-032",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Er hat einen Bruder. (a brother)",
            options: ["Akkusativ","Nominativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The brother is the direct object of haben: accusative (einen).",
            explainWrong: "The brother is the direct object of haben: accusative (einen).",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-033",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Wir besuchen die Oma. (the grandma)",
            options: ["Akkusativ","Nominativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The grandma is the direct object of besuchen: accusative.",
            explainWrong: "The grandma is the direct object of besuchen: accusative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-034",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Sie liebt den Hund. (the dog)",
            options: ["Akkusativ","Nominativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The dog is the direct object of lieben: accusative (den).",
            explainWrong: "The dog is the direct object of lieben: accusative (den).",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-035",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich mag den Kaffee. (the coffee)",
            options: ["Akkusativ","Nominativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The coffee is the direct object of mögen: accusative (den).",
            explainWrong: "The coffee is the direct object of mögen: accusative (den).",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-036",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Wir sehen einen Film. (a film)",
            options: ["Akkusativ","Nominativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The film is the direct object of sehen: accusative (einen).",
            explainWrong: "The film is the direct object of sehen: accusative (einen).",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-037",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Er braucht den Computer. (the computer)",
            options: ["Akkusativ","Nominativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The computer is the direct object of brauchen: accusative (den).",
            explainWrong: "The computer is the direct object of brauchen: accusative (den).",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-038",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich finde den Schlüssel. (the key)",
            options: ["Akkusativ","Nominativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The key is the direct object of finden: accusative (den).",
            explainWrong: "The key is the direct object of finden: accusative (den).",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-039",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Sie kauft ein Kleid. (a dress)",
            options: ["Akkusativ","Nominativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The dress is the direct object of kaufen: accusative (ein).",
            explainWrong: "The dress is the direct object of kaufen: accusative (ein).",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-040",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Er trägt einen Mantel. (a coat)",
            options: ["Akkusativ","Nominativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The coat is the direct object of tragen: accusative (einen).",
            explainWrong: "The coat is the direct object of tragen: accusative (einen).",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-041",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich höre die Musik. (the music)",
            options: ["Akkusativ","Nominativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The music is the direct object of hören: accusative.",
            explainWrong: "The music is the direct object of hören: accusative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-042",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Wir lernen das Alphabet. (the alphabet)",
            options: ["Akkusativ","Nominativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The alphabet is the direct object of lernen: accusative.",
            explainWrong: "The alphabet is the direct object of lernen: accusative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-043",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Sie macht die Hausaufgaben. (the homework)",
            options: ["Akkusativ","Nominativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The homework is the direct object of machen: accusative.",
            explainWrong: "The homework is the direct object of machen: accusative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-044",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Er schreibt einen Brief. (a letter)",
            options: ["Akkusativ","Nominativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The letter is the direct object of schreiben: accusative (einen).",
            explainWrong: "The letter is the direct object of schreiben: accusative (einen).",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-045",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich bestelle einen Kaffee. (a coffee)",
            options: ["Akkusativ","Nominativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The coffee is the direct object of bestellen: accusative (einen).",
            explainWrong: "The coffee is the direct object of bestellen: accusative (einen).",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-046",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Wir suchen den Bahnhof. (the station)",
            options: ["Akkusativ","Nominativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The station is the direct object of suchen: accusative (den).",
            explainWrong: "The station is the direct object of suchen: accusative (den).",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-047",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Sie versteht die Frage. (the question)",
            options: ["Akkusativ","Nominativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The question is the direct object of verstehen: accusative.",
            explainWrong: "The question is the direct object of verstehen: accusative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-048",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Er nimmt das Taxi. (the taxi)",
            options: ["Akkusativ","Nominativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The taxi is the direct object of nehmen: accusative.",
            explainWrong: "The taxi is the direct object of nehmen: accusative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-049",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich vergesse den Namen. (the name)",
            options: ["Akkusativ","Nominativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The name is the direct object of vergessen: accusative (den).",
            explainWrong: "The name is the direct object of vergessen: accusative (den).",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-050",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Wir trinken den Tee. (the tea)",
            options: ["Akkusativ","Nominativ","Dativ"],
            correctIndex: 0,
            explainCorrect: "The tea is what is drunk: accusative (den).",
            explainWrong: "The tea is what is drunk: accusative (den).",
          },
        },
      ],
    },
    {
      id: "case-detective-2",
      title: "Level 2: Dativ spotter",
      rounds: [
        {
          kind: "exercise",
          exercise: {
            id: "cd-051",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich helfe dem Mann. (the man)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "helfen always takes the dative: dem Mann.",
            explainWrong: "helfen always takes the dative: dem Mann.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-052",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Wir danken der Frau. (the woman)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "danken takes the dative: der Frau.",
            explainWrong: "danken takes the dative: der Frau.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-053",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Das schmeckt mir gut. (to me)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "schmecken takes the dative: mir.",
            explainWrong: "schmecken takes the dative: mir.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-054",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich gebe dem Kind einen Apfel. (the child)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "The receiver of geben is dative: dem Kind.",
            explainWrong: "The receiver of geben is dative: dem Kind.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-055",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Das gefällt ihm. (to him)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "gefallen takes the dative: ihm.",
            explainWrong: "gefallen takes the dative: ihm.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-056",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Sie antwortet dem Lehrer. (the teacher)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "antworten takes the dative: dem Lehrer.",
            explainWrong: "antworten takes the dative: dem Lehrer.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-057",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich glaube dir. (to you)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "glauben takes the dative: dir.",
            explainWrong: "glauben takes the dative: dir.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-058",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Das Buch gehört mir. (to me)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "gehören takes the dative: mir.",
            explainWrong: "gehören takes the dative: mir.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-059",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Er hilft seiner Mutter. (his mother)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "helfen takes the dative: seiner Mutter.",
            explainWrong: "helfen takes the dative: seiner Mutter.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-060",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich wünsche dir alles Gute. (to you)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "wünschen takes the dative for the person: dir.",
            explainWrong: "wünschen takes the dative for the person: dir.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-061",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Das fehlt mir. (to me)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "fehlen takes the dative: mir.",
            explainWrong: "fehlen takes the dative: mir.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-062",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Wir folgen dem Bus. (the bus)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "folgen takes the dative: dem Bus.",
            explainWrong: "folgen takes the dative: dem Bus.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-063",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich gratuliere der Freundin. (the friend)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "gratulieren takes the dative: der Freundin.",
            explainWrong: "gratulieren takes the dative: der Freundin.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-064",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Die Hose passt mir. (to me)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "passen takes the dative: mir.",
            explainWrong: "passen takes the dative: mir.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-065",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Das schmeckt dem Kind nicht. (the child)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "schmecken takes the dative: dem Kind.",
            explainWrong: "schmecken takes the dative: dem Kind.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-066",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Er dankt dem Arzt. (the doctor)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "danken takes the dative: dem Arzt.",
            explainWrong: "danken takes the dative: dem Arzt.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-067",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Wir helfen der Lehrerin. (the teacher)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "helfen takes the dative: der Lehrerin.",
            explainWrong: "helfen takes the dative: der Lehrerin.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-068",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Sie antwortet dem Kunden. (the customer)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "antworten takes the dative: dem Kunden.",
            explainWrong: "antworten takes the dative: dem Kunden.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-069",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich gebe dem Kellner ein Trinkgeld. (the waiter)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "The receiver of geben is dative: dem Kellner.",
            explainWrong: "The receiver of geben is dative: dem Kellner.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-070",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Das gefällt der Oma. (the grandma)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "gefallen takes the dative: der Oma.",
            explainWrong: "gefallen takes the dative: der Oma.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-071",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Er hilft dem Nachbarn. (the neighbor)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "helfen takes the dative: dem Nachbarn.",
            explainWrong: "helfen takes the dative: dem Nachbarn.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-072",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Wir danken dem Fahrer. (the driver)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "danken takes the dative: dem Fahrer.",
            explainWrong: "danken takes the dative: dem Fahrer.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-073",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Das Buch gehört dem Mädchen. (the girl)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "gehören takes the dative: dem Mädchen.",
            explainWrong: "gehören takes the dative: dem Mädchen.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-074",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich wünsche dem Bruder viel Glück. (the brother)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "wünschen takes the dative: dem Bruder.",
            explainWrong: "wünschen takes the dative: dem Bruder.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-075",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Das fehlt der Familie. (the family)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "fehlen takes the dative: der Familie.",
            explainWrong: "fehlen takes the dative: der Familie.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-076",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Wir folgen dem Weg. (the path)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "folgen takes the dative: dem Weg.",
            explainWrong: "folgen takes the dative: dem Weg.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-077",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Er gratuliert dem Chef. (the boss)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "gratulieren takes the dative: dem Chef.",
            explainWrong: "gratulieren takes the dative: dem Chef.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-078",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Die Schuhe passen dem Vater. (the father)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "passen takes the dative: dem Vater.",
            explainWrong: "passen takes the dative: dem Vater.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-079",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Das schmeckt dem Kind. (the child)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "schmecken takes the dative: dem Kind.",
            explainWrong: "schmecken takes the dative: dem Kind.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-080",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich antworte dem Kunden. (the customer)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "antworten takes the dative: dem Kunden.",
            explainWrong: "antworten takes the dative: dem Kunden.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-081",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Wir helfen dem Opa. (the grandpa)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "helfen takes the dative: dem Opa.",
            explainWrong: "helfen takes the dative: dem Opa.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-082",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Sie dankt der Schwester. (the sister)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "danken takes the dative: der Schwester.",
            explainWrong: "danken takes the dative: der Schwester.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-083",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Das gefällt dem Kind. (the child)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "gefallen takes the dative: dem Kind.",
            explainWrong: "gefallen takes the dative: dem Kind.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-084",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich gebe der Katze Milch. (the cat)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "The receiver of geben is dative: der Katze.",
            explainWrong: "The receiver of geben is dative: der Katze.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-085",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Er hilft dem Freund. (the friend)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "helfen takes the dative: dem Freund.",
            explainWrong: "helfen takes the dative: dem Freund.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-086",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Wir wünschen der Oma alles Gute. (the grandma)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "wünschen takes the dative: der Oma.",
            explainWrong: "wünschen takes the dative: der Oma.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-087",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Das gehört der Mutter. (the mother)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "gehören takes the dative: der Mutter.",
            explainWrong: "gehören takes the dative: der Mutter.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-088",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich glaube dem Arzt. (the doctor)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "glauben takes the dative: dem Arzt.",
            explainWrong: "glauben takes the dative: dem Arzt.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-089",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Sie folgt dem Taxi. (the taxi)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "folgen takes the dative: dem Taxi.",
            explainWrong: "folgen takes the dative: dem Taxi.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-090",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Er antwortet dem Lehrer. (the teacher)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "antworten takes the dative: dem Lehrer.",
            explainWrong: "antworten takes the dative: dem Lehrer.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-091",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich danke dem Kollegen. (the colleague)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "danken takes the dative: dem Kollegen.",
            explainWrong: "danken takes the dative: dem Kollegen.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-092",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Wir geben der Tochter ein Geschenk. (the daughter)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "The receiver of geben is dative: der Tochter.",
            explainWrong: "The receiver of geben is dative: der Tochter.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-093",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Das schmeckt dem Mann nicht. (the man)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "schmecken takes the dative: dem Mann.",
            explainWrong: "schmecken takes the dative: dem Mann.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-094",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Er hilft der Ärztin. (the doctor)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "helfen takes the dative: der Ärztin.",
            explainWrong: "helfen takes the dative: der Ärztin.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-095",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich wünsche dem Lehrer einen guten Tag. (the teacher)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "wünschen takes the dative: dem Lehrer.",
            explainWrong: "wünschen takes the dative: dem Lehrer.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-096",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Das gehört dem Nachbarn. (the neighbor)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "gehören takes the dative: dem Nachbarn.",
            explainWrong: "gehören takes the dative: dem Nachbarn.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-097",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Wir gratulieren den Eltern. (the parents)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "gratulieren takes the dative: den Eltern.",
            explainWrong: "gratulieren takes the dative: den Eltern.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-098",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Sie hilft dem Studenten. (the student)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "helfen takes the dative: dem Studenten.",
            explainWrong: "helfen takes the dative: dem Studenten.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-099",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich bringe dem Kellner die Tasse. (the waiter)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "The receiver of bringen is dative: dem Kellner.",
            explainWrong: "The receiver of bringen is dative: dem Kellner.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-100",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Das gefällt den Kindern. (the children)",
            options: ["Dativ","Akkusativ","Nominativ"],
            correctIndex: 0,
            explainCorrect: "gefallen takes the dative: den Kindern.",
            explainWrong: "gefallen takes the dative: den Kindern.",
          },
        },
      ],
    },
    {
      id: "case-detective-3",
      title: "Level 3: Choose the form",
      rounds: [
        {
          kind: "exercise",
          exercise: {
            id: "cd-101",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich sehe ___ Mann.",
            options: ["den","dem","der"],
            correctIndex: 0,
            explainCorrect: "sehen takes the accusative: den Mann.",
            explainWrong: "sehen takes the accusative: den Mann.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-102",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich gebe ___ Kind einen Apfel.",
            options: ["dem","den","der"],
            correctIndex: 0,
            explainCorrect: "The receiver of geben is dative: dem Kind.",
            explainWrong: "The receiver of geben is dative: dem Kind.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-103",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich danke ___ Frau.",
            options: ["der","die","den"],
            correctIndex: 0,
            explainCorrect: "danken takes the dative: der Frau.",
            explainWrong: "danken takes the dative: der Frau.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-104",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Sie hat ___ Bruder.",
            options: ["einen","einem","ein"],
            correctIndex: 0,
            explainCorrect: "haben takes the accusative: einen Bruder.",
            explainWrong: "haben takes the accusative: einen Bruder.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-105",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Wir besuchen ___ Oma.",
            options: ["die","der","den"],
            correctIndex: 0,
            explainCorrect: "besuchen takes the accusative; feminine stays die.",
            explainWrong: "besuchen takes the accusative; feminine stays die.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-106",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Er kauft ___ Auto.",
            options: ["ein","einen","einem"],
            correctIndex: 0,
            explainCorrect: "kaufen takes the accusative; neuter stays ein.",
            explainWrong: "kaufen takes the accusative; neuter stays ein.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-107",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich helfe ___ Freund.",
            options: ["einem","einen","ein"],
            correctIndex: 0,
            explainCorrect: "helfen takes the dative: einem Freund.",
            explainWrong: "helfen takes the dative: einem Freund.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-108",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Das schmeckt ___ Mann gut.",
            options: ["dem","den","der"],
            correctIndex: 0,
            explainCorrect: "schmecken takes the dative: dem Mann.",
            explainWrong: "schmecken takes the dative: dem Mann.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-109",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Sie sieht ___ Film.",
            options: ["einen","einem","ein"],
            correctIndex: 0,
            explainCorrect: "sehen takes the accusative: einen Film.",
            explainWrong: "sehen takes the accusative: einen Film.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-110",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Wir antworten ___ Lehrerin.",
            options: ["der","die","dem"],
            correctIndex: 0,
            explainCorrect: "antworten takes the dative: der Lehrerin.",
            explainWrong: "antworten takes the dative: der Lehrerin.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-111",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich liebe ___ Hund.",
            options: ["den","dem","der"],
            correctIndex: 0,
            explainCorrect: "lieben takes the accusative: den Hund.",
            explainWrong: "lieben takes the accusative: den Hund.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-112",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Er gibt ___ Schwester ein Geschenk.",
            options: ["der","die","dem"],
            correctIndex: 0,
            explainCorrect: "The receiver of geben is dative: der Schwester.",
            explainWrong: "The receiver of geben is dative: der Schwester.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-113",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich kenne ___ Lehrer.",
            options: ["den","dem","der"],
            correctIndex: 0,
            explainCorrect: "kennen takes the accusative: den Lehrer.",
            explainWrong: "kennen takes the accusative: den Lehrer.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-114",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Wir danken ___ Arzt.",
            options: ["dem","den","der"],
            correctIndex: 0,
            explainCorrect: "danken takes the dative: dem Arzt.",
            explainWrong: "danken takes the dative: dem Arzt.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-115",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Sie braucht ___ Computer.",
            options: ["den","dem","der"],
            correctIndex: 0,
            explainCorrect: "brauchen takes the accusative: den Computer.",
            explainWrong: "brauchen takes the accusative: den Computer.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-116",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Er sucht ___ Schlüssel.",
            options: ["den","dem","der"],
            correctIndex: 0,
            explainCorrect: "suchen takes the accusative: den Schlüssel.",
            explainWrong: "suchen takes the accusative: den Schlüssel.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-117",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich mag ___ Musik.",
            options: ["die","der","den"],
            correctIndex: 0,
            explainCorrect: "mögen takes the accusative; feminine stays die.",
            explainWrong: "mögen takes the accusative; feminine stays die.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-118",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Wir lesen ___ Zeitung.",
            options: ["die","der","den"],
            correctIndex: 0,
            explainCorrect: "lesen takes the accusative; feminine stays die.",
            explainWrong: "lesen takes the accusative; feminine stays die.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-119",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Sie hat ___ Katze.",
            options: ["eine","einer","ein"],
            correctIndex: 0,
            explainCorrect: "haben takes the accusative: eine Katze.",
            explainWrong: "haben takes the accusative: eine Katze.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-120",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Er kauft ___ Jacke.",
            options: ["eine","einer","ein"],
            correctIndex: 0,
            explainCorrect: "kaufen takes the accusative: eine Jacke.",
            explainWrong: "kaufen takes the accusative: eine Jacke.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-121",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich bringe ___ Kind ein Geschenk.",
            options: ["dem","den","der"],
            correctIndex: 0,
            explainCorrect: "The receiver of bringen is dative: dem Kind.",
            explainWrong: "The receiver of bringen is dative: dem Kind.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-122",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Wir helfen ___ Studenten.",
            options: ["dem","den","der"],
            correctIndex: 0,
            explainCorrect: "helfen takes the dative: dem Studenten.",
            explainWrong: "helfen takes the dative: dem Studenten.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-123",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Sie antwortet ___ Chef.",
            options: ["dem","den","der"],
            correctIndex: 0,
            explainCorrect: "antworten takes the dative: dem Chef.",
            explainWrong: "antworten takes the dative: dem Chef.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-124",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Er gibt ___ Mutter einen Kuss.",
            options: ["der","die","dem"],
            correctIndex: 0,
            explainCorrect: "The receiver of geben is dative: der Mutter.",
            explainWrong: "The receiver of geben is dative: der Mutter.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-125",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich frage ___ Lehrer.",
            options: ["den","dem","der"],
            correctIndex: 0,
            explainCorrect: "fragen takes the accusative: den Lehrer.",
            explainWrong: "fragen takes the accusative: den Lehrer.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-126",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Wir besuchen ___ Onkel.",
            options: ["den","dem","der"],
            correctIndex: 0,
            explainCorrect: "besuchen takes the accusative: den Onkel.",
            explainWrong: "besuchen takes the accusative: den Onkel.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-127",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Sie trifft ___ Freundin.",
            options: ["die","der","den"],
            correctIndex: 0,
            explainCorrect: "treffen takes the accusative; feminine stays die.",
            explainWrong: "treffen takes the accusative; feminine stays die.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-128",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Er versteht ___ Frage.",
            options: ["die","der","den"],
            correctIndex: 0,
            explainCorrect: "verstehen takes the accusative; feminine stays die.",
            explainWrong: "verstehen takes the accusative; feminine stays die.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-129",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich höre ___ Radio.",
            options: ["das","dem","den"],
            correctIndex: 0,
            explainCorrect: "hören takes the accusative; neuter stays das.",
            explainWrong: "hören takes the accusative; neuter stays das.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-130",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "What case is the highlighted noun in?",
            prompt: "Wir nehmen ___ Taxi.",
            options: ["das","dem","den"],
            correctIndex: 0,
            explainCorrect: "nehmen takes the accusative; neuter stays das.",
            explainWrong: "nehmen takes the accusative; neuter stays das.",
          },
        },
      ],
    },
    {
      id: "case-detective-4",
      title: "Level 4: Preposition detective",
      rounds: [
        {
          kind: "exercise",
          exercise: {
            id: "cd-131",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Ich fahre mit ___ Auto.",
            options: ["dem","das","den"],
            correctIndex: 0,
            explainCorrect: "mit always takes the dative: mit dem Auto.",
            explainWrong: "mit always takes the dative: mit dem Auto.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-132",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Das Geschenk ist für ___ dich.",
            options: ["dich","dir","du"],
            correctIndex: 0,
            explainCorrect: "für always takes the accusative: für dich.",
            explainWrong: "für always takes the accusative: für dich.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-133",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Ich komme aus ___ Nigeria.",
            options: ["aus","von","zu"],
            correctIndex: 0,
            explainCorrect: "aus answers Woher? without an article: aus Nigeria.",
            explainWrong: "aus answers Woher? without an article: aus Nigeria.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-134",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Die Lampe ist auf ___ Tisch. (position)",
            options: ["dem","den","das"],
            correctIndex: 0,
            explainCorrect: "Wo? position takes the dative: auf dem Tisch.",
            explainWrong: "Wo? position takes the dative: auf dem Tisch.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-135",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Ich lege das Buch auf ___ Tisch. (direction)",
            options: ["den","dem","der"],
            correctIndex: 0,
            explainCorrect: "Wohin? direction takes the accusative: auf den Tisch.",
            explainWrong: "Wohin? direction takes the accusative: auf den Tisch.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-136",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Wir gehen in ___ Kino. (direction)",
            options: ["das","dem","der"],
            correctIndex: 0,
            explainCorrect: "Wohin? into the cinema: in das Kino.",
            explainWrong: "Wohin? into the cinema: in das Kino.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-137",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Er ist in ___ Schule. (position)",
            options: ["der","die","dem"],
            correctIndex: 0,
            explainCorrect: "Wo? position takes the dative: in der Schule.",
            explainWrong: "Wo? position takes the dative: in der Schule.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-138",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Sie wohnt bei ___ Eltern.",
            options: ["den","die","dem"],
            correctIndex: 0,
            explainCorrect: "bei takes the dative; plural dative is den Eltern.",
            explainWrong: "bei takes the dative; plural dative is den Eltern.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-139",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Ich fliege nach ___ Berlin.",
            options: ["nach","in","zu"],
            correctIndex: 0,
            explainCorrect: "nach is used with cities without articles: nach Berlin.",
            explainWrong: "nach is used with cities without articles: nach Berlin.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-140",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Das Buch ist für ___ Kind.",
            options: ["das","dem","den"],
            correctIndex: 0,
            explainCorrect: "für takes the accusative; neuter stays das.",
            explainWrong: "für takes the accusative; neuter stays das.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-141",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Wir treffen uns vor ___ Kino. (position)",
            options: ["dem","das","den"],
            correctIndex: 0,
            explainCorrect: "Wo? position takes the dative: vor dem Kino.",
            explainWrong: "Wo? position takes the dative: vor dem Kino.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-142",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Ich stelle die Vase auf ___ Tisch. (direction)",
            options: ["den","dem","der"],
            correctIndex: 0,
            explainCorrect: "Wohin? direction takes the accusative: auf den Tisch.",
            explainWrong: "Wohin? direction takes the accusative: auf den Tisch.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-143",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Das Bild hängt an ___ Wand. (position)",
            options: ["der","die","dem"],
            correctIndex: 0,
            explainCorrect: "Wo? position takes the dative: an der Wand.",
            explainWrong: "Wo? position takes the dative: an der Wand.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-144",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Ich hänge das Bild an ___ Wand. (direction)",
            options: ["die","der","dem"],
            correctIndex: 0,
            explainCorrect: "Wohin? direction takes the accusative: an die Wand.",
            explainWrong: "Wohin? direction takes the accusative: an die Wand.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-145",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Wir fahren mit ___ Bus.",
            options: ["dem","den","das"],
            correctIndex: 0,
            explainCorrect: "mit always takes the dative: mit dem Bus.",
            explainWrong: "mit always takes the dative: mit dem Bus.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-146",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Er wartet auf ___ Freund.",
            options: ["den","dem","der"],
            correctIndex: 0,
            explainCorrect: "warten auf takes the accusative: auf den Freund.",
            explainWrong: "warten auf takes the accusative: auf den Freund.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-147",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Sie kommt von ___ Arbeit.",
            options: ["der","die","dem"],
            correctIndex: 0,
            explainCorrect: "von takes the dative: von der Arbeit.",
            explainWrong: "von takes the dative: von der Arbeit.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-148",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Ich spreche mit ___ Lehrer.",
            options: ["dem","den","der"],
            correctIndex: 0,
            explainCorrect: "mit always takes the dative: mit dem Lehrer.",
            explainWrong: "mit always takes the dative: mit dem Lehrer.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-149",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Wir kommen aus ___ Schule.",
            options: ["der","die","dem"],
            correctIndex: 0,
            explainCorrect: "aus takes the dative: aus der Schule.",
            explainWrong: "aus takes the dative: aus der Schule.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-150",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Das Geschenk ist von ___ Oma.",
            options: ["der","die","dem"],
            correctIndex: 0,
            explainCorrect: "von takes the dative: von der Oma.",
            explainWrong: "von takes the dative: von der Oma.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-151",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Ich sitze neben ___ Fenster.",
            options: ["dem","das","den"],
            correctIndex: 0,
            explainCorrect: "neben takes the dative for position: neben dem Fenster.",
            explainWrong: "neben takes the dative for position: neben dem Fenster.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-152",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Der Stuhl steht neben ___ Tisch.",
            options: ["dem","den","der"],
            correctIndex: 0,
            explainCorrect: "Position takes the dative: neben dem Tisch.",
            explainWrong: "Position takes the dative: neben dem Tisch.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-153",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Ich gehe nach ___ Hause.",
            options: ["nach","zu","in"],
            correctIndex: 0,
            explainCorrect: "nach Hause is the fixed form for going home.",
            explainWrong: "nach Hause is the fixed form for going home.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-154",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Er fährt zu ___ Oma.",
            options: ["der","die","dem"],
            correctIndex: 0,
            explainCorrect: "zu takes the dative: zu der Oma (zur Oma).",
            explainWrong: "zu takes the dative: zu der Oma (zur Oma).",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-155",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Ich komme zu ___ dir.",
            options: ["dir","dich","du"],
            correctIndex: 0,
            explainCorrect: "zu takes the dative: zu dir.",
            explainWrong: "zu takes the dative: zu dir.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-156",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Das ist für ___ Mama.",
            options: ["die","der","dem"],
            correctIndex: 0,
            explainCorrect: "für takes the accusative; feminine stays die.",
            explainWrong: "für takes the accusative; feminine stays die.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-157",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Wir warten auf ___ Bus.",
            options: ["den","dem","der"],
            correctIndex: 0,
            explainCorrect: "warten auf takes the accusative: auf den Bus.",
            explainWrong: "warten auf takes the accusative: auf den Bus.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-158",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Sie fährt mit ___ Zug.",
            options: ["dem","den","das"],
            correctIndex: 0,
            explainCorrect: "mit always takes the dative: mit dem Zug.",
            explainWrong: "mit always takes the dative: mit dem Zug.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-159",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Ich bin seit ___ Jahr in Deutschland.",
            options: ["einem","einen","ein"],
            correctIndex: 0,
            explainCorrect: "seit takes the dative: seit einem Jahr.",
            explainWrong: "seit takes the dative: seit einem Jahr.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-160",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Er wohnt gegenüber ___ Bahnhof.",
            options: ["dem","den","der"],
            correctIndex: 0,
            explainCorrect: "gegenüber takes the dative: gegenüber dem Bahnhof.",
            explainWrong: "gegenüber takes the dative: gegenüber dem Bahnhof.",
          },
        },
      ],
    },
  ],
};
