import type { Game } from "./schema";

export const caseDetectiveGame: Game = {
  id: "case-detective",
  title: "Case Detective",
  emoji: "🕵️",
  description:
    "Spot the case: nominative, accusative, or dative? Be the grammar detective.",
  category: "grammar",
  tags: ["A1", "A2"],
  levels: [
    {
      id: "case-detective-1",
      title: "Level 1: Nominativ or Akkusativ?",
      rounds: [
        {
          kind: "exercise",
          exercise: {
            id: "cd-01",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Der Mann schläft. (the man)",
            options: ["Nominativ", "Akkusativ", "Dativ"],
            correctIndex: 0,
            explainCorrect: "The man is the subject doing the sleeping: nominative.",
            explainWrong: "The subject of a sentence is always nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-02",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Die Frau arbeitet. (the woman)",
            options: ["Nominativ", "Akkusativ", "Dativ"],
            correctIndex: 0,
            explainCorrect: "The woman is the subject: nominative.",
            explainWrong: "The subject (die Frau) is nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-03",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Das Kind spielt. (the child)",
            options: ["Nominativ", "Akkusativ", "Dativ"],
            correctIndex: 0,
            explainCorrect: "The child is the subject: nominative.",
            explainWrong: "The subject (das Kind) is nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-04",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich sehe den Mann. (the man)",
            options: ["Akkusativ", "Nominativ", "Dativ"],
            correctIndex: 0,
            explainCorrect: "The man is the direct object of sehen: accusative (den).",
            explainWrong: "The direct object after sehen is accusative: den Mann.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-05",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Wir kaufen einen Apfel. (an apple)",
            options: ["Akkusativ", "Nominativ", "Dativ"],
            correctIndex: 0,
            explainCorrect: "The apple is what is bought: accusative (einen).",
            explainWrong: "The direct object of kaufen is accusative: einen Apfel.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-06",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Sie liest das Buch. (the book)",
            options: ["Akkusativ", "Nominativ", "Dativ"],
            correctIndex: 0,
            explainCorrect: "The book is the direct object of lesen: accusative.",
            explainWrong: "das Buch stays das in the accusative, but it is the object: accusative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-07",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Der Hund bellt. (the dog)",
            options: ["Nominativ", "Akkusativ", "Dativ"],
            correctIndex: 0,
            explainCorrect: "The dog is the subject barking: nominative.",
            explainWrong: "The subject (der Hund) is nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-08",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich trinke den Kaffee. (the coffee)",
            options: ["Akkusativ", "Nominativ", "Dativ"],
            correctIndex: 0,
            explainCorrect: "The coffee is what is drunk: accusative (den).",
            explainWrong: "The direct object of trinken is accusative: den Kaffee.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-09",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Die Kinder lernen Deutsch. (the children)",
            options: ["Nominativ", "Akkusativ", "Dativ"],
            correctIndex: 0,
            explainCorrect: "The children are the subject: nominative.",
            explainWrong: "The subject (die Kinder) is nominative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-10",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Er öffnet die Tür. (the door)",
            options: ["Akkusativ", "Nominativ", "Dativ"],
            correctIndex: 0,
            explainCorrect: "The door is what is opened: accusative.",
            explainWrong: "The direct object of öffnen is accusative: die Tür.",
          },
        },
      ],
    },
    {
      id: "case-detective-2",
      title: "Level 2: Dativ spotter",
      rounds: [
        {
          kind: "exercise",
          exercise: {
            id: "cd-11",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich helfe dem Mann. (the man)",
            options: ["Dativ", "Akkusativ", "Nominativ"],
            correctIndex: 0,
            explainCorrect: "helfen always takes the dative: dem Mann.",
            explainWrong: "helfen takes the dative, never the accusative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-12",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Wir danken der Frau. (the woman)",
            options: ["Dativ", "Akkusativ", "Nominativ"],
            correctIndex: 0,
            explainCorrect: "danken takes the dative: der Frau.",
            explainWrong: "danken takes the dative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-13",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted pronoun in?",
            prompt: "Das schmeckt mir gut. (to me)",
            options: ["Dativ", "Akkusativ", "Nominativ"],
            correctIndex: 0,
            explainCorrect: "schmecken takes the dative: mir.",
            explainWrong: "schmecken takes the dative: mir, not mich.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-14",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Ich gebe dem Kind einen Apfel. (the child)",
            options: ["Dativ", "Akkusativ", "Nominativ"],
            correctIndex: 0,
            explainCorrect: "The receiver of geben is dative: dem Kind.",
            explainWrong: "geben: the receiver is dative, the thing given is accusative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-15",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted pronoun in?",
            prompt: "Das gefällt ihm. (to him)",
            options: ["Dativ", "Akkusativ", "Nominativ"],
            correctIndex: 0,
            explainCorrect: "gefallen takes the dative: ihm.",
            explainWrong: "gefallen takes the dative: ihm, not ihn.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-16",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Sie antwortet dem Lehrer. (the teacher)",
            options: ["Dativ", "Akkusativ", "Nominativ"],
            correctIndex: 0,
            explainCorrect: "antworten takes the dative: dem Lehrer.",
            explainWrong: "antworten takes the dative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-17",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted pronoun in?",
            prompt: "Ich glaube dir. (to you)",
            options: ["Dativ", "Akkusativ", "Nominativ"],
            correctIndex: 0,
            explainCorrect: "glauben takes the dative: dir.",
            explainWrong: "glauben takes the dative: dir, not dich.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-18",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Das Buch gehört mir. (to me)",
            options: ["Dativ", "Akkusativ", "Nominativ"],
            correctIndex: 0,
            explainCorrect: "gehören takes the dative: mir.",
            explainWrong: "gehören takes the dative.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-19",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted noun in?",
            prompt: "Er hilft seiner Mutter. (his mother)",
            options: ["Dativ", "Akkusativ", "Nominativ"],
            correctIndex: 0,
            explainCorrect: "helfen takes the dative: seiner Mutter.",
            explainWrong: "helfen takes the dative: seiner Mutter.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-20",
            type: "multiple-choice",
            title: "Which case?",
            instruction: "What case is the highlighted pronoun in?",
            prompt: "Ich wünsche dir alles Gute. (to you)",
            options: ["Dativ", "Akkusativ", "Nominativ"],
            correctIndex: 0,
            explainCorrect: "wünschen: the person is dative: dir.",
            explainWrong: "wünschen takes the dative for the person.",
          },
        },
      ],
    },
    {
      id: "case-detective-3",
      title: "Level 3: Choose the form",
      rounds: [
        {
          kind: "exercise",
          exercise: {
            id: "cd-21",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "Choose the correct article form.",
            prompt: "Ich sehe ___ Mann.",
            options: ["den", "dem", "der"],
            correctIndex: 0,
            explainCorrect: "sehen takes the accusative: den Mann.",
            explainWrong: "The direct object of sehen is accusative: den Mann.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-22",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "Choose the correct article form.",
            prompt: "Ich gebe ___ Kind einen Apfel.",
            options: ["dem", "den", "der"],
            correctIndex: 0,
            explainCorrect: "The receiver of geben is dative: dem Kind.",
            explainWrong: "geben takes the dative for the receiver: dem Kind.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-23",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "Choose the correct article form.",
            prompt: "Ich danke ___ Frau.",
            options: ["der", "die", "den"],
            correctIndex: 0,
            explainCorrect: "danken takes the dative: der Frau.",
            explainWrong: "danken takes the dative: der Frau.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-24",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "Choose the correct article form.",
            prompt: "Sie hat ___ Bruder.",
            options: ["einen", "einem", "ein"],
            correctIndex: 0,
            explainCorrect: "haben takes the accusative: einen Bruder.",
            explainWrong: "The direct object of haben is accusative: einen Bruder.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-25",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "Choose the correct article form.",
            prompt: "Wir besuchen ___ Oma.",
            options: ["die", "der", "den"],
            correctIndex: 0,
            explainCorrect: "besuchen takes the accusative; feminine stays die.",
            explainWrong: "The accusative of die Oma is die Oma.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-26",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "Choose the correct article form.",
            prompt: "Er kauft ___ Auto.",
            options: ["ein", "einen", "einem"],
            correctIndex: 0,
            explainCorrect: "kaufen takes the accusative; neuter stays ein.",
            explainWrong: "The accusative of ein Auto is ein Auto.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-27",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "Choose the correct article form.",
            prompt: "Ich helfe ___ Freund.",
            options: ["einem", "einen", "ein"],
            correctIndex: 0,
            explainCorrect: "helfen takes the dative: einem Freund.",
            explainWrong: "helfen takes the dative: einem Freund.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-28",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "Choose the correct article form.",
            prompt: "Das schmeckt ___ Mann gut.",
            options: ["dem", "den", "der"],
            correctIndex: 0,
            explainCorrect: "schmecken takes the dative: dem Mann.",
            explainWrong: "schmecken takes the dative: dem Mann.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-29",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "Choose the correct article form.",
            prompt: "Sie sieht ___ Film.",
            options: ["einen", "einem", "ein"],
            correctIndex: 0,
            explainCorrect: "sehen takes the accusative: einen Film.",
            explainWrong: "The direct object of sehen is accusative: einen Film.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-30",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "Choose the correct article form.",
            prompt: "Wir antworten ___ Lehrerin.",
            options: ["der", "die", "dem"],
            correctIndex: 0,
            explainCorrect: "antworten takes the dative: der Lehrerin.",
            explainWrong: "antworten takes the dative: der Lehrerin.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-31",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "Choose the correct article form.",
            prompt: "Ich liebe ___ Hund.",
            options: ["den", "dem", "der"],
            correctIndex: 0,
            explainCorrect: "lieben takes the accusative: den Hund.",
            explainWrong: "The direct object of lieben is accusative: den Hund.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-32",
            type: "multiple-choice",
            title: "Choose the form",
            instruction: "Choose the correct article form.",
            prompt: "Er gibt ___ Schwester ein Geschenk.",
            options: ["der", "die", "dem"],
            correctIndex: 0,
            explainCorrect: "The receiver of geben is dative: der Schwester.",
            explainWrong: "geben takes the dative for the receiver: der Schwester.",
          },
        },
      ],
    },
    {
      id: "case-detective-4",
      title: "Level 4: Preposition detective",
      rounds: [
        {
          kind: "exercise",
          exercise: {
            id: "cd-33",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Ich fahre mit ___ Auto.",
            options: ["dem", "das", "den"],
            correctIndex: 0,
            explainCorrect: "mit always takes the dative: mit dem Auto.",
            explainWrong: "mit takes the dative: mit dem Auto.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-34",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Das Geschenk ist für ___ dich.",
            options: ["dich", "dir", "du"],
            correctIndex: 0,
            explainCorrect: "für always takes the accusative: für dich.",
            explainWrong: "für takes the accusative: für dich.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-35",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Ich komme aus ___ Nigeria.",
            options: ["aus", "von", "zu"],
            correctIndex: 0,
            explainCorrect: "aus answers Woher? without an article: aus Nigeria.",
            explainWrong: "aus means from: aus Nigeria.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-36",
            type: "multiple-choice",
            title: "Wo or wohin?",
            instruction: "Position (wo?) takes the dative, direction (wohin?) the accusative.",
            prompt: "Die Lampe ist auf ___ Tisch. (position)",
            options: ["dem", "den", "das"],
            correctIndex: 0,
            explainCorrect: "Wo? position takes the dative: auf dem Tisch.",
            explainWrong: "Position takes the dative: auf dem Tisch.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-37",
            type: "multiple-choice",
            title: "Wo or wohin?",
            instruction: "Position (wo?) takes the dative, direction (wohin?) the accusative.",
            prompt: "Ich lege das Buch auf ___ Tisch. (direction)",
            options: ["den", "dem", "der"],
            correctIndex: 0,
            explainCorrect: "Wohin? direction takes the accusative: auf den Tisch.",
            explainWrong: "Direction takes the accusative: auf den Tisch.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-38",
            type: "multiple-choice",
            title: "Wo or wohin?",
            instruction: "Position (wo?) takes the dative, direction (wohin?) the accusative.",
            prompt: "Wir gehen in ___ Kino. (direction)",
            options: ["das", "dem", "der"],
            correctIndex: 0,
            explainCorrect: "Wohin? into the cinema: in das Kino.",
            explainWrong: "Direction takes the accusative: in das Kino.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-39",
            type: "multiple-choice",
            title: "Wo or wohin?",
            instruction: "Position (wo?) takes the dative, direction (wohin?) the accusative.",
            prompt: "Er ist in ___ Schule. (position)",
            options: ["der", "die", "dem"],
            correctIndex: 0,
            explainCorrect: "Wo? position takes the dative: in der Schule.",
            explainWrong: "Position takes the dative: in der Schule.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-40",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Sie wohnt bei ___ Eltern.",
            options: ["den", "die", "dem"],
            correctIndex: 0,
            explainCorrect: "bei takes the dative; plural dative is den Eltern.",
            explainWrong: "bei takes the dative: bei den Eltern.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-41",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Ich fliege nach ___ Berlin.",
            options: ["nach", "in", "zu"],
            correctIndex: 0,
            explainCorrect: "nach is used with cities and countries without articles: nach Berlin.",
            explainWrong: "nach Berlin, like nach Deutschland: no article.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-42",
            type: "multiple-choice",
            title: "After the preposition",
            instruction: "Choose the correct form after the preposition.",
            prompt: "Das Buch ist für ___ Kind.",
            options: ["das", "dem", "den"],
            correctIndex: 0,
            explainCorrect: "für takes the accusative; neuter stays das.",
            explainWrong: "für takes the accusative: für das Kind.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-43",
            type: "multiple-choice",
            title: "Wo or wohin?",
            instruction: "Position (wo?) takes the dative, direction (wohin?) the accusative.",
            prompt: "Wir treffen uns vor ___ Kino. (position)",
            options: ["dem", "das", "den"],
            correctIndex: 0,
            explainCorrect: "Wo? position takes the dative: vor dem Kino.",
            explainWrong: "Position takes the dative: vor dem Kino.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "cd-44",
            type: "multiple-choice",
            title: "Wo or wohin?",
            instruction: "Position (wo?) takes the dative, direction (wohin?) the accusative.",
            prompt: "Ich stelle die Vase auf ___ Tisch. (direction)",
            options: ["den", "dem", "der"],
            correctIndex: 0,
            explainCorrect: "Wohin? direction takes the accusative: auf den Tisch.",
            explainWrong: "Direction takes the accusative: auf den Tisch.",
          },
        },
      ],
    },
  ],
};