import type { Game } from "./schema";

export const games: Game[] = [
  {
    id: "flashcards",
    title: "Flashcards",
    emoji: "🃏",
    description: "Drill vocabulary with digital flashcards. Say the word aloud before revealing the answer.",
    category: "vocabulary",
    levels: [
      {
        id: "flashcards-1",
        title: "Level 1: Basics",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "fc-greetings",
              type: "flashcard",
              title: "Greetings",
              instruction: "Say the German greeting out loud, then reveal.",
              items: [
                { front: "Hallo!", back: "hello", frontAudio: true },
                { front: "Guten Morgen!", back: "good morning", frontAudio: true },
                { front: "Guten Tag!", back: "good day", frontAudio: true },
                { front: "Guten Abend!", back: "good evening", frontAudio: true },
                { front: "Tschüss!", back: "bye", frontAudio: true },
                { front: "Auf Wiedersehen!", back: "goodbye", frontAudio: true },
              ],
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "fc-family",
              type: "flashcard",
              title: "Family",
              instruction: "Say the German word with its article, then reveal.",
              items: [
                { front: "der Vater", back: "the father", frontAudio: true },
                { front: "die Mutter", back: "the mother", frontAudio: true },
                { front: "der Bruder", back: "the brother", frontAudio: true },
                { front: "die Schwester", back: "the sister", frontAudio: true },
                { front: "die Familie", back: "the family", frontAudio: true },
                { front: "das Kind", back: "the child", frontAudio: true },
              ],
            },
          },
        ],
      },
      {
        id: "flashcards-2",
        title: "Level 2: Food and drink",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "fc-food",
              type: "flashcard",
              title: "Food",
              instruction: "Say the German word with its article, then reveal.",
              items: [
                { front: "das Brot", back: "the bread", frontAudio: true },
                { front: "der Käse", back: "the cheese", frontAudio: true },
                { front: "das Ei", back: "the egg", frontAudio: true },
                { front: "das Obst", back: "the fruit", frontAudio: true },
                { front: "das Gemüse", back: "the vegetables", frontAudio: true },
                { front: "der Apfel", back: "the apple", frontAudio: true },
              ],
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "fc-drinks",
              type: "flashcard",
              title: "Drinks",
              instruction: "Say the German word, then reveal.",
              items: [
                { front: "das Wasser", back: "the water", frontAudio: true },
                { front: "der Kaffee", back: "the coffee", frontAudio: true },
                { front: "der Tee", back: "the tea", frontAudio: true },
                { front: "die Milch", back: "the milk", frontAudio: true },
                { front: "der Saft", back: "the juice", frontAudio: true },
                { front: "das Bier", back: "the beer", frontAudio: true },
              ],
            },
          },
        ],
      },
      {
        id: "flashcards-3",
        title: "Level 3: Daily life",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "fc-daily",
              type: "flashcard",
              title: "Daily verbs",
              instruction: "Say the German verb, then reveal.",
              items: [
                { front: "aufstehen", back: "to get up", frontAudio: true },
                { front: "arbeiten", back: "to work", frontAudio: true },
                { front: "essen", back: "to eat", frontAudio: true },
                { front: "schlafen", back: "to sleep", frontAudio: true },
                { front: "fernsehen", back: "to watch TV", frontAudio: true },
                { front: "einkaufen", back: "to shop", frontAudio: true },
              ],
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "fc-clothes",
              type: "flashcard",
              title: "Clothes",
              instruction: "Say the German word with its article, then reveal.",
              items: [
                { front: "das Hemd", back: "the shirt", frontAudio: true },
                { front: "die Hose", back: "the trousers", frontAudio: true },
                { front: "das Kleid", back: "the dress", frontAudio: true },
                { front: "die Jacke", back: "the jacket", frontAudio: true },
                { front: "die Schuhe", back: "the shoes", frontAudio: true },
                { front: "der Mantel", back: "the coat", frontAudio: true },
              ],
            },
          },
        ],
      },
    ],
  },
  {
    id: "match-words",
    title: "Match Words",
    emoji: "🔗",
    description: "Match German words to their English meanings. The classic word-pair game.",
    category: "vocabulary",
    levels: [
      {
        id: "match-words-1",
        title: "Level 1: Greetings and people",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "mw-people",
              type: "matching",
              title: "People",
              instruction: "Match each German word to its meaning.",
              pairs: [
                ["der Mann", "the man"],
                ["die Frau", "the woman"],
                ["das Kind", "the child"],
                ["der Freund", "the friend (male)"],
                ["die Freundin", "the friend (female)"],
                ["der Lehrer", "the teacher (male)"],
              ],
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "mw-greetings",
              type: "matching",
              title: "Greetings",
              instruction: "Match each greeting to its meaning.",
              pairs: [
                ["Hallo!", "hello"],
                ["Guten Morgen!", "good morning"],
                ["Guten Abend!", "good evening"],
                ["Bis bald!", "see you soon"],
                ["Tschüss!", "bye"],
                ["Schönen Tag noch!", "have a nice day"],
              ],
            },
          },
        ],
      },
      {
        id: "match-words-2",
        title: "Level 2: Places and rooms",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "mw-places",
              type: "matching",
              title: "Places in town",
              instruction: "Match each place to its meaning.",
              pairs: [
                ["der Bahnhof", "the station"],
                ["das Rathaus", "the town hall"],
                ["die Apotheke", "the pharmacy"],
                ["das Krankenhaus", "the hospital"],
                ["die Kirche", "the church"],
                ["der Supermarkt", "the supermarket"],
              ],
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "mw-rooms",
              type: "matching",
              title: "Rooms",
              instruction: "Match each room to its meaning.",
              pairs: [
                ["das Wohnzimmer", "the living room"],
                ["das Schlafzimmer", "the bedroom"],
                ["die Küche", "the kitchen"],
                ["das Badezimmer", "the bathroom"],
                ["der Flur", "the hallway"],
                ["der Balkon", "the balcony"],
              ],
            },
          },
        ],
      },
      {
        id: "match-words-3",
        title: "Level 3: Food and drink",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "mw-food",
              type: "matching",
              title: "Food",
              instruction: "Match each food to its meaning.",
              pairs: [
                ["das Brot", "the bread"],
                ["der Käse", "the cheese"],
                ["das Ei", "the egg"],
                ["die Wurst", "the sausage"],
                ["das Fleisch", "the meat"],
                ["der Fisch", "the fish"],
              ],
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "mw-drinks",
              type: "matching",
              title: "Drinks",
              instruction: "Match each drink to its meaning.",
              pairs: [
                ["das Wasser", "the water"],
                ["der Kaffee", "the coffee"],
                ["die Milch", "the milk"],
                ["der Saft", "the juice"],
                ["das Bier", "the beer"],
                ["der Wein", "the wine"],
              ],
            },
          },
        ],
      },
    ],
  },
  {
    id: "picture-match",
    title: "Picture Match",
    emoji: "🖼️",
    description: "Match German words to picture descriptions. Think of the picture, pick the word.",
    category: "vocabulary",
    levels: [
      {
        id: "picture-match-1",
        title: "Level 1: Animals",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "pm-animals",
              type: "matching",
              title: "Animals",
              instruction: "Match the animal to its German name.",
              pairs: [
                ["the dog", "der Hund"],
                ["the cat", "die Katze"],
                ["the horse", "das Pferd"],
                ["the bird", "der Vogel"],
                ["the fish", "der Fisch"],
                ["the mouse", "die Maus"],
              ],
            },
          },
        ],
      },
      {
        id: "picture-match-2",
        title: "Level 2: Things at home",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "pm-furniture",
              type: "matching",
              title: "Furniture",
              instruction: "Match the picture description to the German word.",
              pairs: [
                ["the table", "der Tisch"],
                ["the chair", "der Stuhl"],
                ["the bed", "das Bett"],
                ["the lamp", "die Lampe"],
                ["the mirror", "der Spiegel"],
                ["the carpet", "der Teppich"],
              ],
            },
          },
        ],
      },
      {
        id: "picture-match-3",
        title: "Level 3: Outside",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "pm-outside",
              type: "matching",
              title: "Outside",
              instruction: "Match the picture description to the German word.",
              pairs: [
                ["the sun", "die Sonne"],
                ["the sky", "der Himmel"],
                ["the rain", "der Regen"],
                ["the snow", "der Schnee"],
                ["the tree", "der Baum"],
                ["the street", "die Straße"],
              ],
            },
          },
        ],
      },
    ],
  },
  {
    id: "memory-cards",
    title: "Memory Cards",
    emoji: "🧠",
    description: "Flip cards to find the German word and its English meaning. Classic memory game.",
    category: "vocabulary",
    levels: [
      {
        id: "memory-cards-1",
        title: "Level 1: Greetings",
        rounds: [
          {
            kind: "memory",
            title: "Greeting pairs",
            instruction: "Flip two cards. Match the German greeting to its English meaning.",
            cards: [
              { de: "Hallo", en: "hello", audio: true },
              { de: "Guten Morgen", en: "good morning", audio: true },
              { de: "Tschüss", en: "bye", audio: true },
              { de: "Bis bald", en: "see you soon", audio: true },
              { de: "Guten Tag", en: "good day", audio: true },
              { de: "Gute Nacht", en: "good night", audio: true },
            ],
          },
        ],
      },
      {
        id: "memory-cards-2",
        title: "Level 2: Family",
        rounds: [
          {
            kind: "memory",
            title: "Family pairs",
            instruction: "Flip two cards. Match the German family word to its English meaning.",
            cards: [
              { de: "der Vater", en: "the father", audio: true },
              { de: "die Mutter", en: "the mother", audio: true },
              { de: "der Bruder", en: "the brother", audio: true },
              { de: "die Schwester", en: "the sister", audio: true },
              { de: "der Sohn", en: "the son", audio: true },
              { de: "die Tochter", en: "the daughter", audio: true },
            ],
          },
        ],
      },
      {
        id: "memory-cards-3",
        title: "Level 3: Food",
        rounds: [
          {
            kind: "memory",
            title: "Food pairs",
            instruction: "Flip two cards. Match the German food word to its English meaning.",
            cards: [
              { de: "das Brot", en: "the bread", audio: true },
              { de: "der Käse", en: "the cheese", audio: true },
              { de: "der Apfel", en: "the apple", audio: true },
              { de: "das Ei", en: "the egg", audio: true },
              { de: "die Milch", en: "the milk", audio: true },
              { de: "der Kaffee", en: "the coffee", audio: true },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "category-sort",
    title: "Category Sort",
    emoji: "🗂️",
    description: "Sort words into the right categories: food, people, places, or verbs.",
    category: "vocabulary",
    levels: [
      {
        id: "category-sort-1",
        title: "Level 1: Food or drink",
        rounds: [
          {
            kind: "sort",
            title: "Food or drink?",
            instruction: "Sort each word into Food or Drink.",
            categories: [
              { name: "Food", items: ["das Brot", "der Käse", "der Apfel", "das Ei"] },
              { name: "Drink", items: ["das Wasser", "der Kaffee", "die Milch", "der Saft"] },
            ],
          },
        ],
      },
      {
        id: "category-sort-2",
        title: "Level 2: People or places",
        rounds: [
          {
            kind: "sort",
            title: "People or places?",
            instruction: "Sort each word into People or Places.",
            categories: [
              { name: "People", items: ["der Vater", "die Mutter", "der Lehrer", "die Ärztin"] },
              { name: "Places", items: ["der Bahnhof", "die Schule", "die Apotheke", "das Kino"] },
            ],
          },
        ],
      },
      {
        id: "category-sort-3",
        title: "Level 3: Actions or things",
        rounds: [
          {
            kind: "sort",
            title: "Verb or noun?",
            instruction: "Sort each word into Verbs (actions) or Nouns (things).",
            categories: [
              { name: "Verb", items: ["arbeiten", "essen", "schlafen", "laufen"] },
              { name: "Nomen", items: ["der Tisch", "die Lampe", "das Buch", "der Stuhl"] },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "article-challenge",
    title: "Article Challenge",
    emoji: "🎯",
    description: "Choose the correct article: der, die, or das. Train your noun genders.",
    category: "grammar",
    levels: [
      {
        id: "article-challenge-1",
        title: "Level 1: Simple nouns",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "ac-1",
              type: "multiple-choice",
              title: "Choose the article",
              instruction: "Pick the correct article.",
              prompt: "___ Tisch (table)",
              options: ["der", "die", "das"],
              correctIndex: 0,
              explainCorrect: "Tisch is masculine: der Tisch.",
              explainWrong: "Tisch is masculine, so it takes der.",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "ac-2",
              type: "multiple-choice",
              title: "Choose the article",
              instruction: "Pick the correct article.",
              prompt: "___ Lampe (lamp)",
              options: ["die", "der", "das"],
              correctIndex: 0,
              explainCorrect: "Lampe is feminine: die Lampe.",
              explainWrong: "Lampe is feminine, so it takes die.",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "ac-3",
              type: "multiple-choice",
              title: "Choose the article",
              instruction: "Pick the correct article.",
              prompt: "___ Buch (book)",
              options: ["das", "der", "die"],
              correctIndex: 0,
              explainCorrect: "Buch is neuter: das Buch.",
              explainWrong: "Buch is neuter, so it takes das.",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "ac-4",
              type: "multiple-choice",
              title: "Choose the article",
              instruction: "Pick the correct article.",
              prompt: "___ Frau (woman)",
              options: ["die", "der", "das"],
              correctIndex: 0,
              explainCorrect: "Frau is feminine: die Frau.",
              explainWrong: "Frau is feminine, so it takes die.",
            },
          },
        ],
      },
      {
        id: "article-challenge-2",
        title: "Level 2: Rooms and furniture",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "ac-5",
              type: "multiple-choice",
              title: "Choose the article",
              instruction: "Pick the correct article.",
              prompt: "___ Küche (kitchen)",
              options: ["die", "der", "das"],
              correctIndex: 0,
              explainCorrect: "Küche is feminine: die Küche.",
              explainWrong: "Küche is feminine, so it takes die.",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "ac-6",
              type: "multiple-choice",
              title: "Choose the article",
              instruction: "Pick the correct article.",
              prompt: "___ Schlafzimmer (bedroom)",
              options: ["das", "der", "die"],
              correctIndex: 0,
              explainCorrect: "Zimmer words are neuter: das Schlafzimmer.",
              explainWrong: "Words ending in -zimmer are neuter: das Schlafzimmer.",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "ac-7",
              type: "multiple-choice",
              title: "Choose the article",
              instruction: "Pick the correct article.",
              prompt: "___ Stuhl (chair)",
              options: ["der", "die", "das"],
              correctIndex: 0,
              explainCorrect: "Stuhl is masculine: der Stuhl.",
              explainWrong: "Stuhl is masculine, so it takes der.",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "ac-8",
              type: "multiple-choice",
              title: "Choose the article",
              instruction: "Pick the correct article.",
              prompt: "___ Sofa (sofa)",
              options: ["das", "der", "die"],
              correctIndex: 0,
              explainCorrect: "Sofa is neuter: das Sofa.",
              explainWrong: "Sofa is neuter, so it takes das.",
            },
          },
        ],
      },
      {
        id: "article-challenge-3",
        title: "Level 3: Food and drink",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "ac-9",
              type: "multiple-choice",
              title: "Choose the article",
              instruction: "Pick the correct article.",
              prompt: "___ Brot (bread)",
              options: ["das", "der", "die"],
              correctIndex: 0,
              explainCorrect: "Brot is neuter: das Brot.",
              explainWrong: "Brot is neuter, so it takes das.",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "ac-10",
              type: "multiple-choice",
              title: "Choose the article",
              instruction: "Pick the correct article.",
              prompt: "___ Milch (milk)",
              options: ["die", "der", "das"],
              correctIndex: 0,
              explainCorrect: "Milch is feminine: die Milch.",
              explainWrong: "Milch is feminine, so it takes die.",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "ac-11",
              type: "multiple-choice",
              title: "Choose the article",
              instruction: "Pick the correct article.",
              prompt: "___ Kaffee (coffee)",
              options: ["der", "die", "das"],
              correctIndex: 0,
              explainCorrect: "Kaffee is masculine: der Kaffee.",
              explainWrong: "Kaffee is masculine, so it takes der.",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "ac-12",
              type: "multiple-choice",
              title: "Choose the article",
              instruction: "Pick the correct article.",
              prompt: "___ Ei (egg)",
              options: ["das", "der", "die"],
              correctIndex: 0,
              explainCorrect: "Ei is neuter: das Ei.",
              explainWrong: "Ei is neuter, so it takes das.",
            },
          },
        ],
      },
    ],
  },
  {
    id: "case-detective",
    title: "Case Detective",
    emoji: "🕵️",
    description: "Spot the case: nominative, accusative, or dative? Be the grammar detective.",
    category: "grammar",
    levels: [
      {
        id: "case-detective-1",
        title: "Level 1: Nominative or accusative?",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "cd-1",
              type: "multiple-choice",
              title: "Which case?",
              instruction: "What case is the highlighted word in?",
              prompt: "Der Mann schläft. (the man)",
              options: ["Nominativ", "Akkusativ", "Dativ"],
              correctIndex: 0,
              explainCorrect: "The man is the subject doing the sleeping: nominative.",
              explainWrong: "The subject of the sentence is in the nominative.",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "cd-2",
              type: "multiple-choice",
              title: "Which case?",
              instruction: "What case is the highlighted word in?",
              prompt: "Ich sehe den Mann. (the man)",
              options: ["Akkusativ", "Nominativ", "Dativ"],
              correctIndex: 0,
              explainCorrect: "The man is the direct object of sehen: accusative.",
              explainWrong: "The direct object after sehen is in the accusative: den Mann.",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "cd-3",
              type: "multiple-choice",
              title: "Which case?",
              instruction: "What case is the highlighted word in?",
              prompt: "Ich helfe dem Mann. (the man)",
              options: ["Dativ", "Akkusativ", "Nominativ"],
              correctIndex: 0,
              explainCorrect: "helfen takes the dative: dem Mann.",
              explainWrong: "helfen always takes the dative: dem Mann.",
            },
          },
        ],
      },
      {
        id: "case-detective-2",
        title: "Level 2: Choose the form",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "cd-4",
              type: "multiple-choice",
              title: "Accusative or dative?",
              instruction: "Choose the correct form.",
              prompt: "Ich gebe ___ Kind einen Apfel.",
              options: ["dem", "den", "der"],
              correctIndex: 0,
              explainCorrect: "geben takes the dative receiver: dem Kind.",
              explainWrong: "The receiver of geben is dative: dem Kind.",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "cd-5",
              type: "multiple-choice",
              title: "Accusative or dative?",
              instruction: "Choose the correct form.",
              prompt: "Ich sehe ___ Mann.",
              options: ["den", "dem", "der"],
              correctIndex: 0,
              explainCorrect: "sehen takes the accusative: den Mann.",
              explainWrong: "The direct object of sehen is accusative: den Mann.",
            },
          },
        ],
      },
      {
        id: "case-detective-3",
        title: "Level 3: Preposition detective",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "cd-6",
              type: "multiple-choice",
              title: "After the preposition",
              instruction: "Choose the correct form after the preposition.",
              prompt: "Ich fahre mit ___ Auto.",
              options: ["dem", "das", "den"],
              correctIndex: 0,
              explainCorrect: "mit always takes the dative: mit dem Auto.",
              explainWrong: "mit takes the dative: mit dem Auto.",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "cd-7",
              type: "multiple-choice",
              title: "Wo or wohin?",
              instruction: "Choose the correct form.",
              prompt: "Die Lampe ist auf ___ Tisch. (position)",
              options: ["dem", "den", "das"],
              correctIndex: 0,
              explainCorrect: "Wo? position takes the dative: auf dem Tisch.",
              explainWrong: "Position (wo?) takes the dative: auf dem Tisch.",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "cd-8",
              type: "multiple-choice",
              title: "Wo or wohin?",
              instruction: "Choose the correct form.",
              prompt: "Ich lege das Buch auf ___ Tisch. (direction)",
              options: ["den", "dem", "der"],
              correctIndex: 0,
              explainCorrect: "Wohin? direction takes the accusative: auf den Tisch.",
              explainWrong: "Direction (wohin?) takes the accusative: auf den Tisch.",
            },
          },
        ],
      },
    ],
  },
  {
    id: "declension-builder",
    title: "Declension Builder",
    emoji: "🏗️",
    description: "Build the correct article and adjective forms across the cases.",
    category: "grammar",
    levels: [
      {
        id: "declension-builder-1",
        title: "Level 1: Articles in the accusative",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "db-1",
              type: "fill-blank",
              title: "The accusative article",
              instruction: "Type the correct article.",
              sentence: "Ich sehe ___ Mann. (the, acc.)",
              blanks: [{ answers: ["den"], hint: "masculine accusative" }],
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "db-2",
              type: "fill-blank",
              title: "The accusative article",
              instruction: "Type the correct article.",
              sentence: "Ich kaufe ___ Apfel. (a, acc.)",
              blanks: [{ answers: ["einen"], hint: "masculine accusative of ein" }],
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "db-3",
              type: "fill-blank",
              title: "The accusative article",
              instruction: "Type the correct article.",
              sentence: "Sie hat ___ Bruder. (a, acc.)",
              blanks: [{ answers: ["einen"], hint: "masculine accusative" }],
            },
          },
        ],
      },
      {
        id: "declension-builder-2",
        title: "Level 2: Articles in the dative",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "db-4",
              type: "fill-blank",
              title: "The dative article",
              instruction: "Type the correct article.",
              sentence: "Ich helfe ___ Mann. (the, dat.)",
              blanks: [{ answers: ["dem"], hint: "masculine dative" }],
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "db-5",
              type: "fill-blank",
              title: "The dative article",
              instruction: "Type the correct article.",
              sentence: "Ich danke ___ Frau. (the, dat.)",
              blanks: [{ answers: ["der"], hint: "feminine dative" }],
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "db-6",
              type: "fill-blank",
              title: "The dative article",
              instruction: "Type the correct article.",
              sentence: "Das Buch gehört ___ Kind. (the, dat.)",
              blanks: [{ answers: ["dem"], hint: "neuter dative" }],
            },
          },
        ],
      },
      {
        id: "declension-builder-3",
        title: "Level 3: Adjective endings",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "db-7",
              type: "fill-blank",
              title: "Adjective endings",
              instruction: "Type the correct ending.",
              sentence: "ein ___ Haus (new, neuter)",
              blanks: [{ answers: ["neues"], hint: "neuter: -es" }],
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "db-8",
              type: "fill-blank",
              title: "Adjective endings",
              instruction: "Type the correct ending.",
              sentence: "eine ___ Lampe (new, feminine)",
              blanks: [{ answers: ["neue"], hint: "feminine: -e" }],
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "db-9",
              type: "fill-blank",
              title: "Adjective endings",
              instruction: "Type the correct ending.",
              sentence: "ein ___ Tisch (new, masculine)",
              blanks: [{ answers: ["neuer"], hint: "masculine: -er" }],
            },
          },
        ],
      },
    ],
  },
  {
    id: "sentence-fixer",
    title: "Sentence Fixer",
    emoji: "🔧",
    description: "The words are scrambled. Put them back in the right order.",
    category: "grammar",
    levels: [
      {
        id: "sentence-fixer-1",
        title: "Level 1: Simple sentences",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "sf-1",
              type: "word-order",
              title: "Fix the sentence",
              instruction: "Build the sentence: I am learning German.",
              chunks: ["Ich", "lerne", "Deutsch."],
              explainCorrect: "Subject, verb, object: the classic order.",
              explainWrong: "The verb follows the subject: Ich lerne Deutsch.",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "sf-2",
              type: "word-order",
              title: "Fix the sentence",
              instruction: "Build the sentence: The man works today.",
              chunks: ["Der", "Mann", "arbeitet", "heute."],
              explainCorrect: "The verb stays in second position.",
              explainWrong: "The verb is second: Der Mann arbeitet heute.",
            },
          },
        ],
      },
      {
        id: "sentence-fixer-2",
        title: "Level 2: With adverbs",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "sf-3",
              type: "word-order",
              title: "Fix the sentence",
              instruction: "Build the sentence: I am going to Berlin by train today.",
              chunks: ["Ich", "fahre", "heute", "mit", "dem", "Zug", "nach", "Berlin."],
              explainCorrect: "Time, manner, place: heute, mit dem Zug, nach Berlin.",
              explainWrong: "The order is time, manner, place: heute, mit dem Zug, nach Berlin.",
            },
          },
        ],
      },
      {
        id: "sentence-fixer-3",
        title: "Level 3: weil and denn",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "sf-4",
              type: "word-order",
              title: "Fix the sentence",
              instruction: "Build the sentence: I stay home because it is raining.",
              chunks: ["Ich", "bleibe", "zu", "Hause,", "weil", "es", "regnet."],
              explainCorrect: "After weil the verb goes to the end.",
              explainWrong: "weil sends the verb to the end: weil es regnet.",
            },
          },
        ],
      },
    ],
  },
  {
    id: "repeat-after-me",
    title: "Repeat After Me",
    emoji: "🗣️",
    description: "Listen to the German, say it aloud, then reveal the meaning.",
    category: "speaking",
    levels: [
      {
        id: "repeat-after-me-1",
        title: "Level 1: Greetings",
        rounds: [
          {
            kind: "repeat",
            title: "Greetings",
            instruction: "Listen, repeat aloud, then check the meaning.",
            phrases: ["Guten Morgen!", "Guten Tag!", "Guten Abend!", "Auf Wiedersehen!", "Bis bald!"],
          },
        ],
      },
      {
        id: "repeat-after-me-2",
        title: "Level 2: Small talk",
        rounds: [
          {
            kind: "repeat",
            title: "Small talk",
            instruction: "Listen, repeat aloud, then check the meaning.",
            phrases: ["Wie geht es dir?", "Mir geht es gut.", "Und dir?", "Bis morgen!", "Schönen Tag noch!"],
          },
        ],
      },
      {
        id: "repeat-after-me-3",
        title: "Level 3: Daily phrases",
        rounds: [
          {
            kind: "repeat",
            title: "Daily phrases",
            instruction: "Listen, repeat aloud, then check the meaning.",
            phrases: ["Ich lerne Deutsch.", "Ich wohne in Berlin.", "Ich arbeite heute.", "Wir essen jetzt.", "Kommst du mit?"],
          },
        ],
      },
    ],
  },
  {
    id: "pronunciation-choice",
    title: "Pronunciation Choice",
    emoji: "🔊",
    description: "Listen and choose the word you heard. Train your ear for German sounds.",
    category: "listening",
    levels: [
      {
        id: "pronunciation-choice-1",
        title: "Level 1: Similar words",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "pc-1",
              type: "listening",
              title: "What did you hear?",
              instruction: "Play the audio and pick the word you heard.",
              prompt: "der Mann",
              options: ["der Mann", "der Name", "die Manne"],
              correctIndex: 0,
              explainCorrect: "You heard Mann with the clear a.",
              explainWrong: "The word spoken was der Mann.",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "pc-2",
              type: "listening",
              title: "What did you hear?",
              instruction: "Play the audio and pick the word you heard.",
              prompt: "der Tisch",
              options: ["der Tisch", "der Fisch", "die Tische"],
              correctIndex: 0,
              explainCorrect: "You heard Tisch, the table.",
              explainWrong: "The word spoken was der Tisch.",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "pc-3",
              type: "listening",
              title: "What did you hear?",
              instruction: "Play the audio and pick the word you heard.",
              prompt: "der Käse",
              options: ["der Käse", "die Kasse", "der Kuss"],
              correctIndex: 0,
              explainCorrect: "You heard Käse with the long ä.",
              explainWrong: "The word spoken was der Käse.",
            },
          },
        ],
      },
      {
        id: "pronunciation-choice-2",
        title: "Level 2: Minimal pairs",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "pc-4",
              type: "listening",
              title: "What did you hear?",
              instruction: "Play the audio and pick the word you heard.",
              prompt: "gut",
              options: ["gut", "gut?"],
              correctIndex: 0,
              explainCorrect: "You heard the adjective gut.",
              explainWrong: "The word spoken was gut.",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "pc-5",
              type: "listening",
              title: "What did you hear?",
              instruction: "Play the audio and pick the word you heard.",
              prompt: "der Hund",
              options: ["der Hund", "die Hand", "das Haus"],
              correctIndex: 0,
              explainCorrect: "You heard Hund, the dog.",
              explainWrong: "The word spoken was der Hund.",
            },
          },
        ],
      },
      {
        id: "pronunciation-choice-3",
        title: "Level 3: Phrases",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "pc-6",
              type: "listening",
              title: "What did you hear?",
              instruction: "Play the audio and pick the phrase you heard.",
              prompt: "Wie geht es dir?",
              options: ["Wie geht es dir?", "Wie heißt du?", "Wo wohnst du?"],
              correctIndex: 0,
              explainCorrect: "You heard the small talk question.",
              explainWrong: "The phrase spoken was Wie geht es dir?",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "pc-7",
              type: "listening",
              title: "What did you hear?",
              instruction: "Play the audio and pick the phrase you heard.",
              prompt: "Ich möchte einen Kaffee.",
              options: ["Ich möchte einen Kaffee.", "Ich möchte einen Tee.", "Ich möchte ein Bier."],
              correctIndex: 0,
              explainCorrect: "You heard the coffee order.",
              explainWrong: "The phrase spoken was the coffee order.",
            },
          },
        ],
      },
    ],
  },
  {
    id: "listening-games",
    title: "Listening Games",
    emoji: "🎧",
    description: "Listen to spoken German and understand what is said.",
    category: "listening",
    levels: [
      {
        id: "listening-games-1",
        title: "Level 1: Words",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "lg-1",
              type: "listening",
              title: "What did you hear?",
              instruction: "Play the audio and pick the word you heard.",
              prompt: "die Frau",
              options: ["die Frau", "der Mann", "das Kind"],
              correctIndex: 0,
              explainCorrect: "You heard Frau.",
              explainWrong: "The word spoken was die Frau.",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "lg-2",
              type: "listening",
              title: "What did you hear?",
              instruction: "Play the audio and pick the word you heard.",
              prompt: "das Wasser",
              options: ["das Wasser", "das Brot", "der Kaffee"],
              correctIndex: 0,
              explainCorrect: "You heard Wasser.",
              explainWrong: "The word spoken was das Wasser.",
            },
          },
        ],
      },
      {
        id: "listening-games-2",
        title: "Level 2: Sentences",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "lg-3",
              type: "listening",
              title: "What did you hear?",
              instruction: "Play the audio and pick the sentence you heard.",
              prompt: "Ich wohne in Berlin.",
              options: ["Ich wohne in Berlin.", "Ich wohne in Hamburg.", "Ich lerne in Berlin."],
              correctIndex: 0,
              explainCorrect: "You heard the Berlin sentence.",
              explainWrong: "The sentence spoken was Ich wohne in Berlin.",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "lg-4",
              type: "listening",
              title: "What did you hear?",
              instruction: "Play the audio and pick the sentence you heard.",
              prompt: "Der Zug hat Verspätung.",
              options: ["Der Zug hat Verspätung.", "Der Zug kommt pünktlich.", "Der Bus hat Verspätung."],
              correctIndex: 0,
              explainCorrect: "You heard the train delay sentence.",
              explainWrong: "The sentence spoken was about the train delay.",
            },
          },
        ],
      },
      {
        id: "listening-games-3",
        title: "Level 3: Numbers",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "lg-5",
              type: "listening",
              title: "What number did you hear?",
              instruction: "Play the audio and pick the number you heard.",
              prompt: "drei",
              options: ["drei", "dreißig", "dreizehn"],
              correctIndex: 0,
              explainCorrect: "You heard drei, the number 3.",
              explainWrong: "The number spoken was drei (3).",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "lg-6",
              type: "listening",
              title: "What number did you hear?",
              instruction: "Play the audio and pick the number you heard.",
              prompt: "vierundzwanzig",
              options: ["vierundzwanzig", "vierzig", "vierzehn"],
              correctIndex: 0,
              explainCorrect: "You heard vierundzwanzig (24).",
              explainWrong: "The number spoken was vierundzwanzig (24).",
            },
          },
        ],
      },
    ],
  },
  {
    id: "listen-and-arrange",
    title: "Listen and Arrange",
    emoji: "🧩",
    description: "Listen to the sentence, then rebuild it from the word tiles.",
    category: "listening",
    levels: [
      {
        id: "listen-and-arrange-1",
        title: "Level 1: Short sentences",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "la-1",
              type: "word-order",
              title: "Rebuild the sentence",
              instruction: "Listen to the audio, then build the sentence.",
              chunks: ["Ich", "lerne", "Deutsch."],
              explainCorrect: "Ich lerne Deutsch.",
              explainWrong: "The correct sentence is Ich lerne Deutsch.",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "la-2",
              type: "word-order",
              title: "Rebuild the sentence",
              instruction: "Listen to the audio, then build the sentence.",
              chunks: ["Wir", "fahren", "nach", "Berlin."],
              explainCorrect: "Wir fahren nach Berlin.",
              explainWrong: "The correct sentence is Wir fahren nach Berlin.",
            },
          },
        ],
      },
      {
        id: "listen-and-arrange-2",
        title: "Level 2: With details",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "la-3",
              type: "word-order",
              title: "Rebuild the sentence",
              instruction: "Listen to the audio, then build the sentence.",
              chunks: ["Er", "arbeitet", "heute", "im", "Büro."],
              explainCorrect: "Er arbeitet heute im Büro.",
              explainWrong: "The correct sentence is Er arbeitet heute im Büro.",
            },
          },
        ],
      },
      {
        id: "listen-and-arrange-3",
        title: "Level 3: Questions",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "la-4",
              type: "word-order",
              title: "Rebuild the question",
              instruction: "Listen to the audio, then build the question.",
              chunks: ["Kommst", "du", "mit?"],
              explainCorrect: "Kommst du mit?",
              explainWrong: "The question is Kommst du mit?",
            },
          },
        ],
      },
    ],
  },
  {
    id: "missing-word",
    title: "Missing Word",
    emoji: "✏️",
    description: "Complete the sentence with the missing word.",
    category: "grammar",
    levels: [
      {
        id: "missing-word-1",
        title: "Level 1: Verbs",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "mw-1",
              type: "fill-blank",
              title: "The missing verb",
              instruction: "Type the correct verb form.",
              sentence: "Ich ___ aus Berlin. (come)",
              blanks: [{ answers: ["komme"], hint: "kommen, ich-form" }],
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "mw-2",
              type: "fill-blank",
              title: "The missing verb",
              instruction: "Type the correct verb form.",
              sentence: "Du ___ Deutsch. (learn)",
              blanks: [{ answers: ["lernst"], hint: "lernen, du-form" }],
            },
          },
        ],
      },
      {
        id: "missing-word-2",
        title: "Level 2: Articles",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "mw-3",
              type: "fill-blank",
              title: "The missing article",
              instruction: "Type the correct article.",
              sentence: "___ Sonne scheint. (the)",
              blanks: [{ answers: ["Die"], hint: "Sonne is feminine" }],
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "mw-4",
              type: "fill-blank",
              title: "The missing article",
              instruction: "Type the correct article.",
              sentence: "Ich möchte ___ Kaffee. (a)",
              blanks: [{ answers: ["einen"], hint: "Kaffee is masculine, accusative" }],
            },
          },
        ],
      },
      {
        id: "missing-word-3",
        title: "Level 3: Prepositions",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "mw-5",
              type: "fill-blank",
              title: "The missing preposition",
              instruction: "Type the correct preposition.",
              sentence: "Ich fahre ___ dem Zug. (by)",
              blanks: [{ answers: ["mit"], hint: "travel by vehicle" }],
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "mw-6",
              type: "fill-blank",
              title: "The missing preposition",
              instruction: "Type the correct preposition.",
              sentence: "Das Geschenk ist ___ dich. (for)",
              blanks: [{ answers: ["für"], hint: "for + accusative" }],
            },
          },
        ],
      },
    ],
  },
  {
    id: "sentence-scrabble",
    title: "Sentence Scrabble",
    emoji: "🔤",
    description: "Move the tiles to build complete sentences under the wire.",
    category: "grammar",
    levels: [
      {
        id: "sentence-scrabble-1",
        title: "Level 1: Two-part sentences",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "ss-1",
              type: "word-order",
              title: "Build the sentence",
              instruction: "Build the sentence: I am hungry.",
              chunks: ["Ich", "habe", "Hunger."],
              explainCorrect: "Hunger is a noun with haben.",
              explainWrong: "The phrase is Ich habe Hunger.",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "ss-2",
              type: "word-order",
              title: "Build the sentence",
              instruction: "Build the sentence: She is thirsty.",
              chunks: ["Sie", "hat", "Durst."],
              explainCorrect: "Durst is a noun with haben.",
              explainWrong: "The phrase is Sie hat Durst.",
            },
          },
        ],
      },
      {
        id: "sentence-scrabble-2",
        title: "Level 2: Three-part sentences",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "ss-3",
              type: "word-order",
              title: "Build the sentence",
              instruction: "Build the sentence: We are going to the cinema today.",
              chunks: ["Wir", "gehen", "heute", "ins", "Kino."],
              explainCorrect: "ins = in + das.",
              explainWrong: "The order is subject, verb, time, place.",
            },
          },
        ],
      },
      {
        id: "sentence-scrabble-3",
        title: "Level 3: Complex sentences",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "ss-4",
              type: "word-order",
              title: "Build the sentence",
              instruction: "Build the sentence: I like coffee, but I drink tea.",
              chunks: ["Ich", "mag", "Kaffee,", "aber", "ich", "trinke", "Tee."],
              explainCorrect: "aber keeps the normal order.",
              explainWrong: "aber keeps the verb in second position.",
            },
          },
        ],
      },
    ],
  },
  {
    id: "time-word-rush",
    title: "Time Word Rush",
    emoji: "⏱️",
    description: "Beat the clock. Answer as many as you can before time runs out.",
    category: "mixed",
    levels: [
      {
        id: "time-word-rush-1",
        title: "Level 1: Easy",
        rounds: [
          {
            kind: "rush",
            title: "Beat the clock",
            instruction: "Answer each question before the timer runs out.",
            timeLimit: 30,
            questions: [
              { prompt: "___ heißt du?", options: ["Wie", "Wo", "Was"], correctIndex: 0 },
              { prompt: "the mother = ___", options: ["die Mutter", "der Vater", "das Kind"], correctIndex: 0 },
              { prompt: "Guten Morgen means ___", options: ["good morning", "good night", "goodbye"], correctIndex: 0 },
              { prompt: "___ Tisch (the table)", options: ["der", "die", "das"], correctIndex: 0 },
              { prompt: "one = ___", options: ["eins", "zwei", "drei"], correctIndex: 0 },
            ],
          },
        ],
      },
      {
        id: "time-word-rush-2",
        title: "Level 2: Medium",
        rounds: [
          {
            kind: "rush",
            title: "Beat the clock",
            instruction: "Answer each question before the timer runs out.",
            timeLimit: 40,
            questions: [
              { prompt: "Ich ___ Deutsch. (learn)", options: ["lerne", "lernst", "lernt"], correctIndex: 0 },
              { prompt: "the bread = ___", options: ["das Brot", "der Käse", "das Ei"], correctIndex: 0 },
              { prompt: "___ Morgen (in the morning)", options: ["Am", "Im", "Um"], correctIndex: 0 },
              { prompt: "you (formal) = ___", options: ["Sie", "du", "ihr"], correctIndex: 0 },
              { prompt: "the station = ___", options: ["der Bahnhof", "das Rathaus", "die Kirche"], correctIndex: 0 },
            ],
          },
        ],
      },
      {
        id: "time-word-rush-3",
        title: "Level 3: Hard",
        rounds: [
          {
            kind: "rush",
            title: "Beat the clock",
            instruction: "Answer each question before the timer runs out.",
            timeLimit: 50,
            questions: [
              { prompt: "Ich fahre mit ___ Auto.", options: ["dem", "den", "das"], correctIndex: 0 },
              { prompt: "the key = ___", options: ["der Schlüssel", "der Spiegel", "der Teppich"], correctIndex: 0 },
              { prompt: "___ regnet. (It is raining)", options: ["Es", "Er", "Sie"], correctIndex: 0 },
              { prompt: "Wir ___ nach Berlin gefahren.", options: ["sind", "haben", "sein"], correctIndex: 0 },
              { prompt: "I would like = ___", options: ["ich möchte", "ich muss", "ich kann"], correctIndex: 0 },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "odd-one-out",
    title: "Odd One Out",
    emoji: "🎲",
    description: "Four words, one does not fit. Find the intruder.",
    category: "vocabulary",
    levels: [
      {
        id: "odd-one-out-1",
        title: "Level 1: Food",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "oo-1",
              type: "multiple-choice",
              title: "Find the odd one",
              instruction: "Which word does not belong?",
              prompt: "das Brot, der Käse, die Milch, der Zug",
              options: ["der Zug", "das Brot", "der Käse"],
              correctIndex: 0,
              explainCorrect: "Zug is transport; the others are food.",
              explainWrong: "Zug is the intruder: it is transport, not food.",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "oo-2",
              type: "multiple-choice",
              title: "Find the odd one",
              instruction: "Which word does not belong?",
              prompt: "der Apfel, die Banane, der Tisch, die Orange",
              options: ["der Tisch", "der Apfel", "die Banane"],
              correctIndex: 0,
              explainCorrect: "Tisch is furniture; the others are fruit.",
              explainWrong: "Tisch is the intruder: it is furniture, not fruit.",
            },
          },
        ],
      },
      {
        id: "odd-one-out-2",
        title: "Level 2: People and places",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "oo-3",
              type: "multiple-choice",
              title: "Find the odd one",
              instruction: "Which word does not belong?",
              prompt: "der Lehrer, die Ärztin, der Bahnhof, der Kellner",
              options: ["der Bahnhof", "der Lehrer", "die Ärztin"],
              correctIndex: 0,
              explainCorrect: "Bahnhof is a place; the others are people.",
              explainWrong: "Bahnhof is the intruder: it is a place.",
            },
          },
        ],
      },
      {
        id: "odd-one-out-3",
        title: "Level 3: Verbs",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "oo-4",
              type: "multiple-choice",
              title: "Find the odd one",
              instruction: "Which word does not belong?",
              prompt: "essen, trinken, schlafen, der Stuhl",
              options: ["der Stuhl", "essen", "trinken"],
              correctIndex: 0,
              explainCorrect: "Stuhl is a noun; the others are verbs.",
              explainWrong: "Stuhl is the intruder: it is a noun, not a verb.",
            },
          },
        ],
      },
    ],
  },
  {
    id: "story-time",
    title: "Story Time",
    emoji: "📖",
    description: "Choose the right responses to complete the story.",
    category: "mixed",
    levels: [
      {
        id: "story-time-1",
        title: "Level 1: Anna's morning",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "st-1",
              type: "multiple-choice",
              title: "The story begins",
              instruction: "Choose the correct sentence to continue the story.",
              prompt: "Anna wakes up. She says to her mother:",
              options: ["Guten Morgen!", "Gute Nacht!", "Auf Wiedersehen!"],
              correctIndex: 0,
              explainCorrect: "In the morning she greets with Guten Morgen.",
              explainWrong: "Morning greetings are Guten Morgen.",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "st-2",
              type: "multiple-choice",
              title: "The story continues",
              instruction: "Choose what Anna says next.",
              prompt: "Her mother asks: Wie geht es dir? Anna answers:",
              options: ["Mir geht es gut, danke!", "Wie heißt du?", "Wo wohnst du?"],
              correctIndex: 0,
              explainCorrect: "The small talk answer is Mir geht es gut.",
              explainWrong: "The answer to Wie geht es dir? is Mir geht es gut.",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "st-3",
              type: "multiple-choice",
              title: "The story ends",
              instruction: "Choose how Anna leaves for school.",
              prompt: "Anna goes to school. She says:",
              options: ["Tschüss, bis später!", "Guten Morgen!", "Gute Nacht!"],
              correctIndex: 0,
              explainCorrect: "Leaving friends takes Tschüss, bis später.",
              explainWrong: "Leaving is Tschüss, bis später.",
            },
          },
        ],
      },
      {
        id: "story-time-2",
        title: "Level 2: Paul at the café",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "st-4",
              type: "multiple-choice",
              title: "At the café",
              instruction: "Choose what Paul says to the waiter.",
              prompt: "Paul wants a coffee. He says:",
              options: ["Ich möchte einen Kaffee, bitte.", "Ich bin ein Kaffee.", "Die Rechnung, bitte!"],
              correctIndex: 0,
              explainCorrect: "Ordering uses möchten: Ich möchte einen Kaffee.",
              explainWrong: "Ordering uses möchten with the accusative.",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "st-5",
              type: "multiple-choice",
              title: "The waiter replies",
              instruction: "Choose the waiter's reply.",
              prompt: "The waiter brings the coffee and says:",
              options: ["Guten Appetit!", "Gute Nacht!", "Auf Wiedersehen!"],
              correctIndex: 0,
              explainCorrect: "The waiter wishes a good appetite.",
              explainWrong: "Food arrives with Guten Appetit.",
            },
          },
        ],
      },
      {
        id: "story-time-3",
        title: "Level 3: The train station",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "st-6",
              type: "multiple-choice",
              title: "At the station",
              instruction: "Choose the correct question.",
              prompt: "Lena asks about the train. She says:",
              options: ["Von welchem Gleis fährt der Zug ab?", "Was kostet das Brot?", "Wie ist das Wetter?"],
              correctIndex: 0,
              explainCorrect: "The platform question: Von welchem Gleis?",
              explainWrong: "Platform questions use Von welchem Gleis?",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "st-7",
              type: "multiple-choice",
              title: "The answer",
              instruction: "Choose the station announcement.",
              prompt: "The answer is:",
              options: ["Gleis 5.", "Fünf Euro.", "Es regnet."],
              correctIndex: 0,
              explainCorrect: "The platform is called Gleis 5.",
              explainWrong: "The platform answer is Gleis 5.",
            },
          },
        ],
      },
    ],
  },
  {
    id: "choose-the-response",
    title: "Choose the Response",
    emoji: "💬",
    description: "Someone speaks. Choose the right German response.",
    category: "speaking",
    levels: [
      {
        id: "choose-the-response-1",
        title: "Level 1: Greetings",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "cr-1",
              type: "multiple-choice",
              title: "Choose the response",
              instruction: "How do you answer?",
              prompt: "Guten Morgen!",
              options: ["Guten Morgen!", "Danke schön!", "Gute Nacht!"],
              correctIndex: 0,
              explainCorrect: "Greetings are answered with the same greeting.",
              explainWrong: "You answer a greeting with the same greeting.",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "cr-2",
              type: "multiple-choice",
              title: "Choose the response",
              instruction: "How do you answer?",
              prompt: "Wie geht es dir?",
              options: ["Mir geht es gut.", "Ich bin Anna.", "Auf Wiedersehen!"],
              correctIndex: 0,
              explainCorrect: "The small talk answer: Mir geht es gut.",
              explainWrong: "Wie geht es dir? is answered with Mir geht es gut.",
            },
          },
        ],
      },
      {
        id: "choose-the-response-2",
        title: "Level 2: In the shop",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "cr-3",
              type: "multiple-choice",
              title: "Choose the response",
              instruction: "How do you answer?",
              prompt: "Zahlen Sie bar oder mit Karte?",
              options: ["Mit Karte, bitte.", "Guten Appetit!", "Gleis 5."],
              correctIndex: 0,
              explainCorrect: "Payment answers: Mit Karte, bitte.",
              explainWrong: "The payment question is answered with the method.",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "cr-4",
              type: "multiple-choice",
              title: "Choose the response",
              instruction: "How do you answer?",
              prompt: "Danke schön!",
              options: ["Bitte schön!", "Auf Wiedersehen!", "Guten Morgen!"],
              correctIndex: 0,
              explainCorrect: "Thanks are answered with Bitte schön.",
              explainWrong: "You answer thanks with Bitte schön.",
            },
          },
        ],
      },
      {
        id: "choose-the-response-3",
        title: "Level 3: Invitations",
        rounds: [
          {
            kind: "exercise",
            exercise: {
              id: "cr-5",
              type: "multiple-choice",
              title: "Choose the response",
              instruction: "How do you answer?",
              prompt: "Kommst du mit ins Kino?",
              options: ["Ja, gern!", "Nein, ich bin müde."],
              correctIndex: 0,
              explainCorrect: "Accepting: Ja, gern!",
              explainWrong: "The natural acceptance is Ja, gern!",
            },
          },
          {
            kind: "exercise",
            exercise: {
              id: "cr-6",
              type: "multiple-choice",
              title: "Choose the response",
              instruction: "How do you answer?",
              prompt: "Hast du am Samstag Zeit?",
              options: ["Nein, ich habe keine Zeit.", "Danke schön!", "Guten Appetit!"],
              correctIndex: 0,
              explainCorrect: "The polite decline names the reason.",
              explainWrong: "Declining politely gives a reason: keine Zeit.",
            },
          },
        ],
      },
    ],
  },
];