import type { Game } from "./schema";

export const artikelDropGame: Game = {
  id: "artikel-drop",
  title: "Artikel Drop",
  emoji: "🪂",
  description:
    "Catch falling German nouns by sending them to the right gate (der, die, or das) before they land. Fast arcade-style artikel practice that speeds up as you play.",
  category: "grammar",
  tags: ["A1"],
  levels: [
    {
      id: "artikel-drop-1",
      title: "Level 1: Everyday nouns",
      rounds: [
        {
          kind: "drop",
          title: "Artikel Drop: everyday nouns",
          instruction: "Send each falling noun to der, die or das before it lands.",
          fallMs: 4500,
          gates: [
            { id: "der", label: "der" },
            { id: "die", label: "die" },
            { id: "das", label: "das" },
          ],
          items: [
            { text: "Tisch", gateId: "der" },
            { text: "Lampe", gateId: "die" },
            { text: "Bett", gateId: "das" },
            { text: "Stuhl", gateId: "der" },
            { text: "Uhr", gateId: "die" },
            { text: "Buch", gateId: "das" },
            { text: "Zug", gateId: "der" },
            { text: "Straße", gateId: "die" },
            { text: "Auto", gateId: "das" },
            { text: "Apfel", gateId: "der" },
            { text: "Milch", gateId: "die" },
            { text: "Ei", gateId: "das" },
            { text: "Kaffee", gateId: "der" },
            { text: "Pizza", gateId: "die" },
            { text: "Brot", gateId: "das" },
            { text: "Hund", gateId: "der" },
            { text: "Katze", gateId: "die" },
            { text: "Pferd", gateId: "das" },
          ],
        },
      ],
    },
    {
      id: "artikel-drop-2",
      title: "Level 2: Places and things",
      rounds: [
        {
          kind: "drop",
          title: "Artikel Drop: places and things",
          instruction: "Send each falling noun to der, die or das before it lands.",
          fallMs: 4000,
          gates: [
            { id: "der", label: "der" },
            { id: "die", label: "die" },
            { id: "das", label: "das" },
          ],
          items: [
            { text: "Bahnhof", gateId: "der" },
            { text: "Apotheke", gateId: "die" },
            { text: "Krankenhaus", gateId: "das" },
            { text: "Supermarkt", gateId: "der" },
            { text: "Kirche", gateId: "die" },
            { text: "Museum", gateId: "das" },
            { text: "Park", gateId: "der" },
            { text: "Schule", gateId: "die" },
            { text: "Hotel", gateId: "das" },
            { text: "Garten", gateId: "der" },
            { text: "Küche", gateId: "die" },
            { text: "Zimmer", gateId: "das" },
            { text: "Kühlschrank", gateId: "der" },
            { text: "Waschmaschine", gateId: "die" },
            { text: "Fenster", gateId: "das" },
          ],
        },
      ],
    },
    {
      id: "artikel-drop-3",
      title: "Level 3: Mixed",
      rounds: [
        {
          kind: "drop",
          title: "Artikel Drop: mixed nouns",
          instruction: "Send each falling noun to der, die or das before it lands.",
          fallMs: 3500,
          gates: [
            { id: "der", label: "der" },
            { id: "die", label: "die" },
            { id: "das", label: "das" },
          ],
          items: [
            { text: "Vogel", gateId: "der" },
            { text: "Maus", gateId: "die" },
            { text: "Schwein", gateId: "das" },
            { text: "Kuchen", gateId: "der" },
            { text: "Banane", gateId: "die" },
            { text: "Mädchen", gateId: "das" },
            { text: "Computer", gateId: "der" },
            { text: "Wohnung", gateId: "die" },
            { text: "Brötchen", gateId: "das" },
            { text: "Regen", gateId: "der" },
            { text: "Nacht", gateId: "die" },
            { text: "Meer", gateId: "das" },
            { text: "Berg", gateId: "der" },
            { text: "Blume", gateId: "die" },
            { text: "Licht", gateId: "das" },
          ],
        },
      ],
    },
  ],
};

export const nounRulesGame: Game = {
  id: "der-die-das-rules",
  title: "Der, Die, Das Rules",
  emoji: "📏",
  description:
    "Pick der, die, or das for each noun and learn the rule behind it, including suffixes like -ung and -chen plus meaning groups like days, months, and materials.",
  category: "grammar",
  tags: ["A1"],
  levels: [
    {
      id: "rules-1",
      title: "Level 1: Suffixes",
      rounds: [
        {
          kind: "exercise",
          exercise: {
            id: "rules-1a",
            type: "multiple-choice",
            title: "Suffix rules",
            instruction: "Choose the correct article.",
            prompt: "___ Wohnung",
            options: ["die", "der", "das"],
            correctIndex: 0,
            explain: "Nouns ending in -ung are always feminine: die Wohnung, die Zeitung, die Übung.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "rules-1b",
            type: "multiple-choice",
            title: "Suffix rules",
            instruction: "Choose the correct article.",
            prompt: "___ Mädchen",
            options: ["das", "die", "der"],
            correctIndex: 0,
            explain: "Nouns ending in -chen are always neuter: das Mädchen, das Brötchen, das Häuschen.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "rules-1c",
            type: "multiple-choice",
            title: "Suffix rules",
            instruction: "Choose the correct article.",
            prompt: "___ Zeitung",
            options: ["die", "das", "der"],
            correctIndex: 0,
            explain: "-ung is feminine: die Zeitung, die Wohnung, die Übung.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "rules-1d",
            type: "multiple-choice",
            title: "Suffix rules",
            instruction: "Choose the correct article.",
            prompt: "___ Brötchen",
            options: ["das", "der", "die"],
            correctIndex: 0,
            explain: "-chen is neuter: das Brötchen, das Mädchen.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "rules-1e",
            type: "multiple-choice",
            title: "Suffix rules",
            instruction: "Choose the correct article.",
            prompt: "___ Übung",
            options: ["die", "der", "das"],
            correctIndex: 0,
            explain: "-ung is feminine: die Übung, die Zeitung, die Wohnung.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "rules-1f",
            type: "multiple-choice",
            title: "Suffix rules",
            instruction: "Choose the correct article.",
            prompt: "___ Lehrer",
            options: ["der", "die", "das"],
            correctIndex: 0,
            explain: "Most nouns ending in -er are masculine: der Lehrer, der Computer, der Kühlschrank. Exceptions: die Mutter, die Schwester.",
          },
        },
      ],
    },
    {
      id: "rules-2",
      title: "Level 2: Meaning groups",
      rounds: [
        {
          kind: "exercise",
          exercise: {
            id: "rules-2a",
            type: "multiple-choice",
            title: "Meaning groups",
            instruction: "Choose the correct article.",
            prompt: "___ Montag",
            options: ["der", "die", "das"],
            correctIndex: 0,
            explain: "All days of the week are masculine: der Montag, der Dienstag, der Samstag.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "rules-2b",
            type: "multiple-choice",
            title: "Meaning groups",
            instruction: "Choose the correct article.",
            prompt: "___ Januar",
            options: ["der", "die", "das"],
            correctIndex: 0,
            explain: "All months are masculine: der Januar, der Mai, der Dezember.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "rules-2c",
            type: "multiple-choice",
            title: "Meaning groups",
            instruction: "Choose the correct article.",
            prompt: "___ Sommer",
            options: ["der", "die", "das"],
            correctIndex: 0,
            explain: "Seasons are masculine: der Sommer, der Winter, der Frühling, der Herbst.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "rules-2d",
            type: "multiple-choice",
            title: "Meaning groups",
            instruction: "Choose the correct article.",
            prompt: "___ Holz",
            options: ["das", "der", "die"],
            correctIndex: 0,
            explain: "Materials and metals are neuter: das Holz, das Glas, das Metall, das Papier.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "rules-2e",
            type: "multiple-choice",
            title: "Meaning groups",
            instruction: "Choose the correct article.",
            prompt: "___ Wasser",
            options: ["das", "der", "die"],
            correctIndex: 0,
            explain: "Materials and liquids are often neuter: das Wasser, das Bier, das Holz.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "rules-2f",
            type: "multiple-choice",
            title: "Meaning groups",
            instruction: "Choose the correct article.",
            prompt: "___ Samstag",
            options: ["der", "die", "das"],
            correctIndex: 0,
            explain: "All days of the week are masculine: der Samstag, der Montag, der Sonntag.",
          },
        },
      ],
    },
  ],
};

export const timeExpressionsGame: Game = {
  id: "time-expressions",
  title: "German Time Expressions",
  emoji: "🕐",
  description:
    "Fill in the correct time preposition (um, am, im, in der, or none) and learn the rule behind each answer with instant explanations.",
  category: "grammar",
  tags: ["A1", "A2"],
  levels: [
    {
      id: "time-expr-1",
      title: "Level 1: um, am, im",
      rounds: [
        {
          kind: "exercise",
          exercise: {
            id: "tex-1a",
            type: "multiple-choice",
            title: "Time prepositions",
            instruction: "Choose the missing time preposition.",
            prompt: "___ 8 Uhr",
            options: ["um", "am", "im"],
            correctIndex: 0,
            explain: "um is for clock times: um 8 Uhr, um halb drei.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "tex-1b",
            type: "multiple-choice",
            title: "Time prepositions",
            instruction: "Choose the missing time preposition.",
            prompt: "___ Montag",
            options: ["am", "um", "im"],
            correctIndex: 0,
            explain: "am is for days: am Montag, am Dienstag.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "tex-1c",
            type: "multiple-choice",
            title: "Time prepositions",
            instruction: "Choose the missing time preposition.",
            prompt: "___ Sommer",
            options: ["im", "am", "um"],
            correctIndex: 0,
            explain: "im is for seasons: im Sommer, im Winter.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "tex-1d",
            type: "multiple-choice",
            title: "Time prepositions",
            instruction: "Choose the missing time preposition.",
            prompt: "___ Januar",
            options: ["im", "am", "um"],
            correctIndex: 0,
            explain: "im is for months: im Januar, im Dezember.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "tex-1e",
            type: "multiple-choice",
            title: "Time prepositions",
            instruction: "Choose the missing time preposition.",
            prompt: "___ Morgen",
            options: ["am", "im", "um"],
            correctIndex: 0,
            explain: "am is for parts of the day: am Morgen, am Abend. Exception: in der Nacht.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "tex-1f",
            type: "multiple-choice",
            title: "Time prepositions",
            instruction: "Choose the missing time preposition.",
            prompt: "___ halb drei",
            options: ["um", "am", "im"],
            correctIndex: 0,
            explain: "um is for clock times: um halb drei, um viertel nach sieben.",
          },
        },
      ],
    },
    {
      id: "time-expr-2",
      title: "Level 2: Tricky cases",
      rounds: [
        {
          kind: "exercise",
          exercise: {
            id: "tex-2a",
            type: "multiple-choice",
            title: "Time prepositions",
            instruction: "Choose the missing time preposition.",
            prompt: "___ Nacht",
            options: ["in der", "am", "im"],
            correctIndex: 0,
            explain: "Nacht is the exception: in der Nacht, not am Nacht.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "tex-2b",
            type: "multiple-choice",
            title: "Time prepositions",
            instruction: "Choose the missing time preposition.",
            prompt: "___ Wochenende",
            options: ["am", "im", "um"],
            correctIndex: 0,
            explain: "am Wochenende is fixed: at the weekend.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "tex-2c",
            type: "multiple-choice",
            title: "Time prepositions",
            instruction: "Choose the missing time preposition.",
            prompt: "___ Jahr 2026",
            options: ["im", "am", "um"],
            correctIndex: 0,
            explain: "im is for years: im Jahr 2026.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "tex-2d",
            type: "multiple-choice",
            title: "Time prepositions",
            instruction: "Choose the missing time preposition.",
            prompt: "heute ___",
            options: ["— (nothing)", "am", "um"],
            correctIndex: 0,
            explain: "heute, morgen and gestern take no preposition at all.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "tex-2e",
            type: "multiple-choice",
            title: "Time prepositions",
            instruction: "Choose the missing time preposition.",
            prompt: "Ich lerne Deutsch ___ Abend.",
            options: ["am", "im", "um"],
            correctIndex: 0,
            explain: "am Abend: parts of the day take am.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "tex-2f",
            type: "multiple-choice",
            title: "Time prepositions",
            instruction: "Choose the missing time preposition.",
            prompt: "___ Dienstag",
            options: ["am", "im", "um"],
            correctIndex: 0,
            explain: "Days take am: am Dienstag.",
          },
        },
      ],
    },
  ],
};

export const dativPrepositionsGame: Game = {
  id: "dativ-prepositions",
  title: "Dativ Prepositions",
  emoji: "📍",
  description:
    "Fill in the correct preposition or article for Wohin?, Wo?, Woher? sentences. Learn Dativ with cities, buildings, shops, and more.",
  category: "grammar",
  tags: ["A1", "A2"],
  levels: [
    {
      id: "dativ-1",
      title: "Level 1: Cities and countries",
      rounds: [
        {
          kind: "exercise",
          exercise: {
            id: "dav-1a",
            type: "multiple-choice",
            title: "Woher? and Wohin?",
            instruction: "Choose the correct preposition.",
            prompt: "Ich komme ___ Nigeria.",
            options: ["aus", "nach", "in"],
            correctIndex: 0,
            explain: "aus + Dativ answers Woher?: where you come from. Ich komme aus Nigeria.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "dav-1b",
            type: "multiple-choice",
            title: "Woher? and Wohin?",
            instruction: "Choose the correct preposition.",
            prompt: "Ich fliege ___ Berlin.",
            options: ["nach", "aus", "zu"],
            correctIndex: 0,
            explain: "nach answers Wohin? with cities and countries without articles: nach Berlin, nach Deutschland.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "dav-1c",
            type: "multiple-choice",
            title: "Woher? and Wohin?",
            instruction: "Choose the correct preposition.",
            prompt: "Ich wohne ___ Berlin.",
            options: ["in", "nach", "aus"],
            correctIndex: 0,
            explain: "in + Dativ answers Wo?: where you are. Ich wohne in Berlin.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "dav-1d",
            type: "multiple-choice",
            title: "Woher? and Wohin?",
            instruction: "Choose the correct preposition.",
            prompt: "Sie kommt ___ der Schule.",
            options: ["aus", "nach", "zu"],
            correctIndex: 0,
            explain: "aus + Dativ: coming out of a place. Sie kommt aus der Schule.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "dav-1e",
            type: "multiple-choice",
            title: "Woher? and Wohin?",
            instruction: "Choose the correct preposition.",
            prompt: "Er fährt ___ dem Supermarkt.",
            options: ["zu", "nach", "aus"],
            correctIndex: 0,
            explain: "zu + Dativ: going to a place with an article. Er fährt zu dem Supermarkt.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "dav-1f",
            type: "multiple-choice",
            title: "Woher? and Wohin?",
            instruction: "Choose the correct preposition.",
            prompt: "Ich gehe ___ der Arbeit.",
            options: ["zu", "in", "aus"],
            correctIndex: 0,
            explain: "zu + Dativ: to a person or place. Ich gehe zu der Arbeit (zur Arbeit).",
          },
        },
      ],
    },
    {
      id: "dativ-2",
      title: "Level 2: Wo? and Wohin?",
      rounds: [
        {
          kind: "exercise",
          exercise: {
            id: "dav-2a",
            type: "multiple-choice",
            title: "Wo? and Wohin?",
            instruction: "Choose the correct preposition.",
            prompt: "Das Buch liegt ___ dem Tisch.",
            options: ["auf", "in", "zu"],
            correctIndex: 0,
            explain: "auf + Dativ answers Wo?: lying on the table. Das Buch liegt auf dem Tisch.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "dav-2b",
            type: "multiple-choice",
            title: "Wo? and Wohin?",
            instruction: "Choose the correct preposition.",
            prompt: "Ich lege das Buch ___ den Tisch.",
            options: ["auf", "in", "zu"],
            correctIndex: 0,
            explain: "auf + Akkusativ answers Wohin?: putting it onto the table. Ich lege das Buch auf den Tisch.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "dav-2c",
            type: "multiple-choice",
            title: "Wo? and Wohin?",
            instruction: "Choose the correct preposition.",
            prompt: "Wir gehen ___ das Kino.",
            options: ["in", "zu", "aus"],
            correctIndex: 0,
            explain: "in + Akkusativ answers Wohin? with buildings: in das Kino, in die Schule.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "dav-2d",
            type: "multiple-choice",
            title: "Wo? and Wohin?",
            instruction: "Choose the correct preposition.",
            prompt: "Sie ist ___ der Schule.",
            options: ["in", "nach", "zu"],
            correctIndex: 0,
            explain: "in + Dativ answers Wo?: inside the school.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "dav-2e",
            type: "multiple-choice",
            title: "Wo? and Wohin?",
            instruction: "Choose the correct preposition.",
            prompt: "Ich bin ___ Hause.",
            options: ["zu", "in", "bei"],
            correctIndex: 0,
            explain: "zu Hause is fixed: at home.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "dav-2f",
            type: "multiple-choice",
            title: "Wo? and Wohin?",
            instruction: "Choose the correct preposition.",
            prompt: "Er ist ___ der Arbeit.",
            options: ["bei", "zu", "in"],
            correctIndex: 0,
            explain: "bei + Dativ: at a workplace or person. Er ist bei der Arbeit.",
          },
        },
      ],
    },
  ],
};

export const imageNounGame: Game = {
  id: "guess-word-from-image",
  title: "Guess the Word from Image",
  emoji: "🐶",
  description:
    "Look at an image and pick the correct German noun with its artikel, across animals and food & drink categories.",
  category: "vocabulary",
  tags: ["A1"],
  levels: [
    {
      id: "image-1",
      title: "Level 1: Animals",
      rounds: [
        {
          kind: "exercise",
          exercise: {
            id: "img-1a",
            type: "multiple-choice",
            title: "Animals",
            instruction: "Look at the picture and choose the correct noun.",
            prompt: "🐶",
            options: ["der Hund", "die Katze", "das Pferd"],
            correctIndex: 0,
            explain: "🐶 ist der Hund.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "img-1b",
            type: "multiple-choice",
            title: "Animals",
            instruction: "Look at the picture and choose the correct noun.",
            prompt: "🐱",
            options: ["die Katze", "der Hund", "der Vogel"],
            correctIndex: 0,
            explain: "🐱 ist die Katze.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "img-1c",
            type: "multiple-choice",
            title: "Animals",
            instruction: "Look at the picture and choose the correct noun.",
            prompt: "🐴",
            options: ["das Pferd", "die Kuh", "das Schaf"],
            correctIndex: 0,
            explain: "🐴 ist das Pferd.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "img-1d",
            type: "multiple-choice",
            title: "Animals",
            instruction: "Look at the picture and choose the correct noun.",
            prompt: "🐟",
            options: ["der Fisch", "der Vogel", "das Schwein"],
            correctIndex: 0,
            explain: "🐟 ist der Fisch.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "img-1e",
            type: "multiple-choice",
            title: "Animals",
            instruction: "Look at the picture and choose the correct noun.",
            prompt: "🐭",
            options: ["die Maus", "die Katze", "die Kuh"],
            correctIndex: 0,
            explain: "🐭 ist die Maus.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "img-1f",
            type: "multiple-choice",
            title: "Animals",
            instruction: "Look at the picture and choose the correct noun.",
            prompt: "🐔",
            options: ["das Huhn", "der Hahn", "das Pferd"],
            correctIndex: 0,
            explain: "🐔 ist das Huhn.",
          },
        },
      ],
    },
    {
      id: "image-2",
      title: "Level 2: Food and drink",
      rounds: [
        {
          kind: "exercise",
          exercise: {
            id: "img-2a",
            type: "multiple-choice",
            title: "Food and drink",
            instruction: "Look at the picture and choose the correct noun.",
            prompt: "🍎",
            options: ["der Apfel", "die Banane", "die Birne"],
            correctIndex: 0,
            explain: "🍎 ist der Apfel.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "img-2b",
            type: "multiple-choice",
            title: "Food and drink",
            instruction: "Look at the picture and choose the correct noun.",
            prompt: "🍌",
            options: ["die Banane", "der Apfel", "die Traube"],
            correctIndex: 0,
            explain: "🍌 ist die Banane.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "img-2c",
            type: "multiple-choice",
            title: "Food and drink",
            instruction: "Look at the picture and choose the correct noun.",
            prompt: "🍞",
            options: ["das Brot", "der Kuchen", "der Käse"],
            correctIndex: 0,
            explain: "🍞 ist das Brot.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "img-2d",
            type: "multiple-choice",
            title: "Food and drink",
            instruction: "Look at the picture and choose the correct noun.",
            prompt: "🧀",
            options: ["der Käse", "das Brot", "die Milch"],
            correctIndex: 0,
            explain: "🧀 ist der Käse.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "img-2e",
            type: "multiple-choice",
            title: "Food and drink",
            instruction: "Look at the picture and choose the correct noun.",
            prompt: "☕",
            options: ["der Kaffee", "das Bier", "der Tee"],
            correctIndex: 0,
            explain: "☕ ist der Kaffee.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "img-2f",
            type: "multiple-choice",
            title: "Food and drink",
            instruction: "Look at the picture and choose the correct noun.",
            prompt: "🍕",
            options: ["die Pizza", "der Kuchen", "das Ei"],
            correctIndex: 0,
            explain: "🍕 ist die Pizza.",
          },
        },
      ],
    },
  ],
};

export const trueFalseNounsGame: Game = {
  id: "true-or-false-nouns",
  title: "True or False (Nouns)",
  emoji: "✅",
  description:
    "See a noun + artikel, plural or mixed statement and decide if it is correct or false. Fast-paced, mobile-friendly noun validation practice.",
  category: "grammar",
  tags: ["A1", "A2"],
  levels: [
    {
      id: "tf-1",
      title: "Level 1: Articles",
      rounds: [
        {
          kind: "exercise",
          exercise: {
            id: "tf-1a",
            type: "multiple-choice",
            title: "Article check",
            instruction: "Is the article correct?",
            prompt: "der Tisch",
            options: ["Richtig", "Falsch"],
            correctIndex: 0,
            explain: "der Tisch is correct: Tisch is masculine.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "tf-1b",
            type: "multiple-choice",
            title: "Article check",
            instruction: "Is the article correct?",
            prompt: "die Auto",
            options: ["Falsch", "Richtig"],
            correctIndex: 0,
            explain: "It is das Auto: Auto is neuter.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "tf-1c",
            type: "multiple-choice",
            title: "Article check",
            instruction: "Is the article correct?",
            prompt: "das Haus",
            options: ["Richtig", "Falsch"],
            correctIndex: 0,
            explain: "das Haus is correct: Haus is neuter.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "tf-1d",
            type: "multiple-choice",
            title: "Article check",
            instruction: "Is the article correct?",
            prompt: "der Lampe",
            options: ["Falsch", "Richtig"],
            correctIndex: 0,
            explain: "It is die Lampe: Lampe is feminine.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "tf-1e",
            type: "multiple-choice",
            title: "Article check",
            instruction: "Is the article correct?",
            prompt: "das Mädchen",
            options: ["Richtig", "Falsch"],
            correctIndex: 0,
            explain: "das Mädchen is correct: -chen words are always neuter.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "tf-1f",
            type: "multiple-choice",
            title: "Article check",
            instruction: "Is the article correct?",
            prompt: "die Straße",
            options: ["Richtig", "Falsch"],
            correctIndex: 0,
            explain: "die Straße is correct: Straße is feminine.",
          },
        },
      ],
    },
    {
      id: "tf-2",
      title: "Level 2: Plurals",
      rounds: [
        {
          kind: "exercise",
          exercise: {
            id: "tf-2a",
            type: "multiple-choice",
            title: "Plural check",
            instruction: "Is the plural correct?",
            prompt: "der Mann — die Männer",
            options: ["Richtig", "Falsch"],
            correctIndex: 0,
            explain: "der Mann → die Männer is correct.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "tf-2b",
            type: "multiple-choice",
            title: "Plural check",
            instruction: "Is the plural correct?",
            prompt: "das Kind — die Kinder",
            options: ["Richtig", "Falsch"],
            correctIndex: 0,
            explain: "das Kind → die Kinder is correct.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "tf-2c",
            type: "multiple-choice",
            title: "Plural check",
            instruction: "Is the plural correct?",
            prompt: "der Apfel — die Äpfel",
            options: ["Richtig", "Falsch"],
            correctIndex: 0,
            explain: "der Apfel → die Äpfel is correct: it takes an umlaut.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "tf-2d",
            type: "multiple-choice",
            title: "Plural check",
            instruction: "Is the plural correct?",
            prompt: "das Buch — die Bücher",
            options: ["Richtig", "Falsch"],
            correctIndex: 0,
            explain: "das Buch → die Bücher is correct.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "tf-2e",
            type: "multiple-choice",
            title: "Plural check",
            instruction: "Is the plural correct?",
            prompt: "die Frau — die Frauen",
            options: ["Richtig", "Falsch"],
            correctIndex: 0,
            explain: "die Frau → die Frauen is correct.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "tf-2f",
            type: "multiple-choice",
            title: "Plural check",
            instruction: "Is the plural correct?",
            prompt: "der Tisch — die Tische",
            options: ["Richtig", "Falsch"],
            correctIndex: 0,
            explain: "der Tisch → die Tische is correct.",
          },
        },
      ],
    },
  ],
};

export const nounPluralsGame: Game = {
  id: "noun-plurals",
  title: "German Noun Plurals",
  emoji: "🔢",
  description:
    "Learn German plural forms by clicking the correct option. Mobile-friendly multiple choice game.",
  category: "grammar",
  tags: ["A1", "A2"],
  levels: [
    {
      id: "plurals-1",
      title: "Level 1: Umlaut plurals",
      rounds: [
        {
          kind: "exercise",
          exercise: {
            id: "pl-1a",
            type: "multiple-choice",
            title: "Plurals with umlauts",
            instruction: "Choose the correct plural.",
            prompt: "der Apfel → ___",
            options: ["die Äpfel", "die Apfeln", "die Apfel"],
            correctIndex: 0,
            explain: "der Apfel → die Äpfel: short masculine nouns often take an umlaut.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "pl-1b",
            type: "multiple-choice",
            title: "Plurals with umlauts",
            instruction: "Choose the correct plural.",
            prompt: "das Buch → ___",
            options: ["die Bücher", "die Buchen", "die Buchs"],
            correctIndex: 0,
            explain: "das Buch → die Bücher.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "pl-1c",
            type: "multiple-choice",
            title: "Plurals with umlauts",
            instruction: "Choose the correct plural.",
            prompt: "der Mann → ___",
            options: ["die Männer", "die Männs", "die Männeren"],
            correctIndex: 0,
            explain: "der Mann → die Männer.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "pl-1d",
            type: "multiple-choice",
            title: "Plurals with umlauts",
            instruction: "Choose the correct plural.",
            prompt: "der Stuhl → ___",
            options: ["die Stühle", "die Stuhlen", "die Stuhl"],
            correctIndex: 0,
            explain: "der Stuhl → die Stühle.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "pl-1e",
            type: "multiple-choice",
            title: "Plurals with umlauts",
            instruction: "Choose the correct plural.",
            prompt: "die Nacht → ___",
            options: ["die Nächte", "die Nachte", "die Nachts"],
            correctIndex: 0,
            explain: "die Nacht → die Nächte.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "pl-1f",
            type: "multiple-choice",
            title: "Plurals with umlauts",
            instruction: "Choose the correct plural.",
            prompt: "das Haus → ___",
            options: ["die Häuser", "die Hause", "die Häusen"],
            correctIndex: 0,
            explain: "das Haus → die Häuser.",
          },
        },
      ],
    },
    {
      id: "plurals-2",
      title: "Level 2: Regular plurals",
      rounds: [
        {
          kind: "exercise",
          exercise: {
            id: "pl-2a",
            type: "multiple-choice",
            title: "Regular plurals",
            instruction: "Choose the correct plural.",
            prompt: "die Frau → ___",
            options: ["die Frauen", "die Fraus", "die Frau"],
            correctIndex: 0,
            explain: "die Frau → die Frauen: feminine nouns usually add -en.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "pl-2b",
            type: "multiple-choice",
            title: "Regular plurals",
            instruction: "Choose the correct plural.",
            prompt: "das Kind → ___",
            options: ["die Kinder", "die Kinden", "die Kinderen"],
            correctIndex: 0,
            explain: "das Kind → die Kinder: neuter nouns often add -er.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "pl-2c",
            type: "multiple-choice",
            title: "Regular plurals",
            instruction: "Choose the correct plural.",
            prompt: "die Lampe → ___",
            options: ["die Lampen", "die Lampes", "die Lampe"],
            correctIndex: 0,
            explain: "die Lampe → die Lampen.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "pl-2d",
            type: "multiple-choice",
            title: "Regular plurals",
            instruction: "Choose the correct plural.",
            prompt: "das Auto → ___",
            options: ["die Autos", "die Autoe", "die Auton"],
            correctIndex: 0,
            explain: "das Auto → die Autos: foreign words add -s.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "pl-2e",
            type: "multiple-choice",
            title: "Regular plurals",
            instruction: "Choose the correct plural.",
            prompt: "der Computer → ___",
            options: ["die Computer", "die Computern", "die Computeres"],
            correctIndex: 0,
            explain: "der Computer → die Computer: -er nouns often stay the same.",
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "pl-2f",
            type: "multiple-choice",
            title: "Regular plurals",
            instruction: "Choose the correct plural.",
            prompt: "das Ei → ___",
            options: ["die Eier", "die Eis", "die Eien"],
            correctIndex: 0,
            explain: "das Ei → die Eier.",
          },
        },
      ],
    },
  ],
};

export const englishNounsToGermanGame: Game = {
  id: "english-nouns-to-german",
  title: "English Nouns to German",
  emoji: "📝",
  description:
    "See an English word and type the German translation with its artikel.",
  category: "vocabulary",
  tags: ["A1"],
  levels: [
    {
      id: "en2de-1",
      title: "Level 1: Basics",
      rounds: [
        {
          kind: "typing",
          title: "English nouns to German",
          instruction: "Type the German noun with its article.",
          items: [
            { prompt: "the house", accept: ["das haus"], hint: "das Haus", audio: true },
            { prompt: "the table", accept: ["der tisch"], hint: "der Tisch", audio: true },
            { prompt: "the woman", accept: ["die frau"], hint: "die Frau", audio: true },
            { prompt: "the man", accept: ["der mann"], hint: "der Mann", audio: true },
            { prompt: "the child", accept: ["das kind"], hint: "das Kind", audio: true },
            { prompt: "the water", accept: ["das wasser"], hint: "das Wasser", audio: true },
            { prompt: "the bread", accept: ["das brot"], hint: "das Brot", audio: true },
            { prompt: "the milk", accept: ["die milch"], hint: "die Milch", audio: true },
            { prompt: "the apple", accept: ["der apfel"], hint: "der Apfel", audio: true },
            { prompt: "the book", accept: ["das buch"], hint: "das Buch", audio: true },
            { prompt: "the street", accept: ["die straße", "die strasse"], hint: "die Straße", audio: true },
            { prompt: "the city", accept: ["die stadt"], hint: "die Stadt", audio: true },
          ],
        },
      ],
    },
    {
      id: "en2de-2",
      title: "Level 2: Around the house",
      rounds: [
        {
          kind: "typing",
          title: "English nouns to German",
          instruction: "Type the German noun with its article.",
          items: [
            { prompt: "the window", accept: ["das fenster"], hint: "das Fenster", audio: true },
            { prompt: "the door", accept: ["die tür", "die tuer"], hint: "die Tür", audio: true },
            { prompt: "the chair", accept: ["der stuhl"], hint: "der Stuhl", audio: true },
            { prompt: "the bed", accept: ["das bett"], hint: "das Bett", audio: true },
            { prompt: "the lamp", accept: ["die lampe"], hint: "die Lampe", audio: true },
            { prompt: "the kitchen", accept: ["die küche", "die kueche"], hint: "die Küche", audio: true },
            { prompt: "the garden", accept: ["der garten"], hint: "der Garten", audio: true },
            { prompt: "the fridge", accept: ["der kühlschrank", "der kuehlschrank"], hint: "der Kühlschrank", audio: true },
            { prompt: "the wall", accept: ["die wand"], hint: "die Wand", audio: true },
            { prompt: "the floor", accept: ["der boden", "der fussboden", "der fußboden"], hint: "der Boden", audio: true },
          ],
        },
      ],
    },
  ],
};

export const guessWordMcGame: Game = {
  id: "guess-word-mc",
  title: "Guess the Word (Multiple Choice)",
  emoji: "🔍",
  description:
    "See a German noun and click the correct English meaning. Mobile-friendly multiple choice game.",
  category: "vocabulary",
  tags: ["A1"],
  levels: [
    {
      id: "gwm-1",
      title: "Level 1: Everyday nouns",
      rounds: [
        {
          kind: "exercise",
          exercise: {
            id: "gwm-1a",
            type: "multiple-choice",
            title: "Guess the word",
            instruction: "Choose the English meaning.",
            prompt: "das Haus",
            options: ["house", "horse", "hose"],
            correctIndex: 0,
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "gwm-1b",
            type: "multiple-choice",
            title: "Guess the word",
            instruction: "Choose the English meaning.",
            prompt: "der Tisch",
            options: ["table", "chair", "ticket"],
            correctIndex: 0,
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "gwm-1c",
            type: "multiple-choice",
            title: "Guess the word",
            instruction: "Choose the English meaning.",
            prompt: "die Schule",
            options: ["school", "schedule", "shell"],
            correctIndex: 0,
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "gwm-1d",
            type: "multiple-choice",
            title: "Guess the word",
            instruction: "Choose the English meaning.",
            prompt: "der Bahnhof",
            options: ["train station", "bank", "farm"],
            correctIndex: 0,
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "gwm-1e",
            type: "multiple-choice",
            title: "Guess the word",
            instruction: "Choose the English meaning.",
            prompt: "das Buch",
            options: ["book", "box", "bus"],
            correctIndex: 0,
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "gwm-1f",
            type: "multiple-choice",
            title: "Guess the word",
            instruction: "Choose the English meaning.",
            prompt: "die Straße",
            options: ["street", "strawberry", "strain"],
            correctIndex: 0,
          },
        },
      ],
    },
    {
      id: "gwm-2",
      title: "Level 2: Food and objects",
      rounds: [
        {
          kind: "exercise",
          exercise: {
            id: "gwm-2a",
            type: "multiple-choice",
            title: "Guess the word",
            instruction: "Choose the English meaning.",
            prompt: "der Kaffee",
            options: ["coffee", "cafeteria", "copy"],
            correctIndex: 0,
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "gwm-2b",
            type: "multiple-choice",
            title: "Guess the word",
            instruction: "Choose the English meaning.",
            prompt: "die Milch",
            options: ["milk", "mill", "melt"],
            correctIndex: 0,
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "gwm-2c",
            type: "multiple-choice",
            title: "Guess the word",
            instruction: "Choose the English meaning.",
            prompt: "das Fenster",
            options: ["window", "fence", "vent"],
            correctIndex: 0,
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "gwm-2d",
            type: "multiple-choice",
            title: "Guess the word",
            instruction: "Choose the English meaning.",
            prompt: "die Uhr",
            options: ["clock", "hour", "ear"],
            correctIndex: 0,
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "gwm-2e",
            type: "multiple-choice",
            title: "Guess the word",
            instruction: "Choose the English meaning.",
            prompt: "der Zug",
            options: ["train", "tug", "zoo"],
            correctIndex: 0,
          },
        },
        {
          kind: "exercise",
          exercise: {
            id: "gwm-2f",
            type: "multiple-choice",
            title: "Guess the word",
            instruction: "Choose the English meaning.",
            prompt: "das Wetter",
            options: ["weather", "water", "wetter"],
            correctIndex: 0,
          },
        },
      ],
    },
  ],
};

export const guessWordTypingGame: Game = {
  id: "guess-word-typing",
  title: "Guess the Word",
  emoji: "⌨️",
  description:
    "Translate German nouns to English. See a German word with its article and type the English meaning.",
  category: "vocabulary",
  tags: ["A1", "A2"],
  levels: [
    {
      id: "gwt-1",
      title: "Level 1: Everyday nouns",
      rounds: [
        {
          kind: "typing",
          title: "Guess the word",
          instruction: "Type the English meaning.",
          items: [
            { prompt: "das Haus", accept: ["house"], audio: true },
            { prompt: "der Tisch", accept: ["table"], audio: true },
            { prompt: "die Schule", accept: ["school"], audio: true },
            { prompt: "der Bahnhof", accept: ["train station", "station"], audio: true },
            { prompt: "das Buch", accept: ["book"], audio: true },
            { prompt: "die Straße", accept: ["street"], audio: true },
            { prompt: "die Stadt", accept: ["city", "town"], audio: true },
            { prompt: "der Garten", accept: ["garden"], audio: true },
            { prompt: "das Fenster", accept: ["window"], audio: true },
            { prompt: "die Küche", accept: ["kitchen"], audio: true },
            { prompt: "der Zug", accept: ["train"], audio: true },
            { prompt: "das Auto", accept: ["car"], audio: true },
          ],
        },
      ],
    },
    {
      id: "gwt-2",
      title: "Level 2: People and things",
      rounds: [
        {
          kind: "typing",
          title: "Guess the word",
          instruction: "Type the English meaning.",
          items: [
            { prompt: "der Mann", accept: ["man"], audio: true },
            { prompt: "die Frau", accept: ["woman"], audio: true },
            { prompt: "das Kind", accept: ["child"], audio: true },
            { prompt: "der Freund", accept: ["friend"], audio: true },
            { prompt: "der Arzt", accept: ["doctor"], audio: true },
            { prompt: "der Lehrer", accept: ["teacher"], audio: true },
            { prompt: "die Zeitung", accept: ["newspaper"], audio: true },
            { prompt: "das Frühstück", accept: ["breakfast"], audio: true },
            { prompt: "der Kühlschrank", accept: ["fridge", "refrigerator"], audio: true },
            { prompt: "das Wetter", accept: ["weather"], audio: true },
            { prompt: "die Arbeit", accept: ["work", "job"], audio: true },
            { prompt: "das Geld", accept: ["money"], audio: true },
          ],
        },
      ],
    },
  ],
};

export const nounGames: Game[] = [
  artikelDropGame,
  nounRulesGame,
  timeExpressionsGame,
  dativPrepositionsGame,
  imageNounGame,
  trueFalseNounsGame,
  nounPluralsGame,
  englishNounsToGermanGame,
  guessWordMcGame,
  guessWordTypingGame,
];