import type { Game } from "./schema";

export const ninewordsGame: Game = {
  id: "nine-words",
  title: "9 Words",
  emoji: "🧩",
  description: "Nine scrambled German words, 30 seconds each. Tap the letters in the right order before the clock runs out.",
  category: "vocabulary",
  tags: ["A1","A2"],
  levels: [
    {
      id: "nine-words-1",
      title: "Level 1: Short words",
      rounds: [
        {
          kind: "scramble",
          title: "Round 1",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"genau","en":"exact, exactly","timeLimit":30,"audio":true},{"de":"neu","en":"new","timeLimit":30,"audio":true},{"de":"satt","en":"full (after eating)","timeLimit":30,"audio":true},{"de":"preis","en":"","timeLimit":30,"audio":true},{"de":"teuer","en":"expensive","timeLimit":30,"audio":true},{"de":"tag","en":"","timeLimit":30,"audio":true},{"de":"euer","en":"your (plural informal)","timeLimit":30,"audio":true},{"de":"spielen","en":"","timeLimit":30,"audio":true},{"de":"hören","en":"","timeLimit":30,"audio":true},{"de":"grün","en":"green","timeLimit":30,"audio":true},{"de":"laut","en":"loud","timeLimit":30,"audio":true},{"de":"arzt","en":"","timeLimit":30,"audio":true},{"de":"hund","en":"","timeLimit":30,"audio":true},{"de":"fertig","en":"finished, ready","timeLimit":30,"audio":true},{"de":"film","en":"","timeLimit":30,"audio":true},{"de":"taxi","en":"","timeLimit":30,"audio":true},{"de":"dunkel","en":"dark","timeLimit":30,"audio":true},{"de":"lernen","en":"","timeLimit":30,"audio":true},{"de":"frau","en":"","timeLimit":30,"audio":true},{"de":"regen","en":"","timeLimit":30,"audio":true},{"de":"name","en":"","timeLimit":30,"audio":true},{"de":"ruhig","en":"quiet, calm","timeLimit":30,"audio":true},{"de":"euro","en":"","timeLimit":30,"audio":true},{"de":"eine","en":"a, one (feminine)","timeLimit":30,"audio":true},{"de":"huhn","en":"","timeLimit":30,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 2",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"hund","en":"","timeLimit":30,"audio":true},{"de":"hand","en":"","timeLimit":30,"audio":true},{"de":"finden","en":"","timeLimit":30,"audio":true},{"de":"kaffee","en":"","timeLimit":30,"audio":true},{"de":"hell","en":"bright, light","timeLimit":30,"audio":true},{"de":"sehen","en":"","timeLimit":30,"audio":true},{"de":"post","en":"","timeLimit":30,"audio":true},{"de":"bett","en":"","timeLimit":30,"audio":true},{"de":"leicht","en":"easy, light","timeLimit":30,"audio":true},{"de":"klein","en":"small","timeLimit":30,"audio":true},{"de":"zug","en":"","timeLimit":30,"audio":true},{"de":"besser","en":"better","timeLimit":30,"audio":true},{"de":"dunkel","en":"dark","timeLimit":30,"audio":true},{"de":"mittag","en":"","timeLimit":30,"audio":true},{"de":"nase","en":"","timeLimit":30,"audio":true},{"de":"hemd","en":"","timeLimit":30,"audio":true},{"de":"stuhl","en":"","timeLimit":30,"audio":true},{"de":"blume","en":"","timeLimit":30,"audio":true},{"de":"eng","en":"narrow, tight","timeLimit":30,"audio":true},{"de":"spät","en":"late","timeLimit":30,"audio":true},{"de":"kirche","en":"","timeLimit":30,"audio":true},{"de":"gelb","en":"yellow","timeLimit":30,"audio":true},{"de":"huhn","en":"","timeLimit":30,"audio":true},{"de":"trinken","en":"","timeLimit":30,"audio":true},{"de":"hübsch","en":"pretty","timeLimit":30,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 3",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"sagen","en":"","timeLimit":30,"audio":true},{"de":"hose","en":"","timeLimit":30,"audio":true},{"de":"mund","en":"","timeLimit":30,"audio":true},{"de":"hund","en":"","timeLimit":30,"audio":true},{"de":"klein","en":"small","timeLimit":30,"audio":true},{"de":"stuhl","en":"","timeLimit":30,"audio":true},{"de":"blau","en":"blue","timeLimit":30,"audio":true},{"de":"alt","en":"old","timeLimit":30,"audio":true},{"de":"gut","en":"good","timeLimit":30,"audio":true},{"de":"schaf","en":"","timeLimit":30,"audio":true},{"de":"mond","en":"","timeLimit":30,"audio":true},{"de":"selten","en":"rare, seldom","timeLimit":30,"audio":true},{"de":"fest","en":"firm, fixed","timeLimit":30,"audio":true},{"de":"spiel","en":"","timeLimit":30,"audio":true},{"de":"regen","en":"","timeLimit":30,"audio":true},{"de":"tee","en":"","timeLimit":30,"audio":true},{"de":"solch","en":"such","timeLimit":30,"audio":true},{"de":"billig","en":"cheap","timeLimit":30,"audio":true},{"de":"häufig","en":"frequent","timeLimit":30,"audio":true},{"de":"vier","en":"four","timeLimit":30,"audio":true},{"de":"farbe","en":"","timeLimit":30,"audio":true},{"de":"apfel","en":"","timeLimit":30,"audio":true},{"de":"warten","en":"","timeLimit":30,"audio":true},{"de":"lied","en":"","timeLimit":30,"audio":true},{"de":"arzt","en":"","timeLimit":30,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 4",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"schule","en":"","timeLimit":30,"audio":true},{"de":"egal","en":"all the same","timeLimit":30,"audio":true},{"de":"hand","en":"","timeLimit":30,"audio":true},{"de":"kleid","en":"","timeLimit":30,"audio":true},{"de":"mund","en":"","timeLimit":30,"audio":true},{"de":"vier","en":"four","timeLimit":30,"audio":true},{"de":"helfen","en":"","timeLimit":30,"audio":true},{"de":"lang","en":"long","timeLimit":30,"audio":true},{"de":"frisch","en":"fresh","timeLimit":30,"audio":true},{"de":"hell","en":"bright, light","timeLimit":30,"audio":true},{"de":"ruhig","en":"quiet, calm","timeLimit":30,"audio":true},{"de":"normal","en":"normal","timeLimit":30,"audio":true},{"de":"kurz","en":"short","timeLimit":30,"audio":true},{"de":"arm","en":"","timeLimit":30,"audio":true},{"de":"kochen","en":"","timeLimit":30,"audio":true},{"de":"tee","en":"","timeLimit":30,"audio":true},{"de":"eng","en":"narrow, tight","timeLimit":30,"audio":true},{"de":"jeder","en":"every, each","timeLimit":30,"audio":true},{"de":"spiel","en":"","timeLimit":30,"audio":true},{"de":"genau","en":"exact, exactly","timeLimit":30,"audio":true},{"de":"milch","en":"","timeLimit":30,"audio":true},{"de":"monat","en":"","timeLimit":30,"audio":true},{"de":"ihr","en":"her, their, you (plural)","timeLimit":30,"audio":true},{"de":"auge","en":"","timeLimit":30,"audio":true},{"de":"hund","en":"","timeLimit":30,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 5",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"tür","en":"","timeLimit":30,"audio":true},{"de":"eng","en":"narrow, tight","timeLimit":30,"audio":true},{"de":"der","en":"the (masculine)","timeLimit":30,"audio":true},{"de":"spielen","en":"","timeLimit":30,"audio":true},{"de":"post","en":"","timeLimit":30,"audio":true},{"de":"bett","en":"","timeLimit":30,"audio":true},{"de":"blau","en":"blue","timeLimit":30,"audio":true},{"de":"jeder","en":"every, each","timeLimit":30,"audio":true},{"de":"brot","en":"","timeLimit":30,"audio":true},{"de":"schuh","en":"","timeLimit":30,"audio":true},{"de":"lehrer","en":"","timeLimit":30,"audio":true},{"de":"stark","en":"strong","timeLimit":30,"audio":true},{"de":"park","en":"","timeLimit":30,"audio":true},{"de":"frisch","en":"fresh","timeLimit":30,"audio":true},{"de":"rund","en":"round","timeLimit":30,"audio":true},{"de":"bus","en":"","timeLimit":30,"audio":true},{"de":"maus","en":"","timeLimit":30,"audio":true},{"de":"euer","en":"your (plural informal)","timeLimit":30,"audio":true},{"de":"morgen","en":"","timeLimit":30,"audio":true},{"de":"spät","en":"late","timeLimit":30,"audio":true},{"de":"farbe","en":"","timeLimit":30,"audio":true},{"de":"kurz","en":"short","timeLimit":30,"audio":true},{"de":"egal","en":"all the same","timeLimit":30,"audio":true},{"de":"preis","en":"","timeLimit":30,"audio":true},{"de":"trinken","en":"","timeLimit":30,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 6",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"kurz","en":"short","timeLimit":30,"audio":true},{"de":"jahr","en":"","timeLimit":30,"audio":true},{"de":"mond","en":"","timeLimit":30,"audio":true},{"de":"nase","en":"","timeLimit":30,"audio":true},{"de":"schön","en":"beautiful, nice","timeLimit":30,"audio":true},{"de":"machen","en":"","timeLimit":30,"audio":true},{"de":"früh","en":"early","timeLimit":30,"audio":true},{"de":"nah","en":"near, close","timeLimit":30,"audio":true},{"de":"vier","en":"four","timeLimit":30,"audio":true},{"de":"heft","en":"","timeLimit":30,"audio":true},{"de":"pferd","en":"","timeLimit":30,"audio":true},{"de":"suchen","en":"","timeLimit":30,"audio":true},{"de":"maus","en":"","timeLimit":30,"audio":true},{"de":"dick","en":"thick, fat","timeLimit":30,"audio":true},{"de":"vogel","en":"","timeLimit":30,"audio":true},{"de":"spieler","en":"","timeLimit":30,"audio":true},{"de":"eine","en":"a, one (feminine)","timeLimit":30,"audio":true},{"de":"wald","en":"","timeLimit":30,"audio":true},{"de":"frisch","en":"fresh","timeLimit":30,"audio":true},{"de":"mittag","en":"","timeLimit":30,"audio":true},{"de":"blume","en":"","timeLimit":30,"audio":true},{"de":"auge","en":"","timeLimit":30,"audio":true},{"de":"bier","en":"","timeLimit":30,"audio":true},{"de":"lesen","en":"","timeLimit":30,"audio":true},{"de":"morgen","en":"","timeLimit":30,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 7",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"heiß","en":"hot","timeLimit":30,"audio":true},{"de":"letzt","en":"last","timeLimit":30,"audio":true},{"de":"gabel","en":"","timeLimit":30,"audio":true},{"de":"hand","en":"","timeLimit":30,"audio":true},{"de":"see","en":"","timeLimit":30,"audio":true},{"de":"kaufen","en":"","timeLimit":30,"audio":true},{"de":"fisch","en":"","timeLimit":30,"audio":true},{"de":"essen","en":"","timeLimit":30,"audio":true},{"de":"warm","en":"warm","timeLimit":30,"audio":true},{"de":"kochen","en":"","timeLimit":30,"audio":true},{"de":"eng","en":"narrow, tight","timeLimit":30,"audio":true},{"de":"die","en":"the (feminine)","timeLimit":30,"audio":true},{"de":"nah","en":"near, close","timeLimit":30,"audio":true},{"de":"sich","en":"oneself, himself, herself","timeLimit":30,"audio":true},{"de":"rund","en":"round","timeLimit":30,"audio":true},{"de":"wand","en":"","timeLimit":30,"audio":true},{"de":"straße","en":"","timeLimit":30,"audio":true},{"de":"cent","en":"","timeLimit":30,"audio":true},{"de":"auge","en":"","timeLimit":30,"audio":true},{"de":"sagen","en":"","timeLimit":30,"audio":true},{"de":"weit","en":"far, wide","timeLimit":30,"audio":true},{"de":"euer","en":"your (plural informal)","timeLimit":30,"audio":true},{"de":"name","en":"","timeLimit":30,"audio":true},{"de":"dünn","en":"thin","timeLimit":30,"audio":true},{"de":"auto","en":"","timeLimit":30,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 8",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"kühl","en":"cool","timeLimit":30,"audio":true},{"de":"frisch","en":"fresh","timeLimit":30,"audio":true},{"de":"abend","en":"","timeLimit":30,"audio":true},{"de":"kuh","en":"","timeLimit":30,"audio":true},{"de":"kommen","en":"","timeLimit":30,"audio":true},{"de":"stern","en":"","timeLimit":30,"audio":true},{"de":"stift","en":"","timeLimit":30,"audio":true},{"de":"farbig","en":"colored","timeLimit":30,"audio":true},{"de":"morgen","en":"","timeLimit":30,"audio":true},{"de":"sie","en":"she, they","timeLimit":30,"audio":true},{"de":"kein","en":"no, not a","timeLimit":30,"audio":true},{"de":"regen","en":"","timeLimit":30,"audio":true},{"de":"klein","en":"small","timeLimit":30,"audio":true},{"de":"genau","en":"exact, exactly","timeLimit":30,"audio":true},{"de":"bett","en":"","timeLimit":30,"audio":true},{"de":"jacke","en":"","timeLimit":30,"audio":true},{"de":"post","en":"","timeLimit":30,"audio":true},{"de":"fragen","en":"","timeLimit":30,"audio":true},{"de":"markt","en":"","timeLimit":30,"audio":true},{"de":"park","en":"","timeLimit":30,"audio":true},{"de":"woche","en":"","timeLimit":30,"audio":true},{"de":"zwei","en":"two","timeLimit":30,"audio":true},{"de":"zimmer","en":"","timeLimit":30,"audio":true},{"de":"spielen","en":"","timeLimit":30,"audio":true},{"de":"nah","en":"near, close","timeLimit":30,"audio":true}],
        },

      ],
    },

    {
      id: "nine-words-2",
      title: "Level 2: Medium words",
      rounds: [
        {
          kind: "scramble",
          title: "Round 1",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"dezember","en":"","timeLimit":30,"audio":true},{"de":"mittwoch","en":"","timeLimit":30,"audio":true},{"de":"mutter","en":"","timeLimit":30,"audio":true},{"de":"fünfzig","en":"fifty","timeLimit":30,"audio":true},{"de":"unbekannt","en":"unknown","timeLimit":30,"audio":true},{"de":"dunkel","en":"dark","timeLimit":30,"audio":true},{"de":"freundin","en":"","timeLimit":30,"audio":true},{"de":"nervös","en":"nervous","timeLimit":30,"audio":true},{"de":"zimmer","en":"","timeLimit":30,"audio":true},{"de":"glücklich","en":"happy","timeLimit":30,"audio":true},{"de":"garten","en":"","timeLimit":30,"audio":true},{"de":"küche","en":"","timeLimit":30,"audio":true},{"de":"direkt","en":"direct, straight","timeLimit":30,"audio":true},{"de":"schnell","en":"fast, quick","timeLimit":30,"audio":true},{"de":"gepäck","en":"","timeLimit":30,"audio":true},{"de":"jemand","en":"someone","timeLimit":30,"audio":true},{"de":"selten","en":"rare, seldom","timeLimit":30,"audio":true},{"de":"geburtstag","en":"","timeLimit":30,"audio":true},{"de":"teppich","en":"","timeLimit":30,"audio":true},{"de":"adresse","en":"","timeLimit":30,"audio":true},{"de":"banane","en":"","timeLimit":30,"audio":true},{"de":"bewölkt","en":"cloudy","timeLimit":30,"audio":true},{"de":"fertig","en":"finished, ready","timeLimit":30,"audio":true},{"de":"sommer","en":"","timeLimit":30,"audio":true},{"de":"japanisch","en":"Japanese","timeLimit":30,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 2",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"dunkel","en":"dark","timeLimit":30,"audio":true},{"de":"sonntag","en":"","timeLimit":30,"audio":true},{"de":"gepäck","en":"","timeLimit":30,"audio":true},{"de":"fünfzehn","en":"fifteen","timeLimit":30,"audio":true},{"de":"frühling","en":"","timeLimit":30,"audio":true},{"de":"rechnung","en":"","timeLimit":30,"audio":true},{"de":"banane","en":"","timeLimit":30,"audio":true},{"de":"verkäufer","en":"","timeLimit":30,"audio":true},{"de":"typisch","en":"typical","timeLimit":30,"audio":true},{"de":"doppelt","en":"double","timeLimit":30,"audio":true},{"de":"nachbar","en":"","timeLimit":30,"audio":true},{"de":"august","en":"","timeLimit":30,"audio":true},{"de":"supermarkt","en":"","timeLimit":30,"audio":true},{"de":"reise","en":"","timeLimit":30,"audio":true},{"de":"nummer","en":"","timeLimit":30,"audio":true},{"de":"selten","en":"rare, seldom","timeLimit":30,"audio":true},{"de":"garten","en":"","timeLimit":30,"audio":true},{"de":"hotel","en":"","timeLimit":30,"audio":true},{"de":"normal","en":"normal","timeLimit":30,"audio":true},{"de":"gabel","en":"","timeLimit":30,"audio":true},{"de":"niemand","en":"nobody","timeLimit":30,"audio":true},{"de":"lehrer","en":"","timeLimit":30,"audio":true},{"de":"farbig","en":"colored","timeLimit":30,"audio":true},{"de":"japanisch","en":"Japanese","timeLimit":30,"audio":true},{"de":"wochenende","en":"","timeLimit":30,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 3",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"gepäck","en":"","timeLimit":30,"audio":true},{"de":"gabel","en":"","timeLimit":30,"audio":true},{"de":"juni","en":"","timeLimit":30,"audio":true},{"de":"spiegel","en":"","timeLimit":30,"audio":true},{"de":"beruflich","en":"professional, work-related","timeLimit":30,"audio":true},{"de":"fertig","en":"finished, ready","timeLimit":30,"audio":true},{"de":"häufig","en":"frequent","timeLimit":30,"audio":true},{"de":"japanisch","en":"Japanese","timeLimit":30,"audio":true},{"de":"langsam","en":"slow","timeLimit":30,"audio":true},{"de":"abendessen","en":"","timeLimit":30,"audio":true},{"de":"küche","en":"","timeLimit":30,"audio":true},{"de":"frühling","en":"","timeLimit":30,"audio":true},{"de":"bewölkt","en":"cloudy","timeLimit":30,"audio":true},{"de":"notwendig","en":"necessary","timeLimit":30,"audio":true},{"de":"schwester","en":"","timeLimit":30,"audio":true},{"de":"computer","en":"","timeLimit":30,"audio":true},{"de":"schnell","en":"fast, quick","timeLimit":30,"audio":true},{"de":"niemand","en":"nobody","timeLimit":30,"audio":true},{"de":"schokolade","en":"","timeLimit":30,"audio":true},{"de":"montag","en":"","timeLimit":30,"audio":true},{"de":"krankenhaus","en":"","timeLimit":30,"audio":true},{"de":"museum","en":"","timeLimit":30,"audio":true},{"de":"messer","en":"","timeLimit":30,"audio":true},{"de":"sonntag","en":"","timeLimit":30,"audio":true},{"de":"freundin","en":"","timeLimit":30,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 4",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"fünfzig","en":"fifty","timeLimit":30,"audio":true},{"de":"kellner","en":"","timeLimit":30,"audio":true},{"de":"august","en":"","timeLimit":30,"audio":true},{"de":"abendessen","en":"","timeLimit":30,"audio":true},{"de":"gemeinsam","en":"together, joint","timeLimit":30,"audio":true},{"de":"dunkel","en":"dark","timeLimit":30,"audio":true},{"de":"deutsch","en":"German","timeLimit":30,"audio":true},{"de":"banane","en":"","timeLimit":30,"audio":true},{"de":"oktober","en":"","timeLimit":30,"audio":true},{"de":"selten","en":"rare, seldom","timeLimit":30,"audio":true},{"de":"japanisch","en":"Japanese","timeLimit":30,"audio":true},{"de":"leicht","en":"easy, light","timeLimit":30,"audio":true},{"de":"löffel","en":"","timeLimit":30,"audio":true},{"de":"computer","en":"","timeLimit":30,"audio":true},{"de":"januar","en":"","timeLimit":30,"audio":true},{"de":"schwester","en":"","timeLimit":30,"audio":true},{"de":"kartoffel","en":"","timeLimit":30,"audio":true},{"de":"zeitung","en":"","timeLimit":30,"audio":true},{"de":"geschäft","en":"","timeLimit":30,"audio":true},{"de":"sicher","en":"safe, certain","timeLimit":30,"audio":true},{"de":"fahrkarte","en":"","timeLimit":30,"audio":true},{"de":"frühling","en":"","timeLimit":30,"audio":true},{"de":"schule","en":"","timeLimit":30,"audio":true},{"de":"mittwoch","en":"","timeLimit":30,"audio":true},{"de":"niemand","en":"nobody","timeLimit":30,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 5",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"computer","en":"","timeLimit":30,"audio":true},{"de":"langsam","en":"slow","timeLimit":30,"audio":true},{"de":"hotel","en":"","timeLimit":30,"audio":true},{"de":"welcher","en":"which","timeLimit":30,"audio":true},{"de":"student","en":"","timeLimit":30,"audio":true},{"de":"freundin","en":"","timeLimit":30,"audio":true},{"de":"beruflich","en":"professional, work-related","timeLimit":30,"audio":true},{"de":"spiegel","en":"","timeLimit":30,"audio":true},{"de":"dezember","en":"","timeLimit":30,"audio":true},{"de":"zeitung","en":"","timeLimit":30,"audio":true},{"de":"telefon","en":"","timeLimit":30,"audio":true},{"de":"löffel","en":"","timeLimit":30,"audio":true},{"de":"neugierig","en":"curious","timeLimit":30,"audio":true},{"de":"montag","en":"","timeLimit":30,"audio":true},{"de":"rechnung","en":"","timeLimit":30,"audio":true},{"de":"sonntag","en":"","timeLimit":30,"audio":true},{"de":"lehrer","en":"","timeLimit":30,"audio":true},{"de":"apotheke","en":"","timeLimit":30,"audio":true},{"de":"dieser","en":"this","timeLimit":30,"audio":true},{"de":"oktober","en":"","timeLimit":30,"audio":true},{"de":"winter","en":"","timeLimit":30,"audio":true},{"de":"frisch","en":"fresh","timeLimit":30,"audio":true},{"de":"frühstück","en":"","timeLimit":30,"audio":true},{"de":"dunkel","en":"dark","timeLimit":30,"audio":true},{"de":"reise","en":"","timeLimit":30,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 6",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"fenster","en":"","timeLimit":30,"audio":true},{"de":"farbig","en":"colored","timeLimit":30,"audio":true},{"de":"wichtig","en":"important","timeLimit":30,"audio":true},{"de":"einzeln","en":"single, separate","timeLimit":30,"audio":true},{"de":"montag","en":"","timeLimit":30,"audio":true},{"de":"billig","en":"cheap","timeLimit":30,"audio":true},{"de":"niedrig","en":"low","timeLimit":30,"audio":true},{"de":"gültig","en":"valid","timeLimit":30,"audio":true},{"de":"mutter","en":"","timeLimit":30,"audio":true},{"de":"richtig","en":"correct, right","timeLimit":30,"audio":true},{"de":"falsch","en":"wrong","timeLimit":30,"audio":true},{"de":"supermarkt","en":"","timeLimit":30,"audio":true},{"de":"gläser","en":"","timeLimit":30,"audio":true},{"de":"welcher","en":"which","timeLimit":30,"audio":true},{"de":"schule","en":"","timeLimit":30,"audio":true},{"de":"häufig","en":"frequent","timeLimit":30,"audio":true},{"de":"günstig","en":"cheap, favorable","timeLimit":30,"audio":true},{"de":"dunkel","en":"dark","timeLimit":30,"audio":true},{"de":"wochenende","en":"","timeLimit":30,"audio":true},{"de":"doppelt","en":"double","timeLimit":30,"audio":true},{"de":"küche","en":"","timeLimit":30,"audio":true},{"de":"nummer","en":"","timeLimit":30,"audio":true},{"de":"frühling","en":"","timeLimit":30,"audio":true},{"de":"teppich","en":"","timeLimit":30,"audio":true},{"de":"dezember","en":"","timeLimit":30,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 7",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"direkt","en":"direct, straight","timeLimit":30,"audio":true},{"de":"apotheke","en":"","timeLimit":30,"audio":true},{"de":"langsam","en":"slow","timeLimit":30,"audio":true},{"de":"zwanzig","en":"twenty","timeLimit":30,"audio":true},{"de":"museum","en":"","timeLimit":30,"audio":true},{"de":"zimmer","en":"","timeLimit":30,"audio":true},{"de":"wichtig","en":"important","timeLimit":30,"audio":true},{"de":"sicher","en":"safe, certain","timeLimit":30,"audio":true},{"de":"dienstag","en":"","timeLimit":30,"audio":true},{"de":"sonntag","en":"","timeLimit":30,"audio":true},{"de":"garten","en":"","timeLimit":30,"audio":true},{"de":"freitag","en":"","timeLimit":30,"audio":true},{"de":"nachbar","en":"","timeLimit":30,"audio":true},{"de":"farbig","en":"colored","timeLimit":30,"audio":true},{"de":"jemand","en":"someone","timeLimit":30,"audio":true},{"de":"banane","en":"","timeLimit":30,"audio":true},{"de":"glücklich","en":"happy","timeLimit":30,"audio":true},{"de":"bruder","en":"","timeLimit":30,"audio":true},{"de":"dezember","en":"","timeLimit":30,"audio":true},{"de":"hübsch","en":"pretty","timeLimit":30,"audio":true},{"de":"dieser","en":"this","timeLimit":30,"audio":true},{"de":"niemand","en":"nobody","timeLimit":30,"audio":true},{"de":"schrank","en":"","timeLimit":30,"audio":true},{"de":"januar","en":"","timeLimit":30,"audio":true},{"de":"balkon","en":"","timeLimit":30,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 8",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"gepäck","en":"","timeLimit":30,"audio":true},{"de":"mutter","en":"","timeLimit":30,"audio":true},{"de":"dezember","en":"","timeLimit":30,"audio":true},{"de":"hotel","en":"","timeLimit":30,"audio":true},{"de":"fahrkarte","en":"","timeLimit":30,"audio":true},{"de":"freitag","en":"","timeLimit":30,"audio":true},{"de":"direkt","en":"direct, straight","timeLimit":30,"audio":true},{"de":"kellner","en":"","timeLimit":30,"audio":true},{"de":"computer","en":"","timeLimit":30,"audio":true},{"de":"kirche","en":"","timeLimit":30,"audio":true},{"de":"schule","en":"","timeLimit":30,"audio":true},{"de":"freundin","en":"","timeLimit":30,"audio":true},{"de":"montag","en":"","timeLimit":30,"audio":true},{"de":"reise","en":"","timeLimit":30,"audio":true},{"de":"richtig","en":"correct, right","timeLimit":30,"audio":true},{"de":"wichtig","en":"important","timeLimit":30,"audio":true},{"de":"frisch","en":"fresh","timeLimit":30,"audio":true},{"de":"museum","en":"","timeLimit":30,"audio":true},{"de":"kartoffel","en":"","timeLimit":30,"audio":true},{"de":"einzeln","en":"single, separate","timeLimit":30,"audio":true},{"de":"april","en":"","timeLimit":30,"audio":true},{"de":"orange","en":"","timeLimit":30,"audio":true},{"de":"spiegel","en":"","timeLimit":30,"audio":true},{"de":"notwendig","en":"necessary","timeLimit":30,"audio":true},{"de":"september","en":"","timeLimit":30,"audio":true}],
        },

      ],
    },

    {
      id: "nine-words-3",
      title: "Level 3: Long words",
      rounds: [
        {
          kind: "scramble",
          title: "Round 1",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"Supermarkt","en":"the supermarket","timeLimit":40,"audio":true},{"de":"Samstagnachmittag","en":"","timeLimit":40,"audio":true},{"de":"Jahreszeit","en":"","timeLimit":40,"audio":true},{"de":"Gutenacht","en":"","timeLimit":40,"audio":true},{"de":"Brille","en":"the glasses","timeLimit":40,"audio":true},{"de":"Universität","en":"the university","timeLimit":40,"audio":true},{"de":"Schularbeit","en":"","timeLimit":40,"audio":true},{"de":"Jacke","en":"the jacket","timeLimit":40,"audio":true},{"de":"verschieden","en":"different, various","timeLimit":40,"audio":true},{"de":"Hose","en":"the pants, the trousers","timeLimit":40,"audio":true},{"de":"Geschäft","en":"the shop","timeLimit":40,"audio":true},{"de":"Schmetterling","en":"the butterfly","timeLimit":40,"audio":true},{"de":"Straßenbahn","en":"the tram","timeLimit":40,"audio":true},{"de":"Montagmorgen","en":"","timeLimit":40,"audio":true},{"de":"Gutenmorgen","en":"","timeLimit":40,"audio":true},{"de":"Eiscreme","en":"","timeLimit":40,"audio":true},{"de":"Regenbogen","en":"the rainbow","timeLimit":40,"audio":true},{"de":"Geburtstag","en":"the birthday","timeLimit":40,"audio":true},{"de":"Einkaufen","en":"","timeLimit":40,"audio":true},{"de":"Socken","en":"","timeLimit":40,"audio":true},{"de":"Schokolade","en":"the chocolate","timeLimit":40,"audio":true},{"de":"Zeitung","en":"the newspaper","timeLimit":40,"audio":true},{"de":"Kleid","en":"the dress","timeLimit":40,"audio":true},{"de":"Haltestelle","en":"the stop","timeLimit":40,"audio":true},{"de":"Banane","en":"the banana","timeLimit":40,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 2",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"Jacke","en":"the jacket","timeLimit":40,"audio":true},{"de":"gemeinsam","en":"together, joint","timeLimit":40,"audio":true},{"de":"Mittagessen","en":"the lunch","timeLimit":40,"audio":true},{"de":"Zeitung","en":"the newspaper","timeLimit":40,"audio":true},{"de":"Geburtstag","en":"the birthday","timeLimit":40,"audio":true},{"de":"Schlafzimmer","en":"the bedroom","timeLimit":40,"audio":true},{"de":"Arbeitszimmer","en":"","timeLimit":40,"audio":true},{"de":"Lieblingsbuch","en":"","timeLimit":40,"audio":true},{"de":"Krankenhaus","en":"the hospital","timeLimit":40,"audio":true},{"de":"Samstagnachmittag","en":"","timeLimit":40,"audio":true},{"de":"Entschuldigung","en":"","timeLimit":40,"audio":true},{"de":"Nebensatz","en":"","timeLimit":40,"audio":true},{"de":"Hausschuhe","en":"the slippers","timeLimit":40,"audio":true},{"de":"kompliziert","en":"complicated","timeLimit":40,"audio":true},{"de":"Krankenwagen","en":"","timeLimit":40,"audio":true},{"de":"glücklich","en":"happy","timeLimit":40,"audio":true},{"de":"Schokolade","en":"the chocolate","timeLimit":40,"audio":true},{"de":"Abendessen","en":"the dinner","timeLimit":40,"audio":true},{"de":"europäisch","en":"European","timeLimit":40,"audio":true},{"de":"Schreibtisch","en":"the desk","timeLimit":40,"audio":true},{"de":"Jahreszeit","en":"","timeLimit":40,"audio":true},{"de":"Sonnenuntergang","en":"the sunset","timeLimit":40,"audio":true},{"de":"Bahnhofstraße","en":"","timeLimit":40,"audio":true},{"de":"Bundesland","en":"","timeLimit":40,"audio":true},{"de":"Freitagabend","en":"","timeLimit":40,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 3",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"Kleid","en":"the dress","timeLimit":40,"audio":true},{"de":"Rechnung","en":"the bill, the invoice","timeLimit":40,"audio":true},{"de":"Bücherregal","en":"the bookshelf","timeLimit":40,"audio":true},{"de":"glücklich","en":"happy","timeLimit":40,"audio":true},{"de":"Zeitung","en":"the newspaper","timeLimit":40,"audio":true},{"de":"Sonnenuntergang","en":"the sunset","timeLimit":40,"audio":true},{"de":"Krankenwagen","en":"","timeLimit":40,"audio":true},{"de":"kompliziert","en":"complicated","timeLimit":40,"audio":true},{"de":"Wochenende","en":"the weekend","timeLimit":40,"audio":true},{"de":"Hausschuhe","en":"the slippers","timeLimit":40,"audio":true},{"de":"neugierig","en":"curious","timeLimit":40,"audio":true},{"de":"Speisekarte","en":"the menu","timeLimit":40,"audio":true},{"de":"europäisch","en":"European","timeLimit":40,"audio":true},{"de":"zufrieden","en":"satisfied, content","timeLimit":40,"audio":true},{"de":"Arbeitszimmer","en":"","timeLimit":40,"audio":true},{"de":"Bücherregal","en":"the bookshelf","timeLimit":40,"audio":true},{"de":"Eiscreme","en":"","timeLimit":40,"audio":true},{"de":"Freitagabend","en":"","timeLimit":40,"audio":true},{"de":"Supermarkt","en":"the supermarket","timeLimit":40,"audio":true},{"de":"Apotheke","en":"the pharmacy","timeLimit":40,"audio":true},{"de":"Haltestelle","en":"the stop","timeLimit":40,"audio":true},{"de":"Entschuldigung","en":"","timeLimit":40,"audio":true},{"de":"Sonnenbrille","en":"","timeLimit":40,"audio":true},{"de":"Einkauf","en":"the shopping","timeLimit":40,"audio":true},{"de":"Geburtstag","en":"the birthday","timeLimit":40,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 4",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"Mütze","en":"the cap","timeLimit":40,"audio":true},{"de":"Bücherregal","en":"the bookshelf","timeLimit":40,"audio":true},{"de":"Polizei","en":"the police","timeLimit":40,"audio":true},{"de":"Wochenende","en":"the weekend","timeLimit":40,"audio":true},{"de":"freundlich","en":"friendly","timeLimit":40,"audio":true},{"de":"Tomate","en":"the tomato","timeLimit":40,"audio":true},{"de":"beruflich","en":"professional, work-related","timeLimit":40,"audio":true},{"de":"unbekannt","en":"unknown","timeLimit":40,"audio":true},{"de":"Hauptsatz","en":"","timeLimit":40,"audio":true},{"de":"Entschuldigung","en":"","timeLimit":40,"audio":true},{"de":"italienisch","en":"Italian","timeLimit":40,"audio":true},{"de":"Universität","en":"the university","timeLimit":40,"audio":true},{"de":"Sonnenaufgang","en":"the sunrise","timeLimit":40,"audio":true},{"de":"Supermarkt","en":"the supermarket","timeLimit":40,"audio":true},{"de":"automatisch","en":"automatic","timeLimit":40,"audio":true},{"de":"Pullover","en":"the sweater","timeLimit":40,"audio":true},{"de":"Apotheke","en":"the pharmacy","timeLimit":40,"audio":true},{"de":"Frühstück","en":"the breakfast","timeLimit":40,"audio":true},{"de":"Samstagnachmittag","en":"","timeLimit":40,"audio":true},{"de":"Hose","en":"the pants, the trousers","timeLimit":40,"audio":true},{"de":"Zeitschrift","en":"the magazine","timeLimit":40,"audio":true},{"de":"Schneemann","en":"","timeLimit":40,"audio":true},{"de":"langweilig","en":"boring","timeLimit":40,"audio":true},{"de":"Bibliothek","en":"the library","timeLimit":40,"audio":true},{"de":"Straßenbahn","en":"the tram","timeLimit":40,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 5",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"Orange","en":"the orange (fruit)","timeLimit":40,"audio":true},{"de":"Sonnenuntergang","en":"the sunset","timeLimit":40,"audio":true},{"de":"Hauptsatz","en":"","timeLimit":40,"audio":true},{"de":"Haltestelle","en":"the stop","timeLimit":40,"audio":true},{"de":"Wohnzimmer","en":"the living room","timeLimit":40,"audio":true},{"de":"Montagmorgen","en":"","timeLimit":40,"audio":true},{"de":"Zusammensetzung","en":"","timeLimit":40,"audio":true},{"de":"Polizei","en":"the police","timeLimit":40,"audio":true},{"de":"Schulfach","en":"","timeLimit":40,"audio":true},{"de":"Sonnenaufgang","en":"the sunrise","timeLimit":40,"audio":true},{"de":"Wiedersehen","en":"","timeLimit":40,"audio":true},{"de":"Hose","en":"the pants, the trousers","timeLimit":40,"audio":true},{"de":"Wintermantel","en":"","timeLimit":40,"audio":true},{"de":"Straßenbahn","en":"the tram","timeLimit":40,"audio":true},{"de":"Jahreszeit","en":"","timeLimit":40,"audio":true},{"de":"Apfelkuchen","en":"the apple cake","timeLimit":40,"audio":true},{"de":"Eiscreme","en":"","timeLimit":40,"audio":true},{"de":"Geschäft","en":"the shop","timeLimit":40,"audio":true},{"de":"Schlafzimmer","en":"the bedroom","timeLimit":40,"audio":true},{"de":"Krankenhaus","en":"the hospital","timeLimit":40,"audio":true},{"de":"Hausaufgaben","en":"the homework","timeLimit":40,"audio":true},{"de":"Bahnhofstraße","en":"","timeLimit":40,"audio":true},{"de":"Fahrkarte","en":"the ticket","timeLimit":40,"audio":true},{"de":"zufrieden","en":"satisfied, content","timeLimit":40,"audio":true},{"de":"Straßenbahn","en":"the tram","timeLimit":40,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 6",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"Jahreszeit","en":"","timeLimit":40,"audio":true},{"de":"Hausaufgaben","en":"the homework","timeLimit":40,"audio":true},{"de":"U-Bahn","en":"the underground","timeLimit":40,"audio":true},{"de":"Lieblingsbuch","en":"","timeLimit":40,"audio":true},{"de":"Gutenacht","en":"","timeLimit":40,"audio":true},{"de":"Gutenmorgen","en":"","timeLimit":40,"audio":true},{"de":"Fahrkarte","en":"the ticket","timeLimit":40,"audio":true},{"de":"Rechnung","en":"the bill, the invoice","timeLimit":40,"audio":true},{"de":"Geschwister","en":"the siblings","timeLimit":40,"audio":true},{"de":"Entschuldigung","en":"","timeLimit":40,"audio":true},{"de":"Schulfach","en":"","timeLimit":40,"audio":true},{"de":"Wohnzimmer","en":"the living room","timeLimit":40,"audio":true},{"de":"japanisch","en":"Japanese","timeLimit":40,"audio":true},{"de":"Schlafzimmer","en":"the bedroom","timeLimit":40,"audio":true},{"de":"Hausaufgaben","en":"the homework","timeLimit":40,"audio":true},{"de":"Polizei","en":"the police","timeLimit":40,"audio":true},{"de":"Schlafzimmer","en":"the bedroom","timeLimit":40,"audio":true},{"de":"Krankenwagen","en":"","timeLimit":40,"audio":true},{"de":"Mittagessen","en":"the lunch","timeLimit":40,"audio":true},{"de":"willkommen","en":"welcome","timeLimit":40,"audio":true},{"de":"Einkauf","en":"the shopping","timeLimit":40,"audio":true},{"de":"Spülmaschine","en":"","timeLimit":40,"audio":true},{"de":"Lieblingsessen","en":"","timeLimit":40,"audio":true},{"de":"interessant","en":"interesting","timeLimit":40,"audio":true},{"de":"Freitagabend","en":"","timeLimit":40,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 7",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"glücklich","en":"happy","timeLimit":40,"audio":true},{"de":"Bücherregal","en":"the bookshelf","timeLimit":40,"audio":true},{"de":"gemeinsam","en":"together, joint","timeLimit":40,"audio":true},{"de":"Geschirrspüler","en":"","timeLimit":40,"audio":true},{"de":"Krankenhaus","en":"the hospital","timeLimit":40,"audio":true},{"de":"Wiedersehen","en":"","timeLimit":40,"audio":true},{"de":"kompliziert","en":"complicated","timeLimit":40,"audio":true},{"de":"unglaublich","en":"unbelievable","timeLimit":40,"audio":true},{"de":"interessant","en":"interesting","timeLimit":40,"audio":true},{"de":"Sonnenaufgang","en":"the sunrise","timeLimit":40,"audio":true},{"de":"Krankenhaus","en":"the hospital","timeLimit":40,"audio":true},{"de":"Schmetterling","en":"the butterfly","timeLimit":40,"audio":true},{"de":"notwendig","en":"necessary","timeLimit":40,"audio":true},{"de":"Polizeistation","en":"","timeLimit":40,"audio":true},{"de":"japanisch","en":"Japanese","timeLimit":40,"audio":true},{"de":"Zugticket","en":"","timeLimit":40,"audio":true},{"de":"Zusammensetzung","en":"","timeLimit":40,"audio":true},{"de":"Freitagabend","en":"","timeLimit":40,"audio":true},{"de":"Straßenbahn","en":"the tram","timeLimit":40,"audio":true},{"de":"Polizei","en":"the police","timeLimit":40,"audio":true},{"de":"Entschuldigung","en":"","timeLimit":40,"audio":true},{"de":"Orange","en":"the orange (fruit)","timeLimit":40,"audio":true},{"de":"Hauptsatz","en":"","timeLimit":40,"audio":true},{"de":"Geburtstag","en":"the birthday","timeLimit":40,"audio":true},{"de":"Schulfach","en":"","timeLimit":40,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 8",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"Schlafzimmer","en":"the bedroom","timeLimit":40,"audio":true},{"de":"Bahnhofstraße","en":"","timeLimit":40,"audio":true},{"de":"zufrieden","en":"satisfied, content","timeLimit":40,"audio":true},{"de":"Handschuhe","en":"the gloves","timeLimit":40,"audio":true},{"de":"Banane","en":"the banana","timeLimit":40,"audio":true},{"de":"Zeitschrift","en":"the magazine","timeLimit":40,"audio":true},{"de":"neugierig","en":"curious","timeLimit":40,"audio":true},{"de":"Hausschuhe","en":"the slippers","timeLimit":40,"audio":true},{"de":"Regenjacke","en":"the rain jacket","timeLimit":40,"audio":true},{"de":"Gutenabend","en":"","timeLimit":40,"audio":true},{"de":"Jahreszeit","en":"","timeLimit":40,"audio":true},{"de":"Hose","en":"the pants, the trousers","timeLimit":40,"audio":true},{"de":"Montagmorgen","en":"","timeLimit":40,"audio":true},{"de":"Sonnenaufgang","en":"the sunrise","timeLimit":40,"audio":true},{"de":"Krankenwagen","en":"","timeLimit":40,"audio":true},{"de":"Krankenhaus","en":"the hospital","timeLimit":40,"audio":true},{"de":"Gebäude","en":"the building","timeLimit":40,"audio":true},{"de":"Zugticket","en":"","timeLimit":40,"audio":true},{"de":"Wochenende","en":"the weekend","timeLimit":40,"audio":true},{"de":"Polizei","en":"the police","timeLimit":40,"audio":true},{"de":"Frühstück","en":"the breakfast","timeLimit":40,"audio":true},{"de":"Straßenbahn","en":"the tram","timeLimit":40,"audio":true},{"de":"Kleid","en":"the dress","timeLimit":40,"audio":true},{"de":"beruflich","en":"professional, work-related","timeLimit":40,"audio":true},{"de":"Gutenmorgen","en":"","timeLimit":40,"audio":true}],
        },

      ],
    },
  ],
};


export const wordmatchgridGame: Game = {
  id: "word-match-grid",
  title: "Word Match Grid",
  emoji: "🔗",
  description: "Tap matching German and English tiles in a single grid to clear the board. Beat the clock across rounds that get faster each time!",
  category: "vocabulary",
  tags: ["A1","A2"],
  levels: [
    {
      id: "grid-match-1",
      title: "Level 1: Nouns",
      rounds: [
        {
          kind: "grid-match",
          title: "Grid 1",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["der Zustand","the condition, the state"],["das Oktoberfest","the Oktoberfest"],["die Badewanne","the bathtub"],["das Bein","the leg"],["der Schuh","the shoe"],["das Wild","the game (animals)"],["die Altstadt","the old town"],["die Autobahn","the motorway"],["die Gans","the goose"],["das Hochhaus","the high-rise building"]],
        },
        {
          kind: "grid-match",
          title: "Grid 2",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["der Körper","the body"],["die Gebühr","the fee"],["die Tafel","the blackboard"],["der Daumen","the thumb"],["der Abschied","the farewell"],["die Hose","the pants, the trousers"],["die Heidelbeere","the blueberry"],["der Besen","the broom"],["der Herd","the stove"],["die Naht","the seam"]],
        },
        {
          kind: "grid-match",
          title: "Grid 3",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["das Saxophon","the saxophone"],["die Kunstgalerie","the art gallery"],["der Lebenslauf","the CV"],["das Familienmitglied","the family member"],["die Decke","the ceiling; the blanket"],["das Bein","the leg"],["die Bevölkerung","the population"],["die Heidelbeere","the blueberry"],["die Paprika","the bell pepper"],["die Kaution","the deposit"]],
        },
        {
          kind: "grid-match",
          title: "Grid 4",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["das Pfand","the deposit"],["das Bier","the beer"],["der Hausmeister","the caretaker"],["die Waschmaschine","the washing machine"],["die Apotheke","the pharmacy"],["die Naht","the seam"],["der Körper","the body"],["das Hochhaus","the high-rise building"],["der Herd","the stove"],["das Licht","the light"]],
        },
        {
          kind: "grid-match",
          title: "Grid 5",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["die Serie","the series"],["das Oktoberfest","the Oktoberfest"],["das Frühstück inklusive","breakfast included"],["der Sohn","the son"],["der Cousin","the cousin (male)"],["die Gebühr","the fee"],["die Altstadt","the old town"],["das Gefühl","the feeling"],["der Stock","the floor, the storey"],["der Daumen","the thumb"]],
        },
        {
          kind: "grid-match",
          title: "Grid 6",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["die Spinne","the spider"],["der Geburtstag","the birthday"],["die Verletzung","the injury"],["das Gefühl","the feeling"],["der Körper","the body"],["der Besen","the broom"],["die Badewanne","the bathtub"],["der Regen","the rain"],["das Stadttor","the city gate"],["die Serie","the series"]],
        },
        {
          kind: "grid-match",
          title: "Grid 7",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["der Hausmeister","the caretaker"],["die Armbanduhr","the wristwatch"],["das Oktoberfest","the Oktoberfest"],["der Schnee","the snow"],["die Gans","the goose"],["die Naht","the seam"],["die Karte","the card, the map, the ticket"],["die Hose","the pants, the trousers"],["die Tafel","the blackboard"],["der Staubsauger","the vacuum cleaner"]],
        },
        {
          kind: "grid-match",
          title: "Grid 8",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["die Altstadt","the old town"],["der Stock","the floor, the storey"],["die Freizeitbeschäftigung","the leisure activity"],["der Körper","the body"],["der Daumen","the thumb"],["die Möwe","the seagull"],["die Serie","the series"],["die Bevölkerung","the population"],["die Decke","the ceiling; the blanket"],["der Platz","the place, the square, the seat"]],
        },
        {
          kind: "grid-match",
          title: "Grid 9",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["die Badewanne","the bathtub"],["der Mais","the corn"],["das Bäumchen","the little tree"],["der Nachbar","the neighbor (male)"],["der Herd","the stove"],["der Löffel","the spoon"],["die Tomate","the tomato"],["die Paprika","the bell pepper"],["das Bein","the leg"],["die Besprechung","the meeting"]],
        },
        {
          kind: "grid-match",
          title: "Grid 10",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["das Putzmittel","the cleaning product"],["die Freizeitbeschäftigung","the leisure activity"],["die Decke","the ceiling; the blanket"],["die Getränkekarte","the drinks menu"],["der Zustand","the condition, the state"],["der Vogel","the bird"],["die Armbanduhr","the wristwatch"],["das Frühstück inklusive","breakfast included"],["das Pfand","the deposit"],["die Autobahn","the motorway"]],
        },
        {
          kind: "grid-match",
          title: "Grid 11",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["die Karte","the card, the map, the ticket"],["das Familienmitglied","the family member"],["die Kunstgalerie","the art gallery"],["das Bein","the leg"],["die Kaution","the deposit"],["der Fehler","the mistake"],["die Besprechung","the meeting"],["die Naht","the seam"],["der Regen","the rain"],["die Gans","the goose"]],
        },
        {
          kind: "grid-match",
          title: "Grid 12",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["der Platz","the place, the square, the seat"],["das Licht","the light"],["die Karte","the card, the map, the ticket"],["die Gebühr","the fee"],["der Sturm","the storm"],["die Altstadt","the old town"],["der Balkon","the balcony"],["die E-Mail","the email"],["der Schuh","the shoe"],["die Autobahn","the motorway"]],
        },
        {
          kind: "grid-match",
          title: "Grid 13",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["die Möwe","the seagull"],["die Tomate","the tomato"],["die Waschmaschine","the washing machine"],["die Kartoffel","the potato"],["der Cousin","the cousin (male)"],["das Putzmittel","the cleaning product"],["der Knopf","the button"],["das Lied","the song"],["der Körper","the body"],["der Lebenslauf","the CV"]],
        },
        {
          kind: "grid-match",
          title: "Grid 14",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["der Platz","the place, the square, the seat"],["die Spinne","the spider"],["die Karte","the card, the map, the ticket"],["das Stadttor","the city gate"],["das Bäumchen","the little tree"],["der Besen","the broom"],["das Großraumbüro","the open-plan office"],["die Pause","the break"],["das Gefühl","the feeling"],["die Kommode","the chest of drawers"]],
        },
        {
          kind: "grid-match",
          title: "Grid 15",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["die Apotheke","the pharmacy"],["die Freizeitbeschäftigung","the leisure activity"],["das Bier","the beer"],["die Möwe","the seagull"],["die Bevölkerung","the population"],["der Sturm","the storm"],["die Waschmaschine","the washing machine"],["die Serie","the series"],["die Heidelbeere","the blueberry"],["die Gans","the goose"]],
        },
        {
          kind: "grid-match",
          title: "Grid 16",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["der Hausmeister","the caretaker"],["der Cousin","the cousin (male)"],["die Gans","the goose"],["die Verletzung","the injury"],["das Putzmittel","the cleaning product"],["das Bücherregal","the bookshelf"],["die Hauptspeise","the main course"],["der Körper","the body"],["der Platz","the place, the square, the seat"],["der Abschied","the farewell"]],
        },
        {
          kind: "grid-match",
          title: "Grid 17",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["die Kartoffel","the potato"],["die Altstadt","the old town"],["die Kommode","the chest of drawers"],["der Platz","the place, the square, the seat"],["die Tafel","the blackboard"],["die Besprechung","the meeting"],["der Nachbar","the neighbor (male)"],["das Publikum","the audience"],["die Gans","the goose"],["die Stereoanlage","the stereo system"]],
        },
        {
          kind: "grid-match",
          title: "Grid 18",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["das Spiel","the game"],["die Kaution","the deposit"],["die Filmvorführung","the film screening"],["der Herd","the stove"],["das Familienmitglied","the family member"],["die Kartoffel","the potato"],["das Tennis","the tennis"],["die Hauptspeise","the main course"],["die Hose","the pants, the trousers"],["die Verletzung","the injury"]],
        },
        {
          kind: "grid-match",
          title: "Grid 19",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["die Verletzung","the injury"],["die Parade","the parade"],["der Strom","the electricity, the current"],["die Heidelbeere","the blueberry"],["die Kaution","the deposit"],["das Saxophon","the saxophone"],["der Sohn","the son"],["die Tafel","the blackboard"],["das Lied","the song"],["das Familienmitglied","the family member"]],
        },
        {
          kind: "grid-match",
          title: "Grid 20",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["der Balkon","the balcony"],["der Mais","the corn"],["die Hose","the pants, the trousers"],["das Gemüse","the vegetables"],["das Reich","the empire, the realm"],["das Bücherregal","the bookshelf"],["der Daumen","the thumb"],["der Urlauber","the holidaymaker"],["das Tennis","the tennis"],["das Bier","the beer"]],
        },

      ],
    },

    {
      id: "grid-match-2",
      title: "Level 2: More nouns",
      rounds: [
        {
          kind: "grid-match",
          title: "Grid 1",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["das Ding","the thing"],["die Straße","the street"],["die Kirmes","the fair"],["die Aussicht","the view"],["die Etage","the floor, the storey"],["das Ziel","the goal, the destination"],["die Limonade","the lemonade"],["die Torte","the gateau"],["das Radio","the radio"],["die Polizeiwache","the police station"]],
        },
        {
          kind: "grid-match",
          title: "Grid 2",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["das Wohlbefinden","the well-being"],["die Polizeiwache","the police station"],["der Motor","the engine"],["die Schildkröte","the turtle"],["der Vortrag","the lecture, the presentation"],["die Limonade","the lemonade"],["der Wein","the wine"],["die Ehefrau","the wife"],["das Feuer","the fire"],["die Steppe","the steppe"]],
        },
        {
          kind: "grid-match",
          title: "Grid 3",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["die Flaschenpfand","the bottle deposit"],["der Sohn","the son"],["die Tracht","the traditional dress"],["die Ehefrau","the wife"],["der Staatsangehörige","the national"],["die Zahnpasta","the toothpaste"],["der Frost","the frost"],["die Polizeiwache","the police station"],["der Hals","the neck, the throat"],["das Boarding","the boarding"]],
        },
        {
          kind: "grid-match",
          title: "Grid 4",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["der Frost","the frost"],["die Ehefrau","the wife"],["der Vortrag","the lecture, the presentation"],["die Pfote","the paw"],["die Flüssigkeit","the liquid"],["der Müll","the rubbish"],["die Polizeiwache","the police station"],["die Praxis","the practice"],["die Abteilung","the department"],["die Aussicht","the view"]],
        },
        {
          kind: "grid-match",
          title: "Grid 5",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["die Pfote","the paw"],["das Saxophon","the saxophone"],["der Cent","the cent"],["das Blut","the blood"],["die Anrede","the form of address"],["die Tasche","the bag, the pocket"],["das Gesicht","the face"],["die Tracht","the traditional dress"],["die Nachbarschaft","the neighbourhood"],["das Ding","the thing"]],
        },
        {
          kind: "grid-match",
          title: "Grid 6",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["die Laune","the mood"],["der Frühling","the spring"],["die Straßenbahnlinie","the tram line"],["der Sänger","the singer"],["die Parkuhr","the parking meter"],["der Flohmarkt","the flea market"],["die Wiese","the meadow"],["die Kanne","the pot"],["der Müll","the rubbish"],["das Radio","the radio"]],
        },
        {
          kind: "grid-match",
          title: "Grid 7",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["der Wischmopp","the mop"],["die Flüssigkeit","the liquid"],["die Krankschreibung","the sick note"],["der Lokführer","the train driver"],["die Zahnpasta","the toothpaste"],["das Fest","the festival"],["der Lehrer","the teacher (male)"],["der Fahrplan","the timetable"],["der Apfelkuchen","the apple cake"],["die Wäsche","the laundry"]],
        },
        {
          kind: "grid-match",
          title: "Grid 8",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["der Lehrer","the teacher (male)"],["das Waschbecken","the sink"],["die Nachbarschaft","the neighbourhood"],["die Wiese","the meadow"],["der Stundenplan","the timetable"],["das Radio","the radio"],["der Garten","the garden"],["die Straßenbahnlinie","the tram line"],["der Frühling","the spring"],["der Gürtel","the belt"]],
        },
        {
          kind: "grid-match",
          title: "Grid 9",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["die Parkuhr","the parking meter"],["die Zunge","the tongue"],["die Kanne","the pot"],["der Mietvertrag","the rental contract"],["die Zahnpasta","the toothpaste"],["der Verkäufer","the salesperson"],["der Garten","the garden"],["die Torte","the gateau"],["der Hals","the neck, the throat"],["die Etage","the floor, the storey"]],
        },
        {
          kind: "grid-match",
          title: "Grid 10",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["der Durst","the thirst"],["der Gürtel","the belt"],["die Ansage","the announcement"],["der Abteilungsleiter","the department head"],["die Straßenreinigung","the street cleaning"],["die Zahnpasta","the toothpaste"],["der Fahrplan","the timetable"],["der Garten","the garden"],["der Berggipfel","the mountain peak"],["die Zunge","the tongue"]],
        },
        {
          kind: "grid-match",
          title: "Grid 11",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["die Limonade","the lemonade"],["die Glotze","the telly"],["die Nachbarschaft","the neighbourhood"],["das Blut","the blood"],["die Abteilung","the department"],["der Staatsangehörige","the national"],["der Gürtel","the belt"],["der Apfelkuchen","the apple cake"],["der Sohn","the son"],["die Straße","the street"]],
        },
        {
          kind: "grid-match",
          title: "Grid 12",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["der Lokführer","the train driver"],["der Müll","the rubbish"],["die Laune","the mood"],["die Hausaufgaben","the homework"],["die Limonade","the lemonade"],["der Kuchen","the cake"],["die Straßenreinigung","the street cleaning"],["die Haltestelle","the stop"],["der Lehrer","the teacher (male)"],["die Anrede","the form of address"]],
        },
        {
          kind: "grid-match",
          title: "Grid 13",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["der Lehrer","the teacher (male)"],["der Durst","the thirst"],["die Parkuhr","the parking meter"],["die Bewegung","the exercise"],["die Abteilung","the department"],["der Garten","the garden"],["das Waschbecken","the sink"],["die Praxis","the practice"],["das Ziel","the goal, the destination"],["das Kleid","the dress"]],
        },
        {
          kind: "grid-match",
          title: "Grid 14",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["der Apfelkuchen","the apple cake"],["der Gürtel","the belt"],["das Gesicht","the face"],["die Suppe","the soup"],["der Kühlschrank","the fridge"],["das Boarding","the boarding"],["der Flohmarkt","the flea market"],["der Wal","the whale"],["das Fest","the festival"],["der Regenschirm","the umbrella"]],
        },
        {
          kind: "grid-match",
          title: "Grid 15",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["die Hausaufgaben","the homework"],["der Staatsangehörige","the national"],["die Ehefrau","the wife"],["der Apfelkuchen","the apple cake"],["die Einwohner","the inhabitants"],["die Laune","the mood"],["die Suppe","the soup"],["der Stundenplan","the timetable"],["der Teller","the plate"],["der Sänger","the singer"]],
        },
        {
          kind: "grid-match",
          title: "Grid 16",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["die Limonade","the lemonade"],["die Abteilung","the department"],["die Kirmes","the fair"],["der Mietvertrag","the rental contract"],["der Papierkorb","the wastepaper basket"],["der Wischmopp","the mop"],["das Saxophon","the saxophone"],["der Kaufmann","the merchant"],["der Löffel","the spoon"],["der Campingplatz","the campsite"]],
        },
        {
          kind: "grid-match",
          title: "Grid 17",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["die Ehefrau","the wife"],["das Feuer","the fire"],["der Staatsangehörige","the national"],["der Durst","the thirst"],["der Sohn","the son"],["das Fest","the festival"],["die Limonade","the lemonade"],["das Wohlbefinden","the well-being"],["die Praxis","the practice"],["die Nachbarschaft","the neighbourhood"]],
        },
        {
          kind: "grid-match",
          title: "Grid 18",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["der Ranzen","the satchel"],["der Lehrer","the teacher (male)"],["der Löffel","the spoon"],["das Ding","the thing"],["die Ehefrau","the wife"],["der Kuchen","the cake"],["der Geburtsort","the birthplace"],["das Waschbecken","the sink"],["der Frühling","the spring"],["der Apfelkuchen","the apple cake"]],
        },
        {
          kind: "grid-match",
          title: "Grid 19",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["der Mietvertrag","the rental contract"],["der Apfelkuchen","the apple cake"],["der Kuchen","the cake"],["das Ding","the thing"],["die Anrede","the form of address"],["die Zahnpasta","the toothpaste"],["die Straßenreinigung","the street cleaning"],["der Garten","the garden"],["die Glotze","the telly"],["das Pferd","the horse"]],
        },
        {
          kind: "grid-match",
          title: "Grid 20",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["die Bewegung","the exercise"],["der Keller","the cellar"],["die Flaschenpfand","the bottle deposit"],["die Tasche","the bag, the pocket"],["die Hausaufgaben","the homework"],["das Ding","the thing"],["die Haltestelle","the stop"],["der Ausgang","the exit"],["der Abteilungsleiter","the department head"],["das Ziel","the goal, the destination"]],
        },

      ],
    },

    {
      id: "grid-match-3",
      title: "Level 3: Longer words",
      rounds: [
        {
          kind: "grid-match",
          title: "Grid 1",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["der Vormittag","the morning (before noon)"],["der Schaden","the damage"],["der Bauch","the belly"],["das Essen","the food, the meal"],["die Gehaltserhöhung","the pay rise"],["der Finger","the finger"],["das Medikament","the medicine"],["die Fahrkartenkontrolle","the ticket control"],["das Feld","the field"],["das Einzelzimmer","the single room"]],
        },
        {
          kind: "grid-match",
          title: "Grid 2",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["der Läufer","the rug"],["die Kontrolle","the check"],["die Brosche","the brooch"],["die Fahrkartenkontrolle","the ticket control"],["das Hemd","the shirt"],["der Stundenplan","the timetable"],["die Serviette","the napkin"],["die Rundreise","the tour"],["das Medikament","the medicine"],["der Donnerstag","Thursday"]],
        },
        {
          kind: "grid-match",
          title: "Grid 3",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["das Mineralwasser","the mineral water"],["das Gefühl","the feeling"],["das Wohnzimmer","the living room"],["das Dessert","the dessert"],["die Gans","the goose"],["der Bericht","the report"],["das Konzerthaus","the concert hall"],["die Hälfte","the half"],["das Lied","the song"],["die Nachrichten","the news"]],
        },
        {
          kind: "grid-match",
          title: "Grid 4",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["die Allergie","the allergy"],["das Bücherregal","the bookshelf"],["die Stadtmauer","the city wall"],["der Norden","the north"],["der Honig","the honey"],["der Füller","the fountain pen"],["der Donnerstag","Thursday"],["die Tablette","the tablet"],["der Baum","the tree"],["das Sofa","the sofa"]],
        },
        {
          kind: "grid-match",
          title: "Grid 5",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["das Lied","the song"],["das Gedächtnis","the memory"],["das Wandern","the hiking"],["das Hobby","the hobby"],["der Baum","the tree"],["der Bauch","the belly"],["der Spiegel","the mirror"],["der Schnabel","the beak"],["der Stern","the star"],["die Stadtmauer","the city wall"]],
        },
        {
          kind: "grid-match",
          title: "Grid 6",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["der Bauch","the belly"],["die Straße","the street"],["die Kunstgalerie","the art gallery"],["die Tablette","the tablet"],["das Fenster","the window"],["der Spiegel","the mirror"],["das Feld","the field"],["das Hobby","the hobby"],["die Nachbarschaft","the neighbourhood"],["der Anruf","the call"]],
        },
        {
          kind: "grid-match",
          title: "Grid 7",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["die Person","the person"],["die Hälfte","the half"],["das Medikament","the medicine"],["die Nachrichten","the news"],["der Stern","the star"],["die Gurke","the cucumber"],["das Grad","the degree"],["das Wohlbefinden","the well-being"],["der Abschied","the farewell"],["die Fahrkartenkontrolle","the ticket control"]],
        },
        {
          kind: "grid-match",
          title: "Grid 8",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["das Hemd","the shirt"],["das Wandern","the hiking"],["die Rundreise","the tour"],["der Bericht","the report"],["der Finger","the finger"],["die Bratwurst","the grilled sausage"],["der Reis","the rice"],["der Schnabel","the beak"],["der Stundenplan","the timetable"],["der Füller","the fountain pen"]],
        },
        {
          kind: "grid-match",
          title: "Grid 9",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["die Qualle","the jellyfish"],["der Reis","the rice"],["die Allergie","the allergy"],["die Welle","the wave"],["die Person","the person"],["das Grad","the degree"],["das Wort","the word"],["der Stern","the star"],["das Mineralwasser","the mineral water"],["die Nachrichten","the news"]],
        },
        {
          kind: "grid-match",
          title: "Grid 10",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["der Haushalt","the household"],["der Salat","the salad, the lettuce"],["das Heft","the notebook"],["der Finger","the finger"],["der Spiegel","the mirror"],["der Läufer","the rug"],["das Sofa","the sofa"],["das Gedächtnis","the memory"],["das Gefühl","the feeling"],["der Strom","the electricity, the current"]],
        },
        {
          kind: "grid-match",
          title: "Grid 11",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["der Honig","the honey"],["das Zelt","the tent"],["der Vormittag","the morning (before noon)"],["der Salat","the salad, the lettuce"],["die Gehaltserhöhung","the pay rise"],["das Hemd","the shirt"],["der Stammgast","the regular"],["der Tiger","the tiger"],["der Drucker","the printer"],["das Publikum","the audience"]],
        },
        {
          kind: "grid-match",
          title: "Grid 12",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["der Salat","the salad, the lettuce"],["das Publikum","the audience"],["das Klassenzimmer","the classroom"],["das Hemd","the shirt"],["die Bratwurst","the grilled sausage"],["die Tankstelle","the petrol station"],["die Gitarre","the guitar"],["das Medikament","the medicine"],["die Gans","the goose"],["der Füller","the fountain pen"]],
        },
        {
          kind: "grid-match",
          title: "Grid 13",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["der Läufer","the rug"],["der Freundeskreis","the circle of friends"],["das Essen","the food, the meal"],["das Klassenzimmer","the classroom"],["der Stern","the star"],["der Norden","the north"],["der Schaden","the damage"],["die Qualle","the jellyfish"],["die Tablette","the tablet"],["der Vormittag","the morning (before noon)"]],
        },
        {
          kind: "grid-match",
          title: "Grid 14",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["die Ente","the duck"],["das Feld","the field"],["die Postkarte","the postcard"],["der Hagel","the hail"],["die Hälfte","the half"],["die Gurke","the cucumber"],["der Salat","the salad, the lettuce"],["die Stadtmauer","the city wall"],["das Mineralwasser","the mineral water"],["das Konzerthaus","the concert hall"]],
        },
        {
          kind: "grid-match",
          title: "Grid 15",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["das Heft","the notebook"],["die Qualle","the jellyfish"],["die Hand","the hand"],["der Bau","the building site"],["der Vormittag","the morning (before noon)"],["der Lieferant","the supplier"],["die Nase","the nose"],["der Haushalt","the household"],["das Lied","the song"],["die Tablette","the tablet"]],
        },
        {
          kind: "grid-match",
          title: "Grid 16",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["die Allergie","the allergy"],["die Serviette","the napkin"],["die Rückgabe","the return"],["der Pass","the passport"],["das Hobby","the hobby"],["das Haustier","the pet"],["der Stammgast","the regular"],["das Fenster","the window"],["das Hemd","the shirt"],["die Kunstgalerie","the art gallery"]],
        },
        {
          kind: "grid-match",
          title: "Grid 17",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["das Radfahren","the cycling"],["die Mülltonne","the dustbin"],["die Kontrolle","the check"],["der Norden","the north"],["das Gedächtnis","the memory"],["das Mineralwasser","the mineral water"],["das Wohnzimmer","the living room"],["der Freundeskreis","the circle of friends"],["der Zahn","the tooth"],["die Hand","the hand"]],
        },
        {
          kind: "grid-match",
          title: "Grid 18",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["der Magen","the stomach"],["der Storch","the stork"],["das Haustier","the pet"],["der Norden","the north"],["der Pass","the passport"],["das Mineralwasser","the mineral water"],["der Bau","the building site"],["die Rundreise","the tour"],["das Wort","the word"],["das Publikum","the audience"]],
        },
        {
          kind: "grid-match",
          title: "Grid 19",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["der Reis","the rice"],["das Gedächtnis","the memory"],["das Fenster","the window"],["der Schinken","the ham"],["der Donnerstag","Thursday"],["der Schnabel","the beak"],["der Drucker","the printer"],["der Urlaub","the vacation"],["das Bücherregal","the bookshelf"],["die Hälfte","the half"]],
        },
        {
          kind: "grid-match",
          title: "Grid 20",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["der Bruch","the fracture"],["das Wandern","the hiking"],["der Honig","the honey"],["die Gans","the goose"],["die Mülltonne","the dustbin"],["das Hobby","the hobby"],["die Person","the person"],["die Rückgabe","the return"],["der Baum","the tree"],["die Nase","the nose"]],
        },

      ],
    },
  ],
};
