import type { Game } from "./schema";

export const ninewordsGame: Game = {
  id: "nine-words",
  title: "9 Words",
  emoji: "🧩",
  description: "Nine scrambled German words, 30 seconds each. Tap the letters in the right order before the clock runs out.",
  category: "vocabulary",
  tags: ["A1","A2"],
  levels: [
    {
      id: "nine-words-1",
      title: "Level 1: Short words",
      rounds: [
        {
          kind: "scramble",
          title: "Round 1",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"genau","en":"exact, exactly","timeLimit":30,"audio":true},{"de":"neu","en":"new","timeLimit":30,"audio":true},{"de":"satt","en":"full (after eating)","timeLimit":30,"audio":true},{"de":"preis","en":"","timeLimit":30,"audio":true},{"de":"teuer","en":"expensive","timeLimit":30,"audio":true},{"de":"tag","en":"","timeLimit":30,"audio":true},{"de":"euer","en":"your (plural informal)","timeLimit":30,"audio":true},{"de":"spielen","en":"","timeLimit":30,"audio":true},{"de":"hören","en":"","timeLimit":30,"audio":true},{"de":"grün","en":"green","timeLimit":30,"audio":true},{"de":"laut","en":"loud","timeLimit":30,"audio":true},{"de":"arzt","en":"","timeLimit":30,"audio":true},{"de":"hund","en":"","timeLimit":30,"audio":true},{"de":"fertig","en":"finished, ready","timeLimit":30,"audio":true},{"de":"film","en":"","timeLimit":30,"audio":true},{"de":"taxi","en":"","timeLimit":30,"audio":true},{"de":"dunkel","en":"dark","timeLimit":30,"audio":true},{"de":"lernen","en":"","timeLimit":30,"audio":true},{"de":"frau","en":"","timeLimit":30,"audio":true},{"de":"regen","en":"","timeLimit":30,"audio":true},{"de":"name","en":"","timeLimit":30,"audio":true},{"de":"ruhig","en":"quiet, calm","timeLimit":30,"audio":true},{"de":"euro","en":"","timeLimit":30,"audio":true},{"de":"eine","en":"a, one (feminine)","timeLimit":30,"audio":true},{"de":"huhn","en":"","timeLimit":30,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 2",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"hund","en":"","timeLimit":30,"audio":true},{"de":"hand","en":"","timeLimit":30,"audio":true},{"de":"finden","en":"","timeLimit":30,"audio":true},{"de":"kaffee","en":"","timeLimit":30,"audio":true},{"de":"hell","en":"bright, light","timeLimit":30,"audio":true},{"de":"sehen","en":"","timeLimit":30,"audio":true},{"de":"post","en":"","timeLimit":30,"audio":true},{"de":"bett","en":"","timeLimit":30,"audio":true},{"de":"leicht","en":"easy, light","timeLimit":30,"audio":true},{"de":"klein","en":"small","timeLimit":30,"audio":true},{"de":"zug","en":"","timeLimit":30,"audio":true},{"de":"besser","en":"better","timeLimit":30,"audio":true},{"de":"dunkel","en":"dark","timeLimit":30,"audio":true},{"de":"mittag","en":"","timeLimit":30,"audio":true},{"de":"nase","en":"","timeLimit":30,"audio":true},{"de":"hemd","en":"","timeLimit":30,"audio":true},{"de":"stuhl","en":"","timeLimit":30,"audio":true},{"de":"blume","en":"","timeLimit":30,"audio":true},{"de":"eng","en":"narrow, tight","timeLimit":30,"audio":true},{"de":"spät","en":"late","timeLimit":30,"audio":true},{"de":"kirche","en":"","timeLimit":30,"audio":true},{"de":"gelb","en":"yellow","timeLimit":30,"audio":true},{"de":"huhn","en":"","timeLimit":30,"audio":true},{"de":"trinken","en":"","timeLimit":30,"audio":true},{"de":"hübsch","en":"pretty","timeLimit":30,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 3",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"sagen","en":"","timeLimit":30,"audio":true},{"de":"hose","en":"","timeLimit":30,"audio":true},{"de":"mund","en":"","timeLimit":30,"audio":true},{"de":"hund","en":"","timeLimit":30,"audio":true},{"de":"klein","en":"small","timeLimit":30,"audio":true},{"de":"stuhl","en":"","timeLimit":30,"audio":true},{"de":"blau","en":"blue","timeLimit":30,"audio":true},{"de":"alt","en":"old","timeLimit":30,"audio":true},{"de":"gut","en":"good","timeLimit":30,"audio":true},{"de":"schaf","en":"","timeLimit":30,"audio":true},{"de":"mond","en":"","timeLimit":30,"audio":true},{"de":"selten","en":"rare, seldom","timeLimit":30,"audio":true},{"de":"fest","en":"firm, fixed","timeLimit":30,"audio":true},{"de":"spiel","en":"","timeLimit":30,"audio":true},{"de":"regen","en":"","timeLimit":30,"audio":true},{"de":"tee","en":"","timeLimit":30,"audio":true},{"de":"solch","en":"such","timeLimit":30,"audio":true},{"de":"billig","en":"cheap","timeLimit":30,"audio":true},{"de":"häufig","en":"frequent","timeLimit":30,"audio":true},{"de":"vier","en":"four","timeLimit":30,"audio":true},{"de":"farbe","en":"","timeLimit":30,"audio":true},{"de":"apfel","en":"","timeLimit":30,"audio":true},{"de":"warten","en":"","timeLimit":30,"audio":true},{"de":"lied","en":"","timeLimit":30,"audio":true},{"de":"arzt","en":"","timeLimit":30,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 4",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"schule","en":"","timeLimit":30,"audio":true},{"de":"egal","en":"all the same","timeLimit":30,"audio":true},{"de":"hand","en":"","timeLimit":30,"audio":true},{"de":"kleid","en":"","timeLimit":30,"audio":true},{"de":"mund","en":"","timeLimit":30,"audio":true},{"de":"vier","en":"four","timeLimit":30,"audio":true},{"de":"helfen","en":"","timeLimit":30,"audio":true},{"de":"lang","en":"long","timeLimit":30,"audio":true},{"de":"frisch","en":"fresh","timeLimit":30,"audio":true},{"de":"hell","en":"bright, light","timeLimit":30,"audio":true},{"de":"ruhig","en":"quiet, calm","timeLimit":30,"audio":true},{"de":"normal","en":"normal","timeLimit":30,"audio":true},{"de":"kurz","en":"short","timeLimit":30,"audio":true},{"de":"arm","en":"","timeLimit":30,"audio":true},{"de":"kochen","en":"","timeLimit":30,"audio":true},{"de":"tee","en":"","timeLimit":30,"audio":true},{"de":"eng","en":"narrow, tight","timeLimit":30,"audio":true},{"de":"jeder","en":"every, each","timeLimit":30,"audio":true},{"de":"spiel","en":"","timeLimit":30,"audio":true},{"de":"genau","en":"exact, exactly","timeLimit":30,"audio":true},{"de":"milch","en":"","timeLimit":30,"audio":true},{"de":"monat","en":"","timeLimit":30,"audio":true},{"de":"ihr","en":"her, their, you (plural)","timeLimit":30,"audio":true},{"de":"auge","en":"","timeLimit":30,"audio":true},{"de":"hund","en":"","timeLimit":30,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 5",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"tür","en":"","timeLimit":30,"audio":true},{"de":"eng","en":"narrow, tight","timeLimit":30,"audio":true},{"de":"der","en":"the (masculine)","timeLimit":30,"audio":true},{"de":"spielen","en":"","timeLimit":30,"audio":true},{"de":"post","en":"","timeLimit":30,"audio":true},{"de":"bett","en":"","timeLimit":30,"audio":true},{"de":"blau","en":"blue","timeLimit":30,"audio":true},{"de":"jeder","en":"every, each","timeLimit":30,"audio":true},{"de":"brot","en":"","timeLimit":30,"audio":true},{"de":"schuh","en":"","timeLimit":30,"audio":true},{"de":"lehrer","en":"","timeLimit":30,"audio":true},{"de":"stark","en":"strong","timeLimit":30,"audio":true},{"de":"park","en":"","timeLimit":30,"audio":true},{"de":"frisch","en":"fresh","timeLimit":30,"audio":true},{"de":"rund","en":"round","timeLimit":30,"audio":true},{"de":"bus","en":"","timeLimit":30,"audio":true},{"de":"maus","en":"","timeLimit":30,"audio":true},{"de":"euer","en":"your (plural informal)","timeLimit":30,"audio":true},{"de":"morgen","en":"","timeLimit":30,"audio":true},{"de":"spät","en":"late","timeLimit":30,"audio":true},{"de":"farbe","en":"","timeLimit":30,"audio":true},{"de":"kurz","en":"short","timeLimit":30,"audio":true},{"de":"egal","en":"all the same","timeLimit":30,"audio":true},{"de":"preis","en":"","timeLimit":30,"audio":true},{"de":"trinken","en":"","timeLimit":30,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 6",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"kurz","en":"short","timeLimit":30,"audio":true},{"de":"jahr","en":"","timeLimit":30,"audio":true},{"de":"mond","en":"","timeLimit":30,"audio":true},{"de":"nase","en":"","timeLimit":30,"audio":true},{"de":"schön","en":"beautiful, nice","timeLimit":30,"audio":true},{"de":"machen","en":"","timeLimit":30,"audio":true},{"de":"früh","en":"early","timeLimit":30,"audio":true},{"de":"nah","en":"near, close","timeLimit":30,"audio":true},{"de":"vier","en":"four","timeLimit":30,"audio":true},{"de":"heft","en":"","timeLimit":30,"audio":true},{"de":"pferd","en":"","timeLimit":30,"audio":true},{"de":"suchen","en":"","timeLimit":30,"audio":true},{"de":"maus","en":"","timeLimit":30,"audio":true},{"de":"dick","en":"thick, fat","timeLimit":30,"audio":true},{"de":"vogel","en":"","timeLimit":30,"audio":true},{"de":"spieler","en":"","timeLimit":30,"audio":true},{"de":"eine","en":"a, one (feminine)","timeLimit":30,"audio":true},{"de":"wald","en":"","timeLimit":30,"audio":true},{"de":"frisch","en":"fresh","timeLimit":30,"audio":true},{"de":"mittag","en":"","timeLimit":30,"audio":true},{"de":"blume","en":"","timeLimit":30,"audio":true},{"de":"auge","en":"","timeLimit":30,"audio":true},{"de":"bier","en":"","timeLimit":30,"audio":true},{"de":"lesen","en":"","timeLimit":30,"audio":true},{"de":"morgen","en":"","timeLimit":30,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 7",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"heiß","en":"hot","timeLimit":30,"audio":true},{"de":"letzt","en":"last","timeLimit":30,"audio":true},{"de":"gabel","en":"","timeLimit":30,"audio":true},{"de":"hand","en":"","timeLimit":30,"audio":true},{"de":"see","en":"","timeLimit":30,"audio":true},{"de":"kaufen","en":"","timeLimit":30,"audio":true},{"de":"fisch","en":"","timeLimit":30,"audio":true},{"de":"essen","en":"","timeLimit":30,"audio":true},{"de":"warm","en":"warm","timeLimit":30,"audio":true},{"de":"kochen","en":"","timeLimit":30,"audio":true},{"de":"eng","en":"narrow, tight","timeLimit":30,"audio":true},{"de":"die","en":"the (feminine)","timeLimit":30,"audio":true},{"de":"nah","en":"near, close","timeLimit":30,"audio":true},{"de":"sich","en":"oneself, himself, herself","timeLimit":30,"audio":true},{"de":"rund","en":"round","timeLimit":30,"audio":true},{"de":"wand","en":"","timeLimit":30,"audio":true},{"de":"straße","en":"","timeLimit":30,"audio":true},{"de":"cent","en":"","timeLimit":30,"audio":true},{"de":"auge","en":"","timeLimit":30,"audio":true},{"de":"sagen","en":"","timeLimit":30,"audio":true},{"de":"weit","en":"far, wide","timeLimit":30,"audio":true},{"de":"euer","en":"your (plural informal)","timeLimit":30,"audio":true},{"de":"name","en":"","timeLimit":30,"audio":true},{"de":"dünn","en":"thin","timeLimit":30,"audio":true},{"de":"auto","en":"","timeLimit":30,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 8",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"kühl","en":"cool","timeLimit":30,"audio":true},{"de":"frisch","en":"fresh","timeLimit":30,"audio":true},{"de":"abend","en":"","timeLimit":30,"audio":true},{"de":"kuh","en":"","timeLimit":30,"audio":true},{"de":"kommen","en":"","timeLimit":30,"audio":true},{"de":"stern","en":"","timeLimit":30,"audio":true},{"de":"stift","en":"","timeLimit":30,"audio":true},{"de":"farbig","en":"colored","timeLimit":30,"audio":true},{"de":"morgen","en":"","timeLimit":30,"audio":true},{"de":"sie","en":"she, they","timeLimit":30,"audio":true},{"de":"kein","en":"no, not a","timeLimit":30,"audio":true},{"de":"regen","en":"","timeLimit":30,"audio":true},{"de":"klein","en":"small","timeLimit":30,"audio":true},{"de":"genau","en":"exact, exactly","timeLimit":30,"audio":true},{"de":"bett","en":"","timeLimit":30,"audio":true},{"de":"jacke","en":"","timeLimit":30,"audio":true},{"de":"post","en":"","timeLimit":30,"audio":true},{"de":"fragen","en":"","timeLimit":30,"audio":true},{"de":"markt","en":"","timeLimit":30,"audio":true},{"de":"park","en":"","timeLimit":30,"audio":true},{"de":"woche","en":"","timeLimit":30,"audio":true},{"de":"zwei","en":"two","timeLimit":30,"audio":true},{"de":"zimmer","en":"","timeLimit":30,"audio":true},{"de":"spielen","en":"","timeLimit":30,"audio":true},{"de":"nah","en":"near, close","timeLimit":30,"audio":true}],
        },

      ],
    },

    {
      id: "nine-words-2",
      title: "Level 2: Medium words",
      rounds: [
        {
          kind: "scramble",
          title: "Round 1",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"dezember","en":"","timeLimit":30,"audio":true},{"de":"mittwoch","en":"","timeLimit":30,"audio":true},{"de":"mutter","en":"","timeLimit":30,"audio":true},{"de":"fünfzig","en":"fifty","timeLimit":30,"audio":true},{"de":"unbekannt","en":"unknown","timeLimit":30,"audio":true},{"de":"dunkel","en":"dark","timeLimit":30,"audio":true},{"de":"freundin","en":"","timeLimit":30,"audio":true},{"de":"nervös","en":"nervous","timeLimit":30,"audio":true},{"de":"zimmer","en":"","timeLimit":30,"audio":true},{"de":"glücklich","en":"happy","timeLimit":30,"audio":true},{"de":"garten","en":"","timeLimit":30,"audio":true},{"de":"küche","en":"","timeLimit":30,"audio":true},{"de":"direkt","en":"direct, straight","timeLimit":30,"audio":true},{"de":"schnell","en":"fast, quick","timeLimit":30,"audio":true},{"de":"gepäck","en":"","timeLimit":30,"audio":true},{"de":"jemand","en":"someone","timeLimit":30,"audio":true},{"de":"selten","en":"rare, seldom","timeLimit":30,"audio":true},{"de":"geburtstag","en":"","timeLimit":30,"audio":true},{"de":"teppich","en":"","timeLimit":30,"audio":true},{"de":"adresse","en":"","timeLimit":30,"audio":true},{"de":"banane","en":"","timeLimit":30,"audio":true},{"de":"bewölkt","en":"cloudy","timeLimit":30,"audio":true},{"de":"fertig","en":"finished, ready","timeLimit":30,"audio":true},{"de":"sommer","en":"","timeLimit":30,"audio":true},{"de":"japanisch","en":"Japanese","timeLimit":30,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 2",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"dunkel","en":"dark","timeLimit":30,"audio":true},{"de":"sonntag","en":"","timeLimit":30,"audio":true},{"de":"gepäck","en":"","timeLimit":30,"audio":true},{"de":"fünfzehn","en":"fifteen","timeLimit":30,"audio":true},{"de":"frühling","en":"","timeLimit":30,"audio":true},{"de":"rechnung","en":"","timeLimit":30,"audio":true},{"de":"banane","en":"","timeLimit":30,"audio":true},{"de":"verkäufer","en":"","timeLimit":30,"audio":true},{"de":"typisch","en":"typical","timeLimit":30,"audio":true},{"de":"doppelt","en":"double","timeLimit":30,"audio":true},{"de":"nachbar","en":"","timeLimit":30,"audio":true},{"de":"august","en":"","timeLimit":30,"audio":true},{"de":"supermarkt","en":"","timeLimit":30,"audio":true},{"de":"reise","en":"","timeLimit":30,"audio":true},{"de":"nummer","en":"","timeLimit":30,"audio":true},{"de":"selten","en":"rare, seldom","timeLimit":30,"audio":true},{"de":"garten","en":"","timeLimit":30,"audio":true},{"de":"hotel","en":"","timeLimit":30,"audio":true},{"de":"normal","en":"normal","timeLimit":30,"audio":true},{"de":"gabel","en":"","timeLimit":30,"audio":true},{"de":"niemand","en":"nobody","timeLimit":30,"audio":true},{"de":"lehrer","en":"","timeLimit":30,"audio":true},{"de":"farbig","en":"colored","timeLimit":30,"audio":true},{"de":"japanisch","en":"Japanese","timeLimit":30,"audio":true},{"de":"wochenende","en":"","timeLimit":30,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 3",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"gepäck","en":"","timeLimit":30,"audio":true},{"de":"gabel","en":"","timeLimit":30,"audio":true},{"de":"juni","en":"","timeLimit":30,"audio":true},{"de":"spiegel","en":"","timeLimit":30,"audio":true},{"de":"beruflich","en":"professional, work-related","timeLimit":30,"audio":true},{"de":"fertig","en":"finished, ready","timeLimit":30,"audio":true},{"de":"häufig","en":"frequent","timeLimit":30,"audio":true},{"de":"japanisch","en":"Japanese","timeLimit":30,"audio":true},{"de":"langsam","en":"slow","timeLimit":30,"audio":true},{"de":"abendessen","en":"","timeLimit":30,"audio":true},{"de":"küche","en":"","timeLimit":30,"audio":true},{"de":"frühling","en":"","timeLimit":30,"audio":true},{"de":"bewölkt","en":"cloudy","timeLimit":30,"audio":true},{"de":"notwendig","en":"necessary","timeLimit":30,"audio":true},{"de":"schwester","en":"","timeLimit":30,"audio":true},{"de":"computer","en":"","timeLimit":30,"audio":true},{"de":"schnell","en":"fast, quick","timeLimit":30,"audio":true},{"de":"niemand","en":"nobody","timeLimit":30,"audio":true},{"de":"schokolade","en":"","timeLimit":30,"audio":true},{"de":"montag","en":"","timeLimit":30,"audio":true},{"de":"krankenhaus","en":"","timeLimit":30,"audio":true},{"de":"museum","en":"","timeLimit":30,"audio":true},{"de":"messer","en":"","timeLimit":30,"audio":true},{"de":"sonntag","en":"","timeLimit":30,"audio":true},{"de":"freundin","en":"","timeLimit":30,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 4",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"fünfzig","en":"fifty","timeLimit":30,"audio":true},{"de":"kellner","en":"","timeLimit":30,"audio":true},{"de":"august","en":"","timeLimit":30,"audio":true},{"de":"abendessen","en":"","timeLimit":30,"audio":true},{"de":"gemeinsam","en":"together, joint","timeLimit":30,"audio":true},{"de":"dunkel","en":"dark","timeLimit":30,"audio":true},{"de":"deutsch","en":"German","timeLimit":30,"audio":true},{"de":"banane","en":"","timeLimit":30,"audio":true},{"de":"oktober","en":"","timeLimit":30,"audio":true},{"de":"selten","en":"rare, seldom","timeLimit":30,"audio":true},{"de":"japanisch","en":"Japanese","timeLimit":30,"audio":true},{"de":"leicht","en":"easy, light","timeLimit":30,"audio":true},{"de":"löffel","en":"","timeLimit":30,"audio":true},{"de":"computer","en":"","timeLimit":30,"audio":true},{"de":"januar","en":"","timeLimit":30,"audio":true},{"de":"schwester","en":"","timeLimit":30,"audio":true},{"de":"kartoffel","en":"","timeLimit":30,"audio":true},{"de":"zeitung","en":"","timeLimit":30,"audio":true},{"de":"geschäft","en":"","timeLimit":30,"audio":true},{"de":"sicher","en":"safe, certain","timeLimit":30,"audio":true},{"de":"fahrkarte","en":"","timeLimit":30,"audio":true},{"de":"frühling","en":"","timeLimit":30,"audio":true},{"de":"schule","en":"","timeLimit":30,"audio":true},{"de":"mittwoch","en":"","timeLimit":30,"audio":true},{"de":"niemand","en":"nobody","timeLimit":30,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 5",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"computer","en":"","timeLimit":30,"audio":true},{"de":"langsam","en":"slow","timeLimit":30,"audio":true},{"de":"hotel","en":"","timeLimit":30,"audio":true},{"de":"welcher","en":"which","timeLimit":30,"audio":true},{"de":"student","en":"","timeLimit":30,"audio":true},{"de":"freundin","en":"","timeLimit":30,"audio":true},{"de":"beruflich","en":"professional, work-related","timeLimit":30,"audio":true},{"de":"spiegel","en":"","timeLimit":30,"audio":true},{"de":"dezember","en":"","timeLimit":30,"audio":true},{"de":"zeitung","en":"","timeLimit":30,"audio":true},{"de":"telefon","en":"","timeLimit":30,"audio":true},{"de":"löffel","en":"","timeLimit":30,"audio":true},{"de":"neugierig","en":"curious","timeLimit":30,"audio":true},{"de":"montag","en":"","timeLimit":30,"audio":true},{"de":"rechnung","en":"","timeLimit":30,"audio":true},{"de":"sonntag","en":"","timeLimit":30,"audio":true},{"de":"lehrer","en":"","timeLimit":30,"audio":true},{"de":"apotheke","en":"","timeLimit":30,"audio":true},{"de":"dieser","en":"this","timeLimit":30,"audio":true},{"de":"oktober","en":"","timeLimit":30,"audio":true},{"de":"winter","en":"","timeLimit":30,"audio":true},{"de":"frisch","en":"fresh","timeLimit":30,"audio":true},{"de":"frühstück","en":"","timeLimit":30,"audio":true},{"de":"dunkel","en":"dark","timeLimit":30,"audio":true},{"de":"reise","en":"","timeLimit":30,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 6",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"fenster","en":"","timeLimit":30,"audio":true},{"de":"farbig","en":"colored","timeLimit":30,"audio":true},{"de":"wichtig","en":"important","timeLimit":30,"audio":true},{"de":"einzeln","en":"single, separate","timeLimit":30,"audio":true},{"de":"montag","en":"","timeLimit":30,"audio":true},{"de":"billig","en":"cheap","timeLimit":30,"audio":true},{"de":"niedrig","en":"low","timeLimit":30,"audio":true},{"de":"gültig","en":"valid","timeLimit":30,"audio":true},{"de":"mutter","en":"","timeLimit":30,"audio":true},{"de":"richtig","en":"correct, right","timeLimit":30,"audio":true},{"de":"falsch","en":"wrong","timeLimit":30,"audio":true},{"de":"supermarkt","en":"","timeLimit":30,"audio":true},{"de":"gläser","en":"","timeLimit":30,"audio":true},{"de":"welcher","en":"which","timeLimit":30,"audio":true},{"de":"schule","en":"","timeLimit":30,"audio":true},{"de":"häufig","en":"frequent","timeLimit":30,"audio":true},{"de":"günstig","en":"cheap, favorable","timeLimit":30,"audio":true},{"de":"dunkel","en":"dark","timeLimit":30,"audio":true},{"de":"wochenende","en":"","timeLimit":30,"audio":true},{"de":"doppelt","en":"double","timeLimit":30,"audio":true},{"de":"küche","en":"","timeLimit":30,"audio":true},{"de":"nummer","en":"","timeLimit":30,"audio":true},{"de":"frühling","en":"","timeLimit":30,"audio":true},{"de":"teppich","en":"","timeLimit":30,"audio":true},{"de":"dezember","en":"","timeLimit":30,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 7",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"direkt","en":"direct, straight","timeLimit":30,"audio":true},{"de":"apotheke","en":"","timeLimit":30,"audio":true},{"de":"langsam","en":"slow","timeLimit":30,"audio":true},{"de":"zwanzig","en":"twenty","timeLimit":30,"audio":true},{"de":"museum","en":"","timeLimit":30,"audio":true},{"de":"zimmer","en":"","timeLimit":30,"audio":true},{"de":"wichtig","en":"important","timeLimit":30,"audio":true},{"de":"sicher","en":"safe, certain","timeLimit":30,"audio":true},{"de":"dienstag","en":"","timeLimit":30,"audio":true},{"de":"sonntag","en":"","timeLimit":30,"audio":true},{"de":"garten","en":"","timeLimit":30,"audio":true},{"de":"freitag","en":"","timeLimit":30,"audio":true},{"de":"nachbar","en":"","timeLimit":30,"audio":true},{"de":"farbig","en":"colored","timeLimit":30,"audio":true},{"de":"jemand","en":"someone","timeLimit":30,"audio":true},{"de":"banane","en":"","timeLimit":30,"audio":true},{"de":"glücklich","en":"happy","timeLimit":30,"audio":true},{"de":"bruder","en":"","timeLimit":30,"audio":true},{"de":"dezember","en":"","timeLimit":30,"audio":true},{"de":"hübsch","en":"pretty","timeLimit":30,"audio":true},{"de":"dieser","en":"this","timeLimit":30,"audio":true},{"de":"niemand","en":"nobody","timeLimit":30,"audio":true},{"de":"schrank","en":"","timeLimit":30,"audio":true},{"de":"januar","en":"","timeLimit":30,"audio":true},{"de":"balkon","en":"","timeLimit":30,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 8",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"gepäck","en":"","timeLimit":30,"audio":true},{"de":"mutter","en":"","timeLimit":30,"audio":true},{"de":"dezember","en":"","timeLimit":30,"audio":true},{"de":"hotel","en":"","timeLimit":30,"audio":true},{"de":"fahrkarte","en":"","timeLimit":30,"audio":true},{"de":"freitag","en":"","timeLimit":30,"audio":true},{"de":"direkt","en":"direct, straight","timeLimit":30,"audio":true},{"de":"kellner","en":"","timeLimit":30,"audio":true},{"de":"computer","en":"","timeLimit":30,"audio":true},{"de":"kirche","en":"","timeLimit":30,"audio":true},{"de":"schule","en":"","timeLimit":30,"audio":true},{"de":"freundin","en":"","timeLimit":30,"audio":true},{"de":"montag","en":"","timeLimit":30,"audio":true},{"de":"reise","en":"","timeLimit":30,"audio":true},{"de":"richtig","en":"correct, right","timeLimit":30,"audio":true},{"de":"wichtig","en":"important","timeLimit":30,"audio":true},{"de":"frisch","en":"fresh","timeLimit":30,"audio":true},{"de":"museum","en":"","timeLimit":30,"audio":true},{"de":"kartoffel","en":"","timeLimit":30,"audio":true},{"de":"einzeln","en":"single, separate","timeLimit":30,"audio":true},{"de":"april","en":"","timeLimit":30,"audio":true},{"de":"orange","en":"","timeLimit":30,"audio":true},{"de":"spiegel","en":"","timeLimit":30,"audio":true},{"de":"notwendig","en":"necessary","timeLimit":30,"audio":true},{"de":"september","en":"","timeLimit":30,"audio":true}],
        },

      ],
    },

    {
      id: "nine-words-3",
      title: "Level 3: Long words",
      rounds: [
        {
          kind: "scramble",
          title: "Round 1",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"Supermarkt","en":"the supermarket","timeLimit":40,"audio":true},{"de":"Samstagnachmittag","en":"","timeLimit":40,"audio":true},{"de":"Jahreszeit","en":"","timeLimit":40,"audio":true},{"de":"Gutenacht","en":"","timeLimit":40,"audio":true},{"de":"Brille","en":"the glasses","timeLimit":40,"audio":true},{"de":"Universität","en":"the university","timeLimit":40,"audio":true},{"de":"Schularbeit","en":"","timeLimit":40,"audio":true},{"de":"Jacke","en":"the jacket","timeLimit":40,"audio":true},{"de":"verschieden","en":"different, various","timeLimit":40,"audio":true},{"de":"Hose","en":"the pants, the trousers","timeLimit":40,"audio":true},{"de":"Geschäft","en":"the shop","timeLimit":40,"audio":true},{"de":"Schmetterling","en":"the butterfly","timeLimit":40,"audio":true},{"de":"Straßenbahn","en":"the tram","timeLimit":40,"audio":true},{"de":"Montagmorgen","en":"","timeLimit":40,"audio":true},{"de":"Gutenmorgen","en":"","timeLimit":40,"audio":true},{"de":"Eiscreme","en":"","timeLimit":40,"audio":true},{"de":"Regenbogen","en":"the rainbow","timeLimit":40,"audio":true},{"de":"Geburtstag","en":"the birthday","timeLimit":40,"audio":true},{"de":"Einkaufen","en":"","timeLimit":40,"audio":true},{"de":"Socken","en":"","timeLimit":40,"audio":true},{"de":"Schokolade","en":"the chocolate","timeLimit":40,"audio":true},{"de":"Zeitung","en":"the newspaper","timeLimit":40,"audio":true},{"de":"Kleid","en":"the dress","timeLimit":40,"audio":true},{"de":"Haltestelle","en":"the stop","timeLimit":40,"audio":true},{"de":"Banane","en":"the banana","timeLimit":40,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 2",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"Jacke","en":"the jacket","timeLimit":40,"audio":true},{"de":"gemeinsam","en":"together, joint","timeLimit":40,"audio":true},{"de":"Mittagessen","en":"the lunch","timeLimit":40,"audio":true},{"de":"Zeitung","en":"the newspaper","timeLimit":40,"audio":true},{"de":"Geburtstag","en":"the birthday","timeLimit":40,"audio":true},{"de":"Schlafzimmer","en":"the bedroom","timeLimit":40,"audio":true},{"de":"Arbeitszimmer","en":"","timeLimit":40,"audio":true},{"de":"Lieblingsbuch","en":"","timeLimit":40,"audio":true},{"de":"Krankenhaus","en":"the hospital","timeLimit":40,"audio":true},{"de":"Samstagnachmittag","en":"","timeLimit":40,"audio":true},{"de":"Entschuldigung","en":"","timeLimit":40,"audio":true},{"de":"Nebensatz","en":"","timeLimit":40,"audio":true},{"de":"Hausschuhe","en":"the slippers","timeLimit":40,"audio":true},{"de":"kompliziert","en":"complicated","timeLimit":40,"audio":true},{"de":"Krankenwagen","en":"","timeLimit":40,"audio":true},{"de":"glücklich","en":"happy","timeLimit":40,"audio":true},{"de":"Schokolade","en":"the chocolate","timeLimit":40,"audio":true},{"de":"Abendessen","en":"the dinner","timeLimit":40,"audio":true},{"de":"europäisch","en":"European","timeLimit":40,"audio":true},{"de":"Schreibtisch","en":"the desk","timeLimit":40,"audio":true},{"de":"Jahreszeit","en":"","timeLimit":40,"audio":true},{"de":"Sonnenuntergang","en":"the sunset","timeLimit":40,"audio":true},{"de":"Bahnhofstraße","en":"","timeLimit":40,"audio":true},{"de":"Bundesland","en":"","timeLimit":40,"audio":true},{"de":"Freitagabend","en":"","timeLimit":40,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 3",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"Kleid","en":"the dress","timeLimit":40,"audio":true},{"de":"Rechnung","en":"the bill, the invoice","timeLimit":40,"audio":true},{"de":"Bücherregal","en":"the bookshelf","timeLimit":40,"audio":true},{"de":"glücklich","en":"happy","timeLimit":40,"audio":true},{"de":"Zeitung","en":"the newspaper","timeLimit":40,"audio":true},{"de":"Sonnenuntergang","en":"the sunset","timeLimit":40,"audio":true},{"de":"Krankenwagen","en":"","timeLimit":40,"audio":true},{"de":"kompliziert","en":"complicated","timeLimit":40,"audio":true},{"de":"Wochenende","en":"the weekend","timeLimit":40,"audio":true},{"de":"Hausschuhe","en":"the slippers","timeLimit":40,"audio":true},{"de":"neugierig","en":"curious","timeLimit":40,"audio":true},{"de":"Speisekarte","en":"the menu","timeLimit":40,"audio":true},{"de":"europäisch","en":"European","timeLimit":40,"audio":true},{"de":"zufrieden","en":"satisfied, content","timeLimit":40,"audio":true},{"de":"Arbeitszimmer","en":"","timeLimit":40,"audio":true},{"de":"Bücherregal","en":"the bookshelf","timeLimit":40,"audio":true},{"de":"Eiscreme","en":"","timeLimit":40,"audio":true},{"de":"Freitagabend","en":"","timeLimit":40,"audio":true},{"de":"Supermarkt","en":"the supermarket","timeLimit":40,"audio":true},{"de":"Apotheke","en":"the pharmacy","timeLimit":40,"audio":true},{"de":"Haltestelle","en":"the stop","timeLimit":40,"audio":true},{"de":"Entschuldigung","en":"","timeLimit":40,"audio":true},{"de":"Sonnenbrille","en":"","timeLimit":40,"audio":true},{"de":"Einkauf","en":"the shopping","timeLimit":40,"audio":true},{"de":"Geburtstag","en":"the birthday","timeLimit":40,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 4",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"Mütze","en":"the cap","timeLimit":40,"audio":true},{"de":"Bücherregal","en":"the bookshelf","timeLimit":40,"audio":true},{"de":"Polizei","en":"the police","timeLimit":40,"audio":true},{"de":"Wochenende","en":"the weekend","timeLimit":40,"audio":true},{"de":"freundlich","en":"friendly","timeLimit":40,"audio":true},{"de":"Tomate","en":"the tomato","timeLimit":40,"audio":true},{"de":"beruflich","en":"professional, work-related","timeLimit":40,"audio":true},{"de":"unbekannt","en":"unknown","timeLimit":40,"audio":true},{"de":"Hauptsatz","en":"","timeLimit":40,"audio":true},{"de":"Entschuldigung","en":"","timeLimit":40,"audio":true},{"de":"italienisch","en":"Italian","timeLimit":40,"audio":true},{"de":"Universität","en":"the university","timeLimit":40,"audio":true},{"de":"Sonnenaufgang","en":"the sunrise","timeLimit":40,"audio":true},{"de":"Supermarkt","en":"the supermarket","timeLimit":40,"audio":true},{"de":"automatisch","en":"automatic","timeLimit":40,"audio":true},{"de":"Pullover","en":"the sweater","timeLimit":40,"audio":true},{"de":"Apotheke","en":"the pharmacy","timeLimit":40,"audio":true},{"de":"Frühstück","en":"the breakfast","timeLimit":40,"audio":true},{"de":"Samstagnachmittag","en":"","timeLimit":40,"audio":true},{"de":"Hose","en":"the pants, the trousers","timeLimit":40,"audio":true},{"de":"Zeitschrift","en":"the magazine","timeLimit":40,"audio":true},{"de":"Schneemann","en":"","timeLimit":40,"audio":true},{"de":"langweilig","en":"boring","timeLimit":40,"audio":true},{"de":"Bibliothek","en":"the library","timeLimit":40,"audio":true},{"de":"Straßenbahn","en":"the tram","timeLimit":40,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 5",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"Orange","en":"the orange (fruit)","timeLimit":40,"audio":true},{"de":"Sonnenuntergang","en":"the sunset","timeLimit":40,"audio":true},{"de":"Hauptsatz","en":"","timeLimit":40,"audio":true},{"de":"Haltestelle","en":"the stop","timeLimit":40,"audio":true},{"de":"Wohnzimmer","en":"the living room","timeLimit":40,"audio":true},{"de":"Montagmorgen","en":"","timeLimit":40,"audio":true},{"de":"Zusammensetzung","en":"","timeLimit":40,"audio":true},{"de":"Polizei","en":"the police","timeLimit":40,"audio":true},{"de":"Schulfach","en":"","timeLimit":40,"audio":true},{"de":"Sonnenaufgang","en":"the sunrise","timeLimit":40,"audio":true},{"de":"Wiedersehen","en":"","timeLimit":40,"audio":true},{"de":"Hose","en":"the pants, the trousers","timeLimit":40,"audio":true},{"de":"Wintermantel","en":"","timeLimit":40,"audio":true},{"de":"Straßenbahn","en":"the tram","timeLimit":40,"audio":true},{"de":"Jahreszeit","en":"","timeLimit":40,"audio":true},{"de":"Apfelkuchen","en":"the apple cake","timeLimit":40,"audio":true},{"de":"Eiscreme","en":"","timeLimit":40,"audio":true},{"de":"Geschäft","en":"the shop","timeLimit":40,"audio":true},{"de":"Schlafzimmer","en":"the bedroom","timeLimit":40,"audio":true},{"de":"Krankenhaus","en":"the hospital","timeLimit":40,"audio":true},{"de":"Hausaufgaben","en":"the homework","timeLimit":40,"audio":true},{"de":"Bahnhofstraße","en":"","timeLimit":40,"audio":true},{"de":"Fahrkarte","en":"the ticket","timeLimit":40,"audio":true},{"de":"zufrieden","en":"satisfied, content","timeLimit":40,"audio":true},{"de":"Straßenbahn","en":"the tram","timeLimit":40,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 6",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"Jahreszeit","en":"","timeLimit":40,"audio":true},{"de":"Hausaufgaben","en":"the homework","timeLimit":40,"audio":true},{"de":"U-Bahn","en":"the underground","timeLimit":40,"audio":true},{"de":"Lieblingsbuch","en":"","timeLimit":40,"audio":true},{"de":"Gutenacht","en":"","timeLimit":40,"audio":true},{"de":"Gutenmorgen","en":"","timeLimit":40,"audio":true},{"de":"Fahrkarte","en":"the ticket","timeLimit":40,"audio":true},{"de":"Rechnung","en":"the bill, the invoice","timeLimit":40,"audio":true},{"de":"Geschwister","en":"the siblings","timeLimit":40,"audio":true},{"de":"Entschuldigung","en":"","timeLimit":40,"audio":true},{"de":"Schulfach","en":"","timeLimit":40,"audio":true},{"de":"Wohnzimmer","en":"the living room","timeLimit":40,"audio":true},{"de":"japanisch","en":"Japanese","timeLimit":40,"audio":true},{"de":"Schlafzimmer","en":"the bedroom","timeLimit":40,"audio":true},{"de":"Hausaufgaben","en":"the homework","timeLimit":40,"audio":true},{"de":"Polizei","en":"the police","timeLimit":40,"audio":true},{"de":"Schlafzimmer","en":"the bedroom","timeLimit":40,"audio":true},{"de":"Krankenwagen","en":"","timeLimit":40,"audio":true},{"de":"Mittagessen","en":"the lunch","timeLimit":40,"audio":true},{"de":"willkommen","en":"welcome","timeLimit":40,"audio":true},{"de":"Einkauf","en":"the shopping","timeLimit":40,"audio":true},{"de":"Spülmaschine","en":"","timeLimit":40,"audio":true},{"de":"Lieblingsessen","en":"","timeLimit":40,"audio":true},{"de":"interessant","en":"interesting","timeLimit":40,"audio":true},{"de":"Freitagabend","en":"","timeLimit":40,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 7",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"glücklich","en":"happy","timeLimit":40,"audio":true},{"de":"Bücherregal","en":"the bookshelf","timeLimit":40,"audio":true},{"de":"gemeinsam","en":"together, joint","timeLimit":40,"audio":true},{"de":"Geschirrspüler","en":"","timeLimit":40,"audio":true},{"de":"Krankenhaus","en":"the hospital","timeLimit":40,"audio":true},{"de":"Wiedersehen","en":"","timeLimit":40,"audio":true},{"de":"kompliziert","en":"complicated","timeLimit":40,"audio":true},{"de":"unglaublich","en":"unbelievable","timeLimit":40,"audio":true},{"de":"interessant","en":"interesting","timeLimit":40,"audio":true},{"de":"Sonnenaufgang","en":"the sunrise","timeLimit":40,"audio":true},{"de":"Krankenhaus","en":"the hospital","timeLimit":40,"audio":true},{"de":"Schmetterling","en":"the butterfly","timeLimit":40,"audio":true},{"de":"notwendig","en":"necessary","timeLimit":40,"audio":true},{"de":"Polizeistation","en":"","timeLimit":40,"audio":true},{"de":"japanisch","en":"Japanese","timeLimit":40,"audio":true},{"de":"Zugticket","en":"","timeLimit":40,"audio":true},{"de":"Zusammensetzung","en":"","timeLimit":40,"audio":true},{"de":"Freitagabend","en":"","timeLimit":40,"audio":true},{"de":"Straßenbahn","en":"the tram","timeLimit":40,"audio":true},{"de":"Polizei","en":"the police","timeLimit":40,"audio":true},{"de":"Entschuldigung","en":"","timeLimit":40,"audio":true},{"de":"Orange","en":"the orange (fruit)","timeLimit":40,"audio":true},{"de":"Hauptsatz","en":"","timeLimit":40,"audio":true},{"de":"Geburtstag","en":"the birthday","timeLimit":40,"audio":true},{"de":"Schulfach","en":"","timeLimit":40,"audio":true}],
        },
        {
          kind: "scramble",
          title: "Round 8",
          instruction: "Tap the letter tiles to spell the word. Beat the clock!",
          items: [{"de":"Schlafzimmer","en":"the bedroom","timeLimit":40,"audio":true},{"de":"Bahnhofstraße","en":"","timeLimit":40,"audio":true},{"de":"zufrieden","en":"satisfied, content","timeLimit":40,"audio":true},{"de":"Handschuhe","en":"the gloves","timeLimit":40,"audio":true},{"de":"Banane","en":"the banana","timeLimit":40,"audio":true},{"de":"Zeitschrift","en":"the magazine","timeLimit":40,"audio":true},{"de":"neugierig","en":"curious","timeLimit":40,"audio":true},{"de":"Hausschuhe","en":"the slippers","timeLimit":40,"audio":true},{"de":"Regenjacke","en":"the rain jacket","timeLimit":40,"audio":true},{"de":"Gutenabend","en":"","timeLimit":40,"audio":true},{"de":"Jahreszeit","en":"","timeLimit":40,"audio":true},{"de":"Hose","en":"the pants, the trousers","timeLimit":40,"audio":true},{"de":"Montagmorgen","en":"","timeLimit":40,"audio":true},{"de":"Sonnenaufgang","en":"the sunrise","timeLimit":40,"audio":true},{"de":"Krankenwagen","en":"","timeLimit":40,"audio":true},{"de":"Krankenhaus","en":"the hospital","timeLimit":40,"audio":true},{"de":"Gebäude","en":"the building","timeLimit":40,"audio":true},{"de":"Zugticket","en":"","timeLimit":40,"audio":true},{"de":"Wochenende","en":"the weekend","timeLimit":40,"audio":true},{"de":"Polizei","en":"the police","timeLimit":40,"audio":true},{"de":"Frühstück","en":"the breakfast","timeLimit":40,"audio":true},{"de":"Straßenbahn","en":"the tram","timeLimit":40,"audio":true},{"de":"Kleid","en":"the dress","timeLimit":40,"audio":true},{"de":"beruflich","en":"professional, work-related","timeLimit":40,"audio":true},{"de":"Gutenmorgen","en":"","timeLimit":40,"audio":true}],
        },

      ],
    },
  ],
};


export const wordmatchgridGame: Game = {
  id: "word-match-grid",
  title: "Word Match Grid",
  emoji: "🔗",
  description: "Tap matching German and English tiles in a single grid to clear the board. Beat the clock across rounds that get faster each time!",
  category: "vocabulary",
  tags: ["A1","A2"],
  levels: [
    {
      id: "grid-match-1",
      title: "Level 1: Nouns",
      rounds: [
        {
          kind: "grid-match",
          title: "Grid 1",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["der Delfin","the dolphin"],["das Zentrum","the centre"],["das Feld","the field"],["der Gürtel","the belt"],["das Toilettenpapier","the toilet paper"],["der Bau","the building site"],["die Nummer","the number"],["die Stunde","the hour, the lesson"],["der Rand","the edge"],["die Katze","the cat"]],
        },
        {
          kind: "grid-match",
          title: "Grid 2",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["das Reich","the empire, the realm"],["die Plastiktüte","the plastic bag"],["die Cola","the cola"],["die Politik","the politics"],["die Pizza","the pizza"],["das Ticket","the ticket"],["der Stadtführer","the city guide"],["die Nase","the nose"],["die Kreuzung","the crossing, the junction"],["der Stadtbezirk","the district"]],
        },
        {
          kind: "grid-match",
          title: "Grid 3",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["das Metall","the metal"],["der Friedhof","the cemetery"],["die Verwandten","the relatives"],["der Einkaufskorb","the shopping basket"],["der Finger","the finger"],["der Gürtel","the belt"],["das Orchester","the orchestra"],["der Stadtführer","the city guide"],["das Fernsehprogramm","the TV schedule"],["die Flüssigkeit","the liquid"]],
        },
        {
          kind: "grid-match",
          title: "Grid 4",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["der Kellner","the waiter"],["der Zoo","the zoo"],["das Hemd","the shirt"],["das Fahrrad","the bicycle"],["das Viertel","the quarter"],["der Stadtbezirk","the district"],["das Reich","the empire, the realm"],["die Katze","the cat"],["die Kreuzung","the crossing, the junction"],["die Tankstelle","the petrol station"]],
        },
        {
          kind: "grid-match",
          title: "Grid 5",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["das Gesicht","the face"],["das Zentrum","the centre"],["der Ofen","the oven, the stove"],["das Hochhaus","the high-rise building"],["die Natur","the nature"],["die Plastiktüte","the plastic bag"],["die Nummer","the number"],["der Kaufmann","the merchant"],["die Bewerbung","the application"],["die Politik","the politics"]],
        },
        {
          kind: "grid-match",
          title: "Grid 6",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["der Rücken","the back"],["die Zitrone","the lemon"],["die Mülltonne","the dustbin"],["der Kaufmann","the merchant"],["das Reich","the empire, the realm"],["die Nase","the nose"],["das Feld","the field"],["die Birne","the pear"],["die Erkältung","the cold"],["das Gesicht","the face"]],
        },
        {
          kind: "grid-match",
          title: "Grid 7",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["das Hemd","the shirt"],["die Imbissbude","the snack stand"],["das Zentrum","the centre"],["die Papiertüte","the paper bag"],["der Rand","the edge"],["der Stadtbezirk","the district"],["die Landschaft","the landscape"],["das Ticket","the ticket"],["die Cola","the cola"],["der Krieg","the war"]],
        },
        {
          kind: "grid-match",
          title: "Grid 8",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["die Nummer","the number"],["die Bewerbung","the application"],["die Zeit","the time"],["das Reich","the empire, the realm"],["die Politik","the politics"],["der Topf","the pot"],["das Gesicht","the face"],["das Orchester","the orchestra"],["der Finger","the finger"],["das Bäumchen","the little tree"]],
        },
        {
          kind: "grid-match",
          title: "Grid 9",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["das Feld","the field"],["der Metzger","the butcher"],["der Geschäftsführer","the managing director"],["der Partner","the partner (m.)"],["die Kreuzung","the crossing, the junction"],["der Norden","the north"],["der Regenschirm","the umbrella"],["das Fernsehprogramm","the TV schedule"],["der Gürtel","the belt"],["der Acker","the farmland"]],
        },
        {
          kind: "grid-match",
          title: "Grid 10",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["der Stammgast","the regular"],["die Zeit","the time"],["der Finger","the finger"],["das Werkzeug","the tool"],["der Delfin","the dolphin"],["das Zebra","the zebra"],["die Imbissbude","the snack stand"],["der Ofen","the oven, the stove"],["der Kellner","the waiter"],["die Stunde","the hour, the lesson"]],
        },
        {
          kind: "grid-match",
          title: "Grid 11",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["die Landschaft","the landscape"],["der Einkaufskorb","the shopping basket"],["der Friedhof","the cemetery"],["der Gürtel","the belt"],["die Flüssigkeit","the liquid"],["das Glück","the luck"],["der Acker","the farmland"],["der Stadtbezirk","the district"],["die Birne","the pear"],["der Rand","the edge"]],
        },
        {
          kind: "grid-match",
          title: "Grid 12",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["das Bäumchen","the little tree"],["die Tankstelle","the petrol station"],["die Landschaft","the landscape"],["die Plastiktüte","the plastic bag"],["der Balkon","the balcony"],["die Nummer","the number"],["die Einkaufstasche","the shopping bag"],["der Eintopf","the stew"],["das Toilettenpapier","the toilet paper"],["die Stunde","the hour, the lesson"]],
        },
        {
          kind: "grid-match",
          title: "Grid 13",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["der Topf","the pot"],["der Regenschirm","the umbrella"],["das Fahrrad","the bicycle"],["die Rezeption","the reception"],["die Natur","the nature"],["der Stammgast","the regular"],["das Sprechzimmer","the consultation room"],["der Cousin","the cousin (male)"],["das Reich","the empire, the realm"],["die Verwandten","the relatives"]],
        },
        {
          kind: "grid-match",
          title: "Grid 14",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["das Bäumchen","the little tree"],["der Rücken","the back"],["die Landschaft","the landscape"],["die Erkältung","the cold"],["der Geschäftsführer","the managing director"],["die Nase","the nose"],["die Gebühr","the fee"],["der Schauspieler","the actor"],["der Kaufmann","the merchant"],["die Bucht","the bay"]],
        },
        {
          kind: "grid-match",
          title: "Grid 15",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["das Viertel","the quarter"],["die Zeit","the time"],["der Zoo","the zoo"],["der Topf","the pot"],["das Orchester","the orchestra"],["der Balkon","the balcony"],["das Fahrrad","the bicycle"],["das Gesicht","the face"],["der Stadtführer","the city guide"],["der Rand","the edge"]],
        },
        {
          kind: "grid-match",
          title: "Grid 16",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["das Hemd","the shirt"],["die Natur","the nature"],["der Rand","the edge"],["die Mülltonne","the dustbin"],["der Stammgast","the regular"],["die Straßenbahn","the tram"],["der Fahrer","the driver"],["das Reich","the empire, the realm"],["das Bäumchen","the little tree"],["die Pizza","the pizza"]],
        },
        {
          kind: "grid-match",
          title: "Grid 17",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["die Rezeption","the reception"],["die Nummer","the number"],["die Bucht","the bay"],["das Bäumchen","the little tree"],["die Cola","the cola"],["der Acker","the farmland"],["der Partner","the partner (m.)"],["die See","the sea"],["der Rand","the edge"],["der Kindergarten","the kindergarten"]],
        },
        {
          kind: "grid-match",
          title: "Grid 18",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["der Schalter","the counter"],["die Flüssigkeit","the liquid"],["das Apartment","the apartment"],["die Kreuzung","the crossing, the junction"],["der Einkaufskorb","the shopping basket"],["die Rezeption","the reception"],["die Suppenschüssel","the soup bowl"],["der Fahrer","the driver"],["das Ticket","the ticket"],["die Mülltonne","the dustbin"]],
        },
        {
          kind: "grid-match",
          title: "Grid 19",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["die Mülltonne","the dustbin"],["der Vulkan","the volcano"],["der Welpe","the puppy"],["der Stadtführer","the city guide"],["die Flüssigkeit","the liquid"],["das Metall","the metal"],["das Hochhaus","the high-rise building"],["die Cola","the cola"],["der Cousin","the cousin (male)"],["der Einkaufskorb","the shopping basket"]],
        },
        {
          kind: "grid-match",
          title: "Grid 20",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 45,
          pairs: [["die Einkaufstasche","the shopping bag"],["der Metzger","the butcher"],["das Ticket","the ticket"],["die Lampe","the lamp"],["die Speisekarte","the menu"],["die Straßenbahn","the tram"],["die Politik","the politics"],["die Welle","the wave"],["die Suppenschüssel","the soup bowl"],["der Zoo","the zoo"]],
        },

      ],
    },

    {
      id: "grid-match-2",
      title: "Level 2: More nouns",
      rounds: [
        {
          kind: "grid-match",
          title: "Grid 1",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["der Spatz","the sparrow"],["der Arbeitsvertrag","the employment contract"],["die Mode","the fashion"],["die Freizeitbeschäftigung","the leisure activity"],["die Noten","the grades"],["der Professor","the professor"],["die Turnschuhe","the trainers"],["die Höhle","the cave"],["die Polizeiwache","the police station"],["der Ofen","the oven, the stove"]],
        },
        {
          kind: "grid-match",
          title: "Grid 2",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["das Frühstücksbüfett","the breakfast buffet"],["der Ofen","the oven, the stove"],["die Mahlzeit","the meal"],["der Herbst","the autumn"],["die Bluse","the blouse"],["die Turnschuhe","the trainers"],["die Imbissbude","the snack stand"],["der Elefant","the elephant"],["die Marmelade","the jam"],["die Fahrkarte","the ticket"]],
        },
        {
          kind: "grid-match",
          title: "Grid 3",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["der BH","the bra"],["das Datum","the date"],["die Krankschreibung","the sick note"],["der Elefant","the elephant"],["das Kinn","the chin"],["der Krankenstand","the sick leave"],["der Weg","the way, the path"],["der Ofen","the oven, the stove"],["die Stadtmauer","the city wall"],["das Schwimmen","the swimming"]],
        },
        {
          kind: "grid-match",
          title: "Grid 4",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["der Weg","the way, the path"],["der Elefant","the elephant"],["die Bluse","the blouse"],["die Münze","the coin"],["die Miete","the rent"],["die Stelle","the place, the position"],["der Ofen","the oven, the stove"],["der Fehler","the mistake"],["die CD","the CD"],["die Freizeitbeschäftigung","the leisure activity"]],
        },
        {
          kind: "grid-match",
          title: "Grid 5",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["die Münze","the coin"],["die Untersuchung","the examination"],["die Stufe","the step"],["die Eule","the owl"],["die Hochschule","the college"],["der Bäcker","the baker"],["die Arbeit","the work, the job"],["die Krankschreibung","the sick note"],["die Leber","the liver"],["der Spatz","the sparrow"]],
        },
        {
          kind: "grid-match",
          title: "Grid 6",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["der Ellbogen","the elbow"],["der Computer","the computer"],["die Rückfahrkarte","the return ticket"],["das Restaurant","the restaurant"],["der Lehrer","the teacher (male)"],["der Ordner","the folder"],["die Brosche","the brooch"],["das Tal","the valley"],["die Stelle","the place, the position"],["die Polizeiwache","the police station"]],
        },
        {
          kind: "grid-match",
          title: "Grid 7",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["die Antwort","the answer"],["die Miete","the rent"],["der Vater","the father"],["die Liebe","the love"],["der Krankenstand","the sick leave"],["der Einkaufskorb","the shopping basket"],["die Kneipe","the pub"],["der Rabatt","the discount"],["der Kurzfilm","the short film"],["der Arbeitskollege","the work colleague"]],
        },
        {
          kind: "grid-match",
          title: "Grid 8",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["die Kneipe","the pub"],["die Bäckerei","the bakery"],["die Leber","the liver"],["die Brosche","the brooch"],["das Abendessen","the dinner"],["die Polizeiwache","the police station"],["die Zitrone","the lemon"],["die Rückfahrkarte","the return ticket"],["der Computer","the computer"],["die Großmutter","the grandmother"]],
        },
        {
          kind: "grid-match",
          title: "Grid 9",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["der Lehrer","the teacher (male)"],["die Reservierung","the reservation"],["das Tal","the valley"],["die Präsentation","the presentation"],["der Krankenstand","the sick leave"],["das Menü","the set menu"],["die Zitrone","the lemon"],["die Höhle","the cave"],["die Stadtmauer","the city wall"],["die Noten","the grades"]],
        },
        {
          kind: "grid-match",
          title: "Grid 10",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["der Kohl","the cabbage"],["die Großmutter","the grandmother"],["der Drehbuchautor","the screenwriter"],["der Umtausch","the exchange"],["das Obst","the fruit"],["der Krankenstand","the sick leave"],["der Rabatt","the discount"],["die Zitrone","the lemon"],["der Anfang","the beginning"],["die Reservierung","the reservation"]],
        },
        {
          kind: "grid-match",
          title: "Grid 11",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["die Turnschuhe","the trainers"],["die Fantasie","the imagination"],["die Leber","the liver"],["die Eule","the owl"],["die CD","the CD"],["das Kinn","the chin"],["die Großmutter","the grandmother"],["der Kurzfilm","the short film"],["das Datum","the date"],["der Arbeitsvertrag","the employment contract"]],
        },
        {
          kind: "grid-match",
          title: "Grid 12",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["die Liebe","the love"],["die Stelle","the place, the position"],["der Ellbogen","the elbow"],["die Tracht","the traditional dress"],["die Turnschuhe","the trainers"],["der Dachboden","the attic"],["das Obst","the fruit"],["der Donnerstag","Thursday"],["die Kneipe","the pub"],["die Hochschule","the college"]],
        },
        {
          kind: "grid-match",
          title: "Grid 13",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["die Kneipe","the pub"],["der Kohl","the cabbage"],["der Lehrer","the teacher (male)"],["das Schwimmbad","the swimming pool"],["die CD","the CD"],["die Zitrone","the lemon"],["die Bäckerei","the bakery"],["der Fehler","the mistake"],["der Professor","the professor"],["die Bettdecke","the duvet"]],
        },
        {
          kind: "grid-match",
          title: "Grid 14",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["der Kurzfilm","the short film"],["die Großmutter","the grandmother"],["die Arbeit","the work, the job"],["das Meerschweinchen","the guinea pig"],["der Vortrag","the lecture, the presentation"],["das Schwimmen","the swimming"],["der Ordner","the folder"],["das Gesicht","the face"],["der Einkaufskorb","the shopping basket"],["die Vorlesung","the lecture"]],
        },
        {
          kind: "grid-match",
          title: "Grid 15",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["die Tracht","the traditional dress"],["das Kinn","the chin"],["der Elefant","the elephant"],["der Kurzfilm","the short film"],["der Bahnhof","the train station"],["der Ellbogen","the elbow"],["das Meerschweinchen","the guinea pig"],["das Abendessen","the dinner"],["die Galerie","the gallery"],["das Restaurant","the restaurant"]],
        },
        {
          kind: "grid-match",
          title: "Grid 16",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["die Turnschuhe","the trainers"],["die CD","the CD"],["die Mode","the fashion"],["die Präsentation","the presentation"],["der Geburtstag","the birthday"],["die Antwort","the answer"],["die Untersuchung","the examination"],["die Operation","the operation"],["das Abteil","the compartment"],["der Frost","the frost"]],
        },
        {
          kind: "grid-match",
          title: "Grid 17",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["der Elefant","the elephant"],["die Marmelade","the jam"],["das Kinn","the chin"],["der Kohl","the cabbage"],["das Datum","the date"],["der Einkaufskorb","the shopping basket"],["die Turnschuhe","the trainers"],["das Frühstücksbüfett","the breakfast buffet"],["der Fehler","the mistake"],["die Leber","the liver"]],
        },
        {
          kind: "grid-match",
          title: "Grid 18",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["das Volksfest","the funfair"],["die Kneipe","the pub"],["das Abteil","the compartment"],["der Spatz","the sparrow"],["der Elefant","the elephant"],["der Dachboden","the attic"],["der Zahn","the tooth"],["die Bäckerei","the bakery"],["der Computer","the computer"],["der Kurzfilm","the short film"]],
        },
        {
          kind: "grid-match",
          title: "Grid 19",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["die Präsentation","the presentation"],["der Kurzfilm","the short film"],["der Dachboden","the attic"],["der Spatz","the sparrow"],["die Hochschule","the college"],["der Krankenstand","the sick leave"],["das Obst","the fruit"],["die Zitrone","the lemon"],["die Fantasie","the imagination"],["die Zutat","the ingredient"]],
        },
        {
          kind: "grid-match",
          title: "Grid 20",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 40,
          pairs: [["das Schwimmbad","the swimming pool"],["der Familienname","the surname"],["der BH","the bra"],["der Bäcker","the baker"],["die Tracht","the traditional dress"],["der Spatz","the sparrow"],["der Donnerstag","Thursday"],["die Baumwolle","the cotton"],["der Umtausch","the exchange"],["der Professor","the professor"]],
        },

      ],
    },

    {
      id: "grid-match-3",
      title: "Level 3: Longer words",
      rounds: [
        {
          kind: "grid-match",
          title: "Grid 1",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["die Kirmes","the fair"],["die Pfote","the paw"],["die Anprobe","the fitting"],["die Waschmaschine","the washing machine"],["der Abteilungsleiter","the department head"],["die Ameise","the ant"],["der Hahn","the rooster"],["der Anfang","the beginning"],["der Wein","the wine"],["das Dokument","the document"]],
        },
        {
          kind: "grid-match",
          title: "Grid 2",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["das Schwimmen","the swimming"],["der Sänger","the singer"],["der Autofahrer","the motorist"],["der Anfang","the beginning"],["die Milch","the milk"],["der Umzug","the move"],["der Snack","the snack"],["die Mode","the fashion"],["der Hahn","the rooster"],["der Fluss","the river"]],
        },
        {
          kind: "grid-match",
          title: "Grid 3",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["das Museum","the museum"],["das Benzin","the petrol"],["der Rand","the edge"],["der Gehweg","the pavement"],["die Pflanze","the plant"],["der Flohmarkt","the flea market"],["der Nebel","the fog"],["die Metzgerei","the butcher's"],["der Popmusik","the pop music"],["das Büro","the office"]],
        },
        {
          kind: "grid-match",
          title: "Grid 4",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["die Patientin","the patient (f.)"],["die Papiertüte","the paper bag"],["die Behandlung","the treatment"],["das Sofa","the sofa"],["der Füller","the fountain pen"],["die Reise","the journey, the trip"],["der Fluss","the river"],["die Mitbewohnerin","the flatmate (f.)"],["der Pinguin","the penguin"],["der Wind","the wind"]],
        },
        {
          kind: "grid-match",
          title: "Grid 5",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["der Popmusik","the pop music"],["der Tausch","the exchange, the swap"],["die Schokolade","the chocolate"],["der Geschäftsführer","the managing director"],["der Pinguin","the penguin"],["die Anprobe","the fitting"],["der Baum","the tree"],["das Auto","the car"],["der Strom","the electricity, the current"],["die Behandlung","the treatment"]],
        },
        {
          kind: "grid-match",
          title: "Grid 6",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["die Anprobe","the fitting"],["die Geschwindigkeitsbegrenzung","the speed limit"],["der Apfelkuchen","the apple cake"],["die Mitbewohnerin","the flatmate (f.)"],["der Ausverkauf","the sale"],["der Baum","the tree"],["der Wein","the wine"],["der Geschäftsführer","the managing director"],["die Schlange","the snake"],["der Knopf","the button"]],
        },
        {
          kind: "grid-match",
          title: "Grid 7",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["der Sektor","the sector"],["die Metzgerei","the butcher's"],["der Hahn","the rooster"],["das Büro","the office"],["der Strom","the electricity, the current"],["das Lied","the song"],["der Rettungswagen","the ambulance"],["die Stufe","the step"],["die Adresse","the address"],["der Anfang","the beginning"]],
        },
        {
          kind: "grid-match",
          title: "Grid 8",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["die Milch","the milk"],["die Schokolade","the chocolate"],["die Mode","the fashion"],["der Flohmarkt","the flea market"],["die Ameise","the ant"],["das Kinn","the chin"],["die Erbse","the pea"],["das Auto","the car"],["der Umzug","the move"],["die Reise","the journey, the trip"]],
        },
        {
          kind: "grid-match",
          title: "Grid 9",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["die Ente","the duck"],["die Erbse","the pea"],["die Patientin","the patient (f.)"],["der Staatsangehörige","the national"],["der Sektor","the sector"],["der Rettungswagen","the ambulance"],["die Leber","the liver"],["der Strom","the electricity, the current"],["das Museum","the museum"],["das Büro","the office"]],
        },
        {
          kind: "grid-match",
          title: "Grid 10",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["das Wasser","the water"],["der Norden","the north"],["der Anzug","the suit"],["die Ameise","the ant"],["der Baum","the tree"],["das Schwimmen","the swimming"],["der Wind","the wind"],["der Tausch","the exchange, the swap"],["das Benzin","the petrol"],["der Nachmittag","the afternoon"]],
        },
        {
          kind: "grid-match",
          title: "Grid 11",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["der Füller","the fountain pen"],["das Stadion","the stadium"],["die Kirmes","the fair"],["der Norden","the north"],["der Abteilungsleiter","the department head"],["die Milch","the milk"],["das Geburtsdatum","the date of birth"],["der Löwe","the lion"],["der Bericht","the report"],["das Waschbecken","the sink"]],
        },
        {
          kind: "grid-match",
          title: "Grid 12",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["der Norden","the north"],["das Waschbecken","the sink"],["der Hamster","the hamster"],["die Milch","the milk"],["das Kinn","the chin"],["das Ballett","the ballet"],["das Herz","the heart"],["der Hahn","the rooster"],["die Pflanze","the plant"],["die Reise","the journey, the trip"]],
        },
        {
          kind: "grid-match",
          title: "Grid 13",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["das Schwimmen","the swimming"],["der Garten","the garden"],["die Waschmaschine","the washing machine"],["der Hamster","the hamster"],["der Strom","the electricity, the current"],["das Sofa","the sofa"],["die Pfote","the paw"],["die Ente","the duck"],["die Mitbewohnerin","the flatmate (f.)"],["die Kirmes","the fair"]],
        },
        {
          kind: "grid-match",
          title: "Grid 14",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["die Straßenbahnlinie","the tram line"],["der Wein","the wine"],["der Mittag","the midday"],["das Hähnchen","the chicken"],["die Metzgerei","the butcher's"],["das Lied","the song"],["der Norden","the north"],["die Behandlung","the treatment"],["das Museum","the museum"],["der Nebel","the fog"]],
        },
        {
          kind: "grid-match",
          title: "Grid 15",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["der Anzug","the suit"],["die Ente","the duck"],["die Stadtmauer","the city wall"],["das Kostüm","the costume"],["die Kirmes","the fair"],["die Universität","the university"],["der Zug","the train"],["das Wasser","the water"],["der Popmusik","the pop music"],["die Mitbewohnerin","the flatmate (f.)"]],
        },
        {
          kind: "grid-match",
          title: "Grid 16",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["die Patientin","the patient (f.)"],["der Snack","the snack"],["die Musikrichtung","the music genre"],["das Gate","the gate"],["der Geschäftsführer","the managing director"],["die Landebahn","the runway"],["das Geburtsdatum","the date of birth"],["der Ausverkauf","the sale"],["die Milch","the milk"],["der Apfelkuchen","the apple cake"]],
        },
        {
          kind: "grid-match",
          title: "Grid 17",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["das Publikum","the audience"],["der Sonntag","Sunday"],["der Sänger","the singer"],["das Sofa","the sofa"],["der Tausch","the exchange, the swap"],["das Museum","the museum"],["der Rand","the edge"],["der Garten","the garden"],["die Einbahnstraße","the one-way street"],["die Stadtmauer","the city wall"]],
        },
        {
          kind: "grid-match",
          title: "Grid 18",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["die Mahlzeit","the meal"],["der Parkschein","the parking ticket"],["die Landebahn","the runway"],["das Sofa","the sofa"],["das Gate","the gate"],["das Museum","the museum"],["das Kostüm","the costume"],["die Mode","the fashion"],["die Leber","the liver"],["das Waschbecken","the sink"]],
        },
        {
          kind: "grid-match",
          title: "Grid 19",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["die Erbse","the pea"],["der Tausch","the exchange, the swap"],["der Ausverkauf","the sale"],["die Sportschau","the sports show"],["der Fluss","the river"],["das Auto","the car"],["der Bericht","the report"],["die Bar","the bar"],["die Papiertüte","the paper bag"],["die Metzgerei","the butcher's"]],
        },
        {
          kind: "grid-match",
          title: "Grid 20",
          instruction: "Tap a German word, then its English match.",
          timeLimit: 35,
          pairs: [["die Recycling","the recycling"],["die Schokolade","the chocolate"],["der Füller","the fountain pen"],["die Pflanze","the plant"],["der Sonntag","Sunday"],["der Geschäftsführer","the managing director"],["der Sektor","the sector"],["die Musikrichtung","the music genre"],["der Pinguin","the penguin"],["der Zug","the train"]],
        },

      ],
    },
  ],
};
